### ISSUE TITLE
Assassination mission adverts

### ISSUE THREAD

**Issue by Brianetta** [pioneerspacesim/pioneer#1012]
This image should speak for itself:
![Imgur](http://i.imgur.com/GUwGj.png)
I'm of the opinion that the advert part of the Assassinations mission should be completely rewritten. At the moment, when starting a new game, you have to wonder which dodgy part of LA you've found yourself in. I think it's unrealistic, in a system where things like piracy and murder are supposed to be a crime, to have such blatant adverts on the bulletin board.

Trouble is, a change to this mission will cause a bunch of translation work to need doing again. I'll put this on my list of scripting projects. I'm thinking of some sort of hit job broker system, where you approach the inconspicuous advertiser and they respond based on your notoriety, lawfulness, etc.

Thing is, before I get stuck in, I'd like to get some quick feedback about assassination mission adverts in general. What do people think it should look or feel like?

**Comment by Web-eWorks** [comment]
Thank you for the suggestion! Closing as unimplemented; feature requests and discussion should go on the [forum](https://pioneerspacesim.net/forum), as we use Github for tracking actively-developed features and issues with currently-implemented functionality.

**Comment by impaktor** [comment]
I've had my eyes on this issue for a number of years, as I had intended to close this with my Bar branch (TL;DR: illegal missions are picked up in the bar instead of the BBS + some more stuff). Oh well.
