### ISSUE TITLE
city shape

### ISSUE THREAD

**Issue by gernot66** [pioneerspacesim/pioneer#1026]
how to start?

i don't know actualy hows the ongoing with the city shape, especially if we have the tags back working for "city", "starport" and "power".
but i know what we had before and i've played a good old frontier for a while.
what i noticed was that the regions for such types of buildings are wider spread in frontier.
or to show better in little pics

pioneer (last state before disabling of building tags)
![fig_a](http://i790.photobucket.com/albums/yy187/potsmoke66/help/fig_a.jpg)
while s means all startport buildings incl. the starport, city simply means tagged "city bld." and power reflects "city power"
anyway the regions have overlayed each other by most part.

when i look at the cities in frontier the look more like this
![fig_b](http://i790.photobucket.com/albums/yy187/potsmoke66/help/fig_b.jpg)
the starport stands usually alone and groups like city bld., industry or suburban regions are gathered together overlaying each other only slightly and keeping the starport always off the center of the city.

this just to invoke some ideas

**Comment by nozmajner** [comment]
Closing, due to image url's are borken, and without them the city generator needs quite more detailed and planned out love in general.
