### ISSUE TITLE
Ordering of planets on planetary system page

### ISSUE THREAD

**Issue by Thargoid** [pioneerspacesim/pioneer#1052]
Eta Cassiopeia (and others) display the planets down the page, i.e through the writing which details the trade details and demographics.  Is that intentional? I thought it should be across the page like the other systems.

Not sure if its a bug and people probably already know about it, but submitted just in case

**Comment by Web-eWorks** [comment]
Closing this issue as no longer relevant; we will be replacing the legacy SystemInfoView with a pigui-based replacement very soon.
