### ISSUE TITLE
Music crossfade doesn't work anymore

### ISSUE THREAD

**Issue by robn** [pioneerspacesim/pioneer#1057]
Maybe. The last time I had sound on, months ago, I thought I noticed that the music abruptly switched instead of fading nicely. I keep forgetting to check it though.

**Comment by joonicks** [comment]
this issue?

start on earth
music turned on
time accelerate maximum
wait for a "ship close" alert.
it kills the music instantly, blipps, then starts playing a new music track.

pioneer-20171001-win32
