### ISSUE TITLE
Crash reporting

### ISSUE THREAD

**Issue by robn** [pioneerspacesim/pioneer#1059]
It might be useful to integrate a crash reporting system like [breakpad](http://code.google.com/p/google-breakpad/). At its simplest it could just drop a dump file into the userdir. More advanced would upload it somewhere.

**Comment by impaktor** [comment]
As described in #3211 this has been implemented for Windows, but not Linux/OSX, which are still left to
do.

**Comment by impaktor** [comment]
This issue is superseded by #3690  --> closing.
