### ISSUE TITLE
Collision detected as crime, many times

### ISSUE THREAD

**Issue by Brianetta** [pioneerspacesim/pioneer#1070]
Colliding with another space craft, done properly, results in what seems to be one crime for every frame spent in collision. I spawned a ship and accidentally ran into it. We were both OK, and the police were on their way to kill me (as is their wont). Unfortunately, the station spent the next quarter of an hour repeatedly messaging me to tell me that "Piracey cannot be tolerated here," even after the police had lost interest and I was trying to fly somewhere.

The fine was $14717.46 and, in fact, as I type I'm still waiting for the station to run out of UI.Messages for me.

Talk about hammering the point home...

**Comment by Web-eWorks** [comment]
This is no longer an issue with the Lua-based law system (implemented many years ago).
