### ISSUE TITLE
Ambient sound errors

### ISSUE THREAD

**Issue by Divarin** [pioneerspacesim/pioneer#1097]
After experiencing this I found Issue #47 which looks similar but that issue was closed. 
Landed on earth (on the surface, not a space port)
Ambient sound of thunder plays
Take off, hyperspace.. sound continues
sound keeps playing until I dock at a space station.
now all space station ambient sounds are missing.
this behavior continues even after saving, closing, restarting, reloading
in a new game space station ambient sounds are there, in the save game they are not.

If it helps I can provide the save game file.

**Comment by richardpl** [comment]
Should be fixed.
