### ISSUE TITLE
Scientific Missions

### ISSUE THREAD

**Issue by Styggron** [pioneerspacesim/pioneer#1127]
I was inspired by a post Uxi made on SSC and thought Scientific missions would truly be fantastic and uniqie in pioneer. Other users in the Frontier forums have great ideas as well I have mentioned them here as well.

Would be a great feature request that would open up a whole new aspect of the game.

Here were my thoughts.

Scientific Missions
-Ones where you need to chart planets some of all in a system.
-There could be a general database and your charting could add to the database and raise money for you.

It would not be just fly there, you would need equip to "detect" the fact something is there so you can fly _to_ it. Maybe a different coloured sector on the map etc

You would need to do a slow orbit over the planet/body and the screen would be a grid of green over the surface of the planet showing which parts you have scanned. Now to stop you speeding up time you would require user intervention at times else you would not get "all" the data. So your onboards might register that you have some important things missed that you did not respond to so you would need to fly over that sector again for the data.

There would need to be a reward to do the slow or level 1 sped up method of course but you would have to manually fly over the planet yourself and chart it all.
# Turwhitt from the frontier forums wrote 

> > Or use your fuel scoop to take a sample of the atmosphere (or even land for a surface sample on solid planets) of each planet in a remote system.<<
# DraQ from the frontier forums wrote

> > You could have scientific missions involving deployment, retrieval, and escort of various types of probes, sensors and even manned vehicles, and combinations of such task (for example deploy, wait, retrieve or deploy, escort, retrieve).

For example you could be asked to take an orbital probe (with no own propulsion) and put it in orbit around certain planet. Failure would be determined by it's collision with the atmosphere or flying too far out within certain timeframe. Lack of failure would indicate success.

You could also be asked to launch atmospheric probe, lander or vehicle with its own limited means of propulsion, or set down a platform that would be more or less modified MB40 in terms of gameplay mechanics.

You could also be asked to install some sensor pack and fly in certain place.

Also, apart from scientific missions, S&R from both drifting ships, drifting escape pods and planetary surfaces could be nice.

Another idea - asteroid defence missions on newly colonized worlds without planetary defense systems. <<

**Comment by Web-eWorks** [comment]
Thank you for the suggestion! Closing as unimplemented; feature requests and discussion should go on the [forum](https://pioneerspacesim.net/forum), as we use Github for tracking actively-developed features and issues with currently-implemented functionality.
