### ISSUE TITLE
Rescue/ Support Missions

### ISSUE THREAD

**Issue by Skodyn** [pioneerspacesim/pioneer#1151]
I was recently doing a delivery mission where as I jumped into the destination I was warned "so you have James Reilly on board, that was a bad idea" or words to that effect. I was then chased by 2 ships.
I have another idea for similar missions. I'm doing a delivery or a taxi mission and as I jump into the destination system I get a message- "I see you have Allan Watkins (my real name btw) on board (unknown to me he is a doctor or scientist etc) he is urgently needed on x planet or starport. We will escort you to the destination where you will drop him off and you will be handsomely rewarded". You could then be attacked or not and the said ships would help defend you or not.
You would be given extra time to complete the original mission or it could be cancelled and the reward would more than cover it.
Also it would be nice idea to have a rescue mission where you go to a stranded ship and pick up the stranded pilot and or passengers/ cargo during which you could also be attacked.

Just some ideas of mine, maybe they have been already thought of and implemented, my apologies if that is the case.

**Comment by Web-eWorks** [comment]
Thank you for the suggestion! Closing as unimplemented; feature requests and discussion should go on the [forum](https://pioneerspacesim.net/forum), as we use Github for tracking actively-developed features and issues with currently-implemented functionality.

**Comment by craigo-** [comment]
fwiw, I do like the original idea 👍

**Comment by Web-eWorks** [comment]
These ideas are all good, but we sadly just don't have the time and resources to get to a lot of them. This one in particular is half-implemented already; we have rescue missions and ships that run out of fuel in the game currently.
