### ISSUE TITLE
Guide tunnel enhancement (for combat and navigation)

### ISSUE THREAD

**Issue by Styggron** [pioneerspacesim/pioneer#1163]
This is a suggestion from Geraldine in the Frontier forums, she asked me to post it here as she was unable to login.

"Additional functionality for the Tunnel Guide Markers as suggested by Geraldine from the Frontier Forums:

The tunnels for combat as well would be simpler. Perhaps with red ones for combat and green ones for navigation just like FFE does. Why not have both options then for the existing set up and the tunnels with a toggle on the main console?

The only thing I would add is the toggle should be an either or setup. Having the existing setup with the tunnels overlaying it would clutter the screen up too much in my view. All that's needed is the direction (gun sight) and velocity marker with the tunnels just like in the original game.

Oh, one more thing, the red combat tunnels, it would be really nice if those tunnels (not the nav ones) would automatically lock on to the nearest attacking ship. If you are in a situation where you are facing a pirate/police/military flight wing, clicking on fast moving targets could be bothersome, so it would be good if the game did this for you.

Or

Just have the one set of tunnels at a time that automatically switch themselves between nav and combat modes. That should leave the screen clutter free.

The main idea here is to keep it simple, just use the force! "

**Comment by nozmajner** [comment]
Glide tunnels for combat doesn't seem to be that useful. Imgui HUD might resurrect this I guess, so if still seems useful, then reopen, but closing until that.
