### ISSUE TITLE
3 Navigational reference systems

### ISSUE THREAD

**Issue by Baobobafet** [pioneerspacesim/pioneer#1175]
This is an attempt at a logic framework for 3 Navigation aids.
(or rather 2 nav aids and an Autopilot option)

---

1> Attitude Reference (AR)
## 0-360' pitch, yaw and roll display

2 modes (via toggle) 
Mode 1, Anchor Z axis to nearest gravity.
Mode 2. Turn off Z gravity anchor, Free mode.
Default setting 1 anchors the Z or Yaw (elevation) axis to the nearest center of gravity.
If the gravity is a planet - the AR system should poll for it's radius.
This is important to compensate appropriately for a planet's curvature and will insure that the horizon
 (Pitch) readout of zero always matches that of the physical horizon of the planet while flying over
 it's surface.
The Z Gravity anchor mode also insures you will have the tools to always be perfectly horizontal when
 attempting to land on even the most small and irregular shaped asteroids.
An intuitive and graphic way to display pitch and roll relative to gravity would be to have one of the scanner modes transform the scanner into a giant circular bubble level. (possibly with a resolution zoom option)
 So long as the bubble remains in the center of the bullseye, the ship's pitch and roll are level with the horizon of the planet.
This insures proper ship attitude for even descent onto planet surfaces. Useful visual feedback for making those textbook three point landings.
A possible addition to the bubble display would be the depiction of a target bulls eye for the landing pad, on the scanner display- once your ship was near or directly over top of the assigned landing pad the bulls-eye would begin to blink to signal you were over the landing threshold.

Mode 2, All attitude measurements are zeroed when the AR gauge is set to Mode 2.
(whether in space or on planet or asteroid surface.)
From then on all movements in pitch yaw roll will be compared and shown as deviations from zero
 on the Pioneer dash under the headings pitch, yaw and roll in a 0-360' increments.
 On planet surfaces the yaw readout can function as a makeshift compass for navigation. 
(True only if the AR guage is set to Mode 2 while the pilot's ship is pointed towards a planet's North pole.)

The pitch and roll readouts give a pilot digital attitude feed back for making small measureable
 corrections in angle of attack and bank during flight.
 For space flight, this info takes precise manual 180' retro thrust orientation and other maneuvering
 functions, to a more reliable and repeatable level.
 The pilot's AR gauge must be set to Mode 2 (zeroed) "after" the ship is pointed towards a desired vector
 for deviations to be measured relative to zero on the pitch, yaw and roll display.

An Autopilot plugin might create an option to allow a ship to always keep it's nose on the horizon of
 a planet regardless of whether the planetoid is as small as the 10 km.

---
## 2> Distance & Postional Reference (DPR)

This gauge is for referencing a particular area of space within any chosen solar system.
2 modes to show XYZ  (via toggle) 

Mode 1 (with conversion submode)
1. The exact XYZ coords of your ship's position in that system.
2. Metric distance units. Conversion of XYZ coords into meters,km,AU.
   Likely requires the ghosted box displaying this info to be expandable or larger than most other similar
   boxes in width to accomodate potentialialy large numbers.)
   Perhaps a slider to vary transparency on this readout could be an option

The default Mode 1 reference would be to display the XYZ relative to the largest sun in
 that system (or alternate positional constant).
A specific address in space can be visited by other players knowing the same XYZ co-ords.

Mode 2
Measurement function. Allows a pilot to temporarily zero the XYZ scale so local point to point
distance measurements can easily be made relative to any single position in space.

With X representing the the heading of your ship:
X = distance forward/back displayed in plus or minus meters/km...
Y = distance left or right of X axis displayed in plus or minus meters/km/...
Z = distance of elevation up/down along the X axis displayed in plus or minus meters/km/...

An autopilot plugin option to save &/or target specific XYZ co-ods as a destination or waypoint could be an added feature.  

Mode 1 could also prove quite useful for charting mining areas and points of interest.

---
## 3> CoPilot AI (or A.I. Advanced autopilot)

A combination of Mode 1&2 positional info is used to record custom tactical flight manuevers as macros.
 This makes possible engaging an evasive flight macro durring a battle at the touch of a designated key combo.
 While an evasive prerecorded flight path is being performed, A pilot could concentrate his
 energy manning defense turrets, countermeasures, missles or mines to further discourage any
 pursuing aggressors.
The duration of maneuvers recorded can be a price point in the Copilot AI's quality.
So to purchase an AI Copilot that can record 15 minutes worth of maneuvers (per Macro slot), would
 cost more to buy in the ship's equipment yard, than say an AI Copilot, that could save only
 30 seconds worth of maneuvers (per Macro slot)
Some AI Copilots might be able to record and replicate entire patrol maneuvers.
Thus freeing those pilots to better monitor, other important sensor and visual scans enroute. 

Example Method of use:
Pilot engages "teach" mode for CoPilot AI. Pilot then holds down qualifier key with one of the F1-F10 keys
 as a designated save location. Pilot performs maneuvers.
Pilot ends teach mode. Pilot maneuver is now saved as a macro to that qualifier+F key combo. 

When that specific F1-F10 Macro key is now pressed - The last recorded maneuver in that Macro slot, will be performed.  

A continuos repeat Macro maneuver option (untill disabled) might be a consideration to optimize available macro recording time
(perhaps a third qualifier key could enable/disable the continous repeat maneuver option.)

**Comment by nozmajner** [comment]
Some parts are already in master, some seem to be overthought. Please bring any further discussion to the dev forum, if it's anybody is still interested.
