### ISSUE TITLE
Custom paint jobs

### ISSUE THREAD

**Issue by deadendgalaxy** [pioneerspacesim/pioneer#1189]
How about adding some unique flavor to your ship by spray-painting it. Remember Firefly and the "custom decoration" of the Reapers. :)

Perhaps it would be cool to have a special work shop at the star bases to customize the look of your ride. I imagine simple straight lines you can apply in different colours, as well as logo's, symbols, etc.

**Comment by impaktor** [comment]
In 1959, Sovietunion launched Luna 1 and Luna 2 crashes into the moon, Luna 3 sends back the first pictures of its dark side; US launched many satellites, like the first weather satellite, the first operational spy satellite, and Explorer 6 sends the first picture of Earth from orbit; in Siberia the [Dyatlov Pass incident](https://en.wikipedia.org/wiki/Dyatlov_Pass_incident) occurred; Hawaii and Alaska becomes states, adding two new stars to the US-flag; US Postal service experiments with [missile mail](https://en.wikipedia.org/wiki/Rocket_mail) (even the future was brighter in the past!); Venus occults Regulus (next time in 2044, remember where you read it first!) which allowed for measurement of Venus diameter and atmosphere; the first copying machine, [Xerox 914](https://en.wikipedia.org/wiki/Xerox_914), is released; The Twilight Zone premiers on CBS, and Ben-Hur is released; and this year marks the peak of the [Tailfin war](https://en.wikipedia.org/wiki/Car_tailfin) by the latest Cadillac. It is also the number of a double of this issue: #1959.

**Comment by fluffyfreak** [comment]
What?

**Comment by fluffyfreak** [comment]
ah, 1959
