### ISSUE TITLE
Science missions advance technology

### ISSUE THREAD

**Issue by deadendgalaxy** [pioneerspacesim/pioneer#1191]
Inspired by #1127, I think it would be great if not only you could do research, but it would also give you some new technology.

Such as finding a unique DNA strain in a sample taken from an uninhabitated planet, which results in finding a valuable cure for a certain disease.
Discovering new types of alloys, which yield improved armour plating or more cargo space due to weight savings.
Improving the efficiency of your engines by doing some dangerous high-energy research close to stars.

I think it would be fun if there was some danger involved, not just repeat  same action 1000 times to get price X.

It would also be cool if you could launch probes into stars and planets, which will give you some new insights in planet characteristics etc without having to go to close.

**Comment by WKFO** [comment]
Probes are cool, but I disagree with the R&D thing. Too much roleplay.

**Comment by Web-eWorks** [comment]
Thank you for the suggestion! Closing as unimplemented; feature requests and discussion should go on the [forum](https://pioneerspacesim.net/forum), as we use Github for tracking actively-developed features and issues with currently-implemented functionality.
