### ISSUE TITLE
Additional stardreamer speeds

### ISSUE THREAD

**Issue by CmdrBugbear** [pioneerspacesim/pioneer#1206]
This is more to suit the pilots that fly on manual / do orbital transfers / have a really long way to travel.

E.g. I jumped into a triple system and was low on H2 fuel.  Unfortunately, the nearest gas giant was 7000+AU away.  Taking propellant limitations into account, my max speed (presuming that I wanted to slow down at the other end) was about 20,000km/s, but at that speed, even with stardreamer at 10000x, I would have been looking at a pixel on my screen for quite a few hours (to an extent, I’m pulling these numbers out of the air but you get the idea).

Reminds me of Wobbler’s game “Journey to Alpha Centauri” – I’m pretty sure there will be people on this forum that will get that joke…(bragging rights for the author and book title)

So, I’d like to propose an increase in the maximum stardreamer time acceleration speeds.  

Use ctrl+click stardreamer (or some other modifier key) controls to modify from 10^(0 to 4) to 10^(5 to 9)?  (From a GUI point of view, presumably this would be the simplest to implement).

(I’d be curious to see how fast time acceleration could go before the error bars get significantly big…)

**Comment by nozmajner** [comment]
Additional Time accel levels are not desired. Could introduce issues, and wreck the sense of scale. Closing.
