### ISSUE TITLE
Descent Rate Warning Light and poor man's attitude guage

### ISSUE THREAD

**Issue by Baobobafet** [pioneerspacesim/pioneer#1209]
Pretty straight forward, I thought I should put it out there.

Descent rate & Attitude  

The descent rate Warning Light and attitude guage. (would only activate when gravity is in detect range)

Once a planet's gravity vector is recognized by this guage, the descent rate can automaticaly be calculated for the ship's z axis, once the ship transitions to horizontal for descent to the surface. Depending on orientation and rate of descent, three things would happen.

1. It would only turn the light on when the ship was perpendicular to a detected gravity source. 
 (This is also how it can function as a horizon and landing attitude aid)
In other words, Only when a ship's pitch and roll are horizontal to the surface of a gravity source (planet) a green light on the dash would go on.

2.As a ship decended, rate of speed down the gravity vector could be  calculated, and if safe landing speeds were exceeded, a flag would go off and cause the warning light to change to yellow.

3.Speed down the gravity vector would continue to be calculated, and if it approached lethal landing speeds, a flag would go off and cause the warning light to change to red.

All that would be required would be a small alert light on the dash that goes on when a pilots descent rate velocity down the gravity axis (z axis for ship)  exceeded safe landing speed limits.

Of course this warning light wouldn't protect a landing pilot from lateral drift mishaps, landing in the wrong spot or careening head-on into any surface.

Basics involve a 3 color system for the warning light.

green - for safe landing speed
yellow - for collision or crash speed 
red - for all fatal impact speeds

The warning light need not be distractingly large - just large enough to notice
l
See Pics

<a href="http://s1069.photobucket.com/albums/u465/baobobafet/?action=view&amp;current=DescentRateGauge1-1.png" target="_blank"><img src="http://i1069.photobucket.com/albums/u465/baobobafet/DescentRateGauge1-1.png" border="0" alt="Photobucket"></a>

<a href="http://s1069.photobucket.com/albums/u465/baobobafet/?action=view&amp;current=DescentRateGauge2.png" target="_blank"><img src="http://i1069.photobucket.com/albums/u465/baobobafet/DescentRateGauge2.png" border="0" alt="Photobucket"></a>

Not quite yet level for landing.

<a href="http://s1069.photobucket.com/albums/u465/baobobafet/?action=view&amp;current=DescentRateGauge3.png" target="_blank"><img src="http://i1069.photobucket.com/albums/u465/baobobafet/DescentRateGauge3.png" border="0" alt="Photobucket"></a>

<a href="http://s1069.photobucket.com/albums/u465/baobobafet/?action=view&amp;current=DescentRateGauge4.png" target="_blank"><img src="http://i1069.photobucket.com/albums/u465/baobobafet/DescentRateGauge4.png" border="0" alt="Photobucket"></a>

Ship level on horizon and green for landing.

<a href="http://s1069.photobucket.com/albums/u465/baobobafet/?action=view&amp;current=DescentRateGauge5.png" target="_blank"><img src="http://i1069.photobucket.com/albums/u465/baobobafet/DescentRateGauge5.png" border="0" alt="Photobucket"></a>

Descending level and at safe speed.

<a href="http://s1069.photobucket.com/albums/u465/baobobafet/?action=view&amp;current=DescentRateGauge6.png" target="_blank"><img src="http://i1069.photobucket.com/albums/u465/baobobafet/DescentRateGauge6.png" border="0" alt="Photobucket"></a>

Descending level at crash speed.

<a href="http://s1069.photobucket.com/albums/u465/baobobafet/?action=view&amp;current=DescentRateGauge7.png" target="_blank"><img src="http://i1069.photobucket.com/albums/u465/baobobafet/DescentRateGauge7.png" border="0" alt="Photobucket"></a>

Descending level at lethal speed.

**Comment by nozmajner** [comment]
Closing, because UI related talks should be on the dev forum (we didn't had one back then :) ). 
Also I think in-atmo UI needs a more throughout design.
