### ISSUE TITLE
long. and lat. ° "grid"

### ISSUE THREAD

**Issue by gernot66** [pioneerspacesim/pioneer#121]
nothing important only a wish,

a possibility for a "system designer" to evaluate positions on a planet.

http://i790.photobucket.com/albums/yy187/potsmoke66/help/2011-05-22_132428.jpg

i know this will change often, and didn't makes a lot sense now, but just as a wish, i would like to place the city exacly on the foot of this mountain.
actually that's a bit hard because i don't know where i am on "Tombogandhi", it would make it far easier if i could read the long. and lat. ° even just roughly (10° grid).

second, maybe a way to save a heightmap of a planet, so it will hopefully stay the same, more or less, in next releases, different machines/OS's

more a "cosmetic" thing and has no importance.

**Comment by impaktor** [comment]
double of #826 

Plus we can see lat/long when flying to the location, both in debug mode, but also when in normal mode nowadays.
