### ISSUE TITLE
Storage facility rentals at Spaceports

### ISSUE THREAD

**Issue by Baobobafet** [pioneerspacesim/pioneer#1224]
Did a search for storage and did'nt see this so...

Allows cargo storage as well as storage of extra ship(s) at individual spacestations.
Amount dependant on storage size required and rental duration.
Charged to players account regularly and automatically.

Accessing your storage facility could involve using the existing commodities market.
Where the player has (once he buy's it) his own presence via icon in the commodities menu to move stuff
 to the storage area or from the storage area to their ship.
(basically like an existing store, but where the player is the owner)

The ability to store ships might be a more difficult problem but would be a nice option.
That way you could park your main ship at a spaceport and take a jaunt in something
light 'n sporty - like a small fighter or shuttle.
 Ultimately you wouldn't have to go through the process of having to save game before
 selling your ship to test fly something different.

**Comment by Web-eWorks** [comment]
Thank you for the suggestion! Closing as unimplemented; feature requests and discussion should go on the [forum](https://pioneerspacesim.net/forum), as we use Github for tracking actively-developed features and issues with currently-implemented functionality.
