### ISSUE TITLE
Online Starport

### ISSUE THREAD

**Issue by Baobobafet** [pioneerspacesim/pioneer#1227]
Okay I've been chewin' on this idea for a while, because of talk of some code rewrites it's probably better to toss this idea out there earlier than later.

 I've read some perhaps not all the issues in regards to adding multiplayer
So I understand about trading off realism in the sim to accomodate multiplayer capability.

So I thought lets not touch the physics or anything that will impact the game directly and look at points in the game when the engine for all intensive purposes is on pause.
In particular, this occurs quite naturally when a pilot docks at a spaceport.
So lets imagine a pilot docks at a spaceport - the comms comes up and a new market is available.
This could be a Public market that is interactive with a server to allow trade and comms between other pilots logged in to that particular spaceport's server. The moment a pilot disconnected from the public market, it would be no different had he disconnected from a AI driven market.

The first rule I think it should follow is that no trading should occur between players unless they are at the same corresponding station in the pioneer universe.

 A single server could host comms and trades for many such spaceports.
In addition having multiple starports with this feature allows a lot of RPG flexibility. Including relay races from one starport
to another. This also opens up other possibilities - once there are uber servers around and depending on what flexibility is left in Pioneers code at that point.

The server connect yes or no option would be in the game options screen.

Earth seems a natural starting point for such an online market. It could be a great means of welcoming new people to the game.

What do you all think?
 

I'd also like to credit Issue #827 for reminding me of this idea and I think it would be a no brainer to include this data in any online data protocols established.

**Comment by impaktor** [comment]
Documented here: http://pioneerwiki.com/wiki/Network_features

Also:

> This topic can be closed.
