### ISSUE TITLE
no rear lasers

### ISSUE THREAD

**Issue by gernot66** [pioneerspacesim/pioneer#1262]
i reported this since i don't know and now again.

the rear lasers still don't work in alpha21, it seems that is not important for a space game?

watch this clip please, you will see also that the positions of the laser fire is wrong and not clear where it comes from (compare ship specs below).

http://youtu.be/qu2CXOckeRw

<pre><code>
define_ship {
    name = 'YT-1300 "Millenium Falcon"',
    model = 'millfalc',
    forward_thrust = -4e7,
    reverse_thrust = 2e7,
    up_thrust = 1e7,
    down_thrust = -1e7,
    left_thrust = -1e7,
    right_thrust = 1e7,
    angular_thrust = 15e7,
    gun_mounts =
    {
    { v(0,3.123,-3), v(0,0,-1) },
    { v(0,-3.123,-3), v(0,0,1) },
    },
    max_cargo = 120,
    max_laser = 2,
    max_missile = 0,
    max_hullautorepair = 0,
    max_fuelscoop = 0,
    max_cargoscoop = 0,
    max_cabin = 8,
    capacity = 120,
    hull_mass = 80,
    fuel_tank_mass = 20,
    thruster_fuel_use = 0.0002,
    price = 200000,
    hyperdrive_class = 4,
}
</code></pre>

**Comment by Web-eWorks** [comment]
Closing as inactive; if the issue still exists on latest master, please open a new issue with updated information!
