### ISSUE TITLE
Camera body rotation does not match camera rotation

### ISSUE THREAD

**Issue by gernot66** [pioneerspacesim/pioneer#1281]
i tried to fiddle around with the camera setup and noticed a strange behave.
best is watch the clip, when you are close to a planet the camera seems to spin around the center, but as soon as you leave the close orbit it's vanished and the camera rotates proper on the center. looks like it's influenced by gravity? 

https://www.youtube.com/watch?v=L9m9QFZCAT8

for completeness, pioneer alpha22, mac build, but i guess it won't matter ;)
better try to test that yourself, to see where it might come from.
it won't matter which ship you take...

edit: btw. if you entered a camera pos for the first time, run the game twice, at first run it didn't changes from "standard" view, can't say why. after that it's ok and every change will appear at next start.

just enter a "front_camera" to the ship specs which shows some of the ship as reference geometry.

besides, i know "camera" is still experimental, but i say it here and loud, i like it!
i know that i had doubts about how senseful it is, but let's say i changed my mind about that.
(in despite of all the work it will give to me, making all the cockpits higher detailed)

---

i really like the camera position setup, it gives the ships a very unique handling, imo.
i hope that could be solved, as well as some already mentioned a outsourcing of the buttons setup, is that possible? (i think so).
i really would like that to and a combination of both, a 3d cockpit / bridge and customized buttons / HUD for each ship would be great.

i would prefere that to any overlayed 2d cockpit or bridge.

to restrict the higher res. cockpit model from the outside view is no problem.

**Comment by richardpl** [comment]
What to do with this bug report?

**Comment by nozmajner** [comment]
Alpha 22 is a quite old build, I don't think the problem described exists any more. The model system changed since then, so you can't and don't need to hack the external view to work as a cockpit.

**Comment by Web-eWorks** [comment]
Closing as inactive. If the issue still exists on latest master, please open a new bug report with more information!
