### ISSUE TITLE
Bug: incorrect velocity upon loading from save when near a planet

### ISSUE THREAD

**Issue by Ae-2222** [pioneerspacesim/pioneer#1285]
Steps (latest master):
- Earth start, undock
- F4, set autopilot to vicinity of tranquility base
- Select max time accel
- Afterwards (set speed = 0) save game
- Load and unpause (1:1 time accel)

Result: moving away from planet at great velocity.
Saved game: http://wikisend.com/download/638982/loadgamevelocitybug

**Comment by richardpl** [comment]
This is no longer happening?

**Comment by fluffyfreak** [comment]
Even if it is it was using an old version of Visual Studio only. So didn't/doesn't affect the released versions, also we now support only newer versions of VS so behaviour might be different now.
