### ISSUE TITLE
Possibility to pre-generate a starsystem database

### ISSUE THREAD

**Issue by Metamartian** [pioneerspacesim/pioneer#1318]
For those that want it, How about an option in the config (or upon starting a new game) that allows you to pre generate a starsystem database? if it was designed around a slider they could choose between a light year radius from the core systems which would show approx how much drive space would be required or define how much disk space they want to use which would tell them the light year radius of the core systems. everything outside this radius is generated as it does now...

**Comment by impaktor** [comment]
So, this is for faster loading of scrolling the star map. How much of a problem is this really? My computer is so old it doesn't even run pioneer, and it didn't have any real problem with this when we were on OpenGL 2 (yes, clearly I'm the norm :wink: ). 

4 years is long enough. --> closing.
