### ISSUE TITLE
Adding more space station or asteroids at space.

### ISSUE THREAD

**Issue by SystemNetwork** [pioneerspacesim/pioneer#1320]
I wanted comets or asteroid to hit my ship. 

I wanted it to damage the ship so it can be realistic! Sorry i'm a nOOb at posting.

Anybody have any ideas? I'm just good at designing and programing but not lua :D Oh yeah! how do u even add labels??

**Comment by impaktor** [comment]
Lets take it in: http://pioneerspacesim.net/forum/viewtopic.php?f=4&t=312
