### ISSUE TITLE
Boson Accelerator, possible ship upgrade option available in shipyard

### ISSUE THREAD

**Issue by Baobobafet** [pioneerspacesim/pioneer#1337]
Found this quote relating to the recent Higgs discoveries:

"Scientists went into a frenzy following the announcement, speculating that it could one day make light-speed travel possible by “un-massing” objects or allow huge items to be launched into space by “switching off” the Higgs."

http://news.nationalpost.com/2012/07/05/higgs-boson-find-could-make-light-speed-travel-possible-scientists-hope/

:O

  This had me wondering if this wouldn't easily morph by the year 3200 into at least, some ship device addon/option purchaseable in a shipyard.

Requirements

 Allow for a mechanism in the ship config files to subtract 'some' percent of mass if the ship is carrying (and has activated) the Higgs ship un-mass function ie: Boson Accelerator. There might be various types of ship un-mass strengths and active durations depending on the availability, quality and cost of such a device.

Anybody else think this type of ship tech might be realistic or desireable as a feature in the Pioneer shipyards?

**Comment by nozmajner** [comment]
The consensus about Pioneer is to try and keep handwavium and magitech to the minimum possible. Thus closing.
