### ISSUE TITLE
Surface level flight HUD and compass

### ISSUE THREAD

**Issue by Gudadantza** [pioneerspacesim/pioneer#134]
I propose a HUD similar to those in Modern fighters as a switchable option. It will show  Level lines according to the reference surface object or planet.. It will show in an usefull way as in fighters the ascent or descent rate visually.

It will have upwards an usefull compass too.

At the press of a button the HUD will change between the normal Pioneer HUD and the Level Surface HUD.

**Comment by impaktor** [comment]
2 years since my post above. Also, @nozmajner gives consent. --> closing.
