### ISSUE TITLE
System map needs to graphicaly show orbital direction of bodies

### ISSUE THREAD

**Issue by Baobobafet** [pioneerspacesim/pioneer#1421]
System map needs to show orbital direction of bodies. Small arrow(s) on the orbital path indicator (ring) would be extremely helpful and would more easily allow a user to determine consistantly if he was viewing a map right side up or upside down.

**Comment by impaktor** [comment]
@dodomorandi might be interested in this.

**Comment by dvolk** [comment]
The problem was that the orbit drawing didn't start at the planet's location. It's always started at the same point on the orbit.

**Comment by dodomorandi** [comment]
I opened a new PR (https://github.com/pioneerspacesim/pioneer/pull/3460). What do you think about it?
