### ISSUE TITLE
Inmi System bug

### ISSUE THREAD

**Issue by Adie123** [pioneerspacesim/pioneer#1449]
Inmi (sector: -6, 2, 88) [small asteroid]... Couldnt dock at clements station and could fly through asteroid. On versions alpha25 and alpha26dev (d90d5d8-win32).

Seems like there maybe a rough radius around clements station that makes ~half of the asteroids surface none collidable.

captured video on youtube. Link below

http://www.youtube.com/watch?v=WY6fK0x5lpE

**Comment by fluffyfreak** [comment]
Closing as the system this happened in no longer exists since our changes to the RNG etc.
Also with #4108 being merged it might hve fixed related issues anyway.
