### ISSUE TITLE
Show equipment description tooltip in ship info view (F3)

### ISSUE THREAD

**Issue by PinBlacniP** [pioneerspacesim/pioneer#160]
Feature request ... Equipment to show same mouse-over information as shipyard equipment screen.

**Comment by Web-eWorks** [comment]
@vakhoir this might be low-hanging fruit; I'm not 100% certain if the equipment market currently has *any* tooltips to start with.

**Comment by impaktor** [comment]
I was actually looking at this issue earlier today

> I'm not 100% certain if the equipment market currently has any tooltips to start with.

Que? There's tooltip in the equipment market. Not for every equipment, but it's there. Ideally, in the future, there's a table of sorts showing stats for e.g. current selected weapon, or hyperdrive.

**Comment by Web-eWorks** [comment]
> Que? There's tooltip in the equipment market. Not for every equipment, but it's there. Ideally, in the future, there's a table of sorts showing stats for e.g. current selected weapon, or hyperdrive.

Well that just tells you how much time I spend mucking about in C++ vs. playing the game :stuck_out_tongue: The equipment market needs a major overhaul to be actually user friendly, but that's neither here nor there.

**Comment by Web-eWorks** [comment]
Closing for now, as we're re-designing the InfoView screen anyway. If vakhoir wants to fix this in the interim, I wouldn't say no, though!

**Comment by vakhoir** [comment]
Yeah, the new equipment market has a tooltip for every item that has a description string.

We can make it more userfriendly once everything is ported to pigui.

**Comment by Web-eWorks** [comment]
@vakhoir I believe the original thrust of the issue was displaying those tooltips on the InfoView screen, if that's something you want to handle. Otherwise... that part of the InfoView screen is going to get split into an outfitting UI anyway, so no worries!
