### ISSUE TITLE
New UI: Keyboard navigation

### ISSUE THREAD

**Issue by robn** [pioneerspacesim/pioneer#1668]
Arrow keys should move to the nearest selectable widget in that direction. Since what we currently call "select" is really "keyboard focus", we may need to separate these concepts so that buttons can be selectable without taking the keyboard focus. That might be needlessly complicated though. Needs some thought.

**Comment by Web-eWorks** [comment]
Closing as WONTFIX; we're fighting to get rid of newUI as fast as we possibly can right now!
