### ISSUE TITLE
New UI: Tooltips

### ISSUE THREAD

**Issue by robn** [pioneerspacesim/pioneer#1670]
Pretty simple. Each widget should have a settable tooltip. If the mouse is over the widget for some period of time, a floating widget appears.

I think I'd like it to be possible for a tooltip to be an arbitrary widget, with a special-case in the API that if you set it to a string, it makes a `Label` for you. Then we can have rich, interactive tooltips.

**Comment by impaktor** [comment]
This NewUI system is dead, tooltips are supported in Pigui
