### ISSUE TITLE
Spiky asteroid terrains

### ISSUE THREAD

**Issue by robn** [pioneerspacesim/pioneer#1680]
It started from this thread: http://spacesimcentral.com/forum/topic/3081-some-screenies/

Tiandeth B b is the culprit. Hack a start point to [1,0,-60,1,1] (for example), you'll see it pretty quickly.

![](http://i.imgur.com/wPkGn.png)

Tried to reproduce directly in Sol for convenience, but the seed didn't give identical results. However just loading up Phobos in the object viewer and hitting "random" a few times will quickly show the problem. eg, with just one click:

![](http://i.imgur.com/8d5Eo.png)

/cc @s20dan.

**Comment by impaktor** [comment]
@fluffyfreak you do the honour of closing this?

**Comment by fluffyfreak** [comment]
As far as I know it might still happen. Though I've not seen it in a while.
I did some thing to try an avoid it a while ago. 
Will close for now since all this stuff is still pending my terrain JSON rewrite anyway.
