### ISSUE TITLE
About 20% of trade ships is destroyed when landing and the timestep is big

### ISSUE THREAD

**Issue by irigi** [pioneerspacesim/pioneer#1683]
I observed this during my work at TradeShips.lua, up to 20% of ships fail to land when the timestep is big. The reason is IMHO obvious: autopilot cannot land with so high timestep. Proposed solution would probably be:
- detect if the timestep is big
- if yes, detect when the ship is in some distance X from the starport attempting to land
- let the ship disapper from current position and appear docked at the starport

I, however, do not know how to do this in lua in a best way.

**Comment by richardpl** [comment]
I do not think I encountered trade ship destruction any more.

**Comment by fluffyfreak** [comment]
Just tried it, over 12 days there were just 3 ships destroyed out of over 1300 events. Seems robust enough to me.
