### ISSUE TITLE
Zoom Function for Ship Preview Screen in Shipyard

### ISSUE THREAD

**Issue by Baobobafet** [pioneerspacesim/pioneer#1778]
Unless I'm missing this key or perhaps mouse function via holding both buttons down and drag to zoom?
If this has been debated before hopefully it is in the cue.

  This seems an old problem I have seen overlooked in many space games, to the extent I have become numb to it. A shame really since this is where many of Pioneer's ship's are exposed (or in this case not so much) to the player.

Ignore or close this issue if this is handled by the upcomming ship edit system :) sry

**Comment by impaktor** [comment]
We do have scroll wheel zoom everywhere, on all ship-spinners
Close?

**Comment by nozmajner** [comment]
Yupp, both on the F3 screen and the market.
