### ISSUE TITLE
Park things at Lagrangian points

### ISSUE THREAD

**Issue by mikehgentry** [pioneerspacesim/pioneer#1878]
It would be cool to have things parked at the Lagrangian points.

Maybe spaceports, or maybe just industrial structures, communications arrays, research satellites, space junkyards awaiting recycling (or strip-mining by an enterprising commander... :-)

For a single star and its planet L1 and L2 have particularly interesting properties - L1 is close to the planet but bathed in sunlight, so would be good for industry under solar power. L2 is always in shadow, so might be good for telescopes or communications or something.

For multiple star systems that doesn't apply (ever? always?), but there's got to be an L point right in the centre that would be a great place for an interstellar truckers' café, where dodgy deals are done... :-) Hopefully you could come up with a set of heuristics that fitted appropriate things to the spot.

Possible?

**Comment by impaktor** [comment]
Since this winter, you can see the Lagrange points in the system orbit view. All that remains now is that we place some stuff there.

**Comment by PtrMan** [comment]
You need some hacky special handling code to put the objects parked at L* points on rails.

**Comment by Web-eWorks** [comment]
As this feature request concerns content (and has been without resolution for many years), I'm going to close it. Please start a thread on our [forum](https://pioneerspacesim.net/forum) to continue the discussion with our content creators and modders who would be responsible for bringing it to life!

**Comment by mikehgentry** [comment]
Thread started:

https://forum.pioneerspacesim.net/viewtopic.php?f=10&t=742
