### ISSUE TITLE
Heavy duty atmospheric shielding

### ISSUE THREAD

**Issue by Brianetta** [pioneerspacesim/pioneer#19]
Weighs two tonnes.  Allows ship to fly in atmospheric pressures of more than two bars (remember, space ships are designed to contain pressure, not withstand it) as well as performing regular heat shielding.  Makes fuel scooping safer.

Additional change: Craft entering heavy atmospheres without shielding undergo hull damage over time, proportional to pressure above 2 bars.

**Comment by Garmelon** [comment]
This issue should be closed, closing via commit didn't work apparently.

**Comment by impaktor** [comment]
@Garmelon which commit is it that should have closed this one?

**Comment by impaktor** [comment]
Oh, I see now.

**Comment by richardpl** [comment]
I do not see this equipment in master, but only in fork.

**Comment by Web-eWorks** [comment]
Heavy atmospheric shielding is confirmed to be in master. (Equipment.lua, line 708)
CC @impaktor, I believe this issue can be closed.
