### ISSUE TITLE
Camera control

### ISSUE THREAD

**Issue by Luomu** [pioneerspacesim/pioneer#192]
Game intro (#180) needs some degree of scriptable camera control. We could in any case use a slightly more flexible camera system besides the player's first person view and player's external view.

Something that could accommodate these typical scenarios:
- Onboard view from any ship, facing any direction
- External camera, centered on object (like current external camera, or Objectviewer's camera)
- Chase camera (not quite same as external camera: behind an object, slightly elevated, looking past the object) (related #58)
- Flyby camera: sits at a position, tracks a passing object

From scripting point of view, I don't know if it's sensible to set a camera's XYZ directly. Maybe it should always be positioned to a Body. Camera direction can be set with typical roll/yaw/pitch and/or by tracking a target. Zoom/FOV would be always adjustable (related #135)

**Comment by Web-eWorks** [comment]
Closing this as too broad; we have better internal and external cameras, chase camera is tracked in #58, flyby camera is already implemented, and I've been doing some work on separating the camera controller from WorldView.

I'll open a more specific issue regarding the ability to decouple the camera from the ship and view any arbitrary object.
