### ISSUE TITLE
Engine Power Level indicator

### ISSUE THREAD

**Issue by Baobobafet** [pioneerspacesim/pioneer#1941]
Just a quick mock-up of an idea:

  A smaller indicator could probably be made - finding an easily visible place for it could present a problem.

If on the other hand, the indicator can become part of some virtually already existing graphical detail...
Of course the gauge could be used as a visual pilot feedback cue without adding anything new.

But this has got me thinking if any obstacles exist to enabling analog support options for the thrusters.
This would allow for the use of proper hardware throttles - but most importantly broaden the range of engine output settings possible. Even if analog throttle support is not practical at the moment, the ability to adjust thrust settings incrementally through some key + - key settings would add a whole new dimension to controlling ships in Pioneer.

Anyways, simply an idea.

<img src="http://imageshack.us/a/img198/7231/enginepowerlevels.png" alt="Image Hosted by ImageShack.us"/><br/>

**Comment by nozmajner** [comment]
Closing this because image links are broken, and the use or look of the power indicator cannot be derived from the discussion. 
And we already have compass in master.
And I suspect we are alrady thinking about something related under the imgui HUD project.
