### ISSUE TITLE
tradeships.lua crash

### ISSUE THREAD

**Issue by mikehgentry** [pioneerspacesim/pioneer#1967]
Very early in the game, flying around Earth. Either approaching LA or just landed.

```
Error: [string "[T] modules/TradeShips.lua"]:658: attempt to index field 'starport' (a nil value)
stack traceback:
	[string "[T] modules/TradeShips.lua"]:658: in function 'cb'
	[string "[T] libs/00-Event.lua"]:32: in function '?'
	[string "[T] libs/00-Event.lua"]:182: in function <[string "[T] libs/00-Event.lua"]:177>
zsh: segmentation fault  ./pioneer
```

http://pastebin.com/iq5HkryU

git show
commit 40ac7cdfa05cd3ccc75125ab54a5cb84e7a92a5a
Merge: aac8e45 be14f03
Author: Robert Norris <rob@eatenbyagrue.org>
Date:   Sat Jan 19 14:05:51 2013 +1100

**Comment by impaktor** [comment]
reading (and trusting) what I said 1 year ago above, I'm closing this.
