### ISSUE TITLE
Lua over stdin

### ISSUE THREAD

**Issue by Brianetta** [pioneerspacesim/pioneer#1983]
As Lua outputs both to the Lua console and to stdout, it would be nice to be able to use stdin, as well as the Lua console, for input. This would allow test code to be easily pasted into Pioneer, as well as opening the game up to wrapper scripts for more automated testing.

Doesn't need any fancy tab completion, syntax checking or other cleverness. The goal is to be able to dump well-formatted Lua code directly into the game's Lua interpreter.

> [12:15] \<robn> anyway, its possible, and something I'd like to play with, but not this week. open an issue and assign it to me if you like

**Comment by impaktor** [comment]
#3768 does this, or close enough. --> Closing.
