### ISSUE TITLE
Assertion `!Pi::player->IsDead()' failed.

### ISSUE THREAD

**Issue by johnbartholomew** [pioneerspacesim/pioneer#2116]
From @jmf:

    <john_minetest> pioneer: WorldView.cpp:1502: virtual void WorldView::Draw(): Assertion `!Pi::player->IsDead()' failed.
    <john_minetest> Program received signal SIGABRT, Aborted.
    <john_minetest> 0x00007ffff4e7e2c5 in raise () from /usr/lib/libc.so.6
    <john_minetest> I get this error when executing Game.player:Explode()

**Comment by laarmen** [comment]
Glancing at the new-ui console port commit from 2014, I believe the console stuff still runs from the input event handler. I'm not sure it still triggers the bug, though, and I can't test it before tonight.

**Comment by fluffyfreak** [comment]
Can confirm, still happens.

**Comment by fluffyfreak** [comment]
Looks like that assert is unecessary so have a PR to remove it now.
