### ISSUE TITLE
DS Miner appears on Earth start 

### ISSUE THREAD

**Issue by Zordey** [pioneerspacesim/pioneer#2138]
I have just had the DSminer ship appear on a Earth start.

I assume since you cant fit atmospheric shielding and you cant buy it in the planets ship yard, it should not appear on a planets station?

![Screenshot from 2013-03-04 23:00:33](https://f.cloud.github.com/assets/1453261/219109/528814be-8520-11e2-96a8-41f5ec79eefd.png)

**Comment by joonicks** [comment]
can confirm this still happens as of 2015-10-08
sitting next to a dsminer in london at start of new game
