### ISSUE TITLE
Extend Thrust Limiter Key to Effect  Pitch, Roll & Yaw Thrust Values

### ISSUE THREAD

**Issue by Baobobafet** [pioneerspacesim/pioneer#2145]
Thought this was included in the thrust limiter function..?  ...but not...

 Although lateral, forward/aft thrusters are affected by this control, Pitch, Roll & Yaw are not.

This seems a major oversight - as fine control over these axis' are at least as important as the former.  Extending the thrust limiter to effect thrust over these axis' would be a terrific means to reduce control/joystick sensitivity on command by simple Left Shift keypress.

**Comment by nozmajner** [comment]
This is how it works for at least a year or so, but surely since 2023's Pioneer day release
