### ISSUE TITLE
Speed rating for ships

### ISSUE THREAD

**Issue by s20dan** [pioneerspacesim/pioneer#226]
What do you think about displaying a speed rating for ships along with hyperspace range?

 Rating could be displayed in LY/day or hour.. or even Parsecs/day ;)

 Why? It would be a clear way of seeing how fast a ship is through hyperspace.

 Now IIRC the calculations actually mean that some ships will be faster at long trips and others faster at shorter trips when compared to each other, so perhaps a speed rating can be derived from several distances.

Small ship might look like:
 Short range speed: (5-20 LY)  -  5LY/day
 Long range speed: (20-50 LY)  -  2.125 LY/day ect

Larger ship might look like:
 Short range speed: (5-20 LY)  -  3LY/day
 Long range speed: (20-50 LY)  -  2.25 LY/day ect

**Comment by Web-eWorks** [comment]
Ideally speed rating should be a function of hyperdrive grade and ship hull, but that's neither here nor there.

Closing as unimplemented; feature requests and discussion should go on the [forum](https://pioneerspacesim.net/forum), as we use Github for tracking actively-developed features and issues with currently-implemented functionality.

If you'd like to re-open this, please instead open a new PR with an implementation of the proposed functionality, thank you!
