### ISSUE TITLE
Crashes in terrain mpResult handling

### ISSUE THREAD

**Issue by johnbartholomew** [pioneerspacesim/pioneer#2299]
This issue is to track further crashes in the terrain generation code. See previous issue #2282 and its bugfix #2290.

From @pgimeno in #2290:
> I made the same fix in my local copy before @fluffyfreak submitted this (it looked like the logical thing to do). While it didn't crash there any longer, there were other crashes. I'm in the middle of a system upgrade and can't provide further details at the moment. Just a tip: maybe running several instances of cpuburn or any other CPU-intensive program will reduce the system speed enough to expose the problem? Haven't tried myself.

From @radius75 in #2290:
> I have not checked your fix.
> But I had, after quit or close pioneer a couple of times something like this:
> ![jobq](https://f.cloud.github.com/assets/1929111/513912/2570dfc4-be4b-11e2-8ef0-dc4c1a5b53be.png)

**Comment by fluffyfreak** [comment]
Not seen or heard of this in the last 2 years, assuming that it's fixed and closing.
