### ISSUE TITLE
Additional information in the model viewer

### ISSUE THREAD

**Issue by Zordey** [pioneerspacesim/pioneer#2305]
When designing ships it would be nice to have additional information available in the model viewer similar to what is available in the in game purchase screen. This would greatly speed up the time taken to create the .lua file

Ie. things like:
- Maximum thrust (unladen / laden) for all thrusters
- Hyperspace range

It would also be nice to have some sort of benchmark value for the effective exhaust velocity setting. I have no idea how this could be represented, possibly something like maximum full burn time with max fuel (although I'm sure this would be hard to calculate). 

The current value of exhaust velocity is totally meaningless (to me anyway), currently I am just plugging in random numbers, jumping into the game and flying to Pluto and recording how long it takes. This is quite a drawn out process.

**Comment by Web-eWorks** [comment]
Closing this as the engine has far evolved from the days of defining ships in lua files. I've had the idea of a ship editor boiling in the back of my mind for a while, but I don't think the modelviewer is the right place to hang its hat.
