### ISSUE TITLE
frame drops when changing framerate

### ISSUE THREAD

**Issue by Tichy** [pioneerspacesim/pioneer#2325]
I noticed that when passing from a scene that renders with a particular frame rate, to another with a different frame rate, the game drops some frame.

For example, I could be leaving a planet, thus having a complex scene on my back (terrain and the city) which gives me ~15-25fps and a simple one in front (the stars) which gives me over 100fps. When i turn from one scene to the other, in the moment when the framerate changes, I see frame drops.
This happen even with much higher framerates. In low orbit around Mars, I have from 160 to 200fps, but when I change to sidereal view and move the camera, there are still frame drops.

Another example could be when flyng at low altitude and rotating the view from the direction I'm heading (where the terrain is constantly rendering) to one side or back (where the terrain is alredy rendered), and then to the front again.

I tried to make a screen capture, but when I start recording, the frame rate become more constant and this issue don't appears anymore.

**Comment by fluffyfreak** [comment]
We now have VSync enabled by default and no-one has reported this issue since.
Closing.
