### ISSUE TITLE
"Seam" issues on planets - Missing triangles at LoD borders

### ISSUE THREAD

**Issue by kacktusdev** [pioneerspacesim/pioneer#2331]
On planets, you might see a kind of seam in terrain. The first screenshot shows an overview of the area where I found them.
![screenshot-20130604-014448](https://f.cloud.github.com/assets/2625792/602845/e8166e02-cca8-11e2-9e88-5feb41ae007d.png)
The artifacts occured inside the small crater that crosses the ring of the leftmost giant crater

![screenshot-20130604-014641](https://f.cloud.github.com/assets/2625792/602848/e89cbc5a-cca8-11e2-8c76-3929a577a236.png)
On this screenshot, you can already see the seam passing from the bottom right to the upper left, right through all terrain.

![screenshot-20130604-014058](https://f.cloud.github.com/assets/2625792/602878/21e734bc-ccaa-11e2-9db9-0c6d740a92b4.png)
On this screenshot you see what happens when you combine the seam with LoD. When one side is on a lower LoD than the other, holes in terrain geometry are created.

![screenshot-20130604-014354](https://f.cloud.github.com/assets/2625792/602851/f191f6ae-cca8-11e2-9edf-4c809eae088d.png)
On this screenshot, you can see the ctrl-i screen.

(build 20135.146 (54b7b54))

Good hunting!

**Comment by richardpl** [comment]
This location is no more.

**Comment by fluffyfreak** [comment]
I think that the bug should be fixed as well, there's been lots of changes to the way that the terrain is rendered since this was reported.
