### ISSUE TITLE
Relocated startports on New Hope and possible place for a starport

### ISSUE THREAD

**Issue by Tichy** [pioneerspacesim/pioneer#2334]
I just notices in console that two New Hope starports are being relocated.

Error: Lua custom Systems definition: Surface starport is underwater (height not greater than 0.0) and has been automatically relocated. Please move the starport to another location by changing latitude and longitude fields.
      Surface starport name: Itzalean, Body name: New Hope, In sector: x = 1, y = -1, z = -1.

Error: Lua custom Systems definition: Surface starport is underwater (height not greater than 0.0) and has been automatically relocated. Please move the starport to another location by changing latitude and longitude fields.
      Surface starport name: Epsilon Cove, Body name: New Hope, In sector: x = 1, y = -1, z = -1.

However, if you are interested, I found a place that's quite similar to what were before the change of random function.
It's not far from Epison Cove. It's on a plateau, near the sea and with mountains around. :)

http://postimg.org/image/hia1yuxml/
http://postimg.org/image/5holy4q7x/

**Comment by Tichy** [comment]
Don't know if that's still useful. Some things have changed in the last three years with planet generation.

**Comment by impaktor** [comment]
I think we actually relocated them at least once or twice manually, since this issue was opened.
