### ISSUE TITLE
TradeShips hyperjumping directly above ground starport

### ISSUE THREAD

**Issue by lwho** [pioneerspacesim/pioneer#2376]
It seems that trade ships jump immediately after taking off. I think, they should keep a safe distance before initiating hyperjump (which they did some time ago).

After some debugging this is what happens (everything in `TradeShips.lua`):
1. The trade ship issues a `ship:Undock()`
2. The `onShipUndocked(ship, starport)` callback issues a `ship:AIFlyTo(starport)` (i.e. fly to the just left starport) and marks the ship as outbound.
3. The `onAICompleted` callback triggers the jump for an outbound ship.

It seems that some time ago, `AIFlyTo` to the current starport would bring the ship to a safe distance before completing the command, but now completes immediately after take-off.

For orbital stations the current `AIFlyTo` seems to do the right thing, i.e. jumping at a distance of 15km (I did not check, if that was triggered by `onAICompleted` or by `onFrameChanged`, though).

Anyone has an idea, how to solve that? For ground stations, one could issue an `AIEnterLowOrbit` an then rely on `onFrameChanged` to do the jump. This would happen when leaving the rotating frame of the planet. However, this might still be too close for planets without atmosphere and with low terrain?

**Comment by richardpl** [comment]
Trade ships here do not hyper jump immediately after taking off.
