### ISSUE TITLE
Unexplored systems marked yellow (inhabited independant)

### ISSUE THREAD

**Issue by TheNewBob** [pioneerspacesim/pioneer#2380]
After a certain distance from Sol, all systems start to show up in independant color. They are all unexplored, so it would make more sense to display them as uninhabited.

The break between unexplored systems showing up in grey, along with some inhabited systems, and all systems showing up as inhabited, happens about 730 lightyears from Sol.

I assume that this is a bug that displays all unexplored systems as independant as soon as there are no inhabited systems around anymore.

In fact, the problem can be seen a lot earlier: When loading a new sector, all systems show up as independant for a short while, then revert to grey after if they are not inhabited.

It would seem to me that independant is the default color stars are marked, and after creating the stars in a sector the habitation check is done, which changes the color of uninhabited systems. It seems probable that after a certain distance the habitation check is just simply not performed anymore, as there shouldn't be any inhabited systems, and the colors are thus left on default.

If I am right, I would suggest changing the default (initial) color marking of star labels to uninhabited.

**Comment by richardpl** [comment]
Have this been fixed?

**Comment by impaktor** [comment]
I'm not sure. I think at least half has been fied. @richardpl you can fast-scroll the sector view map by holding in Shift,  so you can get to unexplored territory,  zoom out and see faction colours,  if you want to check if this is fixed or not.

**Comment by richardpl** [comment]
This have been fixed. Unexplored systems are always gray.
