### ISSUE TITLE
Info View: Allow switching tabs with keyboard

### ISSUE THREAD

**Issue by ghost** [pioneerspacesim/pioneer#2383]
My suggestion is to switch to the next tab of the Info View by using F3 again when already in that screen.

The problem is that the info view itself, including the TabGroup widget, is written in Lua.

The fix could be as simple as invoking a Lua function added to InfoView.lua that executes tabGroup:SwitchNext(), calling it from a new _else_ branch of this snippet from ShipCpanel.cpp:

<pre>
 void ShipCpanel::OnChangeInfoView(Gui::MultiStateImageButton *b)
 {
    Pi::BoinkNoise();
    if (Pi::GetView() != Pi::infoView)
        Pi::SetView(Pi::infoView);
+   else
+       /* invoke function in InfoView.lua that does tabGroup:SwitchNext() */
 }
</pre>

I don't know how to invoke a Lua function from C so I didn't write a PR.

**Comment by Web-eWorks** [comment]
...I think I'm going to close this issue. I don't see a particularly large benefit to supporting this behavior when the rest of the UI has extremely minimal support for keyboard/gamepad navigation. We'll revisit the topic in a more general issue at a later date.
