### ISSUE TITLE
SIGFPE from terrain generation not having well-defined bounds

### ISSUE THREAD

**Issue by lwho** [pioneerspacesim/pioneer#2403]
This was originally reported in #2399 by @walterar

I was able to reproduce the crash with clean master ef56f0c4d6427fdfd54eccd78edf6e4807f93fc5 as follows:

- Start on Patterson's Mine, just add the following to `buttonDefs ` in `data/ui/MainMenu.lua` and select it on start:
`        { t("Start at Patterson's Mine"),    function () Game.StartGame(SystemPath.New(12,4,-5,1,8))   setupPlayerWave() end },`

- Do the following in LUA console:
```lua
p = Game.player
planet = p.frameBody
s = Space.SpawnShipLanded("wave", planet, math.deg2rad(7.1717977797), math.deg2rad(-172.82820222029))
s:AIFlyTo(p)
```

and it will immediately crash:

```
Program received signal SIGFPE, Arithmetic exception.
0x00000000005bbf91 in fastfloor (x=-6171278444.9345226) at ../../src/perlin.cpp:55
55      static int fastfloor( const double x ) { return int(x > 0 ? x : x - 1); }
(gdb) bt
#0  0x00000000005bbf91 in fastfloor (x=-6171278444.9345226) at ../../src/perlin.cpp:55
#1  0x00000000005bc090 in noise (x=-582540794.27544403, y=587133946.82504165, z=-4629607121.8382912) at ../../src/perlin.cpp:117
#2  0x0000000000658c5f in noise (p=...) at ../../../src/terrain/../perlin.h:11
#3  0x0000000000658e90 in TerrainNoise::billow_octavenoise (octaves=0, roughness=0.13030215574804646, lacunarity=4.4139197324889681, 
    p=...) at ../../../src/terrain/TerrainNoise.h:132
#4  0x0000000000658de3 in TerrainHeightFractal<TerrainHeightBarrenRock2>::GetHeight (this=0xbd4c880, p=...)
    at ../../../src/terrain/TerrainHeightBarrenRock2.cpp:26
#5  0x00000000005a5f26 in GeoSphere::GetHeight (this=0xbd4c700, p=...) at ../../src/GeoSphere.h:39
#6  0x00000000005a5e7d in TerrainBody::GetTerrainHeight (this=0xbd4c3f0, pos_=...) at ../../src/TerrainBody.cpp:129
#7  0x0000000000550cc8 in Ship::Blastoff (this=0xc9b6d40) at ../../src/Ship.cpp:660
#8  0x0000000000556396 in LaunchShip (ship=0xc9b6d40) at ../../src/ShipAICmd.cpp:194
#9  0x000000000055ba11 in AICmdFormation::TimeStepUpdate (this=0x1cba3080) at ../../src/ShipAICmd.cpp:1102
#10 0x000000000054b29c in Ship::AITimeStep (this=0xc9b6d40, timeStep=0.0166666675) at ../../src/Ship-AI.cpp:77
#11 0x000000000055d55f in ShipController::StaticUpdate (this=0xb4b2420, timeStep=0.0166666675) at ../../src/ShipController.cpp:18
#12 0x0000000000552863 in Ship::StaticUpdate (this=0xc9b6d40, timeStep=0.0166666675) at ../../src/Ship.cpp:961
#13 0x000000000057c511 in Space::TimeStep (this=0xbdac960, step=0.0166666675) at ../../src/Space.cpp:769
#14 0x000000000046a034 in Game::TimeStep (this=0xbdac650, step=0.0166666675) at ../../src/Game.cpp:240
#15 0x0000000000514a74 in Pi::MainLoop () at ../../src/Pi.cpp:1001
#16 0x000000000051469f in Pi::Start () at ../../src/Pi.cpp:937
#17 0x00000000005bbdb4 in main (argc=1, argv=0x7fffffffdfb8) at ../../src/main.cpp:58
```

As you see, `x` has a value that doesn't fit into an `int` letting the cast fail.

**Comment by laarmen** [comment]
@fluffyfreak you did some work in the terrain gen area semi-recently. Do you think this should still be open, ar has it gone stale?

**Comment by fluffyfreak** [comment]
It might still happen somewhere... but I have no idea how to find where it might happen.
We'd need some kind of autmated test setup to land AI ships on every pad of every station on every planet in every system in the galaxy.
Brute force it.

Best to close this until someone get a repro' case.

**Comment by laarmen** [comment]
I think just spawning police ships on every stationin the current system
should be easy enough

**Comment by fluffyfreak** [comment]
I was thinking more of brute-force testing the whole inhabited volume of the game ;)

**Comment by laarmen** [comment]
Can we instantiate several systems at once?

Also, ouch on the memory consumption, I guess!

**Comment by fluffyfreak** [comment]
No we can only do a single system at a time.
I guess what we'd do is create an "automated player" or re-use an "ai" ship as the player.
Start them in one system and then script them to go to each station in a system, possibly cheating somehow to speed up testing, jump them to another system and repeat until they'd visited all/some of the inhabited systems.

**Comment by fluffyfreak** [comment]
I've been thinking about how to do it, mostly because I wanted to get screenshots in an automated way from different altitudes/orbits of planets. However, I am not sure how to go about actually implementing it. Plus I'm busy doing other stuff :/

**Comment by impaktor** [comment]
I was plying with the idea of writing a visit-all-stations lua script for getting statistics on all commodity prices. It would be quite simple to write, but I don't know about speed or memmory consumption.

Also, it's a bit backwards, as I have access to the code that generates the market prices.

**Comment by laarmen** [comment]
Just a little bit, yes :-)

Is the terrain generated around any ship, or just the player?

**Comment by fluffyfreak** [comment]
Around the viewpoint, you can actually move the view away from the player, like the outside/sidereal cameras do, and the terrain will generate around that instead.

In theory, for my screenshot purporses I could just instance the player in a system, then put the camera wherever I like and everything should "just-work"... in theory.

Not as useful for testing spaceports/stations/etc though.

**Comment by laarmen** [comment]
Do we have an API to move the viewport?

**Comment by fluffyfreak** [comment]
No it's just done in the cameras*(/CameraController)*

**Comment by laarmen** [comment]
Now I'm thinking we need such an API :)

**Comment by fluffyfreak** [comment]
@laarmen it might make some things easier.
Maybe we cut n' paste thisthread onto the forum to discuss?
