### ISSUE TITLE
Safety / Master arm switch for weapons

### ISSUE THREAD

**Issue by johnbartholomew** [pioneerspacesim/pioneer#2410]
As mentioned on IRC by XB-7, it would be useful to have a master arm switch to reduce risk of accidental laser (or missile) discharge.

**Comment by impaktor** [comment]
Discussed on the forum: [link](http://pioneerspacesim.net/forum/viewtopic.php?f=3&t=303)

**Comment by impaktor** [comment]
Tracking this in #5547
