### ISSUE TITLE
Allow faction with no systems generated

### ISSUE THREAD

**Issue by jmf** [pioneerspacesim/pioneer#2420]
Haber Corp (which is mentioned in the wiki as story element) is a faction with 5 systems with specified names. At the moment it isn't possible to have a system that only has specified systems, there are always some systems generated.
Having such a system would make the story more believable.

All in all I think it would be very useful to have factions which don't get any system assigned to them automatically but can get written or semi-written systems assigned to them.

**Comment by joonicks** [comment]
should be simple to make a flag say "nonrandom" you can use in the custom factions and make the system generator honour it

**Comment by Web-eWorks** [comment]
You can set the faction expansion rate to `0.0` and it will only have the stars in the same sector as the homeworld plus whatever systems you manually claim it. I'll look into adding a "claims-only" mode but that's for another day and another issue as what is described here is already supported.
