### ISSUE TITLE
Improvements : Add full stop distance

### ISSUE THREAD

**Issue by NyankoSensei** [pioneerspacesim/pioneer#2425]
For a better gameplay i think is usefull have a full stop distance realtime updated widget in hud or in info view for rear and forward thrust.

**Comment by CmdrBugbear** [comment]
Brief update - links to ShipInfo.lua and en.json have been provided in the above thread that calculates distance to stop using main and retro thrusters.  Only snag is that I'm having trouble extracting the current speed via Lua.  Once that is resolved, this improvement should be able to be completed.

**Comment by impaktor** [comment]
closed by #3868
