### ISSUE TITLE
Multi-hop hyperspace route and other improvements to the Map

### ISSUE THREAD

**Issue by diegomilano** [pioneerspacesim/pioneer#2549]
Trying to manually plan a trip covering distances beyond the current range of the hyper-engine can be a frustrating experience:
- selecting a far destination moves the target out of the screen, and zooming out does not help, as the route disappears if the zoom factor is too low
- panning on the map is apparently not possible (and the instinctive click to try and drag will invariably change the hyperjump target) 
  -trying to determine a good "middle point" for an intermediate stop between two systems just by looking at the map is very difficult. 
- The possibility to drag the map would already simplify things much.
- It would be very nice if the board computer could provide suggestions for multi-hop routes, with intermediate stops in inhabited systems. I can imagine that an algorithm to provide optimal results could be complex/slow, but also suboptimal results would be better than having to plan the route manually.

**Comment by richardpl** [comment]
I think part of this have been implemented.
