### ISSUE TITLE
RendererLegacy::DrawPoints bug?

### ISSUE THREAD

**Issue by mvitorovic** [pioneerspacesim/pioneer#2567]
I'll be the first to admit that OpenGL is not my strongest point, but lines 408 and 409 say
```
	glVertexPointer(3, GL_FLOAT, 0, points);
	glColorPointer(4, GL_FLOAT, 0, colors);
```
while lines 344, 345 in RendererLegacy::DrawLines look much more correct to me:
```
	glVertexPointer(3, GL_FLOAT, sizeof(vector3f), v);
	glColorPointer(4, GL_FLOAT, sizeof(Color), c); 
```

**Comment by impaktor** [comment]
OK, yet another year has passed, and now those lines of code don't exist any more.

Please re-open if I'm wrong in closing.
