### ISSUE TITLE
Control panel buttons don't always reflect current view state

### ISSUE THREAD

**Issue by robn** [pioneerspacesim/pioneer#26]
Example:
- From normal flight (eg debug start), click comms. Comms button is now highlighted.
- Click camera. Comms button is no longer highlighted, but comms options are on screen.
- Click comms. Comms button is now highlighted, but comms options disappear.

I've seen similar things with the multifunction buttons (equipment, messages), the labels button (F10) and inconsistencies when switching to settings (Esc) and back.

**Comment by nozmajner** [comment]
Is this still an issue, after moving the buttons to imgui?

**Comment by impaktor** [comment]
Nope, #4093 closes
