### ISSUE TITLE
Render targets have broken alpha channel rendering (ie UI gauges)

### ISSUE THREAD

**Issue by robn** [pioneerspacesim/pioneer#2627]
Since #2525 UI gauges have been broken:

![screenshot - 060114 - 12 31 37](https://f.cloud.github.com/assets/130670/1847944/50498a36-7672-11e3-8740-66fbb4514936.png)

(bisected to @0b119ec0 to confirm).

It appears to be a similar cause to last time - the render target does not request a backing texture with an alpha channel.

The fix appears to be to change `Pi.cpp` line 163 from `TEXTURE_RGB_888` to `TEXTURE_RGBA_8888`. This sort of works in that the fill is masked, but still draws over the border:

![screenshot - 060114 - 12 39 25](https://f.cloud.github.com/assets/130670/1847977/6ccc1a88-7673-11e3-9fe1-7a11083abf42.png)

Since we draw the border first, then the mask, then the fill, it suggests to me that maybe the edge clamping is off. I can probably work around that, but I'd prefer to understand the root cause of the problem which is that the render target is subtly different to the normal screen target (provable, since the boot gauge works fine, and is drawn directly to the screen).

I'll try to find time to look into this but I've got other things to do first.

**Comment by nozmajner** [comment]
I think this is solved. And NewUI will be phased out eventually, so closing.
