### ISSUE TITLE
departure cloud on the ground?

### ISSUE THREAD

**Issue by radius75** [pioneerspacesim/pioneer#2639]
![screenshot-20140109-194640](https://f.cloud.github.com/assets/1929111/1880801/aa100466-795e-11e3-9388-e8f10cc973b4.png)

---

save http://speedy.sh/BCQtx/cloud  rev. 72045dbc7dcf47d15e5e245a4e8da1afca2cf36a

**Comment by HybridDog** [comment]
This didn't crop up for me yet.
