### ISSUE TITLE
rotating ships not showing correctly in main menu

### ISSUE THREAD

**Issue by Gudadantza** [pioneerspacesim/pioneer#2676]
I ve discovered that the rotating ships in the main menu are not showing correctly. The textures dissapear. And the ship is almost invisible, Something similar to a clipping effect or something like that.

It seems that the glitch is only appearing when you come back to the menu finishing a game in proccess.

Greetings

**Comment by HybridDog** [comment]
l can't reproduce this.

**Comment by fluffyfreak** [comment]
Very old issue, closing.
