### ISSUE TITLE
crash, assassination mission

### ISSUE THREAD

**Issue by radius75** [pioneerspacesim/pioneer#2689]
![beztytuu](https://f.cloud.github.com/assets/1929111/2004129/5267e5a0-869a-11e3-9e1e-144092e8b6e0.png)

how to reproduce:
- start new game  - Sol
- accept 1 assassination mission
- hyperflight to mission system
- hyperflight back to Sol

**Comment by richardpl** [comment]
Closing as this is very old report, if crash happens again feel free to create new issue.
