### ISSUE TITLE
strange lines after hyperjump

### ISSUE THREAD

**Issue by radius75** [pioneerspacesim/pioneer#2690]
Sometimes (after the hyperjump) drawn long lines.
Line moving from the direction of flight -> toward hypercloud
![screenshot-20140126-222941](https://f.cloud.github.com/assets/1929111/2005127/babbdb3e-86d1-11e3-9b35-84a581b267fc.png)
![screenshot-20140126-223030](https://f.cloud.github.com/assets/1929111/2005124/ad50b7ee-86d1-11e3-8ed4-aa4e720028ab.png)

**Comment by radius75** [comment]
How to reproduce for me:
- Start game
- turn ON ```Display speed lines```
- jump wherever
- select Arrival Hypercloud as target (LMB click)
- Jump wherever

#3303 not fixes this for me

----
BTW, another bug (maybe related with this)
- start game 
- select Sol or something (LMB click)
- rotate ship

green square moves along with the ship
![screenshot-20150103-173738](https://cloud.githubusercontent.com/assets/1929111/5602959/5a61018c-936f-11e4-9705-20bf06bc244f.png)

**Comment by radius75** [comment]
It seems to me that the speed line runs right through the centre of the camera view.
Ship (after hyperjump) moves (in manual control) in parallel with speed line. 
Is why this line seems to be "infinitely" long.

**Comment by Web-eWorks** [comment]
Closing this as the game's interface and display has come a long way since 2015.
