### ISSUE TITLE
flight controls remain active during typing save game name

### ISSUE THREAD

**Issue by Baobobafet** [pioneerspacesim/pioneer#2698]
While I was busy typing a name for my game save, I heard what sounded like a missile launch after incidentally typing the letter 'M' as part of the save title I chose.

Sure enough, when I checked, I was down one missile. 
When I loaded the save, it could be seen flying away from my ship.

Wouldn't leaving flight controls enabled on the save game screen cascade to other unintentional save and piloting errors?

**Comment by richardpl** [comment]
This does not happen any more. Closing.
