### ISSUE TITLE
No pads lights

### ISSUE THREAD

**Issue by NyankoSensei** [pioneerspacesim/pioneer#2719]
Pioneer build from git pioneer/master lose pad lights after hyperjump

![1](https://f.cloud.github.com/assets/5476493/2076104/5ff05b14-8d9b-11e3-8585-7cdefb6c2ab5.jpg)

i had the same issue with 14 pads station first of build 20131224 but after merging new UI no more noticed, now that issue is back again

Edit
By disabling 1 ground station seems pads lights works well again

**Comment by richardpl** [comment]
I do not think this is reproducible any more.

**Comment by fluffyfreak** [comment]
Actually just tested this and it still happens.
Started at Earth, hyperspace to Epsilon Eridani, landed at Itzalean, no pad lights!

Saved the game, quit and reloaded it, pad lights come back.

**Comment by mike-f1** [comment]
> Started at Earth, hyperspace to Epsilon Eridani, landed at Itzalean, no pad lights!

Just tried and it works as expected, then I jumped back and... well, it works as expected.

May be the #4608 solved this issue?
