### ISSUE TITLE
Consistent ESC key behavior

### ISSUE THREAD

**Issue by monolifed** [pioneerspacesim/pioneer#2727]
When I press ESC key It should close any menus and go back to ship view
But instead of that it opens options menu. It is a little inconvenient in my opinion

**Comment by impaktor** [comment]
@salborrelli is currently looking into this, discussion thread: http://pioneerspacesim.net/forum/viewtopic.php?f=3&t=385

**Comment by salborrelli** [comment]
@impaktor @robn @nozmajner @monolifed @lwho I've just published a document with a proposal for updating the effects of pressing the ESC key on a per-view basis. You can find the details in the Dev Forum: http://pioneerspacesim.net/forum/viewtopic.php?f=3&t=385#p4531

**Comment by Web-eWorks** [comment]
Closing as duplicate of #4851 as that issue better tracks the current situation.
