### ISSUE TITLE
Preview information for modules in particular for hyperdrives and guns.

### ISSUE THREAD

**Issue by Navi1982** [pioneerspacesim/pioneer#2820]
When buying hyperdrives, need to display information about the jump range, for the current ship. Can be displayed on the right side of the screen. But, it is better to display a dialog box where you can confirm your purchase for all modules. In the same dialog box can be displayed information on the jump range. So also, the dialog box will provide a choice of the turret where to install the gun. And of course at the program level, it is necessary to specify which dialog box to show for each module. Or in some other way.

**Comment by Web-eWorks** [comment]
This is (finally) in progress - tracking in #5951.
