### ISSUE TITLE
Scanner "blobs" are not drawn

### ISSUE THREAD

**Issue by robn** [pioneerspacesim/pioneer#2834]
Scanner contacts are drawn with two parts - a stalk and a blob (technical terms from the code). Since #2697 the blobs are no longer drawn.

![screenshot - 020414 - 22 18 02](https://cloud.githubusercontent.com/assets/130670/2590200/95e0ba7c-ba58-11e3-9383-7d30b6bf0dfe.png)

I've confirmed that commenting out `ShipCpanelMultiFuncDisplays.cpp:413` does nothing; ie the problem is there. I played with the state a bit but couldn't find anything that works.

/cc @Luomu.

**Comment by impaktor** [comment]
I wonder if we still have this problem? @robn, @dvol?

**Comment by nozmajner** [comment]
I suspect this is solved since then. Please reopen if not.
