### ISSUE TITLE
AIKill() causes game crash

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#2889]
If `someship:AIKill(Game.player)` is called in the time between the player dies and the explosion-death-animation is playing out, the game crashes, since `AIKill` is referencing an invalid object.

This is possibly the same thing that is happening in #887, and I guess shared pointer is the solution, but I'm not familiar with the code to determine if it's the same/double of that issue.

**Comment by laarmen** [comment]
This is probably a variant on #3704, I'll check it out tonight.

**Comment by laarmen** [comment]
Turns out, not a variant.

I just modified the AIKill Lua call to check if the target is still valid, and if not just return false. At some point userland has to take some responsibility.
