### ISSUE TITLE
Variable low thrust setting suggestion.

### ISSUE THREAD

**Issue by Phip-H** [pioneerspacesim/pioneer#2896]
Feature Request.
I would like to suggest a different mechanism for setting low thrust power other than pre-sets.
My preference would be:
that whilst holding down the low thrust key a gauge is placed on screen (like fuel, hull temp, etc) that can be set to any % value by rolling the mouse scroll wheel.

I would also like to add a note of thanks to development team on this project:
I wasted most of my student years playing the original elite on the Spectrum, it now looks like I will be able to waste my adult years as well:)

**Comment by impaktor** [comment]
I believe what is requested is now in current master (but not the current October build).
