### ISSUE TITLE
distress call should have some effect

### ISSUE THREAD

**Issue by ggergely** [pioneerspacesim/pioneer#29]
It should result in some (positive?) effect:
- "I'm under attack" should make a police go for your rescue?
- some repair/tow ship could be launched for broken down ships... even into interstellar regions.
- might attract pirates!

**Comment by Web-eWorks** [comment]
Closing as unimplemented; feature requests should go on the [forum](https://pioneerspacesim.net/forum), as we use Github for tracking actively-developed features and issues with currently-implemented functionality.

If you'd like to re-open this, please instead open a new PR with an implementation of the proposed functionality, thank you!
