### ISSUE TITLE
Map not shown correctly

### ISSUE THREAD

**Issue by flashrocket** [pioneerspacesim/pioneer#2920]
According to http://pioneerwiki.com/wiki/File:Manual_map_sector_02.png
but in mine i get this.
![screenshot from 2014-05-22 21 11 13](https://cloud.githubusercontent.com/assets/7582063/3056210/9f826502-e1c8-11e3-822c-1befa4f20366.png)

**Comment by impaktor** [comment]
I think this is a bit stale now, that we're on OpenGL 3.1, and changes have been made regarding the drawing of that map.
