### ISSUE TITLE
Searching in star maps crash, then out of game

### ISSUE THREAD

**Issue by foran7** [pioneerspacesim/pioneer#2934]
In star maps just type the name of system from mission and (x,y,z) together, then error, just like that screen
EX : Sol 0,0,0
　
　
　
![map search error](https://cloud.githubusercontent.com/assets/7800186/3199762/6179dc6a-ed6f-11e3-9e40-d33856b64172.jpg)

**Comment by richardpl** [comment]
Looks to be fixed, please report if it is not.
