### ISSUE TITLE
Fonts are "underlined" when multisampling is on

### ISSUE THREAD

**Issue by Tichy** [pioneerspacesim/pioneer#2954]
This happens mostly in game and sector view. Sometimes it's quite evidents, sometimes it's more subtle.
![underline](https://cloud.githubusercontent.com/assets/2348771/3307345/5af56d96-f66b-11e3-8b13-053fef0ceff6.png)

Arch Linux with Mesa 10.2.1 Ati r600 drivers.
With my system the artifacts appears when mutisampling is enabled.

With Catalyst 13.35 drivers they appear with multisampling >= 2x

**Comment by NicolasCARPi** [comment]
I also have this bug.

Screen : https://i.imgur.com/1LpdikU.jpg
Output.txt : http://pastebin.com/EtsRnJMS
Opengl.txt : http://pastebin.com/z5e1RWMj

Hope this helps :)

**Comment by Tichy** [comment]
Checked again. The bug is still there.
