### ISSUE TITLE
Tri-color relative velocity readout

### ISSUE THREAD

**Issue by corundscale** [pioneerspacesim/pioneer#2957]
Another feature request on my part:

Current relative velocity reading (when targeting another ship) is a bit tricky to eyeball quickly, because all near 0 values whether positive or negative are just different shades of purple. 

I propose changing to 3 instead of 2 colours - instead of blending between blue and red it would blend between blue and white for approach and red-white when moving away, pure white being displayed for zero relative velocity. 

It would make assessing relative velocity by just glancing on the meter much faster and easier.

**Comment by impaktor** [comment]
@nozmajner any thoughts on this, or should we close?

**Comment by nozmajner** [comment]
--> Should go to Dev forum UI  discussion.
