### ISSUE TITLE
Possible temperature overflow in Laze (-9, -11, -14)?

### ISSUE THREAD

**Issue by corundscale** [pioneerspacesim/pioneer#2961]
Two innermost planets (rocky planets with no significant atmospheres) have their temperatures listed as absolute 0 (-273 Celsius), despite being on tight orbits around hot 'O' type giant and despite the next planets outwards having temperatures measured in thousands.

**Comment by HybridDog** [comment]
Is the problem fixed?
https://github.com/pioneerspacesim/pioneer/pull/2984
