### ISSUE TITLE
Right click turns the ship to the last mouse position

### ISSUE THREAD

**Issue by vlastan** [pioneerspacesim/pioneer#298]
This can be pretty annoying sometimes, i think mouse position should be placed in front of the ship when you start to control your ship by the mouse. (reset mouse position when you start turning the ship by RMB)
Sometimes it happens that i briefly lose my ship control just because i right clicked when the mouse was pointing away from the direction i was moving trough.

**Comment by richardpl** [comment]
Can this still can be reproduced?

**Comment by nozmajner** [comment]
Nope, it works as intended now.
