### ISSUE TITLE
[interface] supergiants may break system view

### ISSUE THREAD

**Issue by corundscale** [pioneerspacesim/pioneer#2985]
Basically, supergiants and other stars that use very large graphics may make other system bodies inaccessible in system view if they are displayed below supergiant and companion pair they orbit, making system view effectively unusable in that system.

Example:
Uraygre (17, -19, 3)

**Comment by johnbartholomew** [comment]
@nozmajner We should try to fix this with the new-ui System Info View (#3564), but I think it will need some new icons for supergiant stars...
