### ISSUE TITLE
No Audio on Ubuntu 14.04

### ISSUE THREAD

**Issue by andrewobler** [pioneerspacesim/pioneer#3055]
Hello Pioneer community,

I'm running Pioneer on Ubuntu 14.04 "Trusty Tahr", and there seems to be no audio output whatsoever.  I've tried tinkering with various settings in the config.ini file but nothing has worked so far.  If I run the application from the terminal it generates this line:

Could not open audio: No such audio device

I'm fairly certain my audio setup is valid (it works perfectly with other applications), so I don't know why this is happening.  Pioneer itself also runs well besides this error.  Any help with this problem would be greatly appreciated.

Thank you!

**Comment by icarito** [comment]
Same here, no sound on Debian 8. 
ldd shows no SDL link.
Using pioneer-20150319-linux32.tar.bz2

**Comment by flashrocket** [comment]
20150512-linux64 has the problem

**Comment by richardpl** [comment]
Still happens?

**Comment by flashrocket** [comment]
Im sorry I cannot test it as I no longer use Ubuntu. Thank you for the
response though. Pioneer is a very fun game.

**Comment by richardpl** [comment]
I guess this was bug regarding old build available for download from project web page. Closing for now.

**Comment by ask-compu** [comment]
no audio for me on the 20190203 version from the site, ubuntu 14.04

**Comment by ask-compu** [comment]
i believe the audio DID work on the 20180203 version iirc

**Comment by ask-compu** [comment]
was gonna try building from source but apparently the configure script seems to think i don't have assimp version 3.2 even though i installed version 3.2

**Comment by ecraven** [comment]
> was gonna try building from source but apparently the configure script
> seems to think i don't have assimp version 3.2 even though i installed
> version 3.2

How did you compile? Are you using cmake? autotools are deprecated now.

Also, maybe try the flatpack recipe here:
https://flathub.org/apps/details/net.pioneerspacesim.Pioneer
