### ISSUE TITLE
Feature Request: Tool Tips in shopping menus.

### ISSUE THREAD

**Issue by cmsteffen-code** [pioneerspacesim/pioneer#3068]
I can't tell you how many times I've looked at a component for sale and wondered "What the heck is that, and why should I spend my hard earned SpaceBux on it?"

My solution: Tool Tips.

Let's say you're in the commodity market. You see something listed, and you're curious about it. Hover your mouse over it for 2 seconds, and a tool-tip will pop up and tell you about the item. Even if it's just a little fictional blurb to add "flavor" to the game.

Or if you're in the ship-outfitter, and you're looking at a new hyperdrive, but you want to know its specs, such as how far you can travel with it, or whatever. Hover the mouse for 2 seconds, and bam! There's all of its vitals, as well as a little quip about the company that created the item, or whatever.

Since we've got it set so that clicking on an item automatically buys or sells that item, hovering on the item would be the easiest way to implement Tool Tips. And I'd be happy to help write them, too. They could include a little bit of "lore" for the universe, which would be fun for me (since I like writing fiction).

I just think it would be nice to find all the useful information for various things just by hovering over them. Especially since there's no manual that comes with Pioneer.

**Comment by impaktor** [comment]
with pigui, we now have tooltip for ship equipment, and even small lore-text for commodity.

We can still improve the stats shown for ship equipment, but it's well known, and not what's discussed here.
