### ISSUE TITLE
LOT of jitter when leaving a spacestation

### ISSUE THREAD

**Issue by fluffyfreak** [pioneerspacesim/pioneer#3074]
There is a LOT of jitter when leaving a spacestation.
- Start at Barnards Star,
- undock, look back, let yourself drift away under manual control,
- once you leave it's frame-of-reference the station bounces around erratically and drastically if you're accelerating time,
- the more you accelerate time the more it jumps.

An awful quality [video of it in action](https://www.youtube.com/watch?v=WKGliaqXllc).

Andy

**Comment by clausimu** [comment]
I just wanted to confirm that this is still happening (linux build from Feb 05 2015). I have ditched the autopilot and am trying to play a pure manual flight game. Until you reach the frame of reference for a space station it always jumps around very erratically. It may not matter for collision detection etc. - but it sure kills the mood... :)

**Comment by impaktor** [comment]
@fluffyfreak didn't this get fixed as best could be, given float precision? Thus close?

**Comment by impaktor** [comment]
... in #3872 to be precise.
