### ISSUE TITLE
Auto-Save Makes No Sense.

### ISSUE THREAD

**Issue by haxys** [pioneerspacesim/pioneer#3101]
The current auto-save "feature" makes no logical sense. There's no way to know which save reflects the most recent save, and the saves aren't even listed in chronological order. Also, they seem to save multiple times in the same location, and apparently don't save frequently enough to really serve any purpose in protecting your progress through the game. What gives?

We need to fix Auto-Save. Here's what I'm thinking:
1. First and foremost, we need to have a timestamp so we can see which is the most recent save.
2. Second, the auto-saves should be ordered 1 through 9 from most recent to oldest, as opposed to 1 through 9 where the number has nothing to do with anything.
3. Auto-Save should happen immediately after docking with a station. That is the only time I can see a need for auto-save.

Any other thoughts?

**Comment by eloquentmess** [comment]
Sweet!
