### ISSUE TITLE
Crew pilot/autopilot Death screen (Old Bean)

### ISSUE THREAD

**Issue by PinBlacniP** [pioneerspacesim/pioneer#3124]
Select "Fly to vacinity of ..."
Select "Crew/Give orders to crew"
Select "Land at current target"
Set time acceleration to max.

Go to 'other screen'.

View underneath 'other screen',
shows all proceeding as expected,
... planet view ... landing view ...
Death Screen.

===================

in this case:
origin Pluto target "Mexico City"
other screen = 'F2', then 'F3'/ship details.

**Comment by impaktor** [comment]
Outdated --> closing.
