### ISSUE TITLE
Trade ships stuck in the centre of the sun

### ISSUE THREAD

**Issue by johnbartholomew** [pioneerspacesim/pioneer#3128]
1. Start new game on Earth.
2. Open the system orbit view.
3. Turn on display of all ships.
4. Zoom in a bit.
5. Observe that there are ships stuck at the centre of the sun.

Screenshot:
![sundiving-tradeships](https://cloud.githubusercontent.com/assets/115749/3932675/aca31900-246e-11e4-9e73-f8909ae55ece.png)

**Comment by corundscale** [comment]
Clicking on any of those ships, then switching to normal view and tracking the HUD marker indicates that they are actually in completely different location, usually docked somewhere safe, so it seems to actually be a case of #3509 .
