### ISSUE TITLE
game sometimes crashed, after RETURN from Options Menu

### ISSUE THREAD

**Issue by radius75** [pioneerspacesim/pioneer#3177]
![bez tytulu](https://cloud.githubusercontent.com/assets/1929111/4257181/65cc4a2a-3ac0-11e4-82ef-5086100b2ba1.png)
- run pioneer
- [Options]
- [Return to menu] = crash

**Comment by Web-eWorks** [comment]
Closing this as the Options window has been ported to pigui and newUI is deprecated.
