### ISSUE TITLE
Landing on terrain with landing gear folded up has strange consequences

### ISSUE THREAD

**Issue by Brianetta** [pioneerspacesim/pioneer#318]
**Also included in this would be landing on your roof, with or without your landing gear down.**

When your ship hits the ground without landing, it can move right through it, and comes to rest some metres further down, often at an arbitrary attitude.  If your ship hits the ground at a slow speed, it passes through without even incurring any damage.  Upon coming to rest, your ship will often slide along the plane upon which it has found itself.  Sometimes it will slide for a good long distance, occasionally underneath city buildings if they are nearby.

Attitude can be changed at will, without incurring further damage.  Even the velocity of your ship can be changed using the thrusters, with damage only being received above some threshold speed.

Needless to say, hitting the floor with anything other than your wheels is not particularly difficult to achieve, and the slow speeds necessary to survive this are equally easy to achieve if a player is attempting to land rough.

Suggestions:
- Hitting the ground should present a hard barrier to the ship.
  - Hitting it at slow speeds should cause it to stop.
  - High speeds should (perhaps) cause it to bounce, especially at high horizontal speed.
- In all cases, damage proportional to the square of the speed should be received by the ship.
  - The ship should come to rest, or no screwed up landing is survivable.
- At no point should a player who accidentally lands with gear up sink into the floor to see the stars beneath them.

**Comment by mike-f1** [comment]
Given recent PR, is it time to close?

**Comment by impaktor** [comment]
@mike-f1 has this been fixed?

**Comment by mike-f1** [comment]
> Hitting it at slow speeds should cause it to stop.

Done

> High speeds should (perhaps) cause it to bounce, especially at high horizontal speed.

Done

> The ship should come to rest, or no screwed up landing is survivable.

Done

> At no point should a player who accidentally lands with gear up sink into the floor to see the stars beneath them

Almost

> Attitude can be changed at will, without incurring further damage

No

There's a some things described in title which are no more happening, though the only
remaining one is to go deep under the ground. though the "sinking" has ended, and if
you go under terrain is only for limited time and deep after which you emerge.

Another points is that a lot of references are old and unuseful...

Don't know, if it's not fixed then it is at least in a needs to be renewed.
