### ISSUE TITLE
Can not change video resolution in Ubuntu 14.04 x64

### ISSUE THREAD

**Issue by Levan7** [pioneerspacesim/pioneer#3186]
I downloaded Pioneer linux x64 version and I noticed that I can not change video resolution in this game neither in full screen or windowed it only shows the top resolution of my screen, However the compiled version of this game has the ability to change resolution and the sound works

Terminal output if it is any help
The binary version
https://drive.google.com/file/d/0B2EbWg9VhdvaRTNPNmFCeUZDTWM/edit?usp=sharing
Compiled version
https://drive.google.com/file/d/0B2EbWg9VhdvaR3ZmaEFoZzFmekE/edit?usp=sharing

**Comment by Web-eWorks** [comment]
As this issue is almost five years old and we now link against a shared SDL2 v2.0.9, I believe this issue can be closed. If anyone is still experiencing resolution issues after all these years, please feel free to open a new, on-topic issue with current details.
