### ISSUE TITLE
Strange docking in Big Crappy

### ISSUE THREAD

**Issue by walterar** [pioneerspacesim/pioneer#3240]
The ship entered of queue, but only when there are other docked ships.
http://youtu.be/bojaF1svM8Y
This only happens in Scout+, where there is frequently coupled ships. If the problem is not obvious, you should generate one or more ships docked from the console.
Not so with hoop_spacestation, this only happens with big_crappy_spacestation.

**Comment by walterar** [comment]
@Impaktor The new Big Crappy has the same problem. The ships come into reverse.

I did not understand what you mean by optimization. You can clearing that?

**Comment by fluffyfreak** [comment]
"Optimisation" just means making it run faster, so going from 3 frames-per-second to 20 frames-per-second.

Docking direction is controlled by the modeller, so the strange docking needs to be modified for the stations by changing the orientation of the entrance and exit docking locators. Ping @nozmajner

**Comment by impaktor** [comment]
The optimization I was referring to was that perhaps you had turned of compile time optimization (`-O2` or `-O3` flag in gcc/g++) at some earlier point in time when debugging the code, and forgotten to turn it back on? Default is to compile an optimized version of pioneer, which is the case for the official release found on the pioneer download page.

**Comment by walterar** [comment]
You mean this?
make -j 5 'CXXFLAGS+=-O2 -pipe -w'

**Comment by walterar** [comment]
-O3 Cause strange things in my system. ;)

**Comment by nozmajner** [comment]
@fluffyfreak : Oh, it seems I forgot to properly test the docking with autopilot. It felt good with manual docking. I check as soon as I can download the latest build here at my workplace.

**Comment by impaktor** [comment]
@walterar Yes. if it uses the `-O2` then all is fine. Sometimes `-O3` can actually be slower for some programs (I actually have one of those). (Turning off optimization is done with `-O0` or just omitting it for gcc/g++, which will give shorter compile time, but slower run time).

But I hope you're not seeing a 20 times longer star up time anymore with the latest changes @fluffyfreak merged (SGM format).

**Comment by walterar** [comment]
Loading took: 14552.289204 milliseconds

Thanks to improvements made by fluffyfreak in the engine. I can now enjoy the work of nozmajner. :)

**Comment by nozmajner** [comment]
Strange. When I flip the entrance markers, the autopilot approaches from the other end and goes in reverse from that direction. And it has a hard time finding a good direction for approach. Same if I flip all the markers for all bays too.
Here's a dock.dae where all of the markers are rotated to the other direction:
https://dl.dropboxusercontent.com/u/456051/pioneer/station_docking_A.dae

**Comment by walterar** [comment]
It has greatly improved. But still keeps incoming of aft.

**Comment by nozmajner** [comment]
Yes, that's what I'm saying.

**Comment by walterar** [comment]
It seems that the only one who can solve this issue is @fluffyfreak  The bad thing, is that I got used to enter my car into the garage in reverse. Hi Andy  :))

**Comment by walterar** [comment]
Replaced by #3344
