### ISSUE TITLE
Show profession & affiliation over station faces

### ISSUE THREAD

**Issue by robn** [pioneerspacesim/pioneer#327]
Idea from @Luomu in #319:

It is a bit pointless/annoying to have a flashing thing on a static avatar. Instead, we could add some other stuff like the person's name, profession (will be fun to generate some) or affiliation (with logo, if we ever have any). Along these lines:

<img src=http://i.imgur.com/YYx7Z.png />

**Comment by Web-eWorks** [comment]
NPC name and job description is already displayed in master; additional job titles are a different matter entirely.

Closing as implemented; feature requests and discussion should go on the [forum](https://pioneerspacesim.net/forum), as we use Github for tracking actively-developed features and issues with currently-implemented functionality.

If you'd like to re-open this, please instead open a new PR with an implementation of the proposed functionality, thank you!
