### ISSUE TITLE
Pioneer compilation instructions

### ISSUE THREAD

**Issue by CmdrBugbear** [pioneerspacesim/pioneer#3270]
This may just be me, but I lost an hour trying to get VS2013 to compile Pioneer.
I was getting a 'Could not find SDL_stinc.h' error.
After re-reading the instructions, I realised that I hadn't downloaded the pioneer-thirdparty package, so I downloaded and stored alongside the pioneer-master directory.
It's a simple thing but I was getting caught out by the fact that the downloaded and extracted directory was named "pioneer-thirdparty-master" rather than the directory name expected: "pioneer-thirdparty".

I admit this is a really dumb error to report but would it be worth updating the compilation instructions, or ensuring that the thirdparty tools are named as expected by the code?  (Maybe I downloaded them from the wron link...)

**Comment by fluffyfreak** [comment]
@CmdrBugbear do you post as `nick` on the dev forum? If so then the only problem is the folder's name. Just right-click on it and rename `pioneer-thirdparty-master` to `pioneer-thirdparty`. Everything should just work.
