### ISSUE TITLE
Pioneer doesn't start on OSX Yosemite or Win7

### ISSUE THREAD

**Issue by jfacoustic** [pioneerspacesim/pioneer#3280]
Both graphics cards claim to support openGL 3.3 and have the latest drivers.  For the mac, I click the application and it bounces for a little bit, then disappears.  I've tried the version that the FAQ mentions and it keeps freezing.  For the windows, it opens, but get's stuck in the loading screen.  Anything I'm doing wrong?  Permissions issue possibly?  Thanks.

**Comment by fluffyfreak** [comment]
Ah no not 2.1 but I thought yours might do 3.1 but wouldn't start?

**Comment by impaktor** [comment]
Building now.

**Comment by impaktor** [comment]
I don't know what I have, or what the hardware's supposed to work with. But trying out your branch, I get:

    SDL Version 2.0.3
    Failed to set video mode. (Could not create GL context). Re-trying with GL context flags cleared and compatiblity profile requested.
    Failed to set video mode. (Could not create GL context). Re-trying with 16-bit depth buffer
    error: Failed to set video mode: Could not create GL context

**Comment by fluffyfreak** [comment]
Bummer, was hoping that might be the magical incantation that made the OpenGL genie happy :/

**Comment by impaktor** [comment]
I did get a window that poped up at me for like 0.1 seconds, before the error message in a small gray window.

Hm, removing the last commit and recompiling, I still get the same 0.1 seconds flicker, and then this:

    SDL Version 2.0.3
    Failed to set video mode. (Could not create GL context). Re-trying with 16-bit depth buffer
    error: Failed to set video mode: Could not create GL context

**Comment by fluffyfreak** [comment]
Yeah the only change is to retry with a different combination of context/profile flags. OSX forces a certain combination for versions of OpenGL above 3.1 but the alternatives might work better on some hardware than others. Worth a try. 

We really need someone who has this specific problem to give this a try.

**Comment by fluffyfreak** [comment]
@jfacoustic & @eloquentmess is there any update on this? have you tried the latest versions which have bug fixes?

**Comment by impaktor** [comment]
I guess it falls on @eloquentmess to build a new "latest version" for OSX.

**Comment by impaktor** [comment]
OK, so new OSX build is out (thanks @eloquentmess), please give it a try @jfacoustic: http://sourceforge.net/projects/pioneerspacesim/files/pioneer-20150125-osx.zip/download

**Comment by eloquentmess** [comment]
Uploading another version as I type this.

**Comment by impaktor** [comment]
_Summary:_ we definitely had some bug on Mac back in December, but new builds for Mac have been made since, and we have not heard anything back when wanting to confirm with OP that they work for him too. 6 months later: Closing.
