### ISSUE TITLE
ChatForm a vertical space wanted

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#3284]
This has been bugging me for quite some time: I'd like an extra vertical space where the pointer indicates in the attached images, perhaps of equivalent size of one of those check boxes.

Ping @radius75 seems to know the way around `ui/StationView/ChatForm.lua`

(I would really love some documentation on the lua UI stuff.)

_Also, first screenshot is a little treat of what is to come_
![screenshot-20141227-125314](https://cloud.githubusercontent.com/assets/619390/5561201/529bf9a4-8dc8-11e4-8f52-819ea4eabd99.png)
![screenshot-20141227-125325](https://cloud.githubusercontent.com/assets/619390/5561203/5a7a06f2-8dc8-11e4-8b7d-b477a6170bd9.png)

**Comment by impaktor** [comment]
## First suggestion:

> ...change `ui:VBox()` to `ui:VBox(5)`

This inserts space at other places too, such as just above the "Hang up" button.

## Second suggestion:

> Alternatively, you can wrap just the message in a margin to give it some extra space: `box:PackEnd(ui:Margin(5, "HORIZONTAL", ui:Scroller(ui:MultiLineText(self.message))))`

I assume you meant: `box:PackEnd(ui:Margin(5, "VERTICAL", ui:Scroller(ui:MultiLineText(self.message))))`, but doing that adds space also above the message text, which looks strange.

## Third suggestion:
code above by ®radius75.


## Result with second suggestion
Gives extra vertical space above the message, not just below.
![screenshot-20150105-103436](https://cloud.githubusercontent.com/assets/619390/5611760/d58e3d64-94ca-11e4-9f63-2dac4152a857.png)

## Result with third suggestion
Gives space just below the message, which is what I think looks best. Thus I'm going to push this fix to master if I hear no strong objections.
![screenshot-20150105-103704](https://cloud.githubusercontent.com/assets/619390/5611765/e2cc2950-94ca-11e4-95ca-e767b7589c47.png)

**Comment by robn** [comment]
Yeah, I was working from memory. You can do a BOTTOM margin if you like as well.

I don't think I care strongly enough. I don't like it, but I think that's more because of limitations in the layout engine that I wish weren't there.

So yeah, merge away.
