### ISSUE TITLE
Segfault in shipmarket

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#3301]
On latest master: a1d500ce7fba480363a069bcf376fb8310593a87

ShipMarket -> mark a ship -> crash.

I noticed the crash after I built the SGM files, so I removed them all, but still crash:

    Loading took: 69875.622233 milliseconds
    CreateCollisionMesh for : (ac33)
    CreateCollisionMesh for : (amphiesma)
    CreateCollisionMesh for : (deneb)
    CreateCollisionMesh for : (dsminer)
    CreateCollisionMesh for : (kanara_civ)
    CreateCollisionMesh for : (lunarshuttle)
    CreateCollisionMesh for : (malabar)
    CreateCollisionMesh for : (molamola)
    CreateCollisionMesh for : (natrix)
    CreateCollisionMesh for : (nerodia)
    CreateCollisionMesh for : (pumpkinseed)
    CreateCollisionMesh for : (sinonatrix)
    CreateCollisionMesh for : (storeria)
    CreateCollisionMesh for : (varada)
    CreateCollisionMesh for : (vatakara)
    CreateCollisionMesh for : (venturestar)
    CreateCollisionMesh for : (wave)
    CreateCollisionMesh for : (xylophis)
    Creating new galaxy generator 'legacy' version 1
    Clearing and re-using previous Galaxy object
    StarSystemCache: misses: 0, slave hits: 0, master hits: 0
    SectorCache: misses: 101, slave hits: 0, master hits: 1
    Barnard's Star:
        height fractal: Ellipsoid
        colour fractal: StarM
        seed: 535703695
    CreateCollisionMesh for : (kanara)
    
    Program received signal SIGSEGV, Segmentation fault.
    Graphics::RendererOGL::DrawBuffer (this=0xbda250, vb=0x0, state=0x22327b0, mat=0x18cb0710, pt=Graphics::TRIANGLES) at opengl/RendererGL.cpp:486
    486		gvb->Bind();
    (gdb) bt
    #0  Graphics::RendererOGL::DrawBuffer (this=0xbda250, vb=0x0, state=0x22327b0, mat=0x18cb0710, pt=Graphics::TRIANGLES) at opengl/RendererGL.cpp:486
    #1  0x00000000005e0864 in SceneGraph::Group::RenderChildren (this=<optimized out>, trans=..., rd=0x7fffffffcc30) at Group.cpp:129
    #2  0x00000000005ea5b9 in SceneGraph::MatrixTransform::Render (this=<optimized out>, trans=..., rd=<optimized out>) at MatrixTransform.cpp:39
    #3  0x00000000005e0864 in SceneGraph::Group::RenderChildren (this=<optimized out>, trans=..., rd=0x7fffffffcc30) at Group.cpp:129
    #4  0x00000000005ea5b9 in SceneGraph::MatrixTransform::Render (this=<optimized out>, trans=..., rd=<optimized out>) at MatrixTransform.cpp:39
    #5  0x00000000005e0864 in SceneGraph::Group::RenderChildren (this=<optimized out>, trans=..., rd=0x7fffffffcc30) at Group.cpp:129
    #6  0x00000000005e0864 in SceneGraph::Group::RenderChildren (this=<optimized out>, trans=..., rd=0x7fffffffcc30) at Group.cpp:129
    #7  0x00000000005e0864 in SceneGraph::Group::RenderChildren (this=<optimized out>, trans=..., rd=0x7fffffffcc30) at Group.cpp:129
    #8  0x00000000005eb6f9 in SceneGraph::Model::Render (this=0x2093f890, trans=..., rd=<optimized out>) at Model.cpp:129
    #9  0x000000000068f527 in GameUI::ModelSpinner::Draw (this=0x20931e80) at ModelSpinner.cpp:74
    #10 0x000000000065a143 in UI::Context::DrawWidget (this=0xc52a40, w=0x20931e80) at Context.cpp:237
    #11 0x0000000000657d3f in UI::Container::Draw (this=0x206ffe40) at Container.cpp:32
    #12 0x000000000065a143 in UI::Context::DrawWidget (this=0xc52a40, w=0x206ffe40) at Context.cpp:237
    #13 0x0000000000657d3f in UI::Container::Draw (this=0x1eb9680) at Container.cpp:32
    #14 0x000000000065a143 in UI::Context::DrawWidget (this=0xc52a40, w=0x1eb9680) at Context.cpp:237
    #15 0x0000000000657d3f in UI::Container::Draw (this=0x20949bf0) at Container.cpp:32
    #16 0x000000000065a143 in UI::Context::DrawWidget (this=0xc52a40, w=0x20949bf0) at Context.cpp:237
    #17 0x0000000000657d3f in UI::Container::Draw (this=0x1f478640) at Container.cpp:32
    #18 0x000000000065a143 in UI::Context::DrawWidget (this=0xc52a40, w=0x1f478640) at Context.cpp:237
    #19 0x0000000000657d3f in UI::Container::Draw (this=0x1f479900) at Container.cpp:32
    #20 0x000000000065a143 in UI::Context::DrawWidget (this=0xc52a40, w=0x1f479900) at Context.cpp:237
    #21 0x0000000000657d3f in UI::Container::Draw (this=0x1f4796a0) at Container.cpp:32
    #22 0x0000000000687d79 in UI::Background::Draw (this=0x1f4796a0) at Background.cpp:32
    #23 0x000000000065a143 in UI::Context::DrawWidget (this=0xc52a40, w=0x1f4796a0) at Context.cpp:237
    #24 0x0000000000657d3f in UI::Container::Draw (this=0x1f479430) at Container.cpp:32
    #25 0x000000000065a143 in UI::Context::DrawWidget (this=0xc52a40, w=0x1f479430) at Context.cpp:237
    #26 0x0000000000657d3f in UI::Container::Draw (this=0x1f478c70) at Container.cpp:32
    #27 0x000000000065a143 in UI::Context::DrawWidget (this=0xc52a40, w=0x1f478c70) at Context.cpp:237
    #28 0x0000000000657d3f in UI::Container::Draw (this=0x1f477940) at Container.cpp:32
    #29 0x000000000065a143 in UI::Context::DrawWidget (this=0xc52a40, w=0x1f477940) at Context.cpp:237
    #30 0x0000000000657d3f in UI::Container::Draw (this=0x1f477480) at Container.cpp:32
    #31 0x000000000065a143 in UI::Context::DrawWidget (this=0xc52a40, w=0x1f477480) at Context.cpp:237
    #32 0x0000000000657d3f in UI::Container::Draw (this=0x19747fc0) at Container.cpp:32
    #33 0x000000000065a143 in UI::Context::DrawWidget (this=this@entry=0xc52a40, w=0x19747fc0) at Context.cpp:237
    #34 0x000000000065a71e in UI::Context::Draw (this=0xc52a40) at Context.cpp:158
    #35 0x00000000004c8540 in Pi::MainLoop () at Pi.cpp:1250
    #36 0x00000000004c9352 in Pi::Start () at Pi.cpp:1075
    #37 0x000000000040f90d in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:130

**Comment by fluffyfreak** [comment]
Fixed by #3302
