### ISSUE TITLE
Assert when loading a save game (Linux)

### ISSUE THREAD

**Issue by fluffyfreak** [pioneerspacesim/pioneer#3305]
@walterar has pointed out this issue:
> Returned to appear this problem:
>
> opengl/VertexBufferGL.cpp:61: Graphics::OGL::VertexBuffer::VertexBuffer(const Graphics::VertexBufferDesc&): Assertion `m_desc.numVertices > 0' failed.
>
> Is relevant to this PR?

> This sometimes occurs when attempting to retrieve a recently saved game. It is likely that the problem is in the serializer.

After merging in #3303

**Comment by walterar** [comment]
For me, there is nothing better than to try the game, playing.

For me, there is nothing worse than, after playing hours, save the game, and not recover it.

Last night happened again and I went to sleep wanting to break everything.

Clearly, lately, there are new things that the serializer can not handle correctly.

I'll pray for someone to find the solution. :)

**Comment by laarmen** [comment]
I'm wondering if it has anything to do with #3279. After all, there was
some work on the serializer in there, although I can't figure out how
this would impact you.

**Comment by walterar** [comment]
Wanted! Specialists in serializer of Pioneer.
Mission: Find what the serializer can not handle in the new orbital station.
Reward: 1 Kanara, used, ex Police, in good condition.

**Comment by fluffyfreak** [comment]
Hah! Yes sorry @walterar work has gone crazy busy this week. If anyone else wants to give it a try before I get chance then go for it!

**Comment by walterar** [comment]
I'll have to climb the reward then. :)

**Comment by fluffyfreak** [comment]
I've tried saving and loading in full debug, no problems. Is this with plain Pioneer or with Scout+?

**Comment by walterar** [comment]
If the space station is empty, no problems. TradeShips.lua distributes traffic of ships throughout the system, and it is rare to find any NPC ship in the station at stake.

The only way I can generate traffic of 64 ships is with the Scout + Traffic.lua integrated module that replaces TradeShips.lua but traffic is on demand. If you want I send the module adapted for Pioneer engine clean.

@impaktor said it had tested the station with 64 ships; perhaps  can tell us something.

**Comment by fluffyfreak** [comment]
If it's a standard Pioneer save game can you upload it somewhere so I can try it out?

**Comment by impaktor** [comment]
I never tested the station with 64 ships at once (at least I don't remember it). However, I do know I tested spawning (at least one) of each ship available in pioneer, and I also checked that `numDocks==64`. Perhaps I had 20 ships at once in the station at the most.

But foolishly when I tested save/load I only had one ship (or thereabouts). 

For testing, this is handy:

    s=import("Game").player:GetDockedWith()
    import("Space").SpawnShipDocked("varada", s)
    import("Space").SpawnShipDocked("storeria", s)

**Comment by fluffyfreak** [comment]
Tried load/save with 13 ships docked at Gates spacestation in orbit around Earth and it was fine.

**Comment by walterar** [comment]
-- console.lua
--
Game  = import("Game")
Space = import("Space")

function sp(ShipsCount)
  local basePort = Game.player:GetDockedWith()
  ShipsCount=ShipsCount or basePort.numDocks - 2
  for i = 1, ShipsCount do
    Space.SpawnShipDocked("varada", basePort)
--    Space.SpawnShipDocked("storeria", basePort)
  end
end

Create with this a console.lua and put it in the user directory Pioneer (along with config.ini).

Pioneer Launches in Barnard.

Open the console and enter: sp ()

Look at the ships stationed in the Orbital Station.

Save your game.

Close Pioneer.

Pioneer Launches in saved game.

**Comment by nozmajner** [comment]
I've just tested this on windows. Filled up the station with ships, and saved. It asserted on reload.
![assert](https://cloud.githubusercontent.com/assets/4182678/5671941/4fd6fd9a-978c-11e4-89e5-12f0d31c4d0b.png)
Here's my save and the usual output files: https://dl.dropboxusercontent.com/u/456051/pioneer/stationcrash.zip

**Comment by walterar** [comment]
It seems the problem is not the amount of ships.
Try with: sp ("1")
With only one ship, this appear.

**Comment by fluffyfreak** [comment]
@nozmajner that's another assert to do with the scanner, I committed a fix for it last night.

@walterar still not seeing a problem with the serialisation. Can you try with the latest code? As I said above I merged a fix for that assert last night.

**Comment by laarmen** [comment]
I'll try it out tomorrow, see if I can trigger the assert as well.

**Comment by walterar** [comment]
When retrieving the game, I have 1fps.

Two new problems in my master:
The text of fuel (propellant) is black.
The date and time are not see.
![propeller](https://cloud.githubusercontent.com/assets/1334989/5679791/3e5e29e2-97e3-11e4-9a29-f34495d3472b.png)
The reason is that I am using the character "space" to improve the tabulation of the text. But this, convert the color to black.
ej: 
   "FUEL" : {
      "description" : "",
      "message" : "        Propelente"
   },

**Comment by laarmen** [comment]
Setting aside the color matter, white space is not the proper way to solve
this kind of problem. @impaktor and @robn know more about this than I do,
though.

**Comment by walterar** [comment]
Unfortunately it's the only way I found to "accommodate" the text. :(  If there is another way, I am very interested in knowing it. But, if the color turned black when it finds a space, I think it should not happen.

**Comment by fluffyfreak** [comment]
@walterar ok so the crash is fixed but i've broken some text colours/rendering.

I'll close this and then we'll add a new issue about the text colour.

**Comment by walterar** [comment]
:+1:

**Comment by impaktor** [comment]
> Setting aside the color matter, white space is not the proper way to solve this kind of problem. 

Indeed no. 

In Worldview.cpp you have

	m_hudFuelGauge = new Gui::MeterBar(100.f, Lang::FUEL, Color(255, 255, 0, 204));

Where you can concatenate the FUEL string with a space, although that is horrible as well, in my opinion. The MeterBar should be remade anyway to use an icon instead of text and look more like New-UI, if anyone is up for the challenge.
