### ISSUE TITLE
Strange rendering

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#3308]
After the latest merges yesterday/today: #3303 (and #3306) I'm seeing some pretty funky stuff.

When flying it seems like the ground, or parts of it, follows me up into the air, and it looks like the city buildings are sunk into the earth when starting a game. It's a bit difficult to take a screenshot of, since a video would be needed to show it properly, but this is also pretty strange:

![screenshot-20150108-110454](https://cloud.githubusercontent.com/assets/619390/5661019/efc9b9ca-9726-11e4-85b3-ddfe1b05ddde.png)

![screenshot-20150108-111201](https://cloud.githubusercontent.com/assets/619390/5661059/51c1edc8-9727-11e4-965d-ab6cd6ed9051.png)

Interestingly, Barnard's Star seems to work fine, but not starting from a planet side space port.

**Comment by radius75** [comment]
These screens is very similar to https://github.com/pioneerspacesim/pioneer/issues/2779

**Comment by impaktor** [comment]
Perhaps better to show as an animated git. Seems like the terrain/horizon is clipping all the text, i.e. no text below the horizon in Worldview. BTW, this is on latest master, eacf40a97a2bc8a365e16993db80b9b01f183875

![ps1](https://cloud.githubusercontent.com/assets/619390/5685201/75066144-9838-11e4-8d85-710140543fff.gif)

**Comment by fluffyfreak** [comment]
Yeah that's a z-buffer problem alright, you can even see the tower sticking up through the numbers :)

**Comment by fluffyfreak** [comment]
@impaktor I have now seen this on my Linux build!!!

I'll try and look into it tonight, I suspect it just needs to be clearing the z-buffer at the start of UI rendering and that's been lost somewhere.

**Comment by fluffyfreak** [comment]
Got stuck debugging something for another PR for 4 hours :sob:
