### ISSUE TITLE
Text Colouring is wrong.

### ISSUE THREAD

**Issue by fluffyfreak** [pioneerspacesim/pioneer#3310]
@walterar has pointed out that some of the text colouring is black where it should be other colours.

This is after my recent #3304 merge

**Comment by walterar** [comment]
Messages (GameLog) overlap.
![gamelog](https://cloud.githubusercontent.com/assets/1334989/5680905/d11d5010-97f1-11e4-89c2-39d6efbda5e3.png)
MessageBox messages appear in black.
![messagebox](https://cloud.githubusercontent.com/assets/1334989/5680908/ddc3d474-97f1-11e4-8020-5d9c98659ba7.png)

**Comment by walterar** [comment]
Missing text (black?) On the initial screen.
![captura de pantalla de 2015-01-09 12 05 22](https://cloud.githubusercontent.com/assets/1334989/5681558/527f3104-97f8-11e4-90f0-eec5e4f552b5.png)

**Comment by walterar** [comment]
#3312 fix this
