### ISSUE TITLE
Saved games change the alignment of guns

### ISSUE THREAD

**Issue by walterar** [pioneerspacesim/pioneer#3313]
This is especially noticeable in ships without tag_gun.

To probe, put this in the MOD directory:
https://dl.dropboxusercontent.com/u/15391580/Pioneer/Sidewinder_init.zip

Pioneer launch in Earth.
Launch the ship. Away from the station 100 Km, to avoid the stupid police. :)
Now shoot the cannon.
See the alignment of the projectiles.
Save the game and exit.
Retrieve the saved game and watch.

**Comment by nozmajner** [comment]
It doesn't seem to change at all if the ship has gun tag. At least it doesn't with the Pumpkinseed.
This is what happens with that sidewinder (just to provide visuals :) )
![screenshot-20150110-154311](https://cloud.githubusercontent.com/assets/4182678/5691956/8f2f6e56-98df-11e4-82e6-20b777b67c15.png)
Win7 20140109

**Comment by walterar** [comment]
Yes, on start with saved game, instead of shooting at correct direction (12  in the watch ), sometimes shoot in direction at 3 or 6. Here we see that is shooting in the direction of 3.

This is good if you you are attacked by an pirate with that ship. But boring. ;)

**Comment by walterar** [comment]
This worked fine before merging #3252. Hopefully flufyfreak have the solution before forget what did :)

**Comment by fluffyfreak** [comment]
Ah, that's interesting.

**Comment by fluffyfreak** [comment]
So if a ship has a gun tag locator then everything is fine, but the sidewinder doesn't have a gun tag and so it gets corrupted? 

Is that correct?

**Comment by walterar** [comment]
Correct

**Comment by fluffyfreak** [comment]
OK then I think I've found the cause of it, bit of a pain. It doesn't happen for Pioneer itself because all of the ships have gun tags I think. I hadn't taken into consideration mods and none standard ships that were relying on some other behaviour.

I'm looking into restoring it now.

**Comment by walterar** [comment]
But as you can see, when you start working (even better than tag_gun) but everything changes with the save.

**Comment by fluffyfreak** [comment]
Well when I put back the original code the laser now fire backwards. But nothing else in that area has changed. Can you give me the original sidewinder lua ship definition to look at?

**Comment by walterar** [comment]
define_ship {
  name='Sidewinder',
  ship_class='light_scout',
  manufacturer='p66',
  model='sidie_m',
  forward_thrust = 5e6,
  reverse_thrust = 25e5,
  up_thrust = 15e5,
  down_thrust = 15e5,
  left_thrust = 15e5,
  right_thrust = 15e5,
  angular_thrust = 2e7,

  gun_mounts = {
    { v(0,0,-16), v(0,0,-1),9, 'HORIZONTAL' },
    { v(0,0,15), v(0,0,1),9, 'HORIZONTAL' },
  },

  slots = {
    cargo = 30,
    atmo_shield = 1,
    cabin = 1,
    laser_front = 1,
    laser_rear = 0,
    missile = 1,
    scoop = 0,
    cargo_life_support = 0,
    hull_autorepair = 0,
  },

  min_crew = 1,
  max_crew = 2,

  capacity = 30,
  hull_mass = 10,
  fuel_tank_mass = 10,

  thruster_fuel_use = 0.0001,

  hyperdrive_class = 2,

  price = 34000,
}

**Comment by fluffyfreak** [comment]
Ah that's why.

> gun_mounts = {
>     { v(0,0,-16), v(0,0,-1),9, 'HORIZONTAL' },
>     { v(0,0,15), v(0,0,1),9, 'HORIZONTAL' },
> },

The correct way to fix this is to add gun tags to the ships.

We started emitting a warning to the `output.txt` file when gun tags were first added, which was more than a year ago.

I guess I'll have to try and figure out how to get it to load them from the Lua/JSON etc.

**Comment by walterar** [comment]
When you start, this work well. Why after passing through serializer is broken? You understand what is the problem?

**Comment by fluffyfreak** [comment]
Yes it's because they're just being filled with random values. The first time through it looks like they're, entirely by chance, getting filled with useful values.

**Comment by walterar** [comment]
It is not by chance. http://spacesimcentral.com/ssc/topic/3948-camera-and-gunmounts-changes/#entry43685

**Comment by fluffyfreak** [comment]
You misunderstood me, the fact that after loading the game they are working is "by chance". There is nothing setting them to have the correct values. This is exposed when they are loaded from a save game because now the values are completely random.

I'm tempted to say that the model is what is broken, you've had since **23rd September 2013** to fix those models.

**Comment by walterar** [comment]
tag_gunmount_N	Gun positions, X "left", Y "up", Z "out" of the ship (in the fire direction). Note at this time, only N = 0 or 1 will work, and they correspond to "front" and "rear" guns in the UI. The "max_lasers" ship definition field still takes precedence (ie if max_lasers = 1, tag_gunmount_1 will never be used). Defaults to the ship origin.

"Defaults to the ship origin"

Change the rules every day is schizophrenic.

**Comment by walterar** [comment]
And a lack of respect for the work of others.

**Comment by fluffyfreak** [comment]
There's been 1 year, 3 months, 20 days to fix it. 

That isn't `every day`, it's been like that for that whole time. 
The original plan was to remove the code after `a few weeks`.

You don't have to merge our code updates into Scout+, we're glad that you do and that you're working on it but we're not forcing you to take the Pioneer code and we do warn everyone, very far in advance, when things are being changed.

**Comment by walterar** [comment]
OK. I prefer to leave the engine Pioneer and continue with what I consider correct.

**Comment by nozmajner** [comment]
OK, before this gets out of hand.
@walterar: please stop the talk about schizofrenia (it's not even a good term here). This is what disrepect is, this name calling and offensive tone towards one of the developers who put a lot of effort and energy into Pioneer. 
And those rules aren't changing day by day. That fallback is there so older mods could work without the tags, not crashing the game as soon you fire. But tags are preferred anyway. Gun tags came in quite a while ago, and this error didn't turned up since then, or something messed with the fallback, but nobody noticed it until now. It's good to point out errors like this, but it's still important to do it with respect towards the guys who do the actual work. Errors happen, this is how the world works.

**Comment by walterar** [comment]
@nozmajner  Make no mistake you. Andy and I are working. We sometimes use words risqué, damaging people's ears too sensitive, but that's the sound of "working people". And not get any remuneration for this; just like you.

**Comment by walterar** [comment]
@fluffyfreak  #3316 seems to be working. Let me try some hours with real game, and if any problems, i inform him gently, so nozmajner not be shocked. ;)
