### ISSUE TITLE
Text has missing pixels and some special 2 bit characters dissapear

### ISSUE THREAD

**Issue by dreadk2002** [pioneerspacesim/pioneer#3314]
Text is looking kind of strange in build 20150109. Also some (only some) of the characters are dissapearing. The sistem I run Pioneer on is win7, it has GeForce GTX 760 2Gb video card. Also the characters "ș" and "ț" are only sometimes showing. In "Ieșire" is the same character as in "Pornește" (see 2nd and 3rd pictures).

![loading](https://cloud.githubusercontent.com/assets/1060220/5693014/1c78ad34-9914-11e4-93d6-6161d69834f7.jpg)
![menu](https://cloud.githubusercontent.com/assets/1060220/5693015/1e5f21fa-9914-11e4-9820-2569c2107eb7.jpg)
![strings](https://cloud.githubusercontent.com/assets/1060220/5693016/20592e4c-9914-11e4-9afb-0e3838374010.jpg)

**Comment by radius75** [comment]
Check translation:  ş (is ok),  ș (not printed)
You have two different symbols in translation

**Comment by dreadk2002** [comment]
"ș"(with comma) is used in all words in the second screen shot. "Pornește" and "Ieșire" use the same "ș"(with comma), yet it is printed only in "Ieșire". I would prefer not to use the cedilla versions as they are not Romanian characters especially because it seems it's not a general problem (they print sometimes). I would prefer to find out the cause of the weird "sometimes printed" characters and just use the cedilla version as the last resort (I would rather lose the commas and all the other two bit characters then do that; I bet you as well wouldn't replace any of your native characters if they wouldn't print).

**Comment by radius75** [comment]
> yet it is printed only in "Ieșire

 ş - is used 6x in UI-Core; 23x in Core strings.
You will have to standardize this:)

I do not know how to edit the fonts to add missing characters.

**Comment by dreadk2002** [comment]
Sorry, you're right, "Ieșire" had cedille. I didn't notice that because I didn't translate that one. I only used s with comma. Isn't it possible for the game to accept Unicode 3.0.0?

**Comment by johnbartholomew** [comment]
dreadk2002 wrote:
> Isn't it possible for the game to accept Unicode 3.0.0?

The game code has no problem with Unicode, but it is difficult to find
fonts with an appropriate style for the game that also support many
characters. There are three things we can do:

1- Use the wrong characters. This is obviously a bad option.

2- Add the missing characters to the font we use. I think we should do
this, since we're only missing one or perhaps a few characters here, and
we've already modified the font previously so we know it can be done
reasonably easily. To help with this, please make a test string that
includes all the characters needed for your language (including all needed
combinations of letter+diacritic), so that we can check easily that we have
added all necessary characters.

3- Use a different font for this language. We do this for Russian and
Chinese already. This is the easiest option, and you can do it in your copy
right now so you can continue with translations. The result won't look as
nice as option 2 though.

**Comment by nozmajner** [comment]
Does this look ok? (Ignore the rotated C :D )
![char_pioneer](https://cloud.githubusercontent.com/assets/4182678/5704625/9b820020-9a73-11e4-9e55-087536bc4e0d.png)

**Comment by nozmajner** [comment]
Can you try these? They should work, if I'm right, but I'm new to font editing. :) Fontforge gives some minor errors upon exporting, but those may be already present in the fonts, but we need to be on a lookout for errors just in case. For kerning errors and similar too, but I think those shouldn't be there.
https://dl.dropboxusercontent.com/u/456051/pioneer/pioneer_fonts.zip

**Comment by dreadk2002** [comment]
@johnbartholomew You can find all the characters here(unicode as well): http://en.wikipedia.org/wiki/Romanian_alphabet, but I think only ș,ț,Ș and Ț are the problem.
@nozmajner What characters did you use? The issue is not the way it shows in game, but the fact that the letters used in Transifex as "ș" and "ț" (with a comma) are not recognized in the game. I could use s and t with cedille in Transifex as it looks in game like they are with a comma, but I would prefer johnbartholomew's second option.
Leaving these two letters aside, there is still the problem with the missing pixels. Did anybody find them? :)

**Comment by radius75** [comment]
@nozmajner solutions (second option) work well

Test fonts Orbiteer-Bold: all romanian symbols + cedille 
ĂăÂâÎîȘșȚț-ŞşŢţ
![bez tytulu](https://cloud.githubusercontent.com/assets/1929111/5707657/d013a2aa-9a8a-11e4-90b1-0cd81d97b289.png)

**Comment by nozmajner** [comment]
@dreadk2002 The fonts were missing those ș,ț,Ș and Ț letters, so I edited them in, appending a comma to each letter. I think they should now show up properly if you use them with the transifex translation.

**Comment by dreadk2002** [comment]
Is it commited? Will I be able to test with the last build?

**Comment by radius75** [comment]
> ...there is still the problem with the missing pixels. Did anybody find them?

probably related to  #3308

**Comment by nozmajner** [comment]
Not yet commited, but you can test it if you overwrite the files in the data/fonts dir. I'll make a PR right away. I just wanted to wait to see if everything's in place.

**Comment by dreadk2002** [comment]
They are printing now. Thank you.

![menu2](https://cloud.githubusercontent.com/assets/1060220/5708798/de5a1152-9a9c-11e4-8744-2ed067c1b680.jpg)
