### ISSUE TITLE
error: Lua serializer '(null)' tried to serialize an...

### ISSUE THREAD

**Issue by walterar** [pioneerspacesim/pioneer#3317]
error: Lua serializer '(null)' tried to serialize an invalid 'Ship' object

@laarmen This happens to me sometimes, pressing twice II (settings)

null? I have no idea who (lua module?) is generating this error.

LuaObjectBase * lo = static_cast <LuaObjectBase *> (lua_touserdata (l, idx));
void * o = lo-> GetObject ();
if (! o)
Error ("Lua serializer '% s' tried to serialize an invalid'% s' object ', key, lo-> GetType ());

Why key is null?

**Comment by laarmen** [comment]
The key being null isn't exactly worrying, the whole key thing is broken
in the first place.

There isn't much we can do with these info, we'd need to know how to
reproduce (lua serializer bugs are a pain to identify, TBH)

**Comment by walterar** [comment]
The funny thing is that happens when you double press Pause (II) to enter the Setting section. I was not saving anything. It's strange. I hope we can repeat and capture it. :(

**Comment by laarmen** [comment]
Oh, I didn't even know this shortcut. I tried to reproduce it, but
couldn't. Does it happen with vanilla Pioneer, or do you have mods?

**Comment by walterar** [comment]
Forget it; I was trying to compile with -pipe and strange things happen. It has happened to me before, Gentoo kernel compiling, I had forgotten. I believe that this failure is not repeated. Close this now. If repeats (not think) I open another. Thanks @laarmen
