### ISSUE TITLE
Invisible ink in tooltip

### ISSUE THREAD

**Issue by radius75** [pioneerspacesim/pioneer#3322]
![screenshot-20150114-163008](https://cloud.githubusercontent.com/assets/1929111/5741452/580b7eae-9c0b-11e4-875f-b71811752a8c.png)
![screenshot-20150114-163045](https://cloud.githubusercontent.com/assets/1929111/5741453/580e8068-9c0b-11e4-8c0b-e91765f38ee6.png)

**Comment by walterar** [comment]
Yes, I see the same.

**Comment by walterar** [comment]
Surely this related to #3310

**Comment by impaktor** [comment]
I'm thinking, once this is fixed, we have a fairly stable* pioneer again.

*stable means latest bug invasion squashed.

**Comment by fluffyfreak** [comment]
@impaktor your wish is my command! #3334 :)
