### ISSUE TITLE
Squares in the view of the galaxy

### ISSUE THREAD

**Issue by radius75** [pioneerspacesim/pioneer#3323]
![screenshot-20150114-201857](https://cloud.githubusercontent.com/assets/1929111/5745662/ab95a0f8-9c2a-11e4-926e-e0233d5df99c.png)

**Comment by impaktor** [comment]
I think this is a (long lost) feature, and not a bug. 

After all, the stars aren't blue or green either. It just switches to another way of showing the information. A more square way.

**Comment by fluffyfreak** [comment]
Yeah not a bug, when I did the OpenGL 3.1/2 stuff it broke this screen so only showed points instead of the squares that it used too. Then I fixed it, back to what you see there :)

The colours are of the factions, it's not the galaxy view, it's the faction view.

**Comment by radius75** [comment]
ok, I understand:)
