### ISSUE TITLE
Request: temporary lua/json controlled flight UI

### ISSUE THREAD

**Issue by nozmajner** [pioneerspacesim/pioneer#3329]
I was thinking about the flight UI for a while. SOme of the things feel quite randomly placed. These things made sense on the old dashboard style UI though.
Until the whole thing is migrated to the newUI, how hard it would be to expose the current UI elements positioning and scaling to some kind of lua or json file? As a temporary measure, so we could play around with it without the need to build/compile the game.
It could be helpful to rearange some texts, because they tend to overlap other elements, or even stick out from the view.

**Comment by fluffyfreak** [comment]
We could do this, or we could get a few of us together and actually rewrite it once and for all.
@robn has been doing something with the UI again lately.

We do need a few widgets for it: crosshair, scanner, message log. Mostly it just needs someone to sit down, convert it and we need to fill in the missing bits by splitting the work amongst me, @impaktor, @laarmen, @lwho and whomever else can be roped into it.

**Comment by impaktor** [comment]
Considering where we're going with @ecraven's imgui, temporally moving old UI to json is no longer relevant, as we have that functionallity on his imgui branch, and I'm too impatient to wait for merge until closing this.
