### ISSUE TITLE
Strange distances in conjunction with storeria

### ISSUE THREAD

**Issue by robothauler** [pioneerspacesim/pioneer#3335]
If I set the ship type to "storeria" the distance to the selected space station changes from 2.77AU to 4.05AU.

![screenshot-20150125-202929](https://cloud.githubusercontent.com/assets/10255455/5892938/62aab792-a4d2-11e4-92aa-6e2843f1e5d7.png)

![screenshot-20150125-202940](https://cloud.githubusercontent.com/assets/10255455/5892942/7be6db50-a4d2-11e4-851e-a2b674f54ec7.png)

This happens only if I switch to the storeria ship.

**Comment by nozmajner** [comment]
Wow, I can confirm this. And if you set yourself to another ship using the console, then it jumps back to the 2.77AU. And if you switch back to the Storeria again, it goes back to 4AU. 
Also happens on Sol.
I first was going to say that there isn't anything out of ordinary in the model file, but I double checked and it's the camera tag scaling. It's scaled 1.465, which is what you get if you 4.05AU/2.77AU.
I didn't noticed that they were scaled, sorry it's my bad. I'll put up a fix ASAP.

**Comment by fluffyfreak** [comment]
hmmm... the Storeria... is very big? ;)

**Comment by nozmajner** [comment]
So big, it bends space-time :D. But if you have properly scaled camera tags too, then it will only change the distance for the views with improperly scaled tags, you space-time bending at the press of a button.

**Comment by nozmajner** [comment]
Aaaand I wasn't paying attention and copied it to my master branch and committed (I even did a detailed commit message, joke included :) ), instead of a separate one, so I need to fix that, but not tonight. So here's the updated dae instead. Could somebody do the replacing for me?
https://www.dropbox.com/s/puffo2c918en2yg/storeria_hi_fix.zip?dl=0
