### ISSUE TITLE
Equipment labels missing

### ISSUE THREAD

**Issue by clausimu** [pioneerspacesim/pioneer#3337]
I just downloaded and compiled the git version (I'm on a 64-bit linux system). In the station screen all labels for ship equipment are missing. The numbers (prices, amount) are there - just the labels are missing (on both sides of the screen - the stuff available for purchase (left) and the stuff already built into the ship (right)). 

The strange thing: ONLY the Multi-Scoop shows the label. I flew to a different station in a different system. Same thing. Only Multi-Scoop has label - all others have no label.

**Comment by impaktor** [comment]
Most likely something to do with #3295.

Are you playing the English version, or a translated version?

So the commodity labels work? But not ship equipment?

**Comment by victort** [comment]
On 01/26/2015 01:37 PM, Karl F wrote:
>
> Most likely something to do with #3295 
> <https://github.com/pioneerspacesim/pioneer/pull/3295>.
>
> Are you playing the English version, or a translated version?
>
> So the commodity labels work? But not ship equipment?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/pioneerspacesim/pioneer/issues/3337#issuecomment-71543438>.
>
just want to say i'm experiencing the same thing. English version, 
running ver git (fb62c69) on: Linux

**Comment by clausimu** [comment]
Correct - equipment labels are gone but commodity labels are fine. I'm playing the English version.

**Comment by impaktor** [comment]
Nope, this works for me, and it works for @jmf as well, so there seems to be something in your setup that causes this.

Please make sure you don't have any mods installed, or any custom `Equipment.lua` files anywhere.

Also please make sure you have the `data/lang/equipment-core/en.json` file.

**Comment by clausimu** [comment]
I tried again - now it works! That's bizarre! I do have the data/lang/equipment-core/en.json file. No special lua scripts or files. I did have a music mod installed. But trying again (with or without the music mod) everything worked. I will have to keep an eye out for this. Right now at least I can't reproduce it.

**Comment by impaktor** [comment]
@victort does it work for you? If not, could you please try the latest build?

**Comment by impaktor** [comment]
No answer (yet), and I'm quite confident this is just something with a wonky install, or a superposition of two pioneers of different age on top of each other.

_What did I just write?_
