### ISSUE TITLE
error when warping to another system

### ISSUE THREAD

**Issue by ralfy12** [pioneerspacesim/pioneer#3338]
![untitled-1](https://cloud.githubusercontent.com/assets/10765945/5969304/19f61d46-a876-11e4-8390-49628c7deed7.jpg)

I get this message in the latest Win32 version whenever I try to warp to another system, everything else in the game runs fine, I can go to other planets and space stations within a particular system, land, etc. Never gotten this reaction before until now

**Comment by fluffyfreak** [comment]
I've not been able to reproduce this yet.
@ralfy12 what systems were you jumping to and from? It might help me figure it out.

**Comment by ralfy12** [comment]
starting a new game, going from Earth warping to NN 3877. Also from Ward Outpost in the Ethze system to Gliese 638. I've accepted jobs from each origin point to those systems

**Comment by ralfy12** [comment]
I think I've resolved it. 

I'd kept a few community made dds skybox texture files in my skybox folder. Vuzz's Milkyway, etc, just stuff I accumulated to give the game a different look... I just deleted them and left the original default.dds file, now it works fine. Looks like the program might have been trying to load them, don't know why as i've had them there for a few months and regularly update pioneer with no problems like it before. 

Anyway, I've tested it, especially to those locations I mentioned and others. No problems so far, will let you know if the error crops up again

**Comment by fluffyfreak** [comment]
Ah yes, it will try to load a list of cubemaps and they should work. Something might be broken though as I haven't tested them in a very long time.

**Comment by impaktor** [comment]
Is the error in the skybox or in pioneer?

@ralfy12 could you please provide us with the sky box, in case we want to test?

**Comment by ralfy12** [comment]
I downloaded the collection from pebblegardens collection. I just tested them out, didn't really use them and so I left them there. I never had CTD issues with any version earlier than the Jan 20th/21st build of Pioneer for Win32 so I didn't see any point in deleting them. I also deleted the default.dds file in the skybox collection zip file and used Vuzz's Milkyway texture as the default.dds file instead.

Pebblegardens Skybox Collection
http://spacesimcentral.com/ssc/topic/4296-i-dont-like-the-skybox/?p=47345

Vuzz's Milkyway
http://spacesimcentral.com/ssc/topic/4268-vuzzs-milkyway/

**Comment by laarmen** [comment]
We've changed something about how the skybox is rendered recently (what
exactly, I couldn't tell), that would explain why it started to crash all
of a sudden.

**Comment by impaktor** [comment]
Does the fact that old skyboxes crash the game hint at an underlying bug, or is this expected?

**Comment by fluffyfreak** [comment]
Not expected.

**Comment by fluffyfreak** [comment]
Strangely I've just tried those mods and everything seemed to work ok :(

**Comment by ralfy12** [comment]
oh well, thank you anyway. It's worked fine for me since deleting the files and the latest update. If it does up end like that again, i'll let you know.

**Comment by impaktor** [comment]
__In summary:__ We can not reproduce the crash, nor can the original poster, who no longer get the crash, so I'm putting this down as solved for now, although keeping an eye out for if this happens again. 

Thanks for reporting.
