### ISSUE TITLE
Too many stars in sky background

### ISSUE THREAD

**Issue by clausimu** [pioneerspacesim/pioneer#3343]
Something changed with the sky background recently. There are many more stars and they seem much smaller. The disadvantage is that it is getting too noisy and distracting (especially in dogfights, when you are trying to follow the crosshairs, etc.). Can the number of stars be reduced - or even better, the brightness and "crispness" be reduced to make it more of a background feature?

**Comment by impaktor** [comment]
This is a feature, and not a bug: #3321.
#2813 added support for optional skybox/backgroundm but we decided not to merge it.

**Comment by fluffyfreak** [comment]
It might need tweaking however, it's set to 100,000 stars at the moment.

**Comment by impaktor** [comment]
Well, stars will change again to [real ones](http://pioneerspacesim.net/forum/viewtopic.php?f=3&t=302) (I hope).

But first we need a volunteer to write a script for parsing astronomical data; an old script in python is available as starting point

**Comment by walterar** [comment]
I wonder ... How many stars would put the old Stanley?
http://www.imdb.com/rg/VIDEO_PLAY/LINK//video/imdb/vi2388329497/

**Comment by impaktor** [comment]
I think it is better to do a poll on space sim central to change number of stars, if that is something the players want.

The way it looks now is a feature until it is changed again, and it is indeed difficult to please everyone.

**Comment by fluffyfreak** [comment]
As for the number of stars: http://upload.wikimedia.org/wikipedia/commons/5/5d/Zodiacal_Glow_Lightens_Paranal_Sky.jpg

**Comment by walterar** [comment]
There are still people who sees the starry sky in black and white :)
http://youtu.be/jrEpB7U1I_g
