### ISSUE TITLE
Design error in docking sequence, orbital_station

### ISSUE THREAD

**Issue by walterar** [pioneerspacesim/pioneer#3344]
http://youtu.be/X_XE2xdpO5g

**Comment by fluffyfreak** [comment]
Does this happen in regular Pioneer as well or is it unique to Scout+?

**Comment by walterar** [comment]
It happens in my PC, not in yours?

**Comment by walterar** [comment]
I'll give you a hint: The ships enter of aft in the new orbital_station.

This also happens, of course, in Scout+

Question, this happens only in my pc? Or nobody cares?

**Comment by laarmen** [comment]
Wait, did you just say it only happens in Scout+? The question of whether is happend on vanilla Pioneer is crucial: we shouldn't need to install a third-party mod to do some troubleshooting. You need to come up with a way to reproduce this on plain old Pioneer.

**Comment by walterar** [comment]
This ALSO happens, of course, in Scout+

**Comment by walterar** [comment]
ALSO == ONLY ?

**Comment by walterar** [comment]
Make an effort and look carefully.  What you see? A ship incoming? or ship leaving?
![bad-entrance](https://cloud.githubusercontent.com/assets/1334989/8184917/83064ca4-1417-11e5-9368-f3c91e0b26a8.png)

**Comment by laarmen** [comment]
I meant no offense, man. It's just, you know, better safe than sorry (in the end, Andrew seem to have taken it upon himself)

**Comment by walterar** [comment]
There are none so blind as those who will not see.

**Comment by walterar** [comment]
To more than a year of broken, the ships keep entering backwards at orbital port. Also it removed the final sequence to docking at ports of surface.  This looks very ugly. Should we take this as new features?

**Comment by fluffyfreak** [comment]
Yes, and i've been seeing it in Pioneer.
It's on my to-do list that I have to fix it.

**Comment by walterar** [comment]
Thanks Andy. It had not been for your work, orbitals of nozmajner would still be waiting. But need finish, is ugly this.

**Comment by fluffyfreak** [comment]
I've had a go at this over the last week and it is a nightmare to figure out.
I will keep at it but I wanted you to know that I am looking into it.

**Comment by walterar** [comment]
Need help? I can recite an old poem Vogon, if necessary...

**Comment by fluffyfreak** [comment]
@walterar yeah I am sorry, what was meant to take 2 or 3 days I've now spent 5 weeks working on...

...a bit longer than planned!

**Comment by walterar** [comment]
Why the ships parked with the nose pointing to the entrance instead of pointing to the exit?

Perhaps the inputs and outputs are reversed in spaceport?

**Comment by richardpl** [comment]
Perhaps related, but launching several police ships in orbital stations will make them destroy each other when launching.

**Comment by nozmajner** [comment]
I believe that this has been fixed.
