### ISSUE TITLE
Need a way to exit fullscreen on OS X

### ISSUE THREAD

**Issue by jameynakama** [pioneerspacesim/pioneer#3348]
There doesn't seem to be a way to use any other app while in Pioneer full screen. I can't cmd-tab to my browser, for example, or use Mission Control or Exposé.

**Comment by fluffyfreak** [comment]
Sorry we don't have any dedicated Mac developers at the moment. @EloquentMess does builds for us but, as far as I know, is not a programmer.

If you can, or if you know someone who can, fix the issue then I'll be happy to help integrate it into the game.

**Comment by SilkyPantsDan** [comment]
This might be an issue in SDL, will see if I can find out anymore information

https://bugzilla.libsdl.org/show_bug.cgi?id=1908
https://bitbucket.org/rude/love/issue/629/cant-command-tab-in-fullscreen-on-os-x-108

**Comment by jfacoustic** [comment]
I'll start looking into this issue.

**Comment by Web-eWorks** [comment]
Closing this as its a specific and possibly upstream-related issue. Borderless vs true fullscreen is better suited for a more topical issue.
