### ISSUE TITLE
Won't compile o new version of autoconf

### ISSUE THREAD

**Issue by naclander** [pioneerspacesim/pioneer#3352]
I'm running Arch Linux, the current version of automake is 1.15. Pioneer refuses to compile because it requires 1.14.

**Comment by robn** [comment]
I'm stll on 1.11, and its going to take a little while to get something up that can run a newer one. Can you give me the output please? From `bootstrap` on. Thanks!

**Comment by naclander** [comment]
Sorry, for some reason I can't reproduce this anymore. I'll close this ticket until I can reproduce this behavior.
