### ISSUE TITLE
Data folder is repeated within the data folder

### ISSUE THREAD

**Issue by walterar** [pioneerspacesim/pioneer#3358]
This is verified in the last release of linux version pioneer-20150205-linux64.tar.bz2 and pioneer-20150205-linux32.tar.bz2  in sourceforge

**Comment by impaktor** [comment]
Judging by the size of the file,  Windows and Mac seems to be OK.

Ping @robn

**Comment by impaktor** [comment]
If anyone wants to have a go:
@664c8f110d7b20c5b1a9fba3a2ad717efa169005

**Comment by walterar** [comment]
I suppose, by the size of the files, that this was fixed in the latest release. I close with OK.
