### ISSUE TITLE
Labels disappear in the saved game

### ISSUE THREAD

**Issue by walterar** [pioneerspacesim/pioneer#3359]
Start game in London
See label
![label1](https://cloud.githubusercontent.com/assets/1334989/6484378/289306a4-c25a-11e4-8443-e0095720caef.png)

Save game
Recover game
![label2](https://cloud.githubusercontent.com/assets/1334989/6484385/3500b24c-c25a-11e4-802b-5d9d594b706e.png)

The label has disappeared

**Comment by impaktor** [comment]
Perhaps @nick-the-ninja is interested in this?

**Comment by walterar** [comment]
I have no doubt that the work you are doing @nick-the-ninja serve to discover many, many, like this problems. Perhaps the most serious and frustrating is #3345

**Comment by nick-the-ninja** [comment]
Also occurs for JSONSerialise branch.

**Comment by walterar** [comment]
#3406 resolve this, thanks John :+1:
