### ISSUE TITLE
Game crashes or does not load -1

### ISSUE THREAD

**Issue by Josephhun** [pioneerspacesim/pioneer#3360]
Hi!

After asking in IRC channel I have the problems down below:
If I run the game on intergrated graphics card, it crashes after one minute.
If I run the game on NVIDIA graphics card, it does not even start and gives: Could not create GL content error.

Laptop: i5-2450M, Nvidia GeForce GT525M

Error messages from output.txt:

Running with integrated graphics card:
Issue:  Crashes after just after one minute
ver 20150201 (50c25a6) on: Windows

Hardware information: 
  		OEM ID: 0
  		Number of processors: 4
  		Page size: 4096
  		Processor type: 586
  		Minimum application address: 10000
  		Maximum application address: 7ffeffff
  		Active processor mask: 15

Windows 7 (Service Pack 1)
SDL Version 2.0.3
Initialized OpenGL 3.1, with extensions, renderer
invalid axis binding '' in config file for BindAxisPitch
invalid axis binding '' in config file for BindAxisRoll
invalid axis binding '' in config file for BindAxisYaw
started 3 worker threads
ShipType::Init()
Lua::Init()
GalaxyGenerator::Init()
Creating new galaxy generator 'legacy' version 1
Number of factions added: 103
StarSystemCache: misses: 2227, slave hits: 0, master hits: 0
SectorCache: misses: 1571, slave hits: 0, master hits: 11138
FaceParts::Init()
Face Generation source images loaded.
new ModelCache
Shields::Init
BaseSphere::Init
CityOnPlanet::Init
Got 28 buildings of tag city_building
 - kbuilding01: 29.664692
 - kbuilding01: 29.664692
 - kbuilding02: 46.268344
 - kbuilding02: 46.268344
 - kbuilding03: 41.542333
 - kbuilding03: 41.542333
 - newbuilding1: 36.202756
 - newbuilding1: 36.202756
 - newbuilding10: 16.297418
 - newbuilding10: 16.297418
 - newbuilding11: 34.961034
 - newbuilding11: 34.961034
 - newbuilding2: 22.822782
 - newbuilding2: 22.822782
 - newbuilding3: 22.649894
 - newbuilding3: 22.649894
 - newbuilding4: 25.978193
 - newbuilding4: 25.978193
 - newbuilding5: 22.908506
 - newbuilding5: 22.908506
 - newbuilding6: 29.817877
 - newbuilding6: 29.817877
 - newbuilding7: 22.674426
 - newbuilding7: 22.674426
 - newbuilding8: 23.154979
 - newbuilding8: 23.154979
 - newbuilding9: 36.528138
 - newbuilding9: 36.528138
End of buildings.
SpaceStation::Init
ground_station has:
 14 entrances,
 14 pads,
 0 exits
new_ground has:
 6 entrances,
 6 pads,
 0 exits
orbital_station_2-10k has:
 5 entrances,
 64 pads,
 5 exits
orbital_station_2-5k has:
 5 entrances,
 64 pads,
 5 exits
orbital_station_2-5k10k has:
 5 entrances,
 64 pads,
 5 exits
NavLights::Init
Sfx::Init
Sound::Init

Loading took: 62297.799617 milliseconds
Creating new galaxy generator 'legacy' version 1
Clearing and re-using previous Galaxy object
StarSystemCache: misses: 0, slave hits: 0, master hits: 0
SectorCache: misses: 101, slave hits: 0, master hits: 1
Sol:
    height fractal: Ellipsoid
    colour fractal: StarG
    seed: 1685209112
Mercury:
    height fractal: HillsCraters2
    colour fractal: Rock
    seed: 6
Venus:
    height fractal: RuggedLava
    colour fractal: Desert
    seed: 1710384323
Earth:
    height fractal: Mapped
    colour fractal: EarthLikeHeightmapped
    seed: 1717547535
Moon:
    height fractal: Mapped2
    colour fractal: Rock2
    seed: 4294967291
Mars:
    height fractal: MountainsRidged
    colour fractal: TFPoor
    seed: 4294967293
Phobos:
    height fractal: Asteroid4
    colour fractal: Asteroid
    seed: 439771126
Deimos:
    height fractal: Asteroid4
    colour fractal: Asteroid
    seed: 806180402
Warning: Lua custom Systems definition: Surface starport has been automatically relocated. This is in order to place it on flatter ground to reduce the chance of landing pads being buried. This is not an error as such and you may attempt to move the starport to another location by changing latitude and longitude fields.
      Surface starport name: Tomm's Sanctuary, Body name: Deimos, In sector: x = 0, y = 0, z = 0.
Io:
    height fractal: RuggedLava
    colour fractal: Volcanic
    seed: 4294967292
Warning: Lua custom Systems definition: Surface starport has been automatically relocated. This is in order to place it on flatter ground to reduce the chance of landing pads being buried. This is not an error as such and you may attempt to move the starport to another location by changing latitude and longitude fields.
      Surface starport name: Dante's Base, Body name: Io, In sector: x = 0, y = 0, z = 0.
Europa:
    height fractal: Barren Rock 2
    colour fractal: Ice
    seed: 2102431459
Ganymede:
    height fractal: HillsNormal
    colour fractal: Rock
    seed: 3062955636
Warning: Lua custom Systems definition: Surface starport has been automatically relocated. This is in order to place it on flatter ground to reduce the chance of landing pads being buried. This is not an error as such and you may attempt to move the starport to another location by changing latitude and longitude fields.
      Surface starport name: Enki Catena, Body name: Ganymede, In sector: x = 0, y = 0, z = 0.
Callisto:
    height fractal: MountainsCraters2
    colour fractal: Rock
    seed: 1272712740
Dione:
    height fractal: Barren Rock 3
    colour fractal: Rock
    seed: 3732948941
Rhea:
    height fractal: RuggedDesert
    colour fractal: Rock
    seed: 1174493206
Titan:
    height fractal: MountainsVolcano
    colour fractal: Desert
    seed: 0
Iapetus:
    height fractal: Barren Rock 3
    colour fractal: Rock
    seed: 3650944653
Ariel:
    height fractal: MountainsCraters2
    colour fractal: Rock
    seed: 3952866153
Umbriel:
    height fractal: Barren Rock 3
    colour fractal: Rock
    seed: 699943475
Titania:
    height fractal: Barren Rock 3
    colour fractal: Rock
    seed: 2461415048
Oberon:
    height fractal: MountainsCraters2
    colour fractal: Rock
    seed: 663490636
Proteus:
    height fractal: Asteroid4
    colour fractal: BandedRock
    seed: 1251043226
Triton:
    height fractal: Barren Rock 3
    colour fractal: Rock
    seed: 1155973133
Nereid:
    height fractal: Asteroid4
    colour fractal: BandedRock
    seed: 3055461756
Pluto:
    height fractal: HillsCraters2
    colour fractal: Rock
    seed: 3037711761
Charon:
    height fractal: HillsCraters2
    colour fractal: Rock
    seed: 2191294907
libpng warning: iCCP: known incorrect sRGB profile
TradeShips: Removed 0 ships before serialization
BQ-7202 left Sol for Toliman
cleanTSTable:total:32,active:23,removed:0
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Running with NVIDIA graphics card:
Issue: Error: Could not create GL content
ver 20150201 (50c25a6) on: Windows

Hardware information: 
  		OEM ID: 0
  		Number of processors: 4
  		Page size: 4096
  		Processor type: 586
  		Minimum application address: 10000
  		Maximum application address: 7ffeffff
  		Active processor mask: 15

Windows 7 (Service Pack 1)
SDL Version 2.0.3
Failed to set video mode. (Could not create GL context: ఌڀ౴ڀ幐疌ߐڀ). Re-trying with 16-bit depth buffer
error: Failed to set video mode: Could not create GL context: ఌڀ౴ڀ幐疌

THANKS!

**Comment by impaktor** [comment]
Ping @fluffyfreak. Graphics card supports OpenGL 4.4.

**Comment by fluffyfreak** [comment]
Laptop, open nVidia control panel, manage 3d settings, set it to use "High Performance nVidia GPU".

Currently it's using the Intel iGPU. I think that they should work but for some reason they don't.

I'm currently trapped under a bus load of work for my job so don't have much spare time to look into this stuff in the detail it requires.

**Comment by fluffyfreak** [comment]
Ok, Intel situation looks like it run but then runs out of ram. How much ram do you have?
Try lowering the detail settings for planets, cities etc. If it's failing after a while then that's probably because it ran out of ram.
Also how much do you have set for the GPU to use?

For the nVidia... try updating the drivers that always seems to fix nVidia issues. Otherwise I have no idea right now.

**Comment by impaktor** [comment]
@Josephhun did you get it to work? Have you tried the latest version?

**Comment by walterar** [comment]
@Josephhun  It is very likely that # 3405 resolve this. You want to check?

**Comment by impaktor** [comment]
Silence means yes.
Closing.
