### ISSUE TITLE
Joystick inversion, deadzones, axis bindings

### ISSUE THREAD

**Issue by fluffyfreak** [pioneerspacesim/pioneer#3362]
# The Problem:

For a long time we've had some [issues with Joysticks/joypads](https://github.com/pioneerspacesim/pioneer/search?q=joystick&state=open&type=Issues&utf8=%E2%9C%93) which make playing Pioneer less than fun using these times of controls. It's a common post on the [SSC forum](http://spacesimcentral.com/ssc/topic/4925-help-with-flight-system/) and the [developers forum](http://pioneerspacesim.net/forum/viewtopic.php?f=3&t=318). 
# Task overview:

This feature request would evaluate the work done in the [Paragon 10.5 Alpha](https://github.com/MeteoricGames/pioneer/commit/c93e14c8cbb629b3aa2a88dfe92bb445510f5e98) to see if it's a good solution that fits Pioneer and then to reimplement it for Pioneer. 
We cannot directly backport this code, despite it being GPL licensed and based on Pioneer, due to the way that our code bases have diverged.
Therefore the deadzone, axis inversion, and controller mappings would need to be written using the different code present in Pioneer. This will require a mix of C++ for the game side enumeration, access, etc and Lua for the options/setting screen and binding of axes, buttons, and d-pads.
# Alternatives:

Despite referencing the Paragon solution to the problem it is not necessary to use their code or method of fixing the issue if whoever picks up this issue doesn't want to. Other solutions are valid it is the problem that needs solving. The Paragon solution is merely presented as one option.

**Comment by fluffyfreak** [comment]
@nick-the-ninja, here's the issue since you mentioned interest in it :)

**Comment by victort** [comment]
I just noticed I cannot bind joystick axes to thrusters, so I thought i'd :+1: this,

:D
