### ISSUE TITLE
Missing specular highlights

### ISSUE THREAD

**Issue by nozmajner** [pioneerspacesim/pioneer#3366]
The specular highlights aren't showing up in the game. I noticed this while one of my students was trying to create the spec texture for his model. @fluffyfreak you might find it interesting. :D
It seems to affect all models. I've tried to replace the spec .dds with a .png, but no change. I've also tries to change the specularity color in the .model file, but it won't do anything either.
I'm on win7
It works on the 20141029 build. (@jpab suggested that I should check out a pre openGL3 build)
It doesn't work on the 20141128 build. (I found these builds on moddb, and I don't have my external HDD on me to hunt for any build inbetween.)
My GPU: NVidia GFX 660Ti (most recent driver), but I've tried it on my laptop's GT 540M, and on some kind  ATi card too, with the same result.
My opengl.txt: https://dl.dropboxusercontent.com/u/456051/opengl_nospec.txt

It's a bit harder to notice on still images, but here are a couple of screenshots:
An older one, from when I finished the Malabar. The higlights are mostly visible in the circled area, and also the ship itself is quite shiny.
![screenshot-20131230-134745](https://cloud.githubusercontent.com/assets/4182678/6710715/e1bfda34-cd82-11e4-9451-932f4ba06f2a.png)
Currently, no highlights at all, and the whole ship feels matte:
![screenshot-20150318-145851](https://cloud.githubusercontent.com/assets/4182678/6710739/0869f106-cd83-11e4-8efd-cd114cf943fb.png)
It's easier to notice it if you roatate around the ship in the model viewer.

**Comment by fluffyfreak** [comment]
Interesting, and bad! I'll try to take a look tonight, probably just me doing something stupid.

**Comment by fluffyfreak** [comment]
Ok, I took a look whilst my work was compiling and I can see what's going on here but I cannot yet see why.

It's finding the Light attributes before and after (aka diffuse and position) but no the specular, so that never gets set.

**Comment by fluffyfreak** [comment]
It would appear that it is treating the shininess value differently in the OpenGL 330 shader than it was under the old one.

**Comment by fluffyfreak** [comment]
Ah, I think I might have it now. Worryingly it seems like the normal matrix calculation has been wrong since the update to OpenGL 3.0, not wrong enough to be noticeable all the time but subtley wrong.

Trying to figure out the maths, simple as they are, now and fixing it.

**Comment by nozmajner** [comment]
Stupid Noz and his visuals, right? ;D

**Comment by fluffyfreak** [comment]
Hah! Stupid me and making a mistake in the maths :)

**Comment by fluffyfreak** [comment]
OK, I'm getting closer but there's still some odd stuff going on, not fixed yet will have to continue another day/night.

**Comment by fluffyfreak** [comment]
@nozmajner I think you actually found quite a major bug here! It just doesn't show up so clearly.
I can actually fix it with a tiny bit of extra maths in the shader itself, generating the `uNormalMatrix` in the shader instead of passing it in. 

However whenever I pass it in from the code it is broken!

Either our maths libraries are doing the calculations wrong, or passing it to OpenGL is broken, neither of those are good.

**Comment by nozmajner** [comment]
Collateral upside of incorporationg Pioneer modding into my curriculum. I don't know how long it would took me to notice, if the kid doesn't notice that nothing happens when he changes the spec textures.

**Comment by fluffyfreak** [comment]
Awesome idea incorporating it into your curriculum!
Get feedback on the game too ;)

**Comment by impaktor** [comment]
You could always show your students this issue, and they get a sense about how FOSS development (and github) works, and how feedback leads to bug fixes, provided there is a @fluffyfreak in every project. :)
