### ISSUE TITLE
Error compiling shader

### ISSUE THREAD

**Issue by walterar** [pioneerspacesim/pioneer#3369]
[..]
error: Error compiling shader: shaders/opengl/planetrings.vert:
0(120) : error C7011: implicit cast from "vec4" to "vec2"
OpenGL vendor: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 650/PCIe/SSE2

**Comment by walterar** [comment]
Verified after the fusion of #3367

**Comment by fluffyfreak** [comment]
Strange that I didn't see this before, will fix it asap

**Comment by fluffyfreak** [comment]
@walterar there you go, should be fixed now :)

**Comment by walterar** [comment]
This error is gone, thanks.
