### ISSUE TITLE
openGL error(s) during frame: GL_INVALID_OPERATION (April's 1 build, not a joke :) )

### ISSUE THREAD

**Issue by nozmajner** [pioneerspacesim/pioneer#3376]
openGL error(s) during frame: GL_INVALID_OPERATION error dialog pops up after the loading progress bar finishes. It might be interesting (= frustrating :) ) for @fluffyfreak 
Widows build: 20150402, Windows7 rig with NVidia GPU.
It says 20150201 (50c25a6) in the main menu (like the last two build of March, but those don't give that error dialog.)
After it finished loading:
![opengl_error](https://cloud.githubusercontent.com/assets/4182678/6960555/eb8c90dc-d923-11e4-9fda-a4a071797911.png)
I click OK a couple of times:
![opengl_error2](https://cloud.githubusercontent.com/assets/4182678/6960558/f8c307d6-d923-11e4-9096-8e3da06ffbbb.png)
The main menu shows up, and the ships it displays are unlit, apart from the glow texture.
I managed to click on Barnard's Star start, and the station shows up (the interior is self lit), but I was unable to click on anything because of the error popup.
output.txt: https://www.dropbox.com/s/am05z8bxrq7qg1c/output_0401_opengl_error.txt?dl=0
openGL.txt: https://www.dropbox.com/s/850a1w037b0wzlc/opengl_0401_opengl_error.txt?dl=0

I tried to reinstall the GPU driver, but it didn't fix it.

Woratiklis on IRC reported the same popup for this build.

**Comment by robn** [comment]
Updated compiler in the build host seems to have fixed it. Please test 20150403 when it appears in a few hours and let me know how it goes.

**Comment by nozmajner** [comment]
You guys are awsome.

**Comment by nozmajner** [comment]
20140403 build works. Closing.

**Comment by robn** [comment]
:+1:
