### ISSUE TITLE
Headlook rotates the cockpit model oddly

### ISSUE THREAD

**Issue by nozmajner** [pioneerspacesim/pioneer#3377]
I noticed that the headlook rotates the cockpit model oddly in the opposing direction. I was able to do an almost 180 turn to it by rotating the view around about three times. Happens on both horizontal and vertical rotation.
@dvolk might be interested in this. :)

A gif about it:
https://lh6.googleusercontent.com/-zNEH0s3S48A/VR1LRcmvR9I/AAAAAAAADxY/mB8AQ4UuALI/s2048/mouselook_cockpitrot.gif)

**Comment by fluffyfreak** [comment]
hah cool! nice gif too.

**Comment by fluffyfreak** [comment]
Got a fix for this now :)
