### ISSUE TITLE
Game crashes to desktop, first run, Windows 8.1

### ISSUE THREAD

**Issue by theobromine** [pioneerspacesim/pioneer#3378]
The Error - http://i.imgur.com/gTDNT63.png

Output.txt --
ver 20150403 (76b75fa) on: Windows

Hardware information: 
  		OEM ID: 0
  		Number of processors: 8
  		Page size: 4096
  		Processor type: 586
  		Minimum application address: 10000
  		Maximum application address: 7ffeffff
  		Active processor mask: 255

Windows 8
SDL Version 2.0.3
Initialized OpenGL 3.1, with extensions, renderer
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
Opengl.txt --
OpenGL version 3.1.13283 Core Profile Forward-Compatible Context 14.501.1003.0, running on ATI Technologies Inc. AMD Radeon R9 200 Series
Available extensions:
Shading language version: 4.40
  GL_AMDX_debug_output
  GL_AMD_blend_minmax_factor
  GL_AMD_conservative_depth
  GL_AMD_debug_output
  GL_AMD_depth_clamp_separate
  GL_AMD_draw_buffers_blend
  GL_AMD_framebuffer_sample_positions
  GL_AMD_gcn_shader
  GL_AMD_gpu_shader_int64
  GL_AMD_interleaved_elements
  GL_AMD_multi_draw_indirect
  GL_AMD_name_gen_delete
  GL_AMD_occlusion_query_event
  GL_AMD_performance_monitor
  GL_AMD_pinned_memory
  GL_AMD_query_buffer_object
  GL_AMD_sample_positions
  GL_AMD_seamless_cubemap_per_texture
  GL_AMD_shader_atomic_counter_ops
  GL_AMD_shader_stencil_export
  GL_AMD_shader_stencil_value_export
  GL_AMD_shader_trace
  GL_AMD_shader_trinary_minmax
  GL_AMD_sparse_texture
  GL_AMD_sparse_texture_pool
  GL_AMD_stencil_operation_extended
  GL_AMD_texture_cube_map_array
  GL_AMD_texture_texture4
  GL_AMD_transform_feedback3_lines_triangles
  GL_AMD_transform_feedback4
  GL_AMD_vertex_shader_layer
  GL_AMD_vertex_shader_viewport_index
  GL_ARB_ES2_compatibility
  GL_ARB_ES3_compatibility
  GL_ARB_arrays_of_arrays
  GL_ARB_base_instance
  GL_ARB_bindless_texture
  GL_ARB_blend_func_extended
  GL_ARB_buffer_storage
  GL_ARB_clear_buffer_object
  GL_ARB_clear_texture
  GL_ARB_clip_control
  GL_ARB_color_buffer_float
  GL_ARB_compressed_texture_pixel_storage
  GL_ARB_compute_shader
  GL_ARB_conditional_render_inverted
  GL_ARB_conservative_depth
  GL_ARB_copy_buffer
  GL_ARB_copy_image
  GL_ARB_debug_output
  GL_ARB_depth_buffer_float
  GL_ARB_depth_clamp
  GL_ARB_depth_texture
  GL_ARB_derivative_control
  GL_ARB_draw_buffers
  GL_ARB_draw_buffers_blend
  GL_ARB_draw_elements_base_vertex
  GL_ARB_draw_indirect
  GL_ARB_draw_instanced
  GL_ARB_enhanced_layouts
  GL_ARB_explicit_attrib_location
  GL_ARB_explicit_uniform_location
  GL_ARB_fragment_coord_conventions
  GL_ARB_fragment_layer_viewport
  GL_ARB_fragment_program
  GL_ARB_fragment_program_shadow
  GL_ARB_fragment_shader
  GL_ARB_framebuffer_no_attachments
  GL_ARB_framebuffer_object
  GL_ARB_framebuffer_sRGB
  GL_ARB_geometry_shader4
  GL_ARB_get_program_binary
  GL_ARB_get_texture_sub_image
  GL_ARB_gpu_shader5
  GL_ARB_gpu_shader_fp64
  GL_ARB_half_float_pixel
  GL_ARB_half_float_vertex
  GL_ARB_imaging
  GL_ARB_indirect_parameters
  GL_ARB_instanced_arrays
  GL_ARB_internalformat_query
  GL_ARB_internalformat_query2
  GL_ARB_invalidate_subdata
  GL_ARB_map_buffer_alignment
  GL_ARB_map_buffer_range
  GL_ARB_multi_bind
  GL_ARB_multi_draw_indirect
  GL_ARB_multisample
  GL_ARB_multitexture
  GL_ARB_occlusion_query
  GL_ARB_occlusion_query2
  GL_ARB_pixel_buffer_object
  GL_ARB_point_parameters
  GL_ARB_point_sprite
  GL_ARB_program_interface_query
  GL_ARB_provoking_vertex
  GL_ARB_query_buffer_object
  GL_ARB_sample_shading
  GL_ARB_sampler_objects
  GL_ARB_seamless_cube_map
  GL_ARB_seamless_cubemap_per_texture
  GL_ARB_separate_shader_objects
  GL_ARB_shader_atomic_counters
  GL_ARB_shader_bit_encoding
  GL_ARB_shader_draw_parameters
  GL_ARB_shader_group_vote
  GL_ARB_shader_image_load_store
  GL_ARB_shader_image_size
  GL_ARB_shader_objects
  GL_ARB_shader_precision
  GL_ARB_shader_stencil_export
  GL_ARB_shader_storage_buffer_object
  GL_ARB_shader_subroutine
  GL_ARB_shader_texture_lod
  GL_ARB_shading_language_100
  GL_ARB_shading_language_420pack
  GL_ARB_shading_language_packing
  GL_ARB_shadow
  GL_ARB_shadow_ambient
  GL_ARB_sparse_texture
  GL_ARB_stencil_texturing
  GL_ARB_sync
  GL_ARB_tessellation_shader
  GL_ARB_texture_barrier
  GL_ARB_texture_border_clamp
  GL_ARB_texture_buffer_object
  GL_ARB_texture_buffer_object_rgb32
  GL_ARB_texture_buffer_range
  GL_ARB_texture_compression
  GL_ARB_texture_compression_bptc
  GL_ARB_texture_compression_rgtc
  GL_ARB_texture_cube_map
  GL_ARB_texture_cube_map_array
  GL_ARB_texture_env_add
  GL_ARB_texture_env_combine
  GL_ARB_texture_env_crossbar
  GL_ARB_texture_env_dot3
  GL_ARB_texture_float
  GL_ARB_texture_gather
  GL_ARB_texture_mirror_clamp_to_edge
  GL_ARB_texture_mirrored_repeat
  GL_ARB_texture_multisample
  GL_ARB_texture_non_power_of_two
  GL_ARB_texture_query_levels
  GL_ARB_texture_query_lod
  GL_ARB_texture_rectangle
  GL_ARB_texture_rg
  GL_ARB_texture_rgb10_a2ui
  GL_ARB_texture_snorm
  GL_ARB_texture_stencil8
  GL_ARB_texture_storage
  GL_ARB_texture_storage_multisample
  GL_ARB_texture_swizzle
  GL_ARB_texture_view
  GL_ARB_timer_query
  GL_ARB_transform_feedback2
  GL_ARB_transform_feedback3
  GL_ARB_transform_feedback_instanced
  GL_ARB_transpose_matrix
  GL_ARB_uniform_buffer_object
  GL_ARB_vertex_array_bgra
  GL_ARB_vertex_array_object
  GL_ARB_vertex_attrib_64bit
  GL_ARB_vertex_attrib_binding
  GL_ARB_vertex_buffer_object
  GL_ARB_vertex_program
  GL_ARB_vertex_shader
  GL_ARB_vertex_type_10f_11f_11f_rev
  GL_ARB_vertex_type_2_10_10_10_rev
  GL_ARB_viewport_array
  GL_ARB_window_pos
  GL_ATI_draw_buffers
  GL_ATI_envmap_bumpmap
  GL_ATI_fragment_shader
  GL_ATI_separate_stencil
  GL_ATI_texture_compression_3dc
  GL_ATI_texture_env_combine3
  GL_ATI_texture_float
  GL_ATI_texture_mirror_once
  GL_EXT_abgr
  GL_EXT_bgra
  GL_EXT_bindable_uniform
  GL_EXT_blend_color
  GL_EXT_blend_equation_separate
  GL_EXT_blend_func_separate
  GL_EXT_blend_minmax
  GL_EXT_blend_subtract
  GL_EXT_compiled_vertex_array
  GL_EXT_copy_buffer
  GL_EXT_copy_texture
  GL_EXT_depth_bounds_test
  GL_EXT_direct_state_access
  GL_EXT_draw_buffers2
  GL_EXT_draw_instanced
  GL_EXT_draw_range_elements
  GL_EXT_fog_coord
  GL_EXT_framebuffer_blit
  GL_EXT_framebuffer_multisample
  GL_EXT_framebuffer_object
  GL_EXT_framebuffer_sRGB
  GL_EXT_geometry_shader4
  GL_EXT_gpu_program_parameters
  GL_EXT_gpu_shader4
  GL_EXT_histogram
  GL_EXT_multi_draw_arrays
  GL_EXT_packed_depth_stencil
  GL_EXT_packed_float
  GL_EXT_packed_pixels
  GL_EXT_pixel_buffer_object
  GL_EXT_point_parameters
  GL_EXT_polygon_offset_clamp
  GL_EXT_provoking_vertex
  GL_EXT_rescale_normal
  GL_EXT_secondary_color
  GL_EXT_separate_specular_color
  GL_EXT_shader_image_load_store
  GL_EXT_shader_integer_mix
  GL_EXT_shadow_funcs
  GL_EXT_stencil_wrap
  GL_EXT_subtexture
  GL_EXT_texgen_reflection
  GL_EXT_texture3D
  GL_EXT_texture_array
  GL_EXT_texture_buffer_object
  GL_EXT_texture_compression_bptc
  GL_EXT_texture_compression_latc
  GL_EXT_texture_compression_rgtc
  GL_EXT_texture_compression_s3tc
  GL_EXT_texture_cube_map
  GL_EXT_texture_edge_clamp
  GL_EXT_texture_env_add
  GL_EXT_texture_env_combine
  GL_EXT_texture_env_dot3
  GL_EXT_texture_filter_anisotropic
  GL_EXT_texture_integer
  GL_EXT_texture_lod
  GL_EXT_texture_lod_bias
  GL_EXT_texture_mirror_clamp
  GL_EXT_texture_object
  GL_EXT_texture_rectangle
  GL_EXT_texture_sRGB
  GL_EXT_texture_sRGB_decode
  GL_EXT_texture_shared_exponent
  GL_EXT_texture_snorm
  GL_EXT_texture_storage
  GL_EXT_texture_swizzle
  GL_EXT_timer_query
  GL_EXT_transform_feedback
  GL_EXT_vertex_array
  GL_EXT_vertex_array_bgra
  GL_EXT_vertex_attrib_64bit
  GL_IBM_texture_mirrored_repeat
  GL_INTEL_fragment_shader_ordering
  GL_KHR_debug
  GL_KTX_buffer_region
  GL_NV_blend_square
  GL_NV_conditional_render
  GL_NV_copy_depth_to_color
  GL_NV_copy_image
  GL_NV_depth_buffer_float
  GL_NV_explicit_multisample
  GL_NV_float_buffer
  GL_NV_half_float
  GL_NV_primitive_restart
  GL_NV_texgen_reflection
  GL_NV_texture_barrier
  GL_SGIS_generate_mipmap
  GL_SGIS_texture_edge_clamp
  GL_SGIS_texture_lod
  GL_SUN_multi_draw_arrays
  GL_WIN_swap_hint
  WGL_EXT_swap_control

Implementation Limits:
GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = 192
GL_MAX_CUBE_MAP_TEXTURE_SIZE = 16384
GL_MAX_DRAW_BUFFERS = 8
GL_MAX_ELEMENTS_INDICES = 1.67772e+007
GL_MAX_ELEMENTS_VERTICES = 2.14748e+009
GL_MAX_FRAGMENT_UNIFORM_COMPONENTS = 16384
GL_MAX_TEXTURE_IMAGE_UNITS = 32
GL_MAX_TEXTURE_LOD_BIAS = 16
GL_MAX_TEXTURE_SIZE = 16384
GL_MAX_VERTEX_ATTRIBS = 29
GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = 32
GL_MAX_VERTEX_UNIFORM_COMPONENTS = 16384
GL_NUM_COMPRESSED_TEXTURE_FORMATS = 18
GL_SAMPLE_BUFFERS = 1
GL_SAMPLES = 2
GL_ALIASED_LINE_WIDTH_RANGE = 1, 128
GL_MAX_VIEWPORT_DIMS = 16384, 16384
GL_SMOOTH_LINE_WIDTH_RANGE = 1, 63
GL_SMOOTH_POINT_SIZE_RANGE = 1, 63

Compressed texture formats:
  0x8e8c
  0x8e8d
  0x8e8e
  0x8e8f
  0x83f0
  0x83f1
  0x83f2
  0x83f3
  0x9274
  0x9275
  0x9276
  0x9277
  0x9278
  0x9279
  0x9270
  0x9271
  0x9272
  0x9273

**Comment by nozmajner** [comment]
Hmm. I had the same issue today. Stopped at the same place (output.txt)
Could you try to go in the data/models/ directory and delete all .sgm files you find in the subdirectories?
That fixed it for me (although that was a test build, and the offical build didn't needed that to work).
Just to verify if it's the same thing.

**Comment by theobromine** [comment]
I have deleted all .sgm files under data/models/ and sadly the application still dies with the same error.
Are there any other that I should try to delete?
I am running the official build.
Could you possibly upload the test build that you mentioned for me to try? Visual studio is giving me trouble compiling.

**Comment by fluffyfreak** [comment]
Todays released build works ok for me, I just downloaded it. The [20150403 build](http://sourceforge.net/projects/pioneerspacesim/files/pioneer-20150403-win32.7z/download) is the latest so is that the one you're having trouble with?

**Comment by impaktor** [comment]
I think this is outdated and not going anywhere, I say try again with latest build, if it crashes, open a new issue.

Closing.
