### ISSUE TITLE
PSS  Economy page.

### ISSUE THREAD

**Issue by CarlThrust** [pioneerspacesim/pioneer#3380]
Planet economy page stays on earth status on all planet selections. I am using Linux Mint 64bit setup and the 64 bit version of Pioneer. Reloaded PSS multiple times from different download sights. Can someone please point me in the right direction.
P.s. Bravo on what you have accomplished so far.

**Comment by jmf** [comment]
Can you please tell us, what has to be done to reproduce this bug?
Like: "Press button A, choose menu entry B" etc.
Also, which versions have you tested?

**Comment by CarlThrust** [comment]
Thanks for responding.
    I tried many versions of Pioneer and PioneerSP.
All were of the autolosding type. Last night I started over by compiling the install manually. I started by installing all the support programs then compiled from git. Everything seem to install correctly and the game works fine. Always the same issue, I can activate each planet on the planet page but the economy and democracy stay as earth readouts. Perhaps if I knew what files hold this data I might be able to see if the info is there. I will get the version for you when I get back to my computer.

**Comment by nozmajner** [comment]
The Economy tab shows the economy of the whole system. Planets aren't differentiated in that regard.
When you select a planet, you just set it to navigation target.

**Comment by impaktor** [comment]
Yeah, I'm having problems understanding the bug description. Perhaps a screenshot, and a description of expected behavior, but as nozmajner I think this is probably not a bug being described but a feature.

**Comment by CarlThrust** [comment]
My mistake. I assumed each planet in the solar system required different commodities. This sim, each solar system is a state. Issue closed. Thanks.
