### ISSUE TITLE
CTD in start game with Chinese language

### ISSUE THREAD

**Issue by walterar** [pioneerspacesim/pioneer#3391]
OpenGL version 3.1.0 NVIDIA 331.113, running on NVIDIA Corporation GeForce GTX 650/PCIe/SSE2
Available extensions:
Shading language version: 1.40 NVIDIA via Cg compiler
  GL_AMD_multi_draw_indirect
  GL_AMD_seamless_cubemap_per_texture
  GL_ARB_arrays_of_arrays
  GL_ARB_base_instance
  GL_ARB_bindless_texture
  GL_ARB_blend_func_extended
  GL_ARB_buffer_storage
  GL_ARB_clear_buffer_object
  GL_ARB_clear_texture
  GL_ARB_color_buffer_float
  GL_ARB_compressed_texture_pixel_storage
  GL_ARB_conservative_depth
  GL_ARB_compute_shader
  GL_ARB_compute_variable_group_size
  GL_ARB_copy_buffer
  GL_ARB_copy_image
  GL_ARB_debug_output
  GL_ARB_depth_buffer_float
  GL_ARB_depth_clamp
  GL_ARB_depth_texture
  GL_ARB_draw_buffers
  GL_ARB_draw_buffers_blend
  GL_ARB_draw_indirect
  GL_ARB_draw_elements_base_vertex
  GL_ARB_draw_instanced
  GL_ARB_enhanced_layouts
  GL_ARB_ES2_compatibility
  GL_ARB_ES3_compatibility
  GL_ARB_explicit_attrib_location
  GL_ARB_explicit_uniform_location
  GL_ARB_fragment_coord_conventions
  GL_ARB_fragment_layer_viewport
  GL_ARB_fragment_program
  GL_ARB_fragment_program_shadow
  GL_ARB_fragment_shader
  GL_ARB_framebuffer_no_attachments
  GL_ARB_framebuffer_object
  GL_ARB_framebuffer_sRGB
  GL_ARB_geometry_shader4
  GL_ARB_get_program_binary
  GL_ARB_gpu_shader5
  GL_ARB_gpu_shader_fp64
  GL_ARB_half_float_pixel
  GL_ARB_half_float_vertex
  GL_ARB_imaging
  GL_ARB_indirect_parameters
  GL_ARB_instanced_arrays
  GL_ARB_internalformat_query
  GL_ARB_internalformat_query2
  GL_ARB_invalidate_subdata
  GL_ARB_map_buffer_alignment
  GL_ARB_map_buffer_range
  GL_ARB_multi_bind
  GL_ARB_multi_draw_indirect
  GL_ARB_multisample
  GL_ARB_multitexture
  GL_ARB_occlusion_query
  GL_ARB_occlusion_query2
  GL_ARB_pixel_buffer_object
  GL_ARB_point_parameters
  GL_ARB_point_sprite
  GL_ARB_program_interface_query
  GL_ARB_provoking_vertex
  GL_ARB_robust_buffer_access_behavior
  GL_ARB_robustness
  GL_ARB_sample_shading
  GL_ARB_sampler_objects
  GL_ARB_seamless_cube_map
  GL_ARB_seamless_cubemap_per_texture
  GL_ARB_separate_shader_objects
  GL_ARB_shader_atomic_counters
  GL_ARB_shader_bit_encoding
  GL_ARB_shader_draw_parameters
  GL_ARB_shader_group_vote
  GL_ARB_shader_image_load_store
  GL_ARB_shader_image_size
  GL_ARB_shader_objects
  GL_ARB_shader_precision
  GL_ARB_query_buffer_object
  GL_ARB_shader_storage_buffer_object
  GL_ARB_shader_subroutine
  GL_ARB_shader_texture_lod
  GL_ARB_shading_language_100
  GL_ARB_shading_language_420pack
  GL_ARB_shading_language_include
  GL_ARB_shading_language_packing
  GL_ARB_shadow
  GL_ARB_stencil_texturing
  GL_ARB_sync
  GL_ARB_tessellation_shader
  GL_ARB_texture_border_clamp
  GL_ARB_texture_buffer_object
  GL_ARB_texture_buffer_object_rgb32
  GL_ARB_texture_buffer_range
  GL_ARB_texture_compression
  GL_ARB_texture_compression_bptc
  GL_ARB_texture_compression_rgtc
  GL_ARB_texture_cube_map
  GL_ARB_texture_cube_map_array
  GL_ARB_texture_env_add
  GL_ARB_texture_env_combine
  GL_ARB_texture_env_crossbar
  GL_ARB_texture_env_dot3
  GL_ARB_texture_float
  GL_ARB_texture_gather
  GL_ARB_texture_mirror_clamp_to_edge
  GL_ARB_texture_mirrored_repeat
  GL_ARB_texture_multisample
  GL_ARB_texture_non_power_of_two
  GL_ARB_texture_query_levels
  GL_ARB_texture_query_lod
  GL_ARB_texture_rectangle
  GL_ARB_texture_rg
  GL_ARB_texture_rgb10_a2ui
  GL_ARB_texture_stencil8
  GL_ARB_texture_storage
  GL_ARB_texture_storage_multisample
  GL_ARB_texture_swizzle
  GL_ARB_texture_view
  GL_ARB_timer_query
  GL_ARB_transform_feedback2
  GL_ARB_transform_feedback3
  GL_ARB_transform_feedback_instanced
  GL_ARB_transpose_matrix
  GL_ARB_uniform_buffer_object
  GL_ARB_vertex_array_bgra
  GL_ARB_vertex_array_object
  GL_ARB_vertex_attrib_64bit
  GL_ARB_vertex_attrib_binding
  GL_ARB_vertex_buffer_object
  GL_ARB_vertex_program
  GL_ARB_vertex_shader
  GL_ARB_vertex_type_10f_11f_11f_rev
  GL_ARB_vertex_type_2_10_10_10_rev
  GL_ARB_viewport_array
  GL_ARB_window_pos
  GL_ATI_draw_buffers
  GL_ATI_texture_float
  GL_ATI_texture_mirror_once
  GL_S3_s3tc
  GL_EXT_texture_env_add
  GL_EXT_abgr
  GL_EXT_bgra
  GL_EXT_bindable_uniform
  GL_EXT_blend_color
  GL_EXT_blend_equation_separate
  GL_EXT_blend_func_separate
  GL_EXT_blend_minmax
  GL_EXT_blend_subtract
  GL_EXT_compiled_vertex_array
  GL_EXT_Cg_shader
  GL_EXT_depth_bounds_test
  GL_EXT_direct_state_access
  GL_EXT_draw_buffers2
  GL_EXT_draw_instanced
  GL_EXT_draw_range_elements
  GL_EXT_fog_coord
  GL_EXT_framebuffer_blit
  GL_EXT_framebuffer_multisample
  GL_EXTX_framebuffer_mixed_formats
  GL_EXT_framebuffer_multisample_blit_scaled
  GL_EXT_framebuffer_object
  GL_EXT_framebuffer_sRGB
  GL_EXT_geometry_shader4
  GL_EXT_gpu_program_parameters
  GL_EXT_gpu_shader4
  GL_EXT_multi_draw_arrays
  GL_EXT_packed_depth_stencil
  GL_EXT_packed_float
  GL_EXT_packed_pixels
  GL_EXT_pixel_buffer_object
  GL_EXT_point_parameters
  GL_EXT_provoking_vertex
  GL_EXT_rescale_normal
  GL_EXT_secondary_color
  GL_EXT_separate_shader_objects
  GL_EXT_separate_specular_color
  GL_EXT_shader_image_load_store
  GL_EXT_shadow_funcs
  GL_EXT_stencil_two_side
  GL_EXT_stencil_wrap
  GL_EXT_texture3D
  GL_EXT_texture_array
  GL_EXT_texture_buffer_object
  GL_EXT_texture_compression_dxt1
  GL_EXT_texture_compression_latc
  GL_EXT_texture_compression_rgtc
  GL_EXT_texture_compression_s3tc
  GL_EXT_texture_cube_map
  GL_EXT_texture_edge_clamp
  GL_EXT_texture_env_combine
  GL_EXT_texture_env_dot3
  GL_EXT_texture_filter_anisotropic
  GL_EXT_texture_integer
  GL_EXT_texture_lod
  GL_EXT_texture_lod_bias
  GL_EXT_texture_mirror_clamp
  GL_EXT_texture_object
  GL_EXT_texture_shared_exponent
  GL_EXT_texture_sRGB
  GL_EXT_texture_sRGB_decode
  GL_EXT_texture_storage
  GL_EXT_texture_swizzle
  GL_EXT_timer_query
  GL_EXT_transform_feedback2
  GL_EXT_vertex_array
  GL_EXT_vertex_array_bgra
  GL_EXT_vertex_attrib_64bit
  GL_EXT_x11_sync_object
  GL_EXT_import_sync_object
  GL_IBM_rasterpos_clip
  GL_IBM_texture_mirrored_repeat
  GL_KHR_debug
  GL_KTX_buffer_region
  GL_NV_bindless_multi_draw_indirect
  GL_NV_bindless_texture
  GL_NV_blend_equation_advanced
  GL_NV_blend_square
  GL_NV_compute_program5
  GL_NV_conditional_render
  GL_NV_copy_depth_to_color
  GL_NV_copy_image
  GL_NV_depth_buffer_float
  GL_NV_depth_clamp
  GL_NV_draw_texture
  GL_NV_ES1_1_compatibility
  GL_NV_explicit_multisample
  GL_NV_fence
  GL_NV_float_buffer
  GL_NV_fog_distance
  GL_NV_fragment_program
  GL_NV_fragment_program_option
  GL_NV_fragment_program2
  GL_NV_framebuffer_multisample_coverage
  GL_NV_geometry_shader4
  GL_NV_gpu_program4
  GL_NV_gpu_program4_1
  GL_NV_gpu_program5
  GL_NV_gpu_program5_mem_extended
  GL_NV_gpu_program_fp64
  GL_NV_gpu_shader5
  GL_NV_half_float
  GL_NV_light_max_exponent
  GL_NV_multisample_coverage
  GL_NV_multisample_filter_hint
  GL_NV_occlusion_query
  GL_NV_packed_depth_stencil
  GL_NV_parameter_buffer_object
  GL_NV_parameter_buffer_object2
  GL_NV_path_rendering
  GL_NV_pixel_data_range
  GL_NV_point_sprite
  GL_NV_primitive_restart
  GL_NV_register_combiners
  GL_NV_register_combiners2
  GL_NV_shader_atomic_counters
  GL_NV_shader_atomic_float
  GL_NV_shader_buffer_load
  GL_NV_shader_storage_buffer_object
  GL_ARB_sparse_texture
  GL_NV_texgen_reflection
  GL_NV_texture_barrier
  GL_NV_texture_compression_vtc
  GL_NV_texture_env_combine4
  GL_NV_texture_expand_normal
  GL_NV_texture_multisample
  GL_NV_texture_rectangle
  GL_NV_texture_shader
  GL_NV_texture_shader2
  GL_NV_texture_shader3
  GL_NV_transform_feedback
  GL_NV_transform_feedback2
  GL_NV_vdpau_interop
  GL_NV_vertex_array_range
  GL_NV_vertex_array_range2
  GL_NV_vertex_attrib_integer_64bit
  GL_NV_vertex_buffer_unified_memory
  GL_NV_vertex_program
  GL_NV_vertex_program1_1
  GL_NV_vertex_program2
  GL_NV_vertex_program2_option
  GL_NV_vertex_program3
  GL_NVX_conditional_render
  GL_NVX_gpu_memory_info
  GL_NVX_nvenc_interop
  GL_SGIS_generate_mipmap
  GL_SGIS_texture_lod
  GL_SGIX_depth_texture
  GL_SGIX_shadow
  GL_SUN_slice_accum

Implementation Limits:
GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = 192
GL_MAX_CUBE_MAP_TEXTURE_SIZE = 16384
GL_MAX_DRAW_BUFFERS = 8
GL_MAX_ELEMENTS_INDICES = 1.04858e+06
GL_MAX_ELEMENTS_VERTICES = 1.04858e+06
GL_MAX_FRAGMENT_UNIFORM_COMPONENTS = 2048
GL_MAX_TEXTURE_IMAGE_UNITS = 32
GL_MAX_TEXTURE_LOD_BIAS = 15
GL_MAX_TEXTURE_SIZE = 16384
GL_MAX_VERTEX_ATTRIBS = 16
GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = 32
GL_MAX_VERTEX_UNIFORM_COMPONENTS = 4096
GL_NUM_COMPRESSED_TEXTURE_FORMATS = 23
GL_SAMPLE_BUFFERS = 1
GL_SAMPLES = 2
GL_ALIASED_LINE_WIDTH_RANGE = 1, 10
GL_MAX_VIEWPORT_DIMS = 16384, 16384
GL_SMOOTH_LINE_WIDTH_RANGE = 1, 1
GL_SMOOTH_POINT_SIZE_RANGE = 1, 189.875

Compressed texture formats:
  0x83f0
  0x83f2
  0x83f3
  0x8b90
  0x8b91
  0x8b92
  0x8b93
  0x8b94
  0x8b95
  0x8b96
  0x8b97
  0x8b98
  0x8b99
  0x9274
  0x9275
  0x9276
  0x9277
  0x9278
  0x9279
  0x9270
  0x9271
  0x9272
  0x9273

ver git (24b118a) on: Linux

System Name: Linux
Host Name: oper-H61M-USB3-B3
Release(Kernel) Version: 3.2.0-85-generic
Kernel Build Timestamp: #122-Ubuntu SMP Tue May 26 16:14:57 UTC 2015
Machine Arch: x86_64
Domain Name: (none)

SDL Version 2.0.3
Initialized OpenGL 3.1, with extensions, renderer
invalid axis binding '' in config file for BindAxisPitch
invalid axis binding '' in config file for BindAxisRoll
invalid axis binding '' in config file for BindAxisYaw
started 4 worker threads
ShipType::Init()
Lua::Init()
Server agent disabled
GalaxyGenerator::Init()
Creating new galaxy generator 'legacy' version 1
Number of factions added: 103
StarSystemCache: misses: 2227, slave hits: 0, master hits: 0
SectorCache: misses: 1571, slave hits: 0, master hits: 11138
FaceParts::Init()
Face Generation source images loaded.
new ModelCache
Shields::Init
BaseSphere::Init
CityOnPlanet::Init
CreateCollisionMesh for : (kbuilding01)
CreateCollisionMesh for : (kbuilding02)
CreateCollisionMesh for : (kbuilding03)
CreateCollisionMesh for : (newbuilding1)
CreateCollisionMesh for : (newbuilding10)
CreateCollisionMesh for : (newbuilding11)
CreateCollisionMesh for : (newbuilding2)
CreateCollisionMesh for : (newbuilding3)
CreateCollisionMesh for : (newbuilding4)
CreateCollisionMesh for : (newbuilding5)
CreateCollisionMesh for : (newbuilding6)
CreateCollisionMesh for : (newbuilding7)
CreateCollisionMesh for : (newbuilding8)
CreateCollisionMesh for : (newbuilding9)
Got 14 buildings of tag city_building
 - kbuilding01: 29.664692
 - kbuilding02: 46.268344
 - kbuilding03: 41.542333
 - newbuilding1: 36.202756
 - newbuilding10: 16.297418
 - newbuilding11: 34.961034
 - newbuilding2: 22.822782
 - newbuilding3: 22.649894
 - newbuilding4: 25.978193
 - newbuilding5: 22.908506
 - newbuilding6: 29.817877
 - newbuilding7: 22.674426
 - newbuilding8: 23.154979
 - newbuilding9: 36.528138
End of buildings.
SpaceStation::Init
CreateCollisionMesh for : (ground_station)
ground_station has:
 14 entrances,
 14 pads,
 0 exits
CreateCollisionMesh for : (new_ground)
new_ground has:
 6 entrances,
 6 pads,
 0 exits
CreateCollisionMesh for : (orbital_station_2-10k)
orbital_station_2-10k has:
 5 entrances,
 64 pads,
 5 exits
CreateCollisionMesh for : (orbital_station_2-5k)
orbital_station_2-5k has:
 5 entrances,
 64 pads,
 5 exits
CreateCollisionMesh for : (orbital_station_2-5k10k)
orbital_station_2-5k10k has:
 5 entrances,
 64 pads,
 5 exits
NavLights::Init
Sfx::Init
Sound::Init

Loading took: 48145.643232 milliseconds
CreateCollisionMesh for : (ac33)
CreateCollisionMesh for : (amphiesma)
CreateCollisionMesh for : (deneb)
CreateCollisionMesh for : (dsminer)
CreateCollisionMesh for : (kanara_civ)
CreateCollisionMesh for : (lunarshuttle)
CreateCollisionMesh for : (malabar)
CreateCollisionMesh for : (molamola)
CreateCollisionMesh for : (natrix)
CreateCollisionMesh for : (nerodia)
CreateCollisionMesh for : (pumpkinseed)
CreateCollisionMesh for : (sinonatrix)
CreateCollisionMesh for : (storeria)
CreateCollisionMesh for : (varada)
CreateCollisionMesh for : (vatakara)
CreateCollisionMesh for : (venturestar)
CreateCollisionMesh for : (wave)
CreateCollisionMesh for : (xylophis)
pioneer: VertexBufferGL.cpp:61: Graphics::OGL::VertexBuffer::VertexBuffer(const Graphics::VertexBufferDesc&): Assertion `m_desc.numVertices > 0' failed.

**Comment by impaktor** [comment]
From the title of this issue, should we assume it works when selecting english or spanish language?

**Comment by walterar** [comment]
Happens in my pc (es.json) when Pioneer Chinese language change (zh.json). Someone else will happen?

**Comment by walterar** [comment]
This is an old known difficult to catch:
pioneer: VertexBufferGL.cpp:61: Graphics::OGL::VertexBuffer::VertexBuffer(const Graphics::VertexBufferDesc&): Assertion `m_desc.numVertices > 0' failed.

**Comment by impaktor** [comment]
I'm not sure I've understood what is being reported. Perhaps this will clear my confusion:
1. You get no crash when playing on english language? 
2. You get no crash when playing on Spanish language?
3. You get no crash when changing between Spanish and English?
4. You do get a crash when starting a new game if language is Chinese?
5. How often does it crash? Every time you try number 4 above or only sometimes?
6. Can you reproduce it on latest build?

Also, we just built a new more stable version of pioneer, fixing some recent crash bugs, and save/load bugs, so those were not what you were reporting here?

**Comment by walterar** [comment]
@impaktor You can run the latest version of Pioneer?

**Comment by impaktor** [comment]
> You can run the latest version of Pioneer?

Before jpab's fix yesterday with #3402 I could not. I haven't tried the latest version since I'm not at the right computer until tomorrow. I'll get back to you then.

**Comment by johnbartholomew** [comment]
Text on 3D objects is rendered using the `data/fonts/label3d.png` texture, which is a signed distance field rendering of the Orbiteer font. This font does not include Chinese characters. When the code tries to render text containing only Chinese characters, `Text::DistanceFieldFont::GetGeometry` gives geometry with no vertices, which triggers this assertion.

Backtrace:
```
#0  0x00007ffff53ca528 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff53cb93a in abort () from /usr/lib/libc.so.6
#2  0x00007ffff53c33a7 in __assert_fail_base () from /usr/lib/libc.so.6
#3  0x00007ffff53c3452 in __assert_fail () from /usr/lib/libc.so.6
#4  0x0000000000647155 in Graphics::OGL::VertexBuffer::VertexBuffer (this=0xc97ab30, 
    desc=...) at ../../../../pioneer/src/graphics/opengl/VertexBufferGL.cpp:61
#5  0x0000000000634dc7 in Graphics::RendererOGL::CreateVertexBuffer (this=0x2740300, 
    desc=...) at ../../../../pioneer/src/graphics/opengl/RendererGL.cpp:830
#6  0x00000000006ae542 in SceneGraph::Label3D::SetText (this=0xea32bf0, text="先锋")
    at ../../../pioneer/src/scenegraph/Label3D.cpp:64
#7  0x00000000006be219 in SceneGraph::LabelUpdateVisitor::ApplyLabel (
    this=0x7fffffffe060, l=...) at ../../../pioneer/src/scenegraph/Model.cpp:18
#8  0x00000000006ae696 in SceneGraph::Label3D::Accept (this=0xea32bf0, nv=...)
    at ../../../pioneer/src/scenegraph/Label3D.cpp:82
#9  0x00000000006acf6a in SceneGraph::Group::Traverse (this=0xf78e780, nv=...)
    at ../../../pioneer/src/scenegraph/Group.cpp:113
#10 0x00000000006c3056 in SceneGraph::NodeVisitor::ApplyNode (this=0x7fffffffe060, n=...)
    at ../../../pioneer/src/scenegraph/NodeVisitor.cpp:19
#11 0x00000000006c3088 in SceneGraph::NodeVisitor::ApplyGroup (this=0x7fffffffe060, 
    g=...) at ../../../pioneer/src/scenegraph/NodeVisitor.cpp:24
#12 0x00000000006c311e in SceneGraph::NodeVisitor::ApplyMatrixTransform (
    this=0x7fffffffe060, m=...) at ../../../pioneer/src/scenegraph/NodeVisitor.cpp:39
#13 0x00000000006b9462 in SceneGraph::MatrixTransform::Accept (this=0xf78e780, nv=...)
    at ../../../pioneer/src/scenegraph/MatrixTransform.cpp:30
#14 0x00000000006acf6a in SceneGraph::Group::Traverse (this=0xea33690, nv=...)
    at ../../../pioneer/src/scenegraph/Group.cpp:113
#15 0x00000000006c3056 in SceneGraph::NodeVisitor::ApplyNode (this=0x7fffffffe060, n=...)
    at ../../../pioneer/src/scenegraph/NodeVisitor.cpp:19
#16 0x00000000006c3088 in SceneGraph::NodeVisitor::ApplyGroup (this=0x7fffffffe060, 
    g=...) at ../../../pioneer/src/scenegraph/NodeVisitor.cpp:24
#17 0x00000000006c311e in SceneGraph::NodeVisitor::ApplyMatrixTransform (
    this=0x7fffffffe060, m=...) at ../../../pioneer/src/scenegraph/NodeVisitor.cpp:39
#18 0x00000000006b9462 in SceneGraph::MatrixTransform::Accept (this=0xea33690, nv=...)
    at ../../../pioneer/src/scenegraph/MatrixTransform.cpp:30
#19 0x00000000006acf6a in SceneGraph::Group::Traverse (this=0xea333d0, nv=...)
    at ../../../pioneer/src/scenegraph/Group.cpp:113
#20 0x00000000006c3056 in SceneGraph::NodeVisitor::ApplyNode (this=0x7fffffffe060, n=...)
    at ../../../pioneer/src/scenegraph/NodeVisitor.cpp:19
#21 0x00000000006c3088 in SceneGraph::NodeVisitor::ApplyGroup (this=0x7fffffffe060, 
    g=...) at ../../../pioneer/src/scenegraph/NodeVisitor.cpp:24
#22 0x00000000006acef2 in SceneGraph::Group::Accept (this=0xea333d0, nv=...)
    at ../../../pioneer/src/scenegraph/Group.cpp:106
#23 0x00000000006acf6a in SceneGraph::Group::Traverse (this=0xf7b27e0, nv=...)
    at ../../../pioneer/src/scenegraph/Group.cpp:113
#24 0x00000000006c3056 in SceneGraph::NodeVisitor::ApplyNode (this=0x7fffffffe060, n=...)
    at ../../../pioneer/src/scenegraph/NodeVisitor.cpp:19
#25 0x00000000006c3088 in SceneGraph::NodeVisitor::ApplyGroup (this=0x7fffffffe060, 
    g=...) at ../../../pioneer/src/scenegraph/NodeVisitor.cpp:24
#26 0x00000000006acef2 in SceneGraph::Group::Accept (this=0xf7b27e0, nv=...)
    at ../../../pioneer/src/scenegraph/Group.cpp:106
#27 0x00000000006acf6a in SceneGraph::Group::Traverse (this=0xc652b90, nv=...)
    at ../../../pioneer/src/scenegraph/Group.cpp:113
#28 0x00000000006c3056 in SceneGraph::NodeVisitor::ApplyNode (this=0x7fffffffe060, n=...)
    at ../../../pioneer/src/scenegraph/NodeVisitor.cpp:19
#29 0x00000000006c3088 in SceneGraph::NodeVisitor::ApplyGroup (this=0x7fffffffe060, 
    g=...) at ../../../pioneer/src/scenegraph/NodeVisitor.cpp:24
#30 0x00000000006c31b4 in SceneGraph::NodeVisitor::ApplyLOD (this=0x7fffffffe060, l=...)
    at ../../../pioneer/src/scenegraph/NodeVisitor.cpp:54
#31 0x00000000006b78fa in SceneGraph::LOD::Accept (this=0xc652b90, nv=...)
    at ../../../pioneer/src/scenegraph/LOD.cpp:30
#32 0x00000000006acf6a in SceneGraph::Group::Traverse (this=0xea33790, nv=...)
    at ../../../pioneer/src/scenegraph/Group.cpp:113
#33 0x00000000006c3056 in SceneGraph::NodeVisitor::ApplyNode (this=0x7fffffffe060, n=...)
    at ../../../pioneer/src/scenegraph/NodeVisitor.cpp:19
#34 0x00000000006c3088 in SceneGraph::NodeVisitor::ApplyGroup (this=0x7fffffffe060, 
    g=...) at ../../../pioneer/src/scenegraph/NodeVisitor.cpp:24
#35 0x00000000006acef2 in SceneGraph::Group::Accept (this=0xea33790, nv=...)
    at ../../../pioneer/src/scenegraph/Group.cpp:106
#36 0x00000000006bccce in SceneGraph::Model::SetLabel (this=0xf626620, text="先锋")
    at ../../../pioneer/src/scenegraph/Model.cpp:412
#37 0x00000000006c1b15 in SceneGraph::ModelSkin::Apply (this=0xadb08a0, model=0xf626620)
    at ../../../pioneer/src/scenegraph/ModelSkin.cpp:27
#38 0x00000000004a0abd in Intro::Reset (this=0xadb0840, _time=0)
    at ../../pioneer/src/Intro.cpp:76
#39 0x00000000004a0bc5 in Intro::Draw (this=0xadb0840, _time=0)
    at ../../pioneer/src/Intro.cpp:93
#40 0x000000000051d455 in Pi::Start () at ../../pioneer/src/Pi.cpp:1076
#41 0x00000000005f717e in main (argc=1, argv=0x7fffffffe878)
    at ../../pioneer/src/main.cpp:130
```

**Comment by walterar** [comment]
#3405 resolve this, thanks John :+1:

**Comment by impaktor** [comment]
@walterar that was a quite a find you did, considering you're not chinese. :+1:

I don't know why you wanted to play pioneer in Mandarin, but we're glad you did, since there's zero communication with the chinese pioneer-community, sadly.
