### ISSUE TITLE
Need scripts for automatically compiling and building app bundles for Mac.

### ISSUE THREAD

**Issue by eloquentmess** [pioneerspacesim/pioneer#3401]
I wrote some scripts to build on Mac. Now I need to upload them and clean them up a little so I can give them to you all.

**Comment by eloquentmess** [comment]
I just reformatted my Mac so it's a good opportunity to write the "how to" guide for compiling for Mac. I'll create the guide and upload my scripts ASAP.

**Comment by impaktor** [comment]
Perhaps have a look at #3397 and see if that is thumbs up or if you have done things in a different way?

**Comment by eloquentmess** [comment]
I've created an empty App Bundle shell and a .md document which explains how to create the Mac App Bundle from scratch. I believe that both files should be added to the repo in the root directory. As for scripted builds and uploads, my scripts are pretty ugly, and you guys might be able to make something better, so I'll just worry about uploading the manual instructions for now. Everything can be done via command-line, so it shouldn't be hard to automate the build process (though I don't know how to account for errors in compilation).

The files are [here](https://drive.google.com/a/eloquentmess.com/file/d/0B-NGCFl5t09ZLV84NDB6Vktub2M/view?usp=sharing). Feel free to have a look at them before adding them to the repository, but please add them to the repository so that future Mac builders will be able to do it themselves. Also, these instructions should replace the currently-available mac build instructions, so be sure to remove those from the repo as well.

The tutorial provides step-by-step instructions for:
* preparing your build environment
* compiling the program
* building the Mac App Bundle

**Comment by eloquentmess** [comment]
(I'd add these files myself, except I don't recall how to do all the git commit stuff.)

**Comment by impaktor** [comment]
That's awesome work @eloquentmess.

However, seems like I can't access the files without logging in or something. Is it possible to make the access public / viewable to all, or am I doing something wrong?

**Comment by eloquentmess** [comment]
[Fixed the link.](https://drive.google.com/file/d/0B-NGCFl5t09ZLV84NDB6Vktub2M/view?usp=sharing)

**Comment by eloquentmess** [comment]
If we can simply add the two files contained within the zip archive to the Pioneer root directory (where the README.md is located) then that ought to be enough for anyone to be able to manually compile and build via Mac.

**Comment by eloquentmess** [comment]
(One of the files is actually a folder -- Mac's app bundles are just folders with the .app extension which contain required files.)

**Comment by eloquentmess** [comment]
This script will automatically update, compile and build the latest Pioneer App Bundle for Mac, assuming the setup steps have already been performed:

```
#!/bin/bash

# This script will automatically build and bundle Pioneer.

git pull
./bootstrap
LDFLAGS="-L/System/Library/Frameworks/OpenGL.framework/Libraries -L/System/Library/Frameworks/GLUT.framework" ./configure
make -j 8

rm -fr Pioneer.app
cp -R BundleShell.app/ Pioneer.app
cp ./src/pioneer ./Pioneer.app/Contents/Resources/pioneer
rm -fr ./Pioneer.app/Contents/Resources/data/
cp -R data/ Pioneer.app/Contents/Resources/data
/usr/local/bin/dylibbundler -od -of -b -x ./Pioneer.app/Contents/Resources/pioneer -d ./Pioneer.app/Contents/libs/

GitVersion=$(git log -1 --format=%h)
OSVersion=$(sw_vers -productVersion)

cat <<- _EOF_ > ./Pioneer.app/Contents/Info.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>English</string>
    <key>CFBundleDisplayName</key>
    <string>Pioneer</string>
    <key>CFBundleExecutable</key>
    <string>Pioneer</string>
    <key>CFBundleIconFile</key>
    <string>appIcon.icns</string>
    <key>CFBundleIdentifier</key>
    <string>net.pioneerspacesim.Pioneer</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>Pioneer</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>$GitVersion</string>
    <key>CFBundleVersion</key>
    <string>$GitVersion</string>
    <key>LSMinimumSystemVersion</key>
    <string>$OSVersion</string>
    <key>LSUIElement</key>
    <false/>
    <key>NSHumanReadableCopyright</key>
    <string>© 2015 PioneerSpaceSim.net</string>
    <key>NSMainNibFile</key>
    <string>MainMenu</string>
    <key>NSPrincipalClass</key>
    <string>NSApplication</string>
</dict>
</plist>
_EOF_

date=$(date +"%Y%m%d")

zip -r pioneer-$date-osx.zip Pioneer.app
```

**Comment by eloquentmess** [comment]
(Note: There is no error handling in that script.)

**Comment by impaktor** [comment]
With #3540 merged, perhaps this is up next? Perhaps @salborrelli has opinions? @fluffyfreak?

**Comment by fluffyfreak** [comment]
Useful for me doing it although might be redundant with the XCode fixes.

Keep it open for now.

**Comment by impaktor** [comment]
Two years later now... and we have mac builder on the team, with the return of @Philbywhizz -> Closing
