### ISSUE TITLE
When you retrieve a saved game, stations and ships disappear.

### ISSUE THREAD

**Issue by walterar** [pioneerspacesim/pioneer#3404]
Linux. After #3402

**Comment by walterar** [comment]
@johnbartholomew I'm happy that you're there, do not go yet. :))

**Comment by johnbartholomew** [comment]
Yes. The save system seems to be broken.

**Comment by johnbartholomew** [comment]
Should be fixed now, but the bug was in the game save code, so saves made after #3402 and before @f8f5da52e4f06ac8e6f7af11d92f0ea5f8b3eda2 will be corrupted and will never load correctly.
