### ISSUE TITLE
Error compiling shader, can't start game

### ISSUE THREAD

**Issue by zxcv186** [pioneerspacesim/pioneer#3415]
Error compiling shader: shaders/opengl/vtxColor.vert:
ERROR: 3:30: 'location' : syntax error parse error

OpenGL vendor: Intel
OpenGL renderer string: Intel(R) HD Graphics

opengl.txt
OpenGL version 2.1.0 - Build 8.15.10.2993, running on Intel Intel(R) HD Graphics
Available extensions:
Shading language version: 1.20  - Intel Build 8.15.10.2993
  GL_EXT_blend_minmax
  GL_EXT_blend_subtract
  GL_EXT_blend_color
  GL_EXT_abgr
  GL_EXT_texture3D
  GL_EXT_clip_volume_hint
  GL_EXT_compiled_vertex_array
  GL_SGIS_texture_edge_clamp
  GL_SGIS_generate_mipmap
  GL_EXT_draw_range_elements
  GL_SGIS_texture_lod
  GL_EXT_rescale_normal
  GL_EXT_packed_pixels
  GL_EXT_texture_edge_clamp
  GL_EXT_separate_specular_color
  GL_ARB_multitexture
  GL_EXT_texture_env_combine
  GL_EXT_bgra
  GL_EXT_blend_func_separate
  GL_EXT_secondary_color
  GL_EXT_fog_coord
  GL_EXT_texture_env_add
  GL_ARB_texture_cube_map
  GL_ARB_transpose_matrix
  GL_ARB_texture_env_add
  GL_IBM_texture_mirrored_repeat
  GL_EXT_multi_draw_arrays
  GL_NV_blend_square
  GL_ARB_texture_compression
  GL_3DFX_texture_compression_FXT1
  GL_EXT_texture_filter_anisotropic
  GL_ARB_texture_border_clamp
  GL_ARB_point_parameters
  GL_ARB_texture_env_combine
  GL_ARB_texture_env_dot3
  GL_ARB_texture_env_crossbar
  GL_EXT_texture_compression_s3tc
  GL_ARB_shadow
  GL_ARB_window_pos
  GL_EXT_shadow_funcs
  GL_EXT_stencil_wrap
  GL_ARB_vertex_program
  GL_EXT_texture_rectangle
  GL_ARB_fragment_program
  GL_EXT_stencil_two_side
  GL_ATI_separate_stencil
  GL_ARB_vertex_buffer_object
  GL_EXT_texture_lod_bias
  GL_ARB_occlusion_query
  GL_ARB_fragment_shader
  GL_ARB_shader_objects
  GL_ARB_shading_language_100
  GL_ARB_texture_non_power_of_two
  GL_ARB_vertex_shader
  GL_NV_texgen_reflection
  GL_ARB_point_sprite
  GL_ARB_fragment_program_shadow
  GL_EXT_blend_equation_separate
  GL_ARB_depth_texture
  GL_ARB_texture_rectangle
  GL_ARB_draw_buffers
  GL_ARB_color_buffer_float
  GL_ARB_half_float_pixel
  GL_ARB_texture_float
  GL_ARB_pixel_buffer_object
  GL_EXT_framebuffer_object
  GL_ARB_draw_instanced
  GL_ARB_half_float_vertex
  GL_EXT_draw_buffers2
  GL_WIN_swap_hint
  GL_EXT_texture_sRGB
  GL_EXT_packed_float
  GL_EXT_texture_shared_exponent
  GL_ARB_texture_rg
  GL_ARB_texture_compression_rgtc
  GL_NV_conditional_render
  GL_EXT_texture_swizzle
  GL_ARB_sync
  GL_ARB_framebuffer_sRGB
  GL_EXT_packed_depth_stencil
  GL_ARB_depth_buffer_float
  GL_EXT_transform_feedback
  GL_EXT_framebuffer_blit
  GL_ARB_framebuffer_object
  GL_EXT_texture_array
  GL_ARB_map_buffer_range
  GL_EXT_texture_snorm
  GL_INTEL_performance_queries
  GL_ARB_copy_buffer
  GL_ARB_sampler_objects
  GL_NV_primitive_restart
  GL_ARB_seamless_cube_map
  GL_ARB_uniform_buffer_object
  GL_ARB_depth_clamp
  GL_ARB_vertex_array_bgra
  GL_ARB_draw_elements_base_vertex
  GL_EXT_gpu_program_parameters
  GL_ARB_compatibility
  GL_ARB_vertex_array_object
  WGL_EXT_depth_float
  WGL_ARB_buffer_region
  WGL_ARB_extensions_string
  WGL_ARB_make_current_read
  WGL_ARB_pixel_format
  WGL_ARB_pbuffer
  WGL_EXT_extensions_string
  WGL_EXT_swap_control
  WGL_EXT_swap_control_tear
  WGL_ARB_pixel_format_float
  WGL_ARB_framebuffer_sRGB
  WGL_ARB_create_context
  WGL_EXT_pixel_format_packed_float

Implementation Limits:
GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = 16
GL_MAX_CUBE_MAP_TEXTURE_SIZE = 8192
GL_MAX_DRAW_BUFFERS = 8
GL_MAX_ELEMENTS_INDICES = 1200
GL_MAX_ELEMENTS_VERTICES = 1200
GL_MAX_FRAGMENT_UNIFORM_COMPONENTS = 1024
GL_MAX_TEXTURE_IMAGE_UNITS = 16
GL_MAX_TEXTURE_LOD_BIAS = 15
GL_MAX_TEXTURE_SIZE = 8192
GL_MAX_VERTEX_ATTRIBS = 16
GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = 16
GL_MAX_VERTEX_UNIFORM_COMPONENTS = 512
GL_NUM_COMPRESSED_TEXTURE_FORMATS = 6
GL_SAMPLE_BUFFERS = 0
GL_SAMPLES = 0
GL_ALIASED_LINE_WIDTH_RANGE = 1, 7
GL_MAX_VIEWPORT_DIMS = 8192, 8192
GL_SMOOTH_LINE_WIDTH_RANGE = 0, 6.5
GL_SMOOTH_POINT_SIZE_RANGE = 0.5, 10

Compressed texture formats:
  0x83f0
  0x83f2
  0x83f3
  0x83f1
  0x86b0
  0x86b1

output.txt
ver 20150701 (8c141e7) on: Windows

Hardware information: 
  		OEM ID: 0
  		Number of processors: 4
  		Page size: 4096
  		Processor type: 586
  		Minimum application address: 10000
  		Maximum application address: 7ffeffff
  		Active processor mask: 15

Windows 7
SDL Version 2.0.3
Initialized OpenGL 3.1, with extensions, renderer
error: Error compiling shader: shaders/opengl/vtxColor.vert:
ERROR: 3:30: 'location' : syntax error parse error

OpenGL vendor: Intel
OpenGL renderer string: Intel(R) HD Graphics

**Comment by fluffyfreak** [comment]
That GPU the "Intel HD" is returning an OpenGL 2.1 version, it looks like your GPU cannot run the game.

**Comment by zxcv186** [comment]
well, what a bummer, guess I'll have to look for another laptop then.
