### ISSUE TITLE
Ground station landing and collision missing on Qulia Chou's grave (11 0 0)

### ISSUE THREAD

**Issue by nozmajner** [pioneerspacesim/pioneer#3441]
[Marcel stumbled upon a ground base in Scout+](http://spacesimcentral.com/ssc/topic/4211-things-related-to-scout/?p=54916), where it's impossible to land. It happens in Pioneer too.
He mentions different station names from what you see in Pioneer and there's only one, but that's most likely because they are generated differently.
You can't land on the ground base Mullen Station on Chou's Grave in the Qulia system (11 0 0). And you can't even collide with the base, or anything it seems. Or with the planet itself.
Enabling the collision mesh display for the station and the ship shows them properly.

[Here's a save file, so you don't have to hunt and travel to it.](https://www.dropbox.com/s/3sbr4hk0xo7i22v/mullen_base_2?dl=0)
Made on windows, build: 20150810 (0bd8149)
![screenshot-20150822-235759](https://cloud.githubusercontent.com/assets/4182678/9426172/e2edbe0c-492f-11e5-85e7-812b07bd5dad.png)

The strange thing is that the station, and even the city buildings stutters back and forth, while you are hovering at 0 m/s. Quite visible when you turn up time acceleration, and a bit similar to when you leave the reference frame of an orbital sometimes.
What I noticed that the planet seems to rotate and orbit it's star quite fast.
When you switch off the autopilot (I was landing with it at first), you instantly get a 60 m/s speed.  If you switch the frame of reference to the station, and set speed to 0, the speed indicator tells you you are moving at 61 m/s relative to it, while standing still above it. If you switch the frame to the planet, the station instantly starts to go away from you as the autopilot brakes for a bit, and then stops.

And I noticed that the longitude of the station is constantly changing, while you are hovering above it, and the latitude remains the same. Like if the station/city was orbiting the planet at ground level or something, but it's hard to tell if it's really moving, because the area is quite featureless. Both with Very High and Very Low detail settings. It doesn't seem to be moving away from it's position, when I was watching it from orbit, but it's hard to tell.

The planet is not much larger or heavier than Earth (1.5x, 1.2x), and it has a day length and orbital period of 8.1 days, so it's tidally locked. It orbits it's star, a brown dwarf at a distance of about 5 million km or 0.03 AU.

You can dock with Kennedy Station and the other stations on the other planets, in an even tighter and faster orbits, and are  also tidally locked but the speed or latitude thing I described doesn't happen there. Also you can dock with the station orbiting the planet.

**Comment by walterar** [comment]
Similar
Wise Town, Ancequ (4,-2,-2)

**Comment by Marcel-T** [comment]
Interesting. I was thinking that because the system is procedurally generated from the system co-ordinates, the two zeroes might generate a divide by zero error or some such somewhere. Could the two -twos somehow procedurally generate the same sort of error?

**Comment by fluffyfreak** [comment]
That's very strange. I'll have to dig into this one I think!

**Comment by Marcel-T** [comment]
I just remembered this. It may be related to this bug. It's from Scout Plus 23
![screenshot from 2015-07-17 21 42 24](https://cloud.githubusercontent.com/assets/730819/9570606/f4d51b72-4f44-11e5-99e6-a8b067ee9459.png)

**Comment by fluffyfreak** [comment]
I bet @johnbartholomew would be interested in this too, he's got a better idea of how the reference frames and things work than I do.

**Comment by fluffyfreak** [comment]
@Marcel-T that's not usually how the random generator works. It sums the sector coordinates along with other data, and a universe seed so there's always some entropy in there.

**Comment by fluffyfreak** [comment]
Ok, I discussed this briefly with JohnJ (not on GitHub?) via IRC last night and looking into this I've found several odd things.

 - The planet appears to be perfectly smooth.
 - When approaching the surfaces mullen station we are NOT in a rotating frame.
 - When dumping the frames in debug Mullen station is NOT in the frame hierarchy!?!

**Comment by fluffyfreak** [comment]
Further the player seems to be relative to `Chou's Grave` the parent and not `Chou's Grave` the body. Which I think it should be... this is all a bit confusing.

**Comment by fluffyfreak** [comment]
Ok, it seems like it never switches to the body frame from the planet one.
When approaching `New Hope` for example you will get put into the `New Hope` frame, then as you approach the surface you get put into the body's `New Hope` frame.

That doesn't happen with `Mullen Station` on `Chou's Grave` for some reason.

**Comment by fluffyfreak** [comment]
Oh FFS.

`Barren Rock` multiplies the return values by `m_maxHeight*2.0*n*n` which looks like it makes the height of the terrain some massive value. 

So the usual test of how far away you are fails, because it doesn't rely on the actual height values of the terrain (expensive to get) but on the supposed radius on the planet + atmosphere or other factors.

I don't know why it was set to that yet but there does seem to be a problem landing there now that I've changed it to the usual `m_maxHeight*n`. These noise systems are too unpredictable.
