### ISSUE TITLE
OS X Homebrew formula

### ISSUE THREAD

**Issue by tomyun** [pioneerspacesim/pioneer#3443]
I've just made a formula for the OS X package manager, [Homebrew](http://brew.sh/):

Homebrew/homebrew-games#329

It's not building an app bundle for you, but still easily installable by just typing `brew install pioneer`. If interested, please have a look and leave any issues or comments.

**Comment by nozmajner** [comment]
Oh, nobody commented on this ever since? I guess because none of us have any apples around to properly test it, but let's shout them up anyway. :)
@impaktor @fluffyfreak @johnbartholomew

**Comment by johnbartholomew** [comment]
I don't have a system I can test this on, but we should probably mention it in COMPILING.txt

https://github.com/pioneerspacesim/pioneer/blob/master/COMPILING.txt

**Comment by impaktor** [comment]
I have no clue what any of this means. Is it like a build script for pioneer on Mac?
Is there anything we should do?

@tomyun could you suggest text to be added to COMPILING:txt?

**Comment by tomyun** [comment]
Just opened a PR for COMPILING.txt: #3447

**Comment by impaktor** [comment]
OK, so the new Hombrew PR is: https://github.com/Homebrew/homebrew-games/pull/411

Given that in the past month they have 52 open PRs and 0 merged, I'm sceptical to how long it will take for them to merge it.

**Comment by tomyun** [comment]
Homebrew doesn't rely on GitHub's merge feature, instead let maintainers commit themselves after sign-off each PR, so their merge count could be quite misleading. But, it's also true that it's taking longer than usual. I guess they've been pretty busy getting ready for El Captian released this week. I'll ping them again anyways.

**Comment by tomyun** [comment]
`pioneer` is now available via `homebrew-games`.
