### ISSUE TITLE
Build fails in MSVC

### ISSUE THREAD

**Issue by joonicks** [pioneerspacesim/pioneer#3454]
14>pch.obj : error LNK2005: "private: static int const Background::Starfield::BG_STAR_MAX" (?BG_STAR_MAX@Starfield@Background@@0HB) already defined in Background.obj
14>pch.obj : error LNK2005: "private: static int const Background::Starfield::BG_STAR_MIN" (?BG_STAR_MIN@Starfield@Background@@0HB) already defined in Background.obj
14>  exception_handler.lib(exception_handler.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
14>pch.obj : error LNK2005: "private: static int const Background::Starfield::BG_STAR_MAX" (?BG_STAR_MAX@Starfield@Background@@0HB) already defined in Background.obj
14>pch.obj : error LNK2005: "private: static int const Background::Starfield::BG_STAR_MIN" (?BG_STAR_MIN@Starfield@Background@@0HB) already defined in Background.obj
14>LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
14>I:\github\pioneer\win32\vc2013Express\..\..\pioneer.exe : fatal error LNK1169: one or more multiply defined symbols found

**Comment by fluffyfreak** [comment]
I've just tried this at work and it built fine with VS2013 Community Edition.

Is this a clean build? If not can you do a rebuild.
Is it the latest version of the codebase and is that a clean version with no changes?

**Comment by joonicks** [comment]
latest commit 416c11f075
@fluffyfreak fluffyfreak authored 6 days ago

freshly downloaded from github, no alterations, unpacked, loaded pioneer.sln and did "build solution".

**Comment by fluffyfreak** [comment]
Ok and you have the `pioneer-thirdparty` too?

**Comment by joonicks** [comment]
oh yes, it unpacks from github as pioneer-thirdparty-master but after renaming it, no issues there. f.ex. it makes the modelcompiler exe no problems. its only pioneer.exe that fails.

**Comment by fluffyfreak** [comment]
Right, I've created a quick branch and PR with what should be a fix that works across all platforms.

@joonicks please give it a test if you are able too and let me know if it builds.

**Comment by joonicks** [comment]
thumbs up. fix works fine. building now in msvc 2013 professional with only warnings, 15/15 successful.

**Comment by fluffyfreak** [comment]
Ok thanks @joonicks :)
