### ISSUE TITLE
System information screen (F7)

### ISSUE THREAD

**Issue by joonicks** [pioneerspacesim/pioneer#3455]
This info screen needs some loving.

Anol (-6, -24, -23) is a lovely blue giant with 11 stable bodies, which bodies that is, can not be found on the system information screen however.
![anolsystem](https://cloud.githubusercontent.com/assets/14345157/9961417/bcc1c48e-5e20-11e5-9eb0-884b3dc1ba8b.jpg)

**Comment by impaktor** [comment]
Double of #2985, and #1052. -> closing.
