### ISSUE TITLE
Orbit fading not working (linux, version 20150927)

### ISSUE THREAD

**Issue by clausimu** [pioneerspacesim/pioneer#3473]
The new orbit fading does not seem to work - at least I can't see a difference to before. This is using the 20150927 version (64bit, linux).

![pioneer](https://cloud.githubusercontent.com/assets/10633178/10224326/5d959110-682b-11e5-8fc8-7985bdac1401.png)

**Comment by impaktor** [comment]
#3460 was merged after the 0927 build, so you'll have to wait a tad bit longer.

**Comment by impaktor** [comment]
@clausimu now, however, there is a new build, which should include the orbit fading, if you're eager to try it out: http://pioneerspacesim.net/download

**Comment by clausimu** [comment]
My bad - I thought I had seen in the changelog that #3460 had been included already. Thanks for pointing out the new build. I will go ahead and test it.

**Comment by impaktor** [comment]
No problems.

The Change log on the web page reflects the state of the source code in our git repo, so in this case only the changelog provided in the actual build artchive file is to be trusted.
