### ISSUE TITLE
hyperspace range is bugged

### ISSUE THREAD

**Issue by joonicks** [pioneerspacesim/pioneer#3477]
![hyperbug](https://cloud.githubusercontent.com/assets/14345157/10269419/8a3d9aba-6ad7-11e5-947a-03e96851aa2e.png)
According to the formula in equipment.lua, my hyperspace range should be
625*7*7/4280 = 7.16ly
its not just a visual bug, it allowed me to make a 8.58ly jump without complaints

**Comment by joonicks** [comment]
issue comments are bugged, I wrote 620 star 7 star 7 / 4280 which comes out 625*7*7/4280
meants 625 times 7 times 7 divided by 4280

**Comment by joonicks** [comment]
found it, ship.totalMass does not include fuel (for deltav calculations I guess), but it should be included in hyperspace calcs. however I dont know if its safe to call Game.player.fuelMassLeft because calls can also be made by tradeships?

**Comment by impaktor** [comment]
This issue is fixed by 3489 -> closing. 
Further discussion on hyperrange is here: http://pioneerspacesim.net/forum/viewtopic.php?f=3&t=355

Thanks for reporting (and for pointing out how to fix it)
