### ISSUE TITLE
Reports of RNG repeatability failing

### ISSUE THREAD

**Issue by fluffyfreak** [pioneerspacesim/pioneer#3482]
Both #3458 and [galaxy-map-problems](http://spacesimcentral.com/ssc/topic/5219-galaxy-map-problems/) show symptoms of the RNG failing to generate the same outcome on subsequent runs of the game.

**Comment by impaktor** [comment]
Fixed by #3485 we hope? We'll see, I guess.

**Comment by impaktor** [comment]
Closing for now, and hoping for the best,
