### ISSUE TITLE
NPC ships shown in wrong location in system orbit view

### ISSUE THREAD

**Issue by clausimu** [pioneerspacesim/pioneer#3509]
A NPC ship is orbiting NN 3378 c 4 (notice ship "HR-0038" close to my ship in frame of NN 3378 c 4):

![lat_lon_11](https://cloud.githubusercontent.com/assets/10633178/10929062/ac47a684-827c-11e5-9736-b0eed98a4d6e.png)

But in the system orbit view this ship is shown orbiting the sun of that system (> 6 AU away from the place where it really is):

![lat_lon_12](https://cloud.githubusercontent.com/assets/10633178/10929082/e8b1ccbc-827c-11e5-8cbd-9078609d710f.png)

I can reproduce this not just for this system, this is just an example. I am spawning a ship in a ~100,000 km orbit around a random planet in the respective system. The spawned ship ends up there correctly - just the display in the system orbit view (F2/F6) is wrong.

**Comment by corundscale** [comment]
Some of the affected ships also seem to be moving abnormally fast in the orbital map, and yes, the infamous sunships seem to be a case of this bug as well.

**Comment by corundscale** [comment]
Shouldn't that also get UI tag?

**Comment by impaktor** [comment]
So seems like the display of the ships is wrong in the orbit view. Maybe @dvolk has thoughts / want to investigate this?

**Comment by Fixer-007** [comment]
I think I've seen this too in newest game too.

**Comment by nozmajner** [comment]
Yeah, it's still in. Hopefully it will be fixed when we get around bringing the orbital map to the new UI.

**Comment by richardpl** [comment]
Should be fixed.
