### ISSUE TITLE
Docking/Launching delay

### ISSUE THREAD

**Issue by corundscale** [pioneerspacesim/pioneer#3511]
There is a noticeable delay - around 4s - during launch and touchdown during which the game appears frozen.

The issue occurs both in downloaded binaries and locally compiled version (using MinGW).

**Comment by nozmajner** [comment]
It's because of the autosave feature. Since the json save format saving takes much more time.
(I usually disable autosave, delete the lua file for it, especially when I'm testing)

**Comment by corundscale** [comment]
Then I guess it should be closed. 
Or is there any plan to move to some more compact format at some point?

**Comment by fluffyfreak** [comment]
No the old system was ditched in favour of the JSON format.
It does need to be faster though it's ridiculously slow.

**Comment by corundscale** [comment]
I was thinking of some sort of compact format that still allows nested tagged data, like TLV encoding.
There is a definite advantage to JSON for debugging reasons, though.

**Comment by impaktor** [comment]
Perhaps an option to disable autosave? Perhaps autosave should even be off by default. 

I think saving in general should only be possible when docked, for "The Final Version Of Pioneer", but for now it is useful to save where-ever to catch bugs.

**Comment by fluffyfreak** [comment]
Enable/Disable autosave option.
Also it just needs optimising, profile, identify slow bits, optimise.

**Comment by clausimu** [comment]
> Enable/Disable autosave option.

+1

> I think saving in general should only be possible when docked

-1

**Comment by impaktor** [comment]
Not a bug.
