### ISSUE TITLE
Failed to set video mode: Could not create GL context

### ISSUE THREAD

**Issue by gunchleoc** [pioneerspacesim/pioneer#3522]
I get this error both on my Windows and my Linux machine - it might be graphics driver related for both. Here's the console output I get in Ubuntu:

GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from pioneer...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/pioneer-20151109-linux64/pioneer 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
ver 20151109 (a86d829) on: Linux

System Name: Linux
Host Name: museum
Release(Kernel) Version: 3.13.0-67-generic
Kernel Build Timestamp: #110-Ubuntu SMP Fri Oct 23 13:24:41 UTC 2015
Machine Arch: x86_64
Domain Name: (none)

SDL Version 2.0.3
Failed to set video mode. (Couldn't find matching GLX visual). Re-trying without multisampling.
Failed to set video mode. (Could not create GL context). Re-trying with 16-bit depth buffer
Failed to set video mode. (Couldn't find matching GLX visual). Re-trying with 16-bit depth buffer and no multisampling
error: Failed to set video mode: Could not create GL context
[Inferior 1 (process 4049) exited with code 01]

**Comment by fluffyfreak** [comment]
Could you post the contents of your `opengl.txt` file which should be inside the folder `~./.pioneer`.

That will tell us if your graphics card can run Pioneer which needs OpenGL 3.1 at least.

**Comment by gunchleoc** [comment]
The logfiles aren't created, all I have in .pioneer is an empty mods directory.

However, since I have the same problem with SuperTuxKart, it's pretty safe to assume that lack of OpenGL 3.1 support is the problem. If you switched to OpenGL 3.1 sometime within the last year or so, I'd say that we can be sure that this is it.

**Comment by impaktor** [comment]
> If you switched to OpenGL 3.1 sometime within the last year or so

20141118 was the last pre-OpenGL3.1 version.

**Comment by gunchleoc** [comment]
It 's been a long time since I last did some testing, so the time frame fits.
