### ISSUE TITLE
Typo: knifes -> knives

### ISSUE THREAD

**Issue by gunchleoc** [pioneerspacesim/pioneer#3530]
The new Amissionox factory in the {system} system ({sectorx}, {sectory}, {sectorz}) is now up and running. It will produce high quality **knifes** capable of cutting through a space boot; however, due to low supply of resources needed for the blades, they have not yet reached full production potential.

Module: Module: NewsEventCommodity
Key: FLAVOUR_23_NEWSBODY

**Comment by impaktor** [comment]
Pushed fix for this in #3382. Thanks for reporting.
