### ISSUE TITLE
WINDOWS 8.1

### ISSUE THREAD

**Issue by ARA7777** [pioneerspacesim/pioneer#3541]
Sir, Madam; I downloaded your Pioneer space sim  program and ran it on my computer windows 8.1 and halfway when loading a warning comes up and says "Microsoft Visual C++ Runtime Library decided to terminate the loading" and does NOT continue loading and stops. So I cannot play the game.
Although my computer has all visual runtime C++ libraries in it!!
This also happened on another computer I tried!!
Thank you for your attention and concern,   yours, ARA

**Comment by fluffyfreak** [comment]
Hi @ARA7777 try to delete all of the `.sgm` files under the `data/models/` folder and it should work then.

There's been a problem with the last few builds that we're trying to fix now.

**Comment by fluffyfreak** [comment]
This is what a lot of people are reporting in @3439 as well.

**Comment by impaktor** [comment]
@ARA7777 please try again, the file has been replaced by @fluffyfreak now.

**Comment by ARA7777** [comment]
Sir, thank you for your kind assistance. Yes the Pioneer's

latest version is working now. Great Space program!

Thank you again.

with Best wishes,  ARA


________________________________

**Comment by ARA7777** [comment]
Sir, thank you for your kind response and assistance and thanks for the

helpful hints. Yes, Pioneer spacesim is working now on Win 8.1

Great Spacesim, fun game. You gentlemen have done brilliant job.

Thanks again for your help.

Best Wishes,  ARA


________________________________

**Comment by fluffyfreak** [comment]
glad that it's working for you, and thankyou for reporting the bug :)
