### ISSUE TITLE
Search and Rescue missions don't show return station

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#3559]
Reported in IRC: In the missions info screen, for the search and rescue #3529 mission, the return station isn't shown, thus for the missions that require returning to station, like 'get the crew and transport them back'-mission, the player has to remember which station it is.

So for that type it aught to show which return station it is, under the F3 missions screen.

ping @clausimu

**Comment by clausimu** [comment]
Okay - I will look into it and update the text!

**Comment by clausimu** [comment]
I just added return station information to the mission screen for the appropriate missions. (See #3570)

**Comment by fluffyfreak** [comment]
Fixed by #3570
