### ISSUE TITLE
format for latitude and longitude display

### ISSUE THREAD

**Issue by gerrygk** [pioneerspacesim/pioneer#3565]
lat and long values are not easily to identify in the display, they should be formatted like
+/- xxx° xx' xx"

**Comment by johnbartholomew** [comment]
How does your suggestion differ from what we already have?

![latlon-display](https://cloud.githubusercontent.com/assets/115749/11763872/d0c24662-a113-11e5-8ef4-feede8fa37d0.png)

**Comment by gerrygk** [comment]
For one-digit numbers (unfortunately not shown in the example above) there should be a "0" in front so the °, ' and " values would be exactly one below the other. Eventually everything right-aligned.
Btw: "Lat", "Long" and the correspondent degree values are overlapping in my case, so it's sometimes difficult for me to see the minus signs.

**Comment by gerrygk** [comment]
Btw #2: Good work regarding the heading value patch!

**Comment by impaktor** [comment]
So pad with a `0` if the numbers are below 10, and pad with a space infron of the numbers if not minus sign, I take it.

**Comment by nozmajner** [comment]
It won't line up properly that way either, unless it's displayed in a monospace font.

**Comment by clausimu** [comment]
Not sure what to do either. I don't think the current font is monospace. Make every subunit (degree, minute, second) an individual overlay text and align them using a grid?

**Comment by nozmajner** [comment]
The flight UI font is not monospace for sure. I don't think it's worth that much hassle, putting it on a grid. 
Not sure if you can set different font for parts of the flight UI.

**Comment by fluffyfreak** [comment]
I'd happy with it as it is now, this seems like it would need a monospace font, and we'd have to pad/expand the text to have leading 0's which might be less legible.
