### ISSUE TITLE
Assertion failed on startup in GeoSphere.cpp, Line 48 (PC)

### ISSUE THREAD

**Issue by marcoturconi** [pioneerspacesim/pioneer#3581]
Hello, I am trying to run the latest version on Pioneer on my pc.
pioneer-20151221-win32.7z

Each time I try to start the game, it begins "simulating the evolution of the universe" then stops working.
It opens a popup window with the following title:

MinGW Runtime Assertion

and the following content:

Assertion failed!

Program: D:\giochi\pioneer\pioneer.exe
File: GeoSphere.cpp, Line 48

Expression: s_patchContext->GetEdgeLen() <= detail_edgeLen[4]

Then I have the three options "Abort", "Retry", "Ignore"... ignore doesn't solve the problem.

**Comment by impaktor** [comment]
If it's the same as: http://pioneerspacesim.net/forum/viewtopic.php?f=3&t=403

Downloading the latest release (30 minutes old) should fix it.

**Comment by marcoturconi** [comment]
I confirm the issue is fixed with the latest release
