### ISSUE TITLE
Search & Rescue fuel deliver missions don't complete

### ISSUE THREAD

**Issue by clausimu** [pioneerspacesim/pioneer#3582]
This has been reported by destroyfx in the dev forum: http://pioneerspacesim.net/forum/viewtopic.php?f=3&t=408.

Apparently after fuel deliver the mission did not complete (was not removed from mission screen?). Also, the ship flew to land at a nearby station after getting fuel delivered to it but was still acting as if it needed more fuel when the player flew close to it.

**Comment by clausimu** [comment]
I was not able to confirm this issue. Mission was removed properly after delivering fuel and the other ship did not react to further advances by the player.

Please send more details if you have seen this!

I will change the script though to make sure ships that have been rescued "move on" and don't stay parked forever at the next station.

**Comment by walterar** [comment]
Something in the serializer does not handle tables well.

**Comment by clausimu** [comment]
Hmm... I have tried saving and re-loading after (apparent) mission completion. It did not "resurrect" the mission either. You are saying it may be a serializer issue non-related to this mission script?

**Comment by walterar** [comment]
For this to work reasonably well in Scout+ G26f, I had to modify, among other things, the code of delivery of fuel. Perhaps you find something in the source code (Scout) that can help improve the version published in the Pioneer engine.

I can not explain more using the Google translator. I prefer communicate with source code. :)

**Comment by clausimu** [comment]
Thank you, walterar, I will take a look at your version.

**Comment by impaktor** [comment]
@clausimu cmdjameson in IRC is experiencing this bug as well. He'll try to hang out in IRC the coming day(s?). An Aussie, so keep time zone in mind. I assume it's bedtime right now, but he'll prefer late European evenings.

**Comment by walterar** [comment]
It is very important to get the savegame to find the solution. I suspect this is a malfunction of the engine Pioneer; particularly in handling equipment.

**Comment by clausimu** [comment]
This is the same bug as #3627 - except for the mission not completing (which has already been solved). We can probably close this.
