### ISSUE TITLE
Is it really a Happy New Year?

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#3587]
@robn We're still at 2015 it seems? I guess you have a script for touching all files (in a non-sexual way), for a "Happy new year"-commit?

Also, while you're at it could you please update the natural doc / API-page?

Thanks!

**Comment by walterar** [comment]
find . -type f -exec  sed  -i  s/'2008-2015 Pioneer Developers'/'2008-2016 Pioneer Developers'/g {} \;
