### ISSUE TITLE
Solar system gas giants look completely wrong

### ISSUE THREAD

**Issue by fluffyfreak** [pioneerspacesim/pioneer#3595]
Taking a look at the Gas Giants in the Solar System and they look absolutely nothing like they should!

At the moment I don't know when this changed but my guess would be with the change to the RNG in #3485 back in November of last year.

I'd be surprised if no-one has noticed them being broken in that long but I'm going to check now.

**Comment by fluffyfreak** [comment]
Yep I can confirm that it was most likely the #3485 change from November last year that broke it.

**Comment by Tichy** [comment]
I noticed that Jupiter was different, but I thought it was an intentional change. Next time I'll be more quick to report.

**Comment by walterar** [comment]
I found Jupiter. The question is, how do we bring it to Sol? :))

![jupiter2](https://cloud.githubusercontent.com/assets/1334989/12695689/ad5d2f4c-c734-11e5-82af-91b202527ddb.png)

**Comment by impaktor** [comment]
@fluffyfreak didn't you merge code to fix this, since then?

**Comment by fluffyfreak** [comment]
Yes, and then I rewrote the gas giant texturing completely anyway :)
