### ISSUE TITLE
Problems with text messages

### ISSUE THREAD

**Issue by walterar** [pioneerspacesim/pioneer#3604]
Example: Try to buy without enough cash.

**Comment by impaktor** [comment]
Maybe @fluffyfreak knows? 

![screenshot-20160123-152733](https://cloud.githubusercontent.com/assets/619390/12530661/02cfbd68-c1e6-11e5-846f-02d61e076ab6.png)

**Comment by fluffyfreak** [comment]
Hmm, probably a bit of over-optimisation.

**Comment by walterar** [comment]
Another problem with the text.

![text-wrong](https://cloud.githubusercontent.com/assets/1334989/12536600/d62a3038-c288-11e5-8cf8-4668773a13a0.png)

**Comment by fluffyfreak** [comment]
How do you get that first screen? I just get a message saying insufficent funds but not as a popup?
That or the screen stops me from buying it at all.

**Comment by walterar** [comment]
Test in Equipment Market

**Comment by fluffyfreak** [comment]
That second problem with the multiline text is completely bizarre. There is no reason that I can fathom for it to be happening, and it goes away after the first jump.

**Comment by walterar** [comment]
The Radar Mapper It looks very ugly too.

**Comment by fluffyfreak** [comment]
ok, new PR :)

**Comment by walterar** [comment]
#3612 fix it, thanks :+1:
