### ISSUE TITLE
Crash on save

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#3606]
1. Jump to an inhabited system.
2. save 

`error: Lua serializer '(null)' tried to serialize an invalid 'SpaceStation' object`

**Comment by walterar** [comment]
Localized problem in SearchRescue.lua
Disables aircontrol_chars in serialize function, and test.
Something inside the aircontrol_chars table is wrong.

PING @clausimu

**Comment by clausimu** [comment]
Hmm - I'll have to take a close look at this. I did not touch the function that populates the aircontrol_chars table for the last update.

**Comment by clausimu** [comment]
Found the problem - it was an old bug in the original script that only surfaced when I fixed things in the updated version. Just submitted a merge request (#3607) that should fix it. My own test was good.
