### ISSUE TITLE
Crash looking console

### ISSUE THREAD

**Issue by walterar** [pioneerspacesim/pioneer#3609]
VertexBufferGL.cpp:261: virtual bool Graphics::OGL::VertexBuffer::Populate(const Graphics::VertexArray&): Assertion `va.GetNumVerts()==m_numVertices' failed.

It happens when in the console screen there is much text.

**Comment by fluffyfreak** [comment]
I think that I know what this is, even what line it's on. Will find some time to fix it tomorrow.

**Comment by fluffyfreak** [comment]
@walterar there's a potential fix for this in #3611 if you could try and recreate the crash. I had no luck repeating it.

**Comment by walterar** [comment]
#3611 fix it :+1:
