### ISSUE TITLE
Suggestion/Request - Surface Bases in Orbit Planning/Orrery?

### ISSUE THREAD

**Issue by Coldwind254** [pioneerspacesim/pioneer#3616]
The new (or new to me - I've been away a little while) ability to plan out orbital manoeuvres in the system orrery screen is an absolutely beautiful piece of work, and makes Pioneer into a whole new kind of simulation for me. Congratulations to those who've worked on this feature. Being able to plot a transfer orbit, or otherwise work out where I'm going to be and when, brings a new layer of gameplay. If I'm honest, most of my recent play time has been spent just going from station to station just to see if I can.

If I had a request - because I'm a spoilt brat and always want something extra - it would be the inclusion of surface bases on the orrery screen. I don't know how viable this is, as I'm not a coder. At the moment, selecting a surface base as a target puts the green reticle at the centre of the planet in the orrery, and there's no way to orientate yourself to the body.

Would it be possible to add surface bases in the orrery so that we can see when our planned orbit is going to hit the planet at the right lat/long? Perhaps add a lat/long grid to better show the orientation of the planet and the current orbit? Or perhaps allow for manual entry of co-ordinates to select a desired landing zone? I note we have planetary co-ordinates now, which is great - but it would be a further improvement if I could just type in the place I wanted to land and see it selected,

(If any of this already exists then please excuse me - I haven't found any settings or buttons that seem to do it.)

Thanks for your consideration - and thank you for the hard work you're putting into this project.

**Comment by impaktor** [comment]
There migh already be an open issue on this, at least in my mind there is, as a grid + lat/long locatios on the bodies is something that has been brought up at various times. And that is wat it comes down to: time.

**Comment by Coldwind254** [comment]
My apologies, then - I did have a glance through but couldn't see anything.

And I do appreciate that Pioneer is an as-and-when deal, so I'm happy to wait. I wasn't sure if it was something already considered or not, is all.

**Comment by fluffyfreak** [comment]
I'm re-opening this as I cannot seem to find any issues that request this info to be displayed.

**Comment by Web-eWorks** [comment]
This feature has been present in the game for a while now, closing!
