### ISSUE TITLE
GL_INVALID_OPERATION on start

### ISSUE THREAD

**Issue by DreadDendy** [pioneerspacesim/pioneer#3619]
Hello. I have got warnings with "GL_INVALID_OPERATION" after starting the game on the Win 10
[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/116462/opengl.txt)
[output.txt](https://github.com/pioneerspacesim/pioneer/files/116463/output.txt)

**Comment by fluffyfreak** [comment]
Are you using Riva Tuner or another overlay tool like MSI Afterburner?

**Comment by DreadDendy** [comment]
Yes.
Thanks, after switching off all works fine.

**Comment by fluffyfreak** [comment]
Ah yes, great. For some reason the way they work is to inject code to display the overlay... but they use old OpenGL code to do those calls and the mode that we request makes those call invalid.

I wish we could detect when these things were being used and popup a warning.

@DreadDendy do you think it would have been helpful to have a warning about this displayed in the `GL_INVALID_OPERATION` warning popup?

**Comment by DreadDendy** [comment]
I think yes.
