### ISSUE TITLE
linux core dumped error when try to show star system view

### ISSUE THREAD

**Issue by sfence** [pioneerspacesim/pioneer#3631]
My Pioneer is builded from git: d3eb57e
Running on linux

Sometimes, it happens to me, that when I try to show information about star system (F7), game failed with core dumped error in terminal output. Without any warning.

http://147.229.208.36/pioneer/SYSTEMVIEWFAIL_LINUX_CORE_DUMPED

**Comment by fluffyfreak** [comment]
That link says access forbidden.

**Comment by sfence** [comment]
i'm sorry. Now file should be aviable.

**Comment by sfence** [comment]
From testing, it looks like it happens when you have selected navigation target like ship and try to show star system view.

**Comment by fluffyfreak** [comment]
Ah good to know, thanks for testing @sfence :)

**Comment by fluffyfreak** [comment]
Yeah I can repeat it now, should have a fix shortly.

**Comment by fluffyfreak** [comment]
There we go, fix PR'd.

**Comment by fluffyfreak** [comment]
This should be fixed by #3632 which has just been merged.
