### ISSUE TITLE
Object methods do not work properly

### ISSUE THREAD

**Issue by walterar** [pioneerspacesim/pioneer#3635]
Specifically, exists=object:exists()  works only when object is a body. Otherwise an error occurs.

For example:
ship="uncreated"
exist=ship:exists()  fails when it should return false

The same goes isa=ship:isa("Ship")

**Comment by impaktor** [comment]
Yes, because #887 was never fixed.

**Comment by fluffyfreak** [comment]
I think you want.

`exist = (ship~=nil)`

The problem here however is that `ship="uncreated"` does exist, it's just that it's a string.
To signify that something does not exist you should be writing something more like:
`ship = nil
exist = (ship~=nil)`

**Comment by impaktor** [comment]
> Yes, because #887 was never fixed.

...assuming by `ship="uncreated"` you mean you have a ship _object_ that has died, and you choose to report it in this condensed form due to, well, ...language.

If you actually try to run the code you written:
```lua
ship="uncreated"
exist=ship:exists()
```
then there is no bug, since a string does not have the exists-method.

**Comment by walterar** [comment]
Ship is a body? Yes or not?

**Comment by walterar** [comment]
```
local Exists = function (ship)
	local exists = false
	if ship:exists() then
		exists = true
	end
	return exists
end
local ShipExists = function (ship)
	if ship then
		ok,val = pcall(Exists, ship)
		if ok then
			return val
		else
			return false
		end
	end
end
```

```
local serialize = function ()
	for ref,mission in pairs(missions) do
		if mission.system_target == Game.system.path
			and not ShipExists(mission.target) then
			mission.target = "uncreated"
		end
	end
	return { ads = ads, missions = missions }
end
```
This is the way I found to avoid #3648

**Comment by fluffyfreak** [comment]
@walterar when you assign a value like "uncreated" to something then it makes it a `string` object, if you want to delete something and be able to test it then make it `nil`.

So seeing if a ship "exists" should look more like:
```
local Exists = function (ship)
    local exists = false
    if (ship~=nil) and ship:exists() then
        exists = true
    end
    return exists
end
```
Although I'm guessing at the exact Lua right now.

Also you should be setting your `mission.target = "uncreated"` to `mission.target = nil` and testing against that.

**Comment by fluffyfreak** [comment]
One problem with that is that assigning `ship="uncreated"` will not be `nil` and still won't have the `exists()` function because strings do not have the `exists()` function.

**Comment by walterar** [comment]
It does not work as you say.

**Comment by fluffyfreak** [comment]
No it does work, you just need to stop assigning strings like "uncreated" to variables.

Look, the `exists` function is for Pioneer objects ONLY, but when you assign a string like "uncreated" to a variable then that is a lua object and it does not have the function `exists`.

If you did:
```
ship = nil
-- do some other things, maybe assign a LuaShip to ship
exist = (ship~=nil) and ship:exists()
```

Then that would work, because then you would be able to test against the `nil` value AND if there was a valid Pioneer `LuaShip` object there then it would work because it would have the `exists` function on it.

**Comment by walterar** [comment]
The first thing I did was what you say, but it did not work. It is not so easy. The problem is the serializer.

**Comment by walterar** [comment]
http://eatenbyagrue.org/f/pioneer/codedoc/files/LuaObject-cpp.html#Object.exists

**Comment by fluffyfreak** [comment]
Yes, but that only applies to *valid* "Engine" objects, things like ships etc, and they cannot be `nil`.
A string is a "lua" object, and it is not `nil`, but it is not an "Engine" object.

The `exists` functions doesn't check to see if the Lua object is valid, it reaches into the "Engine" and checks that the C++ object is valid.

**Comment by walterar** [comment]
Ok, I see you do not understand what happens, good luck with this.

**Comment by impaktor** [comment]
> Ship is a body? Yes or not?

I suspect we are all missunderstanding each other.

In your first post you write:

ship="uncreated"

_That_ is a _string_, and does not have the `exists()` method.

However:

ship=Game.player

is an object, and should have an `:exists` method that works even after the ship is blown up. I assume you know this, and therefore I assume that what you mean by ship="uncreated" is that you have a ship object, that is not the string "uncreated", but rather you're trying to tell us that the ship blew up, and was thus, in "walterar-English" :wink: "uncreated".

**Comment by robn** [comment]
Put another way: post _real_ code. Something that can be tested to reproduce the issue.

**Comment by walterar** [comment]
Many times it is necessary to check whether a variable contains what is supposed to contain, especially after recalling a saved game.
Thus, the variable "ship" no "is" a ship. As a variable "andy" and "robn" not exactly "is" andy or robn.
After retrieving a saved game, "ship" may contain just trash, or it might ship = "ioewu49823y2gefhb__?"
In this case:
if ship and ship:exists() then ... does not work, it will fail.

**Comment by Web-eWorks** [comment]
Not sure why this one was left open, but the `exists` method *is* properly bound to all engine-created Objects. You can test `type(ship) == 'userdata' and ship.exists` to query whether the `ship` object is in fact a valid userdata and it has an `exists` method, but given the date of this issue I doubt it's still a problem in need of solution.
