### ISSUE TITLE
Can't tell what equipments are compatible before buying a ship

### ISSUE THREAD

**Issue by Echoes91** [pioneerspacesim/pioneer#3637]
I noticed it when i tried (just for testing) to buy a lunar shuttle, it looked like a good swap until it came out that it couldn't mount a hyperdrive.
Since ship trading is very unforgiving (with such prices and values halved immediately it seems to ask you to buy a not existing premium account), for a "serious" career  playing it would be nice to see these informations on ship descriptions

**Comment by Web-eWorks** [comment]
This has been rectified with the PiGui-based Ship Market.
