### ISSUE TITLE
Current OSX build corrupt

### ISSUE THREAD

**Issue by fluffyfreak** [pioneerspacesim/pioneer#3638]
@salborrelli it seems that the current `pioneer-20160212-osx.zip` build is corrupt or uploaded as the wrong type. This is probably my fault and I might have done something wrong with the file you gave me.

Could you do a new build from the current master and upload it with the `pioneer-YYYYMMDD-osx` format as a zip file please?

This was originally reported here: http://spacesimcentral.com/ssc/topic/5447-mac-download-broken/#entry57198

**Comment by salborrelli** [comment]
@fluffyfreak Hi Andrew, the new build is ready, you can download it here:

https://drive.google.com/file/d/0B3YT4wkIA2jja2hYZmc3SmU1ZlE/view?usp=sharing

**Comment by fluffyfreak** [comment]
Thanks @salborrelli I'll try to test & upload it tonight or tomorrow.

**Comment by fluffyfreak** [comment]
My work machine says that the zip file is valid and contents are not corrupted like the last one. Can't upload to sourceforge from here sadly.

**Comment by fluffyfreak** [comment]
Ok latest version was uploaded and old, corrupt, version deleted :)
