### ISSUE TITLE
Some ship have strange black textures

### ISSUE THREAD

**Issue by Tichy** [pioneerspacesim/pioneer#3656]
See screenshots. These are the ones that I noticed.
This issue appears when the ships are nearer. At other distances, they look ok.

![2016-03-23-170826_1920x1200_scrot](https://cloud.githubusercontent.com/assets/2348771/13992244/a8372cb4-f11b-11e5-8029-cdcb3a1c2fb6.png)
![2016-03-23-170845_1920x1200_scrot](https://cloud.githubusercontent.com/assets/2348771/13992245/a83e28e8-f11b-11e5-99e1-fc3dde37ec34.png)
![2016-03-23-171119_1920x1200_scrot](https://cloud.githubusercontent.com/assets/2348771/13992246/a84685b0-f11b-11e5-95a9-aaa7b173a1ef.png)

I'll add some informations

My opengl.txt
https://gist.github.com/Tichy/6ecbe05b46511798619f

My output.txt
https://gist.github.com/Tichy/b755b6465a63783ac136

`glxinfo | grep OpenGL`

OpenGL vendor string: X.Org
OpenGL renderer string: Gallium 0.4 on AMD JUNIPER (DRM 2.43.0, LLVM 3.7.1)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.1.2
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 11.1.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 11.1.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

config.ini
https://gist.github.com/Tichy/051f02d64ae40cfec73a

**Comment by fluffyfreak** [comment]
I don't think that's so much a bug as it is a feature of the new colour picking algorithm.
Thats sounds like a cop-out doesn't it :D

I will need to double check it though to make sure that is what's happening so don't close this issue yet.

**Comment by walterar** [comment]
Definitely not a mistake but a new feature. Many more colors for ships. And now, black is black. ;)
It is nice. :+1:

**Comment by Tichy** [comment]
I need to check again, but it looked like an issue also because the that black was so prominent only when the ships were closer.

**Comment by impaktor** [comment]
Should black have some kind of visible texture?

**Comment by impaktor** [comment]
@Tichy If you agree with the other's that isn't a bug, then please go ahead and close this.

**Comment by Tichy** [comment]
I need to check if that black textures appears only when the ship is closest, and not at other distances, as I noticed when I opened this issue.

I'll check that when I'll get back from work. This and my other opened issues.

**Comment by Tichy** [comment]
It looks ok to me
