### ISSUE TITLE
Can't play in fullscreen

### ISSUE THREAD

**Issue by Tichy** [pioneerspacesim/pioneer#3657]
When starting pioneer it goes fullscreen during the loading screen, but then it returns to window.

Using linux with dwm as window manager and no compositing.

I'll add some informations

My opengl.txt
https://gist.github.com/Tichy/6ecbe05b46511798619f

My output.txt
https://gist.github.com/Tichy/b755b6465a63783ac136

`glxinfo | grep OpenGL`

OpenGL vendor string: X.Org
OpenGL renderer string: Gallium 0.4 on AMD JUNIPER (DRM 2.43.0, LLVM 3.7.1)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.1.2
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 11.1.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 11.1.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:

config.ini
https://gist.github.com/Tichy/051f02d64ae40cfec73a

**Comment by Tichy** [comment]
This issue seems to be gone. Now it stays in fullscreen even after the loading screen.

**Comment by impaktor** [comment]
thanks for (re-)checking.
