### ISSUE TITLE
KUbuntu/Mint/Ubuntu(?) missing libcurl.so.4

### ISSUE THREAD

**Issue by fluffyfreak** [pioneerspacesim/pioneer#3658]
It looks like some Linux distro's are missing the `libcurl.so.4` that we need to run Pioneer.

This was reported on the forum [within another report](http://spacesimcentral.com/ssc/topic/5456-pioneer-does-not-run-under-kubuntu-1404/?p=57462).

**Comment by robn** [comment]
I'll see what I can do. Probably need to upgrade the build roots again or something.

As usual, the distribution story on Linux is a joke. Even if we are working on Ubuntu, we're probably not working on other distros. This is always going to be whack-a-mole until someone works out a unified package manager or something. You know, Steam.

**Comment by Tichy** [comment]
In Arch I have a similar issue. I have libcurl 4, but I get that error if I try to load pioneer from the precompiled package.

`/usr/lib/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by ./pioneer)`

**Comment by laarmen** [comment]
Wait. Whaaaaaaaaaat? Do we depend on libcurl3 or 4?

For Arch, there is somewhere a libcurl-compat (or similar name) for that
kind of issues.

**Comment by impaktor** [comment]
Pioneer no longer reqires libcurl.
