### ISSUE TITLE
ship hyperdrive bug?

### ISSUE THREAD

**Issue by juri74** [pioneerspacesim/pioneer#3665]
i'm new on pioneer but played a lot with frontier.
when i buy (or trade for)a new ship it is fitted with a hyperdrive, unable to jump even with 100% fuel!
it report 0.00 ly in info page.

**Comment by nozmajner** [comment]
Depends on the default drive of the ship. The Xylophis and the Police Kanara won't have any for example. (And the Police Kanara shouldn't be available at all to buy, not to mention for 1$)

**Comment by fluffyfreak** [comment]
@juri74 can you tell us a bit more, what kind of ship, and what kind of fuel do you have?
If you start on Earth or Epsilon Eridani, can you buy some hydrogen fuel, and target another system?

**Comment by juri74** [comment]
hello, thanks for your replies, i can't replicate the bug, yesterday i was able to replicate it with some affordable space ships, i do not remember the name since i'm really a new user, but today, after power cycle of my desktop pc, it work!! i'm puzzled, if it will show again i will write down all info possible :(

**Comment by nozmajner** [comment]
It might have been the Kanara, which was available for 1$ because I did a mistake in it's definition file. That will be fixed in the next build.

**Comment by impaktor** [comment]
I don't think there is a bug here (anymore). If it happens again, make sure to check what ship it is, that you really have a hyperdirve fitted, and how much hydrogen (or military fuel if that kind of drive) you have.

Thanks for reporting, and fly safe.

Closing for now.
