### ISSUE TITLE
Missiles produce a lot of smoke

### ISSUE THREAD

**Issue by walterar** [pioneerspacesim/pioneer#3681]
@fluffyfreak  Help! :) 
![smokemissile1](https://cloud.githubusercontent.com/assets/1334989/14443891/7ce694d0-0018-11e6-96fa-97eeb4327238.png)
![smokemissile2](https://cloud.githubusercontent.com/assets/1334989/14443893/83fd8422-0018-11e6-9050-fd8cba39a74f.png)
![smokemissile3](https://cloud.githubusercontent.com/assets/1334989/14443895/89e74e2c-0018-11e6-97a3-3352424fd39c.png)

Cof! cof!
![smokemissile4](https://cloud.githubusercontent.com/assets/1334989/14443929/b6f61d6c-0018-11e6-9b19-65736b9e1913.png)

**Comment by laarmen** [comment]
Yeah, I guess in vacuum smoke should expand and disappear pretty quickly.

**Comment by walterar** [comment]
Everything points to #3670 (and #3667?)

**Comment by walterar** [comment]
With #3667 works well. The great smoker is #3670

**Comment by fluffyfreak** [comment]
I've been away, gimme a couple of days to catchup.

**Comment by laarmen** [comment]
Here, have 3!

**Comment by fluffyfreak** [comment]
Thanks! :P

This is probably caused by the changes to object size calculation. In the old system it decided how big each quad should be, which was then built and rendered. With billboards however you have to tell it the final size in pixels that it will occupy onscreen.

I probably just didn't get that maths right though I did test firing missiles at stations and made sure it was comparable. Oh well.

**Comment by walterar** [comment]
If the smoke cloud of missile seems too big, wait till you see the explosions of large ships. The size has very much increased.

**Comment by fluffyfreak** [comment]
I think I have an idea of how to tackle this, my brains a bit too tired to get it correct just now but I have it partially working.

I'll try a bit more tomorrow.

**Comment by walterar** [comment]
@fluffyfreak Some precisions of what I have observed:

The dimensions of the explosion are well on normal ships. I like it better now. Only in large statics it seems excessive.

The smoke effect on missile becomes a much more interesting effect with a simple change in these values, try it.

```
 	switch (m_type) {
 		case TYPE_EXPLOSION:
			if (m_age > 3.2) m_type = TYPE_NONE;
 			break;
 		case TYPE_DAMAGE:
			if (m_age > 2.0) m_type = TYPE_NONE;
 			break;
 		case TYPE_SMOKE:
-			if (m_age > 8.0)
+			if (m_age > 0.5)
 				m_type = TYPE_NONE;
 			break;

```
The damage effect requires some adjustment but looks good.

I hope you have time to find a better solution before month end. But if do not achieve it, there are no serious problems because Pioneer vanilla does not have many scenes of combat yet.

**Comment by fluffyfreak** [comment]
This should be much improved with the #3695 patch.
