### ISSUE TITLE
Autopilot:  Lock to ecliptic

### ISSUE THREAD

**Issue by tlhonmey** [pioneerspacesim/pioneer#3682]
Finding reference points in space with the "Eyeball Mk I" is somewhat difficult under the best of circumstances.  An autopilot setting or visual navigational aid to orient the ship with the ecliptic plane, while still displaying one's attitude with respect to the body one is orbiting would be handy for being able to translate the current planet layout in the system map into a meaningful interpretation of landmarks (spacemarks?) by effectively reducing the navigation puzzle from three dimensions to two.

Not that one can't figure this out with some careful observation and multiple consultations with the map, but making a human pilot do that when the autopilot obviously already has the information kind of messes with my willing suspension of disbelief...

Either a HUD mode that marks the ecliptic, or an autopilot setting to lock "up" to the galactic north would suffice for these purposes.

**Comment by impaktor** [comment]
Myabe something @dvolk might be interested in? (I'm not sure I've understood it exactly.)

**Comment by nozmajner** [comment]
What's the point of galactic north when you are flying (spaceing?)?

**Comment by tlhonmey** [comment]
Galactic north would be less useful than system north due to the fact that systems could, potentially, be oriented differently.  However, the concept is useful when trying to manually fly between planets.

"North" in this case refers to the spin of the system.  Just like north on a planet is toward one particular end of its axis, the entire system spins around a similar axis, and the vast majority of satellites will be oriented in a plane perpendicular to that axes.  If you're going to try manually flying between planets with something other than a maximum power flight, you need to know where you are in relation to that plane in order to get the orbits lined up.  It also narrows down the amount of area you have to search to even find the objects you're looking for.

After posting the request, I realised I could sort of do it manually by using the brightest part of the Milky Way as a reference, but that only actually works if you're in a system that's oriented the same way as Sol, and it doesn't tell you which way things are orbiting, so it's easy to go the wrong direction and smack into something.
