### ISSUE TITLE
Cannot build OSX

### ISSUE THREAD

**Issue by fluffyfreak** [pioneerspacesim/pioneer#3685]
Calling @salborrelli or @eloquentmess to help me out on this one.

I'm trying to build the latest code but I'm being stymied by nonsense errors and I cannot figure out what's wrong with the XCode build.

# new files:
First of all there are (at least) two new files that need adding to the XCode project in `src\graphics\opengl\BillboardMaterial.h/cpp`.
I've done that but they fail to compile with an error saying: `"vtable for Graphics::OGL::BillboardMaterial()", referenced from: 
Graphics::OGL::BillboardMaterial::BillboardMaterial() in RendererGL.o
NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.`

Which is complete bloody nonsense :/

Any help would be appreciated guys.

**Comment by fluffyfreak** [comment]
Of note, it still builds and runs fine when built in the terminal the old auto-tools way.

**Comment by salborrelli** [comment]
@fluffyfreak no problems I've just created PR #3686 to fix this.

**Comment by fluffyfreak** [comment]
Fantastic, thanks @salborrelli :)
