### ISSUE TITLE
Crash on jettisoning cargo

### ISSUE THREAD

**Issue by icarito** [pioneerspacesim/pioneer#3688]
error: [string "[T] @modules/CrimeTracking/CrimeTracking.lua"]:74: couldn't find constant with name 'SEMI_FINISHED_PRODUCTS' in namespace 'CommodityType

stack traceback:
	[C]: in function 'IsCommodityLegal'
	[string "[T] @modules/CrimeTracking/CrimeTracking.lua"]:74: in function 'cb'
	[string "[T] @libs/Event.lua"]:34: in function '?'
	[string "[T] @libs/Event.lua"]:185: in function <[string "[T] @libs/Event.lua"]:180>

**Comment by laarmen** [comment]
Hi,

Thanks for the report!
@impaktor, that's one of yours isn't it?

**Comment by impaktor** [comment]
@laarmen Depends. Seems like the error is that checking the legal state on custom cargo is not well defined? Or what is the intended behaviour of `LuaStarSystem.cpp:l_starsystem_is_commodity_legal` if the cargo is custom?

**Comment by laarmen** [comment]
This function was written before my time. The whole legal commodity thing has been a pain in my rear, but I didn't dare touch it at the time of #1719 because people were talking about refactoring sysgen and all that.

**Comment by laarmen** [comment]
(so basically its behaviour is undefined for custom cargo)

**Comment by impaktor** [comment]
I guess the logical thing would be to default to "not illegal / legal" for custom cargo?

**Comment by laarmen** [comment]
That'd be a patch, yes, but the more fundamental problem remains: we need to make this moddable!
