### ISSUE TITLE
Save and land bug - game show error and exit

### ISSUE THREAD

**Issue by sfence** [pioneerspacesim/pioneer#3694]
Hello.

I have a mission, from Pluto research base to Sirius. But when I do hyperjump to Sirius system and try to land, game says there is a problem with serializing 'Ship' object. I tried to jump into Sirius system and save game, but same error happend.
I run Pioneer under Linux, from top of git reposity. Last git fetch and merge - today morning (7th May).

My save from Pluto Research base: http://147.229.208.36/pioneer/SIRIUS_LAND_SAVE_BUG

I tried both of target mission bases. No one works.

**Comment by walterar** [comment]
@sfence Do you feel able to replace or modify this function in SearchRescue.lua?
This will solve your problem:

`local serialize = function ()
  for i,ship in pairs(discarded_ships) do
    if not ship or not ship:exists() then
      table.remove(discarded_ships,i)
    end
  end
  return {ads              = ads,
          missions         = missions,
          aircontrol_chars = aircontrol_chars,
          discarded_ships  = discarded_ships}
end
`

**Comment by sfence** [comment]
Fix it primary in main source branch of the game. :)
Because of testing, I want to keep my pioneer source same like source from main branch. :)

**Comment by laarmen** [comment]
Well, you can always modify the file, and use git reset --hard HEAD to go
back to the pristine state.

**Comment by impaktor** [comment]
I was going to suggest `git checkout path/to/changed/file.lua` which is much less brütal. (Usually, `reset --hard` is only for the brave and the bold.)

**Comment by laarmen** [comment]
Well, he/she did say they wanted to keep the experience completely vanilla.
Besides, aren't we all brave and bald^Wbold?

**Comment by clausimu** [comment]
Is this still a problem? I can't replicate it with the current git version (7/25/16). I thought I had solved it and submitted a patch to the module - but so much has happened in "real life" in the past two months that I lost track. Please let me know if I need to look further into it.

**Comment by walterar** [comment]
@clausimu Hello!
This problem is still present while the patch I have suggested are not merged. This is necessary to eliminate the possibility that discarded_ships contain "dead" ships.

**Comment by clausimu** [comment]
@walterar - good catch! Now I understand why you suggested the patch. Logically, I would rather put the fix into the "onShipDestroyed" function though. Any objections to that?

    local onShipDestroyed = function (ship, attacker)

        ...other stuff here.....

        for i, discarded_ship in pairs(discarded_ships) do
	    if ship == discarded_ship then table.remove(discarded_ships,i) end
        end
    end

**Comment by walterar** [comment]
I prefer to filter in serializer, which is where the error occurs. A better solution would be to dispense with discarded_ships ;)

**Comment by walterar** [comment]
@clausimu  It would be good to start by standardizing the style, so that everyone would be easier to understand the code. I suggest see "Tabs & spacing" in http://pioneerwiki.com/wiki/Code_style

**Comment by clausimu** [comment]
I'll go over the code to work on style. I think I need to change some emacs settings.

As for getting rid of discarded_ships - I thought it would be a nice way of getting rid of unwanted ships gracefully (fly them to nearest base and then hyp away to random inhabited system later). I don't quite understand how you do it in your version. I see that you fly the mission.target to the nearest base, but what happens with it then? You explode it? I tried a fuel delivery mission in scout+ and was flown to low orbit after completion, away from the target.

**Comment by walterar** [comment]
In Scout+ the ships may explode (due to the poor quality of fuel provided), crashing into the planet (the pilot runs out of fuel tends to be somewhat awkward), jump to hyperspace or mysteriously disappear. :)
The ships abandoned self-destruct in an explosion.

**Comment by clausimu** [comment]
@walterar - I have put in a patch (#3770). I decided to keep the "discarded_ships" version of giving former mission targets a graceful exit for now. That also meant I have to filter during "onShipDestroyed" rather than during serialization because it is really a weak design on my part to keep references to destroyed ships.

Thank you for finding the solution to this bug!! I really appreciate your input!

**Comment by walterar** [comment]
@clausimu There are cases where onShipDestroyed not work, but for now there are no problems in vanilla. Good job.

**Comment by clausimu** [comment]
I guess we can close this now.
