### ISSUE TITLE
Refuel mission - Unresponsive ship

### ISSUE THREAD

**Issue by sfence** [pioneerspacesim/pioneer#3700]
http://147.229.208.36/pioneer/UNRESPONSIVE

No refuel is possible because of ship is unresponsive.
Problem should happend after load and continue in playing.
For me it happens on linux. (I have pionner version from git, actualized a few minutes ago).

**Comment by walterar** [comment]
You have come too late, the due date expired. No signs of life on the ship; all have died because of your negligence. It should be severely punished for this. ;)

**Comment by sfence** [comment]
Ok. I missed it. Sorry. That it is correct behavior.

**Comment by walterar** [comment]
Too happened to me. :)

**Comment by impaktor** [comment]
Sounds like it wasn't a bug then.
