### ISSUE TITLE
CTD when missile target hyperjumps

### ISSUE THREAD

**Issue by walterar** [pioneerspacesim/pioneer#3704]
If you shoot a missile at a ship and this ship jumps to hyperspace before the missile impact the target, a CTD occurs.

**Comment by laarmen** [comment]
(edited the title to better represent the issue at hand)

Thanks for the report!

**Comment by walterar** [comment]
This problem is long-standing. No relation to any recent change.

**Comment by laarmen** [comment]
Oh, good to know.
I'm fighting with VS to update my master branch, and I'll look into it.

**Comment by walterar** [comment]
#3705 solves this.

**Comment by walterar** [comment]
#3705 solves this, too. :)
