### ISSUE TITLE
Unable to compress time or hyperjump after hyperjump

### ISSUE THREAD

**Issue by Marcurling** [pioneerspacesim/pioneer#3720]
Alert says 'Laser fire detected' but I didn't fired or been fired.
I see no ship/objects on scanner.
I'm running  pioneer-20160610-win32 on Windows 7/64 with a nVidia GT430
[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/314786/opengl.txt)

**Comment by Marcurling** [comment]
Ctrl-F8 Esc Esc 'Exit this game' Continue solved it ;)

**Comment by walterar** [comment]
Old known bug. #3345
