### ISSUE TITLE
Bad text when asking hyperdrive servicer without having a hyperdrive

### ISSUE THREAD

**Issue by Wuzzy2** [pioneerspacesim/pioneer#3722]
Hi!
I noticed the text is stupid when you ask a hyperdrive servicer without having a hyperdrive on your ship.
They say that they want to service my None for $0.00. xD

I suggest to use just a new string in case the player has no hyperdrive, that would be the simplest fix. The text should say that they are a servicing company, how they are called, what guarantee they offer and that the player can't be a customer right now because no hyperdrive is installed. Perhaps with a custom flavor for each of the different servicing companies.

**Comment by impaktor** [comment]
This is a simple one to fix.
