### ISSUE TITLE
Use system language by default

### ISSUE THREAD

**Issue by Wuzzy2** [pioneerspacesim/pioneer#3723]
Suggestion:

Add a new item in the list of languages, called “System language”. If this one is selected, the game uses the language as defined by the operating system (to be detected with environment variables, etc.)

The system language should be used by default.

The the game was unable to detect the system language, use English.

**Comment by impaktor** [comment]
In linux I guess it's a question of reading in `$LANG` or `locale`, but I think we have deactivated running shell commands from lua in pioneer, so it would have to be done from C-side. How is locale handled on OSX and Windoze?

**Comment by fluffyfreak** [comment]
As usual, it's a bit complicated on Windows, http://stackoverflow.com/questions/1322578/win32-api-for-getting-the-languagelocalization-info-of-the-os

**Comment by laarmen** [comment]
We can just ignore windows at first, though.

Le sam. 25 juin 2016 09:51, Andrew Copland <notifications@github.com> a
écrit :

**Comment by impaktor** [comment]
I suspect this feature would be nices for those who are so bad at english they don't even know how to navigate the Language-menu. I suspect those people would be on Windows to begin with. (GNU/Linux users know how to fix stuff, and read tutorials, manuals, documentation, most of which is in English)

**Comment by fluffyfreak** [comment]
I can add it for Windows easily enough. If either of you want to do the Linux part and interface then I can just plug in the Windows part afterwards.

We'll fight over who gets to do OSX afterwards ;)

**Comment by impaktor** [comment]
Implementing it would be at least one or several hours of head-scratching for me, which I don't intend to invest to save new players a few seconds of choosing the language.

**Comment by nozmajner** [comment]
Wouldn't it be easier to bring up a question dialog about language on the first start of the game?

**Comment by fluffyfreak** [comment]
@laarmen you interested?

@nozmajner maybe, but it's good to have a default selected that matches the current system language too.

**Comment by impaktor** [comment]
I found some pack of small png-flags a while back and had an idea that it could go with languages. Assuming one can match flags/countries with languages. 

Anyway, just throwing that idea out there in case anyone feels devoted to perfecting language selection.

Also, @nozmajner's idea is not bad at all, I like it's simplicity, and it would "just work". E.g. for reading $LANG for GNU/Linux, there's an enormous plethora of different languages, flavours, char-sets, codings, layouts, etc. So you would have to handle that some way. And then support it. Just a greeting screen for first time circumnavigates the problem. Also, sooner or later, we will need a variable that holds if the player is "new", showing extra help, extra info, tutorial mode, etc.
