### ISSUE TITLE
Long commodity names may use bad line wrap in econmy analysis

### ISSUE THREAD

**Issue by Wuzzy2** [pioneerspacesim/pioneer#3724]
If you go into system information, econmy analysis and use a language with long words, some of the commodities in the economy analysys may use an automatic line wrap. This is good, but the next commodiy name is written over the previous text.

Example can be seen in German for “Chemische Kampfstoffe” (bad translation of “Nerve Gas”).
I semi-fixed it for now by changing the translation to “Nervengas”, but this does not really solve the problem, I suppose other languages may not so easy to fix.

The real fix would be to make sure long commodity names work properly in this interface so translators don't have to worry about this. :-)

**Comment by impaktor** [comment]
I don't think we plan to maintain this OldUI much longer.
