### ISSUE TITLE
Make selected item in lists more visible

### ISSUE THREAD

**Issue by Tichy** [pioneerspacesim/pioneer#3726]
When browsing long lists, like the ship market, it's easy to loose track of the item that's selected, expecially when scrolling the view.

![screenshot-20160624-173733](https://cloud.githubusercontent.com/assets/2348771/16342655/a17a320c-3a33-11e6-8065-740636ceff06.png)
Which of the two Nerodia is selected?

Maybe it would be better if the selected item is kept highlighted:
![screenshot-20160624-173727](https://cloud.githubusercontent.com/assets/2348771/16342712/d933c62c-3a33-11e6-8e3a-13732b5c3bbe.png)

**Comment by impaktor** [comment]
@nozmajner thoughts?

**Comment by fluffyfreak** [comment]
I think it would be an improvement

**Comment by nozmajner** [comment]
I had almost the same color for highlight in my mockups actually :)
