### ISSUE TITLE
Cryptic error message when attempting to continue game when game has never been played

### ISSUE THREAD

**Issue by Wuzzy2** [pioneerspacesim/pioneer#3727]
How to repdroduce:

* Start Pioneer the first time
* Click on “Continue game”
* You see a cryptic error message complaining about a missing save file called “_exit”

I suggest to just disable or remove the “Continue game” button if _exit is not there.

**Comment by impaktor** [comment]
It's not so cryptic, since you actually have a "_exit" save game if you've played the game before. A new player pressing "continue game" will probably understand that it will not work, and that it is referencing a auto-saved game.

**Comment by walterar** [comment]
Maybe you should change to "Just what do you think you're doing, Dave?" :)

**Comment by impaktor** [comment]
yeah, that's one option. :)

I'm willing to close this, but thanks for reporting.

**Comment by fluffyfreak** [comment]
I think this one is worth a quick look over so I'll do it.

**Comment by impaktor** [comment]
I started looking at it last night, and concluded that the code is very small and minimalistic, so I don't want to bloat it by adding a language module just for some not-really-needed "No auto save exists" message.

As for shading the continue button, that's a valid solution, but I didn't look into it. It takes a lot of will power for me to start looking at UI stuff.

**Comment by fluffyfreak** [comment]
Yeah the UI is... not a lot of fun :/

**Comment by fluffyfreak** [comment]
PR up for review, bit hacky
