### ISSUE TITLE
Mission panel can contain multiple entries for job-seekers, all with the same persons

### ISSUE THREAD

**Issue by Wuzzy2** [pioneerspacesim/pioneer#3729]
Sometimes I saw multiple entries for people seeking jobs.
But the multiple entries are pretty pointless since clicking each of them reveals the exact same persons to me.

So I think there should only one job-seekers entry at most in the missions panel.

**Comment by impaktor** [comment]
What do you mean?

That person "X" is looking for job multiple times in the crew for hire advert on the BBS? Same name, same face, same pay?

I know this module has some bug along those lines, I think it's been reported before.

**Comment by Wuzzy2** [comment]
Yes.

**Comment by impaktor** [comment]
I stronly suspect this issue is a double then, but I don't have time now to find it's twin.

**Comment by impaktor** [comment]
OK with #3733 we definitly have a duplicate, it not "tripplicate". -> closing.
