### ISSUE TITLE
Black markets have identical prices and goods on same station

### ISSUE THREAD

**Issue by Wuzzy2** [pioneerspacesim/pioneer#3730]
If there are multiple black markets on a station (in the mission panel), they always have the exact same prices, there's no competition at all, apparently. They also always agree in the kind of stuff they offer (But why would they? It seems boring that you can almost always assume that a black market has a *full* set of illegal goods, not just, let's say, one or two).
They only differ in the amount of stuff available.

I think this should be changed to make it more interesting.

**Comment by impaktor** [comment]
No, there is only one _real_ black market. The other is fake, by Police.
