### ISSUE TITLE
Add flavor texts for black markets

### ISSUE THREAD

**Issue by Wuzzy2** [pioneerspacesim/pioneer#3732]
It would be nice to add a few flavor texts for the black markets, just for fun.
The texts could more or less allude to the fact that they're illegal without directly mentioning it.
Also, with the typical bullshit bingo we all know and love from advertising. xD

I suggest the following texts (where “Black Market Inc.” ( ;-) ) should be replaced with the real name, of course).

* Welcome to Black Market Inc., your trader of inconventional goods.
* We at Black Market Inc. trade the most unusual goods.
* Welcome to Black Market Inc., the market without restrictions.
* Black Market Inc.: The only really free market.
* Trade top-quality goods at Black Market Inc.
* Black Market Inc. fills the gap of the conventional market. We buy and sell unusual goods.
* Trade premium products at premium prices!
* Black Market Inc.: Because sometimes, you need more.
* Welcome to our free marketplace.
* Welcome to our little marketplace, where people come to trade what others don't dare to trade.
* Black Market Inc. takes the principle of the free market very serious.
* Buy and sell without restrictions at Black Market Inc.
* Do you feel the conventional market is lacking? Then you have come to the right place at Black Market Inc.!
* Black Market Inc. is your trustworthy market for special commodities.
* Welcome to Black Market Inc.! We buy and sell special commodities.

Feel free to come up with your own silly texts. ;-)

**Comment by impaktor** [comment]
If you're looking to get this into the development-side of the game, it sounds like a good project to start, as it is all in Lua, so you don't need to compile anything, and it just builds on the same pattern that is already in-place. Just edit the module/GoodsTrader.lua.
