### ISSUE TITLE
Duplicate entries in BBS

### ISSUE THREAD

**Issue by Wuzzy2** [pioneerspacesim/pioneer#3733]
In the BBS I sometimes see entries with the identical titles and content. It's not a serious bug, but slightly annoying because it clutters the mission screen.

Examples:
- News entries with the identical news
- Hyperdrive servicing company (same company)
- Job seekers (identical persons) (#3729)

**Comment by impaktor** [comment]
Is this reproducible? Is it in any way related with restoring from a saved game?

**Comment by Wuzzy2** [comment]
I don't know. It just happens sometimes but I don't know when exactly. That's all I know. :-(
If you want, I can try to send a savegame the next time this happens to me.

**Comment by Wuzzy2** [comment]
OK, here's a zipped savefile where the player is docked at a station with two identical fuel cooperatives in the mission panel.

[Wuzzy Wuzzard.zip](https://github.com/pioneerspacesim/pioneer/files/333101/Wuzzy.Wuzzard.zip)

**Comment by impaktor** [comment]
Are there still duplicates if you load that save-game?

**Comment by Wuzzy2** [comment]
Yes.

**Comment by walterar** [comment]
This is a nightmare. The problem seems to be in the load and not in the save.

Often do not load OK the saved and you have to try to load several times until it succeeds without problem.

The same happens when you start a saved game with red alert. ( #3345 )

**Comment by walterar** [comment]
In this case it is clear that the missions tables do break in load and the system creates new ones.

**Comment by walterar** [comment]
This is an old bug, is unrelated to recent changes in serializer.

There a way to reproduce this, sometimes.

1) Start on Earth
2) Save game.
2) takes off and crashes into the planet.
3) Click RIP
4) Without totally out, load the saved game.

Maybe many rare things occur to see.

**Comment by walterar** [comment]
Another way that reproduces this is modifying the text of a language file (missions and others) and reload the saved game. But in this case it is tolerable.

**Comment by walterar** [comment]
@fluffyfreak  It seems that the video cache is related to this problem. I can retrieve a saved game corrupted removing ~/.nv in Linux

**Comment by fluffyfreak** [comment]
That's interesting and unexpected!
Also I didn't know that nVidia cached generated opengl shaders so that's also quite cool to find out :)

**Comment by walterar** [comment]
I think (not sure) that this began with #3303

**Comment by richardpl** [comment]
I do not think this happens any more.

**Comment by nozmajner** [comment]
I haven't noticed this for a while now.
