### ISSUE TITLE
Pioneer linux download CTD

### ISSUE THREAD

**Issue by sloanonlinux** [pioneerspacesim/pioneer#3734]
So I'm trying to run it on Linux Mint KDE edition:

~/pioneer-20160614-linux64 > ./pioneer
./pioneer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./pioneer)
./pioneer: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./pioneer)

**Comment by sloanonlinux** [comment]
The solution:
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-4.9 g++-4.9

Found at:
http://askubuntu.com/questions/466651/how-do-i-use-the-latest-gcc-on-ubuntu

**Comment by impaktor** [comment]
OK, I assume we can close it then.

**Comment by fluffyfreak** [comment]
Good work! closing.
