### ISSUE TITLE
Equipment lacks description

### ISSUE THREAD

**Issue by Wuzzy2** [pioneerspacesim/pioneer#3735]
The meaning of the various equipment for your ship is not really clear from the game.
I have no idea how to get a description of a certain equipment. I have not found special buttons, also there are no tooltips. I have tried to look into the equipment market screen of the space station, and of the “space ship screen” where you can review the equipment you already have installed. Nowhere I can find descriptions.

Oddly, descriptions seem to be present in the translation system. For example, I found the string “Shows profitable commodities to trade between selected and current system” which appears to be the description of the trade analyzer, I guess.
So it looks like the descriptions are there, but for some reason they are disabled.

Can you please look into this?

(tested in version 20160614)

**Comment by impaktor** [comment]
tripple: #3068, #160, #1670. -> Closing.
