### ISSUE TITLE
Feature request: flying, gliding, aerodynamics, elevators and rudders

### ISSUE THREAD

**Issue by sloanonlinux** [pioneerspacesim/pioneer#3737]
So currently, the spacecraft are not much more than rocket powered bricks, even if the model has wings. Let's change that, perhaps as a long term goal, and allow aerodynamics to be configured for each vehicle.

**Comment by impaktor** [comment]
It's a big and complicated change, no one working on this currently.

We discuss this here: http://pioneerspacesim.net/forum/viewtopic.php?f=3&t=160 therefore closing.
