### ISSUE TITLE
More useful texts in police tab and repair service tab

### ISSUE THREAD

**Issue by Wuzzy2** [pioneerspacesim/pioneer#3738]
I think the police tab and repair service tab can be more useful by giving the player more information.

I suggest to add the following informative texts in the repair tab:

If the ship is fully repaired, mention in another sentence how much it _would_ cost to repair a certain percentage of the current ship (I suggest 1%).
If you want to be extra nice, write down the formula which is used to calculate the cost, unless it is too complicated. Writing it in prose may also be OK.

I suggest to add to the police tab a section to list the punishable crimes. Currently, it would be mostly the same for any station as it appears to be the same in the entire galaxy. xD

The text could be something along the lines of:

“The following acts are punishable by law:
(list of crimes)”

It would be nice if the penalty (i.e. the fine, or if you will be attacked) for each crime is written in brackets after that. If this is not an exact number, write a range (e.g. “$1-$100”).

The list of crimes is probably the same for every police, with the exception of “Trading with illegal goods” (piracy), which should not be listed if there are no illegal goods.

If there is at least one illegal good, also add this text:
“The following goods are illegal in this system:
(list of illegal goods)”

I know this is redundant to the systems tab, but I suggest this anyways for convenience.

Maybe, the police strength could also be mentioned (or is it the same for all stations?).

**Comment by impaktor** [comment]
> If you want to be extra nice, write down the formula which is used to calculate the cost, unless it is too complicated. Writing it in prose may also be OK.

I don't think we should expose the nuts and bolts of the game. Makes it feel artificial. You don't get to see the "formula" when going to your car-mechanic. They pull a number out of their ass, that leaves you feeling they actually pulled it out of yours.

> I suggest to add to the police tab a section to list the punishable crimes.

I don't know. If there was a pull request for it, I might be more positive.

> Maybe, the police strength could also be mentioned (or is it the same for all stations?).

No, they have different number of ships.

Please consider posting ideas like these on our development forum instead. It's open for registration now.

**Comment by Web-eWorks** [comment]
Closing as off-topic, please open a new topic on the pioneer dev forum if you'd like to pursue discussion further!
