### ISSUE TITLE
Taxi mission: Show snarky comment when jumping to wrong system but equal name

### ISSUE THREAD

**Issue by Wuzzy2** [pioneerspacesim/pioneer#3739]
I once made a taxi mission where I had to jump to system XYZ. I jumped into system XYZ, but I noticed too late it was the wrong one. There were two systems sharing the name.
Yes, I know that equal names of systems are intentional.

Still I think this can be a bit unfair to new players because they don't know why they can't complete the mission. I suggest to add a snarky comment when the player jumps into a system which has the same name as the target system but it is not the target system.

Something along the lines of: “Hey, that's not the system I was looking for. Have you checked the sector coordinates?”

(And maybe some flavor variants.)

It's just a snarky comment which does not have any other effect (no reputation loss). It can help to get rid of one FAQ. :-)

**Comment by sloanonlinux** [comment]
The other Gliese 482, dummy!

**Comment by sloanonlinux** [comment]
Perhaps the comment could come upon arrival to the wrong system.

**Comment by sloanonlinux** [comment]
Hey wuzzy why don't you join us on IRC? Sorry, but I couldn't find any other way to contact you

**Comment by impaktor** [comment]
Then we would do that to all other misson types as well, not just Taxi.

**Comment by impaktor** [comment]
And yes, come buy IRC, and we can set you up with an account on our dev-forum, if you don't already have one, as most of what you post here, is better suited for the forum. 

On the issue tracker we post bugs, and things that are not working, where as on the forum we post ideas, and sketch new features, for the future, and discuss those there.

This issue falls on the "border" on if it is best suited for the dev-forum or issue-tracker.

Also, this is an easy one to fix, so good if either of you want to get into development of pioneer.
