### ISSUE TITLE
Hardcore game start for those who find life too easy.

### ISSUE THREAD

**Issue by Brianetta** [pioneerspacesim/pioneer#374]
Starting in an orbital station, with no hyperdrive, no autopilot and no atmospheric shielding... then making it play out that autopilots and hyperdrives are only available from the planet's surface. So, first thing the player has to do make their life less hands-on is learn to dock at an orbital, selectively choose missions and trade to scrape together the pennies for atmospheric shielding, then learn to land on a surface, then continue trying to earn money to buy that hyperdrive and finally break into the world of interstellar trade.

To make it even harder still, and really take the piss, give the player a ship that isn't compatible with atmospheric shielding. That way, they have to actually save up for a new ship before they can even consider purchasing an autopilot or leaving the system. I'm pretty sure I could think of things to make it even more daunting.

Requirements:
- The ability to limit items (in this example, a hyperdrive and an autopilot) to a specific starport or starports within a system.  My suggestion would be a low-tech system, with that one starport marked as having these items available.
- The ability to limit the slots available for ship upgrades to a greater extent.  In this case, a ship that can't use atmospheric shielding.
- A custom system in which to start.

**Comment by richardpl** [comment]
Well, we already have 3rd, and it is hard, do we really need yet another starting point?

**Comment by nozmajner** [comment]
I think it's hard enough. So no, I'd say no need for another starting point. Maybe a randomized one, if possible, but that's another question. (Random starting point, funds, ship, eqipment).

**Comment by Web-eWorks** [comment]
We have several game starts already, one of which fulfills almost all the conditions of this proposal. Closing the issue; if you feel a start needs to be harder, please open a PR with the proposed changes instead!
