### ISSUE TITLE
Untranslatable string: Uninstalling trade analyzer fail

### ISSUE THREAD

**Issue by Wuzzy2** [pioneerspacesim/pioneer#3742]
It looks like a particular string is untranslatable: If you attempt to uninstall the trade analyzer, the game complains that software can't be sold back. But this message is only in English. It does not look like this string has been exposed for translation.

(search for “system software”)

**Comment by impaktor** [comment]
You mean: "System software upgrades can not be uninstalled and resold. Visit a ship service station if you want to purge the upgrade from your on board computer", I assume. 

Right. I'll fix.

**Comment by impaktor** [comment]
Actually, I want to remove that "feature" all together. Not being able to sell something back (like Trade Analyzer) is not a good feature, in my opinion.

It was implemented by someone who had the distinct idea that this _must_ be software, and that you can't sell software back. I say: it could be a cartrige, or license, or whatever. I want it to have the same behavior as other equipment, just like it used to be. I don't see how the game becomes more "fun" by not being able to sell some equipment that you've bought.

@fluffyfreak are you OK with me changeing it back?
