### ISSUE TITLE
Lost external camera after merge #3751

### ISSUE THREAD

**Issue by walterar** [pioneerspacesim/pioneer#3752]
On reload saved game

![error3751-1](https://cloud.githubusercontent.com/assets/1334989/16654109/ac1f042a-442a-11e6-824b-1965e7214f64.png)
![error3751-2](https://cloud.githubusercontent.com/assets/1334989/16654153/d837bb42-442a-11e6-9a5c-da649a8ccc7d.png)

**Comment by fluffyfreak** [comment]
Ok thanks @walterar I'll look into it asap. Dammit the Faster float convert (#3751) was supposed to be safe :(

Nothing ever goes to plan!

**Comment by fluffyfreak** [comment]
Ah I see what's happened here :(
This will require a save game bump, I'll see if I can make a patch that will avoid that

**Comment by fluffyfreak** [comment]
There we go, we'll retain the improved saving speed, but revert back to the slower loading speed. it's less critical anyway.
