### ISSUE TITLE
Lat/Lon values could go to new line when there are negative values

### ISSUE THREAD

**Issue by Tichy** [pioneerspacesim/pioneer#3763]
See screenshot: 
![screenshot-20160718-204944](https://cloud.githubusercontent.com/assets/2348771/16926794/9f768456-4d2a-11e6-83ca-080adfeefe55.png)
Playing at 1440x900 in window.

Shortening Lat/Long labels isn't enough.

**Comment by impaktor** [comment]
I guess the minus sign causes a line break? Just move the text a bit to the left should fix this?

**Comment by Tichy** [comment]
I think so. Furthermore, I think it could be made more readable by aligning the text so that the minus sign does not shift the values to the right, but "appears" just before them. Like they were aligned in a grid.

![screenshot-20160718-204944](https://cloud.githubusercontent.com/assets/2348771/16927451/b913383e-4d2d-11e6-8119-2364bd802e2b.png)

**Comment by impaktor** [comment]
Looks fine on my resolution:
![scr](https://cloud.githubusercontent.com/assets/619390/17054797/65fc8374-5009-11e6-8c6c-ba9a540c564e.png)

Maybe something @jfacoustic wants to have a crack at? At least just moving the text a few notches to the left?

**Comment by Tichy** [comment]
It probably depends on screen proportions or font proportions (which are probably related to it). I see in your screenshot that your fonts are narrower.

**Comment by nozmajner** [comment]
This shouldn't happen on master since imgui HUD stuff got merged.

**Comment by Tichy** [comment]
But in the latest build from git I still see the old cpanel Lat/Lon indicators, along with the new reticule.

**Comment by impaktor** [comment]
@Tichy that's correct, they haven't been moved yet. Just an hour ago we were discussing what/how to move them. I think it was said that @ecraven will put them on the new HUD somewhere semi-temporarily, as end goal is to have them in a propper cockpit. He's swamped with real life until next week.

**Comment by Tichy** [comment]
Ok. Sorry. I didn'meant to be pushy. I misunderstood noz's comment, thinking that lat/lon in cpanel was alredy removed :smile:

**Comment by nozmajner** [comment]
Yes, I only meant the overlap should not be there.
