### ISSUE TITLE
Pioneer-20160724-win32 is crashing at startup on Windows 7

### ISSUE THREAD

**Issue by Magnum357-be** [pioneerspacesim/pioneer#3771]
Hello,
This night i have downloaded and installed Pioneer-20160724-win32 on my computer (64 bits) with Windows 7.
But when starting the game it go to the first screen with the options and stop running/crashing.
I have try in different compatibility mode but give the same results.
Important maybee: the last version of the binaries for windows have been just installed. # #

**Comment by impaktor** [comment]
Well, yesterday two pull requests were merged untested, "on good faith" possibly they contain something bad. Do you get an error message?

Have previous versions of pioneer worked? Please see FAQ on how to obtain older version.

**Comment by nozmajner** [comment]
20160724 works fine for me. Also on Win7 64 bit.

**Comment by Magnum357-be** [comment]
I have just tested version Pioneer-20160710-win32 and Pioneer-20160720-win32 but with the same result as the last version.
The game crash/stop running at the end of compiling models and rarely go up to first screen with the options.
I have try to run it without my firewall/antivirus in case of... but that change nothing.

**Comment by Magnum357-be** [comment]
The problem seem to be in the compiling of the world because it rarely go to the end of it and pass it to the options screen.
Hard to see or give more infos because there is no log file with a message erro or the process made before the game crash.

**Comment by fluffyfreak** [comment]
Hi @Magnum357-be was there also an 'opengl.txt' file next to that 'output.txt' file?
I just need the part with what GPU you have so the first 7 to 10 lines of it would be enough.

**Comment by Magnum357-be** [comment]
Here is the part you asked of opengl.txt and i have attached the file too.

OpenGL version 3.1.13399 Core Profile Forward-Compatible Context 15.200.1062.1004, running on ATI Technologies Inc. AMD Radeon HD 5800 Series
Available extensions:
...
...
Implementation Limits:
GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = 108
GL_MAX_CUBE_MAP_TEXTURE_SIZE = 16384
GL_MAX_DRAW_BUFFERS = 8
GL_MAX_ELEMENTS_INDICES = 1.67772e+007
GL_MAX_ELEMENTS_VERTICES = 2.14748e+009
GL_MAX_FRAGMENT_UNIFORM_COMPONENTS = 16384
GL_MAX_TEXTURE_IMAGE_UNITS = 18
GL_MAX_TEXTURE_LOD_BIAS = 16
GL_MAX_TEXTURE_SIZE = 16384
GL_MAX_VERTEX_ATTRIBS = 29
GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = 18
GL_MAX_VERTEX_UNIFORM_COMPONENTS = 16384
GL_NUM_COMPRESSED_TEXTURE_FORMATS = 18
GL_SAMPLE_BUFFERS = 1
GL_SAMPLES = 2
GL_ALIASED_LINE_WIDTH_RANGE = 1, 128
GL_MAX_VIEWPORT_DIMS = 16384, 16384
GL_SMOOTH_LINE_WIDTH_RANGE = 1, 63
GL_SMOOTH_POINT_SIZE_RANGE = 1, 63
[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/407186/opengl.txt)

**Comment by fluffyfreak** [comment]
Thanks! :)

**Comment by fluffyfreak** [comment]
@Magnum357-be there's a new build dated `20160814`.

Could you also try deleting your `config.ini` file, which should be in the same folder as the `opengl.txt` and `output.txt`, before running it again?

**Comment by impaktor** [comment]
No reply. Closing for now.
