### ISSUE TITLE
GRAPHICS

### ISSUE THREAD

**Issue by BILL2517** [pioneerspacesim/pioneer#3779]
The cursor bumps against but will not hover over the opening menu. Therefore, the user cannot do anything. Perhaps a resolution setting? BUT, the settings are not available. Game always starts with the same resolution. Cannot get to the settings. Why does it remember the settings? Cannot start new.
There is no "readme" or email address for problem reporting.

**Comment by impaktor** [comment]
Sounds strange.

> There is no "readme" ...

There's a wiki, with FAQ. Please see note there on location of config file. Try another resolution by manually editing it, and see if that resolves the problem.

> or email address for problem reporting.

This is the place, you're doing it right now.

**Comment by impaktor** [comment]
[README](https://github.com/pioneerspacesim/pioneer/blob/master/README.md)

**Comment by impaktor** [comment]
@BILL2517  Please let us know if you've solved this.

**Comment by fluffyfreak** [comment]
@BILL2517 also please provide some more detail, what operating system are you running the game on?
If Linux then what distribution and Window Manager.
Also what GPU are you using?

**Comment by BILL2517** [comment]
Win 8.1; I7-4770; GT640 (HP Envy Phoenix 810-160)
I am unable to change the resolution via config-resolution may be the problem.
ESC to config doesn't work until in the game...can't get there.
Updated video driver-no change
Initially, I could move over the menu items. I selected a resolution in setup. Now, can't hover over the menu. It seems to remember the bad resolutiuon even after removing the game and setting it up again.
Is there something hidden...a registry item?

**Comment by fluffyfreak** [comment]
No registry just the contents of the `config.ini` file, try deleting either the two lines:
`ScrHeight=960
ScrWidth=1280`
When it loads it will default to 800x600.

Or the entire `config.ini` file, it will recreate it when the game starts.

**Comment by BILL2517** [comment]
Thanks for the answer….there is no CONFIG.INI file

I created an empty one, which did nothing.

The program I downloaded is: "pioneer-20160814-win32"

 

Bill

 

"Be happy in your work."
- <http://www.imdb.com/name/nm0370564/?ref_=tt_trv_qu> Colonel Saito 

Sent from my toy computer

**Comment by impaktor** [comment]
> there is no CONFIG.INI file

_After_ running pioneer? There really should be a config-file found as described on the [FAQ](http://pioneerwiki.com/wiki/FAQ#Where_is_the_configuration_file.2C_saved_games.2C_screenshots.3F), which I alluded to in my first post. What do you find in that location instead? Do you see the save folder? opengl.txt?

**Comment by fluffyfreak** [comment]
You're on Windows so look in your `My Documents` folder, there'll be one called `Pioneer` and the `config.ini` is in there.

**Comment by BILL2517** [comment]
Yes, I see that…I'll apply your suggested changes and

get back to you

 

Bill

 

"Be happy in your work."
- <http://www.imdb.com/name/nm0370564/?ref_=tt_trv_qu> Colonel Saito 

Sent from my toy computer

**Comment by BILL2517** [comment]
Yes, removing the resolution lines allowed me in.

I've only tried 800x600 and 1024x768-which work.

Thanks for your help!

Bill

 

"Be happy in your work."
- <http://www.imdb.com/name/nm0370564/?ref_=tt_trv_qu> Colonel Saito 

Sent from my toy computer

**Comment by fluffyfreak** [comment]
Great, glad to hear that's fixed it :)
