### ISSUE TITLE
modelcompiler could use more threads to work faster

### ISSUE THREAD

**Issue by HybridDog** [pioneerspacesim/pioneer#3782]
l tried ```$ ./src/modelcompiler -b inplace``` and noticed ($ top) that it uses only one thread.

**Comment by fluffyfreak** [comment]
This is true, and it could use more threads to build multiple models simultaneously.

However, this is also a build tool that only really needs to run very infrequently. Usually on our build machine. A player might only do this if building from source and our model format has changed.

**Comment by fluffyfreak** [comment]
I'll leave this open in case someone has an interest in doing it.

**Comment by HybridDog** [comment]
thanks

**Comment by impaktor** [comment]
In my opinion, this is a non-isse if I've ever seen one. Is this something we want to spend time on? If @HybridDog has a patch, then good. Else, my finger is itching to hit close, to let us track real issues, and keep us focued on what matters.

Sorry if I sound anoyed, but I'm hungry and grumpy at the moment.

**Comment by fluffyfreak** [comment]
I figure that it might be a useful introduction for someone wanting to get involved. Maybe we should make a list of these bite-sized tasks and keep it on the wiki instead of the issue tracker?

**Comment by fluffyfreak** [comment]
Yeah going to track as bite-sized intro tasks on the wiki

**Comment by HybridDog** [comment]
>Maybe we should make a list of these bite-sized tasks and keep it on the wiki instead of the issue tracker?

This would make the issues list at github more lucid, to avoid that someone puts a trifle issue here, you could show a link to the guidelines, e.g. https://github.com/minetest/minetest/issues/new

**Comment by fluffyfreak** [comment]
@HybridDog ah, I didn't know you could do that :)

**Comment by fluffyfreak** [comment]
Ah ha!
https://github.com/blog/2111-issue-and-pull-request-templates
https://help.github.com/articles/creating-an-issue-template-for-your-repository/
Brilliant!

**Comment by fluffyfreak** [comment]
@HybridDog I just had a go at this tonight, unfortunately it's not possible at the moment with Pioneer.

In the background we do a lot of things like caches textures to avoid reloading from disk, generate shared buffers and no doubt a number of other things. None of which are compatible with multithreading at the moment so this would actually be quite a bit of work to fix all of those.

**Comment by fluffyfreak** [comment]
@HybridDog I've just opened a PR that enables with this a little help from an `SDL_mutex` and some head scratching :)

**Comment by HybridDog** [comment]
thanks

**Comment by fluffyfreak** [comment]
No, thankyou for suggesting it or I'd probably have never done it :)

**Comment by fluffyfreak** [comment]
Closing this as the #3821 PR was merged.
