### ISSUE TITLE
Reckless jump into non-inhabited system causes crash

### ISSUE THREAD

**Issue by clausimu** [pioneerspacesim/pioneer#3788]
### Observed behaviour
Doing a reckless jump from Los Angeles into an uninhabited system. After reaching the system the game crashed with: 

error: [string "[T] @modules/CrimeTracking/CrimeTracking.lua"]:27: attempt to index local 'station' (a nil value)
stack traceback:
        [string "[T] @modules/CrimeTracking/CrimeTracking.lua"]:27: in function <[string "[T] @modules/CrimeTracking/CrimeTracking.lua"]:18>

### Steps to reproduce
Do an illegal jump into a non-inhabited system.

__My pioneer version (and OS):__
pioneer: git (3c331d0)
openSUSE 42.1 64bit

**Comment by HybridDog** [comment]
Does it try to find a place in an uninhabited system to eject the police?
https://github.com/pioneerspacesim/pioneer/blob/master/data/modules/CrimeTracking/CrimeTracking.lua#L26

**Comment by impaktor** [comment]
I have assigned this to myself. I see the bug. I wrote the code.

**Comment by laarmen** [comment]
The bug is actually that there is a notion of law in an uninhabited system, which was assumed not to be possible.

**Comment by impaktor** [comment]
System `NN 3737` (close to Sol) has `lawlessness=0.5813`. I'll just do a quick fix for now, while we ponder the issue.
