### ISSUE TITLE
Segmentation fault after AI ship is set to hyperjump

### ISSUE THREAD

**Issue by clausimu** [pioneerspacesim/pioneer#3794]
### Observed behaviour
I hope it is not something stupid I did. But the crash seems to happen on the c++ side.

AI controlled ship is set to hyperjump (ship:HyperjumpTo(system-whatever.path)) out of a non-inhabited system. The corresponding functions that are triggered in Ship.lua and Equipment.lua run fine (as tested by inserting print statements everywhere). Engine present, enough fuel present, hyperjump status is "OK". But after the scheduled warmup time the game crashes with a segmentation fault. Ship never moved.

gdb backtrace:
```
#0  Frame::GetInterpPositionRelTo (this=0x0, relTo=relTo@entry=0x112fd130) at Frame.cpp:182
#1  0x000000000041ef8d in Body::GetInterpPositionRelTo (relTo=0x112fd130, this=0x11eec140) at Body.cpp:142
#2  Body::GetInterpPositionRelTo (this=this@entry=0x11eec140, relTo=<optimized out>) at Body.cpp:154
#3  0x0000000000593237 in WorldView::UpdateProjectedObjects (this=this@entry=0x115c2260) at WorldView.cpp:1769
#4  0x00000000005945a6 in WorldView::Update (this=0x115c2260) at WorldView.cpp:1202
#5  0x00000000004e3f19 in Pi::MainLoop () at Pi.cpp:1357
#6  0x00000000004e4dca in Pi::Start () at Pi.cpp:1222
#7  0x0000000000412765 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:130
```

### Expected behaviour
Ship should hyperjump.

### Steps to reproduce
I can provide a save game.

__My pioneer version (and OS):__
pioneer version: git (3c331d0)
OS: openSUSE 42.1 64bit

**Comment by clausimu** [comment]
Because @impaktor had asked in irc: removing the CrimeTracking module has no impact.

**Comment by laarmen** [comment]
I'll take that savegame :-)

**Comment by clausimu** [comment]
Savegame here: 

https://dl.dropboxusercontent.com/u/35453311/Pioneer/sar_test_26

To reproduce:

1) move within 49 m of the deep space miner just ahead
2) wait until all three crew members have been transferred to the deep space miner (as shown by the comms)
3) the deep space miner will then attempt to jump (but won't budge)
4) if you wait for 25 sec after the crew transfer the game will crash

**Comment by walterar** [comment]
@clausimu @laarmen The cause of this problem is similar to 3705.
You can have a temporary solution by adding these lines before the junp:

```
--- /orig/data/modules/SearchRescue/SearchRescue.lua
+++ /mod/data/modules/SearchRescue/SearchRescue.lua
@@ -1057,6 +1057,8 @@
 			if ship.flightState == "LANDED" then
 				ship:AIEnterLowOrbit(ship:FindNearestTo("PLANET") or ship:FindeNearestTo("STAR"))
 			end
+			if Game.player:GetNavTarget() == ship then Game.player:SetNavTarget() end
+			if Game.player:GetCombatTarget() == ship then Game.player:SetCombatTarget() end
 			Timer:CallAt(Game.time + 5, function () ship:HyperjumpTo(nearbysystems[1]) end)
 		else
 			return
```

**Comment by laarmen** [comment]
@clausimu I can't reproduce on master!

**Comment by laarmen** [comment]
Nor on 3c331d0 ! Are you sure you don't have any modifications to the code somewhere?

**Comment by walterar** [comment]
@laarmen 
This happens in the clausimu branch: SAR_fix_crew delivery #3795 - (2e9cefc)

**Comment by clausimu** [comment]
@laarmen - I'm sorry, @walterar is right. I should have mentioned that this needs the changes introduced in #3795. In the current master this mission is still broken and the target ship won't hyp no matter what.

I'm sorry I forgot to tell you.

**Comment by impaktor** [comment]
@laarmen should this be closed now?

**Comment by laarmen** [comment]
Indeed.
