### ISSUE TITLE
Segmentation fault on destroying target ship of SAR contract

### ISSUE THREAD

**Issue by yump** [pioneerspacesim/pioneer#3801]
### Observed behaviour

I took a search-and-rescue mission to retrieve crew members from a stranded ship.  After the crew transfer, I tried to destroy the derelict hulk to see if I would get illegitimate kill credit.  Instead, I got a segfault.

### Expected behaviour

Game does not crash.  Instead, there should be a total or partial penalty for destroying the ship. (Total if the crew is still on it, partial if they were rescued.)

### Steps to reproduce

1. Load [this save file](https://u.pomf.is/brtvte)
2. Hold down the spacebar and blow that orange rust bucket out of the sky.
3. Observe segfault.

__My pioneer version (and OS):__ 20160814-linux64, Fedora 24

**Comment by impaktor** [comment]
ping @clausimu

**Comment by walterar** [comment]
This happens when the ship destroyed is set as NavTarget and CombatTarget in the attacking ship

It can be solved with the following patches:
```
--- /orig/StatsTracking.lua
+++ /mod/StatsTracking.lua
@@ -41,9 +41,10 @@
 local onShipHit = function (ship, attacker)
 	if attacker and attacker:isa('Ship') and attacker:IsPlayer() then
 		PlayerDamagedShips[ship]=true
+		if attacker:GetNavTarget() == ship then attacker:SetNavTarget() end
 	end
 end
 
 Event.Register("onShipDestroyed",onShipDestroyed)
 --Commented out pending issue #887
---Event.Register("onShipHit",onShipHit)
+Event.Register("onShipHit",onShipHit)
```
```

--- /orig/SearchRescue.lua
+++ /mod/SearchRescue.lua
@@ -1683,7 +1683,7 @@
 	Timer:CallEvery(1, function ()
 
 		-- abort if player is about to leave system
-		if leaving_system == true then
+			if leaving_system == true or not mission.target then
 				mission.searching = false
 				return true
```

But the real solution lies elsewhere. PING @laarmen ?

**Comment by walterar** [comment]
@laarmen did his job. If #3796 is merged, do not need the patch for StatsTracking.lua

**Comment by laarmen** [comment]
@yump could you try with the latest master, possibly in GDB to get a stack trace ? If @walterar 's diagnosis is correct, it should all be fine, but I'd rather be on the safe side (and I can't very well try it at work, now, can I?)

**Comment by clausimu** [comment]
I will take a look as soon as I can, hopefully today.

**Comment by clausimu** [comment]
@yump - thank you for reporting and providing the savegame. For now I will shoot for eliminating the segfault first. But your ideas of penalizing the player for target ship destruction are noted and on my todo list now.

@walterar - I added the check for target ship presence in my search loop (see #3802). But still not sure about the segfault, even with the most up to date master.

@laarmen - stack trace when running in GDB:

#0  0x000000000f278f40 in ?? ()
#1  0x0000000000588a4e in WorldView::RefreshButtonStateAndVisibility (this=this@entry=0xb6cd330) at WorldView.cpp:1015
#2  0x00000000005943ce in WorldView::Update (this=0xb6cd330) at WorldView.cpp:1147
#3  0x00000000004e3f49 in Pi::MainLoop () at Pi.cpp:1357
#4  0x00000000004e4dfa in Pi::Start () at Pi.cpp:1222
#5  0x0000000000412759 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:130

**Comment by laarmen** [comment]
Apparently this had the same cause as #3794, closing.
