### ISSUE TITLE
Error compiling with mxe

### ISSUE THREAD

**Issue by walterar** [pioneerspacesim/pioneer#3803]
OSWin32.cpp: In function 'const string OS::GetHardwareInfo()':
OSWin32.cpp:149:34: warning: format '%u' expects argument of type 'unsigned int', but argument 4 has type 'DWORD {aka long unsigned int}' [-Wformat=]
   siSysInfo.dwActiveProcessorMask);
                                  ^
OSWin32.cpp:149:34: warning: format '%u' expects argument of type 'unsigned int', but argument 5 has type 'DWORD {aka long unsigned int}' [-Wformat=]
OSWin32.cpp:149:34: warning: format '%u' expects argument of type 'unsigned int', but argument 6 has type 'DWORD {aka long unsigned int}' [-Wformat=]
OSWin32.cpp:149:34: warning: format '%u' expects argument of type 'unsigned int', but argument 7 has type 'DWORD {aka long unsigned int}' [-Wformat=]
OSWin32.cpp:149:34: warning: format '%u' expects argument of type 'unsigned int', but argument 10 has type 'DWORD_PTR {aka long unsigned int}' [-Wformat=]
OSWin32.cpp: In function 'void OS::OpenUserFolderBrowser()':
OSWin32.cpp:254:75: error: cannot convert 'const wchar_t*' to 'LPCSTR {aka const char*}' for argument '2' to 'HINSTANCE__* ShellExecuteA(HWND, LPCSTR, LPCSTR, LPCSTR, LPCSTR, INT)'
  ShellExecute(NULL, L"open", dumps_path.c_str(), NULL, NULL, SW_SHOWNORMAL);
                                                                           ^
make[2]: *** [OSWin32.o] Error 1

**Comment by walterar** [comment]
@fluffyfreak
The blame seems to be #3790

**Comment by impaktor** [comment]
@fluffyfreak just letting you know that this also happens on the build machine, so no new builds until this is sorted out.

**Comment by impaktor** [comment]
Poor fluffy, he's on vacation the rest of the week, without mobile phone or computer (excellent decision! I applaud you sir!) I hope he's not thinking about this until he gets back. 

(He contacted us to let us know, regarding this issue)

**Comment by walterar** [comment]
Do not keep running away Andy. Surrender yourself, we guarantee a fair trial to you.

**Comment by fluffyfreak** [comment]
hmm `ShellExecuteA` should have resolved to `ShellExecuteW` since we use unicode. MXE might not be properly configured?

Either way the macro `ShellExecute` can just be substituted for the actual function `ShellExecuteW` and it shuld all be good.

PS: back from my holidays :) the lack of internet was unplanned, I even took my laptop!

**Comment by fluffyfreak** [comment]
Ok I just made a change directly onto master to fix this by calling `ShellExecuteW` instead of `ShellExecute`. I used `W` instead of `A` as that's the unicode variant so it should handle characters from a more diverse range of languages appearing within the path.

**Comment by fluffyfreak** [comment]
@robn @walterar I think this means that MXE should build again now :)

**Comment by walterar** [comment]
@fluffyfreak  This works fine now. :+1: 

You can return to the beach. :)
