### ISSUE TITLE
wheels up audio should continue upon hyperspace countdown initiation

### ISSUE THREAD

**Issue by Digit** [pioneerspacesim/pioneer#3804]
### Observed behaviour

"wheels up" audio cuts out upon **initiation of hyperspace _countdown_**,

instead of
### Expected behaviour

"wheels up" audio continues _during countdown_, only cutting out upon **initiation of hyperspace _jump_** 
-  if it even should cut out at all then either.
-  a bonus nice touch would be some kind audio distortion upon jump, if the sound was still playing at that moment
  -- like a very plush echoing-down-the-drain effect, or
  -- like a simple pitch (and speed) increase.
### Steps to reproduce

after taking off, hit f6 (or clicking wheels up button), and while the sound is playing, with a destination selected to jump to, hit f7 (or clicking the hyperspace button), 
wheels up audio cutting out upon initiating hyperspace countdown is jarring and ruins suspension of disbelief.

**My pioneer version (and OS):**
running pioneer-20160814-linux64:

**Comment by richardpl** [comment]
This does not happen any more, if one try to start hyperjump with wheels not completely retracted alarm will be played. And there is already another PR to fix audio crossfade issues.

**Comment by richardpl** [comment]
Should be fixed.
