### ISSUE TITLE
purchase equip mass cuts out of view in lower resolution

### ISSUE THREAD

**Issue by Digit** [pioneerspacesim/pioneer#3805]
### Observed behaviour

weight / mass / tonnage of equipment in ship equipment purchase screen cuts out in 800x600 resolution, able to see some 1 digit equipment masses able to see two pixels of the t.

like thus: http://ks392457.kimsufi.com/stuff/scrots/2016-09-07-074043_798x598_scrot.png
and here's the opengl.txt from pioneer config dir: http://ks392457.kimsufi.com/stuff/opengl.txt
### Expected behaviour

see mass of equip regardless of number of digits, and able to see the t, even in low resolutions.
### Steps to reproduce

reduce resolution to 800x600.
(not sure if system font is involved, causing this)

**My pioneer version (and OS):**
 running pioneer-20160814-linux64:

**Comment by impaktor** [comment]
Sadly, there's no one-size-fits all. I hope the new-new-UI/imgui floating windows will fix it.

**Comment by walterar** [comment]
@Digit You have two ways to solve this.

1) Download and apply this mod: https://sourceforge.net/projects/pioneersp/files/TuningMods/fonts43-pioneer-vanilla-mod.zip/download

2) Edit config.ini and change the value of UIScaleFactor=1 to UIScaleFactor=0.8

**Comment by impaktor** [comment]
...or fixed by imgui soon by @ecraven I hope, so no need to waste time on code to be kicked out.

@Digit you can uplad images directly to github, no need to link to outside source.

**Comment by Web-eWorks** [comment]
Fixed by the pigui rewrite.
