### ISSUE TITLE
Linking fails on macOS, ar has no flag D

### ISSUE THREAD

**Issue by ecraven** [pioneerspacesim/pioneer#3839]
As @tomyun mentioned in #3827, macOS does not have the `ar' flag D, so linking with our default flags crD fails.
Can anyone with macOS experience recommend a good set of ar flags?

**Comment by fluffyfreak** [comment]
@ecraven since none of us understood the original commit due to `ar` flags being absolutely impossible to Google, or to understand once you have found something, can you tell us what `ar` flags are for? And what `D` was supposed to do?

**Comment by fluffyfreak** [comment]
Just thinking that if we didn't need them previously, can we just remove them again?

**Comment by ecraven** [comment]
If we do not set ARFLAGS, they are cru by default with autotools. ar complains while linking with a warning. The intention of the fix was to get rid of that warning.
I think the best way forward would be to have different ARFLAGS on linux and macOS (crD for linux, cru for macOS). I'll start a PR later, but I cannot test on macOS :-/

**Comment by fluffyfreak** [comment]
Separate configs would be best I think then. From reading the feedback @tomyun gave it looks like they just need leaving blank on OSX.

**Comment by impaktor** [comment]
@ecraven ping.

**Comment by fluffyfreak** [comment]
The OSX builds using XCode work fine as far as I know, do we still want the autotools/cmd line version maintained if there is no maintainer?
