### ISSUE TITLE
The GL_OUT_OF_MEMORY OpenGL error, when turning to gas giant planet

### ISSUE THREAD

**Issue by senderghost** [pioneerspacesim/pioneer#3842]
The @impaktor suggested to report this on issue tracker.

How to reproduce:
1. Run pioneer application with default settings (e.g. cleared ~/.pioneer directory).
2. Click on "Start at Barnard's Star".
3. Push F4 button.
4. Click on "Request Launch" button.
5. Turn to Neptune gas giant planet (e.g. push 4 button on numpad (i.e. left)).

This may lead to following warning message (on 20161022) in console (and separate window):

```
...
Color Fractal name: GGNeptune
warning: In function DrawBufferIndexed
On line 769
OpenGL error(s) during frame:
GL_OUT_OF_MEMORY
...
```

Possible cause(s) of it:
More GPU memory required to process new algorithm(s), related to gas giant textures (d193baa757b4fe9e5552b31f21395a7a7dc29c01).
This was tested on FreeBSD 10.2 amd64, with using NVidia GeForce 9600 GT with 512 MB of GPU memory.

Results of git bisect log:

```
# bad: [da47e6a947a3a6053a50f4550c823f3fa4397254] Missing punctuation in goodstraderstrings, fix in code
# good: [176e8e9fe9567d1cf1b40fa550ccdf1a05df188c] auto-commit: translation updates
git bisect start '20160701' '20160628' '--'
# bad: [59bde651983807892a76dd150d95a85b5b520db9] Scope the small texture generation.
git bisect bad 59bde651983807892a76dd150d95a85b5b520db9
# good: [0b59b9aaf2fc71b0874a0266c3e74e273b2b2c92] Remove unused libs
git bisect good 0b59b9aaf2fc71b0874a0266c3e74e273b2b2c92
# bad: [4c90d35e71419ad7956289f827d4821f29448d4c] Merge branch 'master' of https://github.com/pioneerspacesim/pioneer into gpu-gas-giant-textures
git bisect bad 4c90d35e71419ad7956289f827d4821f29448d4c
# bad: [41272a856d9072404efbfdb10f0e3c9e4f96bb4d] What is the point of a new feature that is turned off? Enable by default.
git bisect bad 41272a856d9072404efbfdb10f0e3c9e4f96bb4d
# good: [e0a6db0722d67db18ad8f200e0d875c106df13cc] Subtle bitwise logic bug, replaced |= with &= when testing if GPU job shaders compiled. Add in a workaround for AMD R600 GPUs using MESA failing to compile shaders - use the DisableEclipse config flag as indicator. Pack the data into the top 16-bits of the MaterialDescriptor::quality member.
git bisect good e0a6db0722d67db18ad8f200e0d875c106df13cc
# first bad commit: [41272a856d9072404efbfdb10f0e3c9e4f96bb4d] What is the point of a new feature that is turned off? Enable by default.
```

The found commit is 41272a856d9072404efbfdb10f0e3c9e4f96bb4d.

**Comment by senderghost** [comment]
The @fluffyfreak suggested to use EnableGPUJobs=0 in config.ini (or ~/.pioneer/config.ini) for this case.
I tested this and it worked. Also this correlates with found commit 41272a856d9072404efbfdb10f0e3c9e4f96bb4d, with using git bisect.

**Comment by senderghost** [comment]
The possible (intermediate) solution is to revert 41272a856d9072404efbfdb10f0e3c9e4f96bb4d commit and provide configurable GUI option in Video settings for EnableGPUJobs (with default off, if you want to support users, for which pioneer worked before 41272a856d9072404efbfdb10f0e3c9e4f96bb4d commit (e.g. 20160628 release), without the need to find what option caused this issue on default settings (in config.ini) after first start).

**Comment by senderghost** [comment]
I consider this issue as (silently) ignored. It wasn't fixed (as of current 50c362b3653eaf221c0d5f9522c0612d29c3f150 commit) and closed without public explanation.

The user(s) with this issue may need to use manual solution to disable EnableGPUJobs in config.ini and/or build pioneer with following sed patch:
```
sed -i '.bak' -e '/EnableGPUJobs/s|1|0|' src/GameConfig.cpp
```
There is no configurable GUI option to do this manually and/or a hint about how to fix this.

**Comment by fluffyfreak** [comment]
@senderghost that isn't the case.

You haven't provided us with the `opengl.txt` or `output.txt` files which might help us diagnose the issue.
For example are you using the proprietary driver of the open source (nouveau)[https://nouveau.freedesktop.org/wiki/] driver?

You're options to fix this Out of Memory issue are:
- reduce the terrain detail level so that the game uses less memory
- make sure that it's the only program running (_so close web browsers etc_)
- make sure that the texture compression flag is enabled to reduce texture size
- or AS A LAST RESORT set the `EnableGPUJobs=0` in `config.ini`

The solution isn't by default `EnableGPUJobs=0` as that option will eventually go away when the terrain generation becomes a GPU job.

The main trouble we have is that you seem to have a very customised build and you are the only person who has ever reported this issue even when I specifically acquired a 512MB GPU (_borrowed from work_) I still can't reproduce the problem that you're having.

**Comment by senderghost** [comment]
> You haven't provided us with the opengl.txt or output.txt files which might help us diagnose the issue.

I provided other information, which explained this issue and how to reproduce it.
Ok, I attached [opengl.txt](https://github.com/pioneerspacesim/pioneer/files/657336/opengl.txt) and [output.txt](https://github.com/pioneerspacesim/pioneer/files/657338/output.txt) (with using RedirectStdio=1 in config.ini) files. The pioneer was run on default settings (i.e. low settings with 800x600 windowed screen) to reproduce this issue, as explained in first message.

> For example are you using the proprietary driver of the open source nouveau driver?

This is official NVidia driver for FreeBSD x64 ([340.101](http://www.nvidia.com/download/driverResults.aspx/113002/en-us) version, currently).

> Your options to fix this Out of Memory issue are:
> reduce the terrain detail level so that the game uses less memory

Attached [config.ini](https://github.com/pioneerspacesim/pioneer/files/657339/config.ini.txt) (with ".txt" file's extension, because of GitHub restrictions), where Planet detail distance: Low, Planet textures: disabled, Fractal detail: Very low, City detail level: Low. This is done for testing only, because pioneer is capable to run on higher settings.
> make sure that it's the only program running (so close web browsers etc.)

This was done on first test(s).
> make sure that the texture compression flag is enabled to reduce texture size

UseTextureCompression=1 by default.
> or AS A LAST RESORT set the EnableGPUJobs=0 in config.ini

This is what fixed this.

> The main trouble we have is that you seem to have a very customised build and you are the only person who has ever reported this issue even when I specifically acquired a 512MB GPU (borrowed from work) I still can't reproduce the problem that you're having.

I did git bisect, which found 41272a856d9072404efbfdb10f0e3c9e4f96bb4d commit as a (possible) cause of this issue. This is usual building of sources from pioneer's GitHub repository, with using FreeBSD ports system to install needed dependencies as in [games/pioneer](http://www.freshports.org/games/pioneer) port.
I can't say for others or invite other people to test, but I reported about this issue here, because I was asked to do this on IRC.

In the process of other testing I found, that sometimes disabled VSync and Multisampling (but not alone) didn't lead to "GL_OUT_OF_MEMORY OpenGL error", but pioneer's freezes (looks as if it dropping frames), when turning to gas giant planet (e.g. with numpad buttons) and ok, if not.

I can't exclude, that this issue may be related to this sample of video card. So, your note about not reported issue by many other people may be valid.

Thanks for public explanation.

**Comment by laarmen** [comment]
Who else had blanked out the FreeBSD part of the bug report? Because that
would explain a lot about the reproducibility issue :-)

**Comment by senderghost** [comment]
> Who else had blanked out the FreeBSD part of the bug report?

I reported about FreeBSD operating system in first message of this bug report.

I guess, this issue may be closed, if no other reports available about this issue in period of next week.
The possible manual fix exists, in case this issue will be raised again by other people.

**Comment by laarmen** [comment]
Yeah, I know, it simply didn't register in my brains.

**Comment by senderghost** [comment]
This bug report was closed, because this issue wasn't confirmed by other people, including upstream developers. On the other hand, the manual solution was found for releases between [20160701](https://github.com/pioneerspacesim/pioneer/releases/tag/20160701) and [20161129](https://github.com/pioneerspacesim/pioneer/releases/tag/20161129).
