### ISSUE TITLE
Bluenose High and Medium LODs are the same model

### ISSUE THREAD

**Issue by nozmajner** [pioneerspacesim/pioneer#3844]
I accidentally noticed that the High and Medium level LOD of the Bluenose is the same model, except the Medium one doesn't have the locators (which is correct BTW).
I was looking at the model file sizes out of curiosity, when we were discussing ship numbers/performance on IRC. 
@BobTheTerrible: Is it an error while exporting, and you have the mid LOD, or you/me should make one?

**Comment by nozmajner** [comment]
And I realized right away, that I could check if you have it in your asset repo...

**Comment by BobTheTerrible** [comment]
Nuts.... ok let me look into it. The blend likely has the med LOD in it.... If you get to it first let me know...
