### ISSUE TITLE
Autorefuel at docking/landing not working

### ISSUE THREAD

**Issue by limburgher** [pioneerspacesim/pioneer#3862]
Observed on 20161028 on Fedora 24.  Seemed to work on 20161022.

**Comment by nozmajner** [comment]
Could you elaborate?
Autorefuel was removed by #3837 and replaced by manual refuel on  the station lobby.

**Comment by limburgher** [comment]
Ah, ok.  However, it still says it's deducting a docking and fueling fee of $6, and it does reduce my money by $6.

**Comment by nozmajner** [comment]
Yes, the text wasn't updated for it to omit the fueling fee part.

**Comment by laarmen** [comment]
That's a problem...

**Comment by nozmajner** [comment]
How would you update the text? Just edit the lang file, and then after merge, it would be beamed to transifex?

**Comment by laarmen** [comment]
Yes, but check first where the $6 part came from!

**Comment by nozmajner** [comment]
Isn't that supposed to be the docking fee? I thought that still makes sense. At least if I were a spaceport operator, I'd charge for the usage of the landing pad and facilities.
Frontier charged that daily or weekly if I remember correctly.

**Comment by clausimu** [comment]
I would actually increase the price and make it a daily fee (like Frontier had it). Then having "cheap" small stations vs "expensive" large hubs makes for even more dynamics. But definitely keep the docking fee (even without refueling)!

**Comment by nozmajner** [comment]
Yeah, that's sound sane, but the question is, would that be fun for the player? Although I'm not against it, because then you have to plan ahead. But also that would assume info on starport type/fee somewhere in the UI you could check out before traveling.

**Comment by impaktor** [comment]
It could be that you would have to query the stations for fees and payment plans. Initial dockign fee + daily fee.

But then very soon we would see feature request for better UI to see all at once, and sort on fee, etc.

**Comment by clausimu** [comment]
I think a certain amount of pressure on the player (to have enough money, to think ahead) makes for fun play. It shouldn't be a nuisance, but be part of the experience of a self-employed pilot. I don't want to discuss feature changes/requests here though. We can do that in IRC if you want. :)

**Comment by limburgher** [comment]
Better!  The word fee has also been removed, but that's minor.

**Comment by impaktor** [comment]
Ops. Fixed in next release. Thanks.

**Comment by limburgher** [comment]
Thank you!

**Comment by impaktor** [comment]
@nozmajner, I think you missed that I posted the above just after having fixed it, 15e9884b54b285e76a68feb3659694e51b88ed20, so you don't need to do anything tomorrow, as you planned to (said in IRC).
