### ISSUE TITLE
Problems with saving the game

### ISSUE THREAD

**Issue by Neale88** [pioneerspacesim/pioneer#3866]
When trying to save a game either in deep space or at a station the game reverts to the Windows desktop with the following error:
                                      Lua serializer '(null)' tried to serialize an invalid 'SpaceStation' object

The game then ends and I lose my progress.  The problem does not happen all the time as I've made some progress in the game.  Sometimes it happens when I save at a station but not when I save in deep space.  Equally it happens when I save in deep space but not when I save at a station.  I'm running the latest build of Pioneer 20161028.  I run Windows 7 on an Intel Celeron G530 dual core with 6Gb of RAM.  Thanks for your help.

**Comment by ecraven** [comment]
See #3852, should be fixed in git.

**Comment by impaktor** [comment]
Yeah, it's a bug in the Oct 28 build. Please grab an older one (see FAQ) or wait for the next build, which will be out in a few hours I hope.

**Comment by Neale88** [comment]
Thanks for the help and advice.  The game is GREAT!  Pioneer is an excellent modern interpretation of Frontier Elite 2.  I still play Frontier through DOSBox.  Cheers, Neale

**Comment by impaktor** [comment]
@Neale88 thanks for kind words, and thanks for reporting.  A new build is out now, either grab it here https://sourceforge.net/projects/pioneerspacesim/files/ or wait 10 minutes for the pioneer home page to update.
