### ISSUE TITLE
Continually-accumulating vertex buffer in scenegraph/Billboard.cpp

### ISSUE THREAD

**Issue by jaj22** [pioneerspacesim/pioneer#3873]
I'm not sure how this code is supposed to work, but every time Billboard::Render() is called, it adds another vertex to the buffer, renders nothing and then doesn't clear the buffer. The vertex buffer does not appear to be cleared elsewhere, so it continually expands. The orbital station models appear to use this function.

The results here are that if you wait near an orbital station, the 2GB address space limit is exceeded in around 120,000 frames, typically causing a crash with a useless traceback.

**Steps to reproduce:**
1. Start game on Barnard's Star.
2. Wait a bit.
3. Put breakpoint on VertexArray::Add(const vector3f &v, const vector3f &n)
4. Check out size of the position & normal vectors.

**Setup:**
Pioneer version: Compiled from current master with VC2015
OS: Windows 8.1 64-bit
Settings: Default
Mods: None

**Comment by fluffyfreak** [comment]
Well that's embarrassing, it was me!

**Comment by fluffyfreak** [comment]
Interesting, at some point the `m_navlight->Render()` call went missing for orbital stations. 
So navlight billboards were being added but never flushed.

I've got a fix for this incoming shortly.
