### ISSUE TITLE
Time accel +- shortcuts sometimes jump more than one step.

### ISSUE THREAD

**Issue by nozmajner** [pioneerspacesim/pioneer#3875]
### Observed behaviour
 I noticed that the time acceleration step increase and decrease keyboard shortcuts sometimes jumps more than one step. Sometimes right to the top level even, and it happens up and down: if it jumps up two steps, then it also jumps down two steps.

### Expected behaviour
Buttons only increase/decrease one step.

### Steps to reproduce
It happens both on current master and the latest 2016-1110 (win32). 
Start a new game, the shortcuts work as expected.
Exit to main menu and start a new game on any of the starting points, or load a save.
Now it increases/decreases 2x
Go to main menu and start another game
Now it's 3x jump
Another new start
Now it's 4x jump
...
It goes away if you quit the game and restart, both for new games or loaded saves.

(_I noticed this a while ago, but I don't know how to reproduce it reliably apart from playing for a while. I'll record it next time I encounter it, I'm just reporting it, so I won't forget about it. (Or even better, somebody can reproduce it)
It usually happens after a bit of flying around. I notice it mostly when higher levels are restricted (close to a planet), and from 1x it jumps right away to 100x or above, skipping 10x, and they just blink away, and don't really accelerate time.
Just tried to get it again, but it didn't want to show it's face, even after forcing restricted levels by selecting it with ctrl, or landing and taking off again._)

__My pioneer version (and OS):__
Latest master, also happened on 20161028 win32
Win7 64 bit
It happens on 2015-1221, the first build on the moddb page that has it.

**Comment by walterar** [comment]
This is another symptom of the same old bug that produces # 3345 and # 3733
If you close and reopen the saved game (sometimes many times) it returns to normal.

**Fixing this bug should be top priority. Pioneer does not retrieve the saved game exactly.**

**Comment by nozmajner** [comment]
@walterar You are right and helped me figuring it out, but you are wrong about the cause. It does happen after a reload, but it's unrelated to the alert level. I don't get the alert bug, but it still happens.
And it happens also if you exit to the main menu and start a new game.

**Comment by walterar** [comment]
Question. Is there any way to temporarily remove all types of cache?

**Comment by laarmen** [comment]
OK, apparently @jaj22 fixed it in #3876 , so closing.

**Comment by impaktor** [comment]
@walterar if this really is the same bug as #3345, as you say, then you can close that one now.

**Comment by walterar** [comment]
@impaktor  The appearance of bug #3345 is very previous to what gave rise to this error that solved jaj22. Luckily I was wrong to relate them. But unfortunately there must be something else wrong out there.

**Comment by jaj22** [comment]
@walterar Well, load/save and even load/load are generally high-stress and liable to trigger bugs in both C & lua code. I'm particularly interested in any cases where loading the same saved game multiple times generates different results. I suspect there's an arbitrary overwrite bug somewhere, but they're very difficult to identify.
