### ISSUE TITLE
GL_INVALID_OPERATION on launch

### ISSUE THREAD

**Issue by CmdrBugbear** [pioneerspacesim/pioneer#3881]
### Observed behaviour
After compiling master successfully, Pioneer crashes with error:

ver git (0c423b2) on: Linux

System Name: Linux
Host Name: xxxxxxxx
Release(Kernel) Version: 3.16.0-4-amd64
Kernel Build Timestamp: #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19)
Machine Arch: x86_64
Domain Name: (none)

SDL Version 2.0.3
Initialized OpenGL 3.1, with extensions, renderer
invalid axis binding '' in config file for BindAxisPitch
invalid axis binding '' in config file for BindAxisRoll
invalid axis binding '' in config file for BindAxisYaw
started 7 worker threads
ShipType::Init()
Lua::Init()
Server agent disabled
Game::CanLoadGame('_exit')
nanosvg: /home/xxxxxx/Documents/Games/Pioneer/pioneer/data/icons/icons.svg 1024x1024
texture id: 20
nanosvg: /home/xxxxxx/Documents/Games/Pioneer/pioneer/data/icons/icons.svg 1024x1024
texture id: 21
error: OpenGL error(s) during frame:
GL_INVALID_OPERATION

This error seems to have been introduced on 16th October - I am able to successfully compile and run commit./ c716257, but from 7c71de9 onwards, it crashes on launch.

### Expected behaviour
Pioneer launches successfully

### Steps to reproduce
(git checkout master)
(cd to pioneer directory)
./bootstrap
./configure --with-thirdparty=../pioneer/pioneer-thirdparty
make
ln -s ../data ./src/data
./src/pioneer

__My pioneer version (and OS):__
OS: Debian GNU/Linux 8 (jessie) 64-bit

**Comment by fluffyfreak** [comment]
@CmdrBugbear in the `opengl.txt` file what GPU are you using? Can you post the first 5 or 10 lines of it here so we can see?

**Comment by CmdrBugbear** [comment]
OpenGL version 3.1 (Core Profile) Mesa 10.3.2, running on Intel Open Source Technology Center Mesa DRI Intel(R) Sandybridge Mobile
Available extensions:
Shading language version: 1.40
  GL_ARB_ES2_compatibility
  GL_ARB_ES3_compatibility
  GL_ARB_base_instance

**Comment by fluffyfreak** [comment]
@CmdrBugbear does it actually crash at that point? Or did you stop it running?

**Comment by ecraven** [comment]
This might be due to imgui trying to create a font atlas texture that is too large, I've seen crashes in similar places due to that. We are reworking the way font textures are created, so if this really is the reason, it should be solved soon. Also, we should add better error reporting about this.

**Comment by fluffyfreak** [comment]
Decals, I think that it's decals.

**Comment by fluffyfreak** [comment]
Yes! If I disable compress-on-load **OR** mipmapping for decals then they show up correctly on the Intel iGPU that I have running Linux Mint.

So the problem is the combination of compress-on-load **AND** mipmapping, I tried with either of them enabled and it worked so it only fails when they're both enabled.

**Comment by fluffyfreak** [comment]
And finally if I disable runtime DXTn compression, i.e.: `UseTextureCompression=0`, in `config.ini` then there's no problems at all at startup.

**Comment by jaj22** [comment]
I might be barking up the wrong tree here, but as far as I can tell, the uncompressed source + mipmaps texture path never generates the mipmaps, which should be incorrect behaviour. The partial update function does generate mipmaps, which suggests that it's an accidental omission.

I suspect some older games ignored the texture completeness rules and so most GL drivers silently disable the mipmapping, but there's one particular path on the Intel drivers that follows the rules and throws the INVALID_OPERATION.

Some test code. Check if this fixes the problem:
https://github.com/jaj22/pioneer/commit/35c3528871bbc6b3d96700efc6b03d1c41029803

**Comment by CmdrBugbear** [comment]
Hey all, back again (blame an inconvenient timezone...)
@fluffyfreak Pioneer crashes before it displays the initial "Simulating evolution of the universe..." progress bar.
@jaj22 - I'm currently downloading and compiling your branch.  This will take an hour or so.  Once done I'll post the results here.
Thanks everyone :-)

**Comment by CmdrBugbear** [comment]
Slight hurdle - jaj22, when I attempted to run ./configure, it complained about not finding assimp > 3.0.  I have 3.1.1 (pretty sure I composed the configure command correctly).  I've got things to do for the next few hours so I'm probably not going to get a chance to look at this again until tomorrow night / Saturday morning.
I'll keep you posted.
Cheers

**Comment by fluffyfreak** [comment]
It's Assimp >= 3.2 that is needed.

**Comment by fluffyfreak** [comment]
@CmdrBugbear in your existing copy of pioneer could you try opening the `config.ini` and changing:
`UseTextureCompression=1`
to
`UseTextureCompression=0`

Then running it again please?

**Comment by fluffyfreak** [comment]
You **might** get away with Assimp 3.1.1 for this test, if you want too then in your local copy just remove the lines between https://github.com/pioneerspacesim/pioneer/blob/master/configure.ac#L284 and https://github.com/pioneerspacesim/pioneer/blob/master/configure.ac#L313 (284 to 313).

Then `./bootstrap`, `./configure`, etc...

**Comment by CmdrBugbear** [comment]
Tried UseTextureCompression=0 - no effect, still crashed.

**Comment by fluffyfreak** [comment]
@jaj22 sadly that doesn't seem to work

**Comment by fluffyfreak** [comment]
I don't know if this issue is related to Intel drivers. I'm not seeing an actual crash on mine it just displays some corrupted textures and gives a warning popup once (*others are suppressed after first instance*)

**Comment by jaj22** [comment]
These could easily be different problems, although it seems likely that they're both are related to Intel drivers. If this one started on 16th October, it's probably related to the ImgUI merge, and that currently uses entirely separate texture loading and rendering code. I can't see any obvious suspects in the ImgUI code though. The font texture code does currently use a 4096x512 texture, but that should be within the hardware capabilities.

Might be worth trying a smaller font texture. In src/PiGui.cpp, change line 117 from:
`static unsigned short glyph_ranges[] = { 0x1, 0x3c0, 0x0, 0x0 };`
to:
`static unsigned short glyph_ranges[] = { 0x1, 0xff, 0x0, 0x0 };`

**Comment by CmdrBugbear** [comment]
Hi Jaj - I'm trying your edit to PiGui.cpp right now.  Compilation in progress...

**Comment by CmdrBugbear** [comment]
Took a while to compile - no change in behaviour:

./src/pioneer 
ver git (ee9a3d5) on: Linux

System Name: Linux
Host Name: xxxxxx
Release(Kernel) Version: 3.16.0-4-amd64
Kernel Build Timestamp: #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19)
Machine Arch: x86_64
Domain Name: (none)

SDL Version 2.0.3
Initialized OpenGL 3.1, with extensions, renderer
invalid axis binding '' in config file for BindAxisPitch
invalid axis binding '' in config file for BindAxisRoll
invalid axis binding '' in config file for BindAxisYaw
started 7 worker threads
ShipType::Init()
Lua::Init()
Server agent disabled
Game::CanLoadGame('_exit')
nanosvg: /home/xxxxxx/Documents/Games/Pioneer/pioneer_cmdrbugbear/pioneer/data/icons/icons.svg 1024x1024
texture id: 20
nanosvg: /home/xxxxxx/Documents/Games/Pioneer/pioneer_cmdrbugbear/pioneer/data/icons/icons.svg 1024x1024
texture id: 21
error: OpenGL error(s) during frame:
GL_INVALID_OPERATION

**Comment by fluffyfreak** [comment]
@CmdrBugbear off-topic slightly but when you're compiling you are using `make -j4` or a higher number right? It shouldn't take that long to build.

**Comment by fluffyfreak** [comment]
Ah ha! Thanks to #3885 and #3478 it looks like it might, at least in part, be the driver version you're running which from earlier in this thread is `Mesa 10.3.2, running on Intel Open Source Technology Center Mesa DRI Intel(R) Sandybridge Mobile`.

The PR #3885 should fix this issue and stop it from crashing at least, but you will still get two warnings on startup. Those you should get past ok but to completely fix it you can either update your Mesa installation to something post-11 or wait for your distro to upgrade too it.
