### ISSUE TITLE
No explosions when destroying ships in combat

### ISSUE THREAD

**Issue by Neale88** [pioneerspacesim/pioneer#3882]
I've been playing Pioneer for a few weeks now and it is a GREAT game!  I've found when in combat and I destroy a ship there is no explosion.  The ship I've destroyed disappears and I get the sound of the ship exploding.  I'm running the 22 October 2016 build of Pioneer on Windows 7.  My graphics drivers are up to date.  Thanks, Neale

**Comment by impaktor** [comment]
We just released a new version with many bug fixes, could you please try that one?

Could you also please post your output.txt found in your pioneer config folder?

**Comment by Neale88** [comment]
Here's the output.txt file
[output.txt](https://github.com/pioneerspacesim/pioneer/files/622348/output.txt)

**Comment by Neale88** [comment]
I've just tried the latest build of Pioneer and there are still no explosions.  A bit of a puzzle!

**Comment by Neale88** [comment]
Here's the output.txt file for the latest build of pioneer.  The previous file I posted was for 22 October 2016 build.
[output.txt](https://github.com/pioneerspacesim/pioneer/files/622498/output.txt)

**Comment by fluffyfreak** [comment]
Hi @Neale88 is there an `opangl.txt` in the same place that you found the `output.txt`?
If so could you copy and paste the top 4 lines from it here please?

Thanks.

**Comment by Neale88** [comment]
Hi fluffyfreak, here are the 4 lines of code.  Cheers, Neale
[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/622809/opengl.txt)

**Comment by impaktor** [comment]
Most probably same as #3888
