### ISSUE TITLE
Startup error - SDL initialization failed: windib not avialable

### ISSUE THREAD

**Issue by WmRTaylor** [pioneerspacesim/pioneer#3886]
### Observed behaviour
Pioneer would not start. Only gives SDL initialization error "windib not available".

__My pioneer version (and OS):__
ver 20161129 (0c423b2) on: Windows 10 x64
Downloaded pre-built 7zip file from pioneerspacesim.com

full output.txt:
ver 20161129 (0c423b2) on: Windows

Hardware information: 
  		OEM ID: 0
  		Number of processors: 4
  		Page size: 4096
  		Processor type: 586
  		Minimum application address: 00010000
  		Maximum application address: 7ffeffff
  		Active processor mask: 15

Windows 8
error: SDL initialization failed: windib not available

No opengl.txt available as game has not gone beyond the SDL error.

**Comment by jaj22** [comment]
Can you check the value of the environment variable SDL_VIDEODRIVER? To do this, open a command prompt (start button, type `cmd`) and then type `set SDL_VIDEODRIVER`.

**Comment by WmRTaylor** [comment]
Thought about that. It was set to "windib", but then I changed it to "directx". Same message, only with "directx not available".

**Comment by jaj22** [comment]
I think those are both SDL 1.2 driver names. In SDL 2.0, the only driver in the Windows video code appears to be called "windows". If in doubt, remove the environment variable and SDL will use whatever's available.

**Comment by WmRTaylor** [comment]
That worked! I remember having to set the variable because DOSBox or Stella wasn't starting. Deleted the var and now made it to the main menu at least, and everything else seems to be working normally. Now I just need to plug in my X-45 HOTAS and see the stars.

THX!
