### ISSUE TITLE
Ship name not displayed or editable in ship information screen

### ISSUE THREAD

**Issue by limburgher** [pioneerspacesim/pioneer#3891]
Ship name is viewable by using the external camera view, but the field for it in the ship information screen is blank, and nothing entered there is reflected anywhere.  Present in 20161129.

**Comment by nozmajner** [comment]
As far as I know it's more like a lack of feature. That name field was never shown on the external view. 
The number shown on the ships are considered more as a craft ID, like a licence plate number, and you can't just change that on a whim either.
It would be nice to display the ship name somehow for sure though.
Maybe @ecraven will find this interesting for the future UI work. :)

**Comment by impaktor** [comment]
@fluffyfreak did stuff regarding this on a branch. Idea was to have an ID number that could be hacked, and possibly a user selected name as well, if I remember correctly.

**Comment by fluffyfreak** [comment]
yep that was me aka: "half-implemented idea andy" :)

The idea was indeed to have it displayed on the exterior like the ID currently is. We can certainly do that as we do it for stations.

The changing of the ship ID itself would have worked a bit like the "[pay n' spray](http://gta.wikia.com/wiki/Pay_'n'_Spray)" shops in GTA. You got somewhere and pay to have you're ID changed which means that your criminal record is also wiped.

I got some of that done and partcially tested but the Lua frustrated me :/

**Comment by Web-eWorks** [comment]
The custom name of the ship has been editable for quite some time now, and changing ship identification numbers is off-topic. Closing as resolved!
