### ISSUE TITLE
Cannot load saved game

### ISSUE THREAD

**Issue by robothauler** [pioneerspacesim/pioneer#3893]
Game stops with error message "error: [string "[T] @libs/Equipment.lua"]:89: missing translation token: `SOME_TOKEN' in resource `some_resource', language code `en'."

"SOME_TOKEN" and "some_resource" are placeholder for various caught tokens and resources.

**Comment by impaktor** [comment]
It worked for me in #3890, but I haven't tried #3892. Does this happen when using English? Which straings exactly is it it cant find? An example? All?

**Comment by robothauler** [comment]
So far
`DRIVE_CLASS1_DESCRIPTION' in resource `equipment-core', language code `en'
and
`INDUSTRIAL_MACHINERY_DESCRIPTION' in resource `core', language code `en'

**Comment by robothauler** [comment]
Tried german language and a fresh start at earth, save, and load.
error: [string "[T] @libs/Equipment.lua"]:89: missing translation token: 'DRIVE_CLASS3_DESCRIPTION' in resource 'equipment-core', language code 'de'.
