### ISSUE TITLE
Police ship spawned as pirate

### ISSUE THREAD

**Issue by robothauler** [pioneerspacesim/pioneer#3902]
The "pumpkinseed_police" ship appears sometimes as pirate ship.
Also, sometimes an unarmed Varada is attacking.

I assume it is because the Police Pumkinseed is hyperdrive capable contrary to the other police ships.
And the front laser slot isn't checked in all missions.

**Comment by impaktor** [comment]
> The "pumpkinseed_police" ship appears sometimes as pirate ship

How can you tell? You mean you anger the police, and they come after you but send "Piraty" messages to you? "Give us the map to the gold treassure, arr!"?

**Comment by nozmajner** [comment]
It's not a coincidence, Elwood Blues was into police cars: :D
https://www.youtube.com/watch?v=LMagP52BWG8

**Comment by robothauler** [comment]
I cannot imagine such situations. I trust the police totally! :-D
