### ISSUE TITLE
Station docking repositions ship to designated pad, if trying to land on wrong pad.

### ISSUE THREAD

**Issue by nozmajner** [pioneerspacesim/pioneer#3905]
### Observed behaviour
@mike-f1 brought this to light:
When landing you are repositioned when you hit the collision mesh of another landing pad.
I noticed this back then when I tried per pad collision mesh in orbitals, but never realized that it happens on ground stations too (I'm too law abiding I guess).
It is quite more visible on his #3901 branch because it's not instantaneous like in current master.

### Expected behaviour
Ship should either set down on wrong pad, receive fine and/or scolding for his/her behaviour, and/or consider it a rough landing (no station connection).

### Steps to reproduce
Start on Earth, blast off and stop. Ask for clearance, which should point you to pad 7 or so. Just set down on pad 1, to be teleported to designated pad as soon as you reach pad.

__My pioneer version (and OS):__
20161129, Win7

**Comment by fluffyfreak** [comment]
hah! oops! I never tried that during the rewrite :) good find

**Comment by mike-f1** [comment]
I don't see a reason to keep this open: #3901 should solve this, although it not uses
bitmask for docking surfaces in order to identify the right pad (because this will limit
max number of pads to 16).
