### ISSUE TITLE
CTD asking DistanceTo in LUA

### ISSUE THREAD

**Issue by mike-f1** [pioneerspacesim/pioneer#3913]
![issueinluatrade](https://cloud.githubusercontent.com/assets/13293916/22294126/5f9417ee-e312-11e6-9fb7-f77b46ce6b5e.png)

### Observed behaviour
Results are documented in attached picture

### Expected behaviour
Trade ships ask DistanceTo nearest starport and then
decide if hyperspace or reach starport

### Steps to reproduce
try to kill a trade ship: you could use attached save game
[Test_ShipKill_SaveLoadError.zip](https://github.com/pioneerspacesim/pioneer/files/729964/Test_ShipKill_SaveLoadError.zip)

Pioneer version: January 2017, on Linux/Ubuntu x86_64

**Comment by walterar** [comment]
@mike-f1 This will solve the problem.

```
--- /old/TradeShips.lua
+++ /new/TradeShips.lua
@@ -786,7 +786,7 @@
 	if trader.no_jump ~= true then
 		if #starports == 0 then
 			trader['no_jump'] = true -- it already tried in onEnterSystem
-		elseif Engine.rand:Number(1) < trader.chance then
+		elseif trader.starport and Engine.rand:Number(1) < trader.chance then
 			local distance = ship:DistanceTo(trader.starport)
 			if distance > 149598000 * (2 - trader.chance) then -- 149,598,000km = 1AU
 				if getSystemAndJump(ship) then
```

**Comment by mike-f1** [comment]
@walterar  It work! :) ...this needs to be pushed in master I think

**Comment by mike-f1** [comment]
@walterar , do you want me to open a new PR for this?

**Comment by walterar** [comment]
@mike-f1 Yes, do it yourself, I do not get along with github, excuse me.

**Comment by mike-f1** [comment]
Ok, this needs to remains open because we don't know exactly what it happens...

Needs further investigations

**Comment by impaktor** [comment]
Has been fixed on master.

**Comment by mike-f1** [comment]
@impaktor : you're right, this has been fixed on master but with a "patch" (as we wrote in related PR).

The real reason why this happens is not yet investigated, so I suggest to 
left this open until we ended up with solution.
