### ISSUE TITLE
Assertion Failed(Imgui_draw.cpp, Line 1198) - I can not start Pioneer(20161129-win32) 

### ISSUE THREAD

**Issue by megamilove** [pioneerspacesim/pioneer#3928]
### Observed behaviour

I have seen the message that

>![mingw runtime assertion message](https://cloud.githubusercontent.com/assets/25802817/22992260/7c243ffa-f402-11e6-9a6b-a93465410dc4.jpg)

when I started Pioneer.exe.

### Expected behaviour

N/A

### Steps to reproduce

[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/778203/opengl.txt)
[output.txt](https://github.com/pioneerspacesim/pioneer/files/778202/output.txt)

__My pioneer version (and OS): Pioneer(20161129-win32) / Windows7(Service Pack 1)

Thank you for your effort :)

**Comment by fluffyfreak** [comment]
It looks like the problem is caused by Unicode characters in the file name path.

> nanosvg: D:\게임\pioneer\pioneer-20161129-win32\data/icons/icons.svg 1024x1024
error: Could not open SVG image.

@ecraven this looks like it's nanosvg's fault, since it uses standard C file handling

**Comment by impaktor** [comment]
Fixed.

**Comment by impaktor** [comment]
OK, maybe not fixed. Please report if it happens again. 
Especially our next build (whenever that is).
