### ISSUE TITLE
Telescope for planetary observation

### ISSUE THREAD

**Issue by Brianetta** [pioneerspacesim/pioneer#393]
Suggested by batmump (German language):

Postby batmump » Fri Aug 19, 2011 8:31 am
http://www.spacesimcentral.com/forum/viewtopic.php?f=77&t=2315

I read here recently of an idea, that doesn't have functional value, but which would further the immersion of the game.  Somebody wished for a searchlight on the ship.  Here's a further idea.  What is your opinion of, if you could, from one planet, make a survey of other planets in the same system, or if directly after a hyperspace jump you could immediately take a glance at the planets in the system before you?  A telescope would be fine thing.  Perhaps, sure, only in the ships that have turrets.  Also, only mountable on these placements.

Danke schön, batmump.

**Comment by impaktor** [comment]
I was more thinking that a "magnifying glass" could be useful in ship-to-ship combat. Also, this would let the player see our nice ships, that are usually just tiny dots now.

**Comment by nozmajner** [comment]
Mechwarrior 3 had something like that, and it was quite good for combat. On right mouse (or something) the HUD dispayed a rectangular magnified area around the crosshair.  Although you could move around your crosshair in it and the weapons tracked it.
http://youtu.be/cLan9dguo2s at around 2:40

**Comment by fluffyfreak** [comment]
Another option is to show a 3D image of the ship you're currently targeting relative to your ship.

That way you can see from the radar+ship what direction they must be heading in, plus you get a neato view of their ship ;)

As for the telescope, I like the idea of using it to target a planet/star for a while to do a simple survey of it and get some extra information.

**Comment by impaktor** [comment]
> That way you can see from the radar+ship what direction they must be heading in, plus you get a neato view of their ship ;)

If we show a little tiny enemy ship like that, then I (here's where it gets ambitious) like it to be linedraw, and eventually show damage to enemy hull.

(But just a magnifying glass would be sweet)
One presses a fourth mouse button? or presses x/z to zoom?

**Comment by impaktor** [comment]
Bottom right:
![wc](https://cloud.githubusercontent.com/assets/619390/10611062/bbb8c81a-774a-11e5-9ba5-17262a04a117.png)

**Comment by corundscale** [comment]
Could we open a secondary viewport somewhere on HUD with zoomed in (low FOV) to fit view of current target?

**Comment by Web-eWorks** [comment]
SystemView is slated for several improvements that will make the original concept of this issue possible; target status display is an entirely unrelated feature that needs its own issue.

Closing as unimplemented; feature requests and discussion should go on the [forum](https://pioneerspacesim.net/forum), as we use Github for tracking actively-developed features and issues with currently-implemented functionality.

If you'd like to re-open this, please instead open a new PR with an implementation of the proposed functionality, thank you!
