### ISSUE TITLE
Fullscreen Misalignment and Windowed Mode Too Large when using Low Resolution

### ISSUE THREAD

**Issue by Enverex** [pioneerspacesim/pioneer#3932]
Not sure if this is fixable or just a universal design issue when trying to use a resolution so low, but I was trying to play the game today on a 1024x600px resolution screen and the game really didn't seem to like it.

In "fullscreen" mode, it would still appear in a window, but where the mouse was on the screen didn't actually match up with where the game though it was (despite it being the in-game cursor). I had to have the mouse about 200px above where I actually wanted to click. There was also a large black space above the rendered game inside this window.

![image](https://cloud.githubusercontent.com/assets/958670/23319562/01b64d48-facf-11e6-9dda-aa49423b0572.png)

Switching to windowed mode fixed the mouse issue, but the game itself was far too large and was pretty much unusable. Despite 1024x600 being selected in the resolutions drop-down box.

![image](https://cloud.githubusercontent.com/assets/958670/23319582/1bc57556-facf-11e6-8651-ecaf1db00c87.png)

Is this a configuration issue, a fixable issue with the game itself, or an unfixable issue due to scaling limitations?

**Comment by impaktor** [comment]
You can set the pioneer resolution in the config file in the pioneer config folder.(see FAQ on wiki)

**Comment by Enverex** [comment]
It already appears to be correct in the menu and the config file appears to be correct:

ScrHeight=600
ScrWidth=1024

**Comment by johnbartholomew** [comment]
The gap you're seeing at the top of the window is certainly strange. I tried running at 1024x600 in windowed mode and it worked ok; the UI scaling should be able to cope with it (mostly anyway -- there might be bad UI layout in some places).

What happens when you run the game in windowed mode (set StartFullscreen=0 in the game's config file)? Does everything still get displayed with a vertical offset?

![screenshot-20170224-231016](https://cloud.githubusercontent.com/assets/115749/23324579/7ea16cc2-fae6-11e6-85a9-be2b927a2824.png)

![screenshot-20170224-231021](https://cloud.githubusercontent.com/assets/115749/23324621/bbdb2ee8-fae6-11e6-9597-3fc36be890d7.png)

**Comment by johnbartholomew** [comment]
As an amusing aside, the game's default settings are actually still 800x600 (windowed mode):
https://github.com/pioneerspacesim/pioneer/blob/master/src/GameConfig.cpp#L16

**Comment by Enverex** [comment]
Not sure if you saw (or read?) my first post. The two images I posted were "fullscreen" and then in windowed mode. Big offset was fullscreen (yet still appeared in a window) and the "doesn't fit the screen" shot was in windowed mode.

Settings I change in-game are saving correctly in the config file (e.g. windowed mode or not, resolution, etc).

**Comment by johnbartholomew** [comment]
I both saw and read your first post, I just missed the sentence between your two screenshots. Earlier in the post you wrote "In "fullscreen" mode, it would still appear in a window", so I thought *both* screenshots were with StartFullscreen=1.

**Comment by Enverex** [comment]
Ah right. So yeah, to clarify: In fullscreen mode, it still appears in a window and is displaced downwards. In windowed mode it isn't displaced, but the window is much larger than it should be.

**Comment by johnbartholomew** [comment]
Ok. I'm sorry I don't have any brilliant ideas about this, but I have some system questions anyway.

- Have you seen this kind of problem with any other software?
- Is this on Linux? (If not, the rest of these questions are irrelevant)
- What window manager/desktop environment are you using? Do you happen to have any other window managers installed that you could try?
- X11, or Wayland? And if using Wayland, are you able to try it on X11?
- Do you have any screen scaling settings configured in the window manager? (I assume not...)

**Comment by Enverex** [comment]
* No.
 * Yes. Arch, 64bit, latest kernel (4.9.11).
 * MATE, I could maybe try something else but I've never heard of issues like this with anything on MATE before.
 * X11 (Wayland has too many unimplemented things so far).
 * No scaling or anything of that sort configured.

It's all a bit odd really.

**Comment by mike-f1** [comment]
I have something similar to things above happening on my machine:
Xubuntu 16.04, with fglrx driver (lspci output say:
`3D controller: NVIDIA Corporation GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M]` ).

I have no problem running at any resolution (even custom) if windowed,
but if I launch pioneer after setting a custom resolution it switch to 1024x768.
More: my machine is a laptop with 1600x900 tft, and if in fullscreen mode, pioneer
not use all the screen.

**Comment by fluffyfreak** [comment]
@mike-f1 how are you using the `fglrx` driver with an nVidia GPU?
Also which Xubuntu window manager do you use?

Since it's an nVidia GPUcan you check what GPU drivers you're using for it? 
Or if it is using the `fglrx` driver then is it an AMD CPU with a built-in GPU?

**Comment by mike-f1** [comment]
@fluffyfreak , I'm using standard X11 wm and it seems I use
NVIDIA driver version 340.101, while board is an GeForce GT 630M
with 1GB of dedicated RAM.

With my previous posts I would also state there're troubles when programs
run in fullscreen if not at the display resolution: this happened sometime also
in Window (at least the games I had...).

Just, I don't know how it work: to me it seems that when you don't play
at display resolution sometime drivers "crop" the image... But I could be
wrong

**Comment by Enverex** [comment]
For reference, my machine in this instance has an Intel HD 500 and is using Mesa 13. This isn't an AMD/Nvidia issue.

**Comment by mike-f1** [comment]
@Enverex : May I ask if it works in fullscreen if resolution is what it is needed by your display?
...and what if is a "standard" resolution (like 1026x768 or 800x600)?

**Comment by Enverex** [comment]
That's covered by my first post. No and 1024x600. The display only supports one resolution so I can't try any others.

**Comment by impaktor** [comment]
> The display only supports one resolution so I can't try any others.

![c1084](https://cloud.githubusercontent.com/assets/619390/23342752/38389cf8-fc60-11e6-8f98-592350b75e3c.jpg)

**Comment by Enverex** [comment]
That's a syncmaster isn't it? In which case that actually supported loads!

**Comment by impaktor** [comment]
....would be interesting to see pioneer run on it.

**Comment by impaktor** [comment]
The UI has  been replaced since this was reported, scaling is still not perfect with the new one, I suspect, but that's discussed in other threads.
