### ISSUE TITLE
Compiler warning in miniz: always_inline attribute

### ISSUE THREAD

**Issue by HybridDog** [pioneerspacesim/pioneer#3935]
When compiling, l get some of this warning:
warning: always_inline function might not be inlinable [-Wattributes]

Why is the always_inline attribute used there?

**Comment by laarmen** [comment]
Probably because it isn't our code so we didn't touch the build system more than strictly needed.

**Comment by HybridDog** [comment]
Usually with optimization flag, gcc automatically detects whether inlining makes the code more efficient. If you inline too much, the code becomes longer, thus more code needs to be loaded into the processor cache and if you don't inline, the code is spread, incoherency leads to more frequent cache loading into the low level cache.

**Comment by laarmen** [comment]
Well, yes. But still, we let gcc do its thing, our upstream theirs, and we
patch only if necessary, which isn't the case here.

Le lun. 27 févr. 2017 à 18:14,
̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄
̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄̄ <notifications@github.com> a
écrit :

**Comment by HybridDog** [comment]
Then please suppress the warning by passing a flag to gcc.

**Comment by laarmen** [comment]
I will not write the patch as I find build systems a PITA but I'll happily merge somebody else's.

**Comment by impaktor** [comment]
@ecraven relation to #3982, or just close?
