### ISSUE TITLE
Build error: textstress.cpp:10:33: fatal error: text/FontDescriptor.h: No such file or directory

### ISSUE THREAD

**Issue by ckorn** [pioneerspacesim/pioneer#3939]
### Observed behaviour
- The build fails.

### Expected behaviour
- Build should succeed.

### Steps to reproduce
- Build version 20161129
This is the build log:
http://pastebin.com/raw/GTUFd37T
```
textstress.cpp:10:33: fatal error: text/FontDescriptor.h: No such file or directory
```

__My pioneer version (and OS):__
Ubuntu 16.04
pioneer version 20161129

**Comment by impaktor** [comment]
> pioneer version 20161129

I'm not sure I follow, are you building from master branch? If so, your version sould be today's version, preferably given by hash, e.g. curent one is ab2433354f4be6dd19fd7a957381df73bf47a762

**Comment by ckorn** [comment]
This is from the tarball:
https://github.com/pioneerspacesim/pioneer/archive/20161129.tar.gz

**Comment by mike-f1** [comment]
@ckorn: you are trying to build a deb package from source. If you just try to compile pioneer it works.

Try with `./bootstrap && ./compile && make -j4`

**Comment by impaktor** [comment]
...and please compile from master, `git clone <path>`, we need people testing latest features.

**Comment by ckorn** [comment]
Just found out that this build error only occurs when compiling the tests.
So when disabling the tests everything is fine.

Yeah, I want to create a Debian package for the Ubuntu gaming site playdeb.net.
There was a request to build and publish this game.

I am taking the latest of your builds because this way I automatically see when you publish a new build. When I build master from today, I cannot tell when I should build a newer version.

**Comment by impaktor** [comment]
@ckorn We tweet the new builds, at least if they have something moderately new in them.

And since pioneer is built on a Debian 8 machine (if I'm not mistaken), why do you need to re-build it once more?

**Comment by ckorn** [comment]
@impaktor The sources need to be built on the build server to get published.
I cannot publish precompiled packages.

**Comment by fluffyfreak** [comment]
This thread raises a good point though, we have defunct/dead tests committed.

**Comment by ckorn** [comment]
Just to let you know.

Just published the game on PlayDeb.net

http://www.playdeb.net/game/Pioneer

**Comment by laarmen** [comment]
Patches to the debian/ directory are welcome... Although now that it comes
up, I'm thinking we should actually just rip it out of our repo and let
packagers do their thing...

**Comment by fluffyfreak** [comment]
@ckorn great thanks!
