### ISSUE TITLE
Strange behaviour close to Torvalds Plattform

### ISSUE THREAD

**Issue by robothauler** [pioneerspacesim/pioneer#3946]
Relative flight vector points to station, but distance increases.
This is the saved file.
http://hauler.lusc.net/pioneer/Test

**Comment by Atomschlag** [comment]
I get the same behavior from the autopilot when approaching Phobos base

**Comment by mike-f1** [comment]
In my case autopilot was unable to dock and when I try docking manually the sequence don't even start.
...Also collision don't work...

Could be related to https://github.com/pioneerspacesim/pioneer/issues/34?
I mean: something happens with `Frame` because this station is too near to planet:

![strangebehaviourneartorvalds](https://cloud.githubusercontent.com/assets/13293916/24007650/8fdf1c4e-0a6f-11e7-8c5f-f73f51f78b42.png)
![strangebehaviourneartorvalds2](https://cloud.githubusercontent.com/assets/13293916/24007651/8fe4854e-0a6f-11e7-9467-84b920f81e05.png)

**Comment by nozmajner** [comment]
This seem to happen for all smaller bodies, that have fast orbital speeds (my guess at least): Phobos and Deimos Bases, or Thebe for example. All of them have quite small frame radiuses and go around fast as far as I saw.
And if you fly into their frames, then set the autopilot to dock, it can do it. If you are out of frame, it's a drunk dervish.
Other observations: "The fly the vicinity" to distance to Phobos base is about 50km. (63km from body center in the case I tried.). You enter the frame of Phobos at about 52km from center.
AI ships seem to be also affected, I had like six of them flying a fixed distance from Phobos. They were pulling the dervish stunt too, depending on rotation speed of the ship. [Here's a savefile.](https://www.dropbox.com/s/o856kpvrnrp8gp7/phobos%20error?dl=0)
![dervish](https://cloud.githubusercontent.com/assets/4182678/24073553/583ae5ee-0bf9-11e7-869b-9cf3a35ab216.gif)
![screenshot-20170318-163221](https://cloud.githubusercontent.com/assets/4182678/24073556/61f4e896-0bf9-11e7-82aa-b8cd1a620e57.png)

**Comment by impaktor** [comment]
```
<JohnJ> oh, phobos is broken now?                                       [04:59]
<JohnJ> I tested it a lot before Christmas and it was fine then :P
<atom___> it bugs out at phobos, and others                             [05:01]
<JohnJ> Looks like someone reduced frame sizes to below the FlyAround
        distance.
<JohnJ> Either that or increased FlyAround distance indirectly by increasing
        the effect radius of bodies.                                    [05:03]
<JohnJ> possibly both. People like to change these things :P
<atom___> ^^                                                            [05:04]
<JohnJ> The FlyAround logic likely assumes that you're inside the target's
        frame, which is a reasonable assumption...                      [05:07]
```

**Comment by fluffyfreak** [comment]
@jaj22 / thread, could this be because of my #3491 changes to the Minimum PhysRadius?

**Comment by mike-f1** [comment]
...I fear yes :/ : tested applying your commit, but
> 
> <JohnJ> The FlyAround logic likely assumes that you're inside the target's
>         frame, which is a reasonable assumption...                      [05:07]
> 
this seems not true: in `AICmdFlyAround::Setup` (ShipAICmd.cpp:1084) you have a third object (the "obstructor") which can have their own frame.

But (at least for me) the question is if there's a way in which you could deal with this overlap, thus the lines you change aren't the *final* reason.
If there's a way to *deal* with this, then you could ease other problems:
- What if you are some AU away a planet (say Earth) and you would fly to another more distant planet (say Mars) that is behind the first? (note: the first object (=obstructor) could also be an orbital)
- What about (here just speculation) Galaxy gen? There's a *coded* way in which you avoid this overlap?

In `AICmdFlyTo` there's the *only* line where a `AICmdFlyAround` command is instantiated, and this line can be reached if `CheckCollision` returns 2, 3 or 4. And (finally!) `CheckCollision` rely on `MaxFeatureRad` to decide how to deal with obstructors...

All these thoughts to say:
It could be different values in `MaxFeatureRad` (ShipAICmd.cpp:618) (called just before the *only* line in where a AICmdFlyAround command is instantiated) made a difference?

**Comment by spolen88** [comment]
I have been unable to dock at Juarez Platform as well, I haven't tried to manually dock because I'm not sure how. I also receive the no collision issue.

I'm running Version "pioneer-20170304-win32"
