### ISSUE TITLE
Adding equipment ingame doesn't work

### ISSUE THREAD

**Issue by Jamould** [pioneerspacesim/pioneer#3951]
I've been typing "import("Game").player:AddEquip("equip", amount) ingame,
but it doesn't seem to work.

Something about the line being deprecated

Specifically trying to add passenger cabins and hyperdrives

Pioneer Scout Plus G30F

**Comment by laarmen** [comment]
I'm gonna need the exact line that doesn't work.

**Comment by fluffyfreak** [comment]
@Jamould this appears to be a bug for [Scout Plus](https://github.com/walterar/pioneer-sp) which is a fork of Pioneer which branched off in December 2012 so there's probably some differences with the scripting!

You either want to ask on their GitHub or on their forums http://spacesimcentral.com/forum/discussion/3229/new-game-mod-pioneer-scout/p23
