### ISSUE TITLE
Incorrectly listed as 31st century

### ISSUE THREAD

**Issue by spolen88** [pioneerspacesim/pioneer#3956]
when looking at the website, it states "Pioneer is a space adventure game set in our galaxy at the turn of the 31st century." but the game starts Jan. 1 3200 which is the turn of the 33rd century.

**Comment by laarmen** [comment]
3200 is still technically the 32nd century (no year 0) but indeed,
something is wrong :-)

**Comment by impaktor** [comment]
Well, yes and no.

Yes, 31st century is wrong, but I'd say the 33rd century starts in the year 3201.

Which is why the famous book is titled "2001", and not "2000". And why an [incunable](https://en.wikipedia.org/wiki/Incunable) is a book printed before 1501.

**Comment by impaktor** [comment]
So, now that we can put the nitpicking aside, what should we change it to?

**Comment by spolen88** [comment]
I suppose so there's no confusion it could say:

 "Pioneer is a space adventure game set in our galaxy in early 33rd century."
or
 "Pioneer is a space adventure game set in our galaxy during the turn of the 33rd century."
or (My personal favorite)
 "Pioneer is a space adventure game set in our galaxy at the end of the 32nd century."
 
This way even if it's technically starts in the 32nd century, it's still accurate because it's not the 32nd century for long, and will mostly be in the 33rd after that.

**Comment by fluffyfreak** [comment]
I like: "Pioneer is a space adventure game set in our galaxy at the end of the 32nd century."

Might also suggest alternatives: 
- "Pioneer is a space adventure game set in our galaxy at the close of the 32nd century."
- "Pioneer is a space adventure game set in our galaxy at the dawn of the 33rd century."

**Comment by spolen88** [comment]
@fluffyfreak I really like "Pioneer is a space adventure game set in our galaxy at the dawn of the 33rd century."

**Comment by alugarius** [comment]
We also can change the Game and make it 3201 tho

**Comment by impaktor** [comment]
> We also can change the Game and make it 3201 

That would break some of our security questions. I think 3001 would look more neat, or 3200, for historical ties to Frontier (which I assume started that year). Also changing year would mess up our "lore" on the wiki.

**Comment by fluffyfreak** [comment]
Or we can just change the text on the website/docs :)

**Comment by impaktor** [comment]
@WKFO Care to open a PR against our website repo? Changing to "32nd century", I think is the above consensus.

**Comment by WKFO** [comment]
@impaktor I just did: https://github.com/pioneerspacesim/pioneer-web/pull/11
