### ISSUE TITLE
The Facegenerator!

### ISSUE THREAD

**Issue by alugarius** [pioneerspacesim/pioneer#3961]
Its just bad, if using that kind of system i recommend following...

1. NOT using random pieces of faces of real human.... its looking scary and unprofessional, i am for using at least comic style faces.

2. Choosing the style manually for the own profile, not spamming the random button and hopeing for a less ugly face.

A swich in the settings to turn them off?
   I am just really disgust by this mutant people.

(a smaller suggestion, for later versions:  Choosing a race, not only human.)

**Comment by nozmajner** [comment]
[Sure it is](https://youtu.be/pK3FEiNiKOk?t=3m29s). Yes, we know, we aren't blind really. :D
1. Sadly it's not a trivial one afternoon job to fix it. It's a vestige nobody got around cutting out/replacing.
[Evarchart started working on an updated set](https://pioneerspacesim.net/forum/viewtopic.php?f=3&t=218) a while ago, don't know if he had any progress on it recently.
2. Would be useful. Hoping for less ugly is futile, these images are not able to produce any.

You could try your hand making a generic mod that only shows woman/man silhouettes without any features, as a workaround. (Paragon/Jumpdrive approached it this way) And my experience is that after a bit you just tune them out and don't really notice them. (I do at least)

About races: we don't have any alien races and aren't really planning one, at least for now. (huge volume of work even to come up with distinct designs, and we are behind with human stuff already)
Also the "A game of lonely space adventure" tagline could be approached from several directions. ;)

**Comment by alugarius** [comment]
I might have found a face that looks like Nicolas Cage

**Comment by nozmajner** [comment]
There are lot's of Nicolas Cages in there to be found.

**Comment by alugarius** [comment]
I found in the forum a mod that uses comic style faces, alot better

**Comment by impaktor** [comment]
You can download Evarchart's mod here: http://wayneashworthart.com/pioneer%20facegen%20mod.html

And also throw money at him, to show appreciation.

**Comment by alugarius** [comment]
i meand that, cant we use that facegen instead?

**Comment by impaktor** [comment]
No, because it doesn't have all the components needed, nor in the quantity.

**Comment by alugarius** [comment]
well, leaving the actual one isnt a good idea. 
Any ideas to make this better without mods?

**Comment by impaktor** [comment]
This isn't a case of getting something for nothing. It will cost significant time to replace. We've discussed this at length, before. Over many years of time.

**Comment by nozmajner** [comment]
Yes, it's not about ideas. It's about lots of work.

**Comment by alugarius** [comment]
What exactly has to be done?

**Comment by nozmajner** [comment]
Parts for faces. Lot's of them. Eyes, noses, mouths, heads, hairs, clothes, bgs.

There's like 700 files in the facegen dir currently, which is a lot even when you account for a little bit of redundancy.
It really comes down to the amount of work needed, nothing else.

**Comment by LuccoJ** [comment]
Let me be a voice out of the choir and express some sympathy for the uglyfaces. We're not all born beautiful, and most of us are born pretty random!
I like the faces about as much as I like the silly "are you sure you want to quit" prompts, i.e. a fair amount.

**Comment by bsmanny** [comment]
RE: Parts for faces. Lot's of them. Eyes, noses, mouths, heads, hairs, clothes, bgs.

nozmajner - I would like to take this project on. I just need direction. is facegen required (using parts) or can individual png files be used? what file format do the parts need to be in? I am a total noob - but willing to contribute - and this is the holy grail!

**Comment by impaktor** [comment]
@bsmanny Do you have any samples to share?

**Comment by nozmajner** [comment]
@bsmanny Nice, you are welcome to have a go on it! :) Come by on IRC, to discuss it further. (I'm usually up there in the evening CET). I'd also ping @ecraven here, to ask if he had anything in mind for the newnew UI regarding faces.
The preferred way is to have cartoon faces, not butchered photos.
I'd prefer the part approach, because it can offer more variety than individual portraits, and easier to expand on it. 
I think the system is flexible enough to make it possible to have very varied faces, like very different silhohuettes and proportions. You just have to treat them as separate races, if part positions are too different.
One bottleneck could be that face parts are placed on specific coordinates, but maybe we can nudge the others to change that to use full size images too, so you can decide where eyes and other parts should go.

Image format is png with transparency. Image size could go up at least to the double of what we have right now. Maybe even 4 times in source files, so we are somewhat future proof in that regard.

**Comment by ecraven** [comment]
> Image format is png with transparency. Image size could go up at least
> to the double of what we have right now. Maybe even 4 times in source
> files, so we are somewhat future proof in that regard.

Just to throw it out there, maybe we could discuss SVGs that are
automatically rendered at the correct resolution for the current device?
Like we do with the icons now? I'm not a graphics artist but as a
programmer it would be nice to move away from the pixel formats (for
purely technical reasons).

Though we'd have to test how well things like gradients are rendered by
nanosvg..

**Comment by bsmanny** [comment]
![space port female](https://user-images.githubusercontent.com/29179346/26953581-0c0a933e-4c60-11e7-96f6-4a2cf9e08adf.png)

she could be a tranny (lol) - but this is just something quickly created using make human. I have been searching all the discussions related to facegen - and have gotten myself smarter on what needs to be done. Develop all the assets so they can be randomized using existing shell. What I need is someone to help me map out the total requirement before I start creating all the assets: 1) how many races and what are they?, 2) how many females and male combinations of each?, 3) how many different roles: e.g. passenger, police, trader, etc, 4) desired image size, 5) backgrounds for each component. would be very helpful for someone to provide me a folder of all the existing png images to look at. not smart enough on move away from pixel format - but open to learn. I would like to define need - and then proceed to building everything once the development/programming team agree on what exactly is needed. I have formal education in graphic design - but changed career field to business to pay the bills - so its 20 years not current. am bit of a geek - but quick learner - and excited about the potential - so thats what i offer.

**Comment by bsmanny** [comment]
@nozmajner I am California - PST - so its gonna be tough to connect. @ecraven standing by for your input/ direction. RE: " if he had anything in mind for the newnew UI regarding faces."

**Comment by bsmanny** [comment]
RE: There's like 700 files in the facegen dir currently, which is a lot even when you account for a little bit of redundancy. It really comes down to the amount of work needed, nothing else.

@nozmajner there's a quote i like to live by: "the difficult we do immediately, the impossible only takes a little longer ;^}

**Comment by bsmanny** [comment]
..and yes - modeling space ships - and planets - and docking stations - is sexier.... but those faces need some major plastic surgery! ;^}

**Comment by bsmanny** [comment]
is the requirement to what i should develop all the assets for ?? - or is there is a change in direction? thx.

https://github.com/pioneerspacesim/pioneer/blob/480a59ef2608b8cadd161abbd9a65b8263417332/data/facegen/readme.txt

**Comment by Tichy** [comment]
IMHO, 3D generated faces if not done in some cartoonish style (eg. with cel shading) or extremely realistic, are at very high risk of going straight in the uncanny valley. http://www.gamesindustry.biz/articles/2013-05-01-the-psychology-of-the-uncanny-valley

**Comment by impaktor** [comment]
@bsmanny You should be able to find us on IRC between 23:00 - 15:00 in your local time. (I see you came by earlier this morning (my time), was 01:00 am here.

Either way, communication might best be done through our dev forum, but you need to come by IRC for us to give you an account.

and that readme is quite recent (by pioneer standards) and hails from the most recent re-write, so it should be accurate. 

For quantity, I think we were thinking that minimum would be about 10 distinctly different versions of each kind of face part, then one could inflate that number through some minor variations, like mirror, and change pigmentation, hair/eye color.

**Comment by ecraven** [comment]
> and that readme is quite recent (by pioneer standards) and hails from the most recent re-write, so it should be accurate. 

Also, the pixel sizes should definitely be increased by quite a lot. If
the faces are rendered, it would be good to include the sources with
pioneer-assets, so that we can later re-create them at a higher
resolution, if needed :)

**Comment by nozmajner** [comment]
Hmm, I'm still not a fan of the 3D and/or realistic approach. It lacks character, and I suspect it will go stale very quickly.

**Comment by fluffyfreak** [comment]
Stylised is cheaper to create/maintain, easier to match the pieces so we get variation etc and it avoids looking dated so quickly.

So my personal preference is 2D stylised in some way.

**Comment by bsmanny** [comment]
if the preference is for 2d - i can just as easily support. I would suggest though that 3d/realistic for the characters would be visually aligned with the 3d design/style of the rest of the game/sim. There are no other old school - 2d textures/models that I can recall seeing. Completely understand the reluctance to use 3d - but with adherence to standard deviation for facial components/head size/clothing - classic stylization - can work. Perhaps a middle ground between 2d/3d - ultra realistic/cartoon would be the sweet spot?

**Comment by bsmanny** [comment]
it might be helpful for the team to provide me some examples of the "ideal" style (from any other source/game/sim out there)

**Comment by nozmajner** [comment]
Nah, the ships aren't that realistic visually. And never will be. And 2D != Old school in my opinion.
I'll paint up how I imagine the faces in the weekend.

**Comment by bsmanny** [comment]
I chatted with impaktor earlier today. If the team is for continuing on with evarchart's design/files - I can pick up from there.

**Comment by bsmanny** [comment]
ok - so in between the house remodel and my day job - I spent my time on learning the history by reviewing threads / doing google searches - going back as far as 2011. Ive also been building myself a library of visual ideas as well. @nozmajner i am still interested in seeing what your vision based on some comments/ideas you had prior to everchart.

**Comment by nozmajner** [comment]
Something along these lines:
![](http://68.media.tumblr.com/0774d3ee99c3d6f803499df4aa0f43fd/tumblr_oliy9yry3P1tzk1xao2_1280.png)
![](http://68.media.tumblr.com/e9c3c272879ed5368110480066ed23cd/tumblr_o1vfz6Feiy1rntbxmo1_1280.jpg)

**Comment by bsmanny** [comment]
interesting ....visually reminds me of team fortress - oxenfree - team fortress

![oxenfree](https://user-images.githubusercontent.com/29179346/27210988-1fa3778e-520b-11e7-82ce-64af6be208b9.png)
![broken age](https://user-images.githubusercontent.com/29179346/27210992-24cf0700-520b-11e7-9cb5-6aa9d700af03.png)
![team fortress 2](https://user-images.githubusercontent.com/29179346/27210996-2c854b44-520b-11e7-88c4-e8a1ab08f6df.png)
