### ISSUE TITLE
Burning into a crisp near the sun could be improved.

### ISSUE THREAD

**Issue by alugarius** [pioneerspacesim/pioneer#3963]
using the Hull temperature instead of crashing into a sun?

**Comment by alugarius** [comment]
Bump?

**Comment by impaktor** [comment]
As you can see, we have 296 open issues to address, and very very very very little free time. If this is something you feel passionate about, then feel free to submitt code to this effect.

**Comment by impaktor** [comment]
duplicate of #1336, closing
