### ISSUE TITLE
Game is considered to be frozen during startup by GNOME

### ISSUE THREAD

**Issue by LuccoJ** [pioneerspacesim/pioneer#3965]
This affects the March 2017 build and also all the ones I tried before that one (I used to put it down to a slow computer, but I just upgraded it), under Debian Stretch (testing).

![Pioneer hanging dialog at startup](https://cloud.githubusercontent.com/assets/1684791/24710263/e9a293b6-1a1c-11e7-9141-b3231ac409a9.png)

I assume Pioneer fails to [send some keepalive data](http://unix.stackexchange.com/questions/131434/how-to-detect-a-desktop-application-hanging) informing its environment it is still responsive during the startup phase, and this may trigger the behavior selectively under GNOME and maybe not some other environment due to a particularly short timeout value set by default, which is [not changeable at runtime](http://askubuntu.com/questions/412917/how-to-increase-waiting-time-for-non-responding-programs).

I have been informed Windows also sometimes detects Pioneer as frozen when switching away from its window by using Alt+Tab, though that might be a different issue (doesn't seem to occur in GNOME).

**Comment by laarmen** [comment]
I can confirm.

**Comment by ecraven** [comment]
> I can confirm.

Pioneer actually *is* unresponsive, it is running only one thread which
does the initialization, even the gui is only updated in between the
init steps (about once every few seconds).

This could be fixed, but would probably mean putting the rendering into
its own thread.

**Comment by fluffyfreak** [comment]
Alternatively thread the loading and keep the rendering on the main thread. That's the approach I would prefer. I have tried to move rendering onto a separate thread, and thread the loading workload but Pioneer just was NOT written with any of that in mind and it is ugly :(

**Comment by ecraven** [comment]
> Alternatively thread the loading and keep the rendering on the main
> thread. That's the approach I would prefer. I have tried to move
> rendering onto a separate thread, and thread the loading workload but
> Pioneer just was NOT written with any of that in mind and it is ugly
> :(

Ah, Sorry, of course that is the better idea, I didn't mean to suggest
moving rendering away, just that we'd need to have two separate threads.

What makes this a bit harder is that initializing lua is interleaved
with using lua for rendering, so things are not as simple as they could
be :-/

**Comment by impaktor** [comment]
Going to take a guess this is no longer an issue, 5 years later, I can't remember seeing anyone complaining about this the last few years.
