### ISSUE TITLE
Auto pilot eratic/unreliable

### ISSUE THREAD

**Issue by nostrebor66** [pioneerspacesim/pioneer#3972]
Auto pilot having problems docking with orbiting stations around 75% of the time , and ground stations around 10% of attempts . Not docking or crashing into station or port .

This is only issue found so thanks to all the developers for the hard work

Linux 64 20170304
Linux Mint 18.1
Amd fx4 
Gtx760
16 Gig ram

**Comment by nozmajner** [comment]
It should be fixed in the next release. The fix is already merged, but not sure when the new build will happen. At least for the issue with the orbitals.

Could you elaborate on the crashing into the station part? Do you have a save where it happens?

**Comment by impaktor** [comment]
I think we should maybe ask @robn (ping) for a build now?

**Comment by nostrebor66** [comment]
Sorry no save it appears to happen randomly , auto pilot just appears to fly into the side of a station or on the odd occasion it will fly into the starport or ground .

**Comment by nozmajner** [comment]
@nostrebor66 What ship you have? How much cargo?
I'm asking that most ships have quite weak retro thrusters, and that could cause issues with the autopilot, if you are overloaded. Since it approaches heads down before using the belly thrusters.

**Comment by nostrebor66** [comment]
Started with default ship from earth had problem with it . then after making some money moved to a Moa Moa , load wise it can happen with only a tank of fuel and a package or two on board , the Moa Moa is worse for auto pilot error than start ship .
It happens if you use the crew order as well , crew with 100% experience in piloting .

**Comment by impaktor** [comment]
Could you please download and try the latest release. The bug should be fixed there. Report back here if you still experience strange behaviour.

**Comment by nostrebor66** [comment]
Have downloaded latest and have tested a bit in the Sol system as requested

![screenshot from 2017-04-16 15-36-50](https://cloud.githubusercontent.com/assets/27512522/25087183/fe53987c-2364-11e7-9021-98200a3b4e38.png)


Testing latest version of Pioneer
20170415-Linux

Sol system test

Still unable to dock at Torvalds Platform (as was the case with 20170304)
Docking granted OK but will not dock

Autopilot has crashed into two stations so far 

having a new problem with game crashing with following error

[string "[T] @modules/PolicePatrol/PolicePatrol.lua"]:47: attempt to get length of upvalue 'patrol' {a nil value}
stack traceback:
[string "[T] @modules/PolicePatrol/PolicePatrol.lua"]:47: in function 'cb'
[string "[T] @libs/Event.lua"]:34: in function '?'
[string "[T] @libs/Event.lua"]:185: in function <[string "[T] @libs/Event.lua"]:180>

when travelling to following stations
Daniels Haven
Poseidon Station
Oasis City

Distance from destination varies from

0.40AU - 2.42AU

no other ships in area and no proximity alerts


Departure points tried include

Mars High
Thebes Gas Refinery
Clarks Station

Ships Tested include 
Sinonatrix
Bowfin
Mola Mola
Pumpkinseed

Have tried a Clean restart from Earth (in case of a glitch in earlier save)
still have  problems at Torvalds Platform and game crash with error message

Hope this is of help and Thanks for reply

**Comment by nostrebor66** [comment]
Stupid me have got rid of problems ,can dock at Torvalds and error seems ok now .

Did a restart on comp and it seems to have sorted out the glitch .

Autopilot still flew into Earth rather than go the long way round hohum technology eh .

Again a big thanks to you guys for helping out , and for all the work on this project .

Maybe I will fire up blender and see what happens .

**Comment by impaktor** [comment]
The only thing I can think of that would "sort out the glitch" is if you we're playing an older version of pioneer before, when you had the bug, and if you are first now playing the April version, which includes a bug fix for the bad auto pilot.

It's not like pioneer "installs" itself and nestles it's way all over your computer like other windows programs can do. It's just sitting in a folder, self contained.

**Comment by nostrebor66** [comment]
I had deleted the 20170403 build before I unpacked the 20170415 build , only thing I did was shutdown and restart my comp . 
Will try to get a few more hours of testing in and let you know what happens .

thanks again for the help

**Comment by pcercuei** [comment]
I noticed that when I'm travelling to a remote planet my reserve of hydrogen goes down slowly; I believe because the auto-pilot corrects its trajectory to compensate for the movement of the planet.

Could we maybe have an option to buy a smarter (and expensive) auto-pilot, that would calculate the position of the planet at time of arrival, and use that?

**Comment by nozmajner** [comment]
As a workaround you could goto the parent body until you get reasonably close, then switch over to your destination.

**Comment by laarmen** [comment]
The upgraded autopilot would be a nice touch indeed.

**Comment by ecraven** [comment]
> The upgraded autopilot would be a nice touch indeed.

I want to show distance at closest approach in the ui, to calculate
that, I'd need to find the point the autopilot should aim for. Maybe
when we do that, we can fix / upgrade the autopilot ;)

**Comment by nostrebor66** [comment]
Sorry for not being around life and health problems but hey ho ,
have had no further issues with autopilot accidents .
I have also noticed fuel use on longer in system travel just asumed that it was course addjustments taking place inflight .

**Comment by nozmajner** [comment]
It's that and the lateral thrusters are less efficient then the mains, so they gobble up propellant faster. I had some very stressfull SAR missions recently because of that, where I had to tweak orbits for weeks in-gabe because of the autopilot botching the transfer.

**Comment by impaktor** [comment]
> have had no further issues with autopilot accidents .

FIxed, closing.
