### ISSUE TITLE
Crash - exact same time each reload

### ISSUE THREAD

**Issue by nozmajner** [pioneerspacesim/pioneer#3996]
### Observed behaviour
Current master ([9c8c112](https://github.com/pioneerspacesim/pioneer/commit/9c8c11276eaa10b7db020790093798ce150143c2)) crashes sometimes. It seems random, sometimes I can play for 10-20 minutes, sometimes it happens after a few minutes. Sometimes it only happens if you jump out to another system.
And if it happens, it will happen the exact same time, if you load back the save you did before the crash.
Win7 64bit, Decent nVidia GPU. Latest thirdparty, building with VS2015. No mods.

![crash_tradeship](https://cloud.githubusercontent.com/assets/4182678/25545819/b67f6b7a-2c60-11e7-9d27-755507a33792.png)

### Steps to reproduce
[Here's a save that should crash](https://www.dropbox.com/s/ni0itw54eqgcy6s/_quicksave_crash?dl=0) at 14:17:07 Jan 1. Just time accelerate and let the autopilot fly to Ceres (the already issued command). The crash happens exactly the same time, down to the second, if you just enable time acceleration. It differs a little if you alter the course to somewhere else, or force time acceleration.

I tried jumping to Epsilon Eridani - no crash there.
If I jump back to Sol, it crashes again, but at different times each time.

I tried removing the Tradeships.lua module. This only postponed the crash, and the crash also happens around the same time, but with little differences in this case, especially with forced time accel (around 06:25 Jan3).

If I remove the Tradeships.lua, jump out and jumped back, then the crash doesn't happen.
(I issued a goto to Ceres at each try for consistency)

Also tried removing every modul that would generate a ship, but that made no difference.

Output.txt seem to end on different stuff each time, and no error message.

I tried watching the other ships from the orbital map, but didn't saw anything out of ordinary. One ships achieving escape velocity seem to coincide, (PI-5143), but I guess that's just coincidence.

**Comment by ecraven** [comment]
just tried, successfully arrived. might be a windows/vc problem?

**Comment by fluffyfreak** [comment]
Got it, debugging it. Think I've seen this before.
