### ISSUE TITLE
Collision at the orbital gates (landing collision damages ship)

### ISSUE THREAD

**Issue by nozmajner** [pioneerspacesim/pioneer#3997]
### Observed behaviour
On current master ([9c8c112](https://github.com/pioneerspacesim/pioneer/commit/9c8c11276eaa10b7db020790093798ce150143c2)) orbital station and ground station docking collision meshes also do damage to the ship. 
That might be expected from a hard landing to a ground station, but collision sounds even play if you drop from a cm or so above the pad. And you also get damaged when you are flying trough the gates of the orbitals.

### Steps to reproduce
Ask for docking permission and fly into the station. Without permission you will fly trough unharmed, with permission you get damage (based on your speed, as in any other collision). It happens with the autopilot too, but that slows down the ship upon docking, so it's not that noticable. But try flying trough fast:
![stationcollision](https://cloud.githubusercontent.com/assets/4182678/25546953/7c39852c-2c65-11e7-913e-e94707398968.gif)
(Cropped awkwardly, because I wanted to show the hull gauge appearing. I'm flying towards the center of the hole, no collision is happening to the station itself)

Doesn't happen on the current release (2017-0415).
Maybe the [37aac98](https://github.com/pioneerspacesim/pioneer-thirdparty/commit/37aac98f00ed634739ccc464284e2fcbd07924e0) libassimp update on Thirdparty?

My rig is Win7 64 bit, builded with VS2015.

**Comment by fluffyfreak** [comment]
Might be related too #3953

**Comment by fluffyfreak** [comment]
Also awesome use of video 👍

**Comment by mike-f1** [comment]
@fluffyfreak: You guess correctly :/
