### ISSUE TITLE
Azimuthal radar over planar

### ISSUE THREAD

**Issue by nozmajner** [pioneerspacesim/pioneer#4001]
The new azimuthal radar shows up on top of the planar one, if you start a new game, switch it to azimuthal, exit to the main menu and start a new game again. If you rightmouse on it and select either, the other will disapear.
![radar](https://cloud.githubusercontent.com/assets/4182678/25559160/4394b76a-2d36-11e7-9368-362ab20d993e.png)

**Comment by ecraven** [comment]
My fault, I need to initialize the UI correctly on restarting a game, I only ever tested with starting a completely new game. I'll fix it asap.

**Comment by ecraven** [comment]
Should be fixed by 5bd61e4
