### ISSUE TITLE
Ghost pointer

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#4003]
### Observed behaviour
When piloting ship with left mouse button down, it remains active in its hidden state and doing all kinds of shenanigans.

### Expected behaviour
Mouse pointer doesn't click things or move when holding down right button to navigate

### Steps to reproduce
Be in flight, place cursor close to, say F4 button, and fly so it hides, then when you guestimate it's over/under f4 button, shoot, i.e. left click. It can open both C and Lua cpanel-menues 

__My pioneer version (and OS):__ e427dac4e8a7d64307ccdfc7cc76a4de97f675f8

**Comment by ecraven** [comment]
This seems to be behaviour present even in pre-imgui pioneer. We will need to find a good way to disable the mouse when MMB/RMB is held :-/

**Comment by Web-eWorks** [comment]
Fixed by #4842.
