### ISSUE TITLE
Cannot save game

### ISSUE THREAD

**Issue by robothauler** [pioneerspacesim/pioneer#4013]
Game stops with a segmentation fault when saving.

This is the gdb output:
Thread 1 "pioneer" received signal SIGSEGV, Segmentation fault.
ShipCpanel::SaveToJson (this=<optimized out>, jsonObj=...) at ShipCpanel.cpp:271
271             shipCPanelObj["cam_button_state"] = m_camButton->GetState();

**Comment by nozmajner** [comment]
Could you specify the version? Or it's current master? What OS you are on?

**Comment by robothauler** [comment]
Ups, sorry. It's the current master. OS is a debian gnu linux.

**Comment by fluffyfreak** [comment]
Found it, uninitialised pointer to a removed object from #4009 

Fix incoming shortly 😄
