### ISSUE TITLE
Crash when jump to Gliese 783

### ISSUE THREAD

**Issue by robothauler** [pioneerspacesim/pioneer#4019]
### Observed behaviour
Crash when jump to Gliese 783 B
Output:
error: [string "[T] @pigui/game.lua"]:674: invalid order function for sorting
stack traceback:
        [C]: in function 'sort'
        [string "[T] @pigui/game.lua"]:674: in function 'displayOnScreenObjects'
        [string "[T] @pigui/game.lua"]:746: in function 'fun'
        [string "[T] @pigui/pigui.lua"]:42: in function 'window'
        [string "[T] @pigui/game.lua"]:739: in function 'fun'
        [string "[T] @pigui/pigui.lua"]:71: in function 'withStyleColors'
        [string "[T] @pigui/game.lua"]:738: in function 'game'
        [string "[T] @pigui/pigui.lua"]:83: in function <[string "[T] @pigui/pigui.lua"]:81>

### Steps to reproduce
Start at Earth
Jump to Gliese 783 B

__My pioneer version (and OS):__
pioneer git (363e44165)
Debian 9.0 x86_64

**Comment by fluffyfreak** [comment]
Can confirm, I just managed to repro it, works fine if you jump to `Gliese 783 A` but crashes if you jump to `Gliese 783 B`

**Comment by fluffyfreak** [comment]
@ecraven the offending block of code seems to be

>	for k,v in pairs(onscreen) do
>
>		table.sort(v.others, function(a,b) return a.body:IsMoreImportantThan(b.body) end)
>
>		local coords = v.mainBody.screenCoordinates
>
>		ui.addIcon(coords, getBodyIcon(v.mainBody.body), colors.frame, iconsize, ui.anchor.center, ui.anchor.center)`

**Comment by fluffyfreak** [comment]
Fixed by #4024
