### ISSUE TITLE
Crash after Hyperspace travel : attempt to index upvalue 'l' (a nil value)

### ISSUE THREAD

**Issue by Warlkiry** [pioneerspacesim/pioneer#4022]
### Observed behaviour
When traveling to Edessio system (last time)
Did it twice while traveling from Phiack to Waveda system (3rd time worked fine)

Error in the terminal:
error: [string "[T] @modules/PolicePatrol/PolicePatrol.lua"]:22: attempt to index upvalue 'l' (a nil value)
stack traceback: [string "[T] @modules/PolicePatrol/PolicePatrol.lua"]:22: in function 'getNumberOfFlavours' [string "[T] @modules/PolicePatrol/PolicePatrol.lua"]:107: in function 'cb' [string "[T] @libs/Event.lua"]:34: in function '?' [string "[T] @libs/Event.lua"]:185: in function <[string "[T] @libs/Event.lua"]:180>

### Steps to reproduce
Hyperspace traveling from Phiack to Waveda (randomely happends)

__My pioneer version (and OS):__
pioneer 20170415 (41a0f4c)
Linux R2D2 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux

sorry for bad english

**Comment by impaktor** [comment]
@robothauler ping.

**Comment by robothauler** [comment]
It seems the language files are missing.
data/lang/module-policepatrol/ contains only en.json

**Comment by robothauler** [comment]
@Warlkiry could you please temporary switch to english language and try again?

**Comment by impaktor** [comment]
Oops. So this falls on me, it seems. 

(I thought I added a new module to transifex not too long ago?)
