### ISSUE TITLE
Misplaced target ship icon in external view?

### ISSUE THREAD

**Issue by Tichy** [pioneerspacesim/pioneer#4028]
### Observed behaviour

When I select a ship as a target and change my view to one of the externals, the ship icon is moved off the ship.

### Expected behaviour

I expect the icon to be on the ship, as it happens in the internal view.

### Steps to reproduce

Select a target ship, change to external view. Rotate it, zoom in and out...

__My pioneer version (and OS):__

Pioneer compiled from git through AUR package in Archlinux.

![screenshot-20170619-141532](https://user-images.githubusercontent.com/2348771/27285366-d4231c34-54fc-11e7-998f-860741071e8b.png)
![screenshot-20170619-141539](https://user-images.githubusercontent.com/2348771/27285373-d60c2b3a-54fc-11e7-817b-5ee9f09cb064.png)
![screenshot-20170619-141543](https://user-images.githubusercontent.com/2348771/27285377-d73ea168-54fc-11e7-9509-3e7bab450128.png)

**Comment by ecraven** [comment]
I'll fix this, just to note the probable cause: I use the ship position to calculate where to show the markers, but I should use the camera position instead...
