### ISSUE TITLE
Cities spawned on top of each other

### ISSUE THREAD

**Issue by nozmajner** [pioneerspacesim/pioneer#4034]
### Observed behaviour
Two cities spawned almost on top of each other in Hoa system (-1, -5, -3), Byers Claim: Boyle Village and Shao City:
![closecity](https://user-images.githubusercontent.com/4182678/27517914-a68f69bc-59d4-11e7-92a1-d3c0d6b1b3ab.png)
![closecity2](https://user-images.githubusercontent.com/4182678/27517915-a7a964e2-59d4-11e7-886f-71d959a12189.png)
There's no mention of repositioned city due to unsuitable terrain in the output.txt

It's problematic because buildings spawn very close to the docks, blocking some of them. (I was able to land though.)
 I guess it's mostly a problem on smaller bodies and lot's of cities. This one, Byers Claim has four cities and 0.13 Earth radii.

There could be a minimum distance between cities to avoid this.

__My pioneer version (and OS):__
Win7 54bit. Master (can't remember the commit number, it's from 2017 june 22 or so)

**Comment by fluffyfreak** [comment]
Doh
