### ISSUE TITLE
Buying Ship Breaks Game

### ISSUE THREAD

**Issue by thomasscottterry121** [pioneerspacesim/pioneer#4041]
### Observed behaviour
After Selling my first ship on earth and buying the lunar shuttle i could not controll the spaceship at all, the only things that could be done were buying fuel and using menus. 

When compiling i did not have any compile warnings or errors.

### Expected behaviour
The ship should have been flyable

### Steps to reproduce
Compile a new version of the current commit and click the earth start. Then use the money cheat to give yourself extra money and buy a ship. Then undock and try to take off. This happened as well when i tested it by giving myself extra money through the console and buying any ship.

[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/1116344/opengl.txt)
[output.txt](https://github.com/pioneerspacesim/pioneer/files/1116343/output.txt)

One thing i might have done wrong was doing a multi-thread build. i am trying again with single thread.

__My pioneer version (and OS):__
Lubuntu Yakkety new install
Pioneer commit 8e1aa996bbf0e27ab074ee4df611ccc753ed0415
I compiled it normally with the required programs

**Comment by thomasscottterry121** [comment]
The problem was fixed by recompiling in single thread mode with one job. Apparently more than one thread in make breaks the compilation of the program.

**Comment by thomasscottterry121** [comment]
It would be good if someone else would confirm that this happens

**Comment by ecraven** [comment]
I regularly compile with `make -j8`, very seldom have there been any
problems. Someone mentioned CMake a short time ago, maybe we should have
another look into using that (no idea how well it plays with VS, it
would be nice to not have to maintain two build systems, as we do at the
moment).

**Comment by laarmen** [comment]
It plays quite nicely with VS 2017 (native support from the Visual side, no
less), less so with the 2015 version.

**Comment by thomasscottterry121** [comment]
I was trying it on the linux side instead of from windows so VS 2015 wont work, but I haven't tried doing it with -j8.

**Comment by thomasscottterry121** [comment]
Looking into it further, the problem seems to be that the money cheat import("Game").player:SetMoney(amount) makes it so that if you buy a ship with that money you can't fly it. It turns out it had nothing to do with the number of make jobs.

**Comment by fluffyfreak** [comment]
Using `import("Game").player:SetShipType("lunarshuttle")` it seems like the lunar shuttle collides with the deck somehow. the Setmoney thing is a red herring

**Comment by fluffyfreak** [comment]
Using the dropdown and:
> model = import('Game').player.model
> model:SetDebugFlags({"BBOX","COLLMESH", "TAGS"})

@nozmajner It looks like the collmesh might have static geometry that protrudes below landing gear, and that might be throwing off the bounding box size and other collision info. Once the ship is launched it's collision testing turns on and it is already colliding with the station because of the enlarged bounding box and protruding antenna things.

Simplest fix would be to remove the bottom antenna from the collision mesh. It won't make much, if any, difference in combat etc.

**Comment by nozmajner** [comment]
It doesn't happen to me, I can land and take off with the Lunar Shuttle, either if it's cheated, or bought with the money cheat.
I'll do the changes anyhow, just to be safe.

**Comment by fluffyfreak** [comment]
This still needs more investigation. Merging #4044 only partially fixes the issue.

**Comment by Web-eWorks** [comment]
![Screenshot from 2020-07-06 23-51-32](https://user-images.githubusercontent.com/4218491/86705294-bac25200-bfe3-11ea-9938-28c16dc6bc22.png)
![Screenshot from 2020-07-06 23-51-23](https://user-images.githubusercontent.com/4218491/86705297-bbf37f00-bfe3-11ea-97b2-7ec4750d8970.png)

As you can see, the LunarShuttle seems to have a weird 'spike' underneath the ship. I've not personally had any issues taking off, but this might explain it.

**Comment by WKFO** [comment]
That spike is to imitate landing gear contact as far as I know, so that the ship registers as landed before it's main hull touches the ground. Quite a few ships have it.

**Comment by nozmajner** [comment]
Yes, that's the reason for it. Not sure if its needed still, since we have landing tags now. I'll check.

**Comment by Web-eWorks** [comment]
Going to close this issue; pretty sure we haven't had it recur in the three years since it was opened.
