### ISSUE TITLE
Corrupted, invalid values for navigation to far bodies shown in UI.

### ISSUE THREAD

**Issue by fluffyfreak** [pioneerspacesim/pioneer#4048]
### Observed behaviour
As reported by Atom via IRC.
![bug2](https://user-images.githubusercontent.com/825083/27954996-6b0c5cb2-630a-11e7-91a2-77b67623d444.png)

### Expected behaviour
~~The values should not get completely nonsensical!~~
It turns out that the values reported are **CORRECT**.
Upon approaching the Phobos station you seem to get teleported/flung out of the system at alarming velocity.

### Steps to reproduce
https://dl.dropboxusercontent.com/u/8608538/Desktop%2007.06.2017%20-%2020.51.14.02.mp4

Locally built, Visual Studio 2015, win10, 32-bit release.

**Comment by impaktor** [comment]
Should have been closed by 4108 above...
