### ISSUE TITLE
Ship's cargo definition too long to display

### ISSUE THREAD

**Issue by Marcel-T** [pioneerspacesim/pioneer#4052]
Running 20170415-linux 64 at 1360x768. The description 'Containerized living units' doesn't quite fit. I assume the quantity column needs to be moved to the right a few spaces.
![screenshot from 2017-07-16 21-30-35](https://user-images.githubusercontent.com/730819/28255774-2fa6e530-6a70-11e7-8c02-fa1970b81874.png)

**Comment by impaktor** [comment]
Thanks. This whole UI will go, and be replaced by something better soonish (we hope), so a fix for this would be slightly temporary, as I/we hope it will all be thrown out by a new UI soon*.

_*as measured in pioneer time scale_

**Comment by Marcel-T** [comment]
Late reply because it's of little importance. I'd read about the new UI. Consider it a note to watch the length of strings in the new one. :smile: And feel free to close this issue.
