### ISSUE TITLE
Crash on exit (X_GLXDestroyContext)

### ISSUE THREAD

**Issue by ecraven** [pioneerspacesim/pioneer#4058]
I get this when pioneer exits:
````
  X Error of failed request:  GLXBadContext
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  4 (X_GLXDestroyContext)
  Serial number of failed request:  13533
  Current serial number in output stream:  13533
````

**Comment by impaktor** [comment]
...and #4057 fixes this, I assume.

**Comment by ecraven** [comment]
for me, this is fixed by #4057.

**Comment by impaktor** [comment]
Should be fixed now then.

**Comment by fluffyfreak** [comment]
@impaktor Yeah, sorry I'm not getting much time to comment/IRC at moment.
Started new job in an office and I'm sat in with the producers and CTO!
No sneaky IRC sessions for me right now.
