### ISSUE TITLE
Click-through causes incorrect selection with new UI

### ISSUE THREAD

**Issue by radcapricorn** [pioneerspacesim/pioneer#4063]
### Observed behaviour
Selecting a target from the new UI dropdown effectively selects another target if it's "under" the popup.

### Expected behaviour
Clicks should not pass through, clicking a target in the popup should select it, and not another one underneath. This will make manual travelling with time compression easier, as player won't have to drop time compression every time popup selection fails, to go through system map to select the correct target.

### Steps to reproduce
1. Start at Earth, look left and up until you see Elara, Jupiter and Jobs Pad icons.
2. Click on Elara or Jupiter, a popup will appear.
3. Click on "Jupiter" or "Adrastea" in the popup.
4. Jobs Pad will be selected, instead of the choice made in the popup.

__My pioneer version (and OS):__
Linux 64-bit
3b14961362d7df2e6e04e5b07f259ef8a5b5ae87

**Comment by ecraven** [comment]
This is something we need to think of all the time, I hope I fixed all current problems, but I'll need to think about it for the rest of the UI too ;)
