### ISSUE TITLE
Both radar modes are shown at the same time

### ISSUE THREAD

**Issue by radcapricorn** [pioneerspacesim/pioneer#4064]
### Observed behaviour
When "2D azimuthal projection" mode is selected for radar, disabling and enabling the radar results in both radar modes drawn.

### Expected behaviour
Only the last selected radar mode should be visible.

### Steps to reproduce
1. Start the game in any starting point.
2. Right-click the radar and switch to "2D azimuthal projection".
3. In the top menu, click on "Scanner" to disable the radar.
4. Click the same button (now "Equpment") again to enable the radar.
5. Both the original and the new radars are now displayed.

__My pioneer version (and OS):__
Linux 64-bit.
3b14961362d7df2e6e04e5b07f259ef8a5b5ae87

**Comment by impaktor** [comment]
Let me just take this opportunity, and mention that today is @ecraven's one year anniversary since he first logged into #pioneer, there's been really amazing progress since then!

No progress without some bugs.

**Comment by radcapricorn** [comment]
Congrats from me as well :) But I don't think this one in particular is "his", more likely it's legacy: the click-through existed in Pioneer since forever (e.g. clicking on buttons in the Sector Map would select systems, etc.).
