### ISSUE TITLE
Autopilot landing warnings

### ISSUE THREAD

**Issue by Brianetta** [pioneerspacesim/pioneer#407]
When the player selects a (station) target and instructs the autopilot to land there, the autopilot should perform the following checks:
- Measure gravity acceleration at surface
  - derived from mass of planet, radius of planet
- Compare the force that would be exerted on the current mass of the ship with that which could be exerted by the ventral thruster
- If the former is greater than the latter, refuse to operate, with a warning to the player.

The player has the following options:
- Ask it to land elsewhere
- Jettison some cargo
- Attempt to land manually

In the case of NPCs:
- Raise a Lua event or exception

A similar feature request could perhaps be made for comparing cross-section of the ship with the aperture of a space station.

**Comment by Web-eWorks** [comment]
This has already been implemented as of (at least) 2016. Closing!
