### ISSUE TITLE
Training missions available through the bulletin board

### ISSUE THREAD

**Issue by johnbartholomew** [pioneerspacesim/pioneer#408]
This is quite a broad feature request which would be implemented (I imagine) as a whole bunch of Lua scripts, with some extensions to the core being necessary too.

I'd like to see advertisements for training (of various sorts) on the bulletin board. For a small fee, a (semi-)retired trader/explorer will teach you the tricks of the trade. There are tons of things that could be taught like this as and when people want to spend time writing the scripts, but in particular I'd like to see BB adverts offering lessons on:
- Manual maneuvering and docking
- Orbital transfers and manual system navigation
- One-on-one combat techniques

I don't expect it to be possible to touch the combat training idea until combat is a lot more fleshed out, but the first two are maybe within reach already.

**Comment by WKFO** [comment]
@dataf3l There is this for now: https://pioneerwiki.com/wiki/How_to_fly_without_autopilot

**Comment by Web-eWorks** [comment]
Closing as unimplemented; feature requests and discussion should go on the [forum](https://pioneerspacesim.net/forum), as we use Github for tracking actively-developed features and issues with currently-implemented functionality.

If you'd like to re-open this, please instead open a new PR with an implementation of the proposed functionality, thank you!
