### ISSUE TITLE
macOS build failure due to ARFLAGS

### ISSUE THREAD

**Issue by ilovezfs** [pioneerspacesim/pioneer#4080]
```
Making install in miniz
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
Making install in jenkins
  CC       lookup3.o
  AR       libjenkins.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar: illegal option -- j
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
make[2]: *** [libjenkins.a] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
```

This is what happens if I remove
```
ENV["ARFLAGS"] = "cru"
```
from the Homebrew formula.

The comment in the formula says:
```
     # Remove as soon as possible
     # https://github.com/pioneerspacesim/pioneer/issues/3839
```
But https://github.com/pioneerspacesim/pioneer/issues/3839 is apparently closed (via https://github.com/pioneerspacesim/pioneer/pull/3987) and yet the problem remains.

https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/6489/version=sierra/console

**Comment by impaktor** [comment]
ping @salborrelli

**Comment by salborrelli** [comment]
@ilovezfs  Are you trying to build via Xcode or the makefile? If you are on a Mac, I suggest that you use Xcode for building the App.

@impaktor  A you know I am not the maintainer of the makefile and do not recommend using it because I suspect it is quite outdated.

**Comment by Philbywhizz** [comment]
Looks like OSX uses its own version of ar instead of GNU's version so the command lines are different. Working on a pull request that fixes this.
