### ISSUE TITLE
Crash when ordering to dock with a target colony

### ISSUE THREAD

**Issue by macksting** [pioneerspacesim/pioneer#4081]
### Observed behaviour
After hitting the launch button in a space station, while the ship was being taxied out, I ordered my crew members to sail for another colony. This caused a crash. (Mola Mola ship launching with self and two other crew from Morrison High en route to Maynardton in the Ackay system [-13, -13, -10]) 

### Expected behaviour
I guess I expected them to patiently wait for the opportunity to take control of the ship rather than flip-tables. (I like to think of it as a mutiny.)

### Steps to reproduce
stub; will see if I can reproduce. So far at least from the latest autosave it's pretty reliable, so maybe just hire a crew member and take a shot at it if I don't isolate it a bit first.

__My pioneer version (and OS):__
git (dc33002), lubuntu 16.04

### More data
__Terminal output__
```
Hyperspace departure cloud leaves frame Ackay b
UB-4378 enters frame Ackay c
UB-4378 enters frame West Colony
UB-4378 enters frame Morrison High
TradeShips: Removed 4 ships before serialization
error: [string "[T] @ui/InfoView/CrewRoster.lua"]:122: bad argument #1 to 'SetText' (string expected, got nil)
stack traceback:
	[C]: in function 'SetText'
	[string "[T] @ui/InfoView/CrewRoster.lua"]:122: in function <[string "[T] @ui/InfoView/CrewRoster.lua"]:118>
```

__Error message__
![undockerr](https://user-images.githubusercontent.com/29901471/29246537-f504ae82-7fb2-11e7-8b1d-94fe22c58f83.png)

**Comment by ecraven** [comment]
> error: [string "[T] @ui/InfoView/CrewRoster.lua"]:122: bad argument #1 to 'SetText' (string expected, got nil)
> stack traceback:
> 	[C]: in function 'SetText'
> 	[string "[T] @ui/InfoView/CrewRoster.lua"]:122: in function <[string "[T] @ui/InfoView/CrewRoster.lua"]:118>
> ```

Looks like there is a flight state (Game.player.flightState) that isn't in
- FLYING
- DOCKED
- LANDED
- JUMPING
- HYPERSPACE
- DOCKING
and that causes problems here. From looking at Ship.h, there's a state
UNDOCKING that isn't handled here.
