### ISSUE TITLE
Autopilot High Orbit around Ceres runs out of fuel

### ISSUE THREAD

**Issue by ecraven** [pioneerspacesim/pioneer#4088]
### Observed behaviour
Autopilot High Orbit around Ceres runs out of fuel
### Expected behaviour
Reach proper High Orbit around Ceres
### Steps to reproduce
Start at Earth, take off, target Ceres, tell AP to enter a high orbit.

Low and medium orbits work fine.

**Comment by impaktor** [comment]
I wonder if this still happens, after #4108 has been merged.

**Comment by macksting** [comment]
Managed to attain high orbit in git cc4fc0f on lubuntu 16.04 twice so far, no failures yet. First time it settled in at 28% fuel, second time at 29%.

**Comment by kennworl** [comment]
Well, I couldn't recreate either really.  I tried twice from Los Angeles, and once from New Hope and it managed high orbit with about 29% fuel left (25% from New Hope).  The only time there was an issue was when I was already in orbit and I forced x10000 time factor.  The ship did the twist, then the funky monkey, and finally ran out of fuel and threw itself backwards at 7km/s but all bets are off at that time speed.  I was using the standard August 2017 build (not my own).  Can this be replicated reliably?

**Comment by ecraven** [comment]
just tried again, seems to only happen if taking off from earth, then forcing max time acceleration. might be a problem with physics at that high a level, can we just ignore it?

**Comment by kennworl** [comment]
Well, thinking about it, x10000 time acceleration is almost 3hrs per sec.  Do you really want to try and get the PC to try and figure out that much physics when you are in orbit of something that small where your orbital adjustments would be significant?  I would seriously limit the forcing of time acceleration in close proximity to anything, to maybe x100 at most.  That would avoid this problem entirely and I think x10000 is a bit much for anything really.  If you want to compress travel time that much, it's time to think about in-system FTL.

I have tried from Earth to Ceres at max time acc, and while the results vary, nothing was normal.  Safe to say that the physics model does not cope with x10000.   But that's nothing.  Try setting the autopilot to orbit Metis (closest asteroid to Jupiter).  I'm about to log my very first issue.

**Comment by ecraven** [comment]
> Well, thinking about it, x10000 time acceleration is almost 3hrs per
> sec.  Do you really want to try and get the PC to try and figure out
> that much physics when you are in orbit of something that small where
> your orbital adjustments would be significant?  I would seriously
> limit the forcing of time acceleration in close proximity to anything,
> to maybe x100 at most.  That would avoid this problem entirely and I
> think x10000 is a bit much for anything really.  If you want to
> compress travel time that much, it's time to think about in-system
> FTL.

Well, given the kinds of differences in mass, this should not be a
problem at all. I've implement full n-body simulation that went way
faster than that, calculating in multiple-second timesteps, running at
days per actual second. But that's of course only the gravity
simulation, I haven't looked at the autopilot code enough to understand
it.

> I have tried from Earth to Ceres at max time acc, and while the
> results vary, nothing was normal.  Safe to say that the physics model
> does not cope with x10000.   But that's nothing.  Try setting the
> autopilot to orbit Metis (closest asteroid to Jupiter).  I'm about to
> log my very first issue.

Great, thanks for that! I think we'll have to investigate time
acceleration in general, to find out what makes sense and how to best
deal with it ;)

**Comment by kennworl** [comment]
In that case, can that be calculated ahead of time, and the displayed option of high orbit be removed before you send the autopilot on mission impossible, or can the autopilot be made to cope with this?

**Comment by jaj22** [comment]
Well, the orbit setup has been broken for a long time. The minimum frame radius (used for planets without moons) is a straight 4 x sbody radius, while the orbit specification is based on TerrainBody::GetPhysRadius, which is larger (includes terrain & atmosphere) but by a variable proportion. High orbits are set at 3.2x, so they're sometimes inside and sometimes outside the frame. I think GetPhysRadius was increased recently to work around terrain range issues, so that may be related.

A relatively easy fix would be to clamp the maximum orbit altitude to ~0.95x frame radius in the FlyAround setup function. I'll need to think about whether this has further consequences, but it should be reasonably safe.

**Comment by fluffyfreak** [comment]
alternatively could we extend the frame radius instead to ~1.05x of the high orbit?

**Comment by jaj22** [comment]
Yeah, this is a bit daft actually. The rotating frame size is already based on body->GetPhysRadius, so there's no reason why the non-rotating frame shouldn't too. If everything's based on the same value then we get relative sanity.

The autopilot will need a few tweaks anyway. It's currently doing its own +1km adjustment on top of GetPhysRadius, which is obsolete. There's also a silly theoretical issue with gravitational safety adjustments pushing the radius outside the frame.

**Comment by fluffyfreak** [comment]
This should be fixed by #4131
