### ISSUE TITLE
Game crashes if you instruct autopilot to enter orbit to a body with 0g gravity

### ISSUE THREAD

**Issue by nozmajner** [pioneerspacesim/pioneer#4095]
### Observed behaviour
If you instruct the autopilot to enter low orbit around any body that has 0.000m/s^2 gravity.

According to @Stan_Pancakes, it's a floating point exception (it didn't said that on windows):
> 0  CheckCollision (r=6403479.2363868402, endvel=<optimized out>, tpos=<synthetic pointer>..., pathdist=143420200833.03012, pathdir=<synthetic pointer>..., dBody=0x244bdd60)
    at ShipAICmd.cpp:664
1  AICmdFlyTo::TimeStepUpdate (this=0x2a3f1190) at ShipAICmd.cpp:820
2  0x0000000000563aba in AICommand::ProcessChild (this=0x307fdc20) at ShipAICmd.cpp:80
3  AICmdFlyAround::TimeStepUpdate (this=0x307fdc20) at ShipAICmd.cpp:1181
4  0x000000000054ef20 in Ship::AITimeStep (this=0x244bdd60, timeStep=timeStep@entry=0.166666672) at Ship-AI.cpp:36
5  0x000000000056d64f in PlayerShipController::StaticUpdate (this=0x244ad570, timeStep=0.166666672) at ShipController.cpp:178
6  0x0000000000558121 in Ship::StaticUpdate (this=this@entry=0x244bdd60, timeStep=timeStep@entry=0.166666672) at Ship.cpp:1051
7  0x0000000000523633 in Player::StaticUpdate (this=0x244bdd60, timeStep=0.166666672) at Player.cpp:274
8  0x000000000058acd8 in Space::TimeStep (this=0x217d20d0, step=step@entry=0.166666672) at Space.cpp:962
9  0x000000000045df23 in Game::TimeStep (this=0x217b9540, step=0.166666672) at Game.cpp:248
10 0x0000000000505e7f in Pi::MainLoop () at Pi.cpp:1414
11 0x0000000000507879 in Pi::Start () at Pi.cpp:1327
12 0x0000000000412a8c in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:130

### Steps to reproduce
Select any of the outer moons of Jupiter (above ), or the moons of Mars, and instruct the autopilot to enter low orbit. It might not crash right away, because first the autopilot takes off and leaves the planet, but it will, if you enable time acceleration. Fly to vicinity command works.

__My pioneer version (and OS):__
Master 858629b seems to be affected, also @ecraven's function branch. Might be there for quite a while now, I never used that function for minor planets for example.

**Comment by radcapricorn** [comment]
Possibly related to #4048

**Comment by nozmajner** [comment]
Edit: it doesn't happen on the previous release (2017-0416)
