### ISSUE TITLE
AI Ship falling down

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#4098]
### Observed behaviour
Parked AI ships failing to hyperspace

### Expected behaviour
1. that AI ships are able to jump to hyperspace (they should know to raise their wheels in time)
2. That player doesn't hear sounds meant for the AI player

### Steps to reproduce
Sit on landingpad of e.g. New Hope. Wait for an AI Ship to take off. Hear the warning sound for entering hyperspace with wheels down (bug number one), then see ship fall down, as it fails to jump (bug number 2).

### Origin
I strongly suspect #4074 and #4049 

__My pioneer version (and OS):__

**Comment by impaktor** [comment]
Possibly, @WKFO might want to have a look at this.

**Comment by WKFO** [comment]
Maybe we should tell the AI ships to gain some altitude before hyperspacing, not just because of this bug; because it is illegal too.

**Comment by WKFO** [comment]
About the warning sound we will have to use sth else than BodyMakeSound I think.

**Comment by impaktor** [comment]
or just add an if in the code checking that it's the player and not AI that is taking off?

**Comment by ecraven** [comment]
playsfx, maybe in luaengine. maybe just add an if for now?
