### ISSUE TITLE
Crew member pilot descends to 500m, then ascends to 15 km, repeats ad infinitum

### ISSUE THREAD

**Issue by macksting** [pioneerspacesim/pioneer#4100]
### Observed behaviour
My pilot will descend sharply to reach 500m above the target spaceport, then slowly rise a few meters per second until she achieves 15 km, then descend again. When I turn on manual piloting this ceases, and gravity takes its proper effect.

### Expected behaviour
She probably should either feather the ventral thrust to keep the descent slow, or just let the ship fall for a few moments before braking.

### Steps to reproduce
Well, it happens with great reliability at Pallier's Folly in Arar (-13, -9, -11), a planet with roughly three times Earth's mass. I'll try to reproduce later under other circumstances, including with autopilot and at a planet closer to Sol.
Edit: Might help to have bespoke thrusters.

__My pioneer version (and OS):__
git (858629b) on lubuntu 16.04

**Comment by radcapricorn** [comment]
It appears as though thruster upgrades (optimized, modified, bespoke) confuse the autopilot: it starts to have difficulty settling on a direction (especially noticeable with time compression), and during landing may start climbing instead of gently setting down.

**Comment by ecraven** [comment]
probably not taking the extra acceleration into account :/

**Comment by fluffyfreak** [comment]
yeah, my fault
