### ISSUE TITLE
Balloon planet with two stations in nearly the same orbit/period

### ISSUE THREAD

**Issue by macksting** [pioneerspacesim/pioneer#4105]
### Observed behaviour
I report this as a bug not in the interest of its removal, but with trepidation and sadness as it's a fascinating and borderline broken system I'd much rather add to the Things To See page.
Rivas's World (Urur C c, -14, -9, -8) has a tenuous helium atmosphere, a complex ecosystem, and an order of magnitude difference between its radius and its mass (0.069 or 0.074 Earth masses, 0.410 Earth radii). I theorize it has a vast, spongy interior kept inflated with helium. Despite this, it has a population of 1 billion people and several starports, in balmy 50 C "weather."
The bigger problem is that its nearest two space stations, Morales Station and Fields High, occupy nearly the same orbit and pass alarmingly close together. Screenshots will be included below. I once launched from one and crashed into the other. My screenshot-20170822-132622 shows Morales Station visible through the launch bay of Fields High at 2:37:15.

### Expected behaviour
Well, the mass to radius ratio's pretty weird, so I imagine that usually would match up better and imply a less hollow planet. Space stations that close together really ought to at least be at a LaGrange point, not freely orbiting and subject to wild perturbations. It's probably not intended behavior that they should pass so close.

### Steps to reproduce
Go to Urur (-14, -9, -8) C's third planet Rivas's World, and its orbital stations Morales Station and Fields High around 3204 dec 1, 02:31:57.

__My pioneer version (and OS):__
git (cc4fc0f) and lubuntu 16.04
![screenshot-20170822-134741](https://user-images.githubusercontent.com/29901471/29587564-336d2ac2-8743-11e7-901d-79bc4e1d73a3.png)
![screenshot-20170822-134747](https://user-images.githubusercontent.com/29901471/29587565-336ee15a-8743-11e7-936a-1c044ecf5301.png)
![screenshot-20170822-134758](https://user-images.githubusercontent.com/29901471/29587566-336fbdbe-8743-11e7-9060-38a77ca40c73.png)
![screenshot-20170822-131840](https://user-images.githubusercontent.com/29901471/29587578-3f0b7104-8743-11e7-9cf5-90222f7f5952.png)
![screenshot-20170822-132622](https://user-images.githubusercontent.com/29901471/29587596-4704f59c-8743-11e7-859a-61f8e0b0f1f4.png)

**Comment by impaktor** [comment]
So random placement of stations should check if there's another station in the system that is too close, I guess. Sounds like a savebumping fix would be needed. Could go with the PR for moving start location #4092.

**Comment by Zireael07** [comment]
The pics are awesome, as is your theory on the planet. I say it lands in the Things to See page regardless.

**Comment by fluffyfreak** [comment]
I am surprised that the stations are in those orbits, I vaguely recall there being some safeguards against that sort of thing from when I did the multi-orbit work.

**Comment by fluffyfreak** [comment]
The problem is coming from https://github.com/pioneerspacesim/pioneer/blob/master/src/galaxy/StarSystemGenerator.cpp#L1594 where it decides what orbits and shells to fill. Though I don't understand why yet (_obviously or I'd fix the bug!_) because after filling a shell it should put the next iteration of station in at a different part of the orbit several dozen degrees away from the existing station.
