### ISSUE TITLE
Most (gas giants?) planets have gravity = 1.000 Earth g?

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#4111]
### Observed behaviour
Looking in System Info View, it looks like most gas giants have 1.000 g gravity, especially gas giants.

I did't do a very extensive investigation, but Sol seems to be OK.

I'm just on the look out now that we've merged #4108 

### Expected behaviour
More random!

![dilbert](https://cloud.githubusercontent.com/assets/619390/10359231/def43a20-6d96-11e5-9583-893aef229c23.gif)

Why does it seem to be so fond of creating 1.000 g worlds? Is there some coupling between random radius and random mass?

### Steps to reproduce
Start at Sol, e.g. search for Kapteyn's star, and look in system info view at the gass giants' gravity. 

__My pioneer version (and OS):__
Today's master, ab5fd7448c33f5875074a18b9ca63081d00392d7

**Comment by jaj22** [comment]
See StarSystemGenerator.cpp, line 790+. The radius for generated planets is purely dependent on their mass, with no random or composition-dependent factors. For bodies with mass 1 to 200 EU, the calculation is simply rad = sqrt(mass). As surface gravity is G*mass/rad^2 and both values are measured in earth units, all of those bodies will have 1.0g. 

The ideal is probably composition dependence.

**Comment by impaktor** [comment]
OK, thanks. Then we know it's not a bug. I'll think about this some, how it could be improved.

**Comment by kennworl** [comment]
Having had a look at Kapteyn's Star, I noticed that everthing that had mass falling between 1 and 200 Earth Units (EU) had a surface gravity of 1G.  Is that wrong?

KS(c) is a gas giant with 6.661 EU and 2.581 ER (Earth Radii)
KS(d) is an ice world with 1.572 EU and 1.254 ER
KS(e) is a gas giant with 65.446 EU and 8.090 ER
KS(h) is a gas giant with 178.126 EU and 13.346 ER

All of the planetary measurements are generally based on comparisons to Earth.  The "surface" of Earth is where the pressure is 1 bar  or sea-level.  So I guess for oceanic, or rocky planets, the surface is the average level of the ground, or ocean (whichever is higher).  For gas-giants where you don't have a clear cut surface, the NASA definition is to use the level of the atmosphere where the pressure is 1 bar.  So this should provide a measurable radius or diameter of any given planet.  However, I have seen descriptions of gas-giant radii that are measured from cloud tops, which will vary depending on atmosphere composition I suppose.

Now the web site mentioned had a big disclaimer about how shaky the exo-planet Mass/Radius formula was, but they had to start somewhere.  It is m^0.5 where m is <= 1 and < 200.  The above planets obey that rule (no bug).  However that range of 1 to 200 spans everything from rocky planets to gas giants.

Anyway, lets see how this formula stacks up to the relevant planets in the solar system
 - Saturn = 95.162 EU and 9.140 ER to 9.44 ER - not quite spherical (accepted), 9.755 (formula)
 - Neptune = 17.147 EU and 3.865 ER (accepted), 4.141 (formula)
 - Uranus = 14.536 EU and 3.981 ER (accepted), 3.813 (formula)

So the radius formula is great at the small end of the scale and less accurate towards the 200 EU mark with lots of variation depending on planet composition.  I suppose the quick fix would be to add a radii random +/- multiplier that goes from 0% (for 1 EU) to 10% (for 200 EU).  That will look a bit better and who is going to argue how realistic it is.  I wouldn't overthink this one.  I'll give it a go tonight and see how that system looks.

**Comment by impaktor** [comment]
For reference, the url in the souce discussed is:
http://phl.upr.edu/library/notes/standardmass-radiusrelationforexoplanets

And just doing an internet search on: _Standard Mass-Radius Relation for Exoplanets_ turns up several papers. My idea was, either (or both):
1. add some small random noise, e.g. 1.000 g -> 1.231 g
2. make a polynomial fit to experimental data, would also remove the if-else in the code, as it would be "one equation to rule them all".

Anyway, this is some "low hanging fruit" up for grabs.

**Comment by kennworl** [comment]
ok.  My quick fix is below.  Works well enough.
		//sbody->m_radius = fixed::FromDouble(pow(sbody->GetMassAsFixed().ToDouble(), 0.5));
		sbody->m_radius = fixed::FromDouble(pow(sbody->GetMassAsFixed().ToDouble(), 0.5) * (1.0 + rand.Int32(-10, 10) / 100.0));
		// The above calculation r=m^-2 combined with the standard gravity formula g=G*m/r^2 works out to be standard 1g (issue #4111)
		// added a random factor +/- 0 to 10%

As for one equation to rule them all, not sure if that works with terrestrial vs gas giant, but you're welcome to have a go at it.   If you find it, be sure to let the guys at the lab know.  You might get a Nobel prize out of it.  :-)

**Comment by impaktor** [comment]
@kennworl Will you PR it, or should we make a commit with it?

Making the actual equation is very simple, with my un-scientific approach. The main thing stopping me from doing it is the data in the plot is overlapping (too big blobs), so I can't extract all points, but the equation itself wouldn't have to make any sense. Just fit a high degree polynomial to data. No paper in it as it wouldn't capture any "understanding" of the underlying process, or model anything, other than existing data, and it wouldn't need to have high accuracy, or make predictions. Just be in the right ballpark.

**Comment by kennworl** [comment]
Well, the one line change and the surrounding comments (including the original line) are posted here.  All it does is an unscientific masking of the problem.  I put it here so people could try it and improve on it before the change made it to the main trunk.  It is easily undone so commit it for now if you are in a hurry to fix it.  It.

**Comment by fluffyfreak** [comment]
Today a RNG, tomorrow a polynomial fit to experimental data. All good with me.

**Comment by impaktor** [comment]
I have a commit of the suggested fix above, but it's a save bump, and on the other computer. I'm closing this for now, as we understand why it happens.

**Comment by fluffyfreak** [comment]
@impaktor I had an idea of how to do this without bumping? Create a new Random using the systembody->GetSeed() and use that for the additional values you need.

That way it wouldn't affect other calls to the existing Random.

**Comment by impaktor** [comment]
@fluffyfreak In this case, I prefer to wait until some other PR requires a save bump, rather than uglyfy the code, by introducing another instance of Random. This issue isn't really a bug, so no rush.
