### ISSUE TITLE
SIGFPE in AICmdFlyTo::TimeStepUpdate at ShipAICmd.cpp:897

### ISSUE THREAD

**Issue by etam** [pioneerspacesim/pioneer#4112]
### Observed behaviour
Game crashes

### Expected behaviour
Guess ;)

### Steps to reproduce

1. Load this save: [save.zip](https://github.com/pioneerspacesim/pioneer/files/1254236/save.zip)
2. Set destination to Tomm's Sanctuary
3. Take off from station
4. Use autopilot to dock with the target station
5. Set time speed to maximum
6. Wait for it

### Additional notes

    Thread 1 "pioneer" received signal SIGFPE, Arithmetic exception.
    AICmdFlyTo::TimeStepUpdate (this=0x261ff370) at ShipAICmd.cpp:897
    897                     std::min(sdiff, m_prop->GetAccelFwd()*timestep);
    (gdb) p sdiff
    $1 = -nan(0x8000000000000)

https://github.com/pioneerspacesim/pioneer/blob/d8f9a981a9693ad1488bed228d95daa3c7f92542/src/ShipAICmd.cpp#L897

__My pioneer version (and OS):__
version: 20170813
OS: openSUSE 42.2

**Comment by fluffyfreak** [comment]
I think that this is the same bug as fixed by #4108 earlier today.

Will leave it open until we can confirm with the new builds.

**Comment by impaktor** [comment]
@etam please download the latest release. If bug is still there, then please re-open (or open an new issue).

**Comment by etam** [comment]
I can't test the save I've uploaded here, because pioneer crashes with the following error:

    pioneer: SpaceStation.cpp:208: void SpaceStation::InitStation(): Assertion `m_shipDocking.size() == m_type->NumDockingPorts()' failed.

My current save is not affected though.

If I happen to catch this bug again, I'll reopen this ofc.
