### ISSUE TITLE
can't start the game (SVG image)

### ISSUE THREAD

**Issue by Wolfox6687** [pioneerspacesim/pioneer#4117]
Hello I can't open my game.
When i open my game, a window open and say that:
![svg problem](https://user-images.githubusercontent.com/31419039/29789672-1a3290f8-8c37-11e7-9115-0236fadf1b0d.PNG)
I use this version of the game: pioneer-20170827-win32

**Comment by nozmajner** [comment]
I suspect you have some odd non-base alphabet characters in a directory name in path of Pioneer, like "áé" etc. Could you check that?

**Comment by Wolfox6687** [comment]
yes its that but how can i change the name because its a user name ?

**Comment by nozmajner** [comment]
I don't know if you can do that. But you could move out Pioneer to c:/ or Program Files for example, and I think it will run. (Never understood why microsoft thinks it's a good idea to allow such letters in directory and file names, they are nothing but trouble /rant)

**Comment by ecraven** [comment]
I think this has been fixed in upstream, I'll check later and update our
contrib accordingly.

**Comment by impaktor** [comment]
I'm going to assume we're good on this one. We just upgraded to higher imgui on master. Sadly, no build out yet.
