### ISSUE TITLE
Add delete button into "Load Game" window (Feature Request)

### ISSUE THREAD

**Issue by Fixer-007** [pioneerspacesim/pioneer#4120]
Something like this:
![default](https://user-images.githubusercontent.com/16494741/29825288-a280588c-8cdc-11e7-9ce4-0dbd7836c69b.png)

To delete: select save, press "Delete", confirmation popup "Really delete? Y/N"

What do you think?

**Comment by impaktor** [comment]
Yes please? People will probably want to be able to delete multiple saves, and such, so might open the flood gate for more feature requests?

**Comment by macksting** [comment]
Could you also pretty please add a variable number to jettison? Say you have 3000 tons of radioactive waste because that's how you decided you're going to use your dsminer. Save approximately 2995 clicks.

**Comment by Fixer-007** [comment]
Ability to delete one save at a time without closing the Load Window will be sufficient IMO.

**Comment by impaktor** [comment]
@Fixer-007  OK, I thought you were showing of what you were working on. In general, we don't use the issue tracker for feature requests. Anyway, this hole UI is to be re-written soon anyway, and is covered by #4078.
