### ISSUE TITLE
I think time in Pioneer must be UTC

### ISSUE THREAD

**Issue by manolollr** [pioneerspacesim/pioneer#4121]
Now, starting point in Earth is moved to London, but there is still Los Angeles timezone. At 13:30 in London is night!!
Well, it's not a severe issue but it's not aesthetical to see night in London at 13:30.
I think the best time to use is UTC, it's universal :-)

**Comment by nozmajner** [comment]
Actually there's an event in Pioneer role. When the scientists worked on the first hyperdrive prototype there was a huge hyperspatial explosion that shunted Earth back in time about half a day. That's the reason for it. 
But nah, I'm joking, and will check if I can spin back and forth Earth a bit to match up UTC. After I figured out where the Sun should be on the sky at that time.
