### ISSUE TITLE
"Continue Game" button is not loading _exit after first exit to menu

### ISSUE THREAD

**Issue by Fixer-007** [pioneerspacesim/pioneer#4122]
To reproduce the problem:
+ make clean save game folder
+ enable autosave
+ start game
+ undock and fly somewhere
+ exit this game to main menu, observe that few autosave files are created and _exit file is also created
+ observe inactive "Continue game" button

However if you restart game completely (executable itself), "Continue game" will work.

So, it seems that after exiting game to main menu - code does not actually pick up created _exit file for some reason.

Relevant part of the code: https://github.com/pioneerspacesim/pioneer/blob/2da76d412c7a0da9e5056caedea38b7a3ef5bf54/data/ui/MainMenu.lua#L101

I would also suggest to make this "Continue game" button work not only with autosave (_exit file), but with "newest save" if autosave not enabled. That will be convenient.

Pioneer 20170827 / win7

**Comment by richardpl** [comment]
I can not reproduce this. I think this have been fixed.

**Comment by impaktor** [comment]
Actually the UI has been re-written, from NewUI to Imgui, so not surprising.

**Comment by Fixer-007** [comment]
I can't verify possible fix due to old videocard, sorry and fm.

**Comment by impaktor** [comment]
@Fixer-007 even if you put `RendererName=Opengl 2.1` in your config? That works on my +10 year old laptop with Intel 950(?) card. 

If not, then when is the last time pioneer worked for you on your current graphics card?

**Comment by Fixer-007** [comment]
My videocard is 13 years old or so, with 2.1 I have multiple errors and then exit:
![default](https://user-images.githubusercontent.com/16494741/41600327-52d1018a-73de-11e8-9b9e-d418f84d5ec6.png)
![default](https://user-images.githubusercontent.com/16494741/41600341-5c222250-73de-11e8-9eff-513f07a2b23e.png)
![default](https://user-images.githubusercontent.com/16494741/41600355-67f344d8-73de-11e8-9409-b3cb3af44d8c.png)

>If not, then when is the last time pioneer worked for you on your current graphics card?

It never worked on that card, my new card died during mining craze, so due to outrageous prices that are still high I decided to use older GPU for some time.

**Comment by fluffyfreak** [comment]
Radeon X800 GTO, 256MB card?

Yeah that's an Opengl 2.0, not even 2.1 capable card, and half as much ram as we've ever seen it run on a GPU (_nVidia 8600GT 512MB was the lowest I know of_).

The ram is an issue but the fact that it won't support our shaders is the biggest issue.

Sorry, you could pickup something like a really low-end GPU. Hell I might have one to sell for £20+postage :)

**Comment by Fixer-007** [comment]
Will recheck this on HD2500.
