### ISSUE TITLE
Autosave bugs: not properly landed at city port (ship damaging)

### ISSUE THREAD

**Issue by Fixer-007** [pioneerspacesim/pioneer#4123]
I've landed without any problems on planet city Cooke (System Ceenex), autosave did its job, yet when I quickly loaded it again - ship appeared sitting on landing pad, yet pressing F4 reveals docking menu and unpausing game causes crashing/tumbling of the ship on landing pad.

This is frequent problem on almost any autosave on any city located on any planets. Very annoying.

Faulty save: [_autosave4.zip](https://github.com/pioneerspacesim/pioneer/files/1267446/_autosave4.zip)

Pioneer 20170827 / win7

**Comment by Fixer-007** [comment]
This is frequent problem on almost any autosave on planet.

**Comment by Fixer-007** [comment]
From what I understand, this situation happens when you undock from city (blast off), almost immediately game gets autosave. Since ship during this time has almost no upward velocity, this causes ship to fall down on landing pad causing tumbling, crashing, etc.

One way to solve this is to add slight delay (1-2 seconds?) before autosave to let ship take some upward speed during blast off.

**Comment by richardpl** [comment]
I can not reproduce this, can you still reproduce this?

**Comment by Fixer-007** [comment]
Will recheck in half a year when will decide what gpu to buy.

**Comment by fluffyfreak** [comment]
@Fixer-007 I've got a GeForce GT 730 SILENT 1024MB lying around you could have for the cost of postage.

Not great, but it'll run Pioneer no problem

**Comment by Fixer-007** [comment]
Nah, I don't want to deal with all that international shipping and customs, so be patient :)

**Comment by Fixer-007** [comment]
Will recheck on Intel HD 2500 ;)

**Comment by Bodasey** [comment]
confirmed with actual master; it's not possible to undock again, undock jump is lost, setting a new target brings the ship back to the game, but the first few seconds is tremor, not move. In space stations, the ship hovers (and luckily leaves out backwards, but may collide?).

Do we really need two saves when visiting a space-/starport?

**Comment by Web-eWorks** [comment]
CC @Gliese852 since you've done/are doing work on space stations and docking code.
