### ISSUE TITLE
Autopilot to Metis (Jupiter's innermost asteroid) causes Pioneer to crash

### ISSUE THREAD

**Issue by kennworl** [pioneerspacesim/pioneer#4126]
### Observed behaviour
When asking the autopilot to put me a high orbit around Metis (innermost asteroid of Jupiter) I get this:
Unhandled exception at 0x003BC2FD in pioneer.exe: 0xC00002B5:  Multiple floating point traps (parameters: 0x00000000, 0x00001921).
This was reported from my VS2017 build.  The line that the IDE reported the problem at was line 206 of Propulsion.cpp
```
double calc_ivel(double dist, double vel, double acc)
{
	bool inv = false;
	if (dist < 0) { dist = -dist; vel = -vel; inv = true; }
	double ivel = 0.9 * sqrt(vel*vel + 2.0 * acc * dist);		// fudge hardly necessary

	double endvel = ivel - (acc * Pi::game->GetTimeStep());
	**if (endvel <= 0.0) ivel = dist / Pi::game->GetTimeStep();	// last frame discrete correction**
	else ivel = (ivel + endvel) * 0.5;					// discrete overshoot correction
//	else ivel = endvel + 0.5*acc/PHYSICS_HZ;			// unknown next timestep discrete overshoot correction

	return (inv) ? -ivel : ivel;
}
```
On the standard August 2017 build, the program simply freezes as (not responding).

PS: I've tried this a few times on different bodies in Sol.  Seems to be any of Jupiter's asteroids that will cause this crash.  Asteroids of other planets seem to be ok, as are Jupiter's bigger moons.

### Expected behaviour
Um....not crashing?  I would like the autopilot to put me in orbit of Metis pleeze?

### Steps to reproduce
Starting a completely new game in LA,  lift off, select Metis on the system map, then go back to the viewer, press F4,  select 

__My pioneer version (and OS):__
Crash happens on the standard August 2017 build of Pioneer on a Windows 10 Home PC.  Crash also happens on my VS2017 build from the main trunk.

**Comment by impaktor** [comment]
> On the standard August 2017 build

Which of them? There were 2 builds in August. First one (15th?) had zero mass space bodies (Planetary asteroids).

**Comment by nozmajner** [comment]
If it happens on master too, then it's not the same.
It doesn't happen on the latest release on my end. The autopilot does have problems achieving a high orbit, because that height is outside the frame, but it doesn't crash the game. (only tried once)

**Comment by kennworl** [comment]
The build I was using was the Aug 15 one.  Since grabbed the 27th (didn't know it existed) and the problem seems to have gone away.  I did note that the description of the asteroids in the system view was still zero earth masses, so I don't think that was the problem, but happy to be corrected.  Happy to close this one.  Thanks people.

**Comment by impaktor** [comment]
> Since grabbed the 27th (didn't know it existed) and the problem seems to have gone away.

Expected. That bug was fixed since 15th. Reason you see 0 mass, is because it only shows 3 decimals in the system info view, I believe. Mass is actually non-zero
... unlike the failed promisses of life.

**Comment by jaj22** [comment]
To clarify, zero mass bodies are not a problem: Space stations are zero mass, and so is Themisto. The problem was that some asteroids had _negative_ mass due to an integer overflow.
