### ISSUE TITLE
Sector map: pressing buttons selects stars behind them

### ISSUE THREAD

**Issue by Fixer-007** [pioneerspacesim/pioneer#4128]
Windowed 1152*864, to reproduce open sector map and try pressing any buttons in various places, _very_ often it selects star behind button.

![default](https://user-images.githubusercontent.com/16494741/29925787-2997f4f4-8e6a-11e7-8731-a5b4a84284a0.png)

Pioneer 20170827 / win7

**Comment by nozmajner** [comment]
I'll close this, noted it on #4078
