### ISSUE TITLE
Missing info about cargo bay capacity on Ship market

### ISSUE THREAD

**Issue by Fixer-007** [pioneerspacesim/pioneer#4130]
For some reason info about "cargo space" was omitted, cargo bay size is the first thing trader wants to know before buying a ship.

![default](https://user-images.githubusercontent.com/16494741/29943397-09b2693e-8ea2-11e7-8538-221445a08eea.png)

Pioneer 20170827 / win7

**Comment by nozmajner** [comment]
Capacity is supposedly that, on the right column. But that doesn't necessarily line up with cargo capacity, since the overall capacity can be larger. Don't know why it's not shown.

**Comment by ecraven** [comment]
Szlrd <notifications@github.com> writes:

> Capacity is supposedly that, on the right column. But that doesn't
> necessarily line up with cargo capacity, since the overall capacity
> can be larger. Don't know why it's not shown. 

Related, I *think* it isn't shown whether a ship supports a backwards
gun or not.. that might be relevant too...
