### ISSUE TITLE
Text constrast too strong, makes eyes hurt

### ISSUE THREAD

**Issue by Talkless** [pioneerspacesim/pioneer#4140]
After playing several hours, it becomes uncomfortable to read white text on dark background in Bulletin Board... Contrast is just too strong.

Is there a plan to have different themes maybe, or change colors whatsoever? 

Maybe it would be worth to take examples from [Solarized](http://ethanschoonover.com/solarized) color scheme or something like that..?

Pioneer 20170827 Linux

**Comment by nozmajner** [comment]
Never had that problem, and I'm playing the game for years now.
Anyhow there are plans to support color themes eventually, with the imgui migration.

**Comment by Talkless** [comment]
Maybe it's because I'm playing on 15.6" full-hd laptop? Font size too small?

Anyway, there are people who like to code on black background, others on white, maybe it's preference thing :-) . Though taking my time to choose good tasks on BBS gets rather annoyingly uncomfortable.

So you are rewriting to use imgui for UI? I guess it'll take some time..?

**Comment by nozmajner** [comment]
Yeah, it will take some time.
Until that, you can try uping the font size in data/fonts/UIFont.json as a workaround for them being too small.
Anyhow, I close this issue, and noted it on the UI roadmap.
