### ISSUE TITLE
Head tracking support (Opentrack)

### ISSUE THREAD

**Issue by Talkless** [pioneerspacesim/pioneer#4141]
It would be nice to have head tracking for Pioneer.

Open source [Opentrack](https://github.com/opentrack) project support multiple inputs, from simple paper tracker ([Aruco](https://github.com/opentrack/opentrack/wiki/Aruco-tracker), I use it and it works great!) to Pointracker DIY hat clip with LEDs.

What Pioneer needs is a UDP socket to receive pitch, yaw, roll, and x-y-z offsets. Here's example from Flightgear protocol:
https://github.com/opentrack/opentrack/blob/0bc78d53028f5ac68b9ab454347b8ad453988c08/proto-flightgear/ftnoir_protocol_fg.cpp#L25

Or some sort of generic (I guess) UDP protocol:
https://github.com/opentrack/opentrack/blob/0bc78d53028f5ac68b9ab454347b8ad453988c08/proto-udp/ftnoir_protocol_ftn.cpp#L26

So, simply six doubles...

I believe these values should be added on top of these changed by mouse/numpad, so that you can switch to rear camera and then take a look around freely using head tracker.

**Comment by nozmajner** [comment]
I'll close this, because we prefer feature requests on IRC or the dev forum, and this isn't actionable on it's own anyway. 
@fluffyfreak did some experiments with Oculus Rift, so I'm pinging. :)

**Comment by impaktor** [comment]
@Talkless development forum registration is unlocked now, so you're more than welcome to register.

This was actually an informative feature request, for something we've never been pitched before, and that is rare, but I suggest we keep this closed, until someone starts working on a PR for it, if that day ever comes. Further discussions can be done on the dev forum.

**Comment by Talkless** [comment]
Thanks, just created account.

>  if that day ever comes

*Maybe* I could find some time and energy for that, but yet my open source code contributions are minimal in the reality, so I can't promise anything.

**Comment by nozmajner** [comment]
No need to promise anything. Try your hand if you have the motivation and see if it's even interesting/fun enough to work on or work on open source in general. Nobody owes anybody anything.

**Comment by Talkless** [comment]
I've created post:
https://pioneerspacesim.net/forum/viewtopic.php?f=4&t=515
