### ISSUE TITLE
Add Display FPS counter option

### ISSUE THREAD

**Issue by Talkless** [pioneerspacesim/pioneer#4142]
It would be useful to see frame rate in the screen corner. I feel frame rate drops but I do not know what to report...

I failed to find (Forums, Wiki) how could I see FPS in Pioneer, so writing here.

**Comment by impaktor** [comment]
Already there: Ctrl + I

We don't use the issuetracker for feature requests, so pelase use dev forum/iRC instead.

**Comment by Talkless** [comment]
>We don't use the issuetracker for feature requests

Oh, I guess I was misled by Wiki:
https://pioneerwiki.com/wiki/How_to_communicate
> GitHub Issues are a good way to report issues *and feature requests* to the devs.

Could it be changed then? :-)

**Comment by impaktor** [comment]
Wiki has outdated parts, I've updated it now, thanks.

Didn't mean to "accuse" you, just letting you know. IRC is the preferred way of communication, I think. Fastest.

**Comment by Talkless** [comment]
> Fastest.
But wouldn't it be fastest to.. forget?

**Comment by nozmajner** [comment]
Nope, if we write it down. Also, for forum access, drop by on IRC, so we can open up the reg for you. (We need to sort out the spam problems, damn)
