### ISSUE TITLE
NameGen calls very often

### ISSUE THREAD

**Issue by ColdSpirit0** [pioneerspacesim/pioneer#4157]
Two posts from #4134:
---
[First:](https://github.com/pioneerspacesim/pioneer/pull/4134#issuecomment-328246894)
I created a log with command `src/pioneer 2>pioneer.log`, started game on Earth and closed game after that.  When I read the log, I saw many (unuseful?) calls of import. To count relative amount of calls I used command:
``` sh
# command not count calls of import, but count occurences of that module in the log
# real count of calls in 2-6 smaller than in output
grep -Po '(?<=\[).*(?=\])' pioneer.log | sort | uniq -c | sort -nr > parsed.log
```

I put here top ten of the list:
```
  24307 NameGen
   1035 Event
    402 Engine
    354 Lang
    331 EquipSet
    223 Game
    144 Serializer
    138 Format
    120 ShipDef
    120 Comms
```
NameGen looks very popular =) 
Dont know what functions requires it, but I think it should be moderated.

I added pioneer.log and parsed.log to dropbox, also I made a custom style for vim to watch pioneer.log, you can see it all here: [importfix](https://www.dropbox.com/sh/t7aoly2123tmy42/AABVwQh0aNRdab3n5h56fGhFa?dl=0)

---
[Second:](https://github.com/pioneerspacesim/pioneer/pull/4134#issuecomment-328247614)
I got all callers of NameGen and count it:
```sh
grep -Po '(?<=\[NameGen\]: import started, caller: ).*(?=$)' pioneer.log | sort | uniq -c | sort -nr
```

output:
```
   4529 core
    954 modules/Taxi/Taxi.lua
    421 modules/Assassination/Assassination.lua
    169 modules/TradeShips.lua
      1 modules/GoodsTrader/GoodsTrader.lua
      1 modules/BreakdownServicing/BreakdownServicing.lua
      1 libs/Character.lua
```
Core means somewhere in C++ code. Now output shows exact count of `import("NameGen")` calls at loading time + ~5 seconds of game.

**Comment by impaktor** [comment]
Not sure why this would be a bug? How much _time_ does it spend on name gen relative others? Is this the major bottle neck _timewize_?

Each station has a BBS, each BBS has ~10 Taxi and Delivery missions, each mission has a "Hi my name is.... deliver to friend by name...". Not sure why it's calling TradeShips thoug. All the others make sense, at least assuming it's a system with very many stations, like Sol.

Sol looks to have ~26 sations, say you have ~15 delivery missions on each BBS, and each mission needs two  names, then you'er up to 780 calls.

**Comment by fluffyfreak** [comment]
Might be worth looking into though.

**Comment by ColdSpirit0** [comment]
I made a new log where I waited about ten minutes. When I called first command I got that output:
~~~
119287 Event
  24307 NameGen
   1247 Equipment
    402 Engine
    354 Lang
    347 EquipSet
    223 Game
    144 Serializer
    138 Format
    120 ShipDef
    120 Comms
    119 utils
     84 Space
        ...
~~~
NameGen really have limited calls, I thought it have calls like Event, without end, that why I created the issue.
Dont sure is it really justified that count of calls, but it doesnt bottleneck and no reason to investigate it now.

**Comment by impaktor** [comment]
I assume NameGen is only called upon creating a system, once the BBS have been populated, there's no reason to keep calling NameGen at all, I think.

An optimization that could be done, is to only populate the BBS of a station when landing on it, instead of the entire system.

**Comment by laarmen** [comment]
The problem runs a bit deeper than that. Somewhere, I think there is some
code that calls import("NameGen") during its execution, not just its
initialization. I assume it is the same for import("Event")
>
>
