### ISSUE TITLE
Combat rating remains the same.

### ISSUE THREAD

**Issue by antonspace** [pioneerspacesim/pioneer#4162]
### Observed behaviour

After 48 kills, received message along the lines of "congratulations commander, your combat rating has improved".
Combat rating iterated to Average.
After 64 kills, received message along the lines of "congratulations commander, your combat rating has improved".
Combat rating iterated to Above Average.
After 80 kills, received message along the lines of "congratulations commander, your combat rating has improved".
Combat rating remains at Above Average.

__My pioneer version (and OS):__

a614c6f
Linux Mint 18 64-bit

**Comment by impaktor** [comment]
You get new level every time you pass `2^n` (accumulated) kills, from n=3 to n=9, then at 2400 and then 6000.

So, bug is you get the message at 48 and 80. (At 64 is correct.)

**Comment by impaktor** [comment]
The bug is in the StatsTracking module, there it's assumed modulo 16 is the increment, i.e. you get it at 48%16 and 80%16. It will also miss the level at 6000 and 2400. Possibly, those levels are absurdly high as it is, as combat in Pioneer is a lot more difficult than in Elite. Not sure what the levels were in Elite, or Frontier, for that matter?

This module should not know the levels of combat rating, only if a change is made.

**Comment by impaktor** [comment]
Could you please test my fix for this, [here](https://raw.githubusercontent.com/impaktor/pioneer/fix_combatrating/data/modules/StatsTracking/StatsTracking.lua)?

You might want to open the Lua terminal (F12?) and change your combat rating
to something just below a new rank, e.g 7, or 15, then when you kill a ship the code for sending the message is triggered.

```lua
import("Character").persistent.player.killcount = 7
```

**Comment by nozmajner** [comment]
ctrl+F12 will bring up the combat test ship, which won't even shoot at you. Easy testing!

**Comment by impaktor** [comment]
That's useful. Alternatively, one could re-rout the function call so the function to be tested is trigged by the player jettisoning cargo, or shooting, instead of killing AI ship. A one liner in code-trick, I sometimes use.

**Comment by antonspace** [comment]
Set the kill count to 0, 7, and 15. Previously I have noticed the comms message appear after the first kill also, with combat status remaining at harmless.

Here are the results:

0-1 no comms message.
7-8 no comms message, rating changes from harmless to mostly harmless.
15-16 no comms message, rating changes from mostly harmless to poor.

**Comment by impaktor** [comment]
Right you are. I was bitten by the classic lua bug that `not x == y` is `(not x) == y` and not `not (x == y)`.

Fixed.

However, there will not be any message when going from 0 to 1, ans you're harmless up until 8 kills. No need to test the new version unless you want to. Thanks!
