### ISSUE TITLE
"Unkown AI Command" Tooltip on Autopilot icon

### ISSUE THREAD

**Issue by nozmajner** [pioneerspacesim/pioneer#4163]
### Observed behaviour
Reported by @crem on IRC
When you instruct the autopilot to fly to a ship which is selected as a nav target, the Autopilot button will switch to a rear crosshair, and the tooltip says "UNKOWN AI COMMAND"
![screenshot-20170920-215148](https://user-images.githubusercontent.com/4182678/30664661-c6253ef0-9e4e-11e7-9406-6c9b7a835ec0.png)

### Expected behaviour
It should say and show the same as it would for Fly to to a body.

### Steps to reproduce
Select a ship from the Orbit map (pressing the little ship icon on the top right will turn show them) or the target of a SAR mission.
Take off and instruct the autopilot to Fly to the vicinity of...

__My pioneer version (and OS):__
Win7, 20170828 Build

**Comment by impaktor** [comment]
In c++ side these are the AI commands:
```c++
	// This enum is solely to make the serialization work
enum CmdName { // <enum scope='AICommand::CmdName' name=ShipAICmdName public>
	CMD_NONE,
	CMD_DOCK,
	CMD_FLYTO,
	CMD_FLYAROUND,
	CMD_KILL,
	CMD_KAMIKAZE,
	CMD_HOLDPOSITION,
	CMD_FORMATION
};
```

On Lua-side, only three are mapped:
```lua
local aicommand_info = {
	["CMD_DOCK"] = { icon = icons.autopilot_dock, tooltip = lui.HUD_BUTTON_AUTOPILOT_DOCKING },
	["CMD_FLYTO"] = { icon = icons.autopilot_fly_to, tooltip = lui.HUD_BUTTON_AUTOPILOT_FLYING_TO_TARGET },
	["CMD_FLYAROUND"] = { icon = icons.autopilot_medium_orbit, tooltip = lui.HUD_BUTTON_AUTOPILOT_ENTERING_ORBIT },
}
```
...or else `tooltip = "UNKNOWN AI COMMAND"`. That's the cause.
