### ISSUE TITLE
Refuel doesn't increase amount of fuel when paused

### ISSUE THREAD

**Issue by mooskagh** [pioneerspacesim/pioneer#4168]
### Steps to reproduce
1. Burn some fuel by flying to remote location
2. Dock to any station
3. Pause the game
4. Go to comms and press "Refuel full" button

### Observed behaviour
5. Amount of cash decreases, amount of fuel not increases.
  It's possible to click "Refuel full" several times and drain cash all the way to 0.
  When you unpause, the refuel does happen, unless you have 0 cash left.

### Expected behaviour
5. Amount of cash decreases, amount of fuel increases.

__My pioneer version (and OS):__
git build 1d0eed5ac (2017-09-14)
Linux / x64

**Comment by nozmajner** [comment]
Duplicate of #3988?

**Comment by mooskagh** [comment]
Indeed it is. Closing this one now then.
