### ISSUE TITLE
Problem with save and rescue mission.

### ISSUE THREAD

**Issue by antonspace** [pioneerspacesim/pioneer#4175]
### Observed behaviour
Accepted a mission to save and rescue 1 crew and 1 passenger from a ship that had crash landed on Vesta

With 2 passenger cabins on board, flew to Vesta, landed <50m from ship, received comms message "cannot complete transfer, passenger missing"

Launched from surface, re-landed next to mission ship, missing passenger still missing.

Returned to Gates starport, comms message "Thank you for your efforts, I hope you will return to complete the task" 
Mission still active, returning not an option with just 2 hours remaining. 

Savegame:
[Missing_Pass.pdf](https://github.com/pioneerspacesim/pioneer/files/1348908/Missing_Pass.pdf)

__My pioneer version (and OS):__

Linux 64bit
8e90cc7

**Comment by impaktor** [comment]
@clausimu ping.

**Comment by clausimu** [comment]
In the supplied savegame - is that the 2nd return to the target ship or the first time you are seeing it? Do you still have a savegame available from after accepting the mission but before actually visiting the ship?

**Comment by antonspace** [comment]
The supplied savegame is saved before any interaction with the mission ship, prior to landing the first time. All earlier savegames have been overwritten.

**Comment by clausimu** [comment]
Found the bug. Selection of ship sizes for passenger rescue missions was not conservative enough. This could cause certain combinations of ship/hyperdrive classes that had no space left for passenger cabins. Thus, when you go to rescue the passengers they never even made it on the target ship to begin with. I'll post a fix shortly.
