### ISSUE TITLE
libz.1.dylib issue in MacOS High Sierra

### ISSUE THREAD

**Issue by Real-Gecko** [pioneerspacesim/pioneer#4181]
### Just a quick note for those who run the game on High Sierra
Running Pioneer 20171007 on High Sierra (10.13) gives
```
dyld: Symbol not found: _inflateValidate
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib
  Expected in: ./libs/libz.1.dylib
```
To solve the issue I used the following commands
```
cd <unpacked game folder path>/libs
cp /usr/lib/libz.1.dylib libz.1.dylib
```

**Comment by Philbywhizz** [comment]
Interesting find (and fix).
High Sierra is a version of OSX I haven't run pioneer on (as I don't have it and my old mac isn't really powerful enough) so maybe it doesn't like the version of libz that I've bundled up.

Is everything else working once you copy over the updated libz.1.dylib library? (haven't had much feedback on the success of the osx binary).

**Comment by Real-Gecko** [comment]
I did not play really extensively, but at firsth glance everything is fine, at least game works smoothly. MBP 2012 13`` with integrated Intel HD Graphics 4000, 4GB of 1600MHz DDR3 memory and 256GB solid-state drive.

**Comment by Real-Gecko** [comment]
Actual solution came from this issue:
https://github.com/solvespace/solvespace/issues/294

**Comment by Philbywhizz** [comment]
What if you remove the libz.1.dylib from the <package source>/libs folder (please don't delete your /usr/lib/libz.1.dylib file). My thinking is that its loading the older version on the libs folder, and if it doesn't exist it will fallback to your system version (which is later)

**Comment by Real-Gecko** [comment]
Yep, that worked too. I don't know why didn't I try deleting the dylib in the first place :D

**Comment by Philbywhizz** [comment]
Thanks for that. I'll remove that library from the next binary build.

**Comment by Real-Gecko** [comment]
Glad to help :)

**Comment by impaktor** [comment]
Too lazy to follow, does this report on an issue in mac build that has been fixed in build scipt and will not be an issue in next build?

**Comment by Philbywhizz** [comment]
Yes, this issue has been fixed in my build script. I want to keep this open to remind me to update the repository with the updated script. :)
