### ISSUE TITLE
Assertion failure on startup

### ISSUE THREAD

**Issue by gwerbin** [pioneerspacesim/pioneer#4188]
Pioneer crashes on startup with an assertion failure. I installed it with Homebrew on MacOS 10.12.

### Observed behaviour

This is what I see when running `pioneer -g`:

```
ver 20171001 on: Mac OS X

System Name: Darwin
Host Name: slab.local
Release(Kernel) Version: 16.7.0
Kernel Build Timestamp: Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64
Machine Arch: x86_64

SDL Version 2.0.6
Initialized OpenGL 3.1, with extensions, renderer
invalid axis binding '' in config file for BindAxisPitch
invalid axis binding '' in config file for BindAxisRoll
invalid axis binding '' in config file for BindAxisYaw
started 3 worker threads
ShipType::Init()
Lua::Init()
Fonts:
font orbiteer:
- DejaVuSans.ttf 1.200000
- wqy-microhei.ttc 1.000000
- Orbiteer-Bold.ttf 1.000000
font pionillium:
- DejaVuSans.ttf 0.928571
- wqy-microhei.ttc 1.000000
- PionilliumText22L-Medium.ttf 1.000000
Assertion failed: (ty == FileInfo::FT_FILE), function ReadFile, file FileSystemPosix.cpp, line 158.
```

### Expected behaviour

I get to play Pioneer!

### Steps to reproduce

Install with Homebrew (`brew install pioneer`) and run `pioneer` or `pioneer -g` in the console.

__My pioneer version (and OS):__

```
$ pioneer -v
pioneer 20171001
```

MacOS Sierra 10.12.6, Macbook Pro late 2013 Retina model.

**Comment by impaktor** [comment]
ping @Philbywhizz

**Comment by mooskagh** [comment]
That looks like a "MacOS + fopen() returning success for directories" issue which was fixed in https://github.com/pioneerspacesim/pioneer/pull/4176

**Comment by mooskagh** [comment]
Also mentioned in https://github.com/pioneerspacesim/pioneer/issues/4174#issuecomment-333615394 which happened to be the issue covering two independent problems.

**Comment by Philbywhizz** [comment]
I'll have to check the 'homebrew' setup when I get home, but the version [20171007](https://sourceforge.net/projects/pioneerspacesim/files/pioneer-20171007-osx.tar.bz2/download) should have the fix #4176 applied to it.

**Comment by Philbywhizz** [comment]
I'm not a homebrew expert, but from what I can gather they use the last 'tag' (which is currently at 20171001 316a1f7). The fopen() fix was done after this so when we do a new 'release' and tag it with a new date the homebrew guys will come along and update their repository.

**Comment by gwerbin** [comment]
@Philbywhizz yes, that's the best way to do it. I'm not a Homebrew maintainer but I do occasionally contribute formula updates, so I could make the pull request.

**Comment by impaktor** [comment]
Bug fixed as mentioned --> closing.

**Comment by gwerbin** [comment]
It works, thank you! Now if only I was a good space pilot....
