### ISSUE TITLE
Assertion failed on assigning autopilot in new system

### ISSUE THREAD

**Issue by macksting** [pioneerspacesim/pioneer#4189]
### Observed behaviour
As I entered Ackti B (-87, 1, 0), I attempted to set autopilot to a space station. SpaceStation.lua had an assertion failed and the game crashed.

### Expected behaviour
Expected to autopilot to the space station and begin landing procedures from 12 or so AU away.

### Steps to reproduce
Load from save "corward ho"
Leap out of system and keep leaping until it breaks.

__error text:__
```
error: [string "[T] @libs/SpaceStation.lua"]:541: assertion failed!
stack traceback:
	[C]: in function 'assert'
	[string "[T] @libs/SpaceStation.lua"]:541: in function 'RemoveAdvert'
	[string "[T] @modules/DeliverPackage/DeliverPackage.lu..."]:334: in function 'cb'
	[string "[T] @libs/Event.lua"]:34: in function '?'
	[string "[T] @libs/Event.lua"]:185: in function <[string "[T] @libs/Event.lua"]:180>
```

__My pioneer version (and OS):__
git (7029164) on lubuntu 16.04

**Comment by macksting** [comment]
[corward ho.zip](https://github.com/pioneerspacesim/pioneer/files/1419632/corward.ho.zip)

**Comment by impaktor** [comment]
I wonder if this is still an issue in latest master? We did a new release a few days ago, if you want to test again.

**Comment by impaktor** [comment]
I'll assume this no longer happens. (Spacestation and BBS system has been re-written since this bug was posted)
