### ISSUE TITLE
The pale blue dot is the Earth

### ISSUE THREAD

**Issue by manolollr** [pioneerspacesim/pioneer#4190]
![punt_blau](https://user-images.githubusercontent.com/8089376/32698141-37027db6-c7a0-11e7-850f-370b124bdb5b.png)

I suggest to draw distant planets as dots, so you can say: "the pale blue dot is the Earth", or the red dot is Mercury, or the White dot whit tiny dots is Jupiter and its satellites. And when you are aproaching, the dots are getting bigger until a texture is rendered.

I think it's an easy way to add realism to the game. (My old Spectrum ZX80 was very good drawing dots :-) ). Now, the effect is a little strange, you are watching a point in the universe and instantly a planet is rendered, spontaneous generation? :-( I wish to see planets as dots.

**Comment by impaktor** [comment]
If the problem is that planets suddenly swell in size, then this is a bug, that sounds familiar even.

Might be worth sharing your hardware specs. Please see our wiki-FAQ on what to post

**Comment by manolollr** [comment]
It's not a bug, It's a feature request. Sorry, I haven't seen this line in the FAQ: Feature request? Please consider IRC, player- or dev-forum instead
I'm suggesting to always draw planets, whatever the distance you are from. So you can say: "the pale blue dot is the Earth." https://en.wikipedia.org/wiki/Pale_Blue_Dot
For example, if you are near Neptune, draw Earth as a tiny blue dot. As you are approaching Earth, draw it as a bigger blue dot, and when you are near the Moon, render Earth's texture.
Same for other planets, Mars, Venus, Jupiter and its moons, planets in other stars, etc.

**Comment by fluffyfreak** [comment]
@manolollr what @impaktor means is that we should already be doing what you have asked for, the fact that you don't see it means that there might be a bug.

**Comment by manolollr** [comment]
Ohh, Ok. I haven't latest Pioneer version, I have version 2 weeks ago. This afternoon I will compile newest version and try it.

**Comment by fluffyfreak** [comment]
No, I mean, that is not a new feature, it's been there for years.
When you are far from a planet it should render a small dot for it, then smoothly change to a planet as you get closer.

If that is not what you are seeing then it might be a bug. 
If you post the information in the files that Pioneer generates (https://pioneerwiki.com/wiki/FAQ#How.2Fwhere_do_I_report_my_bug.2Fcrash) then that would be very helpful.

**Comment by impaktor** [comment]
What @fluffyfreak said.

> I have version 2 weeks ago. This afternoon I will compile newest version and try it.

Alas, nothing has changed in pioneer during that time, so no need to.

**Comment by manolollr** [comment]
Ok. This afternoon I will post detailed hardware specs. In advance, I have an nvidia GeForce grahics card. Sometimes I have graphical issues, for example, I can't see moon from Earth, only see when I'm approaching. I'm using Arch Linux with proprietary drivers.
This afternoon more detail.

**Comment by fluffyfreak** [comment]
Great! Thankyou @manolollr

**Comment by manolollr** [comment]
[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/1467611/opengl.txt)
[output.txt](https://github.com/pioneerspacesim/pioneer/files/1467617/output.txt)

Leaving Earth and approaching to Moon. It is not visible until I'm at 240.000 Km. I think it should be visible from Earth.

Intel Core 2 Duo
4 GB RAM DDR 800
Nvidia GeForce 210 512 MB GDDR2

Arch Linux 64 bits
Proprietary nvidia drivers 340.104
Using Gnome Shell. I don't know if makes the difference to use diferent window managers, like Openbox.

**Comment by manolollr** [comment]
![orbital_view](https://user-images.githubusercontent.com/8089376/32737877-92fca910-c89b-11e7-8919-414cb4287704.png)
The text here is not visible. It is only visible 0.1 seconds when you click on a planet.

**Comment by Marcel-T** [comment]
I have the same issue with my GTX460 and Linux Mint18.1. The planet sprites disappeared years ago but I thought it was just part of the code upgrade. I hadn't noticed the issue with the Moon, but it's the same for me as for manolollr.
[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/1467736/opengl.txt)
I hope the above drag and drop works. I can't find output.txt.

**Comment by fluffyfreak** [comment]
Thanks everyone I'll try to get to take a look asap

**Comment by manolollr** [comment]
Until version 20160316-linux64 it was working.
Since version 20160404-linux64 it doesn't work.

**Comment by impaktor** [comment]
@manolollr Thanks, that will probably be very useful. @fluffyfreak come by IRC if you need help with [git bisect](https://robots.thoughtbot.com/git-bisect). Sorry for assuming this is on your table, but I shun any rendering/graphics stuff.

**Comment by impaktor** [comment]
@richardpl There is no description at all in the PR, #4347, that you reference, so it's difficult to know what it's doing. Would be great if you could edit your first post in that one, and also link to the issues it fixes.

I hope you don't think I'm being a pain in the butt, Improvement through iterations. :smiley:

**Comment by richardpl** [comment]
Well, i fixed bug of hiding information in systeminfo view, i dunno about other issue as report is extremely unclear.

**Comment by fluffyfreak** [comment]
Other issue is a rendering bug that looks like it is not rendering the planets when you're far away from them, it should be drawing them but apparently isn't/wasn't.

**Comment by richardpl** [comment]
@fluffyfreak yes, i can confirm that billboard thing draws nothing for me.

**Comment by richardpl** [comment]
@fluffyfreak i bisected it, and bad commit is 5e2e234ec3104be35f2d2e388f9624e90ed3f0f6
Can you take a look or say something?
