### ISSUE TITLE
Show graphic options, that are supported by hardware.

### ISSUE THREAD

**Issue by etam** [pioneerspacesim/pioneer#4192]
For example I set multisampling to x16 and it didn't work. In console output Iv'e found that it couldn't find visual and retried with multisampling disabled.

In glxinfo output I've found that multisampling is supported up to x8. After changing setting to this value, it works fine.

So I think that x16 should be grayed out, or somehow it should be reported in settings window, that it won't work.

**Comment by fluffyfreak** [comment]
Yes, OpenGL is shit at times. There's no way to know in advance what formats are supported, you request them and hope they've worked :/

Need to think about this

**Comment by fluffyfreak** [comment]
Ok Lua is driving me insane, lets say that `maxSamples` has a value of 4, how the hell do I loop through `aaModes` and add every value `<=` to `maxSamples` into `aaTempModes` whilst also adding the equivalent label from `aaLabels` into `aaTempLabels`?

> local maxSamples = Engine.GetMaximumAASamples()
		local aaLabels = { l.OFF, "x2", "x4", "x8", "x16" }
		local aaModes = { 0, 2, 4, 8, 16 }
		local aaTempLabels = {}
		local aaTempModes = {}
		for i = 0, mode in aaModes do
		-- ???
		end

I hate Lua so much.

**Comment by impaktor** [comment]
Something like so?
```lua
maxSamples = 4
aaLabels = { "foobar", "x2", "x4", "x8", "x16" }
aaModes = { 0, 2, 4, 8, 16 }
aaTempLabels = {}
aaTempModes = {}

for i,value in ipairs(aaModes) do
	if value <= maxSamples then
		print(i,value, aaLabels[i])
		table.insert(aaTempModes, value)
		table.insert(aaTempLabels, aaLabels[i])
	end
end
```

**Comment by fluffyfreak** [comment]
tada!

**Comment by laarmen** [comment]
*hugs FluffyFreak. * There, there...

Le jeu. 28 déc. 2017 à 16:49, Andrew Copland <notifications@github.com> a
écrit :
