### ISSUE TITLE
Small amount of missions on BBS after long playing

### ISSUE THREAD

**Issue by etam** [pioneerspacesim/pioneer#4193]
Steps to reproduce: 
* Start fresh game
* Fly to Mars with no time acceleration.
* Land on some station and open BBS

Expected behavior:
* Lots of available missions (around 50), like when you just started the game.

Actual behavior:
* Around 10 available missions.

Additional notes:
* Saving the game, exiting to menu and loading the game back, didn't change anything.
* Saving the game, exiting to OS, restarting and loading the game back, restored the desired amount of available missions.

__My pioneer version (and OS):__
pioneer 20171001
openSUSE Tumbleweed

**Comment by impaktor** [comment]
Number of adverts depend on size of stationg, and other things I can't remember now. You can not expect there to be spammed with 50 adverts in all BBS.

>    Saving the game, exiting to menu and loading the game back, didn't change anything.
>    Saving the game, exiting to OS, restarting and loading the game back, restored the desired amount of available missions. 

Well, this sounds more like a bug, as they should have the same behaviour.

**Comment by etam** [comment]
> Number of adverts depend on size of stationg, and other things I can't remember now. You can not expect there to be spammed with 50 adverts in all BBS.

That's what I thought, when I arrived first at Tomm's Sanctuary, but when I flew to Olympus Mons and got the same amount of missions, that felt a bit wrong to me.

**Comment by impaktor** [comment]
Well I think orbiting stations use same population as planet to set size.

**Comment by richardpl** [comment]
So what is actual bug here?

**Comment by impaktor** [comment]
Correct me if I'm wrong, but missions are created for the BBS when entering the system. Thus if spending a lot of time in a system, hopefully there will be new adverts generated as time in the system progresses.

Inconsistencies in BBS after save/load is probbably reported elsewhere, and might be fixed? It was a few years ago since I last could hold all open issues in my head at once. I have no opinion one way or the other.

**Comment by richardpl** [comment]
This does not happen any more.
