### ISSUE TITLE
Pioneer not running on Mac OSX High Sierra

### ISSUE THREAD

**Issue by AreTaj** [pioneerspacesim/pioneer#4196]
**Steps to reproduce:**
- Attempt to play the game from Pioneer exec file in Terminal, Mac OSX High Sierra
- Terminal opens, shows printout seen in screenshot below, nothing else happens.

**Expected behavior:**
- Game runs as usual, opens in new window, etc.

**Actual behavior:**
- See screenshot of Terminal: 
<img width="571" alt="screen shot 2017-11-25 at 11 39 07 am" src="https://user-images.githubusercontent.com/33988644/33234124-e9183db2-d1d5-11e7-9f9d-de77c9a11e83.png">

**Additional Notes:**
- The game worked perfectly fine before I updated from Mac OSX Sierra to High Sierra. I think that either some files were moved around in this update or whatever Pioneer used to launch does not exist anymore.
- I tried restarting my computer, which didn't change anything.
- I tried reinstalling the game from the .bz2 file; game still didn't run after trying to run as usual.

**My Pioneer version and OS:**
- Pioneer 20171007
- Mac OSX High Sierra

**Comment by Philbywhizz** [comment]
This seems very similar to #4181 

Try removing the libs.1.dylib file from the libs folder in the pioneer directory

See: https://github.com/pioneerspacesim/pioneer/issues/4181#issuecomment-335403485

**Comment by AreTaj** [comment]
Yep, that was it. Thanks so much!
