### ISSUE TITLE
Crash after return to Main Menu from Options Menu

### ISSUE THREAD

**Issue by The-EG** [pioneerspacesim/pioneer#4197]
### Observed behaviour
Pioneer crashes when returning to the Main Menu from the Options Menu.

The error given:
> [string "[T] @ui/MainMenu.lua"]: 194: attempt to index local 'args' (a nil value)
> stack traceback:
>        [string "[T] @ui/MainMenu.lua"]:194: in function 'MainMenu'
>        [string "[T] @ui/MainMenu.lua"]:80: in function <[string "[T]

### Expected behaviour
Returning to the Main Menu 

### Steps to reproduce
1. Run pioneer.
2. On Main Menu, Select 'Options'
3. Select 'Return to menu'
4. (Pioneer Crashes)

__My pioneer version (and OS):__
Pioneer compiled from git pulled today (2017-11-29), VS 2015.3 (main menu says build unknown)
Windows 10

_More Info_
This may have been introduced by the 'Added -skipmenu (-sm) flag' change.

`ui.templates.MainMenu` (data/ui/MainMenu.lua) now assumes that the `args` parameter is valid/exists. 
`Pi::Start` (src/Pi.cpp) was changed to provide the `args` parameter, but `doSettingsScreen` (MainMenu.lua:76) does not.

Checking to see that `args` is defined and using -1 for `startPlanetNum` if not seems to work, although there may be something more appropriate:

```diff
 local skipped = false -- should skip menu only once
 ui.templates.MainMenu = function (args)	
-	local startPlanetNum = args.StartPlanetNum
+	local startPlanetNum = -1
+	if args then
+		startPlanetNum = args.StartPlanetNum
+	end
 	
 	-- if number valid and menu not skipped already
```

**Comment by ColdSpirit0** [comment]
@The-EG thanks, I'll test it
