### ISSUE TITLE
New HUD speed readouts negative

### ISSUE THREAD

**Issue by joonicks** [pioneerspacesim/pioneer#4206]
My current speed is 6.51Mm/s.
Im traveling towards my target at a speed of -6.51Mm/s.

Thats not right.
My "speed of approach" is not negative. Defined as "approach" the number should only be negative if im moving away from it.

Either change the tooltip text to "distance to target change" or drop the negative sign.

**Comment by joonicks** [comment]
O, and on the other side as well, "speed of approach towards the frame of reference"

**Comment by caligari87** [comment]
Technically "speed" is never negative, so this should be referred to as velocity, which is a vector indicating both direction and speed. In that sense, it's intuitive: Negative you're taking away from the distance to the target, positive you're adding to the distance. Think of it as distance-delta, not speed.

**Comment by joonicks** [comment]
name any other game which posts "distance-delta" on the hud instead of "speed". the conventional and humanly intuitive way to indicate rate of progress when traveling is to display speed as a positive number.

**Comment by johnbartholomew** [comment]
I found this confusing myself, because the text of the tooltip seems to be in opposition to the sign of the displayed value. The tooltip says "speed of approach", which I would certainly expect to be positive when *approaching* the target.

So I would be in favour of either (a) change tooltip; (b) flip the sign so that the displayed value matches what the tooltip says; (c) change the display to include direction text itself, e.g., "45 m/s toward" vs "28 m/s away" (or some other appropriate word).

Option (c) uses more space in the UI which may be undesirable.

**Comment by caligari87** [comment]
IMO the tooltip should be changed if anything. I personally find `negative==towards` and `positive==away` to be the more intuitive option for displaying the relative velocity.

**Comment by joonicks** [comment]
pioneer has no manual, no tutorial, nothing like that. so removing the tooltips is a really bad idea.
also, whats wrong with showing speed in the hud? is pioneer for casual gamers, or only scientists?

**Comment by impaktor** [comment]
> Honestly I don't think I ever even saw the tooltip when I was learning how to fly with the new UI,

All elements in the new UI have tooltip

> pioneer has no manual,

[Manual (new)](https://pioneerwiki.com/wiki/Flight_UI)
[Manual (old)](https://pioneerwiki.com/wiki/Manual)

**Comment by ecraven** [comment]
I'm open to suggestions, we could change colour of the velocity indicator, if that's more intuitive, but I agree with @caligari87 that negative = getting closer is the most intuitive. I'll adjust the tooltips when I get a bit of time (after christmas, maybe even next year).

**Comment by joonicks** [comment]
youre a weird lot. so when youre out traveling, on a flight for example, you dont ask "how fast are we going?" rather you ask "whats the rate of change in distance to destination?"

**Comment by fluffyfreak** [comment]
> youre a weird lot

hell yeah! 😁
