### ISSUE TITLE
Atmosphere temperature calculation bug (Planet.cpp::GetAtmosphericState)

### ISSUE THREAD

**Issue by joonicks** [pioneerspacesim/pioneer#4216]
### Observed behaviour
Fuel scooping a small gas giant fails. After lots of digging I find that the pressure is too low and the pressure is calculated on, amongst other things, temperature. As you rise through the atmosphere, temperature is supposed to drop. This calculation is done in Planet.cpp::GetAtmosphericState. But the heavy math apparently makes it difficult to get everything right.

With current code, temperature actually rises as you go up. Because a sign that should be - is a +.

Changing the sign fixes the rising temperature and the fuel scooping. However, that might not be all. The calculated air pressure might also be wrong. I just dont know enough about the formula used to see if its correct.

Both Planet::InitParams and Planet::GetAtmosphericState contains potentially buggy code. Preferably a person who knows the formula should take another look at it.

All I can do is to quickfix and throw in a few extra comments.

pioneer-20171001-win32

**Comment by The-EG** [comment]
Fixed, or at least improved by #4946
