### ISSUE TITLE
Accessibility: time acceleration access mouse/keyboard only not mixed

### ISSUE THREAD

**Issue by joonicks** [pioneerspacesim/pioneer#4223]
yeh. Im disabled. paralyzed left hand. on a good day I can glue a left hand finger to control key and apply pressure, but aside from that, please make an alternative for ctrl-click to force acceleration.
right click is unused for instance.

pioneer-20171001-win32

**Comment by impaktor** [comment]
Accessibility is nice to have. 

Perhaps there should also be a wiki-page on recommended key-mapping and tweaks for playing pioneer with one hand? By the way, Maltron seems to have the market when it comes to one-handed key-boards. I've seen it in an episode of Joss Whedon's [Dollhouse](http://www.imdb.com/title/tt1135300/)
![maltron_ergonomic_single_right_handed_keyboard_large](https://user-images.githubusercontent.com/619390/34421356-20feabdc-ec0f-11e7-8efd-8e8d224ba90e.jpg)

(We're a bunch using the Kinesis Advantage 2 board, but it's two handed.)
