### ISSUE TITLE
Lack of verbose debug when loading json data

### ISSUE THREAD

**Issue by joonicks** [pioneerspacesim/pioneer#4226]
Currently when loading json data, there is no feedback at all. Resulting in the game loading and then crashing as soon as a script tries to use a resource from a buggy file.

Any small issue and the whole json file is silently discarded.

Makes it very painful to try and figure out when all it is, is a misplaced \ or " in one of the strings.

Would be a big improvement if the json loader simply said which line it quit on.

**Comment by johnbartholomew** [comment]
Note for whoever works on this: The JSON library we're using has a getFormattedErrorMessages() method... we probably just need to call that and print out the message as appropriate.
