### ISSUE TITLE
Error with hyperdrive sound changes

### ISSUE THREAD

**Issue by johnbartholomew** [pioneerspacesim/pioneer#4228]
Bug in new hyperdrive sound code (#4202). Reported by @nozmajner on IRC. Creating an issue so I don't lose the report.

Lua stack trace:
https://i.imgur.com/k9zNnm4.png

```
<nozmajner> https://i.imgur.com/k9zNnm4.png
<nozmajner> maybe it's useful
<nozmajner> it happens when I'm not using the planner too
<impaktor> Looks like related to jpab's merge of WKFO's sound files?
<impaktor> As in on a branch with not all files there?
<impaktor> Or module with some sound related changes?
<impaktor> Or is it tradeship trying to play the new hyperjump sounds, failing. Should be reproducible then.
<nozmajner> hmm, I'll check that new sound then
<nozmajner> the sound files are in place
* impaktor wonders if tradeship (internal) engine sounds are trying to play
```

**Comment by johnbartholomew** [comment]
@nozmajner If you have any specific reproduction steps or information about which versions (commits/branches) you saw this on that would be helpful. Also if you started from a saved game then if you still have the save file that could be useful.

**Comment by nozmajner** [comment]
Happens on master - f74f870
64bit on windows built with vs2015 with the "Release" preset. Happens on 32bit build too.
Don't need to do much to reproduce, just wait a couple of minutes at any start and it will pop up.

**Comment by johnbartholomew** [comment]
The line number in the stack trace `Equipment.lua:299` does not correspond to the relevant call in the code in commit f74f87014366ca1d91f7927d4f636b7a1b778d61. In master, the call is here (on line 319)

https://github.com/pioneerspacesim/pioneer/blob/f74f87014366ca1d91f7927d4f636b7a1b778d61/data/libs/Equipment.lua#L319

So I think this was caused by a mod, or using scripts that didn't match the binary version.

Perhaps I should have been more careful when changing the code on the C++ side to maintain some compatibility with existing scripts... but that will often be difficult. In this case not actually difficult but it would mean leaving some hardcoded hyperdrive sound effect names in the C++ code.

**Comment by johnbartholomew** [comment]
Closing; please re-open if you hit this again or have some other reason to think it was not caused by using an older version of Equipment.lua with the new binary.
