### ISSUE TITLE
Mission option to set destination for hyperjump should always select the right star in multiple systems

### ISSUE THREAD

**Issue by Another-MrZ** [pioneerspacesim/pioneer#4235]
### Observed behaviour
When undertaking a mission to a multiple star system, the set destination option does not specify the right star, very often resulting in the impossibility to complete the mission and get lost in space.

### Expected behaviour
If we set the destination from the mission option in the BBS adverts list, the target should always select the right star in multiple system (I only now discovered it is possible to specify a particular star in multiple systems, and so it should be done automatically by the system).

### Steps to reproduce
1 Undertake any mission to a multiple star system (Falaphi, for example)
2 Select Set Destination As Navigational Target
3 Hyperjump there and discover your destination is 14064.60 A.U. away

__My pioneer version (and OS):__
Build 20171001 (316a1f7) - Windows 7

### Related issue
Ridiculous missions #2898

**Comment by Gliese852** [comment]
fixed in #5048?
