### ISSUE TITLE
CustomSystem absurd input syntax requirements

### ISSUE THREAD

**Issue by joonicks** [pioneerspacesim/pioneer#4237]
To me its absurd that CustomSystem doesnt accept float numbers and similar but instead forces the human user to do the conversion to "fixed()".

It should rather be the computer that converts "1.2345" to the appropriate internal format. Massive work overload and excellent potential for mistakes to happen.

Also for some values, allowing alternate units to be used shouldnt be much work. Instead of only accepting earth masses and eath radii, etc.

**Comment by fluffyfreak** [comment]
Yep this I totally agree with.
Also we could really do with the system editor #4173 getting finished

**Comment by joonicks** [comment]
this would close with #4238
