### ISSUE TITLE
SystemView planet icons upscaling looks poor

### ISSUE THREAD

**Issue by joonicks** [pioneerspacesim/pioneer#4243]
Right now these icons are upscaled for higher resolution screens,
why cant they rather be downscaled for lower rez screens?

Because of the upscaling, almost all of the current icons look very bland.

**Comment by impaktor** [comment]
Because it's the best we have? 

I assume if some skilled artist shows up that gives us high resolution / scalable art, with consistent feel and theme, that looks better, we use that instead?

**Comment by nozmajner** [comment]
Or ditch them altogather when it comes to that part of the UI rewrite, to keep it in line with the other UI parts:

![](https://i.imgur.com/dcCQClv.png)

**Comment by fluffyfreak** [comment]
Which icons are these?

**Comment by impaktor** [comment]
Downside is, I really like how you get a sense of (probably false) scale between star and planets. This could be implemented with some circle drawing routine of course.

**Comment by joonicks** [comment]
well, reality is a talented artist for our own solar system atleast. wikipedia has a bunch of images that could be used.

**Comment by nozmajner** [comment]
The scaling is logarithmic or something close currently, I think

**Comment by joonicks** [comment]
I think it would be nice if all the planet bitmaps are oversized and then scaled to the appropriate radius when drawn

**Comment by impaktor** [comment]
This issue doesn't really track any bug. It's basically "X doesn't look as good as hoped". There are many such things in pioneer that could look better. Discussion can be taken on dev forum.

Current status: sure, would be nice with amazing looking, scalable images, but maybe we just generate circles to show scale instead.

Let's use the issue tracker to actually track bugs.
