### ISSUE TITLE
Tradeships module causes crash

### ISSUE THREAD

**Issue by clausimu** [pioneerspacesim/pioneer#4253]
### Observed behaviour
Jumping from Epsilon Eridani to Kaptain's Star. Game crashed when entering the new system with the following error message:

error: [string "[T] @modules/TradeShips.lua"]:310: attempt to index field 'starport' (a nil value)
stack traceback:
        [string "[T] @modules/TradeShips.lua"]:310: in function 'getSystemAndJump'
        [string "[T] @modules/TradeShips.lua"]:592: in function 'cb'
        [string "[T] @libs/Event.lua"]:34: in function '?'
        [string "[T] @libs/Event.lua"]:185: in function <[string "[T] @libs/Event.lua"]:180>

Is this related to #4220?

### Steps to reproduce
No idea. Seemed random. I jumped Epsilon Eridani => Kaptain's Star several times to test a new module I'm working on. Never had a problem except this one time.

__My pioneer version (and OS):__
pioneer built from git on 01/03/18 (should include #4220 fix, right?)
OS: openSUSE 43.2

**Comment by joonicks** [comment]
#4220 was for unexplored systems. but I think tradeships.lua does far less checking than it should

**Comment by joonicks** [comment]
can you include some lines from output.txt?

**Comment by joonicks** [comment]
it seems like the intention with "getSystemAndJump" is either to jump to a pre-set destination, or else find one at random and jump. but the author forgot about the "else" part. im not 100% sure, but... it seems to crash any time you get a trader in an uninhabited system.

**Comment by impaktor** [comment]
> it seems to crash any time you get a trader in an uninhabited system.

My gut feeling is that wouldn't this bug be triggered more often then? Or is a pre-set destination very likely to be valid, so it rarely ends up in this place in the code?

**Comment by joonicks** [comment]
two things have to happen at once. a trader needs to pick an uninhabited system to jump to AND the player also needs to jump to an uninhabited system. even players mostly stick to inhabited systems.

**Comment by impaktor** [comment]
> Jumping from Epsilon Eridani to Kaptain's Star.

and

> AND the player also needs to jump to an uninhabited system

So question is if Kaptain's Star uninhabited? (at work now, so can't check)

**Comment by joonicks** [comment]
kapteyns is uninhabited

**Comment by joonicks** [comment]
the rarity could also be compounded by the fact that the trader needs to have arrived in the system before the player. if the player has a faster (longer range) hyperdrive, the trader would still be in hyperspace when the player arrives and there would be no crash.
