### ISSUE TITLE
imgui hud target selection bug

### ISSUE THREAD

**Issue by joonicks** [pioneerspacesim/pioneer#4258]
![hudbug](https://user-images.githubusercontent.com/14345157/34651273-67dad6cc-f3ce-11e7-8ac6-1f3ae7bdbb55.png)
### Observed behaviour

instead of directly targeting the hyperspace cloud, it drops a dropdown menu with multiple instances of "hyperspace arrival cloud", the highlighted line jumps around randomly without player interaction. only the top line can be selected, the others are ghosts.

does not happen on every hyperspace arrival cloud. when I experienced it, it happened only on two, out of about ten.

### Expected behaviour

immediately select the hyperspace arrival cloud, no menu, as it is a single cloud, not several clouds bunched together.

### Steps to reproduce

it happens in every game? click around on different hyperspace clouds, eventually it happens...

current github version

**Comment by richardpl** [comment]
It never happened with internal view for me, but does happen with external views sometimes. Can you confirm?

**Comment by Web-eWorks** [comment]
The list of targets (somewhat) recently got a major revamp that fixed a number of similar issues. If the issue still persists in the latest master, please open a new issue, thank you!
