### ISSUE TITLE
imgui hud mode indicator vanishes after hyperspace

### ISSUE THREAD

**Issue by joonicks** [pioneerspacesim/pioneer#4260]
### Observed behaviour

![missingindicator](https://user-images.githubusercontent.com/14345157/34652406-938b21aa-f3dd-11e7-9fe0-d8d2173946de.png)

after jumping through hyperspace, the "set speed" hud indicator vanishes, although the mode is set correctly.

current github version

**Comment by impaktor** [comment]
ping @ecraven

**Comment by impaktor** [comment]
I've tried setting speed, and jumping. When you exit the ship is in manual mode, as is reasonable.
However, if then clicking "set speed", it doesn't seem to show the frame of reference, unless set/unset I think. Only tried it once.

**Comment by Web-eWorks** [comment]
Fixed on latest master; it correctly resets to manual control.
