### ISSUE TITLE
Text error in menus

### ISSUE THREAD

**Issue by samwj02** [pioneerspacesim/pioneer#4271]
### Observed behaviour
All text (apart from the main menu) is in blocks
Also, top right 'd' in 'Video' is glitched

[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/1619948/opengl.txt)
[output.txt](https://github.com/pioneerspacesim/pioneer/files/1619949/output.txt)

![menuerror](https://user-images.githubusercontent.com/16866674/34788227-ce2b7c00-f631-11e7-8ad5-17be499218dc.JPG)
![normal](https://user-images.githubusercontent.com/16866674/34789812-98bce33c-f637-11e7-9df6-c128de8d6f2a.JPG)

### Expected behaviour
The text should appear normal

### Steps to reproduce
Load up game, click options

__My pioneer version (and OS):__
Windows 10 Pro
Version 2017/10/01 (pioneer-20171001-win32)

**Comment by nozmajner** [comment]
Do you have any HUD software (fps dipslay, steam overlay etc) enabled?

**Comment by samwj02** [comment]
Yes, steam overlay. I've just tried launching it without steam, text appears normal, thanks

**Comment by nozmajner** [comment]
#2931
#3924
