### ISSUE TITLE
Stations won't allow selling of equipment they aren't having due to their tech level

### ISSUE THREAD

**Issue by nozmajner** [pioneerspacesim/pioneer#4276]
### Observed behaviour
I noticed that you can't sell your equipment, if the station doesn't have it due to it's tech level being low. 

### Expected behaviour
One should be able to sell equipment in my opinion, even if the station doesn't trade in it. I might even imagine they would be more than happy to put their hands on it, so they'd pay a bit more for it. Or less, because it's more work for them, and can't really use it anyway.

### Steps to reproduce
Open up the equipment store.

__My pioneer version (and OS):__
2017 Oct 1 official build, Linux64.

**Comment by fluffyfreak** [comment]
Yeah this does seem silly. I mean we could come up with some [handwavium](https://en.wiktionary.org/wiki/handwavium) as to why but for gameplay it's probably nicer to fix it.

**Comment by impaktor** [comment]
Would also allow for more general: if bought custom cargo not available in at this port, create a slot / offering to buy it. I think E:D has some custom stuff like that, E.g "Wine** from Lave"

**Comment by fluffyfreak** [comment]
Yes there are special commodities whose value goes up the further you are from their point of origin. They're usually restricted in number so you can't just fill your hold with them and make billions with a single run.

**Comment by impaktor** [comment]
Anyway, I assume/hope this will be fixed when moving to imgui.

**Comment by impaktor** [comment]
@nozmajner is this stil the case on master? (I might try it out myself tonight).

**Comment by Bodasey** [comment]
is possible in actual master
But what is expected may differ, i'd see it the other way (should not be possible)

read also discussion / test report #5315
