### ISSUE TITLE
New sector view UI cuts off information that was previously displayed

### ISSUE THREAD

**Issue by CampNowhere** [pioneerspacesim/pioneer#4281]
Running screen resolution 1440x900

I used to be able to see "locked" and the required tonnage of fuel when hyperspacing. Now, a few characters are cut off on the right. Is it possible to use fixed width fonts and fixed width fields in these places, so all of the text geometry can be calculated ahead of time? Or at least expand them to sufficient width so chars are never cut off?

![screenshot at 2018-01-17 08-47-38](https://user-images.githubusercontent.com/13381835/35048799-b52b7dc2-fb63-11e7-8812-02738d558a38.png)

Running git branch d1aff684050 Linux x64 compiled w/G++

**Comment by impaktor** [comment]
I used to be able to see "locked"

"Locked" functionallity isn't availabe at this hour. And I mean "this hour", as we'll soon merge it's spiritual successor: #4241

I guess if the player can resize these windows himself, that would solve it? But then I guess idea is that these should not be floating windows on top of sector view.

**Comment by The-EG** [comment]
Yeah, we have stayed away from windows being resizable (by the user). I have played around with windows that automatically size themselves though, so that may be something to look at.
At this point (in master) this should just be an issue with the 'selected' system, right?
