### ISSUE TITLE
random number generator

### ISSUE THREAD

**Issue by joonicks** [pioneerspacesim/pioneer#4295]
going over #4294 I was trying some things on the massive if-then-else block line 175-245
eventually I figured out that trying to optimize it is pointless.
if you call that block 1 billion times, it will take 16651 "milliseconds", of which
0.000292 is spent in the if-then-else and the rest is spent inside rng.

this made me look deeper, and so I noticed this snippet:

`	inline Uint32 Int32(const int choices)`
`	{`
`		return Int32() % choices;`
`	}`

I was taught to never use modulo to get make random numbers fit, but rather clamp the rand
I dont know exactly why, and I think it depends on the prng used.

In any case, for optimizing, it might be better to use rng.Int32() without the parameter to skip the modulo and adjust the values of the if-then-else accordingly,
and in the future remember that 32 bits of randomness is enough to make 32 instances of true or false, etc, using up all of the randomness before asking for a new rand.
maybe even have a worker thread dedicated to precalculating rands to be used wherever possible.

rewriting the code for universe generation to pack the rands better would change the universe I know, maybe have it in mind for the future.

**Comment by joonicks** [comment]
and there is something wrong with the rng because I get this face way too often:

![face](https://user-images.githubusercontent.com/14345157/35365222-92089efe-0173-11e8-81f4-0c7c8486ecfc.png)

personal info screen->make new face

**Comment by joonicks** [comment]
that guy is half of every male face in the bbs also...

**Comment by impaktor** [comment]
> rewriting the code for universe generation to pack the rands better would change the universe I know, maybe have it in mind for the future.

If it makes the code faster and/or gives us less repetition of patterns in the rng then that _could_ (as in _maybe_) be worth it, but random number generators is a very complex field. There are some previous posts here on github where different random number generator algorithms and libraries are discussed.

There should be an open issue already on the "too-common face bug", somewhere, I think.

**Comment by joonicks** [comment]
2017-10-01 build:
Loading took: 13581.841955 milliseconds
Loading took: 13625.652932 milliseconds
Loading took: 13611.957548 milliseconds
Loading took: 13503.981047 milliseconds
Loading took: 13562.480996 milliseconds
Loading took: 13576.624736 milliseconds
~13576

My own branch optimized to avoid touching the rng as much as possible:
Loading took: 12908.667962 milliseconds
Loading took: 13127.239664 milliseconds
Loading took: 12898.973738 milliseconds
Loading took: 12986.559059 milliseconds
Loading took: 12926.675973 milliseconds
Loading took: 13023.772981 milliseconds
~12978

Only sector generation was optimized to avoid rng,
sector generator is only called 10 (!!) times during startup!

Superheavyweight rng...

**Comment by jaj22** [comment]
The RNG should just be this: http://www.pcg-random.org/download.html , although it's encased in a pile of C++11 so compilers may trip up along the way. 

Do make sure that you're not testing without optimization enabled, because that will murder the performance of any fancy code. 13 seconds startup sounds extremely high to me: My current half-debug build loads the Earth start in about 1.5 seconds.

**Comment by joonicks** [comment]
times reported by Pi::Init
`Output("\n\nLoading took: %lf milliseconds\n", timer.millicycles());`

2017-10-01 build is downloaded from pioneerspacesim ofcourse...
so the comparison should be fair since its on the same computer

**Comment by jaj22** [comment]
Oh right, Pi::Init not game init. The milliseconds that aren't milliseconds. Looks like sector generation is called ~100 times there though, not 10? Should be once per faction.

I gave it a run with the profiler because `SectorRandomSystemsGenerator::Apply` didn't look very significant to me. Comes out as 1.5M cycles for 202 calls, which suggests it's double-generating for some reason, but otherwise several hundred times faster than what you measured. I'd guess that there's some other difference between your two test runs.

**Comment by jaj22** [comment]
For reference, some Pi::Init top-level profiling results:

27% `SpaceStation::Init()` (all LoadModel)
20% `FaceParts::Init()`
19% `Graphics::Init()`
13% `Sound::Init()`
10% `LuaInit()`
3% `CityOnPlanet::Init()`
2% `draw_progress()`

Then a few one-percents. Most of these seem reasonable because they're loading and processing bulk data. Graphics::Init() is odd but probably out of our hands.

**Comment by joonicks** [comment]
weee! facepalm! I was running on a patch with modified factions (only 6 of them (independent +5))
here are the numbers with all the old factions included:

Loading took: 13076.226866 milliseconds
Loading took: 13199.941582 milliseconds
Loading took: 13161.927256 milliseconds
Loading took: 13204.867813 milliseconds
Loading took: 13153.821860 milliseconds
Loading took: 13073.494405 milliseconds
~13144 (vs release build ~13576)

it seems to generate sectors once while loading factions and then again right after for some other reason.. odd, shouldnt it be cached?

still if 10 calls take X seconds, optimized 200 calls take 150 "ms" and 200 un-optimized take ~550 "ms" that would put the optimized routines at about ~3.6 times faster, considering lots of sectors are generated (eg, sectorview, scripts doing getnearbysystems, ...) even though the universe created is not identical, no "usability" is lost. I could overhaul starsystem generation in a similar fashion and maybe it would be worth considering breaking the universe to gain the performance.

its hard to run the optimizations on the same data because of some of the other changes. I should also try to isolate the galaxycreation better in the debug.

**Comment by joonicks** [comment]
hot dang. 
`20% FaceParts::Init()`
thats worth a look maybe

**Comment by jaj22** [comment]
FaceParts::Init() is loading 700 small PNGs in about a second, which is maybe not bad.

I get *0.5* milliseconds (1.5 MCycles) for 200 sector generation calls, not 550ms. System generation may well be a couple of orders of magnitude heavier, but I haven't tested it.

**Comment by joonicks** [comment]
facepalm. that should teach me never to try to benchmark across branches. im getting schitzophrenic here I dont know which number is which anymore...

**Comment by joonicks** [comment]
btw, its Pi::milliseconds. the whole of galaxygeneration::init clocks in at a steady 84ms, optimized or not, no difference. I bet most of it has to do with loading the galaxy bitmap.

**Comment by jaj22** [comment]
Galaxy bitmap loading is ~2.5x larger than the sector generation, but still only a small fraction of GalaxyGeneration::Init. Not sure what else is substantial in there. The code's quite confusing.

**Comment by richardpl** [comment]
Can we close this ticket?

**Comment by impaktor** [comment]
> Can we close this ticket?

Yes, the repeated face was a bug discovered and fixed, where same random sequence kept popping up. (I don't remember the fix, but it's merged). 

Also, we have better discussions on rng in some other issue somewhere.
