### ISSUE TITLE
sectorview new gui no longer supports tab

### ISSUE THREAD

**Issue by joonicks** [pioneerspacesim/pioneer#4298]
old gui supported tab to hide forms and info, new gui does not

**Comment by nozmajner** [comment]
A question: what should tab do? Same as before, switching to a faction list to allow filtering? Is it even needed with, or providing that functionality via imgui would be better?
Or it could switch between different view modes eventually? Like some kind of trade analysis screen could be there too for example in the future.

**Comment by joonicks** [comment]
one tab {faction filter list}
![screenshot-20180127-200303](https://user-images.githubusercontent.com/14345157/35475375-ca577844-039d-11e8-862e-4ad22153b80a.png)

**Comment by joonicks** [comment]
two tabs {no gui}

![screenshot-20180127-200306](https://user-images.githubusercontent.com/14345157/35475380-e4302ad6-039d-11e8-89cd-786e89927350.png)

**Comment by joonicks** [comment]
its the nogui screen im crying myself to sleep over

**Comment by ecraven** [comment]
> its the nogui screen im crying myself to sleep over

So, tab would go through the following three states:

- default state: full gui
- only show factions (but also search box??)
- no gui

If you can specify this a bit more fully, I'll gladly implement it
(shouldn't be hard at all).
Especially, what exactly should the "middle" state show?

Greetings, Peter

**Comment by joonicks** [comment]
since factions are now combined with the target ui, itd just be

--default state: full gui
--tab 1: no gui

unless the waypoint system needs extra space and its own tab

**Comment by Marcel-T** [comment]
I've noticed that when the gui is off I can no longer F1 through the ship views. I don't know if it's related or a separate issue.

**Comment by impaktor** [comment]
Fixed, manual close, due to cherry-pick merge of PR above.
