### ISSUE TITLE
Broke hyper jump by attempting to access main menu

### ISSUE THREAD

**Issue by macksting** [pioneerspacesim/pioneer#4302]
### Observed behaviour
Piloting a Vatakara with a class 9 hyperdrive from Beta Hydri to Qua, I attempted to access the menu to turn off the cockpit graphics. Hitting escape twice while in jump, the game crashed, giving a stack trace in a dialogue window.

```
Started hyperspacing...
error: [string "[T] @pigui/modules/hyperjump-planner.lua"]:230: attempt to index upvalue 'current_system' (a nil value)
stack traceback:
	[string "[T] @pigui/modules/hyperjump-planner.lua"]:230: in function 'fun'
	[string "[T] @pigui/game.lua"]:677: in function 'callModules'
	[string "[T] @pigui/game.lua"]:926: in function 'fun'
	[string "[T] @pigui/pigui.lua"]:65: in function 'window'
	[string "[T] @pigui/game.lua"]:910: in function 'fun'
	[string "[T] @pigui/pigui.lua"]:99: in function 'withStyleColors'
	[string "[T] @pigui/game.lua"]:909: in function 'game'
	[string "[T] @pigui/pigui.lua"]:119: in function <[string "[T] @pigui/pigui.lua"]:117>
```

### Expected behaviour
Hitting esc twice should enter the menu without hassle, even in hyperjump.

### Steps to reproduce
Begin hyperdrive jump, hit esc twice.

__My pioneer version (and OS):__
pioneer (build: git (e12a3bd)) in lubuntu 16.04

**Comment by The-EG** [comment]
This should be a simple fix; I'll take a look tonight unless someone beats me to it.
