### ISSUE TITLE
Request: Limit main engine when gear deployed

### ISSUE THREAD

**Issue by Keeper1st** [pioneerspacesim/pioneer#4305]
There are two in-game reasons why doing this would make sense:

1. Safety, as it makes landing maneuvers more predictable and less likely to have a pilot fire the main thruster and forget how much stronger it is, crashing.

2. Ship integrity. The forces caused by the main thrusters could be damaging to extended landing gear which aren't designed for high lateral force. Thus the ship goes into a "landing thrust mode" when the gear is deployed.

I imagine two possible ways this could be implemented. Either change the forward_thrust value to match the reverse_thrust value when landing gear is deployed, or change the forward_thrust, reverse_thrust, left_thrust and right_thrust values to whatever the lowest of those values is on the ship (i.e. make all thrusters -- other than the up and down thrusters -- fire at the strength of the weakest thruster), thus making adjustments predictable to the pilot as the ship descends toward the landing pad.

Naturally there should be a delay when retracting the gear before setting the thruster(s) back to full strength, to match the time it takes for the gear to retract.

The up/down thrusters would be exempt from this, as the gear is designed for vertical forces, and you rather don't want to limit the up thrust so that the pilot can abort and take off safely.

Perhaps the thruster graphic display could be changed from white to yellow when in this mode, as a subtle reminder that your thrusters are in a different condition (for those wondering why they can't get off a planet quickly -- they haven't retracted their landing gear yet!).

**Comment by impaktor** [comment]
Let's track feature requests on dev forum instead:
https://pioneerspacesim.net/forum/viewtopic.php?f=3&t=549

-> Closing.
