### ISSUE TITLE
Cockpit does not show on new game unless F1 cycled

### ISSUE THREAD

**Issue by Keeper1st** [pioneerspacesim/pioneer#4306]
### Observed behaviour
When starting a new game with cockpit enabled, the cockpit does not show unless the user hits F1 to cycle through views back to cockpit view.

### Expected behaviour
The cockpit should be visible immediately.

### Steps to reproduce
Check the Enable Cockpit button in options. Start a new game at any of the three starting points.

__My pioneer version (and OS):__
64-bit Windows build, made on 5 Feb 2018 from master via VS2015. Windows 10 operating system.
Another player has reported the same problem using the release build, while another still reports normal behaviour. Could be a Windows version issue...? The issue did not occur until making the new build.

**Comment by Keeper1st** [comment]
Addendum to this, as it may be related: When starting a new game, if I go straight to the sector view, the map has drawn vertical lines and labels on out-of-range systems even though those options are not selected. I have to select and them deselect them in order to turn them off. This is a similar behaviour to the cockpit not showing until cycling through views (essentially turning it off, then back on).

**Comment by nozmajner** [comment]
For reference: 
[dev froum thread, with .txts](https://pioneerspacesim.net/forum/viewtopic.php?f=3&t=555),
[SSC thread](http://spacesimcentral.com/forums/topic/cockpit-not-visible/)
