### ISSUE TITLE
Game uses save-game commodity info even if starting new game later

### ISSUE THREAD

**Issue by Keeper1st** [pioneerspacesim/pioneer#4307]
### Observed behaviour
When loading a saved game made in an earlier build, the game uses old commodity language info (e.g. in this case with no descriptions). Upon exit of that game and start of a new game, the old commodity language still is in use -- no descriptions. Upon complete restart of Pioneer and starting a new game, the new commodity language file is used, with descriptions.

### Expected behaviour
A newly started game should use the latest commodity language file, and not the one that was loaded in a saved profile earlier in the play session.

### Steps to reproduce
Explained as above (however, the saved profile did have a Trade Computer added to it before this was noticed, so it is possible this behaviour is related to that new feature).

__My pioneer version (and OS):__
Windows x64, built from master on 5 Feb. Windows 10.

**Comment by impaktor** [comment]
If I understand this correctly, this is simply a border case for how old save files function in new version, and I'd personally rather see pioneer dev time spent on propagating the game forward, rather than fixing things that will fix itself as people make new saves in the new version, thereby resolving this issue (assuming my understanding of the description is correct).

I'm willing to close this, if @The-EG doesn't object. 

Alternative fix: we save bump, and don't allow old saves in the new version.

**Comment by The-EG** [comment]
No objection from me. I'm actually surprised it loaded at all, my October build saves would completely crash when I tried to load them in master starting in December or so.
And, if I remember correctly, this is an issue with how the equipment/cargo data is stored so a true fix would be changing that, which would be a change to the save file format itself and not work on old files...

This does give me an idea for a feature for 'importing' old saved games. It'd be very minimal, just the ship (type), location, money and equipment. But that may make save game bumps easier to deal with.

**Comment by Keeper1st** [comment]
Well, it's more an issue of a new game still uses old settings if an old profile had been loaded before a new profile is made, instead of the game loading new files when a new profile is made. It is somewhat minor, admittedly.

Importing of old saves is a nice idea. OK, so maybe the market and things change based on what they were like when you saved, but as long as your ship hasn't changed between versions, the ability to import the ship and your bank account at least would be nice.
