### ISSUE TITLE
form:Clear() does not remove options

### ISSUE THREAD

**Issue by clausimu** [pioneerspacesim/pioneer#4314]
### Observed behaviour
When using form:Clear() to remove any text/title/options from a banter board chat form, everything is cleared but the options.

### Expected behaviour
The options should be cleared from the form with everything else.

### Steps to reproduce
1. Place this short test module into your pioneer/data/modules folder: https://www.dropbox.com/s/zmcilp3npge0nz0/test_chat_form.lua?dl=0
2. Start the game anywhere.
3. Click on the "TESTAD" in the bulletin board.
4. Click on the "DELETE THIS BUTTON" option.

__My pioneer version (and OS):__
pioneer version: git (a4060e849)
OS version: openSUSE 43.2, 64-bit

**Comment by impaktor** [comment]
this aught to fix itself with a move to pigui, (I hope).

**Comment by Web-eWorks** [comment]
At this point, the only thing using the original form code is the missions view in the info screen and that's slated to be removed as soon as someone picks up vakhoir's PR (aka probably me). If the issue persists afterwards, please reopen the issue!
