### ISSUE TITLE
Too small search results for Solar search

### ISSUE THREAD

**Issue by StrikerASD** [pioneerspacesim/pioneer#4318]
### Observed behaviour
When i am in the Sector Map Nav window and i want to find some specific sector like SOL for example, the results window is badly visible. I can only see top of the letters and not entire ones. When i scroll i still see only a fragment of text. 

### Expected behaviour
When sector is inputed, then results should be visible in at least 5 lines with scroll abitily, now it's 30% of the first line. 

### Steps to reproduce
Launch the game,  start the campaign and go to Sector View window, in the search menu type some sector and see what happens in the results window below the search window.

__My pioneer version (and OS):__

pioneer-20180203-win32

**Comment by nozmajner** [comment]
Could you post a screenshot, and your screen resolution?

**Comment by StrikerASD** [comment]
Screen resolution is 1366x 768 on Intel Graphics card. The Sector Screen has a scroll bar next to sector information and search bar. I can do screenshot but it's blank.

**Comment by StrikerASD** [comment]
Later in the night i will have opportunity to test it better on 1920 x 1080 screen with NVidia graphics card on FreeBSD - same game version though.

**Comment by StrikerASD** [comment]
@nozmajner, i confirm that  the problem is with resolution. I've checked this on 1920 x 1080 and results are working fine. Below is a screenshot from the correct results window.

**Comment by impaktor** [comment]
@StrikerASD so no bug? Then please feel free to close this issue. Otherwise, a screenshot of the actual bug/issue would be illustrative.

(supporting all resolutions isn't possible, but if it's something common then we should.)

**Comment by StrikerASD** [comment]
i've reduced the resolution to 1024 x 768 and the search results are still visible. Only on my laptop with Intel graphics at a higher than mentioned resolution search results are not visible. It might be due to the graphics driver or some other issue. On my stationary computer with NVIDIA GTX 560 ti there are no problems even on lower resolutions than on laptop

**Comment by nozmajner** [comment]
1366*768 is a quite common laptop resolution, so I'd consider it a bug.

**Comment by fluffyfreak** [comment]
1366*768 might be an aspect ratio bug, it's "widescreen"
