### ISSUE TITLE
Crash upon clicking "Options" in start menu

### ISSUE THREAD

**Issue by dnbarbato** [pioneerspacesim/pioneer#4326]
### Observed behaviour
When I click "Options" in the start menu pioneer crashes with the following error message:

```
error: [string "[T] @ui/Settings.lua"]:36: UI.DropDown.SetSelectedIndex: invalid index 1 specified
stack traceback:
        [C]: in function 'SetSelectedIndex'
        [string "[T] @ui/Settings.lua"]:36: in function <[string "[T] @ui/Settings.lua"]:25>
        (...tail calls...)
        [string "[T] @ui/Settings.lua"]:84: in function 'template'
        [string "[T] @ui/Settings.lua"]:370: in function 'template'
        [string "[T] @libs/ui/TabView.lua"]:130: in function 'SwitchToNum'
        [string "[T] @libs/ui/TabView.lua"]:96: in function 'AddTab'
        [string "[T] @ui/Settings.lua"]:377: in function 'Settings'
        [string "[T] @ui/MainMenu.lua"]:78: in function <[string "[T] @ui/MainMenu.lua"]:76>
```

It also crashes when I press ESC twice during the game in order to get to the "Options" menu with the following error message:

```
error: [string "[T] @ui/Settings.lua"]:36: UI.DropDown.SetSelectedIndex: invalid index 1 specified
stack traceback:
        [C]: in function 'SetSelectedIndex'
        [string "[T] @ui/Settings.lua"]:36: in function <[string "[T] @ui/Settings.lua"]:25>
        (...tail calls...)
        [string "[T] @ui/Settings.lua"]:84: in function 'template'
        [string "[T] @ui/Settings.lua"]:370: in function 'template'
        [string "[T] @libs/ui/TabView.lua"]:130: in function 'SwitchToNum'
        [string "[T] @libs/ui/TabView.lua"]:96: in function 'AddTab'
        [string "[T] @ui/Settings.lua"]:377: in function <[string "[T] @ui/Settings.lua"]:51>
        (...tail calls...)
```

__My pioneer version (and OS):__
My pioneer version is 20180203 (This does not happen with version 20171001) and I run GuixSD (GNU/Linux).

**Comment by impaktor** [comment]
If I'm not mistaken, this is the NewUI, which we don't have anymore, so not relevant anymore.

And you must be doing something very unique or strange, as simply entering the menu doens't crash the game for anyone else.

Have you opened the files? accidentally changed something?

**Comment by impaktor** [comment]
I'm closing this as the code no longer exists, and this must be some user error, or corrupt installation.

**Comment by dnbarbato** [comment]
> I'm closing this as the code no longer exists, and this must be some user error, or corrupt installation.

@impaktor Thank you for having looked into this.  I am sorry for wasting your time.

**Comment by impaktor** [comment]
No problem, thanks for reporting.

If you compile from source it should work.
