### ISSUE TITLE
Game won't launch when choosing a localized language

### ISSUE THREAD

**Issue by Tichy** [pioneerspacesim/pioneer#4327]
### Observed behaviour
I previously selected the Italian language from the setting screen. When launching Pioneer the game exits with this error
![screenshot_20180425_183511](https://user-images.githubusercontent.com/2348771/39259726-85e547d6-48b7-11e8-98d7-e5ae527904a9.png)

If I modify Lang=it to Lang=en in config.ini, the game starts correctly.

### Expected behaviour

That the game starts. :)

I saw this issue earlier. It happened when there were untranslated strings. In this case I don't see untranslated strings in transifex for my language. Anyway, I don't even see string that have to be translated for the easter egg module.
What I expect is that the game starts correctly even when there are untranslated strings, and reverts to default english for those.

### Steps to reproduce

Change Lang=en to it, de, pl or others in config.ini and launch the game.

__My pioneer version (and OS):__

Pioneer version 20180203.r33.g22063c289-1
OS: Arch Linux

**Comment by impaktor** [comment]
Hopefully, within a few hours, this will start to be populated, fixing the bug:
https://github.com/pioneerspacesim/pioneer/tree/master/data/lang/module-easteregg-message

**Comment by impaktor** [comment]
DONE! 
78e140c41168f1004a123f815bf3c39f55486bf4
