### ISSUE TITLE
Orbiting the Black Hole Sagittarius A*  from 0.01AU altitude shows the Black Hole as white

### ISSUE THREAD

**Issue by Sthrenor** [pioneerspacesim/pioneer#4330]
### Observed behaviour
Orbiting the Black Hole Sagittarius A*  from 0.01AU altitude shows the Black Hole as white.

### Expected behaviour
Don´t really know. Light is supposed to be trapped, so no light can reach the ship.

### Steps to reproduce
Orbiting the Black Hole as near as possible to the surface in circular orbit. 

__My pioneer version (and OS):__
Pioneer 20180203 (Win7-64)

**Comment by WKFO** [comment]
Some visual: https://www.youtube.com/watch?v=4ar-iLXbv1o
Although I don't have much info, might be the camera clipping into "terrain".

**Comment by Sthrenor** [comment]
![screenshot-20180518-213703](https://user-images.githubusercontent.com/39418775/40268338-d66a1ae4-5b6b-11e8-9399-bc0dacfac113.png)

**Comment by fluffyfreak** [comment]
Ok I know these visual bugs, the odd clipping is a precision limitation.
The star/black hole is just too massive for the way we're rendering it, I think that I know of a fix.
The other issue, that the black hole is white is probably just some stupidity on our part, will look into it.

**Comment by impaktor** [comment]
I wonder what the black hole _should_ look like? Just a black sphere? 

(Yeah, I know about Interstellar, and the equations, published papers, and all that goodies)

**Comment by fluffyfreak** [comment]
Hmm, this was my fault back in #3434, a slight case of over optimisation!

**Comment by fluffyfreak** [comment]
Still don't know why it's rendered bright white though, but it's probably my fault too :D

**Comment by fluffyfreak** [comment]
Ok, I know why that is too, terrain stuff. Got a fix WIP will post later

**Comment by fluffyfreak** [comment]
Resources for future reference
https://unionassets.com/blog/the-effect-of-the-gravitational-lens-195
https://medium.com/@mariosubspace/blackhole-shader-in-unity-eb7d93af9577
http://spiro.fisica.unipd.it/~antonell/schwarzschild/
