### ISSUE TITLE
Crashes on load

### ISSUE THREAD

**Issue by blane1257** [pioneerspacesim/pioneer#4333]
Crashes when loading into new game

pioneer version:  20180203
OS: windows 7 with amd processor and ATI Radeon HD 5450 display adaptor

**Comment by impaktor** [comment]
And what's the error message?

**Comment by blane1257** [comment]
There is no error message. theres just a windows popup that says "pioneer has stopped working"

it doesnt happen until about 5 seconds in

**Comment by impaktor** [comment]
I assume the game you want to load is from an earlier version of the game?

**Comment by blane1257** [comment]
I just downloaded the game for the first time

**Comment by impaktor** [comment]
Is the crash repeatable? Meaning, if you start a new game, and save, and load that game it crashes?

**Comment by blane1257** [comment]
it happens every time. and im not loading a save, im booting it up and selecting one of the start at (location) options. i've not been able to save as i've not been able to play it

**Comment by impaktor** [comment]
Quick fix should be to disable the auto save (options/settings menu).

Does it happen for all three starting locations?

**Comment by blane1257** [comment]
yes. i'll try that

**Comment by blane1257** [comment]
auto save is already disabled

**Comment by impaktor** [comment]
Oh, OK, I thought you were trying to load a saved game. 

Then I assume your graphics card is not compatible, or something. Please have a look at the https://pioneerwiki.com/wiki/FAQ for finding the specs we need for your graphics card, and post here.

**Comment by blane1257** [comment]
well it works for a solid 5 10 seconds and its not really even that laggy then it crashes, so that doesnt seem right

**Comment by blane1257** [comment]
and im not too sure what you want me to do on that site

**Comment by impaktor** [comment]
https://pioneerwiki.com/wiki/FAQ#How.2Fwhere_do_I_report_my_bug.2Fcrashhttps://pioneerwiki.com/wiki/FAQ#How.2Fwhere_do_I_report_my_bug.2Fcrash

**Comment by blane1257** [comment]
@fluffyfreak

**Comment by blane1257** [comment]
what??

**Comment by blane1257** [comment]
can someone please help me?

**Comment by impaktor** [comment]
Please calm down. It's midnight for the entire dev team now. usual respons time is days, I answered your first post in 14 seconds, and the rest in 5 minute intervals. 

Please wait and see what @fluffyfreak says, when he has time.

**Comment by blane1257** [comment]
ok. i was confused because i'm unfamiliar with this site.

**Comment by jaj22** [comment]
Lack of compressed texture formats is interesting (and rather bizarre. I'm sure the hardware's capable), although I'd have expected an earlier crash if that was an issue.

**Comment by fluffyfreak** [comment]
@jaj22 I've seen that before with AMD drivers :( they really do support a whole bunch of compressed formats, just don't report them.

**Comment by blane1257** [comment]
sooo is there anything i can do? :/

**Comment by impaktor** [comment]
@blane1257 I don't know, but try it on another machine, or maybe try running it with a lower version of opengl, see the FAQ for how to set renderer.

**Comment by fluffyfreak** [comment]
I don't think it's the graphics, the ATI Radeon HD 5450 should be able to handle what we use of OpenGL 3.x ok.

There's been any number of bug fixes gone in since February.

**Comment by fluffyfreak** [comment]
@blane1257 You could try setting the line `AMD_MESA_HACKS=0` to `AMD_MESA_HACKS=1` in the `config.ini` file. It should be right beside the `output.txt` you posted earlier.

It limits some texture sizes, simplifies some shaders and things like that.

**Comment by fluffyfreak** [comment]
hmm, you could also try setting `GL3ForwardCompatible=0`, but really I'm guessing at this point.

**Comment by blane1257** [comment]
Neither of the config.ini solutions have worked

**Comment by blane1257** [comment]
i pulled out the ships, it's still crashing.

**Comment by fluffyfreak** [comment]
Ok, two more entries to try, find these entries and set themt o following values:
EnableGLDebug=1
EnableGPUJobs=0

Also perhaps an obvious question but do you have the latest drivers for your graphics card installed?

**Comment by blane1257** [comment]
I believe I do. And that doesn't seem like the problem considering the game does run for 5-10 seconds before crashing. I'll try those values.

**Comment by blane1257** [comment]
after changing those values, it is no longer crashing. i dont seem to be able to control the ship however...

**Comment by blane1257** [comment]
nevermind, its working

**Comment by fluffyfreak** [comment]
Ok, it looks like the `EnableGPUJobs=0` is the probable fix for you, the other you can change back to default :)
