### ISSUE TITLE
Remove some labels

### ISSUE THREAD

**Issue by Garmelon** [pioneerspacesim/pioneer#4382]
There are a lot of tags, and not all of them are used much. This is a list of all labels and their usage at the time of writing this issue:
```
Label                     || Amount    || Suggested for removal
--------------------------||-----------||----------------------
Art                       ||   6 | 111 ||
Bite-sized                ||   2 |  11 ||
Bug fix                   ||   0 | 210 ||
Build                     ||   2 |  49 ||
C++ code                  ||   3 |  16 ||
Cleanup                   ||   2 | 192 ||
CONFIRMED                 ||  16 | 308 ||
Cosmetic or UI            ||  49 | 247 ||
Crash or hang             ||   4 | 255 ||
Design                    ||  11 |  81 ||
Documentation             ||   1 |   1 || <--
Feature request           || 115 | 219 ||
in progress               ||   1 |  25 ||
Input                     ||  19 |  19 ||
Language                  ||   3 |  96 ||
Lua API                   ||   0 |  10 ||
Lua code                  ||   0 |  25 ||
Model system              ||  10 |  52 ||
More information required ||   0 |  33 ||
New feature               ||   0 | 207 ||
Optimization              ||   0 |  21 ||
Platform Specific         ||   3 |  24 ||
Re-assessment requested   ||   0 |  31 ||
ready                     ||   0 |   0 || <--
Save issue                ||   0 |   1 || <--
Savegame bump             ||   0 |  22 ||
To do                     ||  23 | 104 ||
UI rewrite                ||  62 |  88 ||
Unexpected behaviour      ||  34 | 281 ||
unknown                   ||   0 |   3 || <--
Upstream issue            ||   0 |   1 || <--
WIP                       ||   5 |  63 ||
```
The "Amount" colums are `|| open | closed ||`
Some tags which are not used a lot could maybe be removed.

**Comment by ecraven** [comment]
I agree with this, I think we have too many labels (or just don't use them enough). I'd remove even more, but those four would be a good start, and we wouldn't lose much history.

**Comment by impaktor** [comment]
My suggestions:

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-left" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">Label</th>
<th scope="col" class="org-right">Amount</th>
<th scope="col" class="org-right">&#xa0;</th>
<th scope="col" class="org-left">Suggested for removal</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">Bug fix</td>
<td class="org-right">0</td>
<td class="org-right">210</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">Lua API</td>
<td class="org-right">0</td>
<td class="org-right">10</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">Lua code</td>
<td class="org-right">0</td>
<td class="org-right">25</td>
<td class="org-left">?</td>
</tr>


<tr>
<td class="org-left">More information required</td>
<td class="org-right">0</td>
<td class="org-right">33</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">New feature</td>
<td class="org-right">0</td>
<td class="org-right">207</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">Optimization</td>
<td class="org-right">0</td>
<td class="org-right">21</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">Re-assessment requested</td>
<td class="org-right">0</td>
<td class="org-right">31</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">ready</td>
<td class="org-right">0</td>
<td class="org-right">0</td>
<td class="org-left">x</td>
</tr>


<tr>
<td class="org-left">Save issue</td>
<td class="org-right">0</td>
<td class="org-right">1</td>
<td class="org-left">x</td>
</tr>


<tr>
<td class="org-left">Savegame bump</td>
<td class="org-right">0</td>
<td class="org-right">22</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">unknown</td>
<td class="org-right">0</td>
<td class="org-right">3</td>
<td class="org-left">x</td>
</tr>


<tr>
<td class="org-left">Upstream issue</td>
<td class="org-right">0</td>
<td class="org-right">1</td>
<td class="org-left">x</td>
</tr>


<tr>
<td class="org-left">Documentation</td>
<td class="org-right">1</td>
<td class="org-right">1</td>
<td class="org-left">x</td>
</tr>


<tr>
<td class="org-left">in progress</td>
<td class="org-right">1</td>
<td class="org-right">25</td>
<td class="org-left">x</td>
</tr>


<tr>
<td class="org-left">Bite-sized</td>
<td class="org-right">2</td>
<td class="org-right">11</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">Build</td>
<td class="org-right">2</td>
<td class="org-right">49</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">Cleanup</td>
<td class="org-right">2</td>
<td class="org-right">192</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">C++ code</td>
<td class="org-right">3</td>
<td class="org-right">16</td>
<td class="org-left">?</td>
</tr>


<tr>
<td class="org-left">Language</td>
<td class="org-right">3</td>
<td class="org-right">96</td>
<td class="org-left">x</td>
</tr>


<tr>
<td class="org-left">Platform Specific</td>
<td class="org-right">3</td>
<td class="org-right">24</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">Crash or hang</td>
<td class="org-right">4</td>
<td class="org-right">255</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">WIP</td>
<td class="org-right">5</td>
<td class="org-right">63</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">Model system</td>
<td class="org-right">10</td>
<td class="org-right">52</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">CONFIRMED</td>
<td class="org-right">16</td>
<td class="org-right">308</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">Input</td>
<td class="org-right">19</td>
<td class="org-right">19</td>
<td class="org-left">?</td>
</tr>


<tr>
<td class="org-left">To do</td>
<td class="org-right">23</td>
<td class="org-right">104</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">Unexpected behaviour</td>
<td class="org-right">34</td>
<td class="org-right">281</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">Cosmetic or UI</td>
<td class="org-right">49</td>
<td class="org-right">247</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">UI rewrite</td>
<td class="org-right">62</td>
<td class="org-right">88</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">Feature request</td>
<td class="org-right">115</td>
<td class="org-right">219</td>
<td class="org-left">&#xa0;</td>
</tr>
</tbody>
</table>

Combine?

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-left" />

<col  class="org-right" />

<col  class="org-right" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">Label</th>
<th scope="col" class="org-right">Amount</th>
<th scope="col" class="org-right">&#xa0;</th>
<th scope="col" class="org-left">Suggested for removal</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">Design</td>
<td class="org-right">11</td>
<td class="org-right">81</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">Art</td>
<td class="org-right">6</td>
<td class="org-right">111</td>
<td class="org-left">&#xa0;</td>
</tr>
</tbody>
</table>

-   I don't know what "Input" is, keyboard/mouse?
-   Art and Design could be combined? ping @nozmajner?
-   Do we need the C++ / Lua labels?
-   "Language" &#x2014; I suspect this is pre-transifex when translations were done
    manually through git. Can be removed.

**Comment by nozmajner** [comment]
Isn't "New feature" supposed to mean "Hey, here's a new feature I made!"
I'd say Art and design could be combined, provided the design is not referring to Game design. I'd prefer "Art"

**Comment by nozmajner** [comment]
I'd rename it "Game design" then and remove the ones that doesn't belong. If we want any design discussion on github, that is.

**Comment by impaktor** [comment]
I removed most of what we agreed on here. Left art/design as is. Feel free to change those if motiviated.
