### ISSUE TITLE
Radial menu activates autopilot when there is none

### ISSUE THREAD

**Issue by WKFO** [pioneerspacesim/pioneer#4386]
### Observed behaviour
The radial menu activates the autopilots on ships which has no autopilots.

### Expected behaviour
Don't activate the autopilot if ship doesn't have an autopilot installed.

### Steps to reproduce
Start the game, sell your autopilot, and use radial menu to activate autopilot.

__My pioneer version (and OS):__
Latest github master, Linux Mint + Win10

**Comment by csildev** [comment]
From looking at the code it seems that in the code for the radial menu, the autopilot is getting set without a check to see if the player has an autopilot (data/pigui/pigui.lua#L591)

**Comment by csildev** [comment]
I'm working on a temporary fix that checks for an autopilot on the current ship before activating the autopilot function, but the code should probably disable the options on the menu if there is no autopilot.

**Comment by csildev** [comment]
The fix looks like it is working correctly but someone should probably verify it.

**Comment by csildev** [comment]
A question I do have about the fix is whether the game should still set the target as navtarget if there is no autopilot.

**Comment by fluffyfreak** [comment]
Fixed by #4404
