### ISSUE TITLE
[Feature Request] New minimal flight display mode

### ISSUE THREAD

**Issue by Jummit** [pioneerspacesim/pioneer#4389]
I like it that you can press tab to hide the gui, but it is not usable for flight because you cant see some really important HUDs. I would like to fly with near to no gui, and a display mode where only the 'cursor' and the diamond like shaped orientation icons are shown.

**Comment by impaktor** [comment]
We don't use the issue tracker for feature requests.

Hiding UI is mainly for screenshots.

**Comment by Garmelon** [comment]
What is the feature request label for then?

**Comment by impaktor** [comment]
It's a remnant. When you open an issue, the pre-filled template says to leave feature requests on the forum. Sorry if I sound short, but each feature request opened pushes bugs down the list, and adds weight to our shoulders.

Anyway, @Jummit we've discussed your suggestion in IRC, and it's in the back of our minds, when working on that code.
