### ISSUE TITLE
Dual weapons don't fire from correct positions

### ISSUE THREAD

**Issue by fluffyfreak** [pioneerspacesim/pioneer#4397]
When equipped with dual pulse weapons, the shots fired eminate from unexpected locations on the ship or outside of the ship.

This can easily be seen here where one shot seems to be coming from outside of the ship entirely.
![badpewpew](https://user-images.githubusercontent.com/825083/44235201-a0d5b700-a1a0-11e8-86e8-26d028222cd6.png)

In truth they're BOTH incorrect because they are centred around, and then offset from, the `gun_mount_0` tag within the model heirarchy which is beneath the right wing.

In this particular situation the `gun_mount_0` tag's position should/could be mirrored around the ships local position in model space and no offset applied. Then each shot would behave as though it was coming from beneath each wing.

This might not apply to all models, and some models have the `gun_mount_0` along the centre-line of the ship therefore requiring the existing fixed offset.

**Comment by nozmajner** [comment]
What if I put in gun_mount_dual_0 and _dual_1 tags to the models for these? So there's precise per model control. Or that would complicate things a lot?

**Comment by fluffyfreak** [comment]
That'd be great, I guess it'd be best to use a ship with front and rear gun mounts that are already offset, like the Wave? But any ship will do.

**Comment by nozmajner** [comment]
[Here's a sinonatrix with those gun tags.](https://www.dropbox.com/s/0vi5iujcxtafj56/sinonatrix.dae?dl=0)
I named the empties 
gunmount_0_multi_0 gunmount_0_multi_1 for front and 
gunmount_1_multi_0 gunmount_1_multi_1 for rear.

**Comment by fluffyfreak** [comment]
@nozmajner PR is up but doesn't include any ship data.
I also had to make some changes to that data because any tagged entry must start with the word `tag_` so the gunmount entries now look like `tag_gunmount_0_multi_0`.

**Comment by nozmajner** [comment]
Ok, I'll update the ships somewhere along the weekend and make a PR
