### ISSUE TITLE
Lighting of ships inside stations

### ISSUE THREAD

**Issue by WKFO** [pioneerspacesim/pioneer#4399]
I'm kind of suprised no one opened this issue before.

### Observed behaviour
Inside of the space stations are pretty bright, but ships are not illuminated by the station so they become black after the station goes to the dark side of the planet, while the internal walls of the stations stay bright. I know stations don't have actual light sources and the lighting is just a texture trick or sth, but it just feels very wrong.

### Expected behaviour
Perhaps stations should illuminate the ships inside.

### Steps to reproduce
Dock with a station on the night side of a planet.

__My pioneer version (and OS):__
Latest github master

**Comment by nozmajner** [comment]
Yes, it is a known issue. @Fluffyfreak thought about how you could solve it if I'm correct, but not sure how far he got.
The problem is, the station inside aren't lit at all, it is shadeless, and all lighting information is on the texture. Which won't look good on ships in my opinion.
Not that I think of it, maybe it could be done by placing  a (couple of) virtual sun inside the station with some range setting, and ramp up the ambient light level, as you go inside. No cast shadows and such nuissance. Would that work?

**Comment by ConfedMajor** [comment]
I hate this a lot, one time, i entered a station in a system that has a red dwarf, and it was beneath the station...

The ship looked like half black, half red... it was pretty weird...

If the lightning has shadow casting, the station will go completely dark (or maybe a little bit with light if a star is in front of the exit or enter)

So, that is why stations should have inner lights, and also this is why pioneer should have shadow casting, but this is a very very very expensive thing for a OpenGL game

**Comment by fluffyfreak** [comment]
My plan was just to turn off the lighting, or transition it from lit, to unlit and thus rely on the baked in diffuse material lighting as you got "inside" a station.

I mean I had other, more complex ideas, but i thought that one was achievable relatively easily

**Comment by Keeper1st** [comment]
Maybe the easiest way for that is to have it stop lighting/shading on ships once they are set to docked state on a spacestation (but not a ground station). It would mean they stay dark until they dock, of course, but rarely would a player see another ship moving inside a station (other than the player's own -- but that's what you get for not flying "first person"!). I imagine that would be a kind of quick-fix without having to do any really complicated stuff.
