### ISSUE TITLE
Update The Cmake Files to Handle Windows Builds

### ISSUE THREAD

**Issue by csildev** [pioneerspacesim/pioneer#4406]
Since VC2017 does not come with the windows 8.1 SDK anymore it might make more sense to have it compile against the windows 10 SDK in that case.

EDIT This is no longer valid. We are now trying to convert everything to cmake instead.

**Comment by impaktor** [comment]
(assuming VC=Visual Studio Code?):

I think the idea is to remove all VC now, that we merged CMake yesterday. VC can make use of CMake.

In fact, it would be great with a PR that removes all VC stuff from pioneer (if that's possible at this moment in time?), updates COMPILING.txt with how to build on windows using Visual Studio by pointing it to CMake.

**Comment by csildev** [comment]
Yes, VC is Visual Studio. I can remove the VC files from pioneer but it will require a change to the cmake file to point it at the pioneer-thirdparty repository if the user is on windows, but that should be pretty easy. The SDK is just which version of the OS API is being used by the program and doesn't really change much, but the program usually requires a certain version when compiling.

**Comment by impaktor** [comment]
If you can make it compile on windows 10, and windows 7 (with whatever VC version makes the most sense) by not relying on VC specific config files in pioneer, that would be very good indeed.

**Comment by fluffyfreak** [comment]
Please, do not remove the VC files from the project until I've had a very good chance to test all this.

I think that I'm almost the only one using them so I'd like to be 100% sure that everything works before they get pulled from beneath my feet.

**Comment by csildev** [comment]
After looking at the cmake configuration it is totally over my head to do anything with the cmake files because of the nonstandard way pioneer-thirdparty is setup.

**Comment by fluffyfreak** [comment]
Should't CMake always be looking for pioneer-thirdparty? That is one reason why we have it after all.

Yes, doing the Windows Visual Studio config using CMake seems like a horrendous task. You can't even build some of the libraries statically on Windows due to their developers not supporting it. I know because I've tried.

**Comment by pcercuei** [comment]
I started to work on that. The blocker right now is that pioneer-thirdparty does not have a prebuilt libsigc++.

**Comment by impaktor** [comment]
#4634
