### ISSUE TITLE
Building with system GLEW library may still use bundled header files

### ISSUE THREAD

**Issue by johnbartholomew** [pioneerspacesim/pioneer#4409]
Copying from my comment on #4391 (after I had merged it):

> Unfortunately I just found a problem with this. For most of the build, the contrib/ directory is in the include path. We have source files that include "glew/glew.h", which works for the local glew because it finds it (in contrib/glew/glew.h). However, the system header is /usr/include/GL/glew.h. That obviously won't be found at "glew/glew.h"; it would be found at <GL/glew.h>.
>
> So I think with this patch and when configured to use system glew this will actually link against the system library but use the header from the contrib/ library. That will cause a version skew problem except for people who are "lucky" enough that their installed system glew version exactly matches the one we've bundled.
>
> We'll need to move the headers around in contrib/ so that the include structure is more uniform and then conditionally add contrib/glew (or whatever) to the include path when we're using the bundled copy. Or some other fix.

**Comment by pcercuei** [comment]
This is what I get now:

 CMake Error at /usr/share/cmake-3.12/Modules/FindGLEW.cmake:50 (set_target_properties):
   set_target_properties can not be used on an ALIAS target.
 Call Stack (most recent call first):
   CMakeLists.txt:88 (find_package)

**Comment by johnbartholomew** [comment]
CMake Error at /usr/share/cmake-3.12/Modules/FindGLEW.cmake:50 
    (set_target_properties):
    set_target_properties can not be used on an ALIAS target.
    Call Stack (most recent call first):
    CMakeLists.txt:88 (find_package)

The ALIAS is only created in the `if (NOT USE_SYSTEM_LIBGLEW)` branch, and find_package(GLEW) is only called in the `if (USE_SYSTEM_LIBGLEW)` branch. I'm not sure how they could end up both running and conflicting like this.

Perhaps something weird happens if cmake configure is run with one config and then run again with a different config? cmake does a bunch of variable caching... maybe it's caching some information about targets.

**Comment by pcercuei** [comment]
You're right, it seems to be a problem of caching. I used ccmake and toggled the variable between OFF and ON.

**Comment by pcercuei** [comment]
Why did you set an alias anyway? Setting GLEW_LIBRARIES like I did before 5af8061ee8541a2a92876b76b13609ca905a6b3c didn't work?

**Comment by johnbartholomew** [comment]
I'd like to move toward target-based rather than directory/variable-based CMake structure. Target based structure is the widely recommended modern way and avoids unintentionally sharing build settings between different parts of the dependency graph. The basic idea, as I understand it (having just been reading up on it recently) is that each library/whatever is a target, all the build settings for the library and for other targets which use the library (e.g., include directories, preprocessor flags, etc) are attached to the target with appropriate PUBLIC/PRIVATE/INTERFACE scope, and then dependencies between targets are set up with target_link_libraries, and all the build settings get collected together by CMake as part of following those dependencies.

See also:
https://youtu.be/rLopVhns4Zs?t=38m55s (Daniel Pfeifer - "Effective CMake" talk)
https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/
https://gist.github.com/mbinna/c61dbb39bca0e4fb7d1f73b0d66a4fd1#using-a-library-defined-in-the-same-cmake-tree-should-look-the-same-as-using-an-external-library

Since we're setting all this up effectively from scratch it seems like a good opportunity to try to make it relatively clean and maintainable.

But having said that, the GLEW_LIBRARIES thing worked fine as far as I know, so if we can't work out how to make the alias play nice with cmake's configuration cache then we should go back to the old way.

**Comment by fluffyfreak** [comment]
How does all of this work with the MXE cross compiler that we use for Windows builds?

**Comment by pcercuei** [comment]
Should be easy: https://mxe.cc/#tutorial (step 5b)
