### ISSUE TITLE
The game crashes when hovering over corrupt save files

### ISSUE THREAD

**Issue by 42triangles** [pioneerspacesim/pioneer#4415]
### Observed behaviour

The game crashes when hovering over save files that are either corrupt or can't be opened for read access.

### Expected behaviour

The game doesn't crash, but displays a warning instead.

### Steps to reproduce

Manually corrupt a save file or `chmod -r` it, and hover over a save file in the main or pause menu.

__My pioneer version (and OS):__
commit 86cfa671887e57cca70983f8b05a6ea1918c1f65 in this repository, NixOS (Linux)

**Comment by johnbartholomew** [comment]
Fixed by #4416.
