### ISSUE TITLE
Pioneer crashes when sorting for distance in the F4 menu in the Quin system

### ISSUE THREAD

**Issue by 42triangles** [pioneerspacesim/pioneer#4422]
### Observed behaviour

Pioneer crashes when you sort for the distance between you and the targets in the F4 menu in the Quin system.

### Expected behaviour

Pioneer doesn't crash, but sorts for distance.

### Steps to reproduce

* Start at earth
* Buy 4t of hydrogen
* Jump to the Quin system
* Press F4
* Press the button for sorting for the distance between you and the targets

__My pioneer version (and OS):__
commit d50f1ee301cf0c9478e47ecdff1446d3d7ee499a in this repository, NixOS (Linux)

**Comment by fluffyfreak** [comment]
@ecraven Crash happens in the `system-overview-window` indexing a `nil` value for a `body`
