### ISSUE TITLE
configuration file does not exist

### ISSUE THREAD

**Issue by ironclad202** [pioneerspacesim/pioneer#4425]
i used to play Pioneer without problems but since i changed my OS from Winxp to Win7 everytime i try to play the game this error pops out:

"error: Pioneer can not run on your graphics card as it does not appear to support OpenGL 3.1
Please check to see if your GPU driver vendor has an updated driver - or that drivers are installed correctly."

i read that in order to play the game with an older OpenGL version you just have to go to the configuration file (config.ini) in my documents/pioneer and set: "RendererName=Opengl 2.1" but in that folder the only files are the output file and a folder named mods but i can't find the config file nor Opengl.txt the output text file only has this:
```
ver 20180203 (038a2a4) on: Windows

Hardware information: 
  		OEM ID: 0
  		Number of processors: 2
  		Page size: 4096
  		Processor type: 586
  		Minimum application address: 00010000
  		Maximum application address: 7ffeffff
  		Active processor mask: 3

Windows 7 (Service Pack 1)


--------------------
SDL Version (build) 2.0.4
SDL Version (dynamic) 2.0.4
SDL Versions match
SDL_image Version (build): 2.0.0
SDL_image Version (dynamic): 2.0.0
SDL_image Versions match
Assimp Version: 3.2.100100829
FreeType Version: 2.6.3
--------------------

error: Pioneer can not run on your graphics card as it does not appear to support OpenGL 3.1
Please check to see if your GPU driver vendor has an updated driver - or that drivers are installed correctly.
```
but the configuration file is nowhere to be found, can somebody please help me solve this i want to play this game again really bad.

my pioneer version is: pioneer-20180203-win32

**Comment by nozmajner** [comment]
Try running pioneer like this from the command line (cmd)
pioneer.exe -g RendererName=Opengl 2.1
In theory it should override any default setting, and allow the game to run and create the ini, if the renderer made it stuck before it can do that.

**Comment by nozmajner** [comment]
You could also try creating the ini and entering only the opengl line in it.

**Comment by impaktor** [comment]
@ironclad202 did you solve this issue? If so, please smash close button below.

**Comment by ironclad202** [comment]
i finally discovered the problem: the last time i played Pioneer was in the early 2012 wich means that at that time it was on alpha i downloaded a version from the 2012 and it runned perfectly. the problem is that my computer doesn't even have OpenGL  2.1 but 1.4 that is the reason i couldn't play the new versions, my computer is just too old to support the game.

**Comment by impaktor** [comment]
OK, we've just moved from 2.1 to 3.1 I think. A pioneer-capable second hand computer shouldn't cost more than a couple of 10-euro bills, I'm guessing. (or just get a second hand graphics card), if you want to play pioneer. 

2012, that's oooooold.
