### ISSUE TITLE
[Feature Idea] "Hybrid Mode" GUI

### ISSUE THREAD

**Issue by Web-eWorks** [pioneerspacesim/pioneer#4433]
I ran across [this article](http://forums.ltheory.com/viewtopic.php?f=30&t=6582&sid=2882bb2ff011172e9cd2d358908a676c) recently. It's about implementing a so-called "hybrid mode" GUI on top of Dear IMGUI, and I thought it might be worth looking at for the UI system. Obviously, this should not be seriously considered until the UI has stabilized somewhat, but I think that __optional__ automatic sizing and layouting for UI elements would be a _very_ useful feature for anyone who wants to write UI code - either in a mod or as part of the core.

Thoughts, comments, general mutterings from the overworked UI maintainers?

**Comment by impaktor** [comment]
I think we need to finish current tripple-UI migration first. 
- F8 Lua Galaxy -> imgui
- F3-F4 Lua station screens -> imgui
- F6-F7 C++ econ/system/orbit info views (from F2/sector map) -> imgui

**Comment by impaktor** [comment]
I've read the Limit Theory Post now. So the point is he's mixing RMGUI (Retained Mode GUI) with IMUI (Immediate Mode GUI) into a Hybrid Mode: HMGUI.

Relevant points from the post:

> So...where's the catch? Surely there can be no free lunch. Well, HMGUI isn't really a free lunch: of the retained, immediate, and hybrid paradigms, hybrid mode takes the most work to implement. That's not surprising when you consider that, under the hood, HM is just a clever mixing of IM and RM, thus requiring much of the implementation work of both.

and

> One might also point out that, of the three, HM consumes the most CPU time, due to the fact that it involves all of the CPU work of IM plus the layout work of RM

(yeah, I've left out the pro-part of the HMGUI....)

Personally, I'll take code that's easy to understand, maintain, and extend, any time of the day, over nice looking or fast code, considering the enormous undertaking the UI migrations have been. A thousand times over, actually. The first UI migration started 2013(?) or something and after several years came to a stand still (thus we still have pure C++ "OldUI"/Frontier-clone-UI _and_ lua defined "NewUI" -- not to be confused with the third UI: IMGUI).

I'm in no position to make any decisions, but I think we better take any further discussion on the dev-forum, so feel free to write up your ideas there, if you want to discuss it further, and throw ideas around.

**Comment by fluffyfreak** [comment]
I agree, converting the existing UI(s) to IMGUI and ripping out the old stuff has definitely got priority
