### ISSUE TITLE
Translation of star system descriptions

### ISSUE THREAD

**Issue by WKFO** [pioneerspacesim/pioneer#4434]
I'm diagnosed with missing translation OCD (you don't know how ugly it looks). I had to open this because we have more custom systems now.

### Complaint:
System descriptions are directly written to the Lua file in English, not as a proper Lang module.

### Fix:
Add a star_system lang module and make it possible to translate system descriptions.

**Comment by nozmajner** [comment]
I'd add to it that it should be still possible to enter plain text to the description field, to not hinder modding. Even better would be if the mods could provide their own lang entries somehow, but I'm not sure how many modders would also include translations.

**Comment by impaktor** [comment]
I think this is non-trivial as the Lua-thread that loads the star systems is not the same as the one with the translations. It's not as simple as just adding a module, like it is with the other strings.

Also, I suspect we already have an open issue on this.

**Comment by WKFO** [comment]
Maybe, it is very possible that I didn't see the previous issue.

**Comment by impaktor** [comment]
Double: #2867
