### ISSUE TITLE
Language file en.json missing "UNDOCKING"

### ISSUE THREAD

**Issue by bram1253** [pioneerspacesim/pioneer#4456]
> pioneer/data/pigui/modules/saveloadgame.lua line 69
`elseif stats.flight_state == "undocking" then ret = ret .. lui.UNDOCKING`

`UNDOCKING` is not defined in pioneer/data/lang/ui-core/en.json
This results in the game crashing to desktop.

-------------------------------

Playing on Linux Mint 19, compiled binary.
Last git commit when compiled: 1deda53f2e51519b33d718099c4036e53d306b6e .

**Comment by impaktor** [comment]
Looks like the `lui.UNDOCKING` should be `lc.UNDOCKING`
