### ISSUE TITLE
Upgrade JsonCpp to nlohmann/json

### ISSUE THREAD

**Issue by Web-eWorks** [pioneerspacesim/pioneer#4458]
As I briefly discussed on IRC, I may have found the magic bullet here. [nlohmann/json](https://github.com/nlohmann/json) is an alternative Json implementation featuring a much more intuitive API and some really really tempting features over our current JsonCpp.

Before I get into pros and cons, I'd also like to remind anyone reading this that our JsonCpp hasn't been updated since 2010, which is a very long time.

**Pros:**

- It's much faster, more standards-conformant, uses much less memory, and has a smaller binary size. (https://github.com/miloyip/nativejson-benchmark)
- It has a more intuitive API; there's no need for the explicit asX methods, as it uses C++ conversion operators.
- It supports a number of features we don't really use right now but might in the future (JsonPointer, JsonPatch, etc.)
- It supports automatically transforming a JSON tree into CBOR. This means we don't *ever* need to write _yet another_ serialization path when we switch.
- And the best of all: it supports half/float/double internally, only converting them at the serialization step. This means that a round-trip from C++ to CBOR will be bit-correct for all our floating point numbers, allowing us to entirely drop the DoubleToStr calls.

**Cons:**

- There are 598 lines of JSON-related code in `src/` I'd have to upgrade. Not really a big deal, as I can get it done fairly quickly.
- It's a header-only library, so there's now 18,800 lines of C++ header to compile instead of 1800 for our current JsonCpp. This might result in slightly increased compilation times, but it shouldn't be too bad.

I'm... really not seeing a downside here, are you?

cc @fluffyfreak @johnbartholomew

**Comment by laarmen** [comment]
Just for the record : just because a lib hasn't been updated for 8 years,
doesn't mean that it should be upgraded. Typically, old code has known
bugs, whereas new code has unknown bugs, just waiting to be discovered.

I am *not* saying this shouldn't go in, I'm pointing out that the last
argument might actually work in favor of the current solution.

Le lun. 24 sept. 2018 à 14:33, Webster Sheets <notifications@github.com> a
écrit :

**Comment by fluffyfreak** [comment]
A quick skim and it looks interesting. I'll try to take a longer look this evening.

I don't think that it changes the need for #4454 as that's just a case of being intelligent about what actually gets saved/loaded and is long overdue for review.

**Comment by Web-eWorks** [comment]
@fluffyfreak this is complimentary to that issue. This is just the natural follow-up to the save file changes.
Depending upon merge order, you may need to re-write your PR to take advantage of the new Json API; if it gets merged before I start implementation, I'll update it as I go.

@laarmen Old code also typically has known vulnerabilities, and doesn't take advantage of new language features or optimizations. That being said, I agree with you.

**Comment by Web-eWorks** [comment]
Yet another bonus is that we will no longer need to explicitly check for `isMember()` and pollute the code with `throw new SaveGameCorruptException()`, as a combination of automagic objects and type errors handle that for us. A single `try {...} catch (Json::type_error &e) { ... }` block will make the loading code much easier.

**Comment by Web-eWorks** [comment]
Yet more bonus is that for the cases in which we are using exactly a IEEE-754 double, the C++<->JSON round-trip is _guaranteed_ to be perfectly accurate; entirely obsoleting the DoubleToStr methods. This is a compiler-dependent thing, but I believe all major compilers implement their `double` type as IEEE-754 doubles.

**Comment by fluffyfreak** [comment]
I think one problem with this is that I've been able to avoid saving/loading a lot of data out thanks to those `isMember` checks. For example we're storing a *lot* of zero vectors, identity matrices/quaternions and other structures which are set to their default values sometimes.

Will we be able to extract it to human readable JSON? This has been very useful in figuring out what's actually going into our save files.

**Comment by Web-eWorks** [comment]
Actually, all of the isMember checks I have dropped were immediately followed by a `throw SavedGameCorruptException()`. We still keep the functionality to have optional values, but required values are nicer to work with now.

I'm working on extracting to JSON now - it's extraordinarily simple.
