### ISSUE TITLE
Radial autopilot menu only works in the F4 list

### ISSUE THREAD

**Issue by nozmajner** [pioneerspacesim/pioneer#4467]
### Observed behaviour
The autopilot radial menus only work properly on the F4 list. On the UI itself. If you try to use it on the name next to the reticule or next to the body icon in worldview, the mouse will jump back to the center, and while doing that it picks the option from the menu, which is on that direction, and you can't pick another.

### Expected behaviour
The radial menu to work properly on all three cases, like in the F4 menu, allowing the player to pick the proper autopilot command.

### Steps to reproduce
Select a target, right click either to it's name on the right side of the reticule, or at the body indicator to call the radial menu. Try to pick any option other than what happens to be on the closest direction to the screen center.

__My pioneer version (and OS):__
[2df911d](https://github.com/pioneerspacesim/pioneer/commit/2df911dc2a70592cd54eb3e36820ff51621a5f09)

**Comment by Web-eWorks** [comment]
@nozmajner could you test again against the latest master? I believe this should be fixed now.

**Comment by nozmajner** [comment]
Yup, it works properly for me.
