### ISSUE TITLE
Scroll bars for icons on HUD cover icons/items and are unnecessary

### ISSUE THREAD

**Issue by clausimu** [pioneerspacesim/pioneer#4468]
### Observed behaviour
Three icons/indicators on the HUD show scroll bars (see screenshot) that cover half of the icon and are pretty much useless. I'm sure they are not intended to be there?

![screenshot_20181009_124654](https://user-images.githubusercontent.com/10633178/46685264-0eabc700-cbc3-11e8-8692-5e26dbb0092e.jpg)

### Expected behaviour
No scrollbars for items on the screen that don't need them.

### Steps to reproduce
Start on Mars (or probably anywhere?). The first two covered icons are visible right from the start, the other becomes visible when you start flying and open the F4 window.

__My pioneer version (and OS):__
OS: openSUSE 43.2
Pioneer: built from latest git files (42dc2be58)

**Comment by nozmajner** [comment]
What's the resolution of the game?

**Comment by WKFO** [comment]
I have the same problem, resolution: 1360 x 768

**Comment by clausimu** [comment]
Good question, @nozmajner. I have tried at different resolutions now (1600x1200, 1400x1050, 1280x1024, 1024x768) and I get the scroll bars at different places, depending on which resolution I use. But they are always there at least in some areas. Also, the start screen menu does not resize with a resolution change and only displays correctly at 1024x768. With increasing resolution, more and more of the start menu is hidden and needs to be accessed by a scroll bar (which looks really ugly).

**Comment by Web-eWorks** [comment]
Looks like the static `ui.screenHeight` finally strikes. I was wondering when that was going to happen.

This is something that's going to take some fairly significant design work to properly resolve, but the good news is that it's fairly easy to work around it by adjusting the constants in the appropriate Lua UI code.

If someone wants to take a crack at this, your best shot is going to be tracking down which Lua file draws these elements (in `data/pigui/modules`) and adjusting the constant sizes near the top of the file. I'm not going to be available to fix this myself for a while, but anyone else is welcome to it.

**Comment by fluffyfreak** [comment]
Isn't `ui.screenHeight` a function though? It gets mapped to `l_attr_screen_height` in `LuaPiGui.cpp` in `pigui.lua` so every call to it should be getting the real scree height from the C++ code.

**Comment by Web-eWorks** [comment]
Which works fine until you realize that it's usually called _once_ at the top of a Lua file and then never called again. There are some issues with the UI code I really want to resolve, and this is one of them.

**Comment by Gliese852** [comment]
The problem seems to be that the button's window size is being saved in the config file (**imgui.ini**). The game starts by default in the resolution of 800 by 600, and the window sizes are stored in the configuration file. If you further increase the resolution, the sizes of the windows under the buttons remain small, buttons do not fit in the space provided, and scroll bars appear. 
If you delete the **imgui.ini** after increasing the resolution and start the game, the scroll bars disappear and everything becomes beautiful. And in the new file it can be seen that the window sizes for the buttons have increased.
I will try to fix it.
