### ISSUE TITLE
Start menu is scaled up with resolution change

### ISSUE THREAD

**Issue by clausimu** [pioneerspacesim/pioneer#4469]
### Observed behaviour
The start menu and the mouse-over texts are scaled up when increasing the resolution. This makes the text awkwardly large on high resolutions and the menu does not fit in the designated space any more. This may relate to #4468, but I wanted to give it its own report. See screenshots below for just menu or menu + mouse-over text for two resolutions: 1024x768 and 1400x1050. I kept the other desktop windows in the screenshot for size comparisons.

1024x768
![screenshot_20181010_164929](https://user-images.githubusercontent.com/10633178/46765621-79d1c800-ccad-11e8-9845-53a4eb3e39e2.png)
![screenshot_20181010_164916](https://user-images.githubusercontent.com/10633178/46765627-7cccb880-ccad-11e8-9310-754c5e2a1b01.png)

1400x1050
![screenshot_20181010_164758](https://user-images.githubusercontent.com/10633178/46765630-7f2f1280-ccad-11e8-90dd-4ecb882bb041.png)
![screenshot_20181010_164816](https://user-images.githubusercontent.com/10633178/46765634-80f8d600-ccad-11e8-875b-15925f8dc718.png)

### Expected behaviour
Text size should stay constant with different resolution. Or at least should not change so much that it becomes awkward and widgets don't fit their designated space any longer.

### Steps to reproduce
Start the game at different resolutions.

__My pioneer version (and OS):__
OS: openSUSE 43.2 (64bit)
pioneer: latest git build (42dc2be58)

**Comment by fluffyfreak** [comment]
@Web-eWorks I guess this is a result of the updated IMGUI lib too?

**Comment by Web-eWorks** [comment]
@fluffyfreak I don't think so. You're welcome to do regression tests against pre-IMGUI-update Pioneer, but my gut says this one's been here for a while.
