### ISSUE TITLE
Lua Advert crash

### ISSUE THREAD

**Issue by fluffyfreak** [pioneerspacesim/pioneer#4472]
### Observed behaviour
![another-lua-error](https://user-images.githubusercontent.com/825083/46916897-b0af2300-cfb8-11e8-9f09-28987f97c38b.png)

When jumping from system-to-system testing a branch (#4444) I found this issue.
Jumps were Sol->Sirius->Quan->Midaeth, however since the adverts are randomly generated I've not been able to reproduce it yet.

Windows 10, branch #4444

**Comment by impaktor** [comment]
YAY! "Guru meditation error!" :smile:

**Comment by impaktor** [comment]
Relevant stuff has been re-written since this issue.
