### ISSUE TITLE
Overlapping objects in system overview

### ISSUE THREAD

**Issue by quickdudley** [pioneerspacesim/pioneer#4473]
[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/2481771/opengl.txt)
![overlap](https://user-images.githubusercontent.com/5417572/46998230-6c6d7f80-d17e-11e8-80f4-492eef22e1c7.png)

### Observed behaviour
In the system overview for some systems (such as Gliese 667) some objects overlap.

### Expected behaviour
Maybe 667B could be rendered lower in order to make space for all the stations orbiting Kilne's Dream

### Steps to reproduce
Select Gliese 667 in the sector map, and then switch to the system overview.

ver 20180203 (038a2a4) on: Linux

**Comment by impaktor** [comment]
I believe this has already been reported before, but thanks.

**Comment by nozmajner** [comment]
Still agood point to keep in mind when this screen goes imgui.
