### ISSUE TITLE
Compile crash

### ISSUE THREAD

**Issue by clausimu** [pioneerspacesim/pioneer#4475]
### Observed behaviour
When compiling the latest git version I get the following error:

```
make[3]: Entering directory '/games_usb/pioneer/src/graphics/opengl'
  CXX      GenGasGiantColourMaterial.o
In file included from ./../../Json.h:7:0,
                 from ./../../JsonUtils.h:7,
                 from ./../../Propulsion.h:11,
                 from ./../../ShipType.h:12,
                 from ./../../Ship.h:14,
                 from GenGasGiantColourMaterial.cpp:10:
../../../contrib/json/json.hpp:129:14: error: #error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"
             #error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"
              ^
Makefile:433: recipe for target 'GenGasGiantColourMaterial.o' failed
```

This happens after much compilation has already taken place, so I doubt it is actually an "unsupported GCC version."

### Expected behaviour
Should compile completely.

### Steps to reproduce
Sync repo with latest main repo on git. Compile. Enjoy.

__My pioneer version (and OS):__
openSUSE 43.2 (64-bit)
latest git version of pioneer (as of this evening)

**Comment by fluffyfreak** [comment]
pinging @Web-eWorks

**Comment by jaj22** [comment]
The nlohmann JSON documentation claims support for GCC 4.8+, but the code (line 128 of json.cpp) specifies 4.9+. OpenSUSE 43.2 apparently defaults to GCC 4.8.5 although it provides 5/6/7 as options. 

Either the code or documentation for nlohmann JSON is wrong. I wouldn't know which. I guess you could try changing line 128 and see if it works.

**Comment by Web-eWorks** [comment]
The JSON library we use requires full support for C++11 features. GCC 4.8's C++11 support is _not_ feature complete, and has some bugs that directly impact the functioning of that library. If you wish to compile pioneer, you will need GCC 4.9 or newer.

@jaj22 I'm not sure where you're seeing that the documentation allows GCC 4.8; the list of supported compilers is right on the front page, and it explicitly talks about the issues GCC 4.8 has.

**Comment by clausimu** [comment]
I updated to GCC 7 and everything is fine now. #4475 can be closed.
