### ISSUE TITLE
Crash on Remove Jump in Route Jump

### ISSUE THREAD

**Issue by abazaba23** [pioneerspacesim/pioneer#4484]
### Observed behaviour
On the Sector Map screen, If you click the Remove jump [-] button on your Route Jump list AFTER clearing a route, the game crashes to desktop. This does not happen when you click Remove jump and the list is empty.
### Expected behaviour
Nothing happens, or remove jump button becomes inactive. Works as expected if clicked before making a route.

### Steps to reproduce
* Auto-route to any system OR route a single jump
* Select last jump
* Remove all jumps one by one
* Remove jump again after removing all jumps.

(Wow I said jump a lot. My first issue, hello everyone!! 😄)

__My pioneer version (and OS):__
20180203 downloaded from website.
Windows 10 version: 10.0.17134 Build 17134

**Remove Jump is fine with no route**
![img1](https://user-images.githubusercontent.com/21320940/47466710-5f1c4a80-d7a7-11e8-99e8-797d251fee34.png)

**After removing all jumps, and extra click causes crash**
![img2](https://user-images.githubusercontent.com/21320940/47466712-60e60e00-d7a7-11e8-93ce-74b75a2f65a1.png)

**Comment by abazaba23** [comment]
If you give me an idea of where to look, I can give it a shot. I'm still pretty new to open source but I am half way through college currently, maybe I could fix it :)

**Comment by abbottjord94** [comment]
I was trying to debug with gdb on Ubuntu but was unable to reproduce it on
that version. I'd start with debugging, try to see if it will give you an
explanation when it does crash. I've been working on setting up my MS
Visual Studio but having some difficulties with the dependencies.

I'm also a college student too so I'm right there with you :)

**Comment by abbottjord94** [comment]
Update: After building the current source code in VS2017, I was not able to reproduce the error. The function that removes jumps from the list in SectorView.cpp seems like it should work as intended.

I think this issue can be closed; it seems to me that the release on the site should be updated, that's all.

**Comment by WKFO** [comment]
Just thought about it, it's been quite a while since the binary build releases on the website have been updated, eh?

Lots of bugs have been fixed, and some new unpleasant things were introduced (most notably #4468). I don't know what you people are thinking about this, but I think we should have a release as soon as the notable bugs are fixed.

People without compilers have been waiting for beam lasers and stuff, you know...

**Comment by laarmen** [comment]
Well, that's true. OTOH we don't have a proper recipe for releases, now
that our build system has been completely overhauled, and IMHO we can't ask
the owner of our current building box (@robn) to do the work, as he's
already been more than kind enough to provide us with the builds thus far.
