### ISSUE TITLE
Unable to set shift key as a key binding in the controls window

### ISSUE THREAD

**Issue by cwyss** [pioneerspacesim/pioneer#4488]
### Observed behaviour

In the options->controls window it is not possible to set <right shift> as a key binding. After clicking on "Binding" or "Alt Binding", the dialoge that appears does not react when I simply press the shift key. I can bind shift + a normal key though, e.g. <shift + /> by pressing / while holding shift.

### Expected behaviour

Be able  to set <right shift> (and <left shift> too) as key binding, since it is also used in the default bindings.

### Steps to reproduce

Start pioneer, go to options->controls, choose "Binding" or "Alt Binding" for any function you like.
(I tried to set right shift as an alt binding for LowThrusters.

__My pioneer version (and OS):__
173b11adf

**Comment by Web-eWorks** [comment]
The use of the shift key to toggle low-power mode is hard-coded in the ship controller and is not subject to the usual rules for binding inputs at this time. If you wish to select the right shift key, you will need to change ShipController.cpp and/or edit the config file manually.

The inability to bind a modifier key (shift, alt, ctrl...) on its own is a known hold-over from the input system upgrade and is slated to change at some point. The planned replacement is a key-chord system, allowing the use of up to three arbitrary keys (or other key-like inputs, e.g. gamepad buttons) in a binding.

**Comment by Web-eWorks** [comment]
This functionality has been implemented as of current master.
