### ISSUE TITLE
Alert status SHIP_FIRING not working properly

### ISSUE THREAD

**Issue by WKFO** [pioneerspacesim/pioneer#4489]
### Observed behaviour
When a ship starts shooting around in the vicinity of player, the alert status does not change to red (a.k.a. SHIP_FIRING in the code), even if the player gets hit. However, if the player starts shooting back, the alert does change.

### Expected behaviour
Alert status changes to red whenever someone shoots.

### Steps to reproduce
In game, press Ctrl + F12.

__My pioneer version (and OS):__
Last GitHub commit: 0bfde7e

**Comment by Web-eWorks** [comment]
@WKFO see Ship.cpp, line 982. Changing that to:
```cpp
Uint32 gunstate = ship->GetFixedGuns()->IsFiring();
```
Should fix the issue. I can't test it myself right now because I'm in the middle of a refactor - please feel free to open a PR if it works.

**Comment by WKFO** [comment]
Looks like it works.
