### ISSUE TITLE
Missing OpenGL 2.1 shader: shaders/gl2/lmr-dirlight.frag

### ISSUE THREAD

**Issue by stamasd** [pioneerspacesim/pioneer#4493]
Trying to make Pioneer work on an old laptop with built-in GMA3600 video. It only supports OpenGL 3.0 (not 3.1), no driver updates since 2013 - I'm running the latest. I checked out a fresh copy of the SVN yesterday and compiled in VS2017-community, no errors compiling. 

However the binary wouldn't start, error message "failed to set video mode: could not create OpenGL context". I enabled OpenGL 2.1 mode by adding "RendererName=Opengl 2.1" to config.ini. Still get the same error box. 

Stderr has the following:
"Error: Error compiling shader: shaders/gl2/lmr-dirlight.frag:
Compile failed.""
There is no file lmr-dirlight.frag in data/shaders/gl2

I'm attaching stdout.txt, stderr.txt and opengl.txt

[stdout.txt](https://github.com/pioneerspacesim/pioneer/files/2566803/stdout.txt)
[stderr.txt](https://github.com/pioneerspacesim/pioneer/files/2566804/stderr.txt)
[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/2566806/opengl.txt)

**Comment by impaktor** [comment]
> resh copy of the SVN 

git source tree I assume you mean...

2.1 was dropped in September. We should update the wiki. Checkout a version prior to September, and recompile and it should work. Check the Changelog of the commit you checkout to see when/if it was dropped.

**Comment by stamasd** [comment]
Yes, git source (used svn to checkout from git tree :))
I checked several revisions back going all the way to 2013, I can't find that file in any of them.

**Comment by impaktor** [comment]
https://github.com/pioneerspacesim/pioneer/blob/master/Changelog.txt
