### ISSUE TITLE
Error compiling shader: shaders/opengl/multi.frag

### ISSUE THREAD

**Issue by shmerl** [pioneerspacesim/pioneer#4494]
The game doesn't start on Linux, AMD Vega 56, current Mesa master.

```
error: Error compiling shader: shaders/opengl/multi.frag:
0:168(51): error: invalid input layout qualifier used
0:168(69): error: invalid input layout qualifier used
OpenGL vendor: X.Org
OpenGL renderer string: Radeon RX Vega (VEGA10, DRM 3.27.0, 4.19.0-rc7-amd64, LLVM 8.0.0)
```

OpenGL:

```
OpenGL renderer string: Radeon RX Vega (VEGA10, DRM 3.27.0, 4.19.0-rc7-amd64, LLVM 8.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.0.0-devel (git-dd0172e865)
OpenGL core profile shading language version string: 4.50
OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.0.0-devel (git-dd0172e865)
OpenGL shading language version string: 4.50
```

**Comment by shmerl** [comment]
[opengl.txt.zip](https://github.com/pioneerspacesim/pioneer/files/2610008/opengl.txt.zip)

**Comment by fluffyfreak** [comment]
Interesting, it appears to have given you an OpenGL 4.5 core context `OpenGL shading language version string: 4.50` which probably won't work.

We ask for an OpenGL 3.1 context because that's what our shaders will build against.

**Comment by shmerl** [comment]
4.5 is the current one, so I guess it gives whatever the current one is?

**Comment by laarmen** [comment]
Usually drivers implement the whole chain of OpenGL versions, not just the
latest one. Well, at least I think that's how it works ?

**Comment by shmerl** [comment]
They implement all of course, and newer should contain older. You can check OpenGL 3.1 extensions, and they should be present.

**Comment by shmerl** [comment]
See https://mesamatrix.net for radeonsi

**Comment by orbea** [comment]
No issues with the `20180203` release with my AMD RX Vega 56 here and a recent mesa commit, I'll try updating pioneer later to confirm it doesn't break in newer versions.

Requesting a 3.1 core context means you need at least a 3.1 core context, mesa and other video drivers will give a newer core context if available.

**Comment by impaktor** [comment]
As I understand it, it's not a problem on pioneer's side, so closing for now, as evidently the discussion here has reached its conclusion.
