### ISSUE TITLE
Prepare a new release and document the process

### ISSUE THREAD

**Issue by laarmen** [pioneerspacesim/pioneer#4496]
It's been a while since we've had a new release, and that's a shame. However, our build system has evolved quite a bit, and I've basically been told that we don't know how to do releases anymore.

The process might simply be "tag a commit, wait for defined $people to build on their respective platforms, upload the builds, then do the whole website/twitter/stuff dance", but it still has to be documented.

Oh and I'm not volunteering.

**Comment by fluffyfreak** [comment]
Few reasons we haven't done this, I've been waiting on #4427 to be finished but @pcercuei seems to have been away a lot. It's a real shame as I think it'll be a great addition to the build process.

The CMake stuff has taken a while to work but I think that's now ready. I haven't been following along too closely since I want it to work on Linux (_and OSX?_) before I even try to use it with Visual Studio.

I've got a branch of #4427 and have just tried to update it to master, so I'll give that a go and see if it creates a usable windows package after merging latest into it.

**Comment by pcercuei** [comment]
I'm still here, just travelling around without a computer. I will be back next week.

**Comment by fluffyfreak** [comment]
I have a fork of the branch with latest code, some hacking around in it but it does produce an installer now. Hopefully I'll test tomorrow.

Hope you're having fun @pcercuei, I look forward to you getting back us getting this integrated :)

**Comment by impaktor** [comment]
Do remind me:

1. OSX builds still depend on @salborrelli or @Philbywhizz building and uploading, right?

2. And if we use appveyor for windows builds and github for GNU/Linux build, only OSX will be hosted on sourceforge?

**Comment by fluffyfreak** [comment]
Sort of:

1. OSX has been @Philbywhizz the last few times.
2. Appveyor we'd only use for building not as host, it auto deletes after 6 months and there's a 1GB size limit. Each build is ~330MB for Windows.

**Comment by pcercuei** [comment]
@fluffyfreak: this is with #4427 rebased on top of master?

**Comment by fluffyfreak** [comment]
@pcercuei that's with my own branch which has some other hacking in it. So rebasing atop #4427 might be better

**Comment by abbottjord94** [comment]
Genuine noob question: If I'm able to build from source on a given platform and pack it into a .7z file (and document the whole process), is that acceptable? 

I ask because I can build for Windows and Linux (without CMake though), and I'd be happy to provide both of them if that's what we're looking for.

**Comment by impaktor** [comment]
@abbottjord94 Thanks for the offer, but no. We can also build on linux and windows, after all, that's how we do our development. The idea is to get it automated.

**Comment by pcercuei** [comment]
Making the Windows release should be a matter of publishing the setup.exe built by AppVeyor once PR #4427 is updated and merged.

For Linux, the JSON and appdata files at https://github.com/flathub/net.pioneerspacesim.Pioneer should be updated, then the software appstores of (recent) Linux distributions will provide the update. Additionally a .flatpakref (~10-lines text) file can be provided for download on Pioneer's main page, which will open with the distribution's software appstore. The actual build would be hosted for free on Flathub.

For OSX... I don't know. I have experience with creating OSX bundles in CMake, maybe we could setup Travis to build Pioneer just like we will do on Windows with Appveyor. Then the release process would be the same as for Windows, just download and publish a build artifact.

**Comment by laarmen** [comment]
IMO this is actually a regression for our users compared to the
previous ad-hoc setup (which was simply a tarball) : you now need at
some point administrative access to your computer.

**Comment by pcercuei** [comment]
Actually you can install flatpaks as user, from the command line at least (from the GUIs I think they are installed system-wide). Note that we can very well release as a tarball as well, and on the website, just notify that a flatpak version is also available.

**Comment by laarmen** [comment]
I'm not saying that there is no upside to flatpaks, I'm just wary of
regressions, and want to make sure that's taken into account. I'm not
particularly wild about pointing our users to something that's generated
and hosted by a third-party, too, if I understood correctly what's going
on, but then again that's also what we would be doing with the Windows
setup anyway, except for the hosting part.

**Comment by Web-eWorks** [comment]
Tarball (well, zipfile) Linux builds via Travis are already complete in master, the Travisfile just needs a repo key to upload the release binaries to the GH release. The rest of the builds are outside of my realm of expertise, so I can't comment on them.

**Comment by pcercuei** [comment]
Should it be automatically uploaded to github then? We can also do that from appveyor.

**Comment by Web-eWorks** [comment]
I'm in favor of uploading all binaries to the appropriate Github release, and mirroring full releases (e.g. no RCs or pre-alpha builds) on the website/sourceforge proper.

Travis can handle that for both our Linux and macOS builds (assuming we get the previous OSX maintainer to port their build process to the Travisfile), and Appveyor can handle the Windows side of things.

To move forward at this point, @pcercuei needs to finalize the Appveyor setup, @impaktor or @ecraven needs to generate a API token with write access to the repo's releases (see Travis/Github docs for the process), and I need to write this all down in `PUBLISHING.txt` or similar.

Once we have builds from Appveyor and Travis successfully uploading to github releases (aka tags), the PR manager is responsible for uploading the build artifacts to Sourceforge, writing up the new release announcement, and broadcasting the news on Twitter/Mastodon/wherever.

**Comment by impaktor** [comment]
> and I need to write this all down in PUBLISHING.txt or similar.

I'd vote to have the documentation on wiki or something. Not sure the documentation of how we, the devs, publish the builds need to be in the source tree.

> writing up the new release announcement

Usually, Changelog.txt is the only thing we use + I publish the highlights on twitter.

> needs to generate a API token with write access to the repo's releases 

Yeah, I gave them a look but it wasn't obvious to me what needed to be done. I don't know much about euthentication keys, and whatnot, and I didn't follow the jargon of the docs, i.e. I need doc to understand the doc. I'm sure others understand it better.

**Comment by laarmen** [comment]
I'm rather partial to having this documented in the source tree. This
documentation is conceptually similar to COMPILING.txt, IMHO. Otherwise,
this all sounds good to me.

**Comment by impaktor** [comment]
> I'm rather partial to having this documented in the source tree.

OK, fine. your wish is my command...

**Comment by pcercuei** [comment]
Do I need to support 32-bit Windows? (that would require more work)

**Comment by laarmen** [comment]
+1.

We're volunteers. If someone wants a 32-bit build, they can always do
it themselves, or at least open an issue :)

**Comment by impaktor** [comment]
@Web-eWorks  :point_up: done? So if we push a tag, it will now do a GNU/Linux build and upload to github, I assume?

**Comment by Web-eWorks** [comment]
I have to fix the build script first, but yes.

**Comment by pcercuei** [comment]
If you give me a token, I can get the Windows installer uploaded to Github on tags, too.

**Comment by impaktor** [comment]
What's the status on this? Anything I'm supposed to do? (I hope not).

If we change upload site, I assume @ecraven can change the homepage to point to the new location?

**Comment by fluffyfreak** [comment]
I've merged both #4427 and #4501, I've got an appveyor instance setup but don't know how to get it to automatically publish to GitHub/Sourceforge. We might want to use a `pioneerspacesim` account rather than someone (me) personal one anyway. Don't know if that's possible.

**Comment by pcercuei** [comment]
If you have a Pioneer organization on Github, I think you can log in as such.

What about we leave the automatic publishing for after the release?

**Comment by pcercuei** [comment]
So what about that release?

**Comment by pcercuei** [comment]
Sorry, I thought #4510 fixed the modelcompiler.

**Comment by fluffyfreak** [comment]
I'm not sure who else can see these builds but there's a working windows 64 bit build at https://ci.appveyor.com/project/fluffyfreak/pioneer/build/artifacts made from the latest master.

Still some issues, modelcompiler stubbornly refuses to work still for example.

**Comment by fluffyfreak** [comment]
Could thus just be because of something stupid like the unnecessary call to [`SDL_Init(SDL_INIT_VIDEO)`](https://github.com/pioneerspacesim/pioneer/blob/master/src/modelcompiler.cpp#L73) and it running in a headless environment?

That doesn't exaplin why the distributed exe doesn't work on my real Windows machine though.

**Comment by Web-eWorks** [comment]
It's probably to do with that, yes. On Travis, we worked around that by setting the ENV var `SDL_VIDEODRIVER=DUMMY`, but I'm not sure how well that will work on windows.

As for the distributed, you have a copy of VS, right? Hook it up to a debugger, see what's wrong with it.

**Comment by fluffyfreak** [comment]
Yeah that's the first thing I did, also not much help. No symbols, full release with everything stripped.
Have installed MSYS2 64-bit on my own PC and am investigating the build process. It does use several libraries that are much newer than the ones we ship with. However, I'd have expected the main exe to fail if those were the problem since it must use them too.

**Comment by pcercuei** [comment]
It worked when the appveyor PR was merged. Maybe something changed since then, that broke it?

**Comment by fluffyfreak** [comment]
Ok, get an access violation when running the appveyor-alike build process locally. Trying to track it down but it's not making much sense, seems to die when starting to iterate over the list of model filenames. Nothing particularly wierd about that code though.

**Comment by fluffyfreak** [comment]
I'll look into it more tomorrow, I'm having to `printf` debug it and force a flush of stdout after each call. It doesn't seem like the `FileSystem` is setup, it finds no files to iterate over, but I'm not sure what paths it's getting!

**Comment by fluffyfreak** [comment]
Ok, it runs the modelcompiler in the build directory, but that doesn't have the `data` directory in it, that's one level up. Which is why there's no files found so that's a problem. But the access violation happens after all that, so I'm still tracking that down.

**Comment by fluffyfreak** [comment]
Figured it out! Not shutting things down on exit is what causes the access violation. So there's a fix incoming. For some reason it works fine if the modelcompiler is built using VS201X, or on Linux, or on OSX. But if it's built by mingw-g++ for Windows ... then it has the problem.

The next problem is that it doesn't actually build any `sgm` files, because it's looking in the wrong folder for them. @pcercuei any idea how to change the CMake stuff to make it look on folder higher for the `data` folder?

**Comment by fluffyfreak** [comment]
Fixes for the access violation in #4518 but the modelcompiler searching the wrong location will need someone who understands the CMake stuff to figure out.

I tried changing the working directory to the one with `data` in it but without success. Not sure what I was doing wrong but ... there ya go.

**Comment by pcercuei** [comment]
The modelcompiler is already called by CMake in the top-level folder, not in the build folder, so it should be able to find the data.

**Comment by impaktor** [comment]
We now have an appveyor pioneer project page (thanks @pcercuei ); and I just added appveyor build badge to the readme.

I wonder if I need to invite pinoeer "owners" to pioneer's appveyor account, or do you guys have access throuhgh loggin in to it with your github account? If not so, bump me, and I'll send appveyor team invite.

**Comment by impaktor** [comment]
HOLY MOLY, in two days it's been 1 year since last release!

ALL HANDS ON DECK! 

RED ALERT! - ASCHTUNG!

I suggest we just manually make windows and linux upload, asap, and upload manually. I think sourceforge is the only pioneer-system I don't have loggin to, so... this likely falls on @fluffyfreak, really sorry to swamp you with stuff to do.

So basically rename [this latest appveryor build](https://ci.appveyor.com/api/buildjobs/shyytmjylcd8e269/artifacts/pioneer-setup.exe), and upload, please (and can someone test it as well, just that game starts and ship takes off without total crash?):

(from https://ci.appveyor.com/project/pioneerspacesim/pioneer/builds/21861028/artifacts )

**Comment by nozmajner** [comment]
That windows installer throws an error after starting it:
![errormsg](https://user-images.githubusercontent.com/4182678/52133378-7dfd6900-2641-11e9-896e-6c5a03f3278f.png)
But if I OK it, the installer runs fine, and the game runs fine as well. (I only did a quick test).

**Comment by WKFO** [comment]
The Windows installer didn't give me an error.

**Comment by fluffyfreak** [comment]
I've removed the version string from the ISS naming so that appveyor does a successful build again. Just waiting for that to finish, then I'll test and upload to Sourceforge.

**Comment by fluffyfreak** [comment]
Release is here https://github.com/pioneerspacesim/pioneer/releases/tag/20190203

**Comment by pcercuei** [comment]
The AppStream data (metadata/net.pioneerspacesim.Pioneer.appdata.xml) was not modified to add the release information, could you add it?

**Comment by fluffyfreak** [comment]
Is there something somewhere, like onthe wiki, that tells me what needs to be added because I've never heard of this `AppStream data` before?

**Comment by pcercuei** [comment]
Just add a new line below this one: https://github.com/pioneerspacesim/pioneer/blob/master/metadata/net.pioneerspacesim.Pioneer.appdata.xml#L59

Put a new <release> tag just like the already existing one (don't remove it), with this release's date.

**Comment by pcercuei** [comment]
@fluffyfreak, the <releases> tag is in double now ;)

**Comment by impaktor** [comment]
1. https://twitter.com/pioneerspacesim/status/1092098677961838594
2. fixed the `<releases>` issue (also, the file is tab indented, so fixed that line as well)
3. fluffy, since the new builds don't show on pioneer's download page, I assume the script is pesky about naming convention of the files? I think rob's script runs once every hour on the web page. Or was it once every 6 hours? 
4. I renamed them on the github release page, to clearer point out which is windows and which is linux bulld.
5. @pcercuei so that file needs to be manually edited every time we tag a release?

**Comment by pcercuei** [comment]
@impaktor, yes, a good practice would be to edit that file to add the new release just right before tagging the release.

Oh, and AppStream complains that the two ```<release>``` are swapped, the latest should come first. Sorry 😀

I updated the [flatpak recipe](https://github.com/flathub/net.pioneerspacesim.Pioneer/blob/master/net.pioneerspacesim.Pioneer.json). Now you can install Pioneer [from here](https://flathub.org/apps/details/net.pioneerspacesim.Pioneer) for 32-bit and 64-bit x86, as well as 32-bit and 64-bit ARM. Clicking the "Install" button actually downloads a simple text file, that app stores will parse. This text file can be hosted on the pioneerspacesim.net too.

**Comment by impaktor** [comment]
Cool, I've linked to the flatpak from the release notes on github, we should link to it from our homepage as well, and maybe the wiki. I've fixed the `<release>` issue again. Let's see if this is bettter.

**Comment by impaktor** [comment]
@fluffyfreak can I ask you to rename the sourceforge files you uploaded to the same format as previous, so maybe pioneer website script picks them up, assuming @robn's script/cron job is still working.

**Comment by fluffyfreak** [comment]
I think that's gonna require the website to change to be honest. I don't even know how to rename them, it seems needlessly complicated to do anything with Sourceforge...

**Comment by impaktor** [comment]
@fluffyfreak done. @ecraven just launched our new webpage, we have a [new repo](https://github.com/pioneerspacesim/pioneer-hugo) for it, please comment or PR, or whatever. 

@pcercuei how would one best link the flatpak thingy? Does that build against current master, or against latest tag/release?

**Comment by pcercuei** [comment]
The direct download link for the flatpak thingy: https://flathub.org/repo/appstream/net.pioneerspacesim.Pioneer.flatpakref. It will always point to the latest version. The package itself must be updated manually at each release, but it's as simple as updating the source download link and MD5 sum in the recipe.

**Comment by PtrMan** [comment]
Wow you guys have some problems :D .

I would suggest for a linux build to rent a 5$ box and write a script to
* download requirements for build
* pull git
* build
Looks maybe to simple, idfk.

Same can be done with a windows box, no idea here.

**Comment by impaktor** [comment]
four years later, and just having made a new release the other day, I've documented everything I know, and who's responsible for each thin to do here:
https://pioneerwiki.com/wiki/Makeing_a_release
