### ISSUE TITLE
Make Travis Build OSX

### ISSUE THREAD

**Issue by fluffyfreak** [pioneerspacesim/pioneer#4522]
Apparently Travis can also build OSX.
https://docs.travis-ci.com/user/reference/osx/

If we can integrate this as well then we will have Travis building Linux & OSX whilst Appveyor builds Windows.

Which would help with #4496

**Comment by Web-eWorks** [comment]
I honestly have no clue how to go about setting up homebrew and getting xcode to play nice. Once that's done, however, we should be able to build on OSX just fine.

**Comment by impaktor** [comment]
We would like to have @salborrelli and @Philbywhizz see this thread.

**Comment by fluffyfreak** [comment]
@Philbywhizz you build using brew on OSX using the automake tools don't you? That seems like an applicable approach for Travis OSX builds since it's explicitly mentioned in that link I posted.

**Comment by Philbywhizz** [comment]
Yes, I currently use the automake tools to build the image. There is a
'pioneer' in homebrew, but I didn't create it (thank you who ever did it)
nor have had the time to work out how it works - it apparently also uses
the automake tools in its build process.

I've recently upgrade my Mac to Mojave, and to be honest I haven't had the
time to really look at getting pioneer to work on it as of yet, and I'm not
familiar with Travis, CMake and all these other tools that we seem to be
using now.

I'm still more than happy to help out - I just may not be as agile to
updating it as I once was when I first started doing the OSX builds (Time
being a limiting factor for me these days). If there are new (perhaps
better) ways of automatically building releases (the current way is a
manual and upload) then I'm all for that.

**Comment by impaktor** [comment]
Seems relevant?
https://stackoverflow.com/questions/19818336/how-to-make-travis-ci-test-package-for-linux-os-x-windows

**Comment by Web-eWorks** [comment]
As we now do CI builds for OSX via Travis just fine, I think this issue can be closed.

**Comment by jfcaron3** [comment]
Are the OSX builds available anywhere?  They aren't on the release pages.

**Comment by Web-eWorks** [comment]
OSX builds have been discontinued due to lack of maintainer and Apple's deprecation of OpenGL. We do not intend to offer them in the near future - we will need to migrate the rendering path to Vulkan and have enough of a user base to warrant spending time on OSX compatibility.

**Comment by jfcaron3** [comment]
OpenGL is still available long-term on macOS via XQuartz, but if there is no maintainer I guess that can't be helped.  My mac is too old to support Vulkan unfortunately. =\  I'll try compiling myself.

**Comment by fluffyfreak** [comment]
@jfcaron3 if someone wants to maintain the OSX builds then that'd be welcome ;)
