### ISSUE TITLE
20190203: buildopts.h missing when compiling with autotools

### ISSUE THREAD

**Issue by Johnnynator** [pioneerspacesim/pioneer#4525]
### Observed behaviour
```
make[2]: Entering directory '/builddir/pioneer-20190203/src/collider'
  CXX      CollisionSpace.o
  CXX      BVHTree.o
  CXX      Geom.o
  CXX      GeomTree.o
BVHTree.cpp:5:10: fatal error: buildopts.h: No such file or directory
 #include "buildopts.h"
          ^~~~~~~~~~~~~
```

### Expected behaviour
to see buildopts.h generated by the autotools build scripts

### Steps to reproduce
Download the release archive, run `./bootstrap`, `./configure`, `make`.

__My pioneer version (and OS):__
20190203, Os: Void Linux

**Comment by impaktor** [comment]
Yeah, we use CMake now, so that's why. We're about to remove autotools, (assuming we can still compile OSX)

**Comment by Johnnynator** [comment]
@impaktor Ok, you should update the Documenation and so then. It still mentions Autotools to work on Linux and so.

**Comment by impaktor** [comment]
#4511

**Comment by fluffyfreak** [comment]
Yeah I'd say keep it open since we haven't yet agreed to remove it due to the OSX issue.

one option would be to fix the autotools so that it generates a `buildopts.h` like Cmake does, or at least a dummy one which will suffice.

**Comment by h54** [comment]
Cmake works on multiple Linux distros but not autotools.  It looks` ${project_root}/COMPILING.txt` contains cmake build instructions immediately after the autotools instructions.

**Comment by akien-mga** [comment]
Ran into this issue trying to update Mageia's package too.

Regardless of whether the autotools buildsystem will be dropped or fixed, the docs could be updated now already. [COMPILING.txt](https://github.com/pioneerspacesim/pioneer/blob/master/COMPILING.txt) mentions:
```
The Autotools build system is usually the most up-to-date, and is what is used
to produce the Linux and Windows builds. The others typically lag behind,
depending on the motivation of those using them to keep them up too date with
source file changes.
```
Which seems to be bad advice.

**Comment by impaktor** [comment]
fixed in master

**Comment by sodomon2** [comment]
> Download the release archive, run `./bootstrap`, `./configure`, `make`.
