### ISSUE TITLE
Cross Compile support with cmake build system

### ISSUE THREAD

**Issue by Johnnynator** [pioneerspacesim/pioneer#4526]
### Observed behavior
`smth modelcompiler: cannot execute binary file: Exec format error`

### Expected behavior
Having modelcompiler compiled for the build machines architecture

I worked around this problem by executing a `modelcompiler` that is installed on the build machine when cross compiling for now. Idk how you want this isssue to resolved.

```diff
--- CMakeLists.txt	2019-02-03 11:56:16.000000000 +0100
+++ -	2019-02-03 19:12:47.221852468 +0100
@@ -241,11 +241,19 @@
 
 # Optimize the models after the modelcompiler is built.
 # This really shouldn't be done inside the source tree...
+if(CMAKE_CROSSCOMPILING)
+add_custom_command(TARGET modelcompiler POST_BUILD
+	COMMAND ${CMAKE_COMMAND} -E env SDL_VIDEODRIVER=dummy modelcompiler -b inplace
+	WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
+	COMMENT "Optimizing models" VERBATIM
+)
+else()
 add_custom_command(TARGET modelcompiler POST_BUILD
 	COMMAND ${CMAKE_COMMAND} -E env SDL_VIDEODRIVER=dummy $<TARGET_FILE:modelcompiler> -b inplace
 	WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
 	COMMENT "Optimizing models" VERBATIM
 )
+endif()
 
 install(TARGETS ${PROJECT_NAME} modelcompiler savegamedump
 	RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
```

**Comment by impaktor** [comment]
I'm not sure what this is about

**Comment by Johnnynator** [comment]
Currently when using cmake to Cross compile Pioneer for any system that can't executed on the build system (e.g. targeting ppc/arm while building on x86) will result in having a modelcompiler binary that can't be executed on the build machine, but the cmake script requires it.
I worked around this by just executing a previously compiled modelcompiler binary that I installed into $PATH.

This is what happens currently
```
[100%] Building CXX object CMakeFiles/pioneerLib.dir/src/posix/FileSystemPosix.cpp.o
[100%] Building CXX object CMakeFiles/pioneerLib.dir/src/posix/OSPosix.cpp.o
[100%] Linking CXX static library libpioneerLib.a
[100%] Built target pioneerLib
Scanning dependencies of target modelcompiler
Scanning dependencies of target pioneer
[100%] Building CXX object CMakeFiles/modelcompiler.dir/src/modelcompiler.cpp.o
[100%] Building CXX object CMakeFiles/pioneer.dir/src/main.cpp.o
[100%] Linking CXX executable modelcompiler
Optimizing models
/builddir/pioneer-20190203/build/modelcompiler: /builddir/pioneer-20190203/build/modelcompiler: cannot execute binary file
make[2]: *** [CMakeFiles/modelcompiler.dir/build.make:101: modelcompiler] Error 126
make[2]: *** Deleting file 'modelcompiler'
make[1]: *** [CMakeFiles/Makefile2:118: CMakeFiles/modelcompiler.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable pioneer
```

**Comment by impaktor** [comment]
So this is about building for ARM / PPC? Pioneer doesn't support that, so I believe this can be closed. There is a thread about compiling pioneer on raspberry on the dev forum, so further discussion can be taken there.

**Comment by pcercuei** [comment]
Well, Pioneer should support that, so that's a bug that should be fixed.

At the very least, the modelcompiler should only be built and ran if not cross-compiling, then it would work.

**Comment by impaktor** [comment]
Unless someone will take on the task of fixing this, I'm voting to close this. We're not committing ourselves to support yet another set of platforms, when we hardly can make builds on linux, windows and osx.

_if_ this was made to run on ARM/cell phones, then I predict we'll have a new slew of issues, as in "UI looks strange on my 2 inch screen", as if we're obligated to maintain a pioneer version for screens smaller than average penis size, (which, by the way, is a unit of meassurement that makes as much sense as imperial 'feet' or any other such barbaric bodily unit).

**Comment by impaktor** [comment]
@Johnnynator could you please try @pcercuei's fix linked above?
