### ISSUE TITLE
[Question] Free Software?

### ISSUE THREAD

**Issue by asddsaz** [pioneerspacesim/pioneer#4537]
**Question**: Is Pioneer [free software](https://www.wikipedia.org/wiki/Free_software)?

The current websites says pioneer is "open-ended". Is it fully [free software](https://www.wikipedia.org/wiki/Free_software)?

**Comment by pcercuei** [comment]
Yes. Read the license. It's GPL v3.

**Comment by nozmajner** [comment]
And the content, as in models, textures, etc are cc-by-sa.

The open ended partis refering to the game not having an end-goal.

**Comment by asddsaz** [comment]
@pcercuei I don't mean to be rude, but many projects listed as "GPL v3" (or another free software license) have some hidden non-free components like a non-free engine or something.

Thanks for clarifying!

**Comment by laarmen** [comment]
GPL 3 means you cannot use a non-free engine, AFAIK. Our game engine is
custom made, and the libraries are all GPL 3 compatible.
