### ISSUE TITLE
Appveryor notifications and shenanigans

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#4541]
## Don't send notifications?
@ecraven said he's getting notifications from appveyor on each failed build, I'm not sure why that happens. I've [configured](https://ci.appveyor.com/account/pioneerspacesim/environment/42746/settings/notifications) it to only send emails to me and @fluffyfreak when building an actual release.

But, apparently, one can tweak the appveyro.yml file for behaviour, it seems: 
https://www.appveyor.com/docs/notifications/

For the recond, I've never gotten any email from appveyor due to failed PR-builds, that I know of.

## Rename "artifact" for release?
Also, currently, we have yet to figure out how to give the built setup.exe file a propper name, e.g. `pioneer_<yyyyMMdd>_widows.exe`, and have appveyor upload that to our github release page.

**Comment by Web-eWorks** [comment]
@impaktor what's the status on this issue? Is there anything that still needs to be done, or can this be closed?

**Comment by pcercuei** [comment]
I'm getting the notifications, too...

**Comment by impaktor** [comment]
I haven't gotten any notification in a long time (months).

Strange...

_Only winning move is not to play_

**Comment by The-EG** [comment]
Over a year with no response (or complaints!), I'm guessing this was fixed or is otherwise not an issue now.
