### ISSUE TITLE
Missing 'savefiles' directory

### ISSUE THREAD

**Issue by robothauler** [pioneerspacesim/pioneer#4542]
### Observed behaviour
Error message "Error: 'savefiles' is not a directory" on first start when trying to save a game.

### Expected behaviour
No such error message

### Steps to reproduce
1. Delete old .pioneer folder
2. Start Pioneer
3. Start a new game and try to save

I can find a new .pioneer directory in my home directory but no 'savefiles' directory.

__My pioneer version (and OS):__
Linux
Current master

**Comment by impaktor** [comment]
Please check your permissions on the folders, `ls -l`

Maybe pioneer for some reason thinks it's running as root?

There might be issue with non-ASCII characters in the path as well.

**Comment by robothauler** [comment]
Permissions are 'drwxr-xr-x' for the .pioneer directory. Same as the old dir. Setting to 'drwxrwxrwx' has no effect. Path looks good.

**Comment by impaktor** [comment]
And the owner of the pioneer process and the home folder, and .pioneer folder is the same?
(e.g. use `top`)

**Comment by robothauler** [comment]
I can save a game if I create the directory .pioneer/savefiles manually.

**Comment by robothauler** [comment]
According top, process owner is my user.

**Comment by robothauler** [comment]
As far as I can tell, all permissions look good.

**Comment by impaktor** [comment]
> I can save a game if I create the directory .pioneer/savefiles manually.

Oh, OK, that's valuable to know, sorry didn't understand that. 

I think this could maybe happen if you have a path like:
`/home/ballefjång/.pioneer` as it has non-ASCII character, but that is not the case you said.

**Comment by robothauler** [comment]
Just to be save, I deleted the build folder and compiled the game again. All happened again as described above. Additionally, with a manually created savefile directory, the game crashes if I jump out of the system, save and try to load. But I don't know if this is related to the same issue.
