### ISSUE TITLE
Pioneer crashes if you hyperspace with the sector map open

### ISSUE THREAD

**Issue by ElonSatoshi** [pioneerspacesim/pioneer#4544]
### Observed behaviour
Pioneer crashes if I hyperspace with the sector map open, with this error:

```
Started hyperspacing...
error: [string "[T] @pigui/modules/system-overview-window.lua..."]:178: attempt to index field 'system' (a nil value)
stack traceback:
        [string "[T] @pigui/modules/system-overview-window.lua..."]:178: in function 'fun'
        [string "[T] @pigui/game.lua"]:680: in function 'callModules'
        [string "[T] @pigui/game.lua"]:980: in function 'fun'
        [string "[T] @pigui/pigui.lua"]:72: in function 'window'
        [string "[T] @pigui/game.lua"]:959: in function 'fun'
        [string "[T] @pigui/pigui.lua"]:109: in function 'withStyleColors'
        [string "[T] @pigui/game.lua"]:958: in function 'game'
        [string "[T] @pigui/pigui.lua"]:129: in function <[string "[T] @pigui/pigui.lua"]:127>
````

### Expected behaviour
I would expect it to switch to the cool HUDless hyperspace transition screen. Or better yet, as a new feature it could display an animation _in_ the sector map showing the vessel transitioning through the hyperspace route.

### Steps to reproduce
1. Checkout the commit hash mentioned below and compile with cmake.
2. Open Pioneer in a scenario with a spacecraft that has a hyperdrive
3. Target a nearby star system for hyperspace.
4. Launch, fly high enough to go into hyperspace.
6. Hit the hyperspace button and then, while it's still counting down, open the sector map

__My pioneer version (and OS):__
Pioneer commit 0072a0959c026bca3939a70014c84780eb4fc714 on Ubuntu 18.04.2 LTS x86_64

**Comment by nozmajner** [comment]
Animating it in the sector map would certainly look cool. But if that happens, care should be taken so it never implies any interacrivity regarding hyperspace travel I think.

**Comment by impaktor** [comment]
I assume a simpler fix would just be to have the player "not exist" when in hyperspace, or forbid showing the sector view when in hyper space. have it be just a blank screen

**Comment by mike-f1** [comment]
Hope it helps:

https://github.com/pioneerspacesim/pioneer/issues/4302

**Comment by impaktor** [comment]
fixed in PR linked above
