### ISSUE TITLE
Search and rescue is impossible when vessel to be rescued gets destroyed

### ISSUE THREAD

**Issue by ElonSatoshi** [pioneerspacesim/pioneer#4547]
### Observed behavior
Search and rescue missions are sometimes impossible because the vessel you're rescuing gets destroyed shortly after arriving in the system they're in. In my case there's a vessel in 96 Ceti that free-falls into a gas giant when I get there. After hyper-spacing out of that system and then back into it, the same vessel is there again, alive and well as if nothing happened, and free-falls into the gas giant again. There's no way to abort or complete the mission.

### Expected behavior
Either all search and rescue missions include ships in stable orbit, or if they free-fall into a gas giant they get permanently destroyed and the mission is failed. Bonus points if you get to take the spare crewman back to a spaceport safely.

### Steps to reproduce
Download and run the latest stable Pioneer version from feb 2019, start doing search and rescue missions until you do one where the spacecraft you're trying to rescue mysteriously disappears while you're beginning the maneuver towards it. Hyperspace out of that system and back into it, observe that the spacecraft is alive and well again. Use the system map to find out what's happening to the spacecraft.

__My pioneer version (and OS):__
Pioneer 20190203 (425c372) Ubuntu 18.04.2 LTS x86_64

**Comment by impaktor** [comment]
@clausimu ping

**Comment by clausimu** [comment]
@ElonSatoshi I was trying to avoid this situation by having the ship start out at 100000 km away from the planet and the AI get the ship into high orbit. But I guess some gas giants may still have a strong enough gravity to pull the ship down. I will have to come up with a graceful way to deal with destroyed target ships. Thank you for pointing this out.

**Comment by maxrd2** [comment]
This is still a problem in e85a0cf4c.
Also when ship crashes to gas giant mission still stays active. Pull #4569 was supposed to fix this by giving me half the reward, but no notification is received when ship crashes, should there be some message?
I have managed to complete the mission by increasing far_space_orbit_dist to 200000km, maybe this can be calculated based on gas giant gravity? Like 10000km * gravity.
Not sure how to get the gravity from `Space.GetBody(mission.planet_target.bodyIndex)` though is there some lua API documentation somewhere?
```
diff --git a/data/modules/SearchRescue/SearchRescue.lua b/data/modules/SearchRescue/SearchRescue.lua
index b37c7bb6d..e3bc1f34a 100644
--- a/data/modules/SearchRescue/SearchRescue.lua
+++ b/data/modules/SearchRescue/SearchRescue.lua
@@ -55,7 +55,7 @@ local ui = Engine.ui
 local max_mission_dist = 30          -- max distance for long distance mission target location [ly]
 local max_close_dist = 5000          -- max distance for "CLOSE_PLANET" target location [km]
 local max_close_space_dist = 10000   -- max distance for "CLOSE_SPACE" target location [km]
-local far_space_orbit_dist = 100000  -- orbital distance around planet for "FAR_SPACE" target location [km]
+local far_space_orbit_dist = 200000  -- orbital distance around planet for "FAR_SPACE" target location [km]
 local min_interaction_dist = 50      -- min distance for successful interaction with target [meters]
 local target_interaction_time = 10   -- target interaction time to load/unload one unit of cargo/person [sec]
 local max_pass = 20                  -- max number of passengers on target ship
@@ -2043,7 +2043,10 @@ local onEnterSystem = function (player)
 
        -- spawn mission target ships in this system
        for _,mission in pairs(missions) do
-               if mission.system_target:IsSameSystem(syspath) and mission.target_destroyed == "NOT" then
+               if mission.target_destroyed ~= "NOT" then
+                       Comms.ImportantMessage("Mission ship already destroyed")
+               end
+               if mission.system_target:IsSameSystem(syspath) then -- and mission.target_destroyed == "NOT"
                        mission.target = createTargetShip(mission)
                end
        end
@@ -2283,6 +2286,7 @@ end
 local onShipDestroyed = function (ship, attacker)
        for _,mission in pairs(missions) do
                if mission.target and ship == mission.target then
+                       Comms.ImportantMessage("Mission ship destroyed")
                        mission.target = nil
                        if attacker:IsPlayer() then
                                mission.target_destroyed = "BY_PLAYER"
```
