### ISSUE TITLE
Search and Rescue crash for deliver crew mission

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#4551]
Copenhagen_Bram reported this on a S&R mission, landing next to a mission ship on Earth for a transfer:

```
error: [string "[T] @libs/Ship.lua"]:922: attempt to get length of field '?' (a nil value)
stack traceback:
        [string "[T] @libs/Ship.lua"]:922: in function 'CrewNumber'
        [string "[T] @modules/SearchRescue/SearchRescue.lua"]:1627: in function 'deliverCrew'
        [string "[T] @modules/SearchRescue/SearchRescue.lua"]:1790: in function <[string "[T] @modules/SearchRescue/SearchRescue.lua"]:1765>
Segmentation fault (core dumped)

```
Just looking at those lines of code, I think this is what I'd expect to happen if the mission is to deliver crew to a mission ship, that is empty. 

- possibly, a mission ship should never be empty, i.e. exclude single seat
  ships from "deliver crew (pilot/doctor)" to mission ship?
  
- Or L922 in lib/Ship.lua shouldn't crash if CrewRoster is empty.

``` lua
Ship.CrewNumber = function (self)
	return #CrewRoster[self]
end
```

**Comment by ElonSatoshi** [comment]
uhh that's actually `pioneer 20190303 (74e38aa37)` compiled with cmake.

I was trying to make an issue but I need to take a bath and manage to load an autosave without segfaulting.

**Comment by ElonSatoshi** [comment]
How to reproduce:

1. 
```
git clone https://github.com/pioneerspacesim/pioneer
cd pioneer
git checkout 74e38aa37
./bootstrap cmake && cmake --build ./build
```

2. Stick this [save file](https://github.com/pioneerspacesim/pioneer/files/2928515/search.and.rescue.json.gz)
into your ~/.pioneer/savefiles folder and try to open it, but be warned that if I try to load a save with this version it segfaults, an issue which I will open after writing this. If you can't open it, play Pioneer and do search and rescue missions and hope you get the same one I got? Maybe there's a thing you can type into the console. Make sure you have an extra passenger bay.

3. Accept the search and rescue mission, fly to the stranded vessel and land next to it, wait for the crew transference.

**Comment by clausimu** [comment]
@impaktor: Has the lib/Ship.lua Ship.CrewNumber function been touched lately? I just had a quick look at the SAR code and don't see any red flags. If ships with 0 crew would be the problem this should have come up a long time ago? The probability of getting a ship with 0 crew for this particular crew delivery mission is pretty high.

**Comment by impaktor** [comment]
@clausimu Nope, that specific file hasn't been touched for 2 years.

**Comment by RealTehreal** [comment]
Hey I'm new Pioneer and just stumpled upon the same error. Without taking a deep look into the code, it seems like there is no CrewRoster list created for the mission target ship, resulting in the error (it's nil). I just played around with the lua code and fixed it this way for my local copy:

```
Ship.CrewNumber = function (self)
	if CrewRoster[self] == nil then
		return 0
	else
		return #CrewRoster[self]
	end
end
```

But as I'm new here, I'm not sure if this will maybe break other stuff...

**Comment by luiizfenix** [comment]
Hey there, just tumble uppon a similar issue. 

attached my save file, to reproduce, just autopilot near faio d, it will crash after a few mins. 
[searchrescuefaio.zip](https://github.com/pioneerspacesim/pioneer/files/4708637/searchrescuefaio.zip)
