### ISSUE TITLE
Segfault while loading any saved game

### ISSUE THREAD

**Issue by ElonSatoshi** [pioneerspacesim/pioneer#4552]
### Observed behaviour
When I try to load a savegame, pioneer works for several minutes, slowing down my computer, then exits, printing `Segmentation fault (core dumped)` in the terminal I ran it in.

### Expected behaviour
Pioneer loads the saved game successfully

### Steps to reproduce
1.

```
git clone https://github.com/pioneerspacesim/pioneer
cd pioneer
git checkout 74e38aa37
./bootstrap cmake && cmake --build ./build
./build/pioneer
```

2. Try to load the [save file](https://github.com/pioneerspacesim/pioneer/files/2928515/search.and.rescue.json.gz) mentioned in #4551 or make your own by starting a new game and saving it, and then trying to load it.

__My pioneer version (and OS):__
74e38aa37 Ubuntu 18.04 LTS

**Comment by jaj22** [comment]
Can I confirm whether:
1. You have the same problem if you play a new game rather than loading a save.
2. It's a recent problem (check a commit from a month ago, maybe).

**Comment by ElonSatoshi** [comment]
1. No, starting a new game can be done without any problems.
2. The latest release was a month ago and it doesn't have this issue.

Can you reproduce it?

**Comment by jaj22** [comment]
Busy for a couple of hours but I'll test after that.

**Comment by fluffyfreak** [comment]
@jaj22 it doesn't?

Oh, I'd forgotten to merge a PR for `pioneer-thirdparty` that I did a few days ago when I notived this.

Maybe try again after getting latest on that.

**Comment by mike-f1** [comment]
...I would bet this is due to a couple of '&' too much I left in `Space.h` (lines 140 __**&**__ 141)... But I don't find a reason :thinking: ...

**Comment by fluffyfreak** [comment]
ooooor, it might be because I didn't test in debug

**Comment by jaj22** [comment]
Ok, I get a hard crash immediately on loading that save. It's caused by m_ship not being initialized in the load-game constructor for HyperspaceCloud in the case where the cloud isn't attached to a ship.

Can you test whether that's the problem on your side? Before line 47, HyperspaceCloud.cpp, add the line `m_ship = 0;`.
