### ISSUE TITLE
Segmentation fault when loading a game

### ISSUE THREAD

**Issue by manolollr** [pioneerspacesim/pioneer#4560]
Compiled pioneer version: newest (commit 1ca6015)
OS: Arch Linux x86_64
cMake version: 3.14.0
gcc version: 8.2.1

Until commit f4186da it works perfectly, you can load any game without problem. Since commit 34e8965 there is a segmentation fault any time you want to load a game, regardless the game is saved with newer or older versions.
I've tried to debug it and I think the error is in file WorldView.cpp line 64
shipView.LoadFromJson(jsonObj);

I've attached game output, saved game and GDB backtrace.
[output.txt](https://github.com/pioneerspacesim/pioneer/files/2989378/output.txt)
[Marte.zip](https://github.com/pioneerspacesim/pioneer/files/2989380/Marte.zip)
[gdb_backtrace.txt](https://github.com/pioneerspacesim/pioneer/files/2989383/gdb_backtrace.txt)

**Comment by jaj22** [comment]
Yeah, I think you're correct. That line should be passing worldViewObj not jsonObj. Will test later and push a patch.
