### ISSUE TITLE
Can't use autopilot to fly to target ship

### ISSUE THREAD

**Issue by clausimu** [pioneerspacesim/pioneer#4565]
### Observed behaviour
Trying to get the autopilot to fly to a target ship that has been selected via one of the Search-And-Rescue missions. Since the UI upgrade that is not possible any more. Ships are not listed in the overview panel and there is no other way to select an autopilot target.

### Expected behaviour
List ships (or at least currently selected target ships) in the overview panel so the autopilot can be used to fly toward them.

### Steps to reproduce
Select a SAR mission, select the ship as target via the mission window. Try to use autopilot to fly toward that ship - but there is no way to do that.

__My pioneer version (and OS):__

pioneer version (git): 20190327 (04112a410)
OS: openSUSE Leap 15.0

**Comment by nozmajner** [comment]
You can, if you right-mouse on it's name at the reticule.
Admittedly, it is not properly documented that you can bring up that menu that way. An autopilot menu button would be useful for clarity's sake I guess.

**Comment by clausimu** [comment]
@nozmajner Thank you, got it. We'll need some sort of documentation though. Closing because I was just too dumb to click on the right location on screen.
