### ISSUE TITLE
Windows 10 150% scaling = unplayable fullscreen

### ISSUE THREAD

**Issue by pezz** [pioneerspacesim/pioneer#4574]
It seems that the fullscreen setting of your game is doing something wrong when scaling is set above 100% in Windows 10.

**Comment by impaktor** [comment]
My teacher told me there's not such thing as  > 100% !

**Comment by pezz** [comment]
That explains your comment then.

**Comment by nozmajner** [comment]
Windows might give a lower dpi to imgui. Try removing the imgu.ini from Documents/Pioneer. Having the game regenerate it might fix the problem.

**Comment by pezz** [comment]
Nah mate, that doesn't work sorry.

Also, I noticed that setting the resolution to 1920x1080 fullscreen doesn't work either and it goes to 1280x720.

I checked the config.ini file and 1080 appears to be in there and saved.

**Comment by Cyborgscode** [comment]
retry an actual version, a fullscreen text scaling issue has been fixed.
