### ISSUE TITLE
In-flight UI broken

### ISSUE THREAD

**Issue by CylonicRaider** [pioneerspacesim/pioneer#4580]
The latest code changes — i.e. #4548 — have snuck in a few UI bugs, aside from the crash I noticed in #4578.

<p align=center>
<img src="https://user-images.githubusercontent.com/12989435/57195235-89b63f80-6f50-11e9-9517-391e0dafc030.png" alt="Broken reticule">
</p>

I observed that:
1. The movable portion of the horizon indicator is... doing strange things.
2. The approach speed indiator constantly shows zero (even after accelerating the ship in various directions).
3. The direction indicators are missing. (The left-pointing chevron appeared to me spuriously while rotating the ship.) When turning the camera (and not the ship), the direction to front indicator appears; I cannot definitely say whether it points whither it ought to.
4. The small version of the prograde vector indicator appears even while the indicator itself is inside the reticule.
5. Not visibly on this image, the background of the body name (the dark area behind e.g. “Earth”) is shifted upward w.r.t. the body name itself.

I've prepared a fix for the horizon indicator in CylonicRaider@7e014150ae0f1ce625593dd7bd12c799be21cbf7; the other points are beyond my current motivation to debug.

**Comment by mike-f1** [comment]
Thank's for feedback and for code, I just debug the issues and opened a PR

...I hope you have time to check all things are ok.

**Comment by CylonicRaider** [comment]
As of commit 2d9fdfeda221a6750114a9ea2dceba74e9ce6328, the portside direction indicator is missing and the to-front indicator doesn't seem to work correctly. The zenith indicator is pointing somewhere strange as well, but it wasn't working reliably before, either.

**Comment by mike-f1** [comment]
> the portside direction indicator is missing

...typo...

> the to-front indicator doesn't seem to work correctly

Mine is working...  May I ask if you can explain better what's happens?

> The zenith indicator is pointing somewhere strange as well, but it wasn't working reliably before, either.

Now when view is not away from its starting position is pointing in the right direction, though I can confirm it is rotating too fast when you tilt the camera.

And it could be improved: If I look around the rotation is not working the same for every angle.
When looking at 90° from the selected view it is rotating around the view direction instead of panning left/right.

But that should wait: it is an existing issue and I think it is better (for now) to solve the issues
introduced by PR 4548.

**Comment by CylonicRaider** [comment]
>> the portside direction indicator is missing
>
> ...typo...

I don't see it. 🤷

>> the to-front indicator doesn't seem to work correctly

I've seen that one (almost) addressed in the PR.

> it is an existing issue

So is this issue; their only difference is their age. As you are at it anyway, is looks like a great opportunity to fix the zenith indicator as well, however.

**Comment by mike-f1** [comment]
> I don't see it. 🤷

Line ~249: was `aux.y = -1` ; changed to `aux.x = -1`

>And it could be improved ........snip........ it is an existing issue and I think it is better (for now) to solve the issues introduced by PR 4548.

No issue here, I was wrong: it was not rotating :)

**Comment by CylonicRaider** [comment]
>> And it could be improved ........snip........ it is an existing issue and I think it is better (for now) to solve the issues introduced by PR 4548.
>
> No issue here, I was wrong: it was not rotating :)

Ahh, I thought you were referring to the zenith indicator. Free-looking mode does indeed use somewhat simplicistic math, which is a different issue indeed, and also appears in the sector and orbital maps.
