### ISSUE TITLE
Improve Pigui lua flag operations.

### ISSUE THREAD

**Issue by Web-eWorks** [pioneerspacesim/pioneer#4590]
This has been bugging me for a while, ever since @ecraven and I were chatting about it. Currently pigui handles passing ImGui flags (e.g. `ImGuiWindowFlags_NoResize`) from Lua by passing a table containing strings and looking those strings up in a `std::map` to convert them to the integer enum values ImGui expects. It looks a little like this:

```lua
ui.window("<NAME>", { "NoResize", "NoBringToFrontOnFocus", ... }, function() ... end)
```

On the C++ side, this entails copying the string contents from the table into a `std::string`, copying them _once again_ into another stack-allocated `std::string` (though my testing shows that this is mostly optimized out at `-03`), hashing the string with `std::hash`, looking the value up in the map, and then returning the integer enum value.

This is (obviously) comparatively expensive - copying lots of small strings around isn't good for performance, and while the `LuaTable` implementation helps a little with cache coherency it's still not great. This got me thinking... in Lua, there's a little implementation detail: strings are compared and passed around by their hash, which is calculated _once_ (strings are immutable in lua). What if we made Lua do the hashing and map lookup instead?

So I wrote a quick profiling case of 100,000 invocations and got some interesting numbers out of it. `std::map` style is as described above. `lua table` uses a Lua-hosted lookup table to translate string keys into integer constants, and `lua integer` just passes a table of integer values directly to the function, which are error-checked against a `std::set` for validation.

```
std::map style took 44ms.
lua table style took 27ms.
lua integer style took 18ms.
```

Surprisingly, raw integers aren't much faster than doing a lua-side table lookup, coming in at only 50% faster. Depending upon optimization level, lua tables were 2-3 times faster than our existing implementation, probably more as my test case is a small, easily optimized C-style function. Clearly we should just pass raw integers around, right?

Not quite. The reason we pass strings around instead of integers is because it makes for much better error detection. When you pass `NoResize` into a function instead of `CharsUppercase`, a string will fail, while an integer will be unknowingly accepted as correct. Considering that we have very little in the way of static validation for our lua code and pioneer is by its nature a project for rookies and part-time developers, it is usually better to err on the side of resiliency instead of speed.

So, a long winded explanation later, I'm proposing to create a lua lookup table for each flag type instead of a `std::map` to prevent extraneous string creation and speed up flag parsing - quite a number of UI constructs make heavy usage of flags, and speeding that up means more cycles that we can use on other things.

Another related change I'd suggest is to store our flag constants in a table (`ui.WindowFlags` etc.) and refer to them by name instead of raw string - this helps to prevent misspellings and will provide at least a little error detection if we later decide to pass integer constants instead.

**Comment by impaktor** [comment]
> Considering that we have very little in the way of static validation for our lua code and pioneer is by its nature a project for rookies and part-time developers, it is usually better to err on the side of resiliency instead of speed.

Yes, indeed.

As for the other stuff, I'd like to have the opinion of @ecraven, (ping).

**Comment by ecraven** [comment]
I'm all for this, that was just the first and simplest way to implement it that came to mind. @Web-eWorks could you post an example of what the new API would look like?

**Comment by laarmen** [comment]
Nice!

**Comment by Web-eWorks** [comment]
@ecraven Both the C++ and Lua APIs will not change at all as far as existing code is concerned. The only thing that will change is the internals of the `pi_lua_generic_pull` specializations, and we'll start encouraging people to use this format:

```lua
ui.window("name", { ui.WindowFlags.NoResize, ui.WindowFlags.NoBringToFrontOnFocus, ... } fn)
```

..._Alternatively_, we could have the best of both worlds and give Lua a validation function as well, allowing UI code to precache the integer flag value and pass that directly into a function:

```lua
local windowFlags = ui.WindowFlags { "NoResize", "NoBringToFrontOnFocus" }
function drawWindow()
    ui.window("name", windowFlags, function() ... end)
end
```
After some reflection, I think this latter approach is the way to go - `pi_lua_generic_pull` will test if the flag is a table or a number; if a table, we parse like I outlined above; if a number, we directly interpret it as a flag.

**Comment by jaj22** [comment]
It's possible to remove the std::string conversion overhead and work directly with C-style strings in the std::map method. Might be an interesting comparison. I suspect it'd be a similar speed to the lua table implementation for completely different reasons, in which case you just pick the simpler code.

I don't suppose the actual fast option is acceptable? Namely having create-once, use-multiple userdata flag sets. Likely to be an order of magnitude faster than the other methods, and retains error checking.

**Comment by Web-eWorks** [comment]
@jaj22 While possible to do C-style comparisons, what we're trying to avoid is rehashing the strings on every function call - lua hashes each string once, because they're immutable.

Creating a userdata has an allocation overhead of 48 bytes per object, though I suppose if we are caching it outside of a function invocation and reusing it instead of destroying and creating another that doesn't matter. I'm afraid I ninja'd you a bit on this though, but you bring up an interesting point - using a userdata lets us check if someone called `ui.WindowFlags{}` and passed it into `ui.textEdit`, while an integer does not.

Personally, there's enough complexity overhead with the userdata approach that I'd rather just use an integer; it's easy enough to check the ten lines in your code you're passing flags around to ensure that you're using the right ones.

**Comment by jaj22** [comment]
Yeah, I'd definitely go with the integer. Just forgot that the flags boil down to a single integer rather than several. If you wanted more safety you could avoid exposing the individual integer flags to lua.

std::map (as against unordered_map) is conventionally implemented as a bintree rather than a hash, hence it normally works out quite fast for small collections of strings. The std::string creation could easily be the bulk of the cost. If you're going for the create-once use-multiple optimization then it's academic anyway.
