### ISSUE TITLE
Fix atmospheric heat calculations

### ISSUE THREAD

**Issue by Web-eWorks** [pioneerspacesim/pioneer#4594]
I have realized, very belatedly, that I disabled atmospheric heating while I was trying to nail the calculations for atmospheric flight. It, uh... never got rewritten, and fluffy merged the PR without noticing.

I'm not able to work on that right now, but if this issue goes on long enough without a resolution, I'll take a crack at implementing accurate heating calculations that work with the new flight model. Otherwise, I'd really appreciate it if someone would Ctrl+F the `TODOs` in `Ship.cpp` and fix atmo heating so we can turn it back on.

**Comment by fluffyfreak** [comment]
Doh! I never spotted that. My bad.

**Comment by fluffyfreak** [comment]
PR #4606 should do enough to close this, although it is a little basic.
