### ISSUE TITLE
Medical emergency is broken

### ISSUE THREAD

**Issue by pcercuei** [pioneerspacesim/pioneer#4601]
### Observed behaviour
Landing next to the target ship where medical attention is needed does trigger a "please allow 0.0 minutes for transfer" message, and then nothing happens.

### Expected behaviour
Something happens.

### Steps to reproduce

Start a new game on Mars. Accept a medical emergency mission. Navigate to the ship in distress. Land asides it.

This is my savefile to make it easier to reproduce the bug: https://app.box.com/s/m0t8kx4mlq7pk9obutgynmwtsshtch74

__My pioneer version (and OS):__
master branch (4c51f4eff), Debian 9 64-bit

**Comment by impaktor** [comment]
Ping @clausimu

**Comment by ElonSatoshi** [comment]
I can confirm

**Comment by mike-f1** [comment]
I tried some debug, not leading to much answers, but I feel strange someone can pick this kind of mission with 0 cabin space...

Then I tried it again with cabin but when I show mission in "mission panel" I found there's no passengers.

**Comment by craigo-** [comment]
I can also confirm the symptoms when using master (4bc31eef4700b343256cb1dae604622680c534d8). You can accept a medical emergency mission with no available passenger cabin space, and the mission "More info" screen shows:

![image](https://user-images.githubusercontent.com/4467963/63645304-27778980-c74f-11e9-8d71-009acdcd5185.png)

In the current release (20190203), when attempting to accept this mission with no passenger cabin space you receive the message:

![image](https://user-images.githubusercontent.com/4467963/63645307-32321e80-c74f-11e9-9f72-4f8a9bc9ab2b.png)

When you accept the mission with available passenger cabin space, the mission "More info" screen shows:

![image](https://user-images.githubusercontent.com/4467963/63645303-22b2d580-c74f-11e9-9386-42142542a0a5.png)

**Comment by craigo-** [comment]
I've just been thinking about this...

Why is it that (in the working release version) the mission adds to your ship's crew complement and not to its passenger manifest? Particularly when it requires available *passenger* cabin space? Does this mean that the mission cannot (should not be able to) be performed in any ship that has a maximum crew of 1, e.g. Xylophis?

Is there any overlap between this issue and #4551?

**Comment by robothauler** [comment]
Looks like the parameter deliver_crew in function createTargetShipParameters() is set to 0 and never set back to the mission flavour value for all missions with deliver_crew > 0.
Line 653 and line 666.

**Comment by mike-f1** [comment]
>Line 653 and line 666.

These are there for #4579: without them there was a CTD...
Probably missed intention was to set `deliver_crew` (and the other two parameters as well) in each branch of if chain, but I had no time to properly understand that code.
Then my (wrong) assumption: these would be 0 if no care was given.

**Comment by craigo-** [comment]
Thanks, I can confirm that Medical Emergency missions are functional again (tested version: master, commit 470159286dea527e97994f03daae0ff7cb1d92ad, built 20191012).

It took a while, but I think I've finally figured out that 'Crew' listed in a mission's 'More Info' screen has nothing to do with your own ship's crew; they are simply a special sort of passenger.
