### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by zuurw** [pioneerspacesim/pioneer#4604]
Hi, how are you? I'd like to collaborate on your open source project and propose free logo/icon design for this project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by impaktor** [comment]
Considering our current one has a ship that's no longer in the game (Lanner), yes, I think we're interested, but do you have any sketch, or suggestions, or previous work to show?

**Comment by fluffyfreak** [comment]
@impaktor https://github.com/zuurw/Graphic-Design-

**Comment by zuurw** [comment]
> Considering our current one has a ship that's no longer in the game (Lanner), yes, I think we're interested, but do you have any sketch, or suggestions, or previous work to show?

Do you have any ideas for the logo???

Cheers!!!

**Comment by impaktor** [comment]
> Do you have any ideas for the logo???

No, maybe @nozmajner has? Anyway, feel free to improvise and show us any ideas you have.

**Comment by nozmajner** [comment]
I don't have much problem with the current logo. Maybe a bit of a facelift.
I don't think that it is a problem to have a non-existing ship in it, since that shape is quite general anyway.

I'm open for suggestions, sketches anyhow
