### ISSUE TITLE
Unable to dock at New Hope (City), New Hope

### ISSUE THREAD

**Issue by jtgibson01** [pioneerspacesim/pioneer#4611]
"ver 20190203 on: Windows"

Possibly related to #3077, but with an actual immediate test case.

Log entries show that other ships have successfully docked with New Hope city before:
> CA-6999 docked with New Hope ship:varada
> KK-8052 docked with New Hope ship:sinonatrix

but none seem to be present.

[NewHopeDockingIssue.gz](https://github.com/pioneerspacesim/pioneer/files/3245716/NewHopeDockingIssue.gz)
(This is additionally gzipped, rather than just the existing container for the JSON file.)

This is a brand new character, so no biggie.  I'm at a Set Speed 0 hover over the New Hope city, with an 8-ton cargo of goods due for delivery to the city, but communications with the city are not functioning and autopilot will simply refuse to respond to the context menu in any way.

I note that at least one starport pad is partially subterranean, and yet the standard warnings about moving starports to avoid clipping did not catch New Hope (city) at all (only Gandhi's Revenge and Itzalean):
> Warning: Lua custom Systems definition: Surface starport has been automatically relocated. This is in order to place it on flatter ground to reduce the chance of landing pads being buried. This is not an error as such and you may attempt to move the starport to another location by changing latitude and longitude fields.
>       Surface starport name: Itzalean, Body name: New Hope, In sector: x = 1, y = -1, z = -1.
> Warning: Lua custom Systems definition: Surface starport has been automatically relocated. This is in order to place it on flatter ground to reduce the chance of landing pads being buried. This is not an error as such and you may attempt to move the starport to another location by changing latitude and longitude fields.
>       Surface starport name: Gandhi's Revenge, Body name: New Hope, In sector: x = 1, y = -1, z = -1.

Manually landing on a pad (yes, with gear down =P) does nothing other than cause hull damage (the hull already carries some proof of that).  Manual landing on the surface instead "works" -- the craft will successfully land -- but doesn't allow access to the starport comms either.

**Comment by Web-eWorks** [comment]
@jtgibson01 First of all, the file should already be a gzipped file encoded with CBOR - this appears to be what you have uploaded. Thanks you for providing it - I'll boot it up and do some investigation as soon as I get a chance.

Regarding terrain, what is your terrain detail setting set to? It's a known issue that low-detail settings for terrain can cause stations to clip through the ground due to the lower resolution of the terrain mesh. That'd be the first thing to try.

Secondly, the log doesn't print undocking messages for ships, so it's very likely that those ships have simply taken off already - check your log for that ship ID in a message saying `departed for [system X]` - that indicates that they've hyperspaced out of the system.

Finally - have you tried holding right-click over the spaceport name and simply selecting "request docking permission"? Attempting to land on a pad without permission will simply damage your ship due to collision, as you've seen.

**Comment by pcercuei** [comment]
Can you reproduce it with a nighty build?

**Comment by impaktor** [comment]
there's no nightly build, so it would have to compile from master.

**Comment by pcercuei** [comment]
Oh? I thought I had setup AppVeyor for this project :)

**Comment by impaktor** [comment]
hmm, if there are nightly builds, then they live only on appveryor, right? So a "well kept secret", since there are no links pointing to them, as far as I know.

Looking at appveyor, I think it's failing to put the executable somewhere?
https://ci.appveyor.com/project/pioneerspacesim/pioneer

**Comment by pcercuei** [comment]
There's a permalink you can use that will always give you the latest build from master:
https://ci.appveyor.com/projects/pioneerspacesim/pioneer/artifacts/pioneer-setup.exe?branch=master

But it looks like the AppVeyor service is down right now, the artifact server returns error 500. At this point we can only wait until it's fixed.

For this issue: the latest "nighty" build we have is from 9 days ago, which is already better than testing with a 5-months-old build. It can be downloaded here:
https://ci.appveyor.com/api/buildjobs/lu0u8ia6le7auj7o/artifacts/pioneer-setup.exe

**Comment by jtgibson01** [comment]
@Web-eWorks Sorry for the delay in getting back to you.  Been a busy week with a midterm in my immigration law class.

I'm absolutely positive I ran gzip on top of the savefile's existing gzip container (which I was already aware of), because I still have both files -- the naked binary file and the one with the .gz extension. =)  It compressed it down from 306 KB to 244 KB.

All my settings are set to Very High.

@pcercuei Having just tried it out, I still get the problem with the provided 20190528 build artifact.

**Comment by Web-eWorks** [comment]
@jtgibson01 the autopilot menu has two different options: "request docking permission" and "autopilot: dock with station". The first will simply grant clearance for you to manually land, while the second engages the autopilot in addition to getting clearance. I'll take a look at the savefile again; I wasn't getting pioneer to load it when I tested.

**Comment by Web-eWorks** [comment]
Closing as stale due to several recent changes and bugfixes to starport docking. If the issue persists in a recent build from `master` then please re-open with an up-to-date save.
