### ISSUE TITLE
Police ship ignore bandit/pirate/assassin nearby

### ISSUE THREAD

**Issue by Trokinos** [pioneerspacesim/pioneer#4613]
### Observed behaviour
Hyperspace jump into a system
A police ship is there close by, it scans my ship , no problem found.
While it's happening there's a  bandit/pirate/assassin/hostile ship that full speed come and open fire.
Police ship isn't reacting at all and just continue its travel while the hostile ship is still doing its best at rushing forth and back to my ship and shooting as much as it can.

### Expected behaviour
Police reacts to bandit/pirate/assassin/hostile ship and join the fight

### Steps to reproduce
will happen everytime when police and hostile ship are present (with own ship isn't having any legal problem)

__My pioneer version (and OS):__
Release: 20190203 on window 10

**Comment by impaktor** [comment]
ping @robothauler

**Comment by robothauler** [comment]
This is because the police patrol do not know who is what. A solution that I can offer is, who opens fire first is the bad guy.

**Comment by Trokinos** [comment]
That sounds like a very good solution actually.
