### ISSUE TITLE
Unable to load old savestate

### ISSUE THREAD

**Issue by pcercuei** [pioneerspacesim/pioneer#4641]
### Observed behaviour

When trying to load an old savestate (22 june 2017), this is what I get:
```
error: [string "[T] @pigui/modules/saveloadgame.lua"]:107: This saved game cannot be loaded because it contains errors.
stack traceback:
	[C]: in function 'LoadGame'
	[string "[T] @pigui/modules/saveloadgame.lua"]:107: in function 'callback'
	[string "[T] @pigui/modules/saveloadgame.lua"]:37: in function 'optionTextButton'
	[string "[T] @pigui/modules/saveloadgame.lua"]:123: in function 'fun'
	[string "[T] @pigui/pigui.lua"]:74: in function 'window'
	[string "[T] @pigui/modules/saveloadgame.lua"]:120: in function 'fun'
	[string "[T] @pigui/pigui.lua"]:122: in function 'withStyleColors'
	[string "[T] @pigui/modules/saveloadgame.lua"]:118: in function 'fun'
	[string "[T] @pigui/views/mainmenu.lua"]:155: in function 'callModules'
	[string "[T] @pigui/views/mainmenu.lua"]:240: in function 'showMainMenu'
	[string "[T] @pigui/views/mainmenu.lua"]:244: in function 'mainMenu'
	[string "[T] @pigui/pigui.lua"]:163: in function <[string "[T] @pigui/pigui.lua"]:161>
```

### Expected behaviour

Load succeeds.

### Steps to reproduce

Download https://app.box.com/s/tp2ds67pef47sbxlwfkdyzxptj7xwemu and copy the Frank file to ~/.pioneer/savefiles, then try to load it from the "Load game" menu.

__My pioneer version (and OS):__

Latest master (84950fffe) on Debian 9.

**Comment by Web-eWorks** [comment]
@pcercuei that's because of #4459; we changed the encoding of matrixes. We specifically noted that it would break saved games.

**Comment by impaktor** [comment]
Hmm, then we should have done a save bump.

**Comment by impaktor** [comment]
specifically: `s_saveVersion` in Game.cpp

**Comment by Web-eWorks** [comment]
@impaktor yeaaahh, I _did_ mention that in the first post of the PR in question. Bit too late to change that now, though.
