### ISSUE TITLE
PiGui container elements are rendered as transparent in screenshots

### ISSUE THREAD

**Issue by vakhoir** [pioneerspacesim/pioneer#4642]
### Observed behaviour

The background of PiGui containers is transparent in screenshots. Examples:

![screenshot-20190711-195157](https://user-images.githubusercontent.com/48452426/61170924-5acfd180-a570-11e9-93b4-0d091811e022.png)

![screenshot-20190713-122711](https://user-images.githubusercontent.com/48452426/61170925-61f6df80-a570-11e9-825b-c1e566cc6ef0.png)

Some elements, like gouges, are not affected

### Expected behaviour

Screenshots should look exactly like what is actually displayed on screen.

### Steps to reproduce

- Go to the Station View or Person Info View

- Take screenshot (**ctrl+print screen** by default)

Only Pigui  views are affected, but even in the old UI views, the background on the outside of the screen will be transparent.

**Comment by impaktor** [comment]
I think this is fixed. I used to have this bug, but not anymore.

**Comment by Web-eWorks** [comment]
This was closed in the re-theming PR; one of the main goals there was to get rid of transparent UI elements and replace them with solid colors.
