### ISSUE TITLE
MSVC CMake Debug (x64) builds cannot run due to sigc++

### ISSUE THREAD

**Issue by fluffyfreak** [pioneerspacesim/pioneer#4658]
### Observed behaviour
Use CMake to generate Visual Studio 2019 project
Open it and choose Debug x64
Build All
...
Once built attempt to run the `Pioneer` project,
It will stall on https://github.com/pioneerspacesim/pioneer/blob/master/src/Pi.cpp#L524 and if it ever progresses beyond it then it must take at least 10 minutes on a high-end machine but I've never waited that long...

This makes it much harder to debug under MSVC since we cannot run a full Debug build

### Expected behaviour
That it works like it used too.

### Steps to reproduce
see above

__My pioneer version (and OS):__
Windows 10, Visual Studio 2019

**Comment by pcercuei** [comment]
Does it hang in the connect(), or in the ptr_fun()?

**Comment by fluffyfreak** [comment]
I think it's in the `connect()`

**Comment by pcercuei** [comment]
I know that on Windows you can have Release and Debug DLLs, should we use a Debug DLL for use with the debug build of Pioneer then?

**Comment by fluffyfreak** [comment]
@pcercuei I have the horrible feeling this is why the sigcpp static lib exists(_/ed_) becuase I was never able to resolve it any other way.

**Comment by pcercuei** [comment]
I guess you can switch back to using the static library, yeah.

**Comment by fluffyfreak** [comment]
@pcercuei the PR(s) I've just submitted shouldn't change anything for now, just remove the old Visual Studio projects except for vs2019. That one should work again and the CMake generated project should still use the DLLs.

I'll work to get everything resolved eventually.

**Comment by The-EG** [comment]
This does work if you compile/run against the sigc++ debug library instead. I'll get some PRs together for it (one for thirdparty too).
