### ISSUE TITLE
Load game: UI a bit small

### ISSUE THREAD

**Issue by craigo-** [pioneerspacesim/pioneer#4674]
### Observed behaviour
The Load game dialogue is a bit small, truncating the text of both the file name and the date. (I do like the popup detail, though.)

Screenshot below, taken with game resolution at 1920x1080 fullscreen (image cropped):
![image](https://user-images.githubusercontent.com/4467963/64997103-d7e24300-d933-11e9-8f8f-04a9c75ac35d.png)

For reference, this is what it used to look like in Pioneer 20180203 with the same savefiles, again at 1920x1080 fullscreen (image cropped):
![image](https://user-images.githubusercontent.com/4467963/64997188-11b34980-d934-11e9-8558-767dd9913ef6.png)

NB: the truncation gets more pronounced the lower the resolution.

### Expected behaviour
It would be nice to have a bit more horizontal space to display more of the file name and date.

### Steps to reproduce
Load game (with some saves present)

__My pioneer version (and OS):__
Pioneer master (6fd8f02f69f51ed772e6d0f6888491feba60dbf6) - Release x64
Pioneer release (20190203)
Windows 10 Enterprise 1809 x64

__opengl.txt__
[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/3618762/opengl.txt)

**Comment by impaktor** [comment]
Yeah, I agree, that looks a bit silly, and could be better optimized, if anyone wants to have a stabb at it.
