### ISSUE TITLE
Localization engine: if a string is missing in selected language => game crashes on startup.

### ISSUE THREAD

**Issue by Cyborgscode** [pioneerspacesim/pioneer#4687]
The game crashes on startup, when a string is missing in the selected language.

Something in the "DE" set is missing in Fedora Linux version: pioneer-20190203-3.fc29.x86_64

Could be fixed in mainstream already.

**Comment by impaktor** [comment]
New strings, missing in non-ENglish json files means they must have cloned in the few hour window before transifex syncs the repo, and copies english strings into the DE set.

_Even_ if that doesn't happen, I think I remember some PR that impelemented a fallback, so it shoudn't crash. Or was that only discussed? I remember some discussion with @laarmen I think, but I could be wrong. 

Anyway, if you could pin-point which string it is, that would be interesting to see if transifex has had a hickup and didn't move the string into the DE set (most likely it should be the same for all non-English strings).

**Comment by laarmen** [comment]
I vaguely recall doing stuff along those lines on the Equipment side of
things *shudder* but it had more to do with savegame forward compatibility.

**Comment by impaktor** [comment]
Ah, so then we can assume the crash is logical, _if_ fedora cloned at some date when new strings had just been added, so we can probably close this, but would be nice to know which module or string that triggered the crash. I think it should be in the crash message

**Comment by Cyborgscode** [comment]
it's no as easy as i thought.. i played 2 days (RT) and had severals saved playstates,
switchting now to german (de) as language does not crash the game anymore.

Th ebug was reported before i player at all. So 
-fresh installation
-selecting german
-starting the game over 
- boom

BUT... i removed the .pioneer folder with all configs etc and started again. That should be as if it's freshly installed and guess what, now it's working even then. Starting with defaults, switching german, restarting... no crash ...  now i regret not have made those screenshots, but on day one, it crashed reliable.

**Comment by Cyborgscode** [comment]
And there it is :D 

Missing translation token: DISABLE_SCREENSHOT_INFO in ui-core lc "de"

**Comment by impaktor** [comment]
```  "DISABLE_SCREENSHOT_INFO": {
    "description": "",
    "message": "Screenshot-Info ausblenden"
  },
```
It's there in data/lang/ui-code/de.json

**Comment by Cyborgscode** [comment]
So Fedora picked it up a state, where it was not present:

$ grep Screenshot /usr/share/pioneer/lang/ui-core/de.json
$

init BR to Fedora Maintainer

**Comment by Web-eWorks** [comment]
As this problem has been fixed on the master branch for about eight months now and it's been confirmed to be a downstream issue, I'm marking this issue as resolved.

Thank you @Cyborgscode for investigating and figuring out the root of the issue!
