### ISSUE TITLE
equipment not matching techlevel of station, does not work everywhere

### ISSUE THREAD

**Issue by Cyborgscode** [pioneerspacesim/pioneer#4690]
Barnards Star: Sells TRADE COMPUTERS
If fitted, it works in Barnards Star , but travelled to ROSS 154, it vanishes from the fitting window! AND does not work.  

So it's attached to the system instead of the ship :D

**Comment by Web-eWorks** [comment]
Closing this as cannot reproduce. If you can get a consistent reproduction of this issue in latest master, please open a new issue with a savefile attached and detailed reproduction steps.
