### ISSUE TITLE
L-R mousebuttons switched function

### ISSUE THREAD

**Issue by Cyborgscode** [pioneerspacesim/pioneer#4697]
OS: Fedora 29
Version: 2019-10-09

left and right mousebuttons have been switched. When you try to move the flying ship with RMB you now fire the lasers. 

No idea how to change it.

**Comment by Cyborgscode** [comment]
Ok, after disabling JOYSTICKS, its back to "sort of" normal. RMB does not fire anymore, but LMB does not fire either.

**Comment by impaktor** [comment]
Please try (re)moving your config file, so pioneer creates a new one with the default values.

Still bug?

**Comment by Cyborgscode** [comment]
no.

**Comment by Cyborgscode** [comment]
so upgrading causes troubles with old configs now?

**Comment by fluffyfreak** [comment]
It depends when you upgraded and from what version. There have been several large breaking changes to the controls. So how old was the previous config?

**Comment by impaktor** [comment]
Default configs changed some while ago. This doesn't seem to be a bug, or something very exotic, which we cannot reproduce.
