### ISSUE TITLE
Lasercooler indicator is not cooling down

### ISSUE THREAD

**Issue by Cyborgscode** [pioneerspacesim/pioneer#4698]
OS: Fedora 29
Version: 2019-10-09

After the use of weapons, the laser heat indicator does not go back to zero.

![Pioneer-laserbug](https://user-images.githubusercontent.com/8317797/66576916-cc6fe980-eb78-11e9-8a28-cb18279d991b.jpg)

**Comment by Web-eWorks** [comment]
Cannot reproduce on latest `master`. Closing.
