### ISSUE TITLE
mission hangup context not removed

### ISSUE THREAD

**Issue by Cyborgscode** [pioneerspacesim/pioneer#4704]
OS: Fedora 29
Version: 2019-10-09

When talking about a mission, the context does not get auto closed:

![Pioneer-missionquitcontext](https://user-images.githubusercontent.com/8317797/66588979-d9e39e80-eb8d-11e9-9b68-221a74612097.png)

The redish blib is a bug in cinnamon screencapture with fullscreen apps infront. Not a Game bug.

**Comment by impaktor** [comment]
So screen from BBS / F4 is visible in the lobby? Ping @vakhoir, if you have time

**Comment by Cyborgscode** [comment]
whos that and how?

**Comment by impaktor** [comment]
Sorry, I just did.

**Comment by impaktor** [comment]
OK, just tried it. I guess a fix would be if the BBS "chat-windows" steals all focus from underlying UI, so it's not possible to change to lobby until the chat window is closed.

(maybe one still wants to be able to open options window, but only if it's not hard to do / doesn't clutter up the code)
