### ISSUE TITLE
CTD: exiting stellar map in hyperjump 

### ISSUE THREAD

**Issue by Cyborgscode** [pioneerspacesim/pioneer#4712]
Version: 20191009
OS: Fedora 29

While in transit to a distant star, i opened the stellar map, focused on the destination system
and when i tried to leave it back to the mainview, the game crashed to desktop, without the usual a stacktrace window.

**Comment by Web-eWorks** [comment]
Possibly related to #4709's SIGABRT crash?

**Comment by Cyborgscode** [comment]
I would not wonder, if it is. Some Structures will not be filled before entering hyperspace, but afterwards. Accessing them injump will cause the problems.

**Comment by Web-eWorks** [comment]
Closing as we have some improvements to the sector map coming down the pipe. Please reopen (with a stack trace from GDB!) if the issue persists after #4852 is merged.
