### ISSUE TITLE
Police: "we will help you" and than, they fired on me :)

### ISSUE THREAD

**Issue by Cyborgscode** [pioneerspacesim/pioneer#4713]
I think the ai is a bit confused. 

on a cargo mission, a pirate attacked, police detected it and fired on me, instead of the pirate :D

**Comment by robothauler** [comment]
If you open fire first, you're the pirate!

**Comment by Cyborgscode** [comment]
But i didn't, that the point ;)

**Comment by craigo-** [comment]
![hsf](https://user-images.githubusercontent.com/4467963/66771718-7eac0600-ef17-11e9-8710-22e8aa411dce.gif)
