### ISSUE TITLE
The Venturestar looks like Amphiesma

### ISSUE THREAD

**Issue by Cyborgscode** [pioneerspacesim/pioneer#4714]
Version: 20191009

The Venturestar looks like Amphiesma

 
![Bildschirmfoto vom 2019-10-13 20-38-07](https://user-images.githubusercontent.com/8317797/66720177-b1f87300-edf9-11e9-8d88-91e05f2c14a7.jpg)

**Comment by WKFO** [comment]
That's the Venturestar in the screenshot.
How can we help you?

**Comment by fluffyfreak** [comment]
Yes, I see no bug here

**Comment by Web-eWorks** [comment]
This is the venturestar in the screenshot. Lacking a more descriptive bug report, closing as intentional.

**Comment by Cyborgscode** [comment]
@WKFO: the game used the same 3d model for BOTH ships.

**Comment by WKFO** [comment]
I can not confirm, but will take another look when I get home.
Do you mean Venturestar and AC33 Dropstar?

**Comment by Cyborgscode** [comment]
look at the screenshot.  Venturestar <> Amphiesma  both had the same model. 

There a 2 possible versions for this bug:

a) there are 2 models in game, but the game wasn't able to load the second one and just showed the last one loaded.

b) the 3d model of the Amphiesma is not connected to the ship.

I tend to a)

**Comment by fluffyfreak** [comment]
It's not clear from that screenshot that there is any problem. The listing says there is a Venturestar, the information and the ship shown are a Venturestar. That's what in the screenshot.

**Comment by Cyborgscode** [comment]
it shows which ship should have been visible and the venturestars model is the only shown modell. I know that the screenshot does show it directly, also i have to admit, i did not know which model for the venture star is correct. It's purely accidently that it matches ;) 

TBH, a ship that mass and size should look bigger and not that compact..

**Comment by WKFO** [comment]
I would like to argue. It is too easy to underestimate the sizes of ships in Pioneer, and compact shape is important for aerodynamics.

**Comment by nozmajner** [comment]
That ship has a volume of 4000m3s, excluding the wings.

**Comment by WKFO** [comment]
I arrived home. Can not reproduce.
