### ISSUE TITLE
Can click through Save dialogue and select objects behind

### ISSUE THREAD

**Issue by craigo-** [pioneerspacesim/pioneer#4718]
### Observed behaviour
When viewing outside and you bring up the Save dialogue, clicks on the dialogue can select objects behind the dialogue.

### Expected behaviour
The Save dialogue should be 'on top' and be the recipient of all clicks.

### Steps to reproduce
1. Here I am on Tranquility Base. Note the position of Pluto:
![image](https://user-images.githubusercontent.com/4467963/66971423-afde2f00-f0ed-11e9-9a75-0000a691c920.png)

2. I've pressed `Esc` to bring up the in-game menu, then pressed `Save`:
![image](https://user-images.githubusercontent.com/4467963/66971427-b371b600-f0ed-11e9-9ee0-b62e26a79a3f.png)

3. I'm trying to click the `Save` button, but instead it is clicking through and bringing up the menu for clicking on Pluto:
![image](https://user-images.githubusercontent.com/4467963/66971435-b8366a00-f0ed-11e9-8024-d725325141b0.png)

__My pioneer version (and OS):__
Pioneer: master (3dff8caea6bad11d0e49a0afec513ee6a3ebb68b), approx. 20191017, Release x64
Windows 10 Enterprise 1809 x64

[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/3737057/opengl.txt)

**Comment by Web-eWorks** [comment]
Same deal here as with #4720, the Save Game dialogue should be a Modal. Pinging @vakhoir...
