### ISSUE TITLE
Crash when Load Game dialogue selected after New Game started

### ISSUE THREAD

**Issue by craigo-** [pioneerspacesim/pioneer#4720]
### Observed behaviour
Crash to desktop when you are in the Load dialogue and you select one of the `Start on` buttons, but continue to try to load a game.

### Expected behaviour
That the game does not CTD. Probably the best way to deal with this is to not continue to present the initial buttons when presenting the 'Load' dialogue (as it was in the old UI in version 20180203).

### Steps to reproduce
1. Start game, with save games present
2. Click `Load game`
3. Click `Start on Mars` (you probably shouldn't be able to do this):
![image](https://user-images.githubusercontent.com/4467963/66977462-8ed40900-f102-11e9-8a36-fa95f74cc57b.png)

4. The game starts, but the 'Load game' dialogue persists. Select a saved game and click `Load`:
![image](https://user-images.githubusercontent.com/4467963/66977469-94c9ea00-f102-11e9-932c-8cf8ac72badb.png)

5. The game crashes to desktop with the following guru meditation error:
![image](https://user-images.githubusercontent.com/4467963/66977474-998e9e00-f102-11e9-9ee8-5fc11a23342a.png)

NB: clicking the `Cancel` button at Step 4 works fine.

__My pioneer version (and OS):__
Pioneer: master (3dff8ca), approx. 20191017, Release x64
Windows 10 Enterprise 1809 x64

NB: a very similar guru meditation error happens with Pioneer 20190203. You cannot reproduce the error in Pioneer 20180203, because the `Start on` buttons are not there when the Load dialogue is present.

**Comment by Web-eWorks** [comment]
Ah, we just need to make the Load Game dialogue a modal. Pinging @vakhoir; this should theoretically be an easy fix. (If I need to expose Modal to pigui, just let me know.)
