### ISSUE TITLE
out of game problem - pioneer does not end when "quit" is executed

### ISSUE THREAD

**Issue by Cyborgscode** [pioneerspacesim/pioneer#4731]
Package: pioneer-20191009-2.fc29.x86_64

if pioneer is started via a small bash script like this:

$ cat  .local/bin/startpioneer 

#!/bin/bash

mp3-cmdline '/home/gamer/Dave Lowe - Elite Frontier - Timeshift - Uncle Art Orchestra.mp3' 1>/dev/null 2>/dev/null </dev/null &
env force_s3tc_enable=true SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 pioneer
killall mp3-cmdline

It does not close the window/screen when quitting until "killall mp3-cmdline" is executed in a different terminal.

I have no explaination, why playing a mp3 with a different programm inside a script, could prevent another program from closing a  window/screen. 

Pioneer stops working, no interaction is possible any more. But it does not stop. 
redirecting 1,2,3,4 to dev/null on both programms does not help either.

Any Ideas here?

**Comment by Web-eWorks** [comment]
...first of all, please remember to use Markdown formatting in your issues - surround a script using three backticks like this:

    ```bash
  
    # ...
  
    ```
Secondly, you do know you can redirect *both* stdout and stderr with `&>/dev/null`, right? That's making it a little hard to read the script.

From what I can tell, you're launching mp3-cmdline in the background, running Pioneer, and then killing it when Pioneer closes. There should be no issues here; Pioneer does not (as far as I'm aware) have any issues with background processes, etc. Please check Pioneer's output log for errors, as well as the terminal output from pioneer when started with the script.

**Comment by impaktor** [comment]
Am I correct in thinking that we don't think this is a bug with pioneer, unless logs are shown demonstrating it. 

Silence = we can close.

**Comment by Cyborgscode** [comment]
The question i need to answere is: why does it happen with pioneer, not with different tools?

**Comment by impaktor** [comment]
> The question i need to answere is: why does it happen with pioneer, not with different tools?

No, I was more thinking of posting the logs:

> Please check Pioneer's output log for errors, as well as the terminal output from pioneer when started with the script.

**Comment by fluffyfreak** [comment]
@Cyborgscode are there any logs from pioneer, as @impaktor has asked, did it try to quit? Did it receive the quit notification?
In what way does Pioneer "not end"? Is it still running? 
I'm not sure how running the two things together works with Linux. You've launched a cmdline MP3 and pioneer from the same script, is it the Pioneer window which hasn't closed?

This is such a corner case that I doubt it matters too us at all.

**Comment by Cyborgscode** [comment]
Pioneer is still keept running : 

user   16088  0.0  0.0 113008  3236 pts/0    S+   13:58   0:00      \_ /bin/bash ./startpioneer
user   16090 17.2  4.9 1696632 812356 pts/0  Sl+  13:58   0:04          \_ pioneer

It does not consume any cpu anymore, it just "stopped exiting" :) 

strace: Process 16090 attached with 10 threads
[pid 16101] ppoll([{fd=27, events=POLLIN}, {fd=30, events=POLLIN}, {fd=31, events=POLLIN}], 3, NULL, NULL, 8 <unfinished ...>
[pid 16100] ppoll([{fd=22, events=POLLIN}, {fd=25, events=POLLIN}, {fd=26, events=POLLIN}], 3, NULL, NULL, 8 <unfinished ...>
[pid 16099] futex(0x56208bc292d8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 16098] futex(0x56208bc292d8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 16097] futex(0x56208bc292d8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 16096] futex(0x56208bc292d8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 16095] futex(0x56208bc292d8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 16094] futex(0x56208bc292d8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 16093] futex(0x56208bc292d8, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 16090] futex(0x7fcc43a279d0, FUTEX_WAIT, 16101, NULL

Thats it.. after the mp3 ended, the threads continued to work and quited..  

Whatever is responsible, it's build-inside Pioneer.

Here is your startlog:

[pioneer.stop.txt](https://github.com/pioneerspacesim/pioneer/files/3846594/pioneer.stop.txt)

**Comment by orbea** [comment]
What does this mean? Please share logs in english.
> mp3-cmdline: Kein Prozess gefunden

Just a guess, but try something like this instead of `killall`.
```
mp3-cmdline .... &
mp3pid=$!
pioneer ....
kill -15 "$mp3pid"
```

**Comment by Web-eWorks** [comment]
Closing this as unrelated, when Pioneer is executed normally we've observed no issues with phantom processes sticking around.
