### ISSUE TITLE
Can we put this game on itch.io?

### ISSUE THREAD

**Issue by ElonSatoshi** [pioneerspacesim/pioneer#4733]
* It would make the game more visible
* itch.io makes it easy for players to donate

This would definitely help give Pioneer more popularity (which could mean a few more contributors), and maybe bring in some money that could be used to improve it. *Might* be a good idea to put it on steam too, if you're okay with having it on such a DRM loving platform.

**Comment by fluffyfreak** [comment]
@ElonSatoshi did you mean to close this?

**Comment by impaktor** [comment]
How does one go about putting a game on itch.io?

If we put the game on steam, I think players expect pioneer to work better than it does, have fewer bugs, etc. and I suspect we'll be flooded by bug-reports.

But it's a catch-22 problem. We want more attention to get more devs. So if itch is smaller than steam, that might be interesting, in my opinion.

So basically: iteratively add pioneer to larger and larger communities / gaming sites.

**Comment by ElonSatoshi** [comment]
> @ElonSatoshi did you mean to close this?

Erm, I was afraid it sounded a bit pushy/weird, couldn't think of how to improve the tone of the post, and there wasn't a way to delete it so I closed it. But if you guys like the idea, I'll reopen it!

Itch.io is a great place for beginner game developers to publish buggy, even incomplete projects, so I don't think anybody there will expect too much of Pioneer.

I have an itch account, I could try to figure out how to put a game on there (which might require me to actually develop a simple terminal game or something, so I have something to put on there as a test.). Or, if you don't mind me receiving any donations, I could just see if I can figure out how to put Pioneer on itch myself.

**Comment by fluffyfreak** [comment]
A quick bit of Google-fu found this lot:
https://itch.io/developers
https://itch.io/docs/creators/getting-started

This is a thirdparty guide to publishing on Itch.io
http://wiki.compilgames.net/doku.php/gdevelop5/publishing/publishing-to-itch-io

**Comment by impaktor** [comment]
I'd say: anyone feel free to open a pioneer itch account, and put the game there, but please share login details with a "pioneerspacesim"-account with one/all of the currently active dev team: fluffy, noz, me.

**Comment by fluffyfreak** [comment]
@impaktor @ElonSatoshi I'd prefer a bit more discussion before putting it up there, like the copy (_text/images/etc_) to use. Also some plan for future updating of builds etc.

So please hold off on doing any creating or uploading of things.

I'll take a look tomorrow and create a new `pioneerspacesim` account then share details with the team somehow.

It's probably a good idea @ElonSatoshi so thanks for bringing it up.

**Comment by impaktor** [comment]
@fluffyfreak fine by me. @ElonSatoshi is on IRC, (as copenhagenbram) so come by at some time tomorrow for a chat. I might be afk, but I trust what every decision you guys make.

**Comment by ElonSatoshi** [comment]
I've already created a `pioneerspacesim` account and created a draft, I'm waiting for fluffyfreak and woz to join ##pioneer-itch (restricted, invite only channel where I've allowed the 3 of you to join) with impaktor and I where I'll give them a password.

**Comment by ElonSatoshi** [comment]
Or, I could just give it to someone, maybe fluffy, and the rest of the team could get itch accounts (you can log into itch using github) and fluffy could allow the others to edit the game page by adding their accounts as admins on Itch.

**Comment by ElonSatoshi** [comment]
Also I found out you can set a page to not accept any donations, that's how the draft is right now.

**Comment by Web-eWorks** [comment]
@ElonSatoshi probably pass the `pioneerspacesim` account to Fluffy - he's the de-facto project leader right now. I'm all for attaching the github/itch accounts of the people who are going to maintain the page - it's easier and a more hardened solution than just having a single login shared between three-ish people.

I'd be happy to help maintain the Itch page if you would like me to; although there's probably little enough to do that it's not worth the effort of adding an additional account.

@impaktor hey now, I'm still active-ish. Things have been slowing down over here, so I'm just about ready to tackle the renderer redesign.
On a totally related note, where's the best place to host design documents? I refuse to use MediaWiki syntax for anything longer than a few paragraphs, but chucking Markdown files into a `/docs/` directory in the repo seems a little overkill...

**Comment by fluffyfreak** [comment]
@Web-eWorks a `/docs/TDD/` (_Technical Design Document_) folder with Markdown might be a reasonable way to go for engine design things. 
Simple links to them from the Wiki would suffice to start with and if anyone has a particular bugbear about it then they're free to convert them over.

**Comment by impaktor** [comment]
So once we go live it will be on this url:
https://pioneerspacesim.itch.io/pioneer

I'm not sure what's missing for us to go live. 

As a bare minimum, if we have a verified working windows build, that should suffice, I guess.

**Comment by ElonSatoshi** [comment]
The Pioneer page is now live. How does it look, everyone?

**Comment by impaktor** [comment]
Looking good. Further discussions on IRC (or here), but closing now.

**Comment by wiki-me** [comment]
> If we put the game on steam, I think players expect pioneer to work better than it does, have fewer bugs, etc. and I suspect we'll be flooded by bug-reports.

If want to lower expectations, you can do what supertux [did](https://store.steampowered.com/app/1572920/SuperTux/) and mark the game as early access.
