### ISSUE TITLE
Crash on launch - pigui error - appveyor installer used for updating

### ISSUE THREAD

**Issue by nozmajner** [pioneerspacesim/pioneer#4744]
### Observed behaviour
The 2019 11 20 appveyor build (Appveyor says, it's 1.0.629) crashes with a guru meditation error:
![crash_pigui](https://user-images.githubusercontent.com/4182678/69267191-f9c6a300-0bcc-11ea-9aec-af6b91b1a295.png)
It did this when I updated the 20190203 release with the installer from appveyor. Uninstalling, and installing the appveyor build fresh fixed the problem, so I guess some files aren't updated if you install on an existing install.
No mods were active.
### Steps to reproduce
Install appveyor build on top of 20190203.

__My pioneer version (and OS):__
Windows 10.

**Comment by Web-eWorks** [comment]
Oh yeah, this is happening because I moved `pigui/modules/gauges.lua` into `pigui/modules/flight-view/gauges.lua` and therefore the old file is kicking around in your install.

The installer really should delete the current install when upgrading to avoid this kind of issue in the future.

**Comment by Web-eWorks** [comment]
CC @pcercuei...? I think you're the one who handling the windows installer.
For good measure, cc @fluffyfreak too.

**Comment by pcercuei** [comment]
Disagreed. Pioneer should just ignore old files.

**Comment by impaktor** [comment]
This might be resolved now, with fix to setup script. We'll notice.
