### ISSUE TITLE
Crash on "Show Comms" button press

### ISSUE THREAD

**Issue by MDutro** [pioneerspacesim/pioneer#4747]
### Observed behaviour
Game crashes to desktop when I press "Show Comms" button on UI.

### Expected behaviour
See comms. 

### Steps to reproduce
Start new game (any start), press "Show Comms"

__My pioneer version (and OS):__
Latest version for Linux 64-bit (downloaded today). OS - Manjaro Gnome

**Comment by MDutro** [comment]
Just for fun, I downloaded the Flatpak version. It works just fine, so it's possible that I didn't have some dependency or other?

**Comment by Web-eWorks** [comment]
Without a stacktrace, `output.txt` or any other detailed log of the error, we cannot diagnose or even *attempt* to fix the error. Please remember to follow the [bug reporting guide](https://pioneerwiki.com/wiki/FAQ#How.2Fwhere_do_I_report_my_bug.2Fcrash) when opening a crash bug.

**Comment by MDutro** [comment]
Enjoy.


[output.txt](https://github.com/pioneerspacesim/pioneer/files/3888936/output.txt)
[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/3888937/opengl.txt)

**Comment by Web-eWorks** [comment]
That's weird... the log shows that you do not have `libpng12` installed - every time it tries to load an image, it attempts to load libpng12 and fails. This is likely the source of your crash. The flatpack version is bundled with all needed dependencies and therefore does not exhibit this behavior.

I'm not sure why the Manjaro repos don't link in libpng correctly, but if you install that version of libpng it should stop crashing. I'd appreciate it if you could test that and let us know how it goes.

As an addendum, could you capture a stacktrace using GDB of pioneer when it crashes? If you have the system 'core dumps' option enabled, running `gdb /path/to/pioneer /path/to/dump/.12345` will allow you to print a stacktrace of the moment it crashed.

**Comment by mike-f1** [comment]
There's an old and closed issue with a long message chain which may help in order to have a background about `libpng`:

#3959

**Comment by Web-eWorks** [comment]
Closing as downstream issue; to my knowledge Pioneer builds against the system `libpng` version, which should be `libpng16` for distros which only ship, well... libpng16.

@MDutro please test the steps outlined above; if that does not fix the issue please re-open with a new `output.txt` captured with a properly installed libpng12.
