### ISSUE TITLE
Convert Info screens to PiGui

### ISSUE THREAD

**Issue by Web-eWorks** [pioneerspacesim/pioneer#4750]
This is a meta-issue tracking our progress in converting each screen in the Info tab from NewUI to PiGui.

**Progress**:
- [X] Ship Info (#4576)
- [X] Personal Info (#4584)
- [x] Cargo Hold / Trade (#4967)
- [X] Mission Info (#5025)
- [x] Crew Roster / Management (#5022)

Please feel free to use this issue for discussion and to coordinate your efforts!

**Comment by vakhoir** [comment]
@impaktor said it would be a good idea to mention anything we're working on here.  I'm still a few steps away from anything I can show off, even as a WIP, but I'm currently working on the Mission Info view.

**Comment by impaktor** [comment]
@vakhoir perhaps you're interested in #2014, and maybe #1778, or perhaps we want to just close that one?

**Comment by impaktor** [comment]
I started playing around with moving "Cargo hold / trade" to imgui, (layout and pump down/up needs more work, but cargo manifest & jettison buttons work) branch: [impaktor/econ-trade](https://github.com/impaktor/pioneer/tree/econ-trade). (I intend to work on this some more on rainy days during my current summer vacation)

**Comment by Web-eWorks** [comment]
Another one down, another one bites the dust!
