### ISSUE TITLE
Convert Station screens to PiGui

### ISSUE THREAD

**Issue by Web-eWorks** [pioneerspacesim/pioneer#4751]
This is a meta-issue tracking our progress in converting the Station screens from NewUI to PiGui.

**Progress:**
- [X] Lobby Screen (#4651)
- [x] Bulletin Board (#4775)
- [X] Commodity Market (#4654)
- [x] Ship Market (#4774)
- [X] Equipment Market (#4624)
- [x] Ship Repairs (#4791)
- [x] Police (#4790)

Please feel free to use this issue for discussion and to coordinate your efforts!

**Comment by impaktor** [comment]
I'm having a go at the Police tab, I think I've done work on that tab in the past, with the legal PR (#3254), unless @vakhoir (ping) has already started on it?

**Comment by vakhoir** [comment]
Oh, I haven't noticed this, but at this point you probably know I'm doing the bulletin board ;) Go ahead, I'll be happy to review it.

**Comment by impaktor** [comment]
@vakhoir If you haven't started on _Ship Repairs_, I'll do that next.

**Comment by impaktor** [comment]
Now, only #4750 remains :+1: 

I dunno if/what @vakhoir and @Gliese852 will work on next? Maybe post in #4750 if either of you have started on any of the InfoView screens that remain.
