### ISSUE TITLE
Save game dialog does not appear

### ISSUE THREAD

**Issue by cwyss** [pioneerspacesim/pioneer#4755]
### Observed behaviour

The save game dialog does not open when pressing the save button, i.e. flight UI -> Esc -> "Save" button.
After pressing the save button once, also Load Game from the main menu stops working.
quicksave via Ctrl-F9 works fine.

__My pioneer version (and OS):__
d0f26555 (current master)

last bug free:
d016f7a5 (Nov 16 2019)

**Comment by impaktor** [comment]
Yep, it's a known bug, I hope it will be short lived, as it's pretty serious for user experience. 
Thanks for reporting!

**Comment by cwyss** [comment]
Thanks for the info.

I also noticed just now that the dialog box to change a key binding opens _behind_ the options dialog box. But this is probably also known already... :)

**Comment by impaktor** [comment]
....or if you @cwyss have time to look at this, that would be nice. Seems like a pretty major serious bug.

**Comment by vakhoir** [comment]
> @vakhoir do you have time to look into this?

I finally do!
Looking into it now

**Comment by impaktor** [comment]
Great! Do note, there's a PR for it, #4755, but author seems to indicate it's not working as expected. 

I think @Web-eWorks said he knew what was amiss with this bug:

```
<sturnclaw> [08:51:30] yeah, the save issue is just the code in pigui.lua
            being designed for only one modal
<sturnclaw> [08:52:02] I can rip that out and rewrite it in an afternoon, but
            I haven't been able to *think* much less work on Pioneer for the
            past week or so
```

**Comment by Web-eWorks** [comment]
Hmm, on second thought we don't seem to be wrapping the `ImGui::BeginPopupModal()` in any custom code, so it may just be an incorrect use of `ui.openPopup()` / `ui.closeCurrentPopup()`; I'd recommend investigating the imgui docs and looking at the code in `imgui.cpp` and related files...

**Comment by vakhoir** [comment]
Yeah, it's fixable in lua, but I have to say I'm not sure what the ImGui people were going for when they decided the separete openPopup from beginPopup, and then having openPopup be called only once on open, when everything else in the UI has to be called once per frame...

Anyways I have something worked out, I'll be testing and polishing it tomorrow.

**Comment by vakhoir** [comment]
Oh, should've hit refresh

> Hmm, on second thought we don't seem to be wrapping the ImGui::BeginPopupModal() in any custom code, so it may just be an incorrect use of ui.openPopup() / ui.closeCurrentPopup();

What do you meant @Web-eWorks ?

It was incorrect in that if you want nested modals, you need to call openPopup after the first BeginPopupModal was called **and** openPopup should/must be called only once on open, rather than every frame. Makes the whole thing pretty complicated, particularly when each popup is set up by a different script, but I more or less sorted it out.

**Comment by Web-eWorks** [comment]
@vakhoir yeah, that was what I meant - that our current implementation in Lua was mangling the ImGui modal stack. Thanks again for tracking this down!

**Comment by vakhoir** [comment]
Well, I'm the one that screwed this up in the first place ;)

**Comment by vakhoir** [comment]
Hm, can anyone confirm that loading a saved games works? I get the following exception thrown:

`pioneer: ./pioneer/src/Frame.cpp:191: static FrameId Frame::FromJson(const Json&, Space*, FrameId, double): Assertion `(s_frames.size() - 1) != f->m_thisId.id()' failed.`

Can't tell when it started, probably somewhere around #4669, #4745, or #4754. Still works fine on my (rather old) branch https://github.com/vakhoir/pioneer/tree/feature/rescale_ui

**Comment by cwyss** [comment]
@vakhoir 
> Hm, can anyone confirm that loading a saved games works? I get the following exception thrown:

Never had such a problem, as long as I did not try to load very old saved games, i.e., which were saved with a much older pioneer version. In particular, I get no problems doing ctrl-f9 and then loading `_quicksave` again in 0881148a85e247a6

**Comment by vakhoir** [comment]
I made sure to save a new game during the test, and I get the same result testing from the commit you specified.

I'm suspecting this is some compiler/OS weirdness. Anyone else using GCC on Ubuntu?

**Comment by Gliese852** [comment]
I am using GCC on Ubuntu. Installed this branch. The problem with loading both new saves and slightly older ones (about a month) is not observed.

**Comment by vakhoir** [comment]
Huh... well, that's frustrating. It's 100% reproducible for me.

**Comment by Web-eWorks** [comment]
@Gliese852 can you try running `./bootstrap -DCMAKE_BUILD_TYPE=Debug` and recompiling? Sounds like this is an assertion that's being triggered but isn't throwing because you're compiled in Release mode...

We've had intermittent issues with this frame code, so I'll take a closer look at it later on this week.

**Comment by Gliese852** [comment]
```
pioneer: /home/vasya/src/Gliese852/pioneer/src/Frame.cpp:191: static FrameId Frame::FromJson(const Json&, Space*, FrameId, double): Assertion `(s_frames.size() - 1) != f->m_thisId.id()' failed.
Aborted (core dumped)
```

**Comment by Web-eWorks** [comment]
Alright, good to know. I'll dig into the save / load code (as well as a saved game) and see what the issue is; my guess is that we still have some incorrect logic related to frame ordering.

Can anyone confirm that loading a save causes any issues? Obviously something's a little wonky here but my guess is that this is mostly a harmless `assert()`

**Comment by vakhoir** [comment]
> Can anyone confirm that loading a save causes any issues? Obviously something's a little wonky here but my guess is that this is mostly a harmless `assert()`

Yeah, everything works fine when it's commented out.
