### ISSUE TITLE
can't click on fullscreen

### ISSUE THREAD

**Issue by Unixware** [pioneerspacesim/pioneer#4759]
release 

### Observed behaviour

game works on normal window, but can't click on anything when on fullscreen

### Expected behaviour
obvious...

_My pioneer version (and OS):__

SDL Version (build) 2.0.7
SDL Version (dynamic) 2.0.7
SDL Versions match
SDL_image Version (build): 2.0.1
SDL_image Version (dynamic): 2.0.1
SDL_image Versions match
Assimp Version: 3.2.84206075
FreeType Version: 2.5.2
GLEW dynamic version: 2.0.0

Linux - Fedora 31 / XFCE  / x64
GFX: Intel HD4400

**Comment by Web-eWorks** [comment]
@Unixware we will need your Pioneer version as well - you can find it in the output.txt file or in the lower right corner of the main menu. Thank you for the detailed system information though!

Pioneer does have some WM-specific issues; we've tried to work around them where possible, but differing SDL versions and interactions between the game in fullscreen and the window manager mean we can't fix them all.

Judging from the SDL version, you're using a Pioneer build from several releases ago, possibly even 1-2 years. If you can, can you try compiling the latest git tag or master branch and seeing if that resolves the issue?

**Comment by Unixware** [comment]
thanks! 

the info on bottom says " 20190203 (425c372)"

I will try to compile the "latest" (201911xx) and let you know.

**Comment by Web-eWorks** [comment]
Perfect! This is probably related to an upstream packaging issue then, as I don't think we changed all that much in regard to the input handling code between those two releases.
