### ISSUE TITLE
Mouse cursor changes when you hide HUD

### ISSUE THREAD

**Issue by manolollr** [pioneerspacesim/pioneer#4762]
Mouse cursor changes when you hide HUD (default: press TAB key twice) and stay like this until you finish the game.

This is normal mouse cursor:
![mouse_cursor_0](https://user-images.githubusercontent.com/8089376/71481655-11fa9500-27ff-11ea-885a-a7d4737ce249.png)

And this is the cursor that appears when you hide HUD:
![Cursor_bad](https://user-images.githubusercontent.com/8089376/71481675-250d6500-27ff-11ea-8b73-3079c5c85af6.png)

### Steps to reproduce
Hide HUD, in default key config: press TAB twice

ArchLinux
Pioneer git latest commit: 619ed1b

**Comment by Web-eWorks** [comment]
That's weird... What's your desktop environment / compositor? Pretty sure I tested HUD mode toggle and the mouse cursor stayed the same the last time I touched IMGUI.

**Comment by cwyss** [comment]
I can confirm this behaviour, both with current upstream and with 3fdd945 (24 dec 2018).

I'm running Debian 9 Stretch with standard gnome desktop env on x11, not wayland

**Comment by manolollr** [comment]
I'm using ArchLinux with Cinnamon desktop on x11, and with proprietary nvidia drivers v440.44

I've tested with i3 WM and it fails too.
