### ISSUE TITLE
Pioneer fills swap partition to crash or freeze

### ISSUE THREAD

**Issue by Bodasey** [pioneerspacesim/pioneer#4780]
### Observed behaviour

Playing the game, a lot of data are written to the swap partition until it's full and then, pioneer either crashes (rare) or the computer freezes (most cases). With 16GB swap, this happens after about one to two month in-game time.

### Expected behaviour

Should just not happen?

### Steps to reproduce

just play

__My pioneer version (and OS):__
Release(Kernel) Version: 4.12.14-lp151.28.36-default openSUsE Leap
Kernel Build Timestamp: #1 SMP Fri Dec 6 13:50:27 UTC 2019 (8f4a495)
Machine Arch: x86_64

**Comment by impaktor** [comment]
What language setting are you using when playing? Engligh?

**Comment by Bodasey** [comment]
Deutsch / German

**Comment by impaktor** [comment]
Sounds like #4778, which there already is a fix for, not merged yet, though.

**Comment by impaktor** [comment]
@Bodasey To confirm the above, you could try to see if there's a difference with playing with English in-game language.

**Comment by vakhoir** [comment]
I recommend leaving the Equipment Market open for a few minutes, and just keep track of RAM with `top` / `htop` / whatever you prefer, rather than waiting for a crash or freeze. Like impaktor said, it should be stable on English, and from my experience it runs out pretty fast in German.

**Comment by impaktor** [comment]
> should be stable on English, and from my experience it runs out pretty fast in German. 

Ouch, german computers need their lebensraum?

(OK, very sorry, I just had to :roll_eyes:  )

**Comment by Bodasey** [comment]
Confirmed that it is a problem with the language set to german

**Comment by Bodasey** [comment]
Confirmed that it is a problem with the language set to German, English and French are not affected.

**Comment by impaktor** [comment]
@Bodasey thanks for reporting! Then indeed this should be fixed by  #4779, so you can either try compiling that, or wait until it's merged into master.

**Comment by impaktor** [comment]
Closing, as we are already tracking this issue in another bug-report, as mentioned above.
