### ISSUE TITLE
Spaceship is crashing when i trying to dock to thebe gas rafinery.

### ISSUE THREAD

**Issue by 111ukasz111** [pioneerspacesim/pioneer#4781]
### Observed behaviour
Spaceship is crashing

### Expected behaviour
Spaceship is docked

### Steps to reproduce
1.Try to dock to thebe gas rafinery using autopilot.

__My pioneer version (and OS):__
windows 10 64 bit 
pioneer 20190203

[Pioneer.zip](https://github.com/pioneerspacesim/pioneer/files/4134988/Pioneer.zip)

**Comment by vakhoir** [comment]
That's one hell of a 1-star review to leave the auto-pilot manufacturer.

**Comment by nozmajner** [comment]
Could you elaborate it a bit more? I just tried, form the Mars start, and my ship crashes into Jupiter. Is it the case for you as well?  If so, you could try first going to a Jupiter medium orbit, then approach Thebe.
Until the autopilot is fixed, that is.

**Comment by 111ukasz111** [comment]
Just try to dock to thebe gas rafinery in my savegame from zip.

**Comment by nozmajner** [comment]
Hmm, it seems that the terrain generator is the culprit. Try changing the terrain resolution, and see if it resurfaces.

**Comment by 111ukasz111** [comment]
This is a bug.

**Comment by Bodasey** [comment]
fixed / single event? I had no such problems in actual master branch versions.

**Comment by Web-eWorks** [comment]
Closing this as it appears to be driven by terrain LOD issues.
