### ISSUE TITLE
UI Stuck in state, can't get out after TAB TAB ESC

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#4783]
### Observed behaviour
WorldView UI gets stuck in state where no key press takes me back 

### Steps to reproduce
1. start new game
2. while docked, press TAB twice, to get to the "clean screen" with only station name showing, 
3. press ESC
4. Now you can not TAB the ship controls back. (or can you?), TAB and ESC keys have no effect.

### Expected behaviour
Pressing TAB again will cyckle the UI back, or/and possibly ESC brings up settigs/options menu?

__My pioneer version (and OS):__
Current master, 5938ecc39fca0cad9f30b56195083a2bd2f1ba18

**Comment by Bodasey** [comment]
Can confirm that also for the latest build version 20200203, and it happens also when flying, I have also not found a way out.

Did you also notice that the mouse pointer permanently changes after TAB TAB and is catched in a doubled viev in the window when you move it out? I don't think this is a feature.

Using actual openSUsE leap and KDE

![before-TAB](https://user-images.githubusercontent.com/60466586/73757542-a72b6a80-4769-11ea-9571-777ae3c1a860.png)
![after-TAB-TAB](https://user-images.githubusercontent.com/60466586/73757544-a72b6a80-4769-11ea-912e-69d6f052f87d.png)
