### ISSUE TITLE
Improvements to build/release process

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#4788]
Now that we just got a new [build released](https://github.com/pioneerspacesim/pioneer/releases/tag/20200203), here's a write-up of what worked and didn't work, and the improvements needed, (this can also be refereed to as an "How-To" for next release).

## What we did
- Start a draft release, summarize the major changes since last build from [Changelog.txt](https://github.com/pioneerspacesim/pioneer/blob/master/Changelog.txt), from player's perspective, and noticeable bug-fixes
- Push tag should be: YYYYMMDD
- [Tweet](https://twitter.com/pioneerspacesim/status/1224399814483480576) something nice about the release
- Update [flatpack](https://github.com/flathub/net.pioneerspacesim.Pioneer/), e.g. ping @pcercuei 
  - URL to tar ball
  - Version tag and date
  - [this](https://flathub.org/repo/appstream/net.pioneerspacesim.Pioneer.flatpakref) link always points to latest flatpack
- Manually rename and upload the appveyor build artifact to the release notes
- Manually rename the auto-uploaded linux build artifact to have `_linux` suffix.

## What happened
When we pushed the tag:
- Travis seems to have successfully built:
  - linux version with both clang and gcc
  - osx version
- Appveyor successfully built windows version
- However, the only auto-published build artifact to the github release page was the linux version from Travis.

## Actions needed / issues
1. The Poineer download page should link to github release page instead of sourceforge
2. Disband sourceforge? Do we need it? (To show download statistics of the github release files, a [GET post](https://help.github.com/en/github/administering-a-repository/getting-the-download-count-for-your-releases) to the API is needed (good/bad?)).
3. Travis linux build should have suffix `_linux.tar.gz` (I changed this manually)
4. Travis should publish _both_ linux and osx build artifacts to github page, not just the linux-version, as it did.
5. Would be nice if Appveyor build artifact was named: `pioneer_<tag>_win.exe`, instead of `pioneer-setup.exe`
6. Appveyor build artifact should auto-publish to github release page (I upploaded it manually)

## Addendum
The flatpak https://github.com/flathub/net.pioneerspacesim.Pioneer doesn't build since it links to some dead screenshot no longer on our webpage @pcercuei has his hands on this.

([Here](https://www.internalpointers.com/post/build-binary-deb-package-practical-guide) is a guide for building binary deb-packages, might be useful sometime in the future) 

Also, we should remember to:
- update https://pioneerspacesim.itch.io/pioneer
- Post on [SSC](http://spacesimcentral.com/community/pioneer/)
- Post on discord? (we have such a channel somewhere)

__EDIT__ Download counts for github release available [here](https://api.github.com/repos/pioneerspacesim/pioneer/releases)

**Comment by fluffyfreak** [comment]
@impaktor is `YYYMMMDD` supposed to be `YYYYMMDD`?

**Comment by fluffyfreak** [comment]
Also can we get the other artefacts, rename, then upload them so that the Win and OSX builds are also available for this release?

**Comment by impaktor** [comment]
Thanks, fixed the typo. Yeah, I can't find the build artifacts from Travis, meaning the OSX build is lost? Or I'm just not seeing it.

**Comment by Web-eWorks** [comment]
Travis does not generate 'artifacts' as such; the results of a build are only kept if you deploy them to an external storage (Github Releases, etc.) as part of the build process. The OSX build did not deploy because there is a slight issue with the build script (you can take a look at that [here](https://travis-ci.org/pioneerspacesim/pioneer/jobs/645492696?utm_medium=notification&utm_source=github_status)); I'll see about fixing that soon.

**Comment by Web-eWorks** [comment]
@fluffyfreak yes, and I think I know why - I used `tar -caf <filename> [in files]`... which is a GNU-specific extension to automatically determine compression type. I'll change that to explicitly gzip compress our builds instead when I update the build script.

**Comment by impaktor** [comment]
Looking at our .travis.yml-file and the build-travis.sh script, I really don't see where it says which of the two linux versions to deploy, nor even trying to deploy the osx version. 

Oh, well, whatever works.

**Comment by Web-eWorks** [comment]
Technically, that's because *both* are deploying. It's a race condition, so the GCC build usually wins by virtue of taking about a minute less to compile. It's yet another thing on the pile of things I want to fix...

**Comment by impaktor** [comment]
https://pioneerwiki.com/wiki/Makeing_a_release

**Comment by Zireael07** [comment]
Nitpick: the title should be "Making" not makeing. Unless you were making a reference to the make command, but then such puns are better left for the text itself, not title...

**Comment by impaktor** [comment]
@Zireael07 spelling is difficlut...
But thanks for pointing it out. I'll get to it at some point.
