### ISSUE TITLE
./bootstrap doesn't populate build directory on Linux

### ISSUE THREAD

**Issue by pirogronian** [pioneerspacesim/pioneer#4789]
### Observed behaviour
After `./bootstrap` run, `build`directory is empty. So, `make -C buid` fails due to lack of `Makefile` file.

### Expected behaviour
There should be `Makefile` inside `build` and `make` should compile and build the game.

### Steps to reproduce
Run
`git pull`
`./bootstrap`
`make -c build` (I dont use multithreading)

__My pioneer version (and OS):__
OS: Arch Linux. Up-to-date.
Pioneer version: master, just pulled from git.

**Comment by impaktor** [comment]
Please try:
```
./bootstrap cmake
```

And close the issue if success

**Comment by pirogronian** [comment]
Result is the same, directory remains empty. Moreover, in both cases, console logs clearly indicate that build directory is root project dir:
```
./bootstrap cmake
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/pub/Program/git/pioneer
```

**Comment by Web-eWorks** [comment]
Please double-check you're in the correct directory and that manually running the commands `mkdir -p build; cd build; cmake ..` produces the correct output. The script expects a working directory equal to the project root, and should be unequivocally creating the build directory... are your directory permissions set incorrectly?

**Comment by pirogronian** [comment]
First test.
```
$ >> rmdir build
pioneer $ >> ls -l|grep build                                                                                                                           
-rw-r--r--  1 ja ja       274 02-04 16:04 buildopts.h
-rw-r--r--  1 ja ja       300 01-30 18:01 buildopts.h.cmakein
pioneer $ >> ./bootstrap
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/pub/Program/git/pioneer
pioneer $ >> ls -l|grep build                                                                                                                           
drwxr-xr-x  2 ja ja      4096 02-06 17:17 build
-rw-r--r--  1 ja ja       274 02-06 17:17 buildopts.h
-rw-r--r--  1 ja ja       300 01-30 18:01 buildopts.h.cmakein
pioneer $ >> pwd                                                                                                                                        
/mnt/pub/Program/git/pioneer
pioneer $ >> ls -al build                                                                                                                               
razem 8
drwxr-xr-x  2 ja ja 4096 02-06 17:17 .
drwxr-xr-x 23 ja ja 4096 02-06 17:18 .. 
```
(`ja` is my username (and my group)).
So, I'm sure commands are run from correct directory and I have a proper access to this directory.

Second test.

```
pioneer $ >> mkdir -p build; cd build; cmake ..
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/pub/Program/git/pioneer
build $ >> echo $?                                                                                                                                      
0

```

**Comment by impaktor** [comment]
I'm also on Arch Linux, and works here. Just to make sure, you are running these commands from your pioneer directory, looking approximatly like:
```
aclocal.m4
application-icon
appveyor.yml
AUTHORS.txt
autoformat
autom4te.cache
bootstrap
build
buildopts.h.cmakein
Changelog.txt
CI
cmake
CMakeLists.txt
COMPILING.txt
contrib
data
debian
depcomp
doxygen
install-sh
licenses
metadata
Modelviewer.txt
msvc-defaults.cmake
nd
nix
osx
pioneer
pioneer.iss.cmakein
pioneer.rc.cmakein
Quickstart.txt
README.md
SAVEBUMP.txt
scripts
src
win32
```

**Comment by pcercuei** [comment]
Chances are that you already ran CMake in the source folder, so you have a CMakeCache.txt and CMakeFiles/ there. That explains why in your second test it only says "Configuring done", since it doesn't actually reconfigure anything.

**Comment by pirogronian** [comment]
@pcercuei Indeed, thanks for pointing it out. So, now I ran
```
pioneer $ >> git clean -d -f -x  
pioneer $ >> ./bootstrap    
-- The CXX compiler identification is GNU 9.2.0  
-- Check for working CXX compiler: /usr/bin/c++  
-- Check for working CXX compiler: /usr/bin/c++ -- works  
-- Detecting CXX compiler ABI info  
(...)
-- Build files have been written to: /mnt/pub/Program/git/pioneer/build
```
So I consider it solved.
