### ISSUE TITLE
Commodity market activities not reset

### ISSUE THREAD

**Issue by Cyborgscode** [pioneerspacesim/pioneer#4797]
Version: 20200203
OS: Fedora 30

Steps to reproduce:

Dock.
Commodity Market
select i.e. Radioatives to be bought, but don't buy them.
(i.e. take a transport mission)
Fly to a different station ( i think redocking would result in the same result)
Dock.
Open Commodity Market.

You will notice that the ui still shows the selection to buy the commodity you had earlier.
Conclusion: Market window is not reset to default on undock.

**Comment by impaktor** [comment]
Good catch! @vakhoir might want to include a fix for it in #4775

**Comment by vakhoir** [comment]
This might be just a display issue - the selected item is not reset when the view is refreshed. I'll fix in that PR.
