### ISSUE TITLE
ship carshed on ap from poseidon station to shanghai

### ISSUE THREAD

**Issue by Cyborgscode** [pioneerspacesim/pioneer#4798]
Ship traveled with ap enabled from poseidon station to shanghai, earth, and crashed on earth.

### Observed behaviour

Ship crashed on planet earth.

### Expected behaviour

AP avoiding direct flight path thru solid objects.

### Steps to reproduce

__My pioneer version (and OS):__

V: 20200203
O: Fedora 30

**Comment by Web-eWorks** [comment]
Closing this as a quirk, without a savefile attached there's little we can do to debug it. The autopilot has some bugs where it's simply not feasible to calculate every possible edge case, and this looks like one of them.
