### ISSUE TITLE
src/pigui/Face.h & src/gameui/Face.h both "export" the same enum

### ISSUE THREAD

**Issue by Gliese852** [pioneerspacesim/pioneer#4801]
### Observed behaviour
After rescan enums with **scripts/scan_enums.py**, the project does not build and shows an error:

`enum_table.cpp:286:44: error: redefinition of ‘const EnumItem ENUM_GameUIFaceFlags []’
 const struct EnumItem ENUM_GameUIFaceFlags[] = {`

Comparing these two files, you can see that they contain the same instructions for the script:
https://github.com/pioneerspacesim/pioneer/blob/f7f4abd5ab22296fb9bf00c6676efdfa65fac3af/src/pigui/Face.h#L22
https://github.com/pioneerspacesim/pioneer/blob/f7f4abd5ab22296fb9bf00c6676efdfa65fac3af/src/gameui/Face.h#L25

The question is can we just rename **GameUI** to **PIGUI** in src/pigui/Face.h ?

### Expected behaviour
Successful recompilation after rescan.

### Steps to reproduce
1. run `./scripts/scan_enums.py --pattern="*.h" -r -o ./src/enum_table.cpp ./src`
2. run build

__My pioneer version (and OS):__
current master f7f4abd5ab22296fb9bf00c6676efdfa65fac3af

**Comment by Web-eWorks** [comment]
That looks like a simple oversight when implementing the pigui face display code. From what I can see, we very much should rename that to PiGUI, so I'd welcome a pull request to that effect! :smile:
