### ISSUE TITLE
New game may give you zero equipment

### ISSUE THREAD

**Issue by pcercuei** [pioneerspacesim/pioneer#4803]
### Observed behaviour

It's possible to start a new game at Barnard's Star (and probably the others as well) without any equipment given to the player.

### Expected behaviour

The player should start with the atmospheric shielding, the radar, and the autopilot.

### Steps to reproduce

1. Create a new game at Barnard's Star.
2. Sell your equipment.
3. Save the game.
4. Return to the main menu.
5. Load the game.
6. Return to the main menu.
7. Create a new game at Barnard's Star. Now you don't have any equipment.

__My pioneer version (and OS):__
pioneer master (e25517163) on Debian x64.

**Comment by craigo-** [comment]
The symptoms and steps to reproduce sound eerily similar to #4675

**Comment by WKFO** [comment]
Happened to me recently.

- I sell some of my equipment in-game.

- I close the game and return to main menu.

- I start a new game on Mars. My ship only has a hyperdrive.

**Comment by Another-MrZ** [comment]
I had same experience, but slightly different.
If you start a new game afresh (difficult start), you get your Xylophis with all the equipment that appear in the shop list as sellable.
But if you chose different settings, then restart, or if you sell your equipment and restart, you still get all the needed equipment, but it does not show up in the shop list neither in the Ship equipment list.
I started a game this way: I still had autopilot, atmospheric shielding and radar, but they would not show up and could not be sold.

**Comment by joonicks** [comment]
ship equipment isnt stored in the C++ domain, its stored in the Lua domain... isnt Lua being reset fully between games?

**Comment by maxcrystal** [comment]
I have the same bug. New game starts without any equipment visible anywhere (except hyperdrive).

**Comment by impaktor** [comment]
@maxcrystal thanks for reporting many bugs, if you find any way to reproduce this, or report if it's random (how often?), or always only hyperdrive, then please fill us in with any more info you find.

This bug was also reported on [SSC](https://spacesimcentral.com/community/pioneer/new-pioneer-release-2020-12-22/#post-59020) for the release candidate 1 (20201222-rc1)

**Comment by Web-eWorks** [comment]
Closing as addressed by #5734 - please re-open if still valid in the upcoming release.
