### ISSUE TITLE
Number of cabins is incorrectly reported

### ISSUE THREAD

**Issue by pcercuei** [pioneerspacesim/pioneer#4806]
### Observed behaviour

With 3 cabins equipped, one used and two available, the game reports in the ```<F4>``` menu:
```Cabins: 33% 1t used, 3t free```

### Expected behaviour

The game should report:
```Cabins: 33% 1t used, 2t free```

__My pioneer version (and OS):__
git master (e25517163), Debian x64

**Comment by impaktor** [comment]
Seems like the cabin always shows the total capacity as the current free capacity:
I've filled all my 3 cabins, and the pigui `StationView:shipSummary()` shows "3t used/3t free".

The NewUI isn't much better, it shows "2 used, 0 free" (should be "__3__ used, 0 free"). That's a minor point, as we're killing that off today, with #4775.

**Comment by impaktor** [comment]
Looks like it's just counting the number of cabins in the "cabin" slot, however, both the occupied and empty cabin are in that slot, thus this error.

**Comment by pcercuei** [comment]
Still not working right. Now I get ```Cabins: 50% 1 used, 2 free```. It should be 33%.
