### ISSUE TITLE
Trifecta of bugs revealed in sectorview (F2)

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#4815]
## Ship jump status
When preparing #4814, I noticed the jump state shown in the search match list (see screenshot in that PR) is sometimes wrong, and reproducible so:

1. Start new game at Bernard's Star
2. Go to sector view, search for some system. You'll see the "NO_DRIVE" (if on current master) suffixed for all suggested star system matches, as is correct.
3. Start new game from e.g. Sol, repeat 2 above, but now you have a hyperdirve, yet, you still get the "NO_DRIVE" message.
   
This doesn't happen if starting from Sol directly when starting a pioneer session.

## Draw vertical lines
This is what I suspect is happening (I haven't tested it much): When opening sectorview and the default selected system is below the plane, it draws vertical lines even if the lines are turned off. One has to turn them on, then off again to remove them. This is easily reproducible by starting new game (assuming you have vertical line drawing turned off) at New Hope and opening sectorview, then Epsilon Eridani is selected, and there be vertical lines in great abundance.

## Remember settings between pioneer sessions
Every time I start a new game in pioneer, the option "Label uninhabited systems" is ticked. Me thinks once I un-tick it, it aught to remember that for next session. I think our pigui supports storing variables, right?

## My version
Current master: b08c31fe4d262f03253064085fa5fc31af197f73

**Comment by craigo-** [comment]
Re your second point, see also issue #4708.

Issues #4675, #4676, #4803 are other examples of things not quite going right when starting a new game or loading a saved game. It seems to be far-reaching.

I noticed another one today in a recent master regarding the orientation and registration of the spinning model in the Ship Information screen... I'll create a separate issue for it.

**Comment by Gliese852** [comment]
Partially #4708 will be fixed in #4852, settings are not yet saved to the savefile, but remain constant until the program exits

**Comment by impaktor** [comment]
Remaining bugs tracked in #5178
