### ISSUE TITLE
Fix Appveyor error with deploying MINGW build

### ISSUE THREAD

**Issue by Web-eWorks** [pioneerspacesim/pioneer#4823]
@fluffyfreak I'm kicking this one your way because (IIRC) you're the one most knowledgeable about appveyor builds.

Our MINGW appveyor build is throwing a false positive error because it is unable to upload the generated build artifact due to a `500 internal server error` response code during the deployment step. We need to figure out what is causing this error and if necessary disable deploying MINGW builds; it's far too easy to miss that a pull request has a serious issue with it when *every* pull request is showing as failing due to a single AppVeyor build instance running into an issue.

**Comment by impaktor** [comment]
> you're the one most knowledgeable about appveyor builds.

I think @pcercuei have helped us a lot with appveyor in the past. Hopefully also in the future/now, :smiley: and @fluffyfreak has been the MINGW expert.

I hope I got that right.

**Comment by fluffyfreak** [comment]
I think I might be the _least_ knowledgable about Appveyor builds 🤔

**Comment by pcercuei** [comment]
Same problem as usual: https://github.com/appveyor/ci/issues/2005#issuecomment-592970751

**Comment by fluffyfreak** [comment]
Oh it's that again, we should have a note somewhere to remind me what it is because it comes up so infrequently

**Comment by The-EG** [comment]
Closing this; appveyor seems to be working again for PRs.

From the sounds of it, we may have finally hit a delayed retention date or they finally cleared out the build artifacts.

**Comment by pcercuei** [comment]
@fluffyfreak, keep in mind this is a *free* service.

**Comment by fluffyfreak** [comment]
Yes, but that doesn't automatically mean it's one we should use

**Comment by pcercuei** [comment]
What's the alternative?

**Comment by Web-eWorks** [comment]
I forgot to close this issue - Appveyor was having extreme issues with mingw builds, to the point that it wouldn't even *install* mingw on appveyor's end. I've disabled the mingw build entirely as a result, which is why appveyor builds are working again. We weren't even getting as far as a `500 internal server error`, and the mingw build didn't live longer than about 30s per invocation due to whatever issues appveyor is having.
