### ISSUE TITLE
Incorrect Translation Strings for Language Names

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#4825]
This is on translation/[transifex]() side, but crem pointed out there are 4 strings reading "English":
![img](https://i.imgur.com/beH0o0x.png)

The second "English" is "eo.json", which might be Esperanto?

Just filing this, so it's not forgotten.

**Comment by impaktor** [comment]
OK, fixed the Esperanto one now. Won't deal with the other two now, due to lazy.

**Comment by Web-eWorks** [comment]
The other two are Bulgarian and Lithuanian, respectively. Unfortunately I speak neither of those languages, so someone else will have to source the correct word, lest I do more harm than help.

**Comment by impaktor** [comment]
Fixed.
