### ISSUE TITLE
Since PR #4794 game crashes when SetSpeed Target is set to a space station and later you go to another star system

### ISSUE THREAD

**Issue by manolollr** [pioneerspacesim/pioneer#4829]
### Observed behaviour
- Since PR #4794
- Press Ctrl - Click on a space station to set it as the SetSpeed Target
- Go to another star system.
- Press F5 to activate the SetSpeed autopilot
- Game crashes with the following errors:

```
error: In 'GetFrame': fId is valid but out of range (1853476096)...

error: Frame instance deletion outside 'DeleteFrame' [0]
```

If you only go to another planet, game doesn't crash, but the previous space station is memorized as SetSpeed Target and this is uncomfortable.

### Expected behaviour
If you go to another planet or another star system I think SetSpeed Target must be the main planet or star you are. This was the normal behaviour for years.

**Edit:**
On any target change the SetSpeed Target is cleared as expected. So the only undesired behaviour (crash) is when you go to another star system.

**Comment by Web-eWorks** [comment]
Thank you for discovering this issue! We'll get it taken care of very swiftly; looks like we forgot to clear the SetSpeedTarget when jumping to a new system, and that's kept a reference to a previous physics Frame alive.
