### ISSUE TITLE
Background stars don't track sector position

### ISSUE THREAD

**Issue by fluffyfreak** [pioneerspacesim/pioneer#4837]
### Observed behaviour
As the player moves through the galaxy the stars don't track or change with the players position like they should

### Steps to reproduce

__My pioneer version (and OS):__

**Comment by Web-eWorks** [comment]
Thanks for tackling this! I've got a fix for the duplicate initialization of the starfield which you're welcome to snag and submit in the same PR; I'll get it pushed with the rest of my recent work in a few minutes.
