### ISSUE TITLE
ESC button does not work in Station Screens

### ISSUE THREAD

**Issue by Gliese852** [pioneerspacesim/pioneer#4851]
### Observed behaviour
When any of the station screens
- Lobby Screen
- Bulletin Board
- Commodity Market
- Ship Market
- Equipment Market 
- Ship Repairs
- Police

is active, nothing happens when I press the ESC button.

### Expected behaviour
A menu window should open.

__My pioneer version (and OS):__
current master 2e44d9302e11d94d172a38f2417e98b080d01821 (Ubuntu 18.04.3 LTS)

**Comment by CmdrBugbear** [comment]
Just confirming that I've observed this behaviour too on a recent build.

**Comment by impaktor** [comment]
One could argue esc should close windows until back to worldview, and then open settings window, but perhaps that is strange?

**Comment by Web-eWorks** [comment]
That's been default behavior for oldUI / newUI screens; it fell off in the move to pigui, but shouldn't be too terribly difficult to restore.
```lua
if ui.isKeyPressed(ui.keys.escape) then Game:SetView 'WorldView'; return end
```

(note: pseudocode, please use the actual method call and look at the docs instead of working from memory...)
