### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by pirogronian** [pioneerspacesim/pioneer#4853]
Version: git master from Sat Apr 4 15:53:54 2020 -0400.
Debugger log attached.
What's interesting, it says
> Pi shutting down.

just before crash. Why it's shutting down just after start?

[gdb.log](https://github.com/pioneerspacesim/pioneer/files/4437632/gdb.log)

**Comment by fluffyfreak** [comment]
hi @pirogronian this appears to be the same problem found in this [Mac OSX issue](https://github.com/pioneerspacesim/pioneer/issues/4850#issuecomment-609077850).

We'll try to get the code fixed up asap but in the meantime that fix should work for you as well.
