### ISSUE TITLE
GUI freeze then crash on entering system view.

### ISSUE THREAD

**Issue by pirogronian** [pioneerspacesim/pioneer#4857]
### Observed behaviour
On entering system view, gui freezes. However, mouse cursor is moving and sounds & music is still playing. Emerges two error boxes ("Pioneer meditation guru") with error messages:

> error: [string "[T] @pigui/modules/system-view-ui.lua"]:141: missing translation token: `ORBIT_PLANNER' in resource `core', language code `pl'.
> stack traceback:
>         [C]: in function '__index'
>         [string "[T] @pigui/modules/system-view-ui.lua"]:141: in function 'fun'
>         [string "[T] @pigui/pigui.lua"]:109: in function 'window'
>         [string "[T] @pigui/modules/system-view-ui.lua"]:139: in function 'fun'
>         [string "[T] @pigui/pigui.lua"]:158: in function 'withStyleColors'
>         [string "[T] @pigui/modules/system-view-ui.lua"]:138: in function 'showOrbitPlannerWindow'
>         [string "[T] @pigui/modules/system-view-ui.lua"]:506: in function 'fun'
>         [string "[T] @pigui/pigui.lua"]:147: in function 'withFont'
>         [string "[T] @pigui/modules/system-view-ui.lua"]:505: in function 'fun'
>         [string "[T] @pigui/views/game.lua"]:102: in function 'callModules'
>         [string "[T] @pigui/views/game.lua"]:280: in function 'fun'
>         [string "[T] @pigui/pigui.lua"]:109: in function 'window'
>         [string "[T] @pigui/views/game.lua"]:270: in function 'fun'

and

> string "[Terror: Frame instance deletion outside 'DeleteFrame' [0]

When closed, game crashes.

### Steps to reproduce
Run game, start at Mars and click on system view icon.

Gnu debbuger log attached.
[gdb.log](https://github.com/pioneerspacesim/pioneer/files/4469575/gdb.log)
Previous console output also.
[console.log](https://github.com/pioneerspacesim/pioneer/files/4469635/console.log)

Console log is earlier. For some reason, both logs are slightly different, at least at error messages.

**Comment by Web-eWorks** [comment]
@impaktor looks like transifex broke and isn't updating the other translations with the new strings from the SystemView rework... We'll need to make sure transifex is properly tracking and pushing to the repo.

**Comment by pirogronian** [comment]
I also think game shouldnt crash nor hang due to lack of translation to n ir something. Mayby suitable error message and continue.

**Comment by Gliese852** [comment]
@pirogronian the game would not crash, if transifex worked correctly. On the other hand, IIRC, all lines *must* be present in all language files. So we should not get around this error, IMHO.

**Comment by impaktor** [comment]
For unknown reason transifex had lost url to ~5-8 en.json source files. I just fixed it, we'll find out if it's fixed within 12 h.

**Comment by impaktor** [comment]
Translations are back, since apparently (I didn't know) we push the strings manually (from exraven's server) with a cron job which failed due to incompatible local python version, instead of using the (now) existing github-transifex integration app thingy (I started setting that up yesterday but since it now works again, I might break stuff).

Whatever, closing, this as it should now be fixed in master.
