### ISSUE TITLE
Sell price reduction kills commodity trading

### ISSUE THREAD

**Issue by Echoes91** [pioneerspacesim/pioneer#4858]
Maybe this could  be part of [Economy Rebalance](https://github.com/pioneerspacesim/pioneer/projects/2)

### Observed behaviour
Currently `sellPriceReduction = 0.8` is applied both to equipment and commodities, making most trade routes unprofitable. For example:

- Base/buy price of _Mining machines_ is 302 on Sirius (Minor export)
- Base/buy price of _Mining machines_ is 346 on Delta Eridani (Major Import)
- 1 ton bought for 302 on Sirius can be sold for 346 * 0,8 ~ 279 on Delta Eridani, resulting in a loss while trading from a minor export to a major import.

### Expected behaviour
I think any trade from minor export to minor import or better should never result in making a loss.

### Steps to reproduce
Buy any commodity and resell it in the same station to observe the price difference

### Possible fixes
- Reduce or remove `sellPriceReduction` for commodities at least (maybe decoupling from equipment). Seem like this was [done within old UI](https://github.com/pioneerspacesim/pioneer/pull/3161) but not carried over.
- Increase price deltas between import and export to increase profits (0,8 : 1 should be the minimum ratio)

__pioneer 20200410 (609273394) on Arch Linux__

**Comment by impaktor** [comment]
> I think any trade from minor export to minor import or better should never result in making a loss.

In general, this should be true, not sure about the "never" part, since "normal" price could be very different in different regions of space.

I agree that there should not be a price reduction when selling commodity. The reduced price is mainly for equipment as it's now second hand / used.
