### ISSUE TITLE
Formalhaut B exploded before 2005 (reality)

### ISSUE THREAD

**Issue by Cyborgscode** [pioneerspacesim/pioneer#4861]
Ok, this is not a bug you get all day:  the "planet" Formalhaut B  photographed in 2005 is gone today. 

As it looks, the planet exploded before 2000 and was just a expanding cloud of dust in 2005. It is not visible anymore. 

Reference: https://www.heise.de/newsticker/meldung/Exoplanet-verschwunden-Fomalhaut-b-war-wohl-gigantische-Truemmerwolke-4706278.html

**Comment by fluffyfreak** [comment]
Yeah I read about this today, that it might have been two large asteroids colliding

**Comment by nozmajner** [comment]
Nope, it wasn't me! Total innocent, I swear!

**Comment by Web-eWorks** [comment]
As a stop-gap measure, I've added a TODO in the relevant custom system definition. If/when we get the ability to add minable gas clouds or custom asteroid belts, we'll look at changing the body type of Fomalhaut.

Thanks for bringing this up, definitely appreciate it!
