### ISSUE TITLE
Game crushed after hyper jump

### ISSUE THREAD

**Issue by kostano** [pioneerspacesim/pioneer#4862]
### Observed behaviour

After hyper jump game crushed as soon as star shown.
Attached save file as zip.

### Steps to reproduce
[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/4515536/opengl.txt)
[output.txt](https://github.com/pioneerspacesim/pioneer/files/4515537/output.txt)
[5-save.zip](https://github.com/pioneerspacesim/pioneer/files/4515540/5-save.zip)

__My pioneer version (and OS):__

**Comment by impaktor** [comment]
#4857? I.e. you're playing with non-english language?

**Comment by kostano** [comment]
Not sure about language, in options it is English, tried jump to another place - crushed again as soon as star goes into view

**Comment by kostano** [comment]
Built from current master brunch for osx, works fine, no such issue
