### ISSUE TITLE
Docking bay covered by hill, cannot dock

### ISSUE THREAD

**Issue by kostano** [pioneerspacesim/pioneer#4863]
### Observed behaviour
Docking bay covered by hill, cannot dock

### Expected behaviour
Docking bay should be accessible

### Steps to reproduce
Fly to Rasmussen Pad, Daar [0,5,2]
Request clearance to dock,  docking bay 1 will be assigned
Try to dock :) 

__My pioneer version (and OS):__
osx 10.13.6, build from from current master branch

**Comment by nozmajner** [comment]
A possible workarount is to change the terrain detail a couple either of the extremes. That can unearth the pad in some cases.

**Comment by impaktor** [comment]
This is hardly the first time we've had this problem. I wonder if/how much work it would be to write methods for generating all systems in some radius and test that:
1. station is above terrain
2. ships can dock

**Comment by kostano** [comment]
Was able to dock on the edge of the platform.

Changed settings in data/stations. Not sure does it help.

pioneer-master/data/stations$ cat new_ground.json
{
   "model" : "new_ground",
   "type" : "surface",
   "parking_distance" : 5000,
   "parking_gap_size" : **6000**,
   "pad_offset" : **10**
}

**Comment by Web-eWorks** [comment]
Tracking in #5154.
