### ISSUE TITLE
Debug build assertion failed in Phien

### ISSUE THREAD

**Issue by kostano** [pioneerspacesim/pioneer#4869]
### Observed behaviour

Game exits after hyper jump to Phien.
See attached console output with failed assertion.

### Expected behaviour

Normal fly

### Steps to reproduce

Use Debug build
Go to Phien (-2, 6, 2)

__My pioneer version (and OS):__

[console_out.txt](https://github.com/pioneerspacesim/pioneer/files/4536609/console_out.txt)

OSX 10.13.6, Debug build from current master branch

**Comment by Gliese852** [comment]
@kostano It looks like you came out of hyperspace inside a star.

**Comment by Web-eWorks** [comment]
It does appear you came out inside of a star - we'll look into what's causing that particular error, and definitely fix it so the game doesn't crash when that happens!
