### ISSUE TITLE
Cities not generating properly 

### ISSUE THREAD

**Issue by ProgramRAM** [pioneerspacesim/pioneer#4886]
Observed behavior
Cities not being generated and or cities being generated but disappearing during following visits

 Expected behavior
Cities generate and persist 

 Steps to reproduce
Play the game for at least 30 minutes only going between cities then attempt to land at a city it should then not exist only the main docking area will

[Savefile.zip](https://github.com/pioneerspacesim/pioneer/files/4713096/Savefile.zip)
[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/4713101/opengl.txt)
![screenshot-20200601-153400](https://user-images.githubusercontent.com/51994377/83447165-fcc50a80-a41d-11ea-9a56-6c1b3551f245.png)

20200203 My pioneer version (and OS):Windows 10 Home 64 Bit

I went to several cities most notably earth being the strange one where sometimes I have massive cities and sometimes its just one building, also note my city detail has been unchanged since first start at very high. After the issue started happening however I did try to change it back and forth but it did nothing

**Comment by robintown** [comment]
I believe this is a duplicate of #4802. Try starting up Pioneer, selecting "Start on Mars", leaving the game, and then loading your save.

**Comment by ProgramRAM** [comment]
> I believe this is a duplicate of #4802. Try starting up Pioneer, selecting "Start on Mars", leaving the game, and then loading your save.

I can confirm that currently works as a workaround until a fix can be made.

**Comment by robintown** [comment]
Okay, then you should close this issue.

**Comment by ProgramRAM** [comment]
> Okay, then you should close this issue.

Should I? Its a workaround not really a fix the issue still exists I've just put a bandaid on it

**Comment by robintown** [comment]
Yes, since it appears to be a duplicate.

**Comment by ProgramRAM** [comment]
> Yes, since it appears to be a duplicate.

Okay then
