### ISSUE TITLE
fmt can't write to stderr/stdout on Windows

### ISSUE THREAD

**Issue by The-EG** [pioneerspacesim/pioneer#4888]
### Observed behaviour
Pioneer built on Windows (/subsystem:Windows) fails to run with an unhandled `fmt::v6::system_error` exception within `Log::Logger::WriteLog`. This appears to be due to the usage of `fmt::print(stderr` and `fmt::print(stdout` when `stderr`/`stdout` are not open/valid in a Windows application.

Building as a console application allows Pioneer to run, but with an additional console window.

### Expected behaviour
Pioneer should be able to run when built for Windows and output any output to output.txt.

### Steps to reproduce
Build Pioneer for x64 Windows
Run pioneer-x64.exe

__My pioneer version (and OS):__
Current master (https://github.com/pioneerspacesim/pioneer/commit/91d1caa8a647b512cbca23e58c975659efe0c6d9)
Windows 10 (x64)

**Comment by Web-eWorks** [comment]
Good catch, thank you! I'd definitely love to see a PR that resolves this issue, if you get the time!

**Comment by The-EG** [comment]
@Web-eWorks Sure. I just had to fix my hosed up branch first...I'm not sure how I had managed to do what I did, but it should be good now.
