### ISSUE TITLE
Commodity Market: buying goods adds to station stock (should subtract)

### ISSUE THREAD

**Issue by craigo-** [pioneerspacesim/pioneer#4896]
### Observed behaviour

When buying goods, the station stock goes **up** by the amount bought.

### Expected behaviour

Station stock should go **down** by the amount bought.

### Steps to reproduce

1. Start a new game on Mars
2. Go to the Commodities Market
3. Note the amount of an item available at the station (e.g. Carbon ore)
4. Buy 9 tons of the item. Watch both the "In stock" amount and the "Cargo" amount increase by 9 tons.
5. Sell 9 tons of the item. Watch the "In stock" amount increase by 9 tons and the "Cargo" amount decrease by 9 tons.
6. Enjoy infinite supply! 😄 

![output](https://user-images.githubusercontent.com/4467963/85531383-d2ecb580-b662-11ea-8cb5-4c95a28e39d6.gif)

__My pioneer version (and OS):__

Pioneer master 6ff573aa3 x64 (built 20200621)
Windows 10 Enterprise 1909 x64

NB: the issue does not happen with Pioneer 20200203.

**Comment by Web-eWorks** [comment]
Prrrresto! It's magic! We've solved resource scarcity, all we have to do is buy forever!

...On a more serious note, I'll look into it. It's probably just a flipped sign somewhere!

**Comment by joonicks** [comment]
data/pigui/libs/equipment-market.lua: line 112 is supposed to have a '-' in front of the "count"
yes adding a negative number...

**Comment by craigo-** [comment]
Thanks @joonicks, I've been looking for that for a while.

Shall I prepare a PR?

**Comment by joonicks** [comment]
yes please. I always mess up those things anyways.
