### ISSUE TITLE
Ship Info: model not updating when starting new game

### ISSUE THREAD

**Issue by craigo-** [pioneerspacesim/pioneer#4897]
### Observed behaviour

When starting a new game that happens to have the same model as the previous game, the Ship Information screen shows the old model, including its colour scheme, registration and any changes to its plane of rotation.

### Expected behaviour

A new game shows a new ship in the default plane of rotation.

### Steps to reproduce

1. Start a new game on Mars
2. Go to the Ship Information screen, drag the model to show its underside (the model's registration is correct)
![image](https://user-images.githubusercontent.com/4467963/85660340-a0e25e80-b709-11ea-8c52-f104cec09154.png)
3. End Game
4. Start a new game on Mars
5. Go to the Ship Information screen (the model's colour scheme, registration and plane of orientation is all preserved from the previous game)
![image](https://user-images.githubusercontent.com/4467963/85660369-a93a9980-b709-11ea-9564-31c7c03acac7.png)

__My pioneer version (and OS):__

_Pioneer:_
master 619ed1b3e x64 (built 20191216)
release 20200203
master 6ff573aa3 x64 (built 20200621)

_OS:_
Windows 10 Enterprise 1909 x64

NB: this issue does not happen in Pioneer release 20190203.

(See also #4895, possibly related.)

[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/4829254/opengl.txt)

**Comment by Web-eWorks** [comment]
It definitely wouldn't happen in 20190203 because that's before the new model spinner was written. :smile:

I'm pretty sure this is just an issue where the model in the spinner isn't being refreshed, which I should be able to adopt @vakhoir's `refresh()` paradigm to address. I'll look into it soon!
