### ISSUE TITLE
Donaldsonton station on Musk's Grave around Bea system (-8,6,-4) is partially buried under terrain

### ISSUE THREAD

**Issue by Another-MrZ** [pioneerspacesim/pioneer#4900]
### Observed behaviour
Donaldsonton station on Musk's Grave around Bea system (-8,6,-4) is partially buried under terrain, making it impossible for the autopilot to land on the required pad, as it is the one partially buried.
The ship lands on the soil and gets stuck, Landing is not acknowledged by the game.

### Expected behaviour
All landing pads should be clear for landing, especially the one selected by default for the landing. The station should be repositioned to avoid the issue.

### Steps to reproduce
1. Hyperjump to Bea A (-8,6,-4)
2. Select Musk's Grave as your destination on the autopilot
3. Once there Select Donaldsonton as landing station.
4. See the ship land on soil and get stuck.

__My pioneer version (and OS):__ 20200203 (Windows 7)

Note:  May be duplicate for bug 4863. Sorry, I just noticed after having entered it.

See Screenshots
![Screen3](https://user-images.githubusercontent.com/34732798/85932095-12184200-b8c1-11ea-951b-04e439f0a6d1.png)
![Screen4](https://user-images.githubusercontent.com/34732798/85932099-13e20580-b8c1-11ea-92d2-1531f87a0928.png)
![Screen5](https://user-images.githubusercontent.com/34732798/85932102-15abc900-b8c1-11ea-97a1-dd293351e065.png)

**Comment by ConfedMajor** [comment]
![Dia](https://user-images.githubusercontent.com/71795983/97009485-8636bf80-151a-11eb-8133-6288e82cf236.png)

https://drive.google.com/file/d/1QpWMzwsa1nlC218jON4BwjXuxa6B3g46/view?usp=sharing (save file game)

There is another replication of the glitch, but in another base, try to land in the base of the save file

**Comment by impaktor** [comment]
I don't know if this is something for @zesterer, if he's interested and have time. An example of a terrain-generation a bug that keeps plaguing us.

**Comment by Web-eWorks** [comment]
Tracking in #5154.
