### ISSUE TITLE
Game crashes when hyper jumping while having any ship screen open

### ISSUE THREAD

**Issue by Another-MrZ** [pioneerspacesim/pioneer#4901]
### Observed behaviour
Game crashes when hyper jumping while having any ship screen open

### Expected behaviour
Game should not crash

### Steps to reproduce
1. Select any destination on your hyper jump computer
2. Take off and activate hyper jump
3. Before hyper jump occurs open any ship info screen

__My pioneer version (and OS):__ 20200203 (Windows 7)
Error messages and PC specs included in Screenshots

![Error](https://user-images.githubusercontent.com/34732798/86208249-11eda000-bb68-11ea-833a-a5648e00e6f9.png)
![Error_2](https://user-images.githubusercontent.com/34732798/86208257-14e89080-bb68-11ea-9546-9911bef7bd6b.png)
![Specs](https://user-images.githubusercontent.com/34732798/86208265-19ad4480-bb68-11ea-9c02-4833ef9b5697.png)

**Comment by Gliese852** [comment]
Because it's better not to touch anything while you are in hyperspace, otherwise you will inadvertently cause a big bang, or something worse.

**Comment by craigo-** [comment]
I get the same:

- Ship Information: `in 'GetFrame': fld is valid but out of range (13)...`
- Sector Map: `in 'GetFrame': fld is valid but out of range (12)...`
- System Map: crash to desktop with no error message
- System Overview: `in 'GetFrame': fld is valid but out of range (13)...`

Pioneer master (2b0d15baf) x64, built 20200704
Windows 10 Enterprise 1909 x64
