### ISSUE TITLE
GUI: Renderer statistics not updated correctly

### ISSUE THREAD

**Issue by PtrMan** [pioneerspacesim/pioneer#4919]
### Observed behaviour
![image](https://user-images.githubusercontent.com/1067920/87863587-b50e2a00-c95c-11ea-8813-6e845b47240b.png)

### Expected behaviour
Correct numbers bigger than zero

### Steps to reproduce

__My pioneer version (and OS):__
20200718 Linux

**Comment by fluffyfreak** [comment]
This might not be tracking everything going through the renderer correctly

**Comment by Web-eWorks** [comment]
This is working as intended; at the moment, the only system that reports a triangle count is terrain rendering. You just happen to have no terrain rendering in the background (observe how it reports the only visible spacestation).
