### ISSUE TITLE
UI: unable to open the lua-console (german keyboard with english language in game)

### ISSUE THREAD

**Issue by PtrMan** [pioneerspacesim/pioneer#4920]
I tried to open the console by hitting the ´` key with and without (right) shift, this didn't open the console.
I also tried it with the key +*~ pressing Alt-Gr and (right) shift, same result.

I am currently unable to understand the C++ code which is doing the keybinding to modify it myself :( .

__My pioneer version (and OS):__
20200718 linux

**Comment by PtrMan** [comment]
Ah I found the line in KeyBindings.inc.h .

**Comment by PtrMan** [comment]
Hm it doesn't seem to work when I change the binding to:

KEY_BINDING(toggleLuaConsole, "BindToggleLuaConsole", Lang::TOGGLE_LUA_CONSOLE, SDLK_CARET, 0)

**Comment by PtrMan** [comment]
These bindings also don't show up in the keybinding GUI, seems to be bugged to me in many ways.

**Comment by impaktor** [comment]
#4782

**Comment by Web-eWorks** [comment]
You'll need to change the key binding in your `~/.pioneer/options.ini` file. That line only sets the default key binding, and once you've run the game once the config file isn't overridden by C++ changes.

Definitely read the above post as well as searching for my Input PRs (you can search by author:Web-eWorks) to get the full situation on the Input subsystem - the work outlined in the above link is ~85% done, but I've stalled out and won't have time to finish it for a few weeks.

**Comment by impaktor** [comment]
This is known, tracked elsewhere, many keys are not exposed in the current settings GUI
