### ISSUE TITLE
GUI: lua console input is not cleared when function couldn't get executed

### ISSUE THREAD

**Issue by PtrMan** [pioneerspacesim/pioneer#4921]
### Observed behaviour
The input GUI field is not cleared after entering a invalid LUA function, for example exit() .

### Expected behaviour
Input GUI field should get cleared.

### Steps to reproduce
Open LUA console and enter exit()   (with pressing enter)

__My pioneer version (and OS):__
git master 20200718 linux

**Comment by The-EG** [comment]
Looking at how the code was structured for that, I think this is a matter of preference. Invalid input isn't added to the history  either (up and down keys), unlike <pick your favorite terminal emulator>.
If it were to clear the entry on invalid input, it would also need to add that input to the history. I know the few times I've used the Lua console in game and had a typo in a long command I'd rather just edit it in place than retype it all.

6 one, half dozen the other. I don't really think this is a bug.
