### ISSUE TITLE
suggestion: Vehicle as component based design container

### ISSUE THREAD

**Issue by PtrMan** [pioneerspacesim/pioneer#4922]
There are a lot of classes in the codebase which have basically the same properties such as
* being a physical object
* having a mesh to render with the renderer
* having some kind of AI/control
* having attachments such as weapons, jump drive etc.
* having docking bays (?)

Examples
* the class Ship has attachments such as a jump drive and weapons, scanner etc, they currently don't have docking bays
* the class Missile can basically just get controlled and has a explosive payload
Same is true for other classes which do basically the same thing.
* a station has docking bays

All of this can be represented with instances of a Vehicle class with different components.

I am aware that a lot of old code relies on these explicit classes like Ship, Missile etc. A way may be to handle lua classes for Ship etc with a facade.

Its just a suggestion based on my attempts to write space sim's in a modular and extensible way.

This may allow all sorts of variations which make sense, like ships with docking bays for drones(where a drone itself is a Vehicle which can spawn Missiles which are vehicles). Another variation may be "Carrier" ships which can dock smaller ships.

**Comment by impaktor** [comment]
This is not a bug, and it clutters up our bug tracker, please use the dev-forum for this kind of discussion.

**Comment by Gliese852** [comment]
@PtrMan AFAIK, work is underway to implement ECS here, but this is a lot of work.

**Comment by impaktor** [comment]
@PtrMan if you want to work on ECS, please coordinate with @Web-eWorks (aka. _sturnclaw_ on IRC)

**Comment by Web-eWorks** [comment]
I will be unavailable to check IRC messages for the next week due to scheduling constraints, but I'd definitely like to discuss possible ECS implementations when I'm at the work rig again!
