### ISSUE TITLE
Missile: yield is hardcoded

### ISSUE THREAD

**Issue by PtrMan** [pioneerspacesim/pioneer#4923]
Missile.cpp hardcodes the yield of the missile.
>	const double damageRadius = 200.0;
>	const double kgDamage = 10000.0;

The constructor has a power parameter (which is stored in m_power), but it is just used for ECM jamming. I would expect that there are different parameters for the yield, jamming, etc. The radius can get computed with a simple formula by the yield, this is realistic in most environment (space and in atmosphere combat), the radius should actually depend on the density of the atmosphere, type of explosion and yield.

__My pioneer version (and OS):__
20200718

**Comment by Web-eWorks** [comment]
Thank you for the contribution! Additional terms for atmospheric density et. al. are at your discretion to open a new pull request - at this time, missile damage is "close enough" that I'm satisfied with where it's at.
