### ISSUE TITLE
Star System names are not unique

### ISSUE THREAD

**Issue by PtrMan** [pioneerspacesim/pioneer#4926]
### Observed behaviour
Names of star systems are not unique.
![image](https://user-images.githubusercontent.com/1067920/87897714-7ce61480-ca4c-11ea-8660-b78040f683fc.png)

### Expected behaviour
Unique names of star systems in the system view

### Steps to reproduce

__My pioneer version (and OS):__
git 20200718 linux

**Comment by Gliese852** [comment]
@impaktor will like it.

**Comment by PtrMan** [comment]
heh found the other issue #4866 , it's funny that the screenshots look similar...

**Comment by impaktor** [comment]
Please see my comments in the other issue, and please check issue tracker for existing bugs, and please close when you discover duplicates.
