### ISSUE TITLE
Camera: outside camera can clip into planets

### ISSUE THREAD

**Issue by PtrMan** [pioneerspacesim/pioneer#4929]
### Observed behaviour
![image](https://user-images.githubusercontent.com/1067920/87909007-b7a97600-ca67-11ea-8a5a-f96bc292b9a1.png)

### Expected behaviour
the Camera shouldn't clip into the environment. Doing a raycast to determine the camera position should do the trick.

### Steps to reproduce
* start new game on mars
* bump time acceleration to 1000x or something high
* press F1 multiple times to get outside camera
* rotate camera so it clips into the planet

__My pioneer version (and OS):__
git 20200718 linux

**Comment by Web-eWorks** [comment]
This is the sidereal camera which intentionally doesn't have the same constraints as the regular external camera view. This issue can be reproduced at all timesteps. It's currently tracked in #4818, but thank you for the report!
