### ISSUE TITLE
github: project needs topics

### ISSUE THREAD

**Issue by PtrMan** [pioneerspacesim/pioneer#4934]
Please add github topics to make it easier to find the game.
Some on top of my head: game, space, simulation, simulator, exploration? etc.

**Comment by impaktor** [comment]
We obviously already use `git tag`, but if you're talking about something else, could you please provide a link.

**Comment by PtrMan** [comment]
I meant topics https://docs.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics

**Comment by impaktor** [comment]
done
