### ISSUE TITLE
Game crashes when hyperspacing from Sol to Proxima Centauri

### ISSUE THREAD

**Issue by CampNowhere** [pioneerspacesim/pioneer#4949]
### Observed behaviour

Leave Torvald's Station, and hyperspace toward Proxima Centauri. See crash log.

```
Fatal: [string "[T] @modules/TradeShips.lua"]:221: Object is no longer valid
stack traceback:
	[C]: in function 'DistanceTo'
	[string "[T] @modules/TradeShips.lua"]:221: in function 'getNearestStarport'
	[string "[T] @modules/TradeShips.lua"]:587: in function 'cb'
	[string "[T] @libs/Event.lua"]:34: in function '?'
	[string "[T] @libs/Event.lua"]:185: in function <[string "[T] @libs/Event.lua"]:180>Fatal: Frame instance deletion outside 'DeleteFrame' [0]

```

### Expected behaviour

Game doesn't crash.

### Steps to reproduce

See "observed behavior. Will attempt to reproduce with other systems and document here.

__My pioneer version (and OS):__

On head ddcdaaf0cb490d75f75903eece141e18647086db, using 64 bit Debian Linux.

**Comment by Web-eWorks** [comment]
Hmm, I'm not able to reproduce this myself... If you can, I'd appreciate a savefile that you can consistently reproduce the crash on, it'd make it a lot easier to debug!
