### ISSUE TITLE
External view button has incorrect icon and name when in other views

### ISSUE THREAD

**Issue by zesterer** [pioneerspacesim/pioneer#4954]
### Observed behaviour

The external view button switches from a camera to an eye and its tooltip text changes to 'World View' (which is already the name of one of the other views)

### Expected behaviour

Consistent icon and name

__My pioneer version (and OS):__ `master`

**Comment by Web-eWorks** [comment]
Hmm, this one's a bit interesting. The WorldView button is aliased to changing the view mode when in the WorldView, but when you're looking at the StationView for example, clicking it returns you to the WorldView. I could definitely see making sure the icon stays consistent, but I'm not 100% certain whether the tooltip is particularly a bug.

I'll let some others chime in on this one.
