### ISSUE TITLE
Current official PSS version (20200203) for 32-bit Linux (and Windows) systems

### ISSUE THREAD

**Issue by gerrygk** [pioneerspacesim/pioneer#4962]
Hey all,

lately I was looking for a current official PSS version (20200203) for Linux x86 / 32-bit systems. The only one I found was an older version from 2019 on Flathub (not interesting for me).

It seems to me that the newest official PSS versions for all 32-bit OS's are no more being offered at the Pioneer website for some time now. This could exclude a whole bunch of users from trying and evaluating the newest development results (at least for the Linux community), what would be a real pity.

Maybe it's just a matter of effort, but I would appreciate this versions to be back in the download list again.

What's your opinion on that?

**Comment by impaktor** [comment]
If you're running a very old computer, chances are it won'd support our OpenGL 3.1

**Comment by The-EG** [comment]
Also #4788 .

I think the issue being raised here is that 32bit builds aren't deployed when a new release is built. I suspect that they aren't built as a part of the appveyor/travis process. Compiling 32bit should definitely be working now, with the exception of Windows when using the cmake system (the VS2019 solution does work), but do we want to also provide pre-built 32bit binaries?

p.s. Fluffyfreak, you can now say I told you so!

**Comment by impaktor** [comment]
If anyone can make 32 bit build work, and artifact be made, and ideally, uploaded/linked somewhere, I don't think anyone will object.

**Comment by gerrygk** [comment]
As the source code for v2020-02-03 is still available here, I could give it a try. (I once succeeded when building a Linux 64-bit specimen after February 2020.) I remember having seen a (hopefully up-to-date) list of programs, libraries etc. necessary therefor, but couldn't remember where.

**Comment by impaktor** [comment]
@gerrygk compiling for 32 bit computer from current master should be possible, if not paste error.

**Comment by gerrygk** [comment]
Today I tried the compilation. Unfortunately, it stopped with the following error message:

**********************************************

In file included from /home/gerry/Builds/pioneer-20200203/src/CollMesh.cpp:6:0:
/home/gerry/Builds/pioneer-20200203/src/scenegraph/Serializer.h:29:2: error: static assertion failed: Vector2d is padded differently on this platform and will not serialize properly.
  static_assert((sizeof(vector2d) == 16 && alignof(vector2d) == 8), "Vector2d is padded differently on this platform and will not serialize properly.");
  ^~~~~~~~~~~~~
/home/gerry/Builds/pioneer-20200203/src/scenegraph/Serializer.h:31:2: error: static assertion failed: Vector3d is padded differently on this platform and will not serialize properly.
  static_assert((sizeof(vector3d) == 24 && alignof(vector3d) == 8), "Vector3d is padded differently on this platform and will not serialize properly.");
  ^~~~~~~~~~~~~
/home/gerry/Builds/pioneer-20200203/src/scenegraph/Serializer.h:33:2: error: static assertion failed: Aabb is padded differently on this platform and will not serialize properly.
  static_assert((sizeof(Aabb) == 56 && alignof(Aabb) == 8), "Aabb is padded differently on this platform and will not serialize properly.");
  ^~~~~~~~~~~~~
CMakeFiles/pioneerLib.dir/build.make:278: recipe for target 'CMakeFiles/pioneerLib.dir/src/CollMesh.cpp.o' failed
make[2]: *** [CMakeFiles/pioneerLib.dir/src/CollMesh.cpp.o] Error 1
make[2]: Verzeichnis „/home/gerry/Builds/pioneer-20200203/build“ wird verlassen
CMakeFiles/Makefile2:111: recipe for target 'CMakeFiles/pioneerLib.dir/all' failed
make[1]: *** [CMakeFiles/pioneerLib.dir/all] Error 2
make[1]: *** Auf noch nicht beendete Prozesse wird gewartet …
[ 12%] Linking CXX static library libimgui.a
make[2]: Verzeichnis „/home/gerry/Builds/pioneer-20200203/build“ wird verlassen
[ 12%] Built target imgui
make[1]: Verzeichnis „/home/gerry/Builds/pioneer-20200203/build“ wird verlassen
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
make: Verzeichnis „/home/gerry/Builds/pioneer-20200203/build“ wird verlassen

**********************************************
Additional information:

Hardware:
Mainboard: MSI K9N Neo v2 (MS-7369)
CPU: AMD Athlon 64 X2 Dual Core 6000+
MB memory: 8 Gb
Graphics: Sapphire (AMD) Radeon HD 5450

OS:
ZorinOS 15.2 (x86)

**Comment by gerrygk** [comment]
I think OpenGL 3.1 compatibility is not a problem as PSS v20190203 (x86) is running on this system without any issues.

**Comment by Web-eWorks** [comment]
@gerrygk I'd recommend either changing the comparisons of those asserts to less-equal (`<=`) or building the latest `master` commit; that compilation issue has been fixed for a little while and while we're closing in on a new release we're not quite there.

**Comment by gerrygk** [comment]
I'll try the up-to-date binaries briefly. Thanks for the hint.

**Comment by impaktor** [comment]
I assume you mean you'll try the up-to-date source, to build your binary...

**Comment by gerrygk** [comment]
Sorry yes, surely the source.

**Comment by gerrygk** [comment]
A few days ago, I could successfully build the 32-bit version with the youngest source code. It works fine as far as I can say.

**Comment by impaktor** [comment]
Nice, glad it worked. I take it this is resolved then.
