### ISSUE TITLE
2D radar does not work anymore

### ISSUE THREAD

**Issue by robothauler** [pioneerspacesim/pioneer#4965]
### Observed behaviour
Game stops with error message if player switches to 2D radar.

Fatal: [string "[T] @pigui/modules/radar.lua"]:63: attempt to perform arithmetic on local 'l' (a nil value)
stack traceback:
        [string "[T] @pigui/modules/radar.lua"]:63: in function 'display2DRadar'
        [string "[T] @pigui/modules/radar.lua"]:142: in function 'fun'
        [string "[T] @pigui/views/game.lua"]:107: in function 'callModules'
        [string "[T] @pigui/views/game.lua"]:286: in function 'fun'
        [string "[T] @pigui/libs/wrappers.lua"]:138: in function 'window'
        [string "[T] @pigui/views/game.lua"]:276: in function 'fun'
        [string "[T] @pigui/libs/wrappers.lua"]:534: in function 'withStyleColors'
        [string "[T] @pigui/views/game.lua"]:275: in function <[string "[T] @pigui/views/game.lua"]:267>Fatal: Frame instance deletion outside 'DeleteFrame' [0]

### Expected behaviour
No game crash

### Steps to reproduce
Start a new game
Right click on the radar
Select 2D radar

__My pioneer version (and OS):__
current master (GNU/Linux)

**Comment by The-EG** [comment]
Oops, that's mine. Easy fix.
