### ISSUE TITLE
Segfault if you load a savegame and change the camera mode

### ISSUE THREAD

**Issue by Gliese852** [pioneerspacesim/pioneer#4968]
### Observed behaviour
If you load a game, it starts in pause mode. If, without clicking on play, change the camera mode, a segfault occurs:
```
Thread 1 "pioneer" received signal SIGSEGV, Segmentation fault.
0x00005555556825c0 in CollisionSpace::TraceRay (this=this@entry=0x555569d3aa28, start=..., dir=..., len=200, c=c@entry=0x7fffffffd4e0, ignore=0x555568707400) at .../src/collider/CollisionSpace.cpp:315
315		BvhNode *node = m_staticObjectTree->m_root;
```
If you press play before changing the camera mode, the segfault __does not occur__.

__My pioneer version (and OS):__
master at d5e69790ce957a5aa69cceb2e86bd57e5f1af9ac (Ubuntu 18.04.4 LTS)

**Comment by Gliese852** [comment]
introduced in cb3cdcf4917ca08509d95806ee201f5bf37b83fe

**Comment by Web-eWorks** [comment]
Hrmh, looks like CollisionSpace is dependent on ticking the world to build itself when loading a saved game. That's a bug! I suspect this might take a bit more than a trivial amount of work, but good catch @Gliese852!
