### ISSUE TITLE
Opening the console detaches camera from ship

### ISSUE THREAD

**Issue by nozmajner** [pioneerspacesim/pioneer#4981]
### Observed behaviour
If you open the console while docked on an orbital, the camera stops spinning with the station/detaches from the ship, and jumps back to the ship when the console is closed:
![station_spin](https://user-images.githubusercontent.com/4182678/97000030-7200bb80-1536-11eb-879a-8c1292b7d5e0.gif)
And as @WKFO pointed out, this happens also when you are flying:
![console-whoosh](https://user-images.githubusercontent.com/4182678/97004600-91e7ad80-153d-11eb-8c9f-54be425c640d.gif)
The same happens when you are in internal view (wait for it, it takes a quarter of a rotation):
![console-whooskaboom](https://user-images.githubusercontent.com/4182678/97006367-0d4a5e80-1540-11eb-9157-421f21e77f2d.gif)

Might also happen with the other UI screens, just not visible? Transparency did not work on the newUI widget.png, so I was unable to test. Can I set transparency for the pigui screens?
Might be related to #2735 I guess.

### Expected behaviour
Camera stays with the ship when any UI is open.

### Steps to reproduce
- Start at the Barnard's start, or dock to any orbital. Open the console. Get dizzy.
- Fly slowly, go to external view, open the console. Whoooosh
- Fly towards/away from an orbital, at say 300m/s. Open the console, wait a bit then close. The station will jump closer/further.

###My pioneer version (and OS):###
Happens on the 2020-02-03 Release and on master as well (at 2020-10-23)
Win10

**Comment by WKFO** [comment]
Opening up console detaches the camera from the ship and locks it relative to frame, not only when docked with stations. If you are in external view, have non 0 velocity relative to frame and open the console, you can see your ship zipping away.

**Comment by fluffyfreak** [comment]
Ooh, that is new and exciting!
