### ISSUE TITLE
Combat.lua expects ships to have default hyperdrive class > 1 (ship rebalance)

### ISSUE THREAD

**Issue by WKFO** [pioneerspacesim/pioneer#4983]
### Observed behaviour
I finished a recon mission and just when I exit hyperspace to the payment system, game crashes. Consistent. I have a save file below. (For clarification, you can jump to other systems just fine. It is the payment system that is problematic.)

![aaa](https://user-images.githubusercontent.com/29180904/97108059-f3458300-16db-11eb-9e0a-cd180785607d.PNG)

### Expected behaviour
No crash.

### Steps to reproduce
https://www.dropbox.com/s/sh728r3i83ow5ac/Bugreport?dl=0
Load the save file and click hyperspace.

__My pioneer version (and OS):__
42b67ec4278638d892561ed75885804b53f16698 + Nozmajner's latest ship rebalance (Windows 10 x64)

**Comment by The-EG** [comment]
Just a quick glance at the lua: it looks like it's trying to spawn a ship of one of the types: 'medium_fighter', 'medium_courier', 'light_freighter' and also has a hyperdrive class > 1. The number of ships that meet that criteria is now 0 for some reason, so it doesn't like generating a random number between 1 and 0.

**Comment by nozmajner** [comment]
Hmm, so the default hyperdrives are too low in the rebalance for some ships? Why the mission wants ships that have larger than class 1 hyperdrives?

**Comment by robothauler** [comment]
> Why the mission wants ships that have larger than class 1 hyperdrives?

The intention was to choose only the faster ships. But I think this doesn't matter and can be changed to the usually hyperdrive class > 0.

**Comment by impaktor** [comment]
@robothauler do you have time to look into this, so it's robust to this re-balance?
