### ISSUE TITLE
Skybox star density behaves oddly

### ISSUE THREAD

**Issue by WKFO** [pioneerspacesim/pioneer#4990]
### Observed behaviour
![screenshot-20201031-152401](https://user-images.githubusercontent.com/29180904/97779213-b111bb00-1b8d-11eb-8e1e-9a4fc04d6e5b.png)
Above is Sag A* (-3125, 0, 0) with star density at 50 percent.
![screenshot-20201031-152547](https://user-images.githubusercontent.com/29180904/97779216-b3741500-1b8d-11eb-95cb-97fe1eab88c6.png)
Above is Sol (0, 0, 0) with star density at 0 percent.

Some part of the sky gets "cut off" (as if someone sliced the galaxy into two using a cosmic knife and took a part of it away). This happens when you get close to the galactic center or change the star density.

### Expected behaviour
Spread stars somewhat homogeneously after density change.

### Steps to reproduce
Play with star density slider.

__My pioneer version (and OS):__
8b698e1cf5f95d35d0fa4b9f17e8c348fff170e3 (Win 10 x64)

**Comment by impaktor** [comment]
:metal:

**Comment by impaktor** [comment]
I've experienced this, on the release candidate 1, recently, so it's still in master, as of now

**Comment by The-EG** [comment]
I think it was mentioned at some point that this seems to happen in certain systems even with the default settings. Has anyone confirmed that?

**Comment by impaktor** [comment]
I've definitely experience this at fresh game start in Barnard's system, every time, I think. My config is pretty much default

## "the darkness has swallowed the sky" (Barnard's)
![2021-01-03-211134_1600x900_scrot](https://user-images.githubusercontent.com/619390/103487810-59e7cb00-4e08-11eb-8d2e-7ea66870c286.png)

## config
```
AMD_MESA_HACKS=0
AmountOfBackgroundStars=0.1
AntiAliasingMode=2
BindBottomCamera=Key1073741915
BindCameraRollLeft=Key1073741913
BindCameraRollRight=Key1073741915
BindCameraRotateDown=Key1073741914,Key1073741905
BindCameraRotateLeft=Key1073741916,Key1073741904
BindCameraRotateRight=Key1073741918,Key1073741903
BindCameraRotateUp=Key1073741920,Key1073741906
BindDecreaseScanRange=Key56Mod768
BindFrontCamera=Key1073741920,Key1073741906
BindIncreaseScanRange=Key57Mod768
BindLeftCamera=Key1073741916,Key1073741904
BindMapLockHyperspaceTarget=Key32
BindMapStartSearch=Key47,Key1073741908
BindMapToggleInfoPanel=Key9
BindMapToggleSelectionFollowView=Key13,Key1073741912
BindMapViewReset=Key116
BindMapViewRotateDown=Key1073741906,Key105
BindMapViewRotateLeft=Key1073741903,Key108
BindMapViewRotateRight=Key1073741904,Key106
BindMapViewRotateUp=Key1073741905,Key107
BindMapViewShiftBackward=Key102
BindMapViewShiftDown=Key115
BindMapViewShiftForward=Key114
BindMapViewShiftLeft=Key97
BindMapViewShiftRight=Key100
BindMapViewShiftUp=Key119
BindMapWarpToCurrent=Key99
BindMapWarpToHyperspaceTarget=Key104
BindMapWarpToSelection=Key103
BindRearCamera=Key1073741914,Key1073741905
BindResetCamera=Key1073741898
BindRightCamera=Key1073741918,Key1073741903
BindToggleLuaConsole=InputAction(KeyChord(Key48))
BindToggleScanMode=Key48Mod768
BindTopCamera=Key1073741921
BindViewZoomIn=Key1073741911,Key61
BindViewZoomOut=Key1073741910,Key45
CompactRadar=1
ConfirmQuit=0
DefaultLowThrustPower=0.25
DetailCities=1
DetailPlanets=1
DisableSound=0
DisplayNavTunnel=1
EnableCockpit=0
EnableGLDebug=0
EnableGPUJobs=1
EnableJoystick=1
EnableServerAgent=0
FOVVertical=65
GL3ForwardCompatible=1
HudTrails=1
InvertMouseY=0
JoystickDeadzone=0.2
Lang=en
MasterMuted=0
MasterVolume=0.8
MaxPhysicsCyclesPerRender=4
MusicMuted=1
MusicVolume=0.8
RecordVideo=1
RedirectStdio=0
RendererName=Opengl 3.x
ScrHeight=900
ScrWidth=1600
SectorViewXRotation=-10.0
SectorViewZRotation=0
SectorViewZoom=2.0
SfxMuted=0
SfxVolume=0.8
SpeedLines=0
StartFullscreen=0
UIScaleFactor=1
UseAnisotropicFiltering=0
UseTextureCompression=1
VSync=1
WorkerThreads=0
```

**Comment by fluffyfreak** [comment]
Ah, I know what's causing this :D I wrote it quite naively. 
Once it hits the star count limit, it just ... stops. Unfortunately it fills out the stars starting with the real star systems based on a cube centred on the players current star system. This starts in one corner and then works it's way along through all the sectors, and erm... cuts off part way through that.
