### ISSUE TITLE
GL_ARB_clip_control is not supported on GeForce 8600M

### ISSUE THREAD

**Issue by pirogronian** [pioneerspacesim/pioneer#4992]
[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/5471559/opengl.txt)
[output.txt](https://github.com/pioneerspacesim/pioneer/files/5471563/output.txt)
opengl.txt is from July. I dont know how to obtain more recent version. Mayby pioneer was unable to create one now, before the error occured.

If I can remember, last working version was git master from around august. Or from july, if opengl.txt modification date is a proper marker for it.

### Observed behaviour
Loading stops and error message window appears: 
"Fatal: OpenGL extension GL_ARB_clip_control is not supported by your graphics card or graphics driver version.
Please check to see if your GPU driver vendor has an updated driver - or that drivers are installed correctly."

After accepting, game quits.

### Expected behaviour
Should work, as I have opengl 3.1 (supposed to be) still supported and I have set in my config.ini:
`RendererName=Opengl 3.1`

### Steps to reproduce
Compile & run as with instructions.

__My pioneer version (and OS):__
Git master version, cloned today.
OS: Arch Linux, updated today (except kernel).

**Comment by Web-eWorks** [comment]
We've increased our minimum system requirements recently, less than a month ago in fact. This hasn't hit a release build yet for exactly the issues you've found, but I think there's a work-around that should let you play the game again - I'll let you know once that's merged into master and available for testing.

Fair warning, your graphics card is right at the very bottom edge (possibly outside) of our targeted system requirements; we're planning on upgrading some other parts of the game's rendering system over the next six months to a year which might not be compatible with your hardware. The 8600M GT is now thirteen years old, and while I definitely understand the value in sticking with a laptop that you like, our contributors are cooking up some improvements to the game's content that requires us to bump up the graphical requirements as well. :smile:

**Comment by pirogronian** [comment]
Thank You. I just have no money for new hardware yet still hope to enjoy new Pioneer features...

**Comment by Web-eWorks** [comment]
I totally understand that; we do try to support as many different hardware configurations as possible, but unfortunately some older hardware just wasn't designed to be capable of what is now considered "standard" rendering techniques.

Until I merge in the workaround, commit 6f2116da6d6a0ce062bad11706fee0fca5daeac9 should compile and run fine for you - it's from just before the new extension was introduced.

**Comment by pirogronian** [comment]
I hoped my card at least fulfils declared 3.1 opengl standard. But it seems not always valid, as I can see. So, any effor to support my ancient and problematic hardware is much and even more appreciated.

I recompiled Pioneer with respect to 6f2116d commit but issue remains. Maybe I should clear build cache. Here are recompiled files (based on cmake output):

> [  2%] Building CXX object CMakeFiles/savegamedump.dir/src/posix/FileSystemPosix.cpp.o
> [  2%] Building CXX object CMakeFiles/savegamedump.dir/src/posix/OSPosix.cpp.o
> [  5%] Building CXX object CMakeFiles/pioneer-lib.dir/src/Game.cpp.o
> [  5%] Building CXX object CMakeFiles/pioneer-lib.dir/src/ObjectViewerView.cpp.o
> [  5%] Building CXX object CMakeFiles/pioneer-lib.dir/src/Pi.cpp.o
> [  6%] Building CXX object CMakeFiles/pioneer-lib.dir/src/collider/BVHTree.cpp.o
> [  6%] Building CXX object CMakeFiles/pioneer-lib.dir/src/posix/FileSystemPosix.cpp.o
> [  7%] Building CXX object CMakeFiles/pioneer-lib.dir/src/posix/OSPosix.cpp.o
> [ 77%] Building CXX object src/lua/CMakeFiles/pioneer-lua.dir/LuaConsole.cpp.o
> [ 77%] Building CXX object src/lua/CMakeFiles/pioneer-lua.dir/LuaEngine.cpp.o
> [ 98%] Building CXX object CMakeFiles/modelcompiler.dir/src/modelcompiler.cpp.o
> [ 99%] Building CXX object CMakeFiles/pioneer.dir/src/main.cpp.o

**Comment by Web-eWorks** [comment]
> I hoped my card at least fulfils declared 3.1 opengl standard. But it seems not always valid, as I can see. So, any effor to support my ancient and problematic hardware is much and even more appreciated.

GL_ARB_clip_control is actually not part of the 3.1 standard at all, it's merely a (mostly) widely supported extension that was written around the time of OpenGL 4.2. I have no doubts your card supports OpenGL 3.1; the problem at hand is that OpenGL 3.1 itself doesn't support everything we need, so we need a few extra extensions in addition to the core OpenGL version.

> I recompiled Pioneer with respect to 6f2116d commit (done git reset 6f2116d) but issue remains. Maybe I should clear build cache. Here are recompiled files (based on cmake output):

I'd recommend `git checkout 6f2116d` instead - `git reset` doesn't always do what you'd want. You should see `RendererGL.cpp.o` in the list of recompiled files.

**Comment by Web-eWorks** [comment]
@pirogronian please test the latest `master` branch - it should be compatible with your graphics card! If you run into further issues please re-open this issue.

**Comment by pirogronian** [comment]
Works perfectly, thank You!
Moreover, I noticed dramatic performance increase. Up to now there was dramatic FPS drop if any, even tiny, part of planet or city was inside a vieport. It was virtually from very beginning my use of Pioneer and I was sure it is due to my old hardware. But apparently, You men did a miracle... :smile:

**Comment by Web-eWorks** [comment]
I was certainly expecting a performance increase but not to that level, there must be a lot more overdraw in our scenes than I thought. Good to hear that it's working even better for you now!
