### ISSUE TITLE
Ship Pattern Color "Customization" Glitch 🤭

### ISSUE THREAD

**Issue by ConfedMajor** [pioneerspacesim/pioneer#5001]
### Observed behaviour
When clicking ships randomly (in the ship market), their color patterns changes
To be specific: https://streamable.com/pv432w

### Expected behaviour

Perhaps ship patterns from markets should not change their color... 🤔

### Steps to reproduce

Go to a planet that sells lots of ships, then click them (in the ship market list) semi-randomly and see how its color patterns change

__My pioneer version (and OS):__

Pioneer Version: Lastest version (downloaded from the pioneer website)

PC Specs:

![Pc_Specs](https://user-images.githubusercontent.com/71795983/98456968-5f56cb00-2161-11eb-9dfa-1ac95fbc0fd0.png)

**Comment by Web-eWorks** [comment]
That was actually fixed in a commit to master just yesterday, but thank you for reporting!
