### ISSUE TITLE
Lang doesn't properly fall back to English translation

### ISSUE THREAD

**Issue by pirogronian** [pioneerspacesim/pioneer#5007]
Just tested master version, commit 9d157761aacfafa9d997260b07955e21d7905726, wondering, if recent substancial changes in language files handling would lead to problems... I wasn't surprised :smile: 

### Observed behaviour
Pioneer stops with error message:

> couldn't read language file 'lang/module-stationtrafficcontrol/pl.json'
> Fatal: Translation of 'module-stationtrafficcontrol' into language 'pl' not found! This should be in 'data/lang/module-stationtrafficcontrol/pl.json'.
> stack traceback:
>         [C]: in ?
>         [C]: in function 'GetResource'
>         [string "[T] @modules/StationTrafficControl/StationTra..."]:13: in main chunk
> 

Wasn't tested with default language (English). In fact, I'm not sure, how to temporarily change language settings on my Linux session, but I hope it's not essential to fix this problem...

**Comment by impaktor** [comment]
`Lang=en` in your config file

the pl.json file should be there within 24h

**Comment by pirogronian** [comment]
> `Lang=en` in your config file

Thank You! I must be completely mixed up toy forgot that Pioneer keeps it in its own config file...

> (feel free to help translate, btw)

Good advice. Indeed, some time have passed since I updated translation last time. Let's check if I still remeber my password to Transifex... :smile:

**Comment by Web-eWorks** [comment]
@pirogronian thank you for reporting this, you've saved me the effort of making an issue to track Lang issues when translations aren't available! I'll look into adding automatic fallback to the `en` resource in the event that a translation language isn't available so this doesn't happen again.

**Comment by impaktor** [comment]
btw, the polish file is there now (along with all other languages)
