### ISSUE TITLE
Search system doth not work

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#5019]
# Observed behaviour
searching a system in sector view, and selecting one in the "narrow to search" list, returns "Not Found".

### Steps to reproduce
E.g. try to search system "NN 3379"

__My pioneer version (and OS):__
current master, 5443bb927e55b33d2a80ddbb24dcb85a38f548e2

**Comment by Web-eWorks** [comment]
Fixed in an upcoming PR, with a few other improvements!
