### ISSUE TITLE
Buying and selling ship equipment does not require confirmation

### ISSUE THREAD

**Issue by The-EG** [pioneerspacesim/pioneer#5020]
This has popped up in IRC a few times, but I don't think we have an issue to track it, and prod one of us into fixing it.

### Observed behaviour
Buying or selling ship equipment does not require a confirmation and can be done with a single click. This isn't intuitive, and usually results in the player inadvertently buying/selling equipment.

### Expected behaviour
Buying or selling ship equipment should require a confirmation or function similarly to the commodities screen.

### Steps to reproduce
Open the ship equipment screen in a station. Click on a piece of equipment from either the left or right screens.

__My pioneer version (and OS):__
Current master 
Windows 10

**Comment by tropicalpioneer** [comment]
If I might add, as feature request...
If the ship component is an upgrade/downgrade of a current system, instead of "ship fully laden" dialog box, it would be nice to have a confirmation/dialog window that shows a comparison of the current item and performances (damage points for weapons, speed or distance for hyperspace engine, ...) and the decision to replace the current item.

**Comment by mwerle** [comment]
+1 on this.

The current interface is extremely unintuitive.

In fact, I think that it should not be possible to "Replace" equipment at all. It should only be possible to buy new equipment into an empty slot (with confirmation), forcing the player to first sell any equipment (with confirmation) if the target slot is currently not empty.

More clicking, yes, but far more intuitive, and it's not like equipment changes happen all the time in the game that this needs to be optimised to the fewest clicks possible.

**Comment by bszlrd** [comment]
Funny you mentioned this. The new equipmemt system of #5734 will address this soon.
