### ISSUE TITLE
Commodity and ship market selection marker not cleared

### ISSUE THREAD

**Issue by WKFO** [pioneerspacesim/pioneer#5023]
### Observed behaviour
Commodity market selection marker gets stuck at whatever position it was left at if you switch tabs and come back to the commodity market later.

![bug-commodity](https://user-images.githubusercontent.com/29180904/100250098-59792c00-2f4e-11eb-8981-3a7cdb87593c.gif)

### Expected behaviour
Remove marker when tabs are switched.

### Steps to reproduce
1) Switch to commodity market tab.
2) Select a commodity.
3) Switch to some other tab (for example station lobby).
4) Switch back to commodity market and scroll around.

__My pioneer version (and OS):__
28d865b4d754d41acac1b9d4e4978310a3f7c02f (Win10 x64)

**Comment by impaktor** [comment]
I wonder if this bug can be replicated in ship market as well?

**Comment by WKFO** [comment]
Ship market just selects to the first ship in the list when you switch to the tab. I don't know what would happen if the list has ships when you first switch to the tab, and is empty when you switch to somewhere else and back to it. Sort of an edge-ish case maybe, but that could be a problem. Let me first see if it persists between stations first.
