### ISSUE TITLE
Unable to load valid savestate

### ISSUE THREAD

**Issue by pcercuei** [pioneerspacesim/pioneer#5026]
### Observed behaviour
Loading a saved game created with `master` fails.

```
Fatal: [string "[T] @pigui/modules/saveloadgame.lua"]:113: This saved game cannot be loaded because it contains errors.
stack traceback:
	[C]: in function 'LoadGame'
	[string "[T] @pigui/modules/saveloadgame.lua"]:113: in function 'callback'
	[string "[T] @pigui/modules/saveloadgame.lua"]:40: in function 'optionTextButton'
	[string "[T] @pigui/modules/saveloadgame.lua"]:124: in function 'innerHandler'
	[string "[T] @pigui/libs/modal-win.lua"]:61: in function 'fun'
	[string "[T] @pigui/libs/wrappers.lua"]:596: in function 'withStyleColorsAndVars'
	[string "[T] @pigui/modules/saveloadgame.lua"]:136: in function 'outerHandler'
	[string "[T] @pigui/libs/modal-win.lua"]:59: in function 'drawModals'
	[string "[T] @pigui/libs/modal-win.lua"]:70: in function 'fun'
	[string "[T] @pigui/views/mainmenu.lua"]:172: in function 'callModules'
	[string "[T] @pigui/views/mainmenu.lua"]:258: in function 'showMainMenu'
	[string "[T] @pigui/views/mainmenu.lua"]:262: in function <[string "[T] @pigui/views/mainmenu.lua"]:261>Fatal: Frame instance deletion outside 'DeleteFrame' [0]
```

### Expected behaviour

The savestate is loaded.

### Steps to reproduce

- Get my savestate from https://app.box.com/s/aqzkvm3palsosduuh0zbtujummxizhvy
- Move it to `~/.pioneer/savefiles/`
- Try to load it in the main menu.

__My pioneer version (and OS):__

Pioneer master (d1d3eac3e) on Debian x64.

**Comment by Web-eWorks** [comment]
Master has been savebumped as we're working towards a release. Unless this is a save that was created on the same build as you're trying to load it from, this issue is out-of-scope.

**Comment by pcercuei** [comment]
As I wrote in the title - this is a **valid** savestate, which I actually created after the last savebump.

**Comment by The-EG** [comment]
I poked around a bit...it's crapping out while loading the system bodies, but I didn't narrow down which one.  

Is this reproducible in a particular system?

**Comment by pcercuei** [comment]
I remember I'm in the Dave system, I don't remember the exact coordinates though...

**Comment by Web-eWorks** [comment]
@pcercuei Found your problem. The save game wrote an invalid `skipjack` model to the save file, likely because you saved your game while the skipjack was being improperly loaded. I've added some code to catch this case, but it's absolutely not intended behavior to be able to load a save game with totally different models than the ones it was saved with.

**Comment by pcercuei** [comment]
I'll give it a try ASAP!
