### ISSUE TITLE
libretro port? :3

### ISSUE THREAD

**Issue by DartPower** [pioneerspacesim/pioneer#5035]
Hi there, i have a idea, you want to port to libretro?
This is will be cool, really :)

Check this also please :)
https://www.libretro.com/index.php/mission/
https://docs.libretro.com/development/cores/developing-cores/
https://www.libretro.com/index.php/powered-by-libretro/
https://docs.libretro.com/development/cores/opengl-cores/

**Comment by Web-eWorks** [comment]
Thank you for the suggestion, but we do not intend to port Pioneer to any additional platforms or operating systems at this time or any time in the near future. In addition, feature requests of this scope are best discussed on our [forums](https://pioneerspacesim.net/forum/); we use the Github issue tracker to track active issues with the codebase.

Pioneer has a strict graphical target of Open GL 3.2+extensions with plans to move to Vulkan to target modern desktop-class hardware in the near future. Not only does libretro as a platform and hardware target not support our requirements, but it would be significantly more work to refactor the guts of pioneer to support running inside the libretro container than we are interested in diverting to such an effort at this time.
