### ISSUE TITLE
Ross 154 errors

### ISSUE THREAD

**Issue by Bodasey** [pioneerspacesim/pioneer#5051]
### Observed behaviour

Ross 154 is labeled white in sector map, and no trade analysis is shown:

![Ross154_white_label](https://user-images.githubusercontent.com/60466586/101258808-3fe19c80-3725-11eb-8e87-9cf0230cb777.png)
![Ross154_no_trade_analysis](https://user-images.githubusercontent.com/60466586/101258811-47a14100-3725-11eb-90c7-e25f1d54c857.png)

### Expected behaviour

Ross 154 should be labeled blue (solar federation)

supposed reason: no station on ground, but this needs more research, no else such system seen yet

__My pioneer version (and OS):__
20200203 on SuSE Linux with KDE

**Comment by impaktor** [comment]
Is blue on master, but no import/export trade info icons, (due to all commodities are "minimal trade", it would appear)
![2020-12-05-190640_1600x900_scrot](https://user-images.githubusercontent.com/619390/101260013-19bffa80-372d-11eb-8bce-1366181fba31.png)

**Comment by Web-eWorks** [comment]
Yes, this is not a bug. Ross 154 simply does not have the population to generate any appreciable demand for commodities and is labeled as such on the sector map.
