### ISSUE TITLE
System viev: Destinations on ground are not marked

### ISSUE THREAD

**Issue by Bodasey** [pioneerspacesim/pioneer#5058]
### Observed behaviour

Set a starport on ground as destination, switch to system view: no destination is marked
(but works if the body is the destination)

### Expected behaviour

Same as if an orbital starport is the destination

__My pioneer version (and OS):__
20201206 on SuSE Linux

**Comment by Gliese852** [comment]
To be honest, I have long wanted to enable the display of ground ports in the system map. Seems to be a question for a few lines.

**Comment by impaktor** [comment]
As @Gliese852 mentioned in IRC just now, we don't know the position of surface port until the player enters that system, and terrain gen places the station. Orbit viewer in Frontier was under two different buttons depending on if you wanted current system (toggle F2 between orbit view and sector view) or some other system (F2->F6), and space was coloured differently to remind you which you were looking at (the more I think about it, the more I like it, actually), so brown-red for distant, and green for current system:

![2020-12-07-152147_1600x900_scrot](https://user-images.githubusercontent.com/619390/101364563-0171ec00-38a3-11eb-9c59-198a402b500e.png)

The player had to dive into orbit view to target the station they wanted. The Frontier version ported (back) from Amiga CD32 was essentially a Elite 2.5, in that it also had this nice list of targets to choose from (that we now have on world view): 
![2020-12-07-152348_1600x900_scrot](https://user-images.githubusercontent.com/619390/101364575-046cdc80-38a3-11eb-87d5-38a2402fb4e3.png)

And here's a ground base:
![2020-12-07-153828_1600x900_scrot](https://user-images.githubusercontent.com/619390/101364790-4007a680-38a3-11eb-9057-76d76b7ae200.png)
