### ISSUE TITLE
Error while sharing libraries in release version

### ISSUE THREAD

**Issue by youssefsahli** [pioneerspacesim/pioneer#5069]
./pioneer: error while loading shared libraries: libassimp.so.3: cannot open shared object file: No such file or directory
Pioneer release version

### Observed behaviour
Don't launch. difficult to resolve since ubuntu 20 doesn't provide it
 OS: Ubuntu LTS 20

**Comment by The-EG** [comment]
I'm on Windows so I can only speculate, but my guess: our linux release links against libassimp-3 on Ubuntu 16. Later versions of Ubuntu ship with newer versions (18 = 4, 20 = 5). 

Is it possible to select earlier versions of libassimp on the later versions of Ubuntu?

@Web-eWorks do we support *only* Ubuntu 16 for binary release?

**Comment by Web-eWorks** [comment]
Release binaries are provided as a reference version - for your platform you will either need to compile `libassimp` version 3 and install it locally or install Pioneer from your package manager. Alternatively, compiling Pioneer from source is the preferred way to resolve these conflicts.

The release version is now almost a year out of date and was actually authored *before* Ubuntu 20.04 was released. We do not officially support it with the current release.
