### ISSUE TITLE
Equipment market sign error

### ISSUE THREAD

**Issue by Bodasey** [pioneerspacesim/pioneer#5071]
### Observed behaviour

The number of an item in stock decreases when it is sold / increases when it is built into the ship

### Expected behaviour

clear

__My pioneer version (and OS):__
20201211 master on SuSE Linux

**Comment by osjc** [comment]
To be more accurate, here are steps to reproduce:

1. Start on Mars
2. Go to the equipment screen
3. Find the Radar on the list of equipment for sale.
4. Sell your radar (click on it on the right side)
5. The count of radars on the market DECREASES.

**Comment by impaktor** [comment]
It's because count variable is already negative, easy fix, thanks for reporting

**Comment by Bodasey** [comment]
fix confirmed, thank you!
