### ISSUE TITLE
Linux build, both from this year

### ISSUE THREAD

**Issue by STyx2909** [pioneerspacesim/pioneer#5088]
Ubuntu 18.06 and 20.06.

### Observed behaviour
**Error log:** pioneer: /home/[censored]/pioneer-20200203_linux/release/pioneer: error while loading shared libraries: libassimp.so.3: cannot open shared object file: No such file or directory

**__ Fix : __**
Sudo ln -s /usr/lib/x86_64-linux-gnu/libassimp.so.5.0.0 libassimp.so.3

**Comment by The-EG** [comment]
See #5069 . 
The binaries are built on Ubuntu 16, which ships assimp-3.0. Ubuntu 18 and 20 both ship newer version, 4 and 5 respectively. While linking the 5.0 version to 3.0 may work, it could also have unexpected consequences, so use at your own risk.

**Comment by The-EG** [comment]
Note: this is the second time this has come up in just over a week...with the upcoming release, do we need to consider bumping the binary build to Ubuntu 18, etc?
