### ISSUE TITLE
Template string in the bulletin board

### ISSUE THREAD

**Issue by maxcrystal** [pioneerspacesim/pioneer#5090]
![image](https://user-images.githubusercontent.com/13114986/103108020-e4843980-4654-11eb-8250-193c8c7d1817.png)

![Pioneer Screenshot 2020 12 24 - 17 21 36 93](https://user-images.githubusercontent.com/13114986/103108026-efd76500-4654-11eb-99cb-23f0d684b03a.png)

__My pioneer version (and OS):__ 20201222-rc1 (Windows 10)

**Comment by The-EG** [comment]
At a guess: I know some of the lang strings use different placeholders based on where/how they are displayed...since only that type of ad is misbehaving it may have been swapped. Or, just that string has something wrong with it.

**Comment by impaktor** [comment]
Fixed by #5092
