### ISSUE TITLE
Windows Defender started to quarantine  pioneer.exe right after installation

### ISSUE THREAD

**Issue by maxcrystal** [pioneerspacesim/pioneer#5091]
After last updates Windows Defender deletes pioneer.exe

Updates:
![12_25_20 @10_17_05](https://user-images.githubusercontent.com/13114986/103124946-7f533700-469a-11eb-89e8-ff52981b854a.PNG)

Defender:
![12_25_20 @10_03_07](https://user-images.githubusercontent.com/13114986/103124742-c42a9e00-4699-11eb-8f4b-63b1bd00e79d.PNG)

__My pioneer version (and OS):__ 20201222-rc1 (Windows 10)

**Comment by The-EG** [comment]
That's strange, I wonder if anyone else got this. I did not, and I'm fully up to date on both updates and definitions.

What version of Windows do you have? Do you have any extra definitions (like those that would be managed by the company you work for or government, etc)?

Also, it only quarantined the start menu link. The game itself is still there, where ever you installed it to

**Comment by maxcrystal** [comment]
@The-EG 

> What version of Windows do you have? Do you have any extra definitions (like those that would be managed by the company you work for or government, etc)?

Windows 10 Pro (x64). It is my gaming laptop, I have no extra definitions.

> Also, it only quarantined the start menu link. The game itself is still there, where ever you installed it to

No, it quarantined executable `pioneer.exe` and desktop and start menu links associated with it.

**Comment by The-EG** [comment]
Ok. At this point I can't reproduce. We'll see if anyone else sees this or not.

**Comment by nozmajner** [comment]
Avast did not complain or did anything on my end. 
A stray thought: Maybe something got in the installer during download? 
The md5 of the installer I downloaded is b6cb0c41d546ec91fab5fb4f25510d1a
You can use this command on the installer in a command prompt to check:
`certutil -hashfile pioneer-20201215-win.exe MD5`

**Comment by maxcrystal** [comment]
@nozmajner Release candidate version has other name:
```
MD5 hash of pioneer-20201222-win.exe:
52c36b328071fdc4afc0d7a79e8b3214
```
But the problem has gone as unexpectedly as it occurred. Defender doesn't think there is a threat anymore. 🤷‍♂️

**Comment by The-EG** [comment]
> @nozmajner Release candidate version has other name:
> 
> ```
> MD5 hash of pioneer-20201222-win.exe:
> 52c36b328071fdc4afc0d7a79e8b3214
> ```
> 
> But the problem has gone as unexpectedly as it occurred. Defender doesn't think there is a threat anymore. 🤷‍♂️
> 
> By the way, what is more useful for developers, if I play release candidate, or more recent 'master' branch builds? I'd prefer the latter as I don't want to deal with known bugs.

If you are able and comfortable compiling master then please do that.
