### ISSUE TITLE
Weapons don't work if no combat target is selected

### ISSUE THREAD

**Issue by WKFO** [pioneerspacesim/pioneer#5099]
### Observed behaviour
Weapons make sound but no projectiles/beams are created. However, if you have a combat target, they work as intended. Mining, on the other hand, is broken. (You can't select bodies as combat target.)

### Expected behaviour
Weapons should fire whether the player has a combat target or not.

__My pioneer version:__
78406e21c17a97a5f67d5a0828d15b0c2d99f834

**Comment by The-EG** [comment]
I think this is related to the aim-assist. I noticed something similar last time I was testing other things and fired near a station. In my case, firing makes a sound and I still got a red flash at the front of the ship, but it appeared to go sideways or something instead of forward.

**Comment by WKFO** [comment]
Another thing I noticed and should mention, beam weapons should not be assisted to hit the leading aimpoint. But they should not be assisted to directly hit the ship either, because as far as I've observed, their hit detection requires them to be just a little ahead of the ship; so better leave them as they were maybe (without aim assist).

**Comment by Web-eWorks** [comment]
Hmm, good reporting! I could have sworn I fixed the weapon firing sideways but it's possible I didn't test this specific case. I'll look into beam weapons as well... possibly something to do with projectile velocity.

**Comment by nozmajner** [comment]
It seems like the weapon tags are ignored altogether. Here's a video:
[![](http://img.youtube.com/vi/P5tvyGXbYfA/0.jpg)](http://www.youtube.com/watch?v=P5tvyGXbYfA "Wep")
It's only in the correct place for the Kanara.

**Comment by Web-eWorks** [comment]
Weapon tags is a separate issue, as nothing in that logic was touched by the aimpoint changes.
