### ISSUE TITLE
Crew Roster: Harmless reputation rating appears truncated by a line break

### ISSUE THREAD

**Issue by Another-MrZ** [pioneerspacesim/pioneer#5102]
### Observed behaviour
Commander reputation rating in Crew Roster appears split with the last letter displayed in a second row.
Really minor issue, but it could occur with other ranks too.

### Expected behaviour
Commander reputation rating should have enough space to be seen in a single line.

### Steps to reproduce
1. Ensure your commander has Harmless rank
2. Open Crew roster
3. Click on the commander more info button

__My pioneer version (and OS):__  20201222 (Windows 7)

![LineBreak](https://user-images.githubusercontent.com/34732798/103274677-23e6b900-49ba-11eb-8a07-8b86a253c454.png)

**Comment by The-EG** [comment]
Just for info purposes: what resolution were you running? It looks like 1440x900

**Comment by Another-MrZ** [comment]
Yes, it's 1440x900.
