### ISSUE TITLE
ModelViewer changes resolution to 1600*900

### ISSUE THREAD

**Issue by nozmajner** [pioneerspacesim/pioneer#5103]
### Observed behaviour
If you start the ModelViewer (pioneer -mv), it changes the resolution to 1600*900. Either if you had it larger or smaller. And then it stays at that.
It happens both if the game is fulscreen or windowed.
### Expected behaviour
ModelViewer to not change the resolution

### Steps to reproduce
Start Pioneer, set a resolution, exit.
Run the ModelViewer. Observe changed resolution.
Run the game again, and check the resolution setting.

__My pioneer version (and OS):__
Win 10
December Release Candidate

**Comment by Web-eWorks** [comment]
...that's really weird, as the ModelViewer should be explicitly *not* using the game's config and instead hardcoding resolution and VSync state. I'll look into that.
