### ISSUE TITLE
Autopilot approach/dock with space stations results in a lot more crashes in the 20201222 version

### ISSUE THREAD

**Issue by pebblegarden** [pioneerspacesim/pioneer#5111]
### Observed behaviour
When I use the autopilot to approach or dock with a space station, I usually crash into it. 
The stations often seem to present their ring edge to me.
Extra weirdness: My ship usually docks with the station (when it works) in a reverse heading, that is, flying backward into the slot.

### Expected behaviour
Stations should be oriented along random vectors upon arrival.
My ship should not autopilot into a collision with the station.

### Steps to reproduce
Select a space station from the outliner (upper right corner of HUD).
Choose to either Approach or Dock with the station. 
Enable time acceleration.
Observe how the station often appears oriented with its rotational axis exactly 90 degrees to your ship.
Observe how the autopilot flies toward the ship 

__My pioneer version (and OS):__
i'm using Pioneer 20201222 and Windows 10 OS, with latest updates as of 01/04/2021.

**Comment by WKFO** [comment]
Stations are not oriented according to where the player is, they retain their orientation which is set at the galaxy generation, so I think that part is just a statistical oddity.

**Comment by WKFO** [comment]
For whoever is interested in fixing this: I was about to say that station orientations are not set according to player, but then I realized they do indeed appear with their rotation axis oriented exactly 90 degrees to the player. However this only happens if you are visiting a new station, so if you visit a station, go away and visit that station again without visiting another station, it does not appear oriented 90 degrees to the player but with whatever orientation it had when you visited it.

**Comment by fluffyfreak** [comment]
That is definitely not correct behaviour

**Comment by nozmajner** [comment]
The backwardness part bugged me since they were finished. I tried to fix it with the tags, but couldn't be able to figure it out. I think I could look into it again.

**Comment by fluffyfreak** [comment]
I think the backwardness part is my fault, but the station docking logic and state machine is baffling

**Comment by fluffyfreak** [comment]
@nozmajner is this fixed by #5131

**Comment by nozmajner** [comment]
I don't think so. I think it only affects the inside the station part.

**Comment by jimishol** [comment]
I approached space station and I'm standing still about it. (I upload a save of this moment). Get permission and order autopilot to dock. He crashes my ship on station every time. I manually move my ship in different place. After that i order my autopilot to dock. He can dock this time.
I am afraid autopilot does not understand accurately where the borders of station are.
[save_mod_autopilot_crashes.gz](https://github.com/pioneerspacesim/pioneer/files/7194609/save_mod_autopilot_crashes.gz)

**Comment by Bodasey** [comment]
These crashes have become rare. To close?

**Comment by pebblegarden** [comment]
I haven't observed this problem in a while, so I'm closing this issue. Thanks to the person who fixed it, if you did.
