### ISSUE TITLE
No comms, no autopilot

### ISSUE THREAD

**Issue by liambrownweb** [pioneerspacesim/pioneer#5122]
### Observed behaviour
I can open the comm log, and before taking off at the beginning of a game, pressing F4 opens the station comm view. Once I take off, I cannot talk to autopilot or anything else; F4 does nothing.

### Expected behaviour
F4 opens the comm view, allowing communication with stations and autopilot.

__My pioneer version (and OS):__
2012-12-22 running on OpenSuSE Tumbleweed.

**Comment by Web-eWorks** [comment]
This could be a matter of not having touched that code in a while, but as far as I'm aware there has not been an F4 menu to talk to *anything* while in flight for longer than I've been on the team. Requesting docking is carried out by using the right-click radial menu on stations in the world, and so is setting the autopilot.

**Comment by liambrownweb** [comment]
Aha. I must have read outdated docs. Here I thought it was a bug.

**Comment by impaktor** [comment]
The F4 menu was removed maybe in 2016, one of the first things to go with the pigui. 

However, I believe this raises an important point: Frontier players (and old Pioneer players) will not find the right-click pie-menu easily, so question is how to guide the user right? Ideally a tutorial system, but easiest would be to update that outdated documentation. @liambrownweb do you know where you read it on the wiki? Even better: if you find it, can you please edit it?
