### ISSUE TITLE
Transifex stopped pushing

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#5130]
Last push from Transifex was December 8: 2132b52a3d9cf7b17a336d8c0405fad3307c8930

I'll click around and see if I can accidentally do something that kicks it back into life again.

**Comment by impaktor** [comment]
OK, mystery solved, we have a script that used to run as a cron job (I assume) that's stopped running:
https://github.com/pioneerspacesim/pioneer/blob/master/scripts/update-translations.sh

@ecraven just did a manual single run of it, pulling in quite a bit of translations b42abbe01ec7a27da975932db8b14e07d03e1ade

Ideally, we would have this run is as a scheduled github action, if possible.

**Comment by The-EG** [comment]
> Ideally, we would have this run is as a scheduled github action, if possible.

Oh. That should be possible, it looks like it would require the transifex client to be installed. 

Also of interest: https://docs.transifex.com/transifex-github-integrations/github-tx-ui

**Comment by The-EG** [comment]
In the link above it suggests that it's possible for transifex to push back to github automatically:

> Pulling content from the designated GitHub repository and branch happens automatically upon changes on that branch.
>
> To push localized content from Transifex back to GitHub you have the following options:
> - Upon 100% translated, reviewed or proofread content.
> - Push content via a Pull Request on that branch, which will create a new branch with the localized content and open a Pull Request on the branch, that you can later merge directly from GitHub.
> - Push content via a commit back to the selected branch.

Maybe this wasn't possible back when it was fist setup...or did we not do this for other reasons?

**Comment by impaktor** [comment]
I suspect it's the last (third) option we would want.

> Maybe this wasn't possible back when it was fist setup...or did we not do this for other reasons?

I suspect this is fairly new. I know the dev team (rob or jpab, or maybe fluffy?) wrote some blog posts on the transifex migration, on pioneer's google+ account, back when that was a thing.

I know we have some link in transifex to the github repo:
![2021-02-01-133604_1600x900_scrot](https://user-images.githubusercontent.com/619390/106459746-9b64a800-6492-11eb-9667-dd4d98ec8f20.png)

We also have something in github:
![2021-02-01-133824_1600x900_scrot](https://user-images.githubusercontent.com/619390/106459936-e383ca80-6492-11eb-8d6b-f0ecf9f48497.png)

However, I don't see the direct usage of these, since new resources are added manually to transifex, together with URL to the raw json counterpart in our repo, to monitor for updates.

The only actual writing is done by the pioneer-transifex user.

**Comment by impaktor** [comment]
Yeah, github's transifex webapp doesn't seem to do what it claims to do:
 
> All setup is easily managed through the all-in-one Transifex web app, in three simple steps:

> Authenticate Transifex on GitHub,
> Link your GitHub repository to a Transifex project, and
> Specify the files you'd like to sync, and what automated actions should take place after localized content is sent from Transifex back to Github.

**Comment by The-EG** [comment]
> The only actual writing is done by the pioneer-transifex user.

Yeah, that's our own user, isn't it? The docs mention:

> Any commits or PRs that are opening due to the integration are happening from a GitHub user called Transifex-localization-platform[bot]

**Comment by comradekingu** [comment]
Libre software on Transifex just doesn't compute for me.

https://docs.weblate.org/no/latest/admin/continuous.html?highlight=webhooks#automatically-receiving-changes-from-github

I won't go on at length about the shortcomings of Transifex, but alas.

**Comment by Web-eWorks** [comment]
Closing this as transifex is pushing again. Can be reopened in the future if someone wants to try to further automate our solution.
