### ISSUE TITLE
Few Translation Quirks

### ISSUE THREAD

**Issue by RacerBG** [pioneerspacesim/pioneer#5133]
### Observed behaviour
1. The buttons are not resizing according to the string length.
2. At some places the font size is too big and too small.
3. The mass and radius variables are showing their real names instead of the translation.
3.1. The screenshot from the game seems to have white background for no particular reason.

### Expected behaviour
The buttons should either resize or include text with smaller fonts, the text size at some places should be revised, the mass and radius variables should show their translations and the pictures should have native background colour.

![background and variables](https://user-images.githubusercontent.com/68707872/106519331-ca573a00-64e3-11eb-9cf1-aaefad0ca502.png)
![fonts size](https://user-images.githubusercontent.com/68707872/106519334-cb886700-64e3-11eb-9f24-2ef02807654f.png)
![small button](https://user-images.githubusercontent.com/68707872/106519338-cc20fd80-64e3-11eb-83e8-4512af0f186a.png)

Game: Pioneer RC 2020-12-22
OS: Windows 7 SP1 64 bit
GPU: AMD Radeon R7 250 2 GB

PS: Sorry about not giving more detailed bug report (I could do it tomorrow) and making it all in one place, it's quite late here now... :smile: Also, I hope I still have time to finish the Bulgarian translation of the game, I did my best today but real life and work are taking their toll.

Regards,
Georgi

**Comment by The-EG** [comment]
It looks like it's numbers that are oddly sized...but it's not consistent either.

**Comment by RacerBG** [comment]
> 
> 
> It looks like it's numbers that are oddly sized...but it's not consistent either.

This could be related to my earlier issue #4977 .

**Comment by The-EG** [comment]
> This could be related to my earlier issue #4977 .

Yes, it could be. My first thought is that it may be using the fallback font for those numbers for one reason or another. Or the font we are using just doesn't do well, as you pointed out.

**Comment by Web-eWorks** [comment]
So the background color is an easy issue; the screen is cleared to (0, 0, 0, 0) and we never actually render anything over it with opacity. The fix here would be to either stop saving PNGs with alpha channel or to clear the screen with full alpha coverage.

Fonts are a little harder; supporting intentionally smaller glyphs for display on certain buttons is not nearly as easy as it would sound for a number of reasons, but most notably the fact that it involves rendering separate versions of the glyphs at the smaller size to avoid scaling artifacts. Something we can look into but I wouldn't expect to get fixed soon.

The number size issue I believe is due to the russian glyphs being loaded from a different font face at a different scale; I can look into adding some more debug information regarding our font chain when I get a chance.

The N_EARTH_MASSES is purely an issue with the russian / bulgarian translation - that can be fixed in Transifex.

**Comment by RacerBG** [comment]
> So the background color is an easy issue; the screen is cleared to (0, 0, 0, 0) and we never actually render anything over it with opacity. The fix here would be to either stop saving PNGs with alpha channel or to clear the screen with full alpha coverage.

Either one is fine with me.

> Fonts are a little harder; supporting intentionally smaller glyphs for display on certain buttons is not nearly as easy as it would sound for a number of reasons, but most notably the fact that it involves rendering separate versions of the glyphs at the smaller size to avoid scaling artifacts. Something we can look into but I wouldn't expect to get fixed soon.

The main problem (at least in my opinion) here is that some fonts (the fuel and the cabin capacity for example) are too small to read. And on that note some of the Nerodia stats are not on a single line (too large font, I'm not sure) I already tried to avoid too long words.

> The number size issue I believe is due to the russian glyphs being loaded from a different font face at a different scale; I can look into adding some more debug information regarding our font chain when I get a chance.

That would be great!

> The N_EARTH_MASSES is purely an issue with the russian / bulgarian translation - that can be fixed in Transifex.

I will see what can I do about this. I'm already doing a revision of everything which I translated, maybe I made an unintentional mistake somewhere.

Regards,
Georgi

**Comment by impaktor** [comment]
- The planet display: That's oldUI, and slated for move to pigui.
- Text not fitting buttons: this is why we try to avoid putting text on buttons, an use images instead, + tooltip when mouse hovers over a button
- Transparent screenshot is tracked by #4671

**Comment by RacerBG** [comment]
Update: With RC 2021-01-29 the radius and masses issue disappeared.

**Comment by RacerBG** [comment]
After the merge of #5475 everything looks much better so I'm closing this issue. The other problems which I originally reported where already fixed.
