### ISSUE TITLE
Cannot open game

### ISSUE THREAD

**Issue by derpderpderpdarp** [pioneerspacesim/pioneer#5135]
help,
I installed the pioneer version of 2021-02-03, and every time I open the game it shows me an error message says a file is missing and cannot open the game.

**Comment by impaktor** [comment]
There is absolutely nothing we can do unless you tell us what file it is that it claims is missing.

And what's your OS? Windows?

**Comment by etam** [comment]
Probably duplicate of #5138 ?

**Comment by geeksmooth** [comment]
confirm same problem...  file:
Fatal: Error while loading Space Station data (check stdout/output.txt).

and yes... probably duplicate of #5138

[output.txt](https://github.com/pioneerspacesim/pioneer/files/5935383/output.txt)
