### ISSUE TITLE
SmartScreen (Microsoft Defender) Considers pioneer installer as a possible threat

### ISSUE THREAD

**Issue by ConfedMajor** [pioneerspacesim/pioneer#5139]
### Observed behaviour

When running the pioneer installer, this window prompts up:

![imagen](https://user-images.githubusercontent.com/71795983/106934191-9739c400-66f8-11eb-8600-61105e3ddf94.png)

Translation (Spanish To English):

**Windows protected your PC**
Microsoft Defender SmartScreen prevented an unknown application from starting. Running this application can pose a risk to your PC.

Application:
pioneer-20210203-win.exe
Editor:
Unknown publisher

### Expected behaviour

Perhaps SmartScreen should consider it safe app

### Steps to reproduce

Run the pioneer installer (from the lastest release)

__My pioneer version (and OS):__

Pioneer version: Lastest Release

PC Specs:

![Pc_Specs](https://user-images.githubusercontent.com/71795983/106935354-019f3400-66fa-11eb-8054-701070097fca.png)

EDIT: My windows version is up-to-date

**NOTE:** This window can be easily dismissed by clicking *more information* and then clicking *execute* button

This happens 100% of time when i execute the installer

**Comment by The-EG** [comment]
Not sure what we can do about this. It's because it's a new file that hasn't been downloaded much.

This is almost certainly happening [because](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-smartscreen/microsoft-defender-smartscreen-overview):
> Microsoft Defender SmartScreen determines whether a downloaded app or app installer is potentially malicious by:
>
> - Checking downloaded files against a list of files that are well known and downloaded by many Windows users. If the file isn't on that list, Microsoft Defender SmartScreen shows a warning, advising caution.

I've already sent a report to MS stating that it's a safe file, but I have no idea when/if that will actually trigger them to mark it as safe. We may just have to wait until more people download and run it.

**Comment by Web-eWorks** [comment]
@The-EG do we sign the InnoSetup installer? I'm not sure of the feasibility of this especially given that we're an open-source software, but IIRC unsigned executables were starting to get cracked down on the last time I was a serious Windows user.

**Comment by impaktor** [comment]
I'd say: Pioneer considers Windows to be unsafe software.
https://www.gnu.org/proprietary/malware-microsoft.html

**Comment by fluffyfreak** [comment]
Signing exe's for Windows is a pain in the arse
https://stackoverflow.com/questions/252226/signing-a-windows-exe-file
