### ISSUE TITLE
2021-02-03 release missing shared lib on Ubuntu 20.04 (Focal)

### ISSUE THREAD

**Issue by kmasaryk** [pioneerspacesim/pioneer#5140]
Downloaded and unzipped pioneer-20210203-linux.tar.gz. I'm seeing the following error:

```
$ ./pioneer 
./pioneer: error while loading shared libraries: libassimp.so.5: cannot open shared object file: No such file or directory
```

OS info:
```
 OS: Ubuntu 20.04 focal
 Kernel: x86_64 Linux 5.4.0-65-generic
 Uptime: 3d 4h 54m
 Packages: 2754
 Shell: bash 5.0.17
 Resolution: 2560x1440
 DE: Xfce
 WM: Xfwm4
 WM Theme: Greybird-dark
 GTK Theme: Greybird-dark [GTK2]
 Icon Theme: Humanity-Dark
 Font: Noto Sans 11
 Disk: 1.2T / 1.6T (73%)
 CPU: AMD Ryzen 5 2600 Six-Core @ 12x 3.4GHz
 GPU: GeForce RTX 2070 SUPER
 RAM: 20939MiB / 32111MiB
```
I wasn't able to find a list of required dependencies anywhere in the README.md or Quickstart.txt. Not seeing anything on the main website either.

Doing a search for that lib produces the following:

```
$ apt search libassimp
Sorting... Done
Full Text Search... Done
libassimp-dev/focal 5.0.1~ds0-1build1 amd64
  3D model import library (development)

libassimp-doc/focal,focal 5.0.1~ds0-1build1 all
  3D model import library (documentation)

libassimp5/focal 5.0.1~ds0-1build1 amd64
  3D model import library
```

Is that the right one? Any others we need to know about?

**Comment by The-EG** [comment]
It should be libassimp5, yes.

**Comment by kmasaryk** [comment]
Installing `libassimp5` solved that error and then another occurred:
```
./pioneer: error while loading shared libraries: libSDL2_image-2.0.so.0: cannot open shared object file: No such file or directory
```
That one is resolved by installing `libsdl2-image-2.0-0`

It's running now without anymore errors.

**Comment by Web-eWorks** [comment]
For the record, all of these library requirements are documented in COMPILING.TXT here in the repo if you run into further issues. We could look into adding a note about required libraries, but generally if you're not installing software through your distribution's package manager, it's expected that you will have to manually install all needed dependencies.

Shared libraries are by design shared by all programs on a system, and as such it's not really feasible for us to ship our own copy of them in downloadable builds.

**Comment by kmasaryk** [comment]
Actually, something like the COMPILING.TXT file you mention is exactly what I was looking for but didn't see in the binary package. Also, that file mentions a number of packages you don't actually need if you're just running the pre-compiled binary so I'd suggest including an INSTALL file with the binary package which just lists required shared libs.

**Comment by impaktor** [comment]
Yes, that info could be on the wiki FAQ, and also to the release build. Feel free to contribute it. (If signing up to the wiki, the answer to the security question needs to be subtracted by -1, since it still thinks we're in 2020).
