### ISSUE TITLE
Version number independent from local time

### ISSUE THREAD

**Issue by Bodasey** [pioneerspacesim/pioneer#5142]
Again, also not a classic bug, I hope here is the right place for that anyway:

### Observed behaviour

The Version number shown in the Window is based on the local time of compilation.

### Expected behaviour

Something unique / better identifiable

### Steps to reproduce

- Set your computer's clock to a date in the future
- Download and compile master branch
- reset the clock / reboot the system
- start pioneer

You get e.g.

__My pioneer version (and OS):__
20210218 on SuSE Linux (on February 6, 2021)

But even with clocks controlled by a Net Time Protocol Server, you can get different version numbers in different locations on the world for the same thing or different things with the same Version number.

A little wish to the programmers: There is no access to the version number when a game is running (at least, it's not easy to find) - maybe it can be added on the options menu? Many thanks in advance.

Where shall I post other things I have found being inconsistent behave/look of the program or to discuss? What do you recommend as central meeting point? I'm not keen on opening (and maintaining) more than one additional account for the pioneer project.

**Comment by Web-eWorks** [comment]
Version number (or really, the build date) is entirely useless to us. The important part is the git commit hash or git tag name, which happens to be used as the version number in release builds. We could look at adding the commit hash/tag name in the options menu, that shouldn't be too hard to do.

If you have minor papercuts you can open an issue and list them. We might not prioritize them, but it'd be good to have them listed out. This issue tracker is our central coordination point; you don't need to create additional accounts (and we'd prefer you just stick to the one).

**Comment by impaktor** [comment]
> A little wish to the programmers: There is no access to the version number when a game is running (at least, it's not easy to find) - maybe it can be added on the options menu? Many thanks in advance.

![2021-02-07-104132_1600x900_scrot](https://user-images.githubusercontent.com/619390/107142746-4a8cfd80-6931-11eb-961b-c982af1abc2a.png)

Granted, that version hash isn't friendly to copy paste, so a copy to clipboard button, or raw selectable text in options menu could be nice.

> Where shall I post other things I have found being inconsistent behave/look

Bugs, and unexpected behavior goes here on the issue tracker. If you just want to dream starry eyed about what the game could be in the future, what new features you desire, then IRC or dev forum.

**Comment by Web-eWorks** [comment]
Closing this as it's sat for a while and I have no plans to implement it in the near future.
