### ISSUE TITLE
Saved games of older versions cannot be loaded

### ISSUE THREAD

**Issue by gerrygk** [pioneerspacesim/pioneer#5143]
Hey all,

I just tried the new v2021-02-03 @ Linux Mint 20 (archive from pioneerspacesim.net and flathub version) and I couldn't load any saved game state of the precursor.

Any ideas what's going on?

**Comment by impaktor** [comment]
What is the precursor, which version?

what's the error message?

**Comment by gerrygk** [comment]
The precursor is the last official version (2020-02-03).

Unfortunately, I don't get any error message at all. The 'load' button seems to be deactivated when I choose an 'old' saved state (but it works fine with saved states of the new v2021-02-03).

**Comment by WKFO** [comment]
It might be because the galaxy changed with fluffy's system name generation PR.

**Comment by nozmajner** [comment]
I suspect there were a few save bump changes since last year.

**Comment by impaktor** [comment]
Yes, saves are only compatible with the pre-release of january, and december.

Not being able to load is a feature.

**Comment by impaktor** [comment]
https://pioneerwiki.com/wiki/FAQ#Are_savegames_compatible_between_releases.3F
