### ISSUE TITLE
Fatal: GLEW initialisation failed: Missing GL version

### ISSUE THREAD

**Issue by STyx2909** [pioneerspacesim/pioneer#5144]
Ubuntu 20.04 LTS

Unfortunately latest version of Pioneer stopped running on my old laptop.
This is the same error I experienced when I was to compile it from source.

Older binary version was graphically fine aside a library issue that could be hacked.
```

 ./pioneer
ver 20210203 (142693b) on: Linux

System Name: Linux
Host Name: stephan-K61IC
Release(Kernel) Version: 5.4.0-65-generic
Kernel Build Timestamp: #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021
Machine Arch: x86_64
Domain Name: (none)

--------------------
SDL Version (build) 2.0.10
SDL Version (dynamic) 2.0.10
SDL Versions match
SDL_image Version (build): 2.0.5
SDL_image Version (dynamic): 2.0.5
SDL_image Versions match
Assimp Version: 5.0.0
FreeType Version: 2.10.1
GLEW dynamic version: 2.0.0
--------------------

Fatal: GLEW initialisation failed: Missing GL version
```

`OpenGL version 3.2.0 NVIDIA 340.108, running on NVIDIA Corporation GeForce GT 220M/PCIe/SSE2
Available extensions:
Shading language version: 1.50 NVIDIA via Cg compiler
  GL_ARB_arrays_of_arrays
  GL_ARB_base_instance
  GL_ARB_blend_func_extended
  GL_ARB_clear_buffer_object
  GL_ARB_color_buffer_float
  GL_ARB_compressed_texture_pixel_storage
  GL_ARB_conservative_depth
  GL_ARB_copy_buffer
  GL_ARB_copy_image
  GL_ARB_debug_output
  GL_ARB_depth_buffer_float
  GL_ARB_depth_clamp
  GL_ARB_depth_texture
  GL_ARB_draw_buffers
  GL_ARB_draw_elements_base_vertex
  GL_ARB_draw_instanced
  GL_ARB_enhanced_layouts
  GL_ARB_ES2_compatibility
  GL_ARB_ES3_compatibility
  GL_ARB_explicit_attrib_location
  GL_ARB_explicit_uniform_location
  GL_ARB_fragment_coord_conventions
  GL_ARB_fragment_layer_viewport
  GL_ARB_fragment_program
  GL_ARB_fragment_program_shadow
  GL_ARB_fragment_shader
  GL_ARB_framebuffer_no_attachments
  GL_ARB_framebuffer_object
  GL_ARB_framebuffer_sRGB
  GL_ARB_geometry_shader4
  GL_ARB_get_program_binary
  GL_ARB_half_float_pixel
  GL_ARB_half_float_vertex
  GL_ARB_imaging
  GL_ARB_instanced_arrays
  GL_ARB_internalformat_query
  GL_ARB_internalformat_query2
  GL_ARB_invalidate_subdata
  GL_ARB_map_buffer_alignment
  GL_ARB_map_buffer_range
  GL_ARB_multi_bind
  GL_ARB_multisample
  GL_ARB_multitexture
  GL_ARB_occlusion_query
  GL_ARB_occlusion_query2
  GL_ARB_pixel_buffer_object
  GL_ARB_point_parameters
  GL_ARB_point_sprite
  GL_ARB_program_interface_query
  GL_ARB_provoking_vertex
  GL_ARB_robust_buffer_access_behavior
  GL_ARB_robustness
  GL_ARB_sampler_objects
  GL_ARB_seamless_cube_map
  GL_ARB_separate_shader_objects
  GL_ARB_shader_bit_encoding
  GL_ARB_shader_objects
  GL_ARB_shader_texture_lod
  GL_ARB_shading_language_100
  GL_ARB_shading_language_420pack
  GL_ARB_shading_language_include
  GL_ARB_shading_language_packing
  GL_ARB_shadow
  GL_ARB_stencil_texturing
  GL_ARB_sync
  GL_ARB_texture_border_clamp
  GL_ARB_texture_buffer_object
  GL_ARB_texture_buffer_range
  GL_ARB_texture_compression
  GL_ARB_texture_compression_rgtc
  GL_ARB_texture_cube_map
  GL_ARB_texture_env_add
  GL_ARB_texture_env_combine
  GL_ARB_texture_env_crossbar
  GL_ARB_texture_env_dot3
  GL_ARB_texture_float
  GL_ARB_texture_mirror_clamp_to_edge
  GL_ARB_texture_mirrored_repeat
  GL_ARB_texture_multisample
  GL_ARB_texture_non_power_of_two
  GL_ARB_texture_query_levels
  GL_ARB_texture_rectangle
  GL_ARB_texture_rg
  GL_ARB_texture_rgb10_a2ui
  GL_ARB_texture_stencil8
  GL_ARB_texture_storage
  GL_ARB_texture_storage_multisample
  GL_ARB_texture_swizzle
  GL_ARB_texture_view
  GL_ARB_timer_query
  GL_ARB_transpose_matrix
  GL_ARB_uniform_buffer_object
  GL_ARB_vertex_array_bgra
  GL_ARB_vertex_array_object
  GL_ARB_vertex_attrib_binding
  GL_ARB_vertex_buffer_object
  GL_ARB_vertex_program
  GL_ARB_vertex_shader
  GL_ARB_vertex_type_10f_11f_11f_rev
  GL_ARB_vertex_type_2_10_10_10_rev
  GL_ARB_viewport_array
  GL_ARB_window_pos
  GL_ATI_draw_buffers
  GL_ATI_texture_float
  GL_ATI_texture_mirror_once
  GL_S3_s3tc
  GL_EXT_texture_env_add
  GL_EXT_abgr
  GL_EXT_bgra
  GL_EXT_bindable_uniform
  GL_EXT_blend_color
  GL_EXT_blend_equation_separate
  GL_EXT_blend_func_separate
  GL_EXT_blend_minmax
  GL_EXT_blend_subtract
  GL_EXT_compiled_vertex_array
  GL_EXT_Cg_shader
  GL_EXT_depth_bounds_test
  GL_EXT_direct_state_access
  GL_EXT_draw_buffers2
  GL_EXT_draw_instanced
  GL_EXT_draw_range_elements
  GL_EXT_fog_coord
  GL_EXT_framebuffer_blit
  GL_EXT_framebuffer_multisample
  GL_EXTX_framebuffer_mixed_formats
  GL_EXT_framebuffer_multisample_blit_scaled
  GL_EXT_framebuffer_object
  GL_EXT_framebuffer_sRGB
  GL_EXT_geometry_shader4
  GL_EXT_gpu_program_parameters
  GL_EXT_gpu_shader4
  GL_EXT_multi_draw_arrays
  GL_EXT_packed_depth_stencil
  GL_EXT_packed_float
  GL_EXT_packed_pixels
  GL_EXT_pixel_buffer_object
  GL_EXT_point_parameters
  GL_EXT_provoking_vertex
  GL_EXT_rescale_normal
  GL_EXT_secondary_color
  GL_EXT_separate_shader_objects
  GL_EXT_separate_specular_color
  GL_EXT_shader_integer_mix
  GL_EXT_shadow_funcs
  GL_EXT_stencil_two_side
  GL_EXT_stencil_wrap
  GL_EXT_texture3D
  GL_EXT_texture_array
  GL_EXT_texture_buffer_object
  GL_EXT_texture_compression_dxt1
  GL_EXT_texture_compression_latc
  GL_EXT_texture_compression_rgtc
  GL_EXT_texture_compression_s3tc
  GL_EXT_texture_cube_map
  GL_EXT_texture_edge_clamp
  GL_EXT_texture_env_combine
  GL_EXT_texture_env_dot3
  GL_EXT_texture_filter_anisotropic
  GL_EXT_texture_integer
  GL_EXT_texture_lod
  GL_EXT_texture_lod_bias
  GL_EXT_texture_mirror_clamp
  GL_EXT_texture_object
  GL_EXT_texture_shared_exponent
  GL_EXT_texture_sRGB
  GL_EXT_texture_sRGB_decode
  GL_EXT_texture_storage
  GL_EXT_texture_swizzle
  GL_EXT_timer_query
  GL_EXT_vertex_array
  GL_EXT_vertex_array_bgra
  GL_EXT_x11_sync_object
  GL_EXT_import_sync_object
  GL_IBM_rasterpos_clip
  GL_IBM_texture_mirrored_repeat
  GL_KHR_debug
  GL_KTX_buffer_region
  GL_NV_blend_square
  GL_NV_conditional_render
  GL_NV_copy_depth_to_color
  GL_NV_copy_image
  GL_NV_depth_buffer_float
  GL_NV_depth_clamp
  GL_NV_ES1_1_compatibility
  GL_NV_explicit_multisample
  GL_NV_fence
  GL_NV_float_buffer
  GL_NV_fog_distance
  GL_NV_fragment_program
  GL_NV_fragment_program_option
  GL_NV_fragment_program2
  GL_NV_framebuffer_multisample_coverage
  GL_NV_geometry_shader4
  GL_NV_gpu_program4
  GL_NV_half_float
  GL_NV_light_max_exponent
  GL_NV_multisample_coverage
  GL_NV_multisample_filter_hint
  GL_NV_occlusion_query
  GL_NV_packed_depth_stencil
  GL_NV_parameter_buffer_object
  GL_NV_parameter_buffer_object2
  GL_NV_path_rendering
  GL_NV_pixel_data_range
  GL_NV_point_sprite
  GL_NV_primitive_restart
  GL_NV_register_combiners
  GL_NV_register_combiners2
  GL_NV_shader_buffer_load
  GL_NV_texgen_reflection
  GL_NV_texture_barrier
  GL_NV_texture_compression_vtc
  GL_NV_texture_env_combine4
  GL_NV_texture_expand_normal
  GL_NV_texture_multisample
  GL_NV_texture_rectangle
  GL_NV_texture_shader
  GL_NV_texture_shader2
  GL_NV_texture_shader3
  GL_NV_transform_feedback
  GL_NV_vdpau_interop
  GL_NV_vertex_array_range
  GL_NV_vertex_array_range2
  GL_NV_vertex_buffer_unified_memory
  GL_NV_vertex_program
  GL_NV_vertex_program1_1
  GL_NV_vertex_program2
  GL_NV_vertex_program2_option
  GL_NV_vertex_program3
  GL_NVX_conditional_render
  GL_NVX_gpu_memory_info
  GL_SGIS_generate_mipmap
  GL_SGIS_texture_lod
  GL_SGIX_depth_texture
  GL_SGIX_shadow
  GL_SUN_slice_accum

Implementation Limits:
GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = 96
GL_MAX_CUBE_MAP_TEXTURE_SIZE = 8192
GL_MAX_DRAW_BUFFERS = 8
GL_MAX_ELEMENTS_INDICES = 1.04858e+06
GL_MAX_ELEMENTS_VERTICES = 1.04858e+06
GL_MAX_FRAGMENT_UNIFORM_COMPONENTS = 2048
GL_MAX_TEXTURE_IMAGE_UNITS = 32
GL_MAX_TEXTURE_LOD_BIAS = 15
GL_MAX_TEXTURE_SIZE = 8192
GL_MAX_VERTEX_ATTRIBS = 16
GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = 32
GL_MAX_VERTEX_UNIFORM_COMPONENTS = 4096
GL_NUM_COMPRESSED_TEXTURE_FORMATS = 23
GL_SAMPLE_BUFFERS = 1
GL_SAMPLES = 2
GL_ALIASED_LINE_WIDTH_RANGE = 1, 10
GL_MAX_VIEWPORT_DIMS = 8192, 8192
GL_SMOOTH_LINE_WIDTH_RANGE = 1, 1
GL_SMOOTH_POINT_SIZE_RANGE = 1, 189.875

Compressed texture formats:
  0x83f0
  0x83f2
  0x83f3
  0x8b90
  0x8b91
  0x8b92
  0x8b93
  0x8b94
  0x8b95
  0x8b96
  0x8b97
  0x8b98
  0x8b99
  0x9274
  0x9275
  0x9276
  0x9277
  0x9278
  0x9279
  0x9270
  0x9271
  0x9272
  0x9273`

**Comment by STyx2909** [comment]
Problem solved by getting rid of Nvidia drivers and incorrect xorg.conf file after that... 8-P
Game launches, is a bit more sluggish than before and finally runs out of memory about 2 minutes later;
```
Warning: OpenGL error(s) during frame:
In function SwapBuffers
On line 530
GL_OUT_OF_MEMORY
TradeShips: Removed 0 ships before serialization
StarSystemCache: misses: 39, slave hits: 0, master hits: 13668
SectorCache: misses: 470038, slave hits: 0, master hits: 13822
Pi shutting down.
StarSystemCache: misses: 0, slave hits: 0, master hits: 0
SectorCache: misses: 0, slave hits: 0, master hits: 0

```
Never happened with official drivers. Meh.

**Comment by Web-eWorks** [comment]
That's going to be a problem with the driver, yeah. It's odd that it's running out of memory; even on a 1GB card you should be fine as I've never seen Pioneer go above more than ~700MB of VRAM (and even then that's very rare).

**Comment by anidotnet** [comment]
I am also facing the same issue on Ubuntu 20.04. Both released binary and compiled from source binary is failing with this exception. So what is the fix for this issue?

**Comment by etam** [comment]
I also have this problem. I'm on openSUSE Tumbleweed, using build from "games" repository (which I'm also a maintainer), using Radeon card with Mesa drivers.
```
ver 20210723 on: Linux

System Name: Linux
Host Name: etam-komp
Release(Kernel) Version: 5.13.6-1-default
Kernel Build Timestamp: #1 SMP Thu Jul 29 04:18:38 UTC 2021 (2d7b44d)
Machine Arch: x86_64
Domain Name:

--------------------
SDL Version (build) 2.0.14
SDL Version (dynamic) 2.0.14
SDL Versions match
SDL_image Version (build): 2.0.5
SDL_image Version (dynamic): 2.0.5
SDL_image Versions match
Assimp Version: 5.0.0
FreeType Version: 2.11.0
GLEW dynamic version: 2.2.0
--------------------

Fatal: GLEW initialisation failed: Missing GL version
```

```
$ glxinfo | grep OpenGL
OpenGL vendor string: AMD
OpenGL renderer string: AMD Radeon RX 5700 (NAVI10, DRM 3.41.0, 5.13.6-1-default, LLVM 12.0.1)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 21.1.6
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.1.6
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.1.6
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

**Comment by neoedmund** [comment]
Same here on Linux, Fatal: GLEW initialisation failed: Missing GL version
Should reopen the issue.

**Comment by Web-eWorks** [comment]
Without detailed information from your output.txt and opengl.txt I cannot determine if you have a valid issue. "Missing GL version" typically indicates that your system does not support the otherwise-valid version of OpenGL we've requested.

**Comment by neoedmund** [comment]
```
Info: ver 20230224 (50b28e3) on: Linux
Info: System Name: Linux
Host Name: n79
Release(Kernel) Version: 6.1.6-gs+
Kernel Build Timestamp: #41 SMP PREEMPT_DYNAMIC Sun Jan 15 17:11:48 JST 2023
Machine Arch: x86_64
Domain Name: (none)
Warning: couldn't read language file 'lang/core/C..json'
Warning: couldn't load language resource core/C., trying core/en
Info: --------------------
Info: SDL Version (build) 2.26.1
Info: SDL Version (dynamic) 2.26.1
Info: SDL Versions match
Info: SDL_image Version (build): 2.0.5
Info: SDL_image Version (dynamic): 2.0.5
Info: SDL_image Versions match
Info: Assimp Version: 5.0.0
Info: FreeType Version: 2.12.1
Info: GLEW dynamic version: 2.0.0
Info: --------------------
Info: 
Fatal: GLEW initialisation failed: Missing GL version
```
[glxinfo.txt](https://github.com/pioneerspacesim/pioneer/files/10828372/glxinfo.txt)

also [sdl2  opengl demo](https://github.com/theandrew168/sdl2-opengl-demo/blob/master/src/main.c) can be run. maybe GLEW is not needed for opengl initialization?
