### ISSUE TITLE
Gas Giants Do Not Render Properly 

### ISSUE THREAD

**Issue by RL-10** [pioneerspacesim/pioneer#5145]
### Observed behaviour
Gas giants will completely disappear when viewed at the center of the screen. They are only visible when they are viewed at the edge of the screen. Basically, the entire gas giant can never be viewed because when the player attempts to bring the whole body into view, the gas giant will disappear entirely. Here is a screenshot that illustrates this behavior.

![Disappearing Gas Giant](https://user-images.githubusercontent.com/79066000/107898031-49933780-6f00-11eb-9608-0de840804d6d.png)

### Expected behaviour
Gas giants should not disappear at all. 

### Steps to reproduce
Visit any gas giant. 

__My pioneer version (and OS):__
ver 20210203 (142693b), Ubuntu 20.04 LTS
OpenGL.txt file: https://pastebin.com/g27cQT78

**Comment by impaktor** [comment]
Works on my build. What resolution are you playing on?
![2021-02-15-092117_1600x900_scrot](https://user-images.githubusercontent.com/619390/107921798-500cc800-6f6f-11eb-88e9-2d5d69cfa30f.png)

**Comment by fluffyfreak** [comment]
2560x1080 by the look of it, will try this on my ultrawide monitor to see if it's that.
You've got an nVidia 2080 so that shouldn't be an issue.

**Comment by fluffyfreak** [comment]
Ok, so I think there might be some issues but I'm not sure if they're resolution related. It looks more like depth buffer problems to me.

![screenshot-20210215-121529](https://user-images.githubusercontent.com/825083/107945600-c74e5600-6f87-11eb-8616-20ba9234ef86.png)
![screenshot-20210215-121513](https://user-images.githubusercontent.com/825083/107945605-c7e6ec80-6f87-11eb-837a-ed7a52c51f5a.png)
![screenshot-20210215-121525](https://user-images.githubusercontent.com/825083/107945606-c87f8300-6f87-11eb-90ea-29118013591d.png)

Save file attached.
[weird-jupiter.zip](https://github.com/pioneerspacesim/pioneer/files/5981474/weird-jupiter.zip)

**Comment by fluffyfreak** [comment]
@Web-eWorks ^^^

**Comment by fluffyfreak** [comment]
To get my state to happen: 
- autopilited into a medium orbit, 
- set the external view to look at Jupiter, 
- turn the ship directly away from Jupiter, 
- accelerated hard and increased the time acceleration two steps.

Then I just kept jupiter in view with the camera controls and paused once I saw the weirdness.

**Comment by Web-eWorks** [comment]
Yeah, I noticed this behavior happening in a New Hope start too - not really sure what's the culprit for the white ring, but I suspect some of the math in the atmosphere shader needs to be double-checked. The bug appears to be related to large gas giants getting depth-clipped (I didn't touch the actual clip dist in the perspective projection originally) before they scale down to 0, so there's a few different fixes:

- Use an infinite projection matrix for rendering far bodies (probably the best idea).
- Increase the camera clip distance (works, but is a rather arbitrary solution).
- Adjust the body scaling logic to work properly for massive gas giants like Jupiter.

**Comment by RL-10** [comment]
@impaktor, Yes, I'm playing on a 2560x1080 ultrawide. I tried playing in a 1920x1080 window and I still got the same issue.

**Comment by RL-10** [comment]
@fluffyfreak Your screenshots and description describe exactly what I've been experiencing.

**Comment by RacerBG** [comment]
I can confirm this bug - I'm playing on a 1280x1024 and Saturn is only half visible when I'm close to it - the other half is basically cut off.

**Comment by fluffyfreak** [comment]
No this is due to the depth buffer for certain, it probably affects stars as well. Any massive object is going to have depth buffer issues.

This either needs to use logarithmic z-buffer method, or infinite projection method

**Comment by Trokinos** [comment]
I ran into the same problem with current release, when flying around Vesta (the asteroid in our solar system) once i started to approach one of the huge elevated ugly crater with its bizarre looking spikes (wonder if it's a bug or some fractal rendering not playing nice) on its surrounding, half of Vesta disappeared, then from another angle of view, it's the whole thing that was invisible.  

This wasn't happening on the version of Pioneer i used a couple of years ago.

**Comment by impaktor** [comment]
@Trokinos spiky asteroids is a different issue, one that @fluffyfreak has been battling before, so if you see those, screenshot, with coordinates, and open an issue.

**Comment by fluffyfreak** [comment]
This was the PR where we dropped logz, etc #4975

I have no idea how to implement the infinite Z projection matrix

**Comment by fluffyfreak** [comment]
@Web-eWorks I just hacked this into RendererGL.cpp line 656 replacing:
`SetProjection(matrix4x4f::PerspectiveMatrix(DEG2RAD(fov), aspect, near_, far_));` 
with
`SetProjection(matrix4x4f::InfinitePerspectiveMatrix(DEG2RAD(fov), aspect, near_));`

Everything seemed to work just fine so I'm wondering why you didn't just go with that in the #4975 PR?
What was the issue that stopped you?

**Comment by Web-eWorks** [comment]
> I have no idea how to implement the infinite Z projection matrix

It's already implemented in matrix4x4.h...

> I just hacked this into RendererGL.cpp line 656 replacing:

> Everything seemed to work just fine so I'm wondering why you didn't just go with that in the #4975 PR?
> What was the issue that stopped you?

Ah, ninja'd I see. That PR was intended to match existing behavior as much as possible to regression-test it; unfortunately it didn't get as much testing uptake as I would have liked during the merge period.

There's no technical reason against using an infinite projection matrix, I simply didn't want to introduce any additional variables in the scope of that PR. If that is a suitable fix without any other side-effects (e.g. introducing Z-fighting) then you'll just need to update the code in WorldView.cpp (and GuiScreen.cpp) that linearizes the post-projection depth values according to https://thxforthefish.com/posts/reverse_z/ and it should be good to merge.

The reason I haven't done it so far (besides being neck deep in refactoring the renderer API and not having any free time to do other work on Pioneer) is because I was originally intending to use the infinite matrix for far planets and moons and use a 'regular' matrix for closer ModelBodies to preserve precision especially in small details. Just haven't had any time to work on that.
