### ISSUE TITLE
Pioneer 20210203 don't start

### ISSUE THREAD

**Issue by G-Stavole** [pioneerspacesim/pioneer#5148]
I tried Pioneer 20210203 but it don't start, from directory release, command line report:
./pioneer
./pioneer: error while loading shared libraries: libassimp.so.5: cannot open shared object file: No such file or directory

Pioneer 20200203 works fine and worked with the previous distribution version. 
I use Linux 64bit Mageia distribution recently upgraded from 7.1 to 8 but this didn't solve the problem.
Mageia doesn't have libassimp.so.5 in its package it reach version 3 only.
Is there a way to bypass the problem, with a simlink maybe?
I have an Intel dual core 64 bit 1800 MHz, 4 GB Ram and Nvidia 6300 graphic card with 2GB Ram.

**Comment by RL-10** [comment]
Can you not install libassimp.so.5 from your distribution's package manager? I believe that was a library I needed to install to get Pioneer to run on Kubuntu.

**Comment by Web-eWorks** [comment]
That is quite the old hardware - it may not be possible that Pioneer runs on your system. However, the way to work around this is to clone Pioneer from this repo and build it yourself. On that system, it may take a while, but as long as your distribution provides libassimp 3.6 or higher you should be okay. Please refer to COMPILING.txt in this repo for instructions.

Unfortunately, if your platform doesn't provide binary packages compatible with the ones used to generate the binary release we're not able to do anything.

**Comment by riidom** [comment]
I get (trying the itch.io build) this error:

`./pioneer: error while loading shared libraries: libassimp.so.3: cannot open shared object file: No such file or directory
`

So are both versions needed? Why is it complaining about 3 missing in my case, and about 5 missing in OP's case? Is there smth to do except building myself, can I somehow "install" what's missing? As you can guess, I'm not too knowledged in this department:)

**Comment by impaktor** [comment]
@riidom what I can tell, the [itch](https://pioneerspacesim.itch.io/pioneer) build is 2 years old. As it so happens, we made a new release this Thursday, please use [that](https://github.com/pioneerspacesim/pioneer/releases/tag/20220203) instead. If you're having problems with that, please open a new issue.

**Comment by riidom** [comment]
Thanks, I did not notice the age of the itch.io build. I indeed had some problems with the recent version, just want to log how I solved it, for other newbies:

- Inside your unpacked pioneer directory, run `ldd pioneer | grep "not found"` If you get no results, but still have problems, it is some other problem
- for me the result has been:
  - `        libassimp.so.5 => not found`
  - `libSDL2_image-2.0.so.0 => not found`
- I installed the missing packages via `sudo apt-get`. How they are exactly called you gotta search on web (try "sudo apt-get *name of above results minus .so.#*")
- in my case, it was `sudo apt-get install libassimp5` and `sudo apt-get install libsdl2-image-2.0-0-dev`
- try again starting pioneer: `./pioneer` success rate should be a lot higher now

**Comment by Zireael07** [comment]
As an aside : why isn't the itch build updated? From a player pov, that would be the first place I'd check...

**Comment by impaktor** [comment]
@Zireael07 I don't think anyone in the dev team has access to the site, I don't remember who made the site, it was by some player who did it. I'm sure I have it in my IRC log or dev forum somewhere.

**Comment by Zireael07** [comment]
In that case, it would be worth it to either make a new itch site (e.g. Pioneer official) by the devs, or get access to it somehow, or get the unofficial site taken down...

**Comment by impaktor** [comment]
@Zireael07 Fixed now. Noz found the password.
