### ISSUE TITLE
Game Crash While Hyperspace

### ISSUE THREAD

**Issue by py7hon** [pioneerspacesim/pioneer#5152]
### Observed behaviour
When I Hypespace and open sector map and game crashes

__My pioneer version (and OS):__
ver 20210203 (142693b) on: Linux
[output.txt](https://github.com/pioneerspacesim/pioneer/files/6153812/output.txt)

**Comment by impaktor** [comment]
@Gliese852 wasn't this fixed, prior to release?

**Comment by Gliese852** [comment]
@impaktor apparently this is something different, I was fixing problems on the C++ side
