### ISSUE TITLE
Weird UI issue in station screen

### ISSUE THREAD

**Issue by WKFO** [pioneerspacesim/pioneer#5159]
### Observed behaviour
https://www.youtube.com/watch?v=jk_kCVmIvsc

### Expected behaviour
Don't do that maybe?

### Steps to reproduce
Enter station screen at the specific time shown in video.

__My pioneer version (and OS):__
8052a5903a2c67fa641f5eb2852a0a4277d63795, Windows 10

**Comment by nozmajner** [comment]
A step up for the facegen for sure!

**Comment by WKFO** [comment]
Sorry for abusing Github for this (but it was worth it).

**Comment by craigo-** [comment]
PROXIMITY ALERT: @WKFO is on a collision course to becoming my favourite Youtuber 😄
