### ISSUE TITLE
Pioneer Only Shows A Black Windowed Screen

### ISSUE THREAD

**Issue by osaryes** [pioneerspacesim/pioneer#5162]
[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/6282287/opengl.txt)
[output.txt](https://github.com/pioneerspacesim/pioneer/files/6282288/output.txt)

 Downloaded and installed the game without any problems, but when opening either the Desktop shortcut or the .exe file it opens a windowed black screen and a warning saying: 

"OpenGL error(s) during frame: In function Text::TextureFont::TextureFont On line 590 GL_INVALID_OPERATION". 

The warning only shows an "OK" button, which I pressed. Next I can hear the background music and the game cursor, but the screen stays black until I close it. Tried uninstalling and reinstaling with no success. Updated the graphics card driver and same thing happens. Verified OpenGL version and it's 4.6.

My pioneer version (and OS): pioneer-20210203 for Windows
OS: Windows 10 *64 bits
CPU: AMD Ryzen 5 4600H w/ Radeon Graphics
RAM:  8.00 GB
Graphics Card: NVIDIA GeForce GTX  1650 and the integrated AMD Radeon card.
Downloaded the .exe file directly from the site https://pioneerspacesim.net/page/download/.

**Comment by impaktor** [comment]
Maybe @fluffyfreak or @Web-eWorks have some insights into what's going on here.

**Comment by fluffyfreak** [comment]
First thing is your GPU driver is fairly out of date on version `NVIDIA 457.63` so try updating that, they're onto version 466.11 now.

The `TextureFont::TextureFont` looks like a red-herring in that it's an error check at the top of the ctor 🤷‍♀️ so the problem probably happened before TextureFont and is just getting caught in it.

**Comment by fluffyfreak** [comment]
Although `TextureFont::TextureFont` happens very early...
It might be that the driver is not handling the Imgui and Pioneer technically have two different OpenGL contexts. I.e. Imgui has it's own instead of rendering through Pioneers 🤷 that's just speculation though

**Comment by The-EG** [comment]
For what it's worth I have a very similar graphics card and I would have been using 457.63 at some point since it was released in November of last year. Unless this issue was introduced after that, it shouldn't be the driver or the card.

The integrated Radeon card was mentioned a few times. Is this a laptop? Or are you using both cards (ie. multiple monitors or something)?

**Comment by osaryes** [comment]
> For what it's worth I have a very similar graphics card and I would have been using 457.63 at some point since it was released in November of last year. Unless this issue was introduced after that, it shouldn't be the driver or the card.
> 
> The integrated Radeon card was mentioned a few times. Is this a laptop? Or are you using both cards (ie. multiple monitors or something)?

Hello. Thanks for answering.

It is a laptop. I also updated the driver last week I think and the issue still occurs. The Alt+Z prompt to show GeForce options also shows up briefly like any other game.

**Comment by The-EG** [comment]
Ah. I'm sure Fluffy and others can weight in, but mobile GPUs can bring in another level of unknowns in terms of drivers.

With it being a laptop and having both a Radeon 'built in' plus the NVidia GPU, I have to wonder if it's something with [Optimus](https://www.nvidia.com/en-us/geforce/technologies/optimus/technology/) going on.

**Comment by osaryes** [comment]
No idea, not very savvy on graphics I'm afraid.

Should I se if I need to configure something?

**Comment by The-EG** [comment]
> Should I se if I need to configure something?

Not yet, I'm just throwing it out there as a possible reason...or to possibly confuse things more 😄. Let's see what Fluffy, et al say.

**Comment by fluffyfreak** [comment]
There's not usually much to configure with nVidia Optimus under Windows, we have the exposed flag that tells it to use it. The `opengl.txt` shows that it's working and picking the nVidia GPU.

Like I say, first thing to do with any graphics problem is update drivers, they break in subtle ways all the time between versions.
This is the (UK language) version of the latest drivers https://www.nvidia.co.uk/Download/driverResults.aspx/172575/en-uk but you should be able to find the specific one from https://www.nvidia.co.uk/Download/index.aspx?lang=uk or you can use the "nVidia Geforce Experience" tool if it's installed.

You could also see if there's any driver updates for the CPU/GPU from AMD... I did have a quick look but the AMD website is... rubbish 🤷‍♂️ and I gave up 😒

Anyway all this is just "_it might help_" at this point.
The output from your log files seems ok with nothing out of the ordinary until the warnings start which is very interesting. It seems like it should have failed on earlier graphics calls.

So step 1: Update nVidia graphics driver, try again, if it fails then report back 👍
Step 2: if step 1 fails see if you can update your AMD drivers either via your laptop manufacturer website/AMDs.
Step 3: well that's odd, I could do you a custom build with the nVidia flag removed/disabled and we could try that.

**Comment by Web-eWorks** [comment]
> Although `TextureFont::TextureFont` happens very early...
> It might be that the driver is not handling the Imgui and Pioneer technically have two different OpenGL contexts. I.e. Imgui has it's own instead of rendering through Pioneers shrug that's just speculation though

In terms of actual proper OGL contexts, ImGui uses the same window context that the rest of Pioneer's rendering does; there's no difference in there. It does handle all of its rendering through raw OpenGL commands rather than going through Pioneer's Renderer API, but that hasn't caused *any* problems so far on any other systems, even when I was hacking apart the rendering code.

**Comment by osaryes** [comment]
Driver for the Nvidia graphics card is updated now. I used the GeForce Experience tool for it. It's now on version 466.11.

Couldn't find a way to update the integrated card, though. Or even check what version it currently is.

**Comment by fluffyfreak** [comment]
@osaryes was there any improvement?

**Comment by osaryes** [comment]
> @osaryes was there any improvement?

Still shows a black screen. Same warning appears too.

**Comment by Web-eWorks** [comment]
@osaryes please change `EnableGLDebug=0` in your `config.ini` to 1, re-run the program, and attach the `output.txt` from that run to this issue. That will hopefully shed more light upon the problem.

**Comment by osaryes** [comment]
> @osaryes please change `EnableGLDebug=0` in your `config.ini` to 1, re-run the program, and attach the `output.txt` from that run to this issue. That will hopefully shed more light upon the problem.

[output.txt](https://github.com/pioneerspacesim/pioneer/files/6410506/output.txt)

Here. The issue is still coming up, though.

**Comment by Web-eWorks** [comment]
Try setting your `AntiAliasingMode=` line in `config.ini` to 0. The error appears to be happening because there's a difference between what Pioneer is requesting for the MSAA level and what the windowing system is giving it.

**Comment by osaryes** [comment]
> Try setting your `AntiAliasingMode=` line in `config.ini` to 0. The error appears to be happening because there's a difference between what Pioneer is requesting for the MSAA level and what the windowing system is giving it.

Oh sh*t! It worked! You got it!

**Comment by impaktor** [comment]
Now, I wonder what lesson we can draw from this? Is there something we should put on the FAQ, or is there some change in the code base?

**Comment by Web-eWorks** [comment]
Going to re-open this issue as we need some better validation in the MSAA handling to ensure that we're getting what we're requesting.
