### ISSUE TITLE
Loading saved file on a port makes the tasks undoable.

### ISSUE THREAD

**Issue by Mutron9050** [pioneerspacesim/pioneer#5163]
### Observed behaviour 
Whenever I load a save in which the ship is docked at the port,
I am no longer able to view and perform the tasks
![image](https://user-images.githubusercontent.com/82556122/114810656-2da9f600-9dca-11eb-9082-8a7e265b32e3.png)

To make the tasks available, I had to undock and land again.

### Expected behaviour
It was expected for it to show the tasks

### Steps to reproduce
Save the game when you are docked with a port,
End the game,
Load the save,
Open 'Show comms',
Open 'bulletin board'.

__My pioneer version (and OS):__ 20210203 (142693b)

**Comment by Gliese852** [comment]
click on play button

**Comment by Mutron9050** [comment]
> click on play button

sorry my bad

**Comment by impaktor** [comment]
@Mutron9050 you're not the first to make that mistake.

I've made a note on it for a potential future "tutorial mode"
