### ISSUE TITLE
Tutorial 

### ISSUE THREAD

**Issue by RocketNinja15** [pioneerspacesim/pioneer#5171]
### Observed behaviour
For a new player, following the Wiki isnt allways the easist. I think there should be some type of introduction to the game highlighting some of the major points in that tutorial 

### Expected behaviour
A tutorial outlinning how to play, features, menus, and anything else of importance that isnt learned along the way

### Steps to reproduce

N/A
__My pioneer version (and OS):__
Latest, Windows

**Comment by impaktor** [comment]
Yes, this is already on our to-do list.
If  you want to help with this, that would be more than welcome.
We generally don't track features on the issue tracker, but rather on the dev forum.

**Comment by RocketNinja15** [comment]
@RocketNinja15 can I get a link to the dev forum! I don't know coding, but if I can, I will help :)

**Comment by impaktor** [comment]
It was still assuming we were in 2020, I've updated it now, so it should be the pioneer year + 2. odd number, 4 digits starting with 3. I don't want to give the answer here for spam bots. Come by IRC if there are problems.
If you don't get confirmation email within an hour, please let us know (this happens often)

**Comment by RocketNinja15** [comment]
> It was still assuming we were in 2020, I've updated it now, so it should be the pioneer year + 2. odd number, 4 digits starting with 3. I don't want to give the answer here for spam bots. Come by IRC if there are problems.
> If you don't get confirmation email within an hour, please let us know (this happens often)

Hi, I still haven't gotten the confirmation email :(

**Comment by impaktor** [comment]
It's been activated now.
