### ISSUE TITLE
(CLOSE?) Game crash during hyperjump if one of the menu buttons is clicked

### ISSUE THREAD

**Issue by tropicalpioneer** [pioneerspacesim/pioneer#5174]
### Observed behaviour
Sometimes the game crashes if, during a hyperjump, I select the top menu icon "show personal info" or "switch to sector map".
A pop up window appears describing the error. I will edit and copy it in here ASAP.

Edit: happens as well if I try to End game.
screenshot of error message added down in my next comment.

### Steps to reproduce

Start a hyperjump, wait for the end of countdown and click a top icon before the hyperjump is completed
edit: or clic End game

__My pioneer version (and OS):__
20210205
Linux Mint 20.1 Cinnamon

**Comment by Gliese852** [comment]
and also please add all the output to the terminal

**Comment by tropicalpioneer** [comment]
Here is a crash message. 
In this case I did not click a menu icon, but I was ending the game.
![pioneer issue click during hyperjump](https://user-images.githubusercontent.com/84130826/118214453-4f1e0080-b4a2-11eb-8fd6-94608147d257.png)

**Comment by tropicalpioneer** [comment]
![Uploading Screenshot from 2021-05-16 00-39-47.png…]()

**Comment by tropicalpioneer** [comment]
![Uploading Screenshot from 2021-05-16 01-25-41.png…]()

**Comment by tropicalpioneer** [comment]
Since I installed 20210513 (0c84df0) I cannot reproduce this bug.

**Comment by impaktor** [comment]
The crash in the first screen shot was likely fixed by this commit in March: 452e9468bc32b844b379307f982c5869733bd85b

Dunno the other crashes, but I'm happy to close.
