### ISSUE TITLE
Combat mission - no show by enemy while orbiting - no mission confirmation

### ISSUE THREAD

**Issue by tropicalpioneer** [pioneerspacesim/pioneer#5175]
### Observed behaviour
In Combat or Sweep missions, sometimes there are no enemies AND there is no message of mission accomplished for reaching the orbit of the target planet.

Tried all distances (vicinity of planet and high, medium, low orbits), because sometimes it is a matter of moving between orbits.
Fast forward, checked.

### Expected behaviour
Either presence of enemy spaceship(s) or a CommsLog message of mission accomplished.
I don't know if there are more scenarios that I am missing,

### Steps to reproduce
Randomly on Combat or sweep missions, POSSIBLY when the target planet has radius >2 Mm 

__My pioneer version (and OS):__
Pioneer downloaded and installed in April 2021
Linux Mint 20.1 Cinnamon

**Comment by Gliese852** [comment]
could you please attach savegame during such a mission

**Comment by tropicalpioneer** [comment]
[pioneer issue 5175.zip](https://github.com/pioneerspacesim/pioneer/files/6472324/pioneer.issue.5175.zip)

**Comment by tropicalpioneer** [comment]
Here is another saved game with a mission where the issue can be tested. If I remember well, the planet is about 100Mm radius.
[issue 5175 example 2 100Mm planet.zip](https://github.com/pioneerspacesim/pioneer/files/6476385/issue.5175.example.2.100Mm.planet.zip)

**Comment by robothauler** [comment]
For the last mission, I got the mission complete message approximately after 16 hours in orbit.

**Comment by tropicalpioneer** [comment]
Yesterday I uploaded another saved game with the issue, then I reloaded it, tried again, and when I got on the planet orbit I received accomplished mission message.

But there is something weird... 
?Where can I read about how the logic/code works :
- when the mission is accomplished without ships showing up
- to decide if and at what distance from the planet the ship(s) appear.

**Comment by robothauler** [comment]
You only need to stay inside the planets frame (the planet must be the dominating mass). Maybe you slipped out of the frame because of a too elliptical orbit? Then you must enter the frame again. If you need to destroy the enemy ships, this doesn't matter.
