### ISSUE TITLE
Skipjack weapon not firing after reload (both tag and save issue)

### ISSUE THREAD

**Issue by tropicalpioneer** [pioneerspacesim/pioneer#5177]
### Observed behaviour
When I shoot, I don't see the beam but I hear it and it heats up.
Target ship is not affected by the shooting, so it appears to be really just noise and heating but no beam and damage.

I had three ships before the Skipjack courier, and did not have this issue before.
Weapon has been bought and mounted on the front.
I am shooting while on the front camera; If I try to shoot while on rear camera there is no sound or heating.

### Expected behaviour
I expect to see the beam and give damage to the target shield and health.

### Steps to reproduce
use the saved game in next post and try to shoot in that battle

__My pioneer version (and OS):__
20210205 and 20210513 (0c84df0)
Mint 20.1 Cinnamon

**Comment by tropicalpioneer** [comment]
here is a saved game, straight in battle, armed with a small plasma but...not hurting at all with "invisible" shooting :)
[issue skipjack coourier not damaging.zip](https://github.com/pioneerspacesim/pioneer/files/6494741/issue.skipjack.coourier.not.damaging.zip)

**Comment by tropicalpioneer** [comment]
here a saved game in 20210513 (0c84df0) 
[issue skypjack weapons.zip](https://github.com/pioneerspacesim/pioneer/files/6554674/issue.skypjack.weapons.zip)

**Comment by impaktor** [comment]
@tropicalpioneer Saw your message on IRC, we have moved from freenode, please find us on libera.chat instead. https://pioneerwiki.com/wiki/IRC

**Comment by jimishol** [comment]
Confirmed except the damage part because i rarely hit the target anyway.

**Comment by f6p** [comment]
Happens for me also on 20210724.

**Comment by nozmajner** [comment]
It works on my end:

https://user-images.githubusercontent.com/4182678/133921577-8ec0fc42-95ba-460d-9276-353553ab0dda.mp4

**Comment by f6p** [comment]
It looks like a corrupted save file.

If I sell ship then buy it again and mount same weapon everything works. Its broken after I make a save and reload it.

**Comment by nozmajner** [comment]
I think I found the issue. The model has `tag_gunmount` tag instead of `tag_gunmount_0`
It is odd though, that it is picked up properly at first, and then it doesn't work after reloading.

**Comment by nozmajner** [comment]
The above PR should fix it
