### ISSUE TITLE
[SOLVED?] Failed missions don't disappear until visiting the target system.

### ISSUE THREAD

**Issue by tropicalpioneer** [pioneerspacesim/pioneer#5181]
### Observed behaviour
When a Combat mission is failed, it does not disappear from the mission list.
edit: _unless you visit the target/payment system_

### Expected behaviour
How about the possibility of manually cancelling a mission previously accepted and manually delete failed ones?

### Steps to reproduce

__My pioneer version (and OS):__

**Comment by Web-eWorks** [comment]
See also: #3006

**Comment by tropicalpioneer** [comment]
You can try to remove the only mission in this savegame.
Target System is right "nextdoor".

I could not: tried visiting the target planet, orbiting, leaving the system.


[issue unremoved failed mission.zip](https://github.com/pioneerspacesim/pioneer/files/6491216/issue.unremoved.failed.mission.zip)

**Comment by tropicalpioneer** [comment]
I managed to receive a failed mission message by visiting the system where I was supposed to be paid. 
Mission was the unlisted.

**Comment by tropicalpioneer** [comment]
Updated my Pioneer to 20210513 (0c84df0).
Failed missions now disappear upon landing (anywhere). 
I would consider _solved_ the "issue" about failed mission being listed until visiting the mission system.
