### ISSUE TITLE
Auto-refuel at stations?

### ISSUE THREAD

**Issue by tropicalpioneer** [pioneerspacesim/pioneer#5182]
### Observed behaviour
Every time we dock, we must click the Auto-refuel button.

Is there a scenario where you don't refuel when you dock in a station?

Does the weight of the fuel _in the tank_ affect cargo, speed, or any other performance?

### Steps to reproduce

__My pioneer version (and OS):__

**Comment by impaktor** [comment]
If the player is short on cash, or maybe prefers to use fuel scoop.
Please leave feature request on the dev forum

**Comment by tropicalpioneer** [comment]
I am not sure I understand. What is the dev forum? Isn't it this one?
Do you mean that feature request must be left on the another forum?

About the fuel, I understand that in the beginning migh tbe short on cash, but isn't it a small amount of gameplay compared to a full career? How about a tickbox to activate/deactivate autofuel? Once "rich", you don't want to be a clicking machine anymore if you don't use fuelscoop.

**Comment by tropicalpioneer** [comment]
I am not sure I understand. What is the dev forum? Isn't it this one?
Do you mean that feature request must be left on the another forum?

About the fuel, I understand that in the beginning migh tbe short on cash, but isn't it a small amount of gameplay compared to a full career? How about a tickbox to activate/deactivate autofuel? Once "rich", you don't want to be a clicking machine anymore if you don't use fuelscoop.

**Comment by nozmajner** [comment]
Yes, we are using the issue tracker for tracking bugs and work.
For feature request and discussion we are using our [dev forum](https://pioneerspacesim.net/forum/).
Please register with the same user name you have here, and I can activate you right away (we had severe spambot problems).

For the refuel button, I don't think it would be good to make an action that deduces money automatic. True, it's peanuts on a smaller ship, but it can go quite high for larger ones. But anyway I think the player should decide on the spending of money wherever possible. A checkbox might work, but then you'd need a way to disable it when not docked, when you realize that you are short on cash, or just doesn't want a full tank.
And ship performance does change with the amount of fuel you have on board. Both acceleration and hyperspace range are affected.

**Comment by tropicalpioneer** [comment]
Very interesting, thank you for the explanation.
Since I started playing, I had ships with max 60t fuel capacity, so obviously I did not feel the need to control refueling costs. I will feel the pain later on bigger ships, apparently! :)

I registered in the dev forum now, same username, waiting for email/activation.

Thank you for taking the time to answer me.

**Comment by nozmajner** [comment]
I've activated you account.
