### ISSUE TITLE
take-off button missing after rescue landing

### ISSUE THREAD

**Issue by tropicalpioneer** [pioneerspacesim/pioneer#5186]
### Observed behaviour
In Rescue missions for crashlanded ships, sometimes the take off button is not available.
Is there another way to ignite the take off? 

### Steps to reproduce
Saved game attached.
You have just loaded the crew from crashed ship.
Try to take off: the blast off button mught or might not be there.

__My pioneer version (and OS):__
downloaded and installed the last week of April (how to find the version?)
Mint Cinnamon 20.1
[issue 5186 - missing take off button.zip](https://github.com/pioneerspacesim/pioneer/files/6488709/issue.5186.-.missing.take.off.button.zip)

**Comment by tropicalpioneer** [comment]
Of course

**Comment by Bodasey** [comment]
= #5320 ?

**Comment by impaktor** [comment]
Probably fixed by #5332
