### ISSUE TITLE
Sector Map - cannot select second choice when searching homonymous stars

### ISSUE THREAD

**Issue by tropicalpioneer** [pioneerspacesim/pioneer#5188]
### Observed behaviour
In Sector Map, when using the search field, if you look for a star name that has multiple results (for example: Vemi) cannot select the second system among the search results showing homonymous stars.
![issue omonimous star selection](https://user-images.githubusercontent.com/84130826/118397768-46871f00-b688-11eb-86cd-192feb7c79a7.png)
![Screenshot from 2021-05-17 11-54-33](https://user-images.githubusercontent.com/84130826/118430470-b63bef00-b706-11eb-863d-9de578bc98ed.png)
![Screenshot from 2021-05-17 12-07-16](https://user-images.githubusercontent.com/84130826/118431284-855cb980-b708-11eb-8615-107c1c5acfb6.png)

### Steps to reproduce

__My pioneer version (and OS):__
20210205
Mint Cinnamon 20.1

**Comment by Web-eWorks** [comment]
This is a very simple fix - the IDs used by the selectable elements in the search results are just the names of the system, which means two systems with the same name have the same ID. Simply append `"##" .. i`, where `i` is the index of the system in the list to the label given to the button to fix.
