### ISSUE TITLE
Not all failed missions disappear from accepted missions list

### ISSUE THREAD

**Issue by tropicalpioneer** [pioneerspacesim/pioneer#5189]
### Observed behaviour
Been late for a couple Combat missions, I continued my adventures in other systems.
The two failed missions have stayed there for a month now. So I decided to visit one of them mission planet and see if anything happens, either mission still possible or a failure message makes it disappear.

Is there a way to make Combat failed missions disappear?
Saved game in attachment, when I came back in the "failed mission" orbit after a month.
[issue listed failed missions.zip](https://github.com/pioneerspacesim/pioneer/files/6489734/issue.listed.failed.missions.zip)

### Expected behaviour
A failed mission should be notified and disappear from the list of accepted missions.

### Steps to reproduce

__My pioneer version (and OS):__
20210205 
Mint Cinnamon 20.1

**Comment by tropicalpioneer** [comment]
Oh, when I left the system I received a message and the failed mission disappeared from listing.

I guess at the moment visiting late is the only way to delete them.

**Comment by Web-eWorks** [comment]
Closing this as subset of #5181.
