### ISSUE TITLE
Shadows

### ISSUE THREAD

**Issue by vlastan** [pioneerspacesim/pioneer#519]
Night time on planet cities results in buildings being very bright because of the sunlight not casting a shadow from the other side of the planet. So, a shadow system should fix thi issue and also give the visual a major quality boost (buildings should cast shadows too)

**Comment by mike-f1** [comment]
@impaktor : there already support for this in code... Close?

**Comment by impaktor** [comment]
Just support in code, or implemented in game?

Good with a reference to code, if the former.

(@Web-eWorks can close issues as well)

**Comment by mike-f1** [comment]
https://pioneerspacesim.net//carousel/in-flight.jpg
https://pioneerspacesim.net//carousel/ss5.png

**Comment by fluffyfreak** [comment]
We still don't have general shadows, only in specific situations do we have a sort of numerically calculated shadow for rings and eclipses. Everything else is just "shading" for lighting calculations which is something different.

**Comment by mike-f1** [comment]
> We still don't have general shadows [snip]

Yes, agreed: only far lights from stars... I'm just noting that the purpose of this issue is: 
> Night time on planet cities results in buildings being very bright because of the sunlight not casting a shadow from the other side of the planet

And that is no more true... Anyway, if you prefer keeping this open, isn't a problem...
I think our last comments will be useful for a reader in order to understand what's happens ["under the hood"](https://github.com/pioneerspacesim/pioneer/blob/b448714b8d409569726ecc6616a7403dc21373fe/src/Camera.cpp#L275).

**Comment by fluffyfreak** [comment]
Just in case anyone is interested in shadow mapping there was an attempt that I did: https://github.com/fluffyfreak/pioneer/tree/shadows

**Comment by fluffyfreak** [comment]
I got as far as rendering the shadowmap itself, but applying was a work in progress

**Comment by Web-eWorks** [comment]
Going to close this, as the original issue was about planets casting shadow volumes and not PSM / CSM shadowing. Ideally we'd like spotlights on ships et al. to cast believable shadows, but that's a task for another issue.

I'll open a replacement issue that better outlines the work to be done.
