### ISSUE TITLE
System mentioned in mission, not found in Sector Map

### ISSUE THREAD

**Issue by tropicalpioneer** [pioneerspacesim/pioneer#5190]
### Observed behaviour
EDIT: I finally could find the systems by entering coordinates in the serach field or by looking manually the _right_ coordinates. Thanks, guys.

ORIGINAL:
The system mentioned in a mission could not be found (Laorth).
BTW "Set destination as navigation target" button is missing in red triangle icon missions (feature request UI?).
![issue system not found Laorth mission-cropped](https://user-images.githubusercontent.com/84130826/118429960-87714900-b705-11eb-827f-9521d77a173b.jpg)
![Screenshot from 2021-05-17 11-51-21](https://user-images.githubusercontent.com/84130826/118430246-4463a580-b706-11eb-939a-217971bbe193.png)

![issue - system not found Laorth](https://user-images.githubusercontent.com/84130826/118429984-98ba5580-b705-11eb-99fd-bb54696e984f.png)

### Steps to reproduce

__My pioneer version (and OS):__
20210205
Mint Cinnamon 20.1

**Comment by tropicalpioneer** [comment]
Fafa system
![issue missing system Fafa](https://user-images.githubusercontent.com/84130826/118430835-8fca8380-b707-11eb-9788-75dfdc341c51.png)
![system not found fafa](https://user-images.githubusercontent.com/84130826/118430842-9658fb00-b707-11eb-8c2a-2a10a4ad4e1f.png)

**Comment by Web-eWorks** [comment]
The system exists, or it wouldn't be able to generate the actual mission text. Try zooming out in the sector map and searching again (the search results are pulled from the currently visible systems).
A savefile with the specific mission accepted would be *really* helpful to diagnose this one.

**Comment by tropicalpioneer** [comment]
I have overwritten that file, but I will add a savefile as soon as it happens again.

Meanwhile, I tried to reverse test what you write about zoom (out of curiosity): the search field still finds other systems even if I have zero fuel in cargo (so I don't have hyperjump range) and even if, in the Sector map, I have well zoomed in somewhere else from the searched system.

**Comment by impaktor** [comment]
Search on the coordinates instead.

**Comment by tropicalpioneer** [comment]
Nice to know I can type the coordinates!
I found Fafa system manually (in my previous post I had I looked up the wrong third coordinate : shame on me!)
Sorry about the false alarm.

I guess you can close this issue, not being a bug.
Shall I create a feature request in dev forum for adding the "Set destination as navigation target" button in red icon missions?
