### ISSUE TITLE
Cities are not always visible 

### ISSUE THREAD

**Issue by jimishol** [pioneerspacesim/pioneer#5198]
I observed the issue not always and mostly on earth cities. Perhaps because of the expectation for them to be.
I attach a save where on my hardware i had the issue 3 times in a row.

Search Sol and add it as jump/ You have enough fuel.
Ask permission to launch, jump, set autopilot to approach London, ask permission to land set autopilot for landing. During landing London is not visible. If you save at any point, exit the game and restart it by ./pioneer, London is vissible.
 
Download the save from 
https://drive.google.com/file/d/1ZsPBa8lsSazWKS3qo3jEhrQT_CGK4OUx/view?usp=sharing

**Comment by joonicks** [comment]
should be fixed by #4913
