### ISSUE TITLE
Buyable Trade Computer

### ISSUE THREAD

**Issue by CreepyStepdad** [pioneerspacesim/pioneer#520]
I know it is old-school to have to remember commodity prices for each system, but it is a giant pain in the posterior. I respectfully request a sci-fi update; the ability to have a purchasable upgrade that tracks the prices of each commodity for each station. I know this would be a lot of work, but it makes sense in the context, as well as adding a great deal of streamlining and efficiency to trading across the universe. For a futuristic trader with the latest tech onboard their flagship to have to jot down info in a paper journal seems anachronistic.

**Comment by impaktor** [comment]
We have the trade analyzer now. It does this, by colour coding the exports/imports compared between selected and current system.

**Comment by impaktor** [comment]
#3081 to be precise.
