### ISSUE TITLE
OpenGL Error on Windows 10 Home, probably font issues...

### ISSUE THREAD

**Issue by KamiruSan994** [pioneerspacesim/pioneer#5201]
Hello I just downloaded a game but sadly I can't even start it.

### Observed behaviour
Game don't want to open normally, I can hear music in a background but screen remains black, also opens windowed

### Steps to reproduce
Open game via Desktop Shortcut.

__My pioneer version (and OS):__
Pioneer 2021-02-03, Windows 10 Home
[output.txt](https://github.com/pioneerspacesim/pioneer/files/6567016/output.txt)
[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/6567017/opengl.txt)

**Comment by The-EG** [comment]
This sounds a lot like #5162. You can try the fix there:
> Try setting your AntiAliasingMode= line in config.ini to 0. The error appears to be happening because there's a difference between what Pioneer is requesting for the MSAA level and what the windowing system is giving it.

**Comment by The-EG** [comment]
Per Discord discussion, the fix from #5162 worked, this is a duplicate.
