### ISSUE TITLE
system overview screen. Translation, at least in greek, creates null fonts.

### ISSUE THREAD

**Issue by jimishol** [pioneerspacesim/pioneer#5213]
1) I tried, through transifex, to full translate the game in Greek.
The system overview screen is not recognize the Greek fonts. I 'm on tubleweed opensuse linux and i use utf-8 . I checked German and Russians and they works alright. I think that the Greek symbols  you see on screenshots are in their right position. In order to not look ugly i deleted about 50 translations of core module from transifex. So, in order to confirm, you need to write Greek letters by hand.

2) Another minor problem is that tombstone does not appear text, not only in Greek, but even in English if the string is larger, and in a case it seemed to me equal, than 'RIP OLD BEAN' string. It does not crop the text, it disappears it all.

3) I think that in 'Simulating evolution of the universe: {age} billion years ;-)' the last 2 symbols '-)' does not appear too.

The relative screenshots are
https://susepaste.org/29044116
https://susepaste.org/14952725
https://susepaste.org/69234246
Thank you

By the way, having capital letter delta Δ higher than the rest Greek letters look ugly.

**Comment by RacerBG** [comment]
About 2 and 3, I have the same problems in Bulgarian. The tombstone stays blank if I try to translate it into Bulgarian and the first few lines of "Simulating evolution of the universe" at least for me are a couple of "??????? ?????? ?????" characters.
