### ISSUE TITLE
ECM popup text is not informative

### ISSUE THREAD

**Issue by jimishol** [pioneerspacesim/pioneer#5215]
(Not really an issue)
When hovering mouse upon ECM button, popups the 'ECM' string. That is not a plus information concerning on that button and null information should cost zero bytes to produce. So, as a matter of principal, there should not exist a popup at all.
This popup string is defined as last string at 65 line of equipment.lua file, that is:

local size, clicked = iconButton(uiPos, icons[ecm.ecm_type], false, mainIconSize, "ECM", not player:IsECMReady(), mainBackgroundColor, mainForegroundColor, mainHoverColor, mainPressedColor, 'ECM')

If should exist a popup informative text, should not be 'ECM' because the label of button as 'ECM' gives that information already, but something different. My suggestion is to replace last 'ECM' with something like
'Activate', 'Activates electronic countermeasures', 'Electronic CounterMeasures', 'Start ECM', 'Implement ECM' and so on.

**Comment by zonkmachine** [comment]
I suggest "Electronic countermeasure" as it's used in the title of the wikipedia page.
https://en.wikipedia.org/wiki/Electronic_countermeasure

Maybe it should be possible to turn the tooltip off with an empty string if it's not needed? Now you get an empty small box in there. That would be better than repeating the text of the button.
