### ISSUE TITLE
Fast sequential hyperjumps may cause crash if police is scanning your cargo

### ISSUE THREAD

**Issue by jimishol** [pioneerspacesim/pioneer#5220]
This is how crash happened
1. jump to system  
2. immediately get scanned by police 
3. during scanning jump to new system already set in hyperjump planner
result of step 3 was a crash.
 
the output.txt says nothing. it is difficult to reproduce and all i have is what i see on terminal now, I post last lines

Struve 2398 B d:
    height fractal: HillsNormal
    colour fractal: Rock
    seed: 2549709410
Color Fractal name: GGSaturn
WARNING: ship varada discarded, because there are no hyperspace routes available for it
WARNING: ship deneb discarded, because there are no hyperspace routes available for it
DEBUG: Jumps since warranty: 0
Warranty expires: 20:30:44 23 Ιούλ 3222
0 clouds brought over
Stars picked from galaxy: 0
Final stars number: 140000
Started hyperspacing...
Fatal: [string "[T] @modules/PolicePatrol/PolicePatrol.lua"]:36: attempt to index field 'system' (a nil value)
stack traceback:
        [string "[T] @modules/PolicePatrol/PolicePatrol.lua"]:36: in function 'hasIllegalGoods'
        [string "[T] @modules/PolicePatrol/PolicePatrol.lua"]:159: in function <[string "[T] @modules/PolicePatrol/PolicePatrol.lua"]:157>

As in IRC suggested 'shouldn't crash even if jumping fast. That should be part of playing mechanics: "jump before police finish scanning".'

I will try to reproduce. I fast jumped many times and never experienced crashes. Today i decided to start new game on Barnard's star, i just bought my first hyperdrive 1 and it was my first hyperdrive jump sequence.

After closing windows output.txt filled up. So there ii is https://susepaste.org/36991731

**Comment by Gliese852** [comment]
@jimishol I think the problem is that activating the hyperdrive at the time of scanning leads to the collapse of the universe

**Comment by jimishol** [comment]
On my first RP request, because of my ignorance of how RP works, i unwillingly disturbed the peace of master branch multiple times for something simple. Because of my knowledge, that limits me only on trivial stuff, if you agree with my solution, please make a proper PR.
The crash can happen statistically few times, certainly below 50% on drivers class 1 (that probability decrease as class gets bigger), with zero probability for class 4  and above. That means it can happen only on early few gameplay hours because in the first few hours of play the player gets military or standard hyperdrive of class 4.

The crash can happen when police scan duration

(between 3nd-9th seconds of arrival https://github.com/pioneerspacesim/pioneer/blob/5bf422c9e713aa068abc668224d1db7775068c37/data/modules/PolicePatrol/PolicePatrol.lua#L157)

overlaps with time interval needed for the warmup of hyperdrives. We can assume that, in order to crash the game, the player clicks the jump button at 0th second of arrival. The duration of warmup is given in

https://github.com/pioneerspacesim/pioneer/blob/5bf422c9e713aa068abc668224d1db7775068c37/data/libs/EquipType.lua#L305

as 5+1.5*Hyperdive's_Class. So, for class 4, the jump will start at 11th second while police scan has finished maxed at 9th and no game crash occurs.
I played with police scan altered to 1th-5th second and i still had time to see the police scan message. But, since i like these messages on my gameplay, i reverted to 3-9 and, instead, i altered the warmup, for duration of 10sec and above. There is zero or totally insignificant impact in gameplay. Specially on large hyperdrive classes, on warmup procedure, i accelerate time to 10x, because i don't want to wait the whole 17seconds for example but not to 100x or more because i like to 'feel' this warmup process.

**I propose you to alter the number 5 to number 9 in the above 305 line.**

Technically the real impact on players like me is 4/10xacceleration=0.4 seconds per jump waste of time and only on the very few gameplay hours of new game starts. That means nothing. The bug is avoided and when you decide that the overlap is needed, then plan these two time intervals so as to intentionally overlap on all classes of hyperdives causing planed and proper vertical consequences.

(With vertical consequences i mean that a player should decide, independently of his wealth,  if he wants to escape or take his illegal action penalty. With horizontal consequences all players are equal and has equal penalties, so poor players always try to escape the police and the penalty of illegal cargo while wealthy players always chose to pay the penalty because their profit worth the penalties. This means that vertical consequences implies decision that adds interest and impact on gameplay life, in contrary to horizontal ones, where the logical decision is predetermined by the status of the player and adds nothing to gameplay life but only the necessity for someone to obey and accept his own fate, determined from his current gamelife status-cvo.)
