### ISSUE TITLE
Game crashes on arriving on system with News Event (resurrected)

### ISSUE THREAD

**Issue by jimishol** [pioneerspacesim/pioneer#5221]
I commented in https://github.com/pioneerspacesim/pioneer/issues/5173
I am afraid the bug resurrected.

https://drive.google.com/file/d/1kI1V0WHwCAngIsHYLxtgccMXcDOnBUZj/view?usp=sharing
Load the above file save
Read NEWS about Gliese 644
Full fuel and buy 1t for hyperdrive
Buy 2t of grain, Request launch and jump to Gliese 644 system.
Land to any station. Upon docking the output.txt must be similar to the following
https://susepaste.org/24168872

From the above save file, game crashed 3 times in a row, so i assume it crashes always.
If you do not open the news then all is ok and you get the 10xprice benefit, despite you didn't read the newspaper.

Trying to write the present, i played the exact above save_02 file and 4 times in a row the bug had gone. Game proceeded as expected. I decided not to fill new issue and continue my game. This time i loaded save_03 that created after game continuation from save_02 and before landing on stone_pad (i think, it is the nearest station), Upon docking game crashed. I reloaded save_03 and tried to dock to the same station just for the confirmation of the bug. The game continued without bug and crash. The randomness of crash makes me speechless. As soon as i manage to get the link of save_03 i will edit the present post with the public link.
Thank you.

The link to the above save_03 is https://drive.google.com/file/d/1X-4CvAIy3cqQpCvJ1Zqpwl-GQGX7_4AE/view?usp=sharing

**Comment by jimishol** [comment]
Today i saw a WANTED computers, where computer stock in station was zero. I did not opened sell option. I  traveled to nearby station and bought 2 computers because i have only Xylophis. Got back and forcefully i sold 1 computer. Upon selling the 2nd computer gamed crashed with 
Fatal: [string "[T] @modules/SoldOut/SoldOut.lua"]:20: attempt to index local 'ad' (a nil value)

**Comment by Web-eWorks** [comment]
Fixed in release 20220203.
