### ISSUE TITLE
Loading a save game corrupted Station Windows

### ISSUE THREAD

**Issue by SkinSz** [pioneerspacesim/pioneer#5231]
### Observed behaviour
Error Message using Station Screens

### Expected behaviour
After loading the save-file, station windows should work as usual

### Steps to reproduce
Unsure, what is the cause.

### Error Messages

See Output.txt
I gladly provide more information.
[output.txt](https://github.com/pioneerspacesim/pioneer/files/6879942/output.txt)

__My pioneer version (and OS):__
Windows 10
2021-07-23

Last Bug Free: May 2021

**Comment by SkinSz** [comment]
Strangely, saving the game again and re-loading fixes the issue

**Comment by Web-eWorks** [comment]
Duplicate of #5149; unfortunately this is a persistent and sometimes difficult to find bug.
