### ISSUE TITLE
Deprecated SPDX license identifiers

### ISSUE THREAD

**Issue by chenrui333** [pioneerspacesim/pioneer#5232]
👋  I noticed that the license header declarations are using the outdated the license identifier GPL v3. I would suggest to replace the license identifier with either `GPL-3.0-only` or `GPL-3.0-or-later` (see [here](https://spdx.org/licenses/) for details).

This is the license header reference:
> // Licensed under the terms of the GPL v3. See licenses/GPL-3.txt

---

relates to Homebrew/homebrew-core#81963

**Comment by Web-eWorks** [comment]
I appreciate the thought, but Pioneer does not use (and has never used, as far as I am aware) SDPX identifiers in any of its declarations; instead it prefers the use of human readable names. As far as the related issue goes, GPLv3-only is likely the best match for a downstream license declaration, though the project does also make use of files and modules under BSD-3-Clause, ZLib, and MIT licenses; such files are called out as needed in the appropriate headers.
