### ISSUE TITLE
System overview shows only the super giant star in a system which contains 47 major bodies

### ISSUE THREAD

**Issue by zookar** [pioneerspacesim/pioneer#5236]
### Observed behaviour
System overview shows only Zeja A in the Zeja(-13, -9, -13) system, which contains 47 major bodies.
Zeja A, a red hyper giant star, has a radius of 384.270 solar radii. 
Does the size of the star matter?

### Expected behaviour
System overview shows all the celestial bodies available in this star system.

### Steps to reproduce
Make sure your ship's landing gear is up and flying somewhere to avoid SAFETY_LOCKOUT.
Open the console in-game by pressing '`', and then copy the lua scripts below line by line into the console, press enter after each line
> path = require "SystemPath".New(-13,-9,-13,1)
> player = require "Game".player
> warmup = 1
> duration = 1
> sounds = {warmup = "Hyperdrive_Charge", abort = "Hyperdrive_Abort", jump = "Hyperdrive_Jump"}
> player:InitiateHyperjumpTo(path,warmup,duration,sounds)

### Attachments
![20210805182208](https://user-images.githubusercontent.com/23634092/128335349-9b09ec0b-b703-4526-bb8a-56e01b33c64a.png)

__My pioneer version (and OS):__
Pionneer version : ver 20210203 (142693b)
Os version : Windows 7 (6, 1, Build 7601)
Video resolution : 1920 * 1080

**Comment by nozmajner** [comment]
That screen will soon be replaced, because it is among (if not) the last screens using OldUI. The replacement does take this into account I believe. @Web-eWorks made some progress with this screen already if I'm correct.

**Comment by Bodasey** [comment]
old one to close with: #2985
