### ISSUE TITLE
System Overview is blank

### ISSUE THREAD

**Issue by Bodasey** [pioneerspacesim/pioneer#5244]
### Observed behaviour

System Overviev is blank / black screen without any information

### Steps to reproduce

- Start new game on whatever or load a game
- Switch to System Overviev

__My pioneer version (and OS):__
actual master (db12012)

Can you please check if there are Version incompatibilities in my new system? I had to install the devel packages for compiling again, but have got no error messages:
[incompatible.txt](https://github.com/pioneerspacesim/pioneer/files/7005401/incompatible.txt)

**Comment by Gliese852** [comment]
It should be so. This was done in #5156, the master is currently not fully functional.
In addition to this issue, a click on the star label is not processed in the sector map, and there are no faction labels. It will all be fixed in the near future.

**Comment by Bodasey** [comment]
Ok, I'll wait patiently and keep testing.

**Comment by Web-eWorks** [comment]
Closing this, `master` branch is purposefully missing a few features while their replacements are in the PR stage.
