### ISSUE TITLE
SDL does not find pulse audio

### ISSUE THREAD

**Issue by jimishol** [pioneerspacesim/pioneer#5246]
I am on rolling distribution opensuse tubleweed.

After some of the frequent system updates, i lost sound of the game with a line from output.txt that noted
Info: Could not initialize SDL Audio: Audio target 'pulse' not available.

In order to get sound back from now on i have to start game by
SDL_AUDIODRIVER=pulseaudio ./pioneer

### Expected behaviour
Start game by ./pioneer

__My pioneer version:__
Info: ver 20210823 (db12012b7)

**Comment by Web-eWorks** [comment]
Closing this as a downstream issue; this is either an issue with your specific system's configuration (possibly pulse-over-pipewire?) or your distribution's SDL package. At no point in the Pioneer code do we ever specify which audio device to open; that is entirely internal to SDL and your system's reported configuration.
