### ISSUE TITLE
out of stock "goods needed" mission crash

### ISSUE THREAD

**Issue by joonicks** [pioneerspacesim/pioneer#5254]
npc wanted 1t of robots, sold 1 by pressing "sell 1", then pressed "sell 1" again and BOOM back to desktop

__My pioneer version (and OS):__
git, windoze

**Comment by jimishol** [comment]
It same issue as https://github.com/pioneerspacesim/pioneer/issues/5251
Try to add the line
 form:Close()
as i suggested there, till someone fixes this.
It solved the issue for me.

**Comment by Web-eWorks** [comment]
Closing this issue as duplicate.
