### ISSUE TITLE
Game Crashes After Completing Cargo Run Mission

### ISSUE THREAD

**Issue by ghost** [pioneerspacesim/pioneer#5258]
### Observed behaviour
I had just destroyed two enemy ships as part of a cargo run mission and was docked at the Albert station in the Hotar system in order to receive my payment. The moment my ship docked and after the game had autosaved, the game froze and crashed without displaying any error message. I loaded the autosave and the game seemed to work fine until I switched time from paused to forward at speed x1.

I then loaded up a previous save from before I had completed the mission and repeated my actions (hyperspaced to Hotar, destroyed the two enemy ships, docked at Albert) and then saved the game. For a few seconds, the game seemed to work fine but then abruptly crashed like before. I then tried loading the save again multiple times, and each time the game successfully loaded the save but crashed once I unpaused time.

### Steps to reproduce
1) Load attached save file "save_before_bug".
2) Hyperspace to the Hotar system mentioned in the cargo run mission in "Missions".
3) Destroy the two enemy ships.
4) Dock at Albert station to receive mission reward.
5) Save the game.
6) At this point, the game may or may not crash after a few seconds (in my tests, it sometimes did not). Either way, close the game and reload the save you just created.
7) Unpause time. 

__My pioneer version (and OS):__
Game version: 2021-07-23
OS: Windows 10.0.19043 Build 19043

### Attached Files
[save_before_bug.zip](https://github.com/pioneerspacesim/pioneer/files/7112569/save_before_bug.zip)
[bugged_save.zip](https://github.com/pioneerspacesim/pioneer/files/7112570/bugged_save.zip)
[output.txt](https://github.com/pioneerspacesim/pioneer/files/7112571/output.txt)

**Comment by Gliese852** [comment]
Hmm, autopilot guides a non-existent ship around the planet?

```
Thread 1 "pioneer" received signal SIGSEGV, Segmentation fault.
Body::GetPositionRelTo (this=0x0, relToId=...) at ...pioneer/src/Body.cpp:144
144             Frame *frame = Frame::GetFrame(m_frame);
(gdb) bt
#0  Body::GetPositionRelTo (this=0x0, relToId=...) at ...pioneer/src/Body.cpp:144
#1  0x000055555571b6a2 in Body::GetPositionRelTo (this=<optimized out>, relTo=<optimized out>) at ...pioneer/src/Body.cpp:162
#2  0x000055555561a58b in AICmdFlyAround::TimeStepUpdate (this=0x55555ab30c20) at ...pioneer/src/ShipAICmd.cpp:1507
#3  0x00005555557af9dc in Ship::AITimeStep (this=0x55555ab326b0, timeStep=timeStep@entry=0.0166666675) at ...pioneer/src/Ship-AI.cpp:37
#4  0x00005555556fe5c2 in ShipController::StaticUpdate (this=0x55556a5ce6f0, timeStep=0.0166666675) at ...pioneer/src/ship/ShipController.cpp:11
#5  0x00005555556108d5 in Ship::StaticUpdate (this=0x55555ab326b0, timeStep=0.0166666675) at ...pioneer/src/Ship.cpp:1243
#6  0x000055555562f0d3 in Space::TimeStep (this=0x555561c23c70, step=step@entry=0.0166666675) at ...pioneer/src/Space.cpp:1016
#7  0x0000555555747a13 in Game::TimeStep (this=0x555565573250, step=step@entry=0.0166666675) at ...pioneer/src/Game.cpp:286
#8  0x00005555555dec43 in GameLoop::Update (this=0x555555d664f0, deltaTime=0.0301411562) at ...pioneer/src/Pi.cpp:945
#9  0x000055555595d994 in Application::Run (this=0x555555d66220) at ...pioneer/src/core/Application.cpp:157
#10 0x00005555555adda3 in main (argc=<optimized out>, argv=<optimized out>) at ...pioneer/src/main.cpp:186

```
