### ISSUE TITLE
Hyperjump cloud's halo is missing

### ISSUE THREAD

**Issue by jimishol** [pioneerspacesim/pioneer#5261]
![screenshot_halo_master](https://user-images.githubusercontent.com/5658995/133263930-5325ac07-ab9f-4f8d-accc-0adef6d798de.png)
![screenshot_halo_stable_20210723](https://user-images.githubusercontent.com/5658995/133263953-6d814862-afbe-4552-a244-7f9f0902652f.png)

I just cloned master branch. At least from db12012b723a80d0c21c605ab6dc645a8d15f694
I noticed that halo around hyperjumps' cloud is missing and that makes cloud to look like an artificial bright sphere.

I expected to see halo around hyperjumps' cloud as usual.

**Comment by Web-eWorks** [comment]
@jimishol before and after images are highly recommended in this case, as otherwise there's no way to validate the issue occurs on more than just your machine and confirm a regression.

**Comment by nozmajner** [comment]
The first image looks more like an error, like an alpha blending issue. I don't think we had it like that, maybe in the very early days.

**Comment by Web-eWorks** [comment]
Definitely a blending issue, thank you @jimishol for reporting with pictures! I'll toss that on the todo list, or someone who can read C++ can touch the code calling `make_circle_thing` to pass it an outer color with an alpha value of 0.
