### ISSUE TITLE
building uses different standards on Linux vs Windows

### ISSUE THREAD

**Issue by joonicks** [pioneerspacesim/pioneer#5265]
git builds at least seems to use C++11 for Linux builds but C++17 for Windows builds.

unknown to me if the different standards could cause issues, but from a developer viewpoint C++11 seems to allow things that cause very verbose warnings on Windows

possibly causing Windows developers to ignore all code warnings unless they are fatal (errors)

should be striving to compile clean without warnings on all platforms, but with this setup, Linux devs can (and have) add a plurality of Windows warnings without ever being aware of the issue

__My pioneer version (and OS):__
git, Winblows

**Comment by Web-eWorks** [comment]
All builds use `CXX_STANDARD 17` statically as a target-level property regardless of platform. (If you're still unsure, remember that std::string_view and std::variant are C++17 library features.) Linux builds allow the use of CXX extensions where needed, and MSVC has a *very* different set of default warnings than either GCC or Clang, leading to the warnings you're getting. The proper course of action here would be to *disable* certain warnings for MSVC, integer size truncation being the most egregious one that I can think of.

**Comment by joonicks** [comment]
the git builder doesnt, check the output: "CXX_STANDARD: 11"

I never thought Id hear "the proper .. action .. would be to disable .. warnings"

the whole of #5260 is to fix integer truncation warnings, not hide them
