### ISSUE TITLE
sectorview zoom out black screen

### ISSUE THREAD

**Issue by joonicks** [pioneerspacesim/pioneer#5273]
enter sectorview and zoom out
stars all disappear except for right under the F1..F4 buttons

![screenshot-20210921-154355](https://user-images.githubusercontent.com/14345157/134182196-b689c20a-4c99-4cd1-b496-bf039d6f6181.png)

__My pioneer version (and OS):__
git b719ede, 2021-09-21
winblowz x64

**Comment by Web-eWorks** [comment]
@Gliese852 have you noticed this behavior while working on sector view labels?

**Comment by Gliese852** [comment]
@Web-eWorks no. But something else is happening to me, not sure if related:

https://user-images.githubusercontent.com/18342621/134252690-4eef0ff5-2fba-4027-892d-c86f21da0320.mp4

**Comment by Web-eWorks** [comment]
@Gliese852 I'd double-check that either the tooltip might be accidentally writing to the depth buffer (you can run the game through RenderDoc to inspect that), or that the Lua variable that controls whether stars are rendered is being set to false due to the mouse being over a tooltip window.

**Comment by joonicks** [comment]
looks like a case of PEBKAC, cleared out old dll's and the problem disappeared
