### ISSUE TITLE
LuaConsole functions no longer available

### ISSUE THREAD

**Issue by joonicks** [pioneerspacesim/pioneer#5274]
somewhere along the way, it seems "LuaConsole::Register()" is no longer called
resulting in Console.AddLine being unavailabe & print() not being overloaded
lua now has no way (it seems?) of adding console/debug output.
there are plenty of print's in lua script but nothing shows in output.txt

__My pioneer version (and OS):__
git 2021-09-21
winblows x64

**Comment by Web-eWorks** [comment]
LuaConsole died a while ago due to nothing using its exports and the console system being rewritten. print() statements do log correctly to the system log, though I'll look into whether they're being propagated to output.txt

**Comment by Web-eWorks** [comment]
Can confirm `print()` logs correctly to the system log on platforms where `stdout` is available.

**Comment by joonicks** [comment]
@Web-eWorks ouch, hey. Being capable of debugging lua on windows is pretty importand to windows developers. unless you are now saying pioneer is a linux only game?

**Comment by laarmen** [comment]
Shouldn't the print() statements also log to the in-game console? From what
I understand it doesn't seem to work for @joonicks?

**Comment by Web-eWorks** [comment]
Updated my comment, forgot to mention that `print()` logs to output.txt and the in-game console as well as the system log (thought the PR was opened with the assumption that those worked correctly already).
