### ISSUE TITLE
Some issues around exiting the Lua console

### ISSUE THREAD

**Issue by zonkmachine** [pioneerspacesim/pioneer#5287]
### Observed behaviour

I open the Lua console with 'L' and exit it with 'Esc'.

When I 'Escape' out of the Lua Console it takes me to the Settings Menu if I was in the world view or if I'm in another view it brings me to the world view.

### Expected behaviour

I definitely think that Closing the Lua console shouldn't bring up the Settings Menu. I also think that it shouldn't bring you to the world view if you started somewhere else.

I think what's needed here is some more of the same tlc provided by @Web-eWorks in 493e258c52bd1f0a4795ee46954a011d9ada81cd

### Steps to reproduce

Enter the Lua console and exit it with the 'Esc' Key.

__My pioneer version (and OS):__

Ubuntu Mate 21.04 and 21.10
On master at 65c3784f0636b283ec15ba761daa0062e4f628c7

**Comment by impaktor** [comment]
Slightly related, if anyone want some heavy development tools, there's now a [write up](https://pioneerwiki.com/wiki/Development_Tools#Editor_integration) on the wiki by @Gliese852 on how to send lua code to the game from your code editor, to a running pioneer instance.
