### ISSUE TITLE
fuel consumption adversely affects gameplay

### ISSUE THREAD

**Issue by joonicks** [pioneerspacesim/pioneer#5294]
Leisure trip to Uranus: 2 minutes on maximum time acceleration
Return trip to Mars High: 7 minutes on maximum time acceleration
A third leg to anywhere without refueling would be unthinkable.
REAL TIME - minutes of GAME play with nothing to do other than seeing a number slowly ticking down.

Delta-v: People were too preoccupied with if they could to stop and think if they should.
"realism" proponents cling to delta-v as a benchmark of reality saying its too high.
But delta-v has no impact on gameplay whatsoever.

The Expanse is hailed as realistic, but they have way more delta-v than Pioneer.

Fuel tank is too big in proportion to cargo. Even filling up cargo 100% has no chance of refilling even half a tank of thruster fuel.

suggested changes:
* Remove all mentions of delta-v. Choose between making a game and a simulator. Having it both ways wont be good at either.
* Reduce thruster fuel to <10% of ship mass. Fuel mass wont significantly influence how many g's you can pull.
* Increase max g of ships again to reduce travel time in systems. Keeping g limits is fine due to "structural limitations of the hull"
* Vastly increase fuel efficiency to the point where player can run several trips on full acceleration without needing to refuel.

Its about time Pioneer allows players to freely travel around star systems without being hounded by cries of "ree-uh-lism!"

**Comment by fluffyfreak** [comment]
A large part of the point of Pioneer is to have that delta-V, slow transit times, good route planning. That is a lot of Pioneer's atmosphere. See this section of the wiki for example https://pioneerwiki.com/wiki/FAQ#What_is_Pioneer.3F

The engine has been forked and other games made from it a couple of times. Including one that made it to Steam (https://store.steampowered.com/app/291250/Jumpdrive/). Some of these focused on making the game more arcadey.

Mods/total-conversions of the game are welcome to change any of these things, and code submissions that enable greater flexibility or improve modding to support changes are also welcome.

Also this isn't an issue, this is a design discussion which should be done on the forum, not as an issue.

Pinging @nozmajner @impaktor @Web-eWorks just for visibility.

**Comment by fluffyfreak** [comment]
Also old sourcecode link to Paragon/Jumpdrive https://github.com/MeteoricGames/pioneer
