### ISSUE TITLE
OpenGL error on launch

### ISSUE THREAD

**Issue by Apollucas** [pioneerspacesim/pioneer#5297]
I get the following error when launching a freshly installed Pioneer (2021-07-23 release):

OpenGL error(s) during frame:
In function Graphics::OGL::TextureGL::TextureGL
On line 96
GL_INVALID_OPERATION

After closing the error the game launches with a black screen, playing background music and with a custom cursor. I'm unable to interact with the menu, though.
I'm running this on Windows 10 Home Edition.

I apologise if this isn't the right way to submit issues, I'm still very much new to GitHub.

**Comment by Apollucas** [comment]
[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/7317554/opengl.txt)
[output.txt](https://github.com/pioneerspacesim/pioneer/files/7317555/output.txt)
Here you go!

**Comment by fluffyfreak** [comment]
Strange, an nVidia 3050 is found and used on your laptop. That should be perfectly compatible. The drivers are up to date as well.

**Comment by fluffyfreak** [comment]
From doing a quick little dig this might be related to the multisampling.
If you open the file `config.ini`, which should be in the same place as `output.txt` and `opengl.txt` were, and change the line `AntiAliasingMode` to be `AntiAliasingMode=0` then run again please?

That should disable an anti-aliasing and avoid the code that uses an anti-aliased rendertarget.

Pinging @Web-eWorks for visibility.

**Comment by Apollucas** [comment]
> From doing a quick little dig this might be related to the multisampling. If you open the file `config.ini`, which should be in the same place as `output.txt` and `opengl.txt` were, and change the line `AntiAliasingMode` to be `AntiAliasingMode=0` then run again please?
> 
> That should disable an anti-aliasing and avoid the code that uses an anti-aliased rendertarget.
> 
> Pinging @Web-eWorks for visibility.

Yep, that did it! Thanks a lot, I hope this was useful to you guys as well!

**Comment by fluffyfreak** [comment]
@Web-eWorks might be worth adding a bit of code to try to create the rendertarget with AA and then fallback to disabling it if it fails?

**Comment by Web-eWorks** [comment]
I've already got code that checks for a failure and bails out... which clearly hasn't triggered here. Once I can reliably detect the bad framebuffer, it should be easy to work around the problem, yeah. Unfortunately I don't have a repro case on my available hardware for this one.

**Comment by fluffyfreak** [comment]
Closing this issue as it seems all others were resolved.
