### ISSUE TITLE
Game Crashes and/or freezes either randomly, when I press something, or when I Alt+Tab

### ISSUE THREAD

**Issue by ThiccCroissant** [pioneerspacesim/pioneer#5299]
### Observed behaviour
While I am playing the game will, without warning, crash or freeze without a heads up or warning.

__My pioneer version (and OS):__
Latest version of Pioneer downloaded from the KDE Discover app
OS: Arch Linux with KDE Plasma 
[output.txt](https://github.com/pioneerspacesim/pioneer/files/7368427/output.txt)
[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/7368428/opengl.txt)

**Comment by impaktor** [comment]
Closing as there's no new info. Please feel free to re-open, if any new info.
