### ISSUE TITLE
onCreateBB runs on already created bulletin boards

### ISSUE THREAD

**Issue by zonkmachine** [pioneerspacesim/pioneer#5305]
![crewforhire](https://user-images.githubusercontent.com/6368949/141050876-b306898e-3180-4d7d-8224-1af0ef86cc04.png)

### Observed behaviour

Since 721c4e22e89050e3f982b0fbd07ea8c14c339fdd (@Web-eWorks) there is a bug introduced that will leave multiple instances of the 'Crew for hire' ad. I think the multiple ads are a result of the `onCreateBB `event being triggered multiple times for the same station. There was another issue that went away with 721c4e2, where all the ads would disappear intermittently but the 'crew' one. That one did not involve `onCreateBB`.

### Steps to reproduce

Start a new game and observe the 'crew' add.
Restart and open the bulletin board. Repeat until things breaks...

I recommend a print statement to see when `onCreateBB` is running.

**Comment by impaktor** [comment]
@zonkmachine Could you please try this on our current master, as BBS has been revamped now.
(E.g. you can find linux and windows version from 9h ago [here](https://github.com/pioneerspacesim/pioneer/actions/runs/1700377830) )

**Comment by zonkmachine** [comment]
The issue is still there.

**Comment by impaktor** [comment]
OK, thanks. For reference, we're now at: 9adb8fdf9fc4aa170bc520236b759f176b2a5b95

**Comment by zonkmachine** [comment]
I poked the code some more but didn't get much further into the issue.
`createStationData()` is used two times in **data/libs/SpaceStation.lua** . It's the first instance that is being called when this happens.
https://github.com/pioneerspacesim/pioneer/blob/85b77d081bc019bdda4cb6034706041361e37bf0/data/libs/SpaceStation.lua#L843

**Comment by Web-eWorks** [comment]
I am completely unable to reproduce this bug on latest master. No combination of new game / save game and reloading has managed to produce a situation in which onCreateBB is called more than once for a station, and never for a station that already has saved data. If you can add more details (OS, git commit hash, a stack trace of the multiple times it's called through `print(debug.stacktrace())`), I can look into the issue, but I cannot find a way to reproduce it.

**Comment by zonkmachine** [comment]
> a stack trace of the multiple times it's called through `print(debug.stacktrace())`),

I'm not sure I follow here. When I added that print statement after **createStationData(dockedStation)**, I got this the second time I started with `continue game`:

```
Fatal: [string "[T] @libs/SpaceStation.lua"]:844: attempt to call field 'stacktrace' (a nil value)
stack traceback:
	[string "[T] @libs/SpaceStation.lua"]:844: in function 'cb'
	[string "[T] @libs/Event.lua"]:34: in function '?'
	[string "[T] @libs/Event.lua"]:185: in function <[string "[T] @libs/Event.lua"]:180>Fatal: Frame instance deletion outside 'DeleteFrame' [0]
terminate called after throwing an instance of 'fmt::v6::system_error'
  what():  cannot write to file: Bad file descriptor
Aborted (core dumped)
```

The core dump had no stack.

**Comment by zonkmachine** [comment]
> If you can add more details (OS, git commit hash

I'm on 18e3ddf78194e4b4b912838a45d489a726423ac6
My OS is Ubuntu Mate 22.04 (beta). I have updated Ubuntu since 20.04 with automatic upgrade. When I originally posted this issue I was on Ubuntu Mate 21.10 .

I'll try and compile this from a fresh clone of Pioneer.

**Comment by zonkmachine** [comment]
> I'll try and compile this from a fresh clone of Pioneer.

Nope, same. I may try a couple of other linux versions if I find the time.

**Comment by Web-eWorks** [comment]
I apologize, that should be debug.traceback instead of debug.stacktrace. Are you able to replicate this issue through manual save/load, or only through the Continue Game button with an initial autosave? (If the latter, that's extremely pertinent information that wasn't present - autosave is a feature I usually have turned off during development...)

**Comment by zonkmachine** [comment]
I haven't been able to reproduce this when closing from the menu but it's still there when closing through Alt+F4 and counting on autosave. After extensive testing it looks like it's fixed in https://github.com/pioneerspacesim/pioneer/pull/5456.
