### ISSUE TITLE
recent version of Pioneer not loading with settings/saved game from an older version

### ISSUE THREAD

**Issue by Trokinos** [pioneerspacesim/pioneer#5307]
Hello

Using window 10
Last i had played Pioneer was with a build from appveyor in Jluy 2019 , so coming back to it i downloaded the window artifact from there : https://github.com/pioneerspacesim/pioneer/actions/runs/1441905849

I noticed that after installing the game, when i launched it the game closed itself after a couple of seconds without reaching the main menu. After trying a few things without success i wondered if it was related to some settings or saved game from my run in 2019.
So i deleted the Pioneer folder that contained the settings and saved games located for me in "C:\Users\YourUSERName\Documents\" 
 
And from there Pioneer launched without any problem.

**Comment by impaktor** [comment]
Not sure this is a bug. We've "intentionally" broken the game a few times since 2019, I think.

**Comment by Trokinos** [comment]
I think it's more of a problem for returning players, as having old data will prevent the game to launch.  Maybe a notice somewhere in the readme about deleting the folder in case of having old data could be useful ?

**Comment by impaktor** [comment]
Feel free to add it to our FAQ on the wiki if it's not there already, under troubleshooting / technical guide.

**Comment by impaktor** [comment]
I've made a small edit to the FAQ.
