### ISSUE TITLE
System overview is blank

### ISSUE THREAD

**Issue by Trokinos** [pioneerspacesim/pioneer#5308]
Hello

using window 10 and the window artifact from there
https://github.com/pioneerspacesim/pioneer/actions/runs/1441905849

I noticed after going to Gliese 445 to deliver something and coming back to Sol that the system overview is completely black .
Closing the game and relaunching it , it is still devoid of what used to be there.

**Comment by impaktor** [comment]
This is known, as we're about to transition to an updated version of it.

Econ info and demographics info have moved to sectorview (F2) map ("__$__" button and '__i__' -button).

...so it's really mostly the overview of which stations are on which planet that's missing, and how large the bodies are in relation to each other.

I'll pin this issue until it's fixed, so people find this easily.
