### ISSUE TITLE
Vegetation and rocks on planets

### ISSUE THREAD

**Issue by vlastan** [pioneerspacesim/pioneer#531]
Pioneer planets should have some natural objects on them. It would be cool to implement a system that places objects depending on the type of terrain  (mountain= snowtree, forest=trees, desert= rocks)

Here are some models i've done:
http://dl.dropbox.com/u/9418121/vegetation.rar

Contains 4 type of trees and 2 rocks.

**Comment by impaktor** [comment]
@fluffyfreak I know you're working on this, so of interest to you?

**Comment by fluffyfreak** [comment]
Yeah I've used these for testing and have a downloaded copy of the file thanks.
@vlastan I don't know if you're still getting notifications but thanks for these models they've come in handy when I've been developing/testing stuff and might make it ingame one of these days!

Going to close this now as we don't really need to track it here, we have a Dev forum (http://pioneerspacesim.net/forum/) if you ever want to get involved a little again (@vlastan).
