### ISSUE TITLE
Lobby Menus and Commodity Menus giving error message when used and opened.

### ISSUE THREAD

**Issue by WhiteGinger1000** [pioneerspacesim/pioneer#5310]
Whenever I try to open up the lobby and put hydrogen into my ship on a space station, the game will through an error at me and make me unable to get any fuel. The same is done with the commodity page as well and every other comms page in a station are all blank. 

It is supposed to just open up the menus and allow me to trade and refuel my ship.

Dock at space station, click on comms, go to lobby, click on +1 or +10 for fuel. Presto, error message.

I have included the output.txt file along with a screenshot of the error message in the lobby menu.

__My pioneer version (and OS):__ 
I'm running the 20210723 version on Windows

[output.txt](https://github.com/pioneerspacesim/pioneer/files/7732260/output.txt)
![Base Profile Screenshot 2021 12 16 - 22 21 13 80](https://user-images.githubusercontent.com/96279532/146494111-7e012bc1-cd94-4e31-bcd8-62edded4c7d5.png)

**Comment by impaktor** [comment]
This works on current master, so I can not reproduce the problem.

**Comment by Web-eWorks** [comment]
Yeah, this issue was fixed with the changes to station restocking. It might be worth leaving open until we kick a new release though.

**Comment by Web-eWorks** [comment]
This issue has been fixed in the 20220203 release.
