### ISSUE TITLE
Question for the developers of Pioneer.

### ISSUE THREAD

**Issue by Henry111182** [pioneerspacesim/pioneer#5314]
So, I downloaded Pioneer off of Itch.io and thought that was the newest version, and of course, I booted the game. After some time, I made a full save that isn't just a blank slate anymore, and I had discovered that there are more newer versions, and when I booted the game, it said my save had errors! And I don't want to redo my entire save, but also, I don't want to leave the new features behind. Is there any way I can fix my save so I can play on the newest version?

**Comment by Bodasey** [comment]
I think most of these newer versions are test / developer versions, and so save format differs. To play your game on, please re-install the version you started playing with, maybe also delete config.ini and imgui.ini in the personal pioneer directory first.

**Comment by Henry111182** [comment]
Ok, thanks! I'll keep backups just in case though.

**Comment by Henry111182** [comment]
It didn't really do anything except make my window configuration default, but I do appreciate your help with this issue!

**Comment by Henry111182** [comment]
I didn't seem to work; I do appreciate your help though.

**Comment by impaktor** [comment]
@Henry111182 https://pioneerwiki.com/wiki/FAQ#Are_savegames_compatible_between_releases.3F
