### ISSUE TITLE
broken data for Deneb class ships

### ISSUE THREAD

**Issue by Bodasey** [pioneerspacesim/pioneer#5316]
### Observed behaviour

![Deneb_error](https://user-images.githubusercontent.com/60466586/148145249-a865a27b-0588-47e7-9ebd-29aedc22910d.png)

### Steps to reproduce
just start the program

__My pioneer version (and OS):__
actual master branch

Terminal output while starting the program:
CreateCollisionMesh for : (ac33)
CreateCollisionMesh for : (amphiesma)
CreateCollisionMesh for : (bluenose)
CreateCollisionMesh for : (bowfin)
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
CreateCollisionMesh for : (error)
CreateCollisionMesh for : (dsminer)
CreateCollisionMesh for : (kanara_civ)
CreateCollisionMesh for : (lodos)
CreateCollisionMesh for : (lunarshuttle)
CreateCollisionMesh for : (malabar)
CreateCollisionMesh for : (molamola)
CreateCollisionMesh for : (molaramsayi)
CreateCollisionMesh for : (natrix)
CreateCollisionMesh for : (nerodia)
CreateCollisionMesh for : (pumpkinseed)
CreateCollisionMesh for : (sinonatrix)
CreateCollisionMesh for : (skipjack)
CreateCollisionMesh for : (storeria)
CreateCollisionMesh for : (varada)
CreateCollisionMesh for : (vatakara)
CreateCollisionMesh for : (venturestar)
CreateCollisionMesh for : (wave)
CreateCollisionMesh for : (xylophis)

Terminal output while loading/starting a game:
CreateCollisionMesh for : (pumpkinseed_police)
CreateCollisionMesh for : (sinonatrix_police)
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
(Some lines with surface starport stuff)
models/ships/deneb/deneb_medhigh.dae:
Couldn't load file
Could not find model: deneb
WARNING: ship varada discarded, because there are no hyperspace routes available for it
WARNING: ship kanara_civ discarded, because there are no hyperspace routes available for it
WARNING: lowering ships flow by 0.76 for performance reasons

**Comment by nozmajner** [comment]
It works on my end. Just downloaded master and built.  (win10)
Can't make a screenshot from the game itself, because windows sandboxes the build for some reason, but here's one from the modelviewer:
![image](https://user-images.githubusercontent.com/4182678/148197326-d61098ae-a7ef-4766-9747-637e1b14d65d.png)
Could you try downloading the offending dae manually and copy it in it's place? Maybe the download got corrupted or something?
According to github the deneb files were not touched since 8 years.

**Comment by Bodasey** [comment]
Done so, same error messages
I get them also in all the other branches i have tested recently, so a download error is unlikely.

my pioneer runs on an OpenSuSE 15.3 OS under KDE, compiled with gcc 7.5.0

**Comment by nozmajner** [comment]
Odd, because I downloaded master today to see if it happens, and built (cmake in VS, on win10).  Downloaded as a zip, not via git.

**Comment by Bodasey** [comment]
Maybe these old file(s) simply have got incompatible with the latest version of java or somewhat else? I updated to OpenSuSE 15.3 in June.

Also, Deneb is the only ship class with a "medhigh" file.

(vatakara model files are in the malabar's directory)

**Comment by fluffyfreak** [comment]
Is the file actually there on your machine as `\data\models\ships\deneb\deneb_medhigh.dae`?
It certainly seems to be in master and was last modified 8 years ago! Holy cow I remember that being added 👴

**Comment by Bodasey** [comment]
deneb_medhigh.dae is here. (was always)

different colour is from single download nozmajner recommended to me

But what's the correct size of the file? I cannot see it's original size on the github server. And both produce the same error messages.

![deneb_medhigh dae_is_here](https://user-images.githubusercontent.com/60466586/148293361-587434a1-88d0-4566-8d96-3a953bbac866.png)

![Screenshot_20220105_224549](https://user-images.githubusercontent.com/60466586/148294151-bee7ed83-c11b-4162-86b5-70c9946daa63.png)

**Comment by fluffyfreak** [comment]
My local copy is 636KB

**Comment by Bodasey** [comment]
@fluffyfreak may you provide it here, please?

**Comment by fluffyfreak** [comment]
[deneb.zip](https://github.com/pioneerspacesim/pioneer/files/7824797/deneb.zip)

Here's the whole folder

**Comment by fluffyfreak** [comment]
You can also run pioneer in modelviewer mode with a command line like `pioneer -mv deneb` to get it to load straight into the modelviewer with the Deneb

**Comment by Bodasey** [comment]
Many thanks for all your help - but i only can return bad news (with fluffyfreak's files); must be something on my computer system

romaschw@localhost:~/pioneer-master> ./pioneer -mv deneb
[  1%] Built target profiler
[  2%] Built target lz4
[  3%] Built target fmt
[  5%] Built target pioneer-core
[  7%] Built target savegamedump
[ 70%] Built target pioneer-lib
[ 79%] Built target lua
[ 93%] Built target pioneer-lua
[ 93%] Built target glew
[ 95%] Built target imgui
[ 96%] Built target jenkins
[ 97%] Built target picodds
[ 98%] Built target modelcompiler
[100%] Built target unittest
[100%] Built target pioneer
--------------------
SDL Version (build) 2.0.8
SDL Version (dynamic) 2.0.8
SDL Versions match
SDL_image Version (build): 2.0.5
SDL_image Version (dynamic): 2.0.5
SDL_image Versions match
Assimp Version: 5.1.0
FreeType Version: 2.10.1
GLEW dynamic version: 2.0.0
--------------------

Warning: OpenGL error(s) during frame:
In function CreateRenderTarget
On line 1036
GL_INVALID_ENUM
Initialized OpenGL 3.1, with extensions, renderer
Created shader vtxColor (address=0x2a4abf0)
Initializing joystick subsystem.
Attempted to write uninitialized IniConfig. Did you forget to Read() first?font orbiteer:
- Orbiteer-Bold.ttf 1.000000
- DejaVuSans.ttf 1.200000
- wqy-microhei.ttc 1.000000
font pionillium:
- PionilliumText22L-Medium.ttf 1.000000
- DejaVuSans.ttf 0.928571
- wqy-microhei.ttc 1.000000
Created shader ui (address=0x2a47b10)
Created shader billboards (address=0x2a44af0)
Created shader shield (address=0x2a42ec0)
Loading model deneb...
Created shader multi (address=0x2a3fb30)
models/ships/deneb/deneb/deneb_medhigh.dae:
Couldn't load file
Could not load model deneb: models/ships/deneb/deneb/deneb_medhigh.dae:
Couldn't load file

_________________________


romaschw@localhost:~/pioneer-master> ./pioneer -mv deneb
[  1%] Built target profiler
[  2%] Built target lz4
[  3%] Built target fmt
[  5%] Built target pioneer-core
[  7%] Built target savegamedump
[ 70%] Built target pioneer-lib
[ 79%] Built target lua
[ 93%] Built target pioneer-lua
[ 93%] Built target glew
[ 95%] Built target imgui
[ 96%] Built target jenkins
[ 97%] Built target picodds
[ 98%] Built target modelcompiler
[100%] Built target unittest
[100%] Built target pioneer
--------------------
SDL Version (build) 2.0.8
SDL Version (dynamic) 2.0.8
SDL Versions match
SDL_image Version (build): 2.0.5
SDL_image Version (dynamic): 2.0.5
SDL_image Versions match
Assimp Version: 5.1.0
FreeType Version: 2.10.1
GLEW dynamic version: 2.0.0
--------------------

Warning: OpenGL error(s) during frame:
In function CreateRenderTarget
On line 1036
GL_INVALID_ENUM
Initialized OpenGL 3.1, with extensions, renderer
Created shader vtxColor (address=0x1762b80)
Initializing joystick subsystem.
Attempted to write uninitialized IniConfig. Did you forget to Read() first?font orbiteer:
- Orbiteer-Bold.ttf 1.000000
- DejaVuSans.ttf 1.200000
- wqy-microhei.ttc 1.000000
font pionillium:
- PionilliumText22L-Medium.ttf 1.000000
- DejaVuSans.ttf 0.928571
- wqy-microhei.ttc 1.000000
Created shader ui (address=0x175faa0)
Created shader billboards (address=0x175ca80)
Created shader shield (address=0x175ae50)
Loading model deneb...
Created shader multi (address=0x1757ac0)
models/ships/deneb/deneb/deneb_medhigh.dae:
Couldn't load file
Could not load model deneb: models/ships/deneb/deneb/deneb_medhigh.dae:
Couldn't load file

_______________________


romaschw@localhost:~/pioneer-master> ./pioneer -mv venturestar
[  1%] Built target profiler
[  2%] Built target lz4
[  3%] Built target fmt
[  5%] Built target pioneer-core
[  7%] Built target savegamedump
[ 70%] Built target pioneer-lib
[ 79%] Built target lua
[ 93%] Built target pioneer-lua
[ 93%] Built target glew
[ 95%] Built target imgui
[ 96%] Built target jenkins
[ 97%] Built target picodds
[ 98%] Built target modelcompiler
[100%] Built target unittest
[100%] Built target pioneer
--------------------
SDL Version (build) 2.0.8
SDL Version (dynamic) 2.0.8
SDL Versions match
SDL_image Version (build): 2.0.5
SDL_image Version (dynamic): 2.0.5
SDL_image Versions match
Assimp Version: 5.1.0
FreeType Version: 2.10.1
GLEW dynamic version: 2.0.0
--------------------

Warning: OpenGL error(s) during frame:
In function CreateRenderTarget
On line 1036
GL_INVALID_ENUM
Initialized OpenGL 3.1, with extensions, renderer
Created shader vtxColor (address=0x27e1a90)
Initializing joystick subsystem.
Attempted to write uninitialized IniConfig. Did you forget to Read() first?font orbiteer:
- Orbiteer-Bold.ttf 1.000000
- DejaVuSans.ttf 1.200000
- wqy-microhei.ttc 1.000000
font pionillium:
- PionilliumText22L-Medium.ttf 1.000000
- DejaVuSans.ttf 0.928571
- wqy-microhei.ttc 1.000000
Created shader ui (address=0x27de9b0)
Created shader billboards (address=0x27db990)
Created shader shield (address=0x27d9d60)
Loading model venturestar...
Created shader multi (address=0x27d69d0)
Created shader unlit (address=0x30ba360)
CreateCollisionMesh for : (venturestar)
venturestar_low.dae: missing UV coordinates
venturestar_low.dae: missing UV coordinates
venturestar_low.dae: missing Tangents and Bitangents coordinates
venturestar_low.dae: missing Tangents and Bitangents coordinates
venturestar_high.dae: missing UV coordinates
venturestar_high.dae: missing UV coordinates
venturestar_high.dae: missing Tangents and Bitangents coordinates
venturestar_high.dae: missing Tangents and Bitangents coordinates
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar.dae: no material Body_Hi_001, using material 1 instead
venturestar_shield.dae: no material DefaultMaterial, using material 1 instead
venturestar_shield.dae: no material DefaultMaterial, using material 1 instead
Group - venturestar
LOD
Group - 5
MatrixTransform - Scene
MatrixTransform - Venturestar_VeryLOW
StaticGeometry - sgMesh0
MatrixTransform - Cube
StaticGeometry - sgMesh1
Group - 350
MatrixTransform - Scene
MatrixTransform - decal_01
StaticGeometry - sgMesh0
MatrixTransform - decal_02
StaticGeometry - sgMesh1
MatrixTransform
Label3D
MatrixTransform
Label3D
MatrixTransform - GasBottles_002
StaticGeometry - sgMesh2
MatrixTransform - Cube_002
StaticGeometry - sgMesh3
MatrixTransform - Cube_005
StaticGeometry - sgMesh4
MatrixTransform - Cube_006
StaticGeometry - sgMesh5
MatrixTransform - Cube_007
StaticGeometry - sgMesh6
MatrixTransform - Wings_000
StaticGeometry - sgMesh7
MatrixTransform - Wings_009
StaticGeometry - sgMesh8
MatrixTransform - Wings_010
StaticGeometry - sgMesh9
MatrixTransform - Wings_011
StaticGeometry - sgMesh10
MatrixTransform - Wings_012
StaticGeometry - sgMesh11
MatrixTransform - Wings_013
StaticGeometry - sgMesh12
MatrixTransform - Wings_014
StaticGeometry - sgMesh13
MatrixTransform - Wings_015
StaticGeometry - sgMesh14
MatrixTransform - Engines_Hi_002
StaticGeometry - sgMesh15
MatrixTransform - Venturestar_Hi_001
StaticGeometry - sgMesh16
StaticGeometry - sgMesh17
Group - 1000
Group
MatrixTransform - Scene
MatrixTransform - Venturestar_Hi
StaticGeometry - sgMesh0
MatrixTransform - Engines_Hi
StaticGeometry - sgMesh1
MatrixTransform - GasBottles_HI
StaticGeometry - sgMesh2
MatrixTransform - Wings_001
StaticGeometry - sgMesh3
MatrixTransform - Wings_002
StaticGeometry - sgMesh4
MatrixTransform - Wings_003
StaticGeometry - sgMesh5
MatrixTransform - Wings_004
StaticGeometry - sgMesh6
MatrixTransform - Wings_005
StaticGeometry - sgMesh7
MatrixTransform - Wings_006
StaticGeometry - sgMesh8
MatrixTransform - Wings_007
StaticGeometry - sgMesh9
MatrixTransform - Wings_008
StaticGeometry - sgMesh10
MatrixTransform - Cube_004
StaticGeometry - sgMesh11
MatrixTransform - decal_01
StaticGeometry - sgMesh12
MatrixTransform - decal_02
StaticGeometry - sgMesh13
MatrixTransform
Label3D
MatrixTransform
Label3D
MatrixTransform - Cube_008
StaticGeometry - sgMesh14
MatrixTransform - Cube_003
StaticGeometry - sgMesh15
MatrixTransform - Cube_001
StaticGeometry - sgMesh16
Group
MatrixTransform - Scene
MatrixTransform - venturestar_shield
MatrixTransform - tag_camera
MatrixTransform - tag_camera_front
MatrixTransform - tag_camera_right
MatrixTransform - tag_camera_left
MatrixTransform - tag_camera_rear
MatrixTransform - tag_camera_top
MatrixTransform - tag_camera_bottom
MatrixTransform - tag_gunmount_0
MatrixTransform - tag_landing
Group - thrusters
MatrixTransform
Thruster - thruster_linear_main_right
MatrixTransform
Thruster - thruster_linear_main_left
MatrixTransform
Thruster - thruster_linear_retro_right1
MatrixTransform
Thruster - thruster_linear_retro_left1
MatrixTransform
Thruster - thruster_top_rear_right
MatrixTransform
Thruster - thruster_top_front_right
MatrixTransform
Thruster - thruster_top_front_left
MatrixTransform
Thruster - thruster_top_rear_left
MatrixTransform
Thruster - thruster_bottom_rear_right
MatrixTransform
Thruster - thruster_side_rear_right
MatrixTransform
Thruster - thruster_side_front_right
MatrixTransform
Thruster - thruster_side_front_left
MatrixTransform
Thruster - thruster_side_rear_left
MatrixTransform
Thruster - thruster_bottom_rear_right_001
MatrixTransform
Thruster - thruster_bottom_rear_right_002
MatrixTransform
Thruster - thruster_bottom_rear_right_003
MatrixTransform
Thruster - thruster_bottom_rear_right_004
MatrixTransform
Thruster - thruster_bottom_rear_right_005
MatrixTransform
Thruster - thruster_bottom_rear_right_006
MatrixTransform
Thruster - thruster_bottom_rear_right_007
MatrixTransform
Thruster - thruster_bottom_rear_right_008
MatrixTransform
Thruster - thruster_bottom_rear_right_009
MatrixTransform
Thruster - thruster_bottom_rear_right_010
MatrixTransform
Thruster - thruster_bottom_rear_right_011
MatrixTransform
Thruster - thruster_bottom_rear_right_012
MatrixTransform
Thruster - thruster_bottom_rear_right_013
MatrixTransform
Thruster - thruster_bottom_rear_right_014
MatrixTransform
Thruster - thruster_bottom_rear_right_015
MatrixTransform
Thruster - thruster_bottom_rear_right_016
MatrixTransform
Thruster - thruster_bottom_rear_right_017
MatrixTransform
Thruster - thruster_bottom_rear_right_018
MatrixTransform
Thruster - thruster_bottom_rear_right_019
MatrixTransform
Thruster - thruster_bottom_rear_right_020
MatrixTransform
Thruster - thruster_bottom_rear_right_021
MatrixTransform
Thruster - thruster_bottom_rear_right_022
MatrixTransform
Thruster - thruster_bottom_rear_right_023
MatrixTransform
Thruster - thruster_bottom_rear_right_024
MatrixTransform
Thruster - thruster_bottom_rear_right_025
MatrixTransform
Thruster - thruster_bottom_rear_right_026
MatrixTransform
Thruster - thruster_bottom_rear_right_027
MatrixTransform
Thruster - thruster_bottom_rear_right_028
MatrixTransform
Thruster - thruster_bottom_rear_right_029
MatrixTransform
Thruster - thruster_bottom_rear_right_030
MatrixTransform
Thruster - thruster_bottom_rear_right_031
MatrixTransform
Thruster - thruster_bottom_rear_right_032
MatrixTransform
Thruster - thruster_bottom_rear_right_033
MatrixTransform
Thruster - thruster_bottom_rear_right_034
MatrixTransform
Thruster - thruster_bottom_rear_right_035
MatrixTransform
Thruster - thruster_bottom_rear_right_036
MatrixTransform
Thruster - thruster_bottom_rear_right_037
MatrixTransform
Thruster - thruster_bottom_rear_right_038
MatrixTransform
Thruster - thruster_bottom_rear_right_039
MatrixTransform
Thruster - thruster_bottom_rear_right_040
MatrixTransform
Thruster - thruster_bottom_rear_right_041
MatrixTransform
Thruster - thruster_bottom_rear_right_042
MatrixTransform
Thruster - thruster_bottom_rear_right_043
MatrixTransform
Thruster - thruster_bottom_rear_right_044
MatrixTransform
Thruster - thruster_bottom_rear_right_045
MatrixTransform
Thruster - thruster_bottom_rear_right_046
MatrixTransform
Thruster - thruster_bottom_rear_right_047
MatrixTransform
Thruster - thruster_bottom_rear_right_048
MatrixTransform
Thruster - thruster_bottom_rear_right_049
MatrixTransform
Thruster - thruster_bottom_rear_right_050
MatrixTransform
Thruster - thruster_bottom_rear_right_051
MatrixTransform
Thruster - thruster_bottom_rear_right_052
MatrixTransform
Thruster - thruster_bottom_rear_right_053
MatrixTransform
Thruster - thruster_bottom_rear_right_054
MatrixTransform
Thruster - thruster_bottom_rear_right_055
MatrixTransform
Thruster - thruster_bottom_rear_right_056
MatrixTransform
Thruster - thruster_bottom_rear_right_057
MatrixTransform
Thruster - thruster_bottom_rear_right_058
MatrixTransform
Thruster - thruster_bottom_rear_right_059
MatrixTransform
Thruster - thruster_bottom_rear_right_060
MatrixTransform
Thruster - thruster_bottom_rear_right_061
MatrixTransform
Thruster - thruster_bottom_rear_right_062
MatrixTransform
Thruster - thruster_bottom_rear_right_063
MatrixTransform
Thruster - thruster_bottom_rear_right_064
MatrixTransform
Thruster - thruster_bottom_rear_right_065
MatrixTransform
Thruster - thruster_bottom_rear_right_066
MatrixTransform
Thruster - thruster_bottom_rear_right_067
MatrixTransform
Thruster - thruster_bottom_rear_right_068
MatrixTransform
Thruster - thruster_bottom_rear_right_069
MatrixTransform
Thruster - thruster_bottom_rear_right_070
MatrixTransform
Thruster - thruster_bottom_rear_right_071
MatrixTransform
Thruster - thruster_bottom_rear_right_072
MatrixTransform
Thruster - thruster_bottom_rear_right_073
MatrixTransform
Thruster - thruster_bottom_rear_right_074
MatrixTransform
Thruster - thruster_bottom_rear_right_075
Group - navlights
MatrixTransform - navlight_red
MatrixTransform - navlight_green
MatrixTransform - navlight_green_001
MatrixTransform - navlight_red_002
MatrixTransform - navlight_002
MatrixTransform - navlight_001
MatrixTransform - navlight_000
MatrixTransform - navlight_003
MatrixTransform - navlight_004
MatrixTransform - navlight_005
MatrixTransform - navlight_006
MatrixTransform - navlight_007
MatrixTransform - navlight_008
MatrixTransform - navlight_009
MatrixTransform - navlight_010
MatrixTransform - navlight_011
MatrixTransform - navlight_012
MatrixTransform - navlight_013
MatrixTransform - navlight_014
MatrixTransform - navlight_015
CollisionGeometry
Group - Shields
MatrixTransform - 0_accMtx4
StaticGeometry - sgMesh0
LOD 1
Nodes: 7
Geoms: 2 opaque, 0 transparent
Triangles: 92

LOD 2
Nodes: 41
Geoms: 16 opaque, 2 transparent
Triangles: 6169

LOD 3
Nodes: 44
Geoms: 15 opaque, 2 transparent
Triangles: 8858

Materials: 1
Collision triangles: 92

**Comment by Bodasey** [comment]
Many thanks for all your help - but i only can return bad news (with fluffyfreak's files); must be something on my computer system
Terminal output is in the text file because of github's text autoformat function (someone can tell me how to switch off, please?)

[modelviewer_terminal.txt](https://github.com/pioneerspacesim/pioneer/files/7824989/modelviewer_terminal.txt)

**Comment by Web-eWorks** [comment]
@Bodasey try overwriting your deneb.model file with https://github.com/pioneerspacesim/pioneer/raw/master/data/models/ships/deneb/deneb.model. It appears to be searching one layer too deep (`data/models/ships/deneb/deneb/deneb_medhigh.dae`).

**Comment by Bodasey** [comment]
rule 1: Don't test when you are too tired.
rule 2: Nothing is better when fully awaken again...

...you can move any ship model files to an additional subdirectory without effect; Vatakara model files are in the Malabar's directory, and both Venturestar and Vatakara load correctly to my modelviewer.
![venturestar_double_directory](https://user-images.githubusercontent.com/60466586/148535231-342667bd-1d86-4f96-af77-c2349ad5286a.png)

![Malabar](https://user-images.githubusercontent.com/60466586/148536427-598b9ee4-9868-4b18-892d-102c2f2676ba.png)


Deneb is also not displayed in the July stable provided by openSuSE package manager.

**Comment by Bodasey** [comment]
something really required missing or incompatible?
[installation_check.txt](https://github.com/pioneerspacesim/pioneer/files/7828609/installation_check.txt)

**Comment by Bodasey** [comment]
SUCCESS!!!!

I compiled pioneer-master with libassimp/assimp-devel 3.3.1 again, and Deneb ships are back!

Wish you all a relaxed week-end!

**Comment by fluffyfreak** [comment]
Glad you got it working!

**Comment by nozmajner** [comment]
I should reexport it though, if it errors out on some assimp versions, like in the case of that SuSE package manager. Just to be safe.
