### ISSUE TITLE
compiler warnings i get

### ISSUE THREAD

**Issue by Bodasey** [pioneerspacesim/pioneer#5317]
with actual master branch
windows compiler never have seen them?

[compiler_warnings.txt](https://github.com/pioneerspacesim/pioneer/files/7814348/compiler_warnings.txt)
same text, looks better in an editor's font

_______________________

make[2]: Verzeichnis „/home/romaschw/pioneer-master/build“ wird betreten
[ 14%] Building CXX object src/core/CMakeFiles/pioneer-core.dir/Application.cpp.o
/home/romaschw/pioneer-master/src/core/Application.cpp: In member function ‘void Application::Run()’:
/home/romaschw/pioneer-master/src/core/Application.cpp:196:14: warning: unused variable ‘profileReset’ [-Wunused-variable]
   const bool profileReset = (m_activeLifecycle && !m_activeLifecycle->m_profilerAccumulate);
              ^~~~~~~~~~~~
[ 15%] Building CXX object src/core/CMakeFiles/pioneer-core.dir/GZipFormat.cpp.o

_______________________

[ 26%] Building CXX object CMakeFiles/pioneer-lib.dir/src/GasGiant.cpp.o
[ 27%] Building CXX object CMakeFiles/pioneer-lib.dir/src/GasGiantJobs.cpp.o
In file included from /home/romaschw/pioneer-master/src/GasGiant.cpp:21:0:
/home/romaschw/pioneer-master/contrib/vcacheopt/vcacheopt.h: In member function ‘void GasPatchContext::Init()’:
/home/romaschw/pioneer-master/contrib/vcacheopt/vcacheopt.h:33:7: warning: ‘<anonymous>.TVertexCacheData<unsigned int, 2147483647>::calculated’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 class TVertexCacheData
       ^~~~~~~~~~~~~~~~
[ 27%] Building CXX object CMakeFiles/pioneer-lib.dir/src/GeoPatch.cpp.o
[ 27%] Building CXX object CMakeFiles/pioneer-lib.dir/src/GeoPatchContext.cpp.o
[ 27%] Building CXX object CMakeFiles/pioneer-lib.dir/src/GeoPatchID.cpp.o
[ 28%] Building CXX object CMakeFiles/pioneer-lib.dir/src/GeoPatchJobs.cpp.o
[ 28%] Building CXX object CMakeFiles/pioneer-lib.dir/src/GeoSphere.cpp.o
In file included from /home/romaschw/pioneer-master/src/GeoPatchContext.cpp:12:0:
/home/romaschw/pioneer-master/contrib/vcacheopt/vcacheopt.h: In static member function ‘static void GeoPatchContext::GenerateIndices()’:
/home/romaschw/pioneer-master/contrib/vcacheopt/vcacheopt.h:33:7: warning: ‘<anonymous>.TVertexCacheData<unsigned int, 2147483647>::calculated’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 class TVertexCacheData
       ^~~~~~~~~~~~~~~~
[ 28%] Building CXX object CMakeFiles/pioneer-lib.dir/src/HudTrail.cpp.o
[ 29%] Building CXX object CMakeFiles/pioneer-lib.dir/src/HyperspaceCloud.cpp.o
[ 29%] Building CXX object CMakeFiles/pioneer-lib.dir/src/Input.cpp.o
[ 29%] Building CXX object CMakeFiles/pioneer-lib.dir/src/InputBindings.cpp.o

________________________

[ 55%] Building CXX object CMakeFiles/pioneer-lib.dir/src/pigui/ModelSpinner.cpp.o
[ 55%] Building CXX object CMakeFiles/pioneer-lib.dir/src/pigui/PerfInfo.cpp.o
[ 56%] Building CXX object CMakeFiles/pioneer-lib.dir/src/pigui/PiGui.cpp.o
/home/romaschw/pioneer-master/src/pigui/PerfInfo.cpp: In member function ‘PiGui::PerfInfo::CounterInfo& PiGui::PerfInfo::GetCounter(PiGui::PerfInfo::CounterType)’:
/home/romaschw/pioneer-master/src/pigui/PerfInfo.cpp:115:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
[ 56%] Building CXX object CMakeFiles/pioneer-lib.dir/src/pigui/PiGuiRenderer.cpp.o
[ 56%] Building CXX object CMakeFiles/pioneer-lib.dir/src/pigui/PiGuiSandbox.cpp.o
[ 56%] Building CXX object CMakeFiles/pioneer-lib.dir/src/pigui/PiGuiView.cpp.o

_______________________

[ 96%] Building CXX object src/lua/CMakeFiles/pioneer-lua.dir/PropertyMap.cpp.o
[ 97%] Building CXX object src/lua/CMakeFiles/pioneer-lua.dir/core/Import.cpp.o
[ 97%] Building CXX object src/lua/CMakeFiles/pioneer-lua.dir/core/Sandbox.cpp.o
/home/romaschw/pioneer-master/src/lua/core/Sandbox.cpp: In function ‘void pi_lua_stacktrace(lua_State*)’:
/home/romaschw/pioneer-master/src/lua/core/Sandbox.cpp:398:7: warning: unused variable ‘status’ [-Wunused-variable]
   int status = lua_getinfo(l, "Sln", &entry);
       ^~~~~~
[ 97%] Linking CXX static library libpioneer-lua.a
make[2]: Verzeichnis „/home/romaschw/pioneer-master/build“ wird verlassen
[ 97%] Built target pioneer-lua

_______________________

romaschw@localhost:~/pioneer-refuel> gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-suse-linux/7/lto-wrapper
OFFLOAD_TARGET_NAMES=hsa:nvptx-none
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,ada,go --enable-offload-targets=hsa,nvptx-none, --without-cuda-driver --enable-checking=release --disable-werror --with-gxx-include-dir=/usr/include/c++/7 --enable-ssp --disable-libssp --disable-libvtv --disable-libcc1 --disable-plugin --with-bugurl=https://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --with-slibdir=/lib64 --with-system-zlib --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-version-specific-runtime-libs --with-gcc-major-version-only --enable-linker-build-id --enable-linux-futex --enable-gnu-indirect-function --program-suffix=-7 --without-system-libunwind --enable-multilib --with-arch-32=x86-64 --with-tune=generic --build=x86_64-suse-linux --host=x86_64-suse-linux
Thread model: posix
gcc version 7.5.0 (SUSE Linux)

**Comment by Web-eWorks** [comment]
In order:
1. enable profiling build
2. external library, wontfix
3. hacky code, on the list to refactor at some point but not worth the effort right now
4. benign warning

Unused variable warnings aren't particularly of interest except when refactoring a function and are entirely harmless - most of them stem from the code using the variable only being enabled in debug or profiling mode. The one control-reaches-end-of-function is only used by code in the same module and covers all input cases. Thanks for reporting, although we see most of these pretty often doing local builds ourselves and there's nothing that's really "an issue" here.
