### ISSUE TITLE
Buying or switching ships crashes the game

### ISSUE THREAD

**Issue by nozmajner** [pioneerspacesim/pioneer#5322]
### Observed behaviour
Switching to any ship either by buying one, using the debug menu or using the console leads to a crash.
Two of this exact error message pops up:
![image](https://user-images.githubusercontent.com/4182678/149619377-817bacf8-62d3-45f4-af87-799feca90946.png)

### Steps to reproduce
Buy any ship, or switch to them with the above methods.

__My pioneer version (and OS):__
Win10 20220115 master

**Comment by impaktor** [comment]
I guess when switching ship, the `self.ship` variable becomes confused (is nil), when the refresh runs. I'm not familiar with how this code is supposed to run, or how often, but maybe a trivial fix.

```lua
function EquipmentWidget:refresh()
	self.selectedEquip = nil
	self.selectedEquipSlots = nil

	local shipDef = ShipDef[self.ship.shipId]    # offending line
	self.modelSpinner:setModel(shipDef.modelName, self.ship:GetSkin(), self.ship.model.pattern)
	self.modelSpinner.spinning = false
end
```
