### ISSUE TITLE
Orbit View display errors

### ISSUE THREAD

**Issue by nozmajner** [pioneerspacesim/pioneer#5329]
Edit: seems like #5326 fixes this issue.

### Observed behaviour
The Orbital map shows the moons and stations and such in the wrong places, and planet/star ball seems to be the wrong size. And the ball also disappears on double-clicking any body.
And when you double-click a body, it does not get centered, and the RMB menü centering does not work either.
And double-clicking any planet, including the Sun moves the Sun around.
Seems to be a map only issue, the planets don't go around actually.

![image](https://user-images.githubusercontent.com/4182678/150602452-5f932fa3-b69d-45c9-8453-1ca7920ccac0.png)
![image](https://user-images.githubusercontent.com/4182678/150602661-06348bb6-6f9d-4b86-9b64-8d5cd90e8d08.png)
![image](https://user-images.githubusercontent.com/4182678/150604883-b3a5e5bd-c389-40c9-b01b-23d9a0732fdc.png)

[Youtube video](https://www.youtube.com/watch?v=kd5I7JQqBO8)

### Steps to reproduce
Start the game. Open the orbit map. Double-click any body or try RMB/Center.

__My pioneer version (and OS):__
Master 2022-01-21 built as release, Win10.

**Comment by Web-eWorks** [comment]
I have absolutely no idea how I broke it, but mea culpa... I figured there would be a few bugs, but given the extensive amount of testing from I wasn't expecting something on this scale. My guess is it's another uninitialized memory issue cropping up on Windows.
