### ISSUE TITLE
Sound not working on Pioneer 020322

### ISSUE THREAD

**Issue by EpsilonEridani** [pioneerspacesim/pioneer#5338]
I have reinstalled the game 5 times and the sound will still not work, sound effects and music should be playing. The volume and sound on my computer is functioning normally but I hear no audio when I launch Pioneer

### Steps to reproduce:
I have no idea how this has happened, I got a new laptop that can run Pioneer on 100+ FPS on very high settings.

My pioneer version (and OS): 030222 and Win 10

**Comment by impaktor** [comment]
There's almost zero information here for us to work with, we need to know drivers, hardware, etc.

> When having problems with graphics, or pioneer not starting/crashing, please attach the files output.txt and opengl.txt from the pioneer [config folder](http://pioneerwiki.com/wiki/FAQ#Where_is_the_configuration_file.2C_saved_games.2C_screenshots.3F) in your home folder / My Documents folder. If you didn't get the output.txt file, then make sure RedirectStdio=1 in config.ini.

https://pioneerwiki.com/wiki/FAQ#How.2Fwhere_do_I_report_my_bug.2Fcrash

**Comment by Web-eWorks** [comment]
Confirmed on IRC as unrelated driver bug.
