### ISSUE TITLE
Mac compatible?

### ISSUE THREAD

**Issue by ninonook1** [pioneerspacesim/pioneer#5344]
Hi, I own a macOS and I have been having a hard time finding the download for that version on both here and the cite, could you point me in the right direction. thanks!

**Comment by impaktor** [comment]
https://pioneerwiki.com/wiki/FAQ#Where_is_the_Mac_version.3F

...there are old versions for Mac on sourceforge, see FAQ a few questions further down

**Comment by ninonook1** [comment]
ah, well I hope there will be a mac version for the more modern version, Thank you for letting me know!
