### ISSUE TITLE
Multiple stations around one planet display in wrong order on system overview screen

### ISSUE THREAD

**Issue by Keeper1st** [pioneerspacesim/pioneer#5350]
### Observed behaviour
In the new system overview screen, if a planet has multiple stations orbiting it, they are displayed in the wrong order on the graphical depiction. I'm assuming it happens in every such instance but I only have Earth to look at for example. The three stations in orbit between Earth and Moon are shown with the closest, Torvalds Platform, third from the top, making it seem like it's farthest from Earth when in fact it is the closest.

### Expected behaviour
Like moons, stations whose orbits are between a planet and the next orbiting body should display in order of closest to furthest.

### Steps to reproduce
Open the system overview in Sol. The list on the left pane will show the stations in correct order with Torvalds Platform first (Jobs Pad and Gates Spaceport share the same distance so their order is arbitrary), but the graphical overview shows Torvalds Platform farthest away from Earth of the three.

__My pioneer version (and OS):__
64-bit Windows executable built from master February 18, 2022.

**Comment by nozmajner** [comment]
I think it is because it uses the order from the system file, not the actual distance. I suspect it should not occur with generated systems.
