### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by shoulderpad-Gamer** [pioneerspacesim/pioneer#5352]
### Observed behavior
![start up broken](https://user-images.githubusercontent.com/100243724/155234379-0e4f614c-36fa-4806-bb41-377a2e893ff3.png)
the start up don't ask me where to put the files, then it shows this and closes

### Steps to reproduce

__My pioneer version (and OS):__

**Comment by shoulderpad-Gamer** [comment]
never mind i went into control panel and uninstalled the old file

**Comment by Gliese852** [comment]
Solved!
