### ISSUE TITLE
If you buy then sell a shield energy booster shields will stop recharging completely

### ISSUE THREAD

**Issue by aladar4** [pioneerspacesim/pioneer#5356]
### Observed behaviour
If you buy then sell a shield energy booster, shields will stop recharging completely. This seems the same as issue #5348 with lasers and lasers cooling boosters.

### Expected behaviour
Your shields should recharge even if you don't have your shield energy booster anymore.

### Steps to reproduce
- Buy a shield energy booster
- Sell it
- Launch
- Go scrape something to lose some shield power
- Shields won't recharge anymore
I'll attach a zipped savefile where you can try this.

20220203 Win 7

[shields_booster_issue.zip](https://github.com/pioneerspacesim/pioneer/files/8191707/shields_booster_issue.zip)

**Comment by impaktor** [comment]
I'm guessing it's the same underlying bug as: #5348

**Comment by Spaceplone** [comment]
the behavior seems to also happen if you sell a ship with shield boosters equipped  and put shields in the new ship
