### ISSUE TITLE
Landing gear inoperable with HUD off

### ISSUE THREAD

**Issue by Keeper1st** [pioneerspacesim/pioneer#5357]
### Observed behaviour
Player can not operate the landing gear when the HUD is in the off state. F6 key does nothing. Player can otherwise fly the ship, operating all thrusters.

### Expected behaviour
Player should be able to operate the landing gear in any mode in which ship controls are active. (Ideally the landing gear command should be bindable, for that matter, like any other ship control.)

### Steps to reproduce
Launch from a station, raise landing gear. Fly toward another station. Click the HUD mode button twice to turn off the HUD (apart from the location information in the corner). Approach for a badass no-HUD landing. Press F6. Realize nothing happened. Panic. Turn HUD back on. Press F6 and landing gear finally operates, but too late. Crash. Die.

**Comment by Web-eWorks** [comment]
CC @Gliese852, I'm sure this will be a fairly easy fix with the work you're doing on binding the GUI to inputs and vice versa.

**Comment by Keeper1st** [comment]
Camera switching with the F1 key also appears to be disabled with the HUD turned off, by the way.
