### ISSUE TITLE
Bulletin board entries become unclickable after loading game

### ISSUE THREAD

**Issue by loveaabb** [pioneerspacesim/pioneer#5358]
### Observed behaviour
After loading a game saved at a spaceport, all entries displayed on the bulletin board are unclickable (grey colored). The bulletin board turns normal after landing a second time at the spaceport (which causes landing fee deduction :( ).

### Expected behaviour
Available bulletin board entries be clickable in any time

### Steps to reproduce
1. Land at a spaceport
2. Save the game
3. Load the game you just saved
4. turn to the bulletin board

__My pioneer version (and OS): 20220203; Windows 10 Pro x64__

**Comment by impaktor** [comment]
Have you un-paused the game?

**Comment by loveaabb** [comment]
> Have you un-paused the game?

OMG... that explains it.
Thank you so much... I'll close this issue right away

**Comment by impaktor** [comment]
@loveaabb anyway, thanks for reporting
