### ISSUE TITLE
Beam weapons show target leading indicator despite being hitscan

### ISSUE THREAD

**Issue by RundownRhino** [pioneerspacesim/pioneer#5360]
### Observed behaviour
Beam lasers show a target leading indicator like that of pulse lasers, which is completely wrong - since they are hitscan, one should instead aim directly at the enemy.
Moreover, the target leading indicator has aim assist. This is not only further misleading, but also makes it impossible to hit the enemy if the target leading indicator is close enough to their ship - the aim assist will steal the shots, even if you are aiming directly at the target.

### Expected behaviour
Beam lasers either shouldn't have a leading indicator at all, or, better, have it exactly align with the target.

### Steps to reproduce
Use a beam laser, such as the `1MW beam laser`, on an enemy, and compare results from shooting directly vs on the leading indicator.

### Notes
The likely cause of this bug is that beam weapons [still have](https://github.com/pioneerspacesim/pioneer/blob/master/data/libs/Equipment.lua#L331) a `speed` attribute - exactly equal to that of pulse lasers in fact, 1km/s:
```lua
laser.beamlaser_1mw = LaserType.New({
	l10n_key="BEAMLASER_1MW", price=2400, capabilities={mass=3},
	slots = {"laser_front", "laser_rear"}, laser_stats = {
		lifespan=8, speed=1000, damage=1500, rechargeTime=0.25, length=10000,
```
 On beam lasers, [that attribute is not used for shooting](https://github.com/fluffyfreak/pioneer/blob/master/src/FixedGuns.cpp#L202-L207):
 ```cpp
		if (m_gun[num].projData.beam) {
			Beam::Add(b, m_gun[num].projData, pos, b->GetVelocity(), dir);
		} else {
			const vector3d dirVel = m_gun[num].projData.speed * dir;
			Projectile::Add(b, m_gun[num].projData, pos, b->GetVelocity(), dirVel);
		}
 ```
It is however [still used for target leading](https://github.com/fluffyfreak/pioneer/blob/master/src/FixedGuns.cpp#L250-L251):
```cpp
	// calculate firing solution and relative velocity along our z axis
	double projspeed = m_gun[num].projData.speed;
```

As such, perhaps setting the `speed` of beam weapon projectiles to something appropriately high, like `299792458`, would fix it.

__My pioneer version (and OS):__
Pioneer version: 2022-02-03 Release (9c06c9f)
OS: Linux Mint 20.3 Cinnamon

**Comment by RundownRhino** [comment]
[Another related issue](https://github.com/pioneerspacesim/pioneer/blob/427e4f9a81ee7b25d6c583ebb0e987550e191edf/src/FixedGuns.h#L48) which I didn't confirm in-game: 
```cpp
inline float GetGunRange(int idx) const { return m_gun[idx].projData.speed * m_gun[idx].projData.lifespan; };
```
This method assumes the range is speed times lifespan. For beam lasers, this is incorrect; their range is just their `length`. For existing beam lasers that should lead to the range being calculated as 8km while the actual value is 10km - a small enough discrepancy to not be obvious.

**Comment by azieba** [comment]
There is 1.5 deg aim assist. I removed the lead component for beams and kept the target position component for the assist and the result is deadly :laughing: You basically hit all the time if you have the target near the reticule. Maybe the aim assist should be turned off entirely for beam weapons..

**Comment by Web-eWorks** [comment]
The entire weapon and weapon-mount system is currently in the process of being rewritten, though it's unknown at this point whether that will land for the next Pioneer release.

I'd welcome small patches to the current system to enable correct behavior for pulse and beam weapons (I suspect there's still some inaccuracy in the lead code as hit probability beyond ~1.5km seems to be lower than that of an AI ship shooting back at you) but the entire `FixedGuns` system is intended to be changed significantly in the near future.

If you want to check out the work-in-progress code, you can find it at [Web-eWorks:pioneer/gun-refactor](https://github.com/Web-eWorks/pioneer/tree/gun-refactor) in code related to the GunManager class. I do not currently have any personal bandwith to continue development on that branch, but I hope to be able to do so within a few weeks.
