### ISSUE TITLE
Crashes after 20 seconds of hyper jumping to Sophian

### ISSUE THREAD

**Issue by Usalabs** [pioneerspacesim/pioneer#5367]
I've been playing pioneer for a few days, and when I created a hyperjump route to Sophian, it was fine up until I hyperjumped to Sophian, then the game completely crashes for no reason.

### Observed behaviour
Game cursor changes to system arrow, then the game crashes back to windows desktop.

### Expected behaviour
Continued play

### Steps to reproduce
Get a large cargo ship with level 9 hyperdrive, then make your way to Sophian, topping up fuel as you go, then on the last hyperjump to Sophian, wait 15-20 seconds, then the game with crash with no error messages, the game just closes without warning.

__My pioneer version (and OS):__
20220203-win

**Comment by Gliese852** [comment]
@Usalabs please indicate the coordinates of the sector in which this system is located.

**Comment by Usalabs** [comment]
There's quite a lot of jumps to get there, but it's Sophian (-8,5,6)

**Comment by Web-eWorks** [comment]
With no save game or backtrace provided, we cannot reproduce and fix this issue. Closing as stale; if the issue recurs with the upcoming release please re-open or open a new issue with a save game!
