### ISSUE TITLE
Fatal: GLEW initialisation failed: Unknown error

### ISSUE THREAD

**Issue by sagitter** [pioneerspacesim/pioneer#5374]
Hi all.

### Observed behaviour
```
ver 20220523 on: Linux

System Name: Linux
Host Name: localhost.localdomain
Release(Kernel) Version: 5.17.8-300.fc36.x86_64
Kernel Build Timestamp: #1 SMP PREEMPT Mon May 16 01:00:37 UTC 2022
Machine Arch: x86_64
Domain Name: (none)

--------------------
SDL Version (build) 2.0.22
SDL Version (dynamic) 2.0.22
SDL Versions match
SDL_image Version (build): 2.0.5
SDL_image Version (dynamic): 2.0.5
SDL_image Versions match
Assimp Version: 5.0.0
FreeType Version: 2.12.1
GLEW dynamic version: 2.2.0
--------------------

Fatal: GLEW initialisation failed: Unknown error
```

### Expected behaviour
No error

### Steps to reproduce
Simply running `Pioneer-20220203` in Fedora 36 ([build log](https://kojipkgs.fedoraproject.org//packages/pioneer/20220203/2.fc36/data/logs/x86_64/build.log)), pioneer is compiled against system libraries (GLEW-2.2.0)

**Comment by Web-eWorks** [comment]
GLEW is failing to initialize on your system, which is an indicator that it cannot find or access an OpenGL driver implementation or has another unknown error. Check the `dmesg` log and/or `journalctl` (I believe Fedora uses systemd for system management), as the error is external to Pioneer and most likely related to your system configuration.

**Comment by impaktor** [comment]
Closing for above stated reasons.
