### ISSUE TITLE
Missing Reticule

### ISSUE THREAD

**Issue by robothauler** [pioneerspacesim/pioneer#5385]
### Observed behaviour
After a few seconds/minutes in flight, the reticule disappears

Warning: [string "[T] @pigui/libs/text.lua"]:365: bad argument #1 to 'CalcTextSize' (string expected, got nil)
stack traceback:
        [C]: in function 'CalcTextSize'
        [string "[T] @pigui/libs/text.lua"]:365: in function 'fun'
        [string "[T] @pigui/libs/wrappers.lua"]:557: in function 'withFont'
        [string "[T] @pigui/libs/text.lua"]:364: in function 'addStyledText'
        [string "[T] @pigui/modules/flight-ui/reticule.lua"]:399: in function 'displayFrameData'
        [string "[T] @pigui/modules/flight-ui/reticule.lua"]:829: in function 'displayReticule'
        [string "[T] @pigui/modules/flight-ui/reticule.lua"]:839: in function <[string "[T] @pigui/modules/flight-ui/reticule.lua"]:835>
        [C]: in function 'xpcall'
        [string "[T] @pigui/libs/wrappers.lua"]:34: in function 'pcall'
        [string "[T] @pigui/views/game.lua"]:168: in function 'drawGameModules'
        [string "[T] @pigui/views/game.lua"]:195: in function 'fun'
        [string "[T] @pigui/libs/wrappers.lua"]:90: in function 'window'
        [string "[T] @pigui/views/game.lua"]:191: in function 'fun'
        [string "[T] @pigui/libs/wrappers.lua"]:597: in function 'withStyleColors'
        [string "[T] @pigui/views/game.lua"]:190: in function <[string "[T] @pigui/views/game.lua"]:177>

### Expected behaviour
An always visible reticule

### Steps to reproduce
It's hard to catch. Sometimes it disappears after a few seconds, sometimes after minutes.

Start a new game
Takeoff
Jump to a system
Land

__My pioneer version (and OS):__
Current master
Arch Linux

![image](https://user-images.githubusercontent.com/10255455/174046357-0c63d54a-18a0-41cc-9240-b4f1335ff1e5.png)

**Comment by Gliese852** [comment]
@robothauler I was able to reproduce this, very strange, the label attribute almost always returns the name of the planet, but in very rare cases it returns `nil`, and then the reticule disappears. I flew Barnard's Star / Formations / OPLI Pax and just landed there, and now it happens once every few minutes, I guess.

**Comment by impaktor** [comment]
```
<sturnclaw> Essentially, when a LuaObject handle to a C++ DeleteEmitter wasn't
            referenced in Lua anymore it would be GC'd ... which works fine.
            However, during the GC process it would deregister the *current*
            handle for the C++ object inadvertently (instead of itself, which
            was already deregistered from the weak table). This is why
            properties are sometimes getting stomped, because if a handle is
            GC'd and another handle for the same object is the  [00:04]
<sturnclaw> On the upside, this should reduce GC load slightly - every time a
            GC cycle culled an unreferenced LuaObject handle, it would cause
            the next call to LuaPush(object) to actually make a new LuaObject
            and push that instead of using the existing handle  [00:29]
```
