### ISSUE TITLE
Radar alerts for docked ships in spaceports

### ISSUE THREAD

**Issue by Bodasey** [pioneerspacesim/pioneer#5393]
From Bodasey's minor series...

### Observed behaviour

Radar alarms on ships in Spaceports

### Expected behaviour

Ships in Spaceports are invisible to the Radar (and are not a danger); Radar is switched off near a port?

### Steps to reproduce

Fly to a Spaceport with Radar equipment

__My pioneer version (and OS):__

actual Master on SuSE Linux 15.3

**Comment by impaktor** [comment]
@WKFO

**Comment by WKFO** [comment]
I don't know how radar-picking-up-ships is done but if it's anything like the traffic counter, then the solution might be an if statement to check whether some method like a Ship.GetDockedTo() returns something, and if it returns a station you just ignore them on radar.

A better solution would be to not raise a yellow alarm on every ship-to-ship encounter now that we have lots of traffic and stuff. But if you don't raise a yellow alarm on ship encounters then what do you do? Raise them only if you are far away from any stations?

I unfortunately don't have time to fix this soon, if the ping was a request for that.

**Comment by Web-eWorks** [comment]
I'm going to mark this as a Design issue, as radar functionality needs to be rethought and include some notion of 'aggressiveness' to the player before justifying a yellow alarm.

**Comment by Gliese852** [comment]
I think the radar does not respond to parked ships. The fact is that due to a bug in the autopilot, sometimes the ships "get stuck" at the beginning of the docking process (about 16 km from the station), and just hang in space. I think that the radar responds specifically to these ships. it is being fixed in #5127.

**Comment by Bodasey** [comment]
Gliese852 is right:
![Screenshot_20220728_132610](https://user-images.githubusercontent.com/60466586/181494933-0d16dfa4-838b-4e32-8ab8-ad864670dc5d.png)

**Comment by Bodasey** [comment]
fixed
