### ISSUE TITLE
Black screen on startup

### ISSUE THREAD

**Issue by GabeTC** [pioneerspacesim/pioneer#5396]
### Observed behavior
Game launches with black screen on startup, music does play in the background and the games cursor does load.

### Expected behavior
Game loads and starts properly

### Steps to reproduce
Launch game

_2022__0203_My pioneer version (and OS):_Edition Windows 11 Home
Version	21H2
Installed on	‎5/‎25/‎2022
OS build	22000.856
Experience	Windows Feature Experience Pack 1000.22000.856.0_

[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/9331286/opengl.txt)

**Comment by ProgramRAM** [comment]
Additionally heres the output.txt I see a lot of errors 
[output.txt](https://github.com/pioneerspacesim/pioneer/files/9332058/output.txt)

**Comment by Web-eWorks** [comment]
Most likely a duplicate of #5297, try the fix mentioned in that issue (set `AntiAliasingMode=0` in your config.ini file)

**Comment by GabeTC** [comment]
> 
Seems to be a working workaround, is there no way for me to enable AA then?

**Comment by Web-eWorks** [comment]
Change your driver settings - the black screen is because the application attempts to create a multisampled render target for MSAA, but the attempt to create the buffer fails in a way Pioneer is unable to detect at present. This is most likely caused by an application-specific or global setting in your driver's configuration forcing MSAA to off.

**Comment by GabeTC** [comment]
> Change your driver settings - the black screen is because the application attempts to create a multisampled render target for MSAA, but the attempt to create the buffer fails in a way Pioneer is unable to detect at present. This is most likely caused by an application-specific or global setting in your driver's configuration forcing MSAA to off.

That fixed it for me thank you!
