### ISSUE TITLE
Logitech Extreme 3D does not works

### ISSUE THREAD

**Issue by marcorighi** [pioneerspacesim/pioneer#5397]
Hi there,
I have a similar problem to

[https://github.com/pioneerspacesim/pioneer/issues/4564](https://github.com/pioneerspacesim/pioneer/issues/4564)

The joystick is a Logitech Extreme 3D but `jstest-gtk` recognize it as 6 axis and 12 buttons.

Inside `jstest-gtk` the joystick works perfectly.

I downloaded Pioneers from AUR.

`
lsb_release -va

LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	21.3.7
Codename:	Ruah`

`
pioneer --version
ver 20210203 (142693b) on: Linux

System Name: Linux
Host Name: mm
Release(Kernel) Version: 5.15.60-1-MANJARO
Kernel Build Timestamp: #1 SMP PREEMPT Thu Aug 11 13:14:05 UTC 2022
Machine Arch: x86_64
Domain Name: (none)

--------------------
SDL Version (build) 2.0.10
SDL Version (dynamic) 2.0.22
WARNING: SDL Versions differ
SDL_image Version (build): 2.0.5
SDL_image Version (dynamic): 2.6.1
WARNING: SDL_image Versions differ
Assimp Version: 5.2.0
FreeType Version: 2.10.1
GLEW dynamic version: 2.0.0
--------------------

Initialized OpenGL 3.1, with extensions, renderer
Initializing joystick subsystem.
Found joystick 'Logitech Extreme 3D' (GUID: 030000006d04000015c2000010010000)
- 4 axes, 12 buttons, 1 hats
- axis 0: deadzone 0.00, curve: 1.00, half-axis mode: 0
- axis 1: deadzone 0.00, curve: 1.00, half-axis mode: 0
- axis 2: deadzone 0.00, curve: 1.00, half-axis mode: 0
- axis 3: deadzone 0.00, curve: 1.00, half-axis mode: 0
font orbiteer:
- Orbiteer-Bold.ttf 1.000000
- DejaVuSans.ttf 1.200000
- wqy-microhei.ttc 1.000000
font pionillium:
- PionilliumText22L-Medium.ttf 1.000000
- DejaVuSans.ttf 0.928571
- wqy-microhei.ttc 1.000000
Warning: Commodity rubbish has invalid producing economy ALL
Loaded economy info: 3 economies, 31 commodities (10 consumable)

started 3 worker threads in 0.21ms
Engine startup took 931.79ms
LoadStep::Start()
ShipType::Init()
Lua::Init()
Loading [08%]: Lua::InitModules() started
nanosvg: /usr/share/pioneer/data/icons/icons.svg 384x384
nanosvg: /usr/share/pioneer/data/icons/icons.svg 512x512
nanosvg: /usr/share/pioneer/data/icons/icons.svg 1024x1024
nanosvg: /usr/share/pioneer/data/icons/logo.svg 512x512
Ship Def found: missile_unguided
Ship Def found: missile_guided
Ship Def found: ac33
Ship Def found: missile_naval
Ship Def found: natrix
Ship Def found: vatakara
Ship Def found: varada
Ship Def found: kanara_civ
Ship Def found: dsminer
Ship Def found: deneb
Ship Def found: wave
Ship Def found: venturestar
Ship Def found: nerodia
Ship Def found: xylophis
Ship Def found: storeria
Ship Def found: skipjack
Ship Def found: sinonatrix_police
Ship Def found: sinonatrix
Ship Def found: pumpkinseed_police
Ship Def found: pumpkinseed
Ship Def found: molaramsayi
Ship Def found: kanara
Ship Def found: bowfin
Ship Def found: missile_smart
Ship Def found: amphiesma
Ship Def found: malabar
Ship Def found: molamola
Ship Def found: lodos
Ship Def found: bluenose
Ship Def found: lunarshuttle
30
Loading [08%]: Lua::InitModules() took 242.76ms
Loading [15%]: Gui::Init() started
Loading [15%]: Gui::Init() took 2.37ms
Loading [23%]: GalaxyGenerator::Init() started
Creating new galaxy generator 'legacy' version 1
Warning: 'mass' is 0.000000 for body 'Themisto'
Warning: 'mass' is 0.000000 for body 'Lucksmall'
Number of factions added: 103
StarSystemCache: misses: 0, slave hits: 0, master hits: 0
SectorCache: misses: 101, slave hits: 0, master hits: 2
Loading [23%]: GalaxyGenerator::Init() took 18.26ms
Loading [31%]: FaceParts::Init() started
Face Generation source images loaded.
Loading [31%]: FaceParts::Init() took 681.47ms
Loading [38%]: new ModelCache started
Loading [38%]: new ModelCache took 0.00ms
Loading [46%]: Shields::Init started
Loading [46%]: Shields::Init took 1.40ms
Loading [54%]: BaseSphere::Init started
GenerateIndices: triangles count = 648, mid indexes = 1728, hi edges = 54
Loading [54%]: BaseSphere::Init took 49.78ms
Loading [62%]: CityOnPlanet::Init started
Got 20 buildings of tag city_building
- Dome1: 39.626175
- Dome2: 48.596382
- Library: 64.693522
- Mall: 26.159388
- Tower1: 33.094160
- Tower2: 34.924003
- kbuilding01: 29.664692
- kbuilding02: 46.268344
- kbuilding03: 41.542333
- newbuilding1: 36.202756
- newbuilding10: 16.297418
- newbuilding11: 34.961034
- newbuilding2: 22.822782
- newbuilding3: 22.649894
- newbuilding4: 25.978193
- newbuilding5: 22.908506
- newbuilding6: 29.817877
- newbuilding7: 22.674426
- newbuilding8: 23.154979
- newbuilding9: 36.528138
End of buildings.
Loading [62%]: CityOnPlanet::Init took 163.59ms
Loading [69%]: SpaceStation::Init started
ground_station has:
 14 entrances,
 14 pads,
 0 exits
new_ground has:
 6 entrances,
 6 pads,
 0 exits
orbital_station_2-10k has:
 5 entrances,
 64 pads,
 5 exits
orbital_station_2-2k has:
 4 entrances,
 18 pads,
 4 exits
orbital_station_2-5k has:
 5 entrances,
 64 pads,
 5 exits
orbital_station_2-5k10k has:
 5 entrances,
 64 pads,
 5 exits
Loading [69%]: SpaceStation::Init took 500.21ms
Loading [77%]: NavLights::Init started
Loading [77%]: NavLights::Init took 0.07ms
Loading [85%]: Sfx::Init started
Loading [85%]: Sfx::Init took 16.94ms
Loading [92%]: Sound::Init started
Loading [92%]: Sound::Init took 397.29ms
Loading [100%]: PostLoad started
Loading [100%]: PostLoad took 0.02ms
Pioneer loading took 2123.12ms
Stars picked from galaxy: 0
Final stars number: 500000
Pi shutting down.
StarSystemCache: misses: 0, slave hits: 0, master hits: 0
SectorCache: misses: 101, slave hits: 0, master hits: 1

`

**Comment by Web-eWorks** [comment]
First, you've failed to mention what problem exactly you're running into - when running a version of Pioneer that's been compiled from a recent `master` checkout, is the joystick visible in the list of devices on the settings screen? If you're unable to bind axes or buttons, make sure you're trying to bind the right type of input (buttons or hats for Actions and physical axis inputs for Axes) and you've ensured axes on any other devices attached to the system are 'centered' at zero input values.

Secondly, according to the logs the device is present and accessible in the system and providing input to Pioneer; a Logitech Extreme 3D has *exactly* four physical axes, 12 buttons, and 1 8-way hat (displayed in jstest-gtk as two axes), which is the precise device and configuration logged by Pioneer. If the device is not reporting any axis or button input to the game, the issue does not lie with Pioneer as far as I am able to determine.

**Comment by Web-eWorks** [comment]
![image](https://user-images.githubusercontent.com/4218491/187325957-ef47b97e-50a7-4f7d-bf81-b6ba389b347b.png)

If you compile a recent version of Pioneer from the master branch, your joystick should be listed on this screen with a `Connected` status.

**Comment by marcorighi** [comment]
Thank you for your answer. The issue is still here with the last PIoneer version. 

The problem. The Joystick in Pioneer does not work correctly (it works perfectly, e.g. with Flight Gear). 

The fault consists of wrong input recognition.

By configuring the joystick, the only input accepted is the one usually used for the throttle. The part of the joystick is unresponsive with Pioneer or, in other words, Pioneers do not react to them. Pioneers recognize only the throttle. After that the throttle axes is configured, by configuring another input in Pioneer, Pineer recognize immediately the throttle axes. In other words, Pioneers does not mask the throttle axes or the throttle axes does not release the control.

I think I have the last version of Pioneer installed, I got it from Arch - AUR.

`aur/pioneer 20220203-1 (+24 0.00) (Installed)
    A game of lonely space adventure
`

The joystick is:

`Bus 001 Device 009: ID 046d:c215 Logitech, Inc. Extreme 3D Pro`


Follows two screenshots. The first one is similar to your one. But My joystick is not listed. The second one shows the recognized axes (with the bug just described).

![Istantanea_2022-08-30_11-09-00](https://user-images.githubusercontent.com/9825472/187402160-01288359-e242-4f19-b0d8-6b13621360a3.png)

![Istantanea_2022-08-30_11-05-53](https://user-images.githubusercontent.com/9825472/187402478-91ba0951-282d-41fc-97f4-c3937dc34925.png)

Thx 4 your time

**Comment by Web-eWorks** [comment]
This is not a bug.

> The fault consists of wrong input recognition.
> By configuring the joystick, the only input accepted is the one usually used for the throttle. The part of the joystick is unresponsive with Pioneer or, in other words, Pioneers do not react to them. Pioneers recognize only the throttle. After that the throttle axes is configured, by configuring another input in Pioneer, Pineer recognize immediately the throttle axes. In other words, Pioneers does not mask the throttle axes or the throttle axes does not release the control.

This is happening because your throttle axis is not at the physical 'center' point but most likely set to the lower bound of its range. The throttle axis reports a +1 <-> -1 numeric range, so setting the throttle axis to the bottom is the same as pushing your stick all the way to the left. To bind other axes, you'll need to move the throttle handle to the center position.

It's very important to be clear when making a bug, as your joystick does indeed very much work with Pioneer and the issue is simply that the throttle axis is taking precedence over other axes you're trying to bind because it stays "active" (reporting a non-zero value) when you release other axes.

> Follows two screenshots. The first one is similar to your one. But My joystick is not listed. The second one shows the recognized axes (with the bug just described).

Your stick is not listed because the version of Pioneer you're running does not include the joystick device display code.

**Comment by marcorighi** [comment]
you close the issue without resolving the problem. I m sorry to affirm that Pioneers do not manage this joystick properly.

**Comment by Web-eWorks** [comment]
If you think there's another problem besides what has been described, you will have to provide significantly more detailed information about both your actions and what exactly the game is doing. What you have described is a user error issue; the game is functioning exactly as intended when it comes to binding axes and the information you have provided shows there is absolutely no problem with either the hardware or Pioneer's handling of the joystick.

The issue here is that you are effectively pushing the joystick to the left and expecting the vertical axis of the stick to be bound when you have never pushed the stick forwards. I'll repeat again from the above reply: **Put the throttle axis to the center position (as shown in JSTest-GTK) when binding other axes.**

No further help can be offered to resolve the issue as reported, as it's entirely beyond the scope and design of Pioneer.

**Comment by Zireael07** [comment]
@Web-eWorks: based on what OP is saying I think he may be experiencing joystick drift (a hardware issue where the joystick is visually in a neutral position, but the hardware/software reports a different one). He is not actively pushing to the left but the game thinks he is.

Alternately there could be a info screen in joystick config telling you to reset the throttle handle.

**Comment by marcorighi** [comment]
@Zireael07 thank you for your kind answer.

@Web-eWorks the game has to be easy to configure, analogic joystick too. It is evident the lack of experience with this type of device. 
First, you should try using another game that uses this joystick. I have already suggested trying Flightgear. 

It is unreasonable to ask a player to configure a  joystick by positioning the throttle in the 0 position. The interface is wrong. The game is very good, but the joystick settings must be rewritten from scratch.

I write again the simple steps that bring to this situation. 

Using the mouse, I click over the area that permits me to associate an action with a joystick button.

Pioneer accepts only one input from the joystick, the input shown in the previous picture. If I press other buttons or I move other axes nothing appears. Pioneer does not respond. During the configuration, Pioneer responds only to the thrust axis. 

In the end, @Web-eWorks does not understand my comments. I am not asking for help but I am providing help by putting in evidence a bug.

Pioneer is a space-flight simulation game, and one primary task is good management of the joysticks. In a mature collaborative system (such as the open source and freeware world) criticisms are accepted and used to improve ourselves.

I hope you have the capacity to resolve this bug n the glory of Pioneer which has nothing to envy in many other games.

For the good of the community, I am here to explain to you the steps that generate the bug.

**Comment by Zireael07** [comment]
Hm... responding only to a single axis is bad UX indeed. What if my joystick happens to have this axis broken/unrecognized?

**Comment by Web-eWorks** [comment]
@marcorighi 
> It is evident the lack of experience with this type of device.

This is an ad-hominem attack and is directly counter-productive to a "mature collaborative system". Please refrain from attacking or insulting any contributors' experience or skills in the future. This is your first and **last** warning.

> Using the mouse, I click over the area that permits me to associate an action with a joystick button.
> Pioneer accepts only one input from the joystick, the input shown in the previous picture. If I press other buttons or I move other axes nothing appears. Pioneer does not respond. During the configuration, Pioneer responds only to the thrust axis.

You have clicked on an axis binding, which permits only associating a physical axis with a logical axis. Try clicking on a 'Positive' or 'Negative' field if you want to bind buttons.

> It is unreasonable to ask a player to configure a joystick by positioning the throttle in the 0 position.

It is perfectly reasonable to ask users to provide the correct input required to achieve the output they are looking for. The only thing that is actually actionable here is that the constraints on the axis binding system are not clearly communicated in Pioneer's primary documentation source (the wiki).

Again, there is no bug here. I have provided the tested and proven steps to correctly bind arbitrary axes in Pioneer, which you have refused to follow as "unreasonable". That makes ***everything*** else in your message a feature request regarding the UX of choosing one of multiple simultaneously active joystick axes to associate with the input binding slot you are trying to bind.

As a feature request, Github is not the place for this discussion. Please open a new thread on the [dev forum](https://pioneerspacesim.net/forum/) where it can be discussed at further length.

To assuage the actual issue you're concerned about (see the X-Y problem), we do eventually plan to track the "last moved axis" when binding axes, but that requires non-trivial handling in the input core code and is considered significantly low priority when the existing method is perfectly functional.

@Zireael07 
> Hm... responding only to a single axis is bad UX indeed. What if my joystick happens to have this axis broken/unrecognized?

At present, your options are to adjust the reported range in your calibration software (jstest-gtk, windows joystick calibration, or the manufacturer's software if applicable), or to set the axis Deadzone (`DZ`) value in the Pioneer config file to 1.0, which will ignore all inputs on that axis.

There are future plans to expose the deadzone / sensitivity values in the settings menu for each physical axis which would allow axis customization at runtime, but it's been a bit low-priority compared to some other major features that have been getting worked on this patch cycle.

**Comment by marcorighi** [comment]
@Web-eWorks are you threatening me? I am sure you are kidding.

Before answering, did you try some games that manage in the right way the problem? You seem to answer without understanding the issue. 

Go on.

Thank for the suggestion to write to dev forum.

Adios
