### ISSUE TITLE
Cannot find shaderdef file vtxColor.shaderdef or at least thats the warning and it's possible results

### ISSUE THREAD

**Issue by Kualani** [pioneerspacesim/pioneer#5401]
I honestly don't know how to solve because I'm not tech savvy but if you guys know how to solve please put the instructions of what to do in a list for me (and whoever else) to follow plz

But i just saw the warning saying:::

Pioneer warning

Cannot find shaderdef file vtxColor.shaderdef

And maybe this is the results of somehow accidentally deleting the file or something else but I've tried re downloading the game after deleting it but the same result pops up

Also I played this game no problem before so I know my laptop can run the game

<!--  ![image](https://user-images.githubusercontent.com/90564883/188535474-2c10d9b5-dfed-4218-88cb-9b67e9b10856.jpeg) 

![image](https://user-images.githubusercontent.com/90564883/188535524-197120a6-06ac-4af0-814e-8b1620200f4f.jpeg)

![image](https://user-images.githubusercontent.com/90564883/188535549-eebd2d42-bb9e-448b-b583-f00a059bb758.jpeg)

![image](https://user-images.githubusercontent.com/90564883/188535575-9d2d910b-3bd7-42b9-86c9-01ab20869330.jpeg)

### Observed behaviour
This screen cutting/clipping is making the game unplayable for me because all the usual buttons and controls are unreachable (I play using mostly the mouse if that makes sense.

This part is important I see the warning I keep getting this error and I don't know how to fix this ![image](https://user-images.githubusercontent.com/90564883/188545192-09204fbf-0e4b-4083-8e1a-b0aadacbd42c.jpeg)

### Expected behaviour
A well relaxed and fun to play game

### Steps to reproduce
All I did was save my game after using the lua console in my game and exiting out of the window.

__My pioneer version (and OS):__
Windows 11 and the version that gets installed after clicking the download/install game on main page of the website

**Comment by impaktor** [comment]
Sounds like pioneer can't find your `data/` folder.

If you excecute it from command line (as is usually done on Linux), make sure you're running the executable from the pioneer root (top) folder.

**Comment by Kualani** [comment]
I will gladly take instructions on how to do that, please do simplify in the most simplest ways you can plz

**Comment by impaktor** [comment]
Not sure how it's run from windows, but do make sure you have the `data/` folder.

Or in windows-speak: `pioneer\data\`

**Comment by Kualani** [comment]
So I did look through all the files and wasn't able to find the folder how would I be able to download it or find it if possible?

**Comment by Kualani** [comment]
How would I go about finding the file or installing/downloading it???

**Comment by Web-eWorks** [comment]
Reinstall Pioneer from the official windows installer and run the file from the folder containing the installed executable. Unfortunately we're not able to provide further support unless you're able to confirm you've correctly followed the installation procedure and provide a game log.

**Comment by Kualani** [comment]
Ok I will do that and right now would pictures of what my game looks like right now be of use at the moment???

**Comment by Kualani** [comment]
Last comment from me about this issue::: 


Somehow when I deleted and downloaded EVERY file including my saved games the game fixed itself so even though we didn't get a definitive answer I still thank those that helped
