### ISSUE TITLE
Segmentation fault when hyperjumping or opening sector map

### ISSUE THREAD

**Issue by sarbs** [pioneerspacesim/pioneer#5405]
On two successive saves, I had a problem where I would play for a while within the system where I started and then eventually, when I would try to jump to any other system, I would get a crash either immediately after jumping or several seconds later (depending on which system I was jumping to). I started a third save in a different system and jumped to a new system immediately and did not have the same problem. But after playing for a while and jumping to systems with no problem I now am getting the crash when I open the sector map. 

I am running the game on Arch Linux with nVidia drivers. I installed the game from a [package in the Arch User Repository](https://aur.archlinux.org/packages/pioneer). The package says version 20220203, which seems to be the most recent release, but my game actually says 20221010 and a few days ago said 20221005. I'm not sure why that is happening. 

Here are my [output.txt](https://github.com/pioneerspacesim/pioneer/files/9759061/output.txt) and [opengl.txt](https://github.com/pioneerspacesim/pioneer/files/9759063/opengl.txt) files. The output.txt always ends in the middle of a line after this crash. Here is the [backtrace](https://github.com/pioneerspacesim/pioneer/files/9759066/trace.txt) output from the debugger, which reports a segfault. Let me know if I didn't generate this file correctly. 

I found [this thread](https://spacesimcentral.com/community/pioneer/newcomer-some-feedback-and-a-problem/) in which someone seems to have a similar problem, although the solution there was updating their nVidia drivers on Windows, and my drivers are already updated. 

If there's anything else that I didn't include that could be helpful please let me know.

**Comment by impaktor** [comment]
- We recently had a bug causing crash on load, if game was saved in sector map outzoomed. (Not sure if it was fixed)
- Last code commit was in july, so the crash is not due to any recent changes in master.
- We have (had) some new code in how space stations are populated with data, i.e. if this hypothesis is correct, you will not get (this) crash when jumping to uninhabited systems.

> The package says version 20220203, which seems to be the most recent release, but my game actually says 20221010 and a few days ago said 20221005

I think you have a commit hash in the bottom right corner of the main menu screen. That (first 4 characters) would confirm which version you're on.

You can always include your saves, and/or even better, post a [backtrace](https://pioneerwiki.com/wiki/FAQ#Debug_backtrace).

Thanks for reporting

**Comment by impaktor** [comment]
> "No debugging symbols found"

Ah, I assume the PKBUILD in AUR you're using is optimized / disables debugging.

If you clone our master branch, and follow instructions in [COMPILING.txt](https://github.com/pioneerspacesim/pioneer/blob/master/COMPILING.txt), it will build using debug symbols, so you can run it through gdb, if you want to drill deeper. (Plus, you'll always be a "git pull" away from new features and bug fixes).

__EDIT:__ If it's this [PKBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pioneer) that you're using, then just remove the `-Wno-dev` flag on line 40.

**Comment by impaktor** [comment]
Hmm, I wonder if the flatpak compiled with optimization flags on, or something, but what I can gather from the first backtrace, it looks like it might be `SectorView::PutFactionLabels` that's failing, @Gliese852 would know better.

**Comment by Gliese852** [comment]
@sarbs Will this workaround help you? https://github.com/pioneerspacesim/pioneer/issues/5349#issuecomment-1073078058

**Comment by impaktor** [comment]
@sarbs I just looked at the AUR file above (now that I'm not sneak-posting from work), and the flatpak, both install the February release, one of the bugs you're reporting is likely fixed +6 months ago. I'd recommend you try [this](https://aur.archlinux.org/packages/pioneer-git) AUR instead (looks like it's using our latest master, and compiles with debug info), if it works. If it doesn't work, it should be relatively trivial to move that part into the AUR you used.

**Comment by impaktor** [comment]
We're glad it helped.

Benefit of playing on current master, is that you're testing real (unknown) bugs for us, which we are very interested in.

**Comment by Web-eWorks** [comment]
Closing as completed by #5361.
