### ISSUE TITLE
Scoop missions do not work properly because onCargoDestroyed event is not emitted when cargo is scooped.

### ISSUE THREAD

**Issue by azieba** [pioneerspacesim/pioneer#5406]
### Observed behaviour
If player scoops navigational target for the mission (like rescue capsule) and then tries to press the button "Set destination as navigation target" in the mission details then the mission crashes.
The mission code relies on onCargoDestroyed event to update the list of available debris to collect. If it is not called then mission code tries to return for navigation an object that does not exist anymore.
### Expected behaviour
No mission exception.

### Steps to reproduce
1. Start a scoop mission.
2. Scoop the "navigation target" object.
3. Press the "Set destination as navigation target" in the mission details

__My pioneer version (and OS):__
master as of 16 Oct 2022 (Debian)

**Comment by Web-eWorks** [comment]
@azieba if you pull #5389 and re-test does this issue still occur? The cargo scooping mission had some internals changed in that PR, I'd like to know if this is still an issue after those changes.

**Comment by azieba** [comment]
The issue is that the onCargoDestroyed is not generated by core and Scoop.lua still uses it so..
Please see my PR #5407. The function was checking if the cargo has scoop property instead of the ship. Simple fix.
