### ISSUE TITLE
Docking Bay 9 requires player to land on Bay 10

### ISSUE THREAD

**Issue by Keeper1st** [pioneerspacesim/pioneer#5408]
### Observed behaviour
In a recent flight, I was given docking clearance for Bay 9 of a ground_station, but as I approached it became evident that the navigation was sending me to Bay 10 -- not Bay 9. The lights around Bay 9 were active, but I was required to land on Bay 10. Here's a clip: https://www.twitch.tv/videos/1626124537

### Expected behaviour
If given clearance to land on "docking bay 9" one should be expected to land on pad 9 -- not pad 10. (Without using HUD nav lines this could be a real problem!)

### Steps to reproduce
Tricky as it requires ships to be occupying bays 7 and 8 when one approaches a ground_station with a small ship.

__My pioneer version (and OS):__
My own Windows build but nothing that would change the docking bay configurations.

**Comment by Keeper1st** [comment]
What's interesting here is that the lights on Pad 9 are on, so that part of the code is correct. It's just the actual expected landing point that is incorrect. While I'm mentioning it, should any of these really be called a "docking bay"? They're better off called "landing pad" since we're not "docking" so much as "landing" no matter which station type it is these days. In the old old days of the original space station, "bay" made a little more sense.

**Comment by nozmajner** [comment]
I'll check the bay tags in the model

**Comment by impaktor** [comment]
So current master? [8dabc67](https://github.com/pioneerspacesim/pioneer/commit/8dabc676cbc530ae605af3b054f18637526fb7bd) I assume (we've been on that commit for quite a while, plus longer without code change)

**Comment by Keeper1st** [comment]
Yes, compiled in July from the latest sources. My own updates to sources don't touch the station codes, so this problem should exist in the standard master as well. There haven't been any source code updates in the mean time that affected the stations.

**Comment by Bodasey** [comment]
confirmed

**Comment by nozmajner** [comment]
This is rather odd. I've checked and the tags are in their proper places:
![image](https://user-images.githubusercontent.com/4182678/213913218-03bec33a-33d2-48a1-ab3a-6d8afc3d8f3a.png)
I tried to remove the leading zeroes from the tags for the tags, (they were named 01-014, but 01-14 did not work either ), but that made it even more confused, putting bay 1 at the 14th pad:
![image](https://user-images.githubusercontent.com/4182678/213912922-64c68626-c4e1-4818-ba6f-6ec065977f0c.png)

I've noticed that the model hierarchy shows the tags in their proper order up to bay 8, and then 10, then 9 and all bets ar off:
![image](https://user-images.githubusercontent.com/4182678/213913248-beedc086-7b4a-4397-b1ad-c96d8b843df0.png)
If I remove the leading zeroes then they are in mostly reverse order which lines up with port 1 placed at the 14th pad:
![image](https://user-images.githubusercontent.com/4182678/213913069-3cd5ad72-6f99-47b0-af7f-69db98fd4e6a.png)

Also the pad locators temselves were named:
loc_A001...
loc_B001...
loc_C001...
I've tried renaming them to all be loc_A001... to loc_A014... but it did not make any difference neither in the order of tags in the hierarchy or in-game.

**Comment by Web-eWorks** [comment]
This issue is being caused by bay numbers (which determine the mapping between docking port number and pad position) being derived from the order of location tags in the model file, rather than pulled from the explicitly-specified bay number in the tag name. I've made a commit to change this, which will be available in a bugfix PR soon.
