### ISSUE TITLE
When trying to register to the forum, you have to input the wrong answer

### ISSUE THREAD

**Issue by wiki-me** [pioneerspacesim/pioneer#5409]
### Observed behaviour

When i tried to register to the forum, this was the question to answer:

"What does the year counter say after two years in the game (four digits):"

The year in the game is 3222, but when entering 3224 it does not work, inputing 3223 completed the registeration.

### Expected behaviour

entering 3224 should work.

### Steps to reproduce

try to register and enter 3224 as the answer.

**Comment by impaktor** [comment]
Fixed, thanks.
