### ISSUE TITLE
new mission type - astro photographer

### ISSUE THREAD

**Issue by matthewfarmery** [pioneerspacesim/pioneer#541]
following from this thread and Rob's idea, 
http://www.spacesimcentral.com/forum/viewtopic.php?f=35&t=2301&start=30#p22599

a new mission type, but this could be expended for all sorts of things, 

my quote

now that isn't a bad idea, having a astro photographer job, maybe, it could have some requirements, time limit, distance from target, or location, / time of day, and if its a good photo, you can get a fair bit for them, 

---

and
yes I remember them, you had to be pretty close and not raise any alarms, better be in a small fast ship,

so this idea could be added for recon missions, taking photos of the following, partial constructed space stations, new ships designs, planets for new civilisations (with planet readings,) enemy fleets preparing to jump, (time limited so you can if you have a fast ship, get in take a few photos, get out and the alarm can be sounded and the enemy fleet could be countered, otherwise the system could be attacked and taken over (as it would be good if systems could change hands once in a while)

you know, for military missions, once you are high enough, the military of your chosen faction could lone you a special kind of ship, cloaked (cloak non removable ) for more high risk photos like the above, decreasing your chances of been found, or you are given a cloak that gets fitted to your ship (again none removable until the mission ends (success of fail) then if fail, the cloak short circuits so stop it been used for other purposes) so stopping it from been an over powered item

I think astro photography type missions could be expended to cover a lot of areas, as it got pretty boring after a while in frontier, but in pioneer it could be pretty fun, and high risk with decent rewards

---

as you did have these in frontier too, but in pioneer, this idea could be expended to cover loads of things, spy missions, want the best photo of a place / station / planet and more

I think these could be pretty fun missions and pretty varied, depending on the client, would be nice if this was added at some point

**Comment by Web-eWorks** [comment]
As this issue hasn't had activity in *nine years*, I'm closing it. Please post feature requests on the [forum](https://pioneerspacesim.net/forum); we use Github to track issues with currrently implemented features.
