### ISSUE TITLE
Not getting any emails when getting replies in the forum, despite being subscribed to a thread and email notifications enabled

### ISSUE THREAD

**Issue by wiki-me** [pioneerspacesim/pioneer#5411]
### Observed behaviour

After posting [this](https://pioneerspacesim.net/forum/viewtopic.php?p=6964#p6964) and getting replies i didn't get any email notifications despite being subscribed to a thread and email notifications enabled (in the section: " Someone replies to a topic to which you are subscribed " )

### Expected behaviour
I should get email notifications.

### Steps to reproduce

Register to the forum, post a topic and subscribe to it (you can also verify email notifications are enabled), have someone else post a reply and see you are not getting an email.

**Comment by impaktor** [comment]
Yeah, emails from the dev forum hasn't worked in many years, as far as I know. I don't know if it's something @robn (ping) can fix?

**Comment by wiki-me** [comment]
> Yeah, emails from the dev forum hasn't worked in many years, as far as I know. I don't know if it's something @robn (ping) can fix?

Maybe it is better to just dump the forums, the profile page says you can put in your Yahoo Messenger (which had it's last release six years ago), i would estimate that the forum software is out of date, might not have security fixes and might risk users . Even if the forum getting hacked seems unimportant it can still hurt some users if they reuse their password on an important service where there email was known to be used (because they were leaked in databases like those shown in [have i been pawned](https://haveibeenpwned.com/)).

Not to mention it makes contributing harder despite having no apparent advantage , if you want a forum for "softer" discussion you can always use [lemmy](https://lemmy.ml/) (a open source project)  or just reddit.

**Comment by nozmajner** [comment]
The issue tracker is intended for actionable, and indeed actioned  things about the game. Bug reports, PRs.
Discussions about design, lore, infrastructure and such should go onto either the forum or IRC. IRC is usually more direct, All the active (and half-active) developers have a backlog.
(And the forum these days act more like a notepad really)
So if you wish to discuss these topics, I'd suggest bringing it to IRC (there's a matrix bridge for that too). Thanks!

**Comment by wiki-me** [comment]
If you want to keep the forum that's fine, but I think it is better to leave this issue open as long as it is not fixed in case someone will encounter it and want to see it exists, or someone might randomly encounter it and decide to work on it.
