### ISSUE TITLE
Irregular display of stars in the sky

### ISSUE THREAD

**Issue by Gliese852** [pioneerspacesim/pioneer#5414]
### Observed behaviour

https://user-images.githubusercontent.com/18342621/199968979-4440df9d-91c8-47fb-833f-244799db1317.mp4

On the oXY plane, a strip is clearly visible, there are more stars than usual, and two dark spots are also visible

__My pioneer version (and OS):__
master at https://github.com/pioneerspacesim/pioneer/commit/824adc84b4451e31c758aec36360b432cc8b7541

**Comment by Web-eWorks** [comment]
Very good catch, thank you! I'll have to take a look into the background star generation code and determine if this is an artifact of sector map generation or building the background...
