### ISSUE TITLE
User made flight log does not save on closing the game

### ISSUE THREAD

**Issue by AgitatedAlice** [pioneerspacesim/pioneer#5420]
### Observed behaviour
Writing an entry into the logbook thing under personal info is not preserved when the game exits and does not show up when the game is reloaded

### Expected behaviour
Log is preserved on exit and viewable when reloading the save in a new session

### Steps to reproduce
Open game, start a save, write a diary/logbook entry, save game, close game, reload game

__My pioneer version (and OS):__
Version: February 2022-02-03
OS: Windows 10 64 bit

**Comment by zonkmachine** [comment]
> Version: February 2022-02-03

I can confirm this on 2022-02-03 / 9c06c9f but it seem to work fine on current master.

**Comment by impaktor** [comment]
I confirm bug is there on current master (just compiled) 9e9fc858b023afce894868958516f951332c220f
