### ISSUE TITLE
current git code (11/15/2022) does not compile cleanly with vs2019

### ISSUE THREAD

**Issue by stamasd** [pioneerspacesim/pioneer#5421]
### Observed behaviour
many errors on compiling as recommended

### Expected behaviour
no errors

### Steps to reproduce
install vs2019 and all updates
git pull https://github.com/pioneerspacesim/pioneer.git
git pull https://github.com/pioneerspacesim/pioneer-thirdparty.git
open pioneer/win32/vs2019/pioneer.sln in vs2019
build solution (either debug or release, same result)
many errors related to LUA code see attached file

__My pioneer version (and OS):__
git 11/15/2022, win10x64, vs2019
[vs2019errors.txt](https://github.com/pioneerspacesim/pioneer/files/10016798/vs2019errors.txt)

**Comment by Web-eWorks** [comment]
CC @fluffyfreak as the one maintaining the VS solution.

I'd highly recommend using the CMake build system when compiling on Windows instead; I'm unsure what the precise steps to set that up in a desktop install of Visual Studio are, but it is what we use with continuous integration (CI) builds of the Windows binaries here on Github.

**Comment by fluffyfreak** [comment]
I've just done the same steps and it builds them ok for me 🤔

Ah-ha! Wait I know what it is. it's the win32 build, @stamasd change the solution platform to `x64` from `win32`

**Comment by fluffyfreak** [comment]
I'll have to fix this up but yeah you can also try the CMake buildnsystem, I got it to build but not run which is why the vs2019 solution is still alive

**Comment by stamasd** [comment]
I can confirm that changing the build platform to x64 from win32 results in a working binary with no compilation errors, both for the release and the debug targets.

**Comment by impaktor** [comment]
Didn't @Web-eWorks recently drop 32 bit support for Linux? So we can just say we only support 64 bit, and close?

**Comment by fluffyfreak** [comment]
As the VS2019 Solution is probably/hopefully going to go away at some point I'm happy with that.

**Comment by Web-eWorks** [comment]
> Didn't @Web-eWorks recently drop 32 bit support for Linux? So we can just say we only support 64 bit, and close?

![image](https://user-images.githubusercontent.com/4218491/202863634-f1558856-8dad-4e26-9223-7647504cdbef.png)

...if I did, it was quite a while ago. Then again, my mental bandwidth has been quite low these last few weeks, so it's entirely possible I simply forgot.

In general I have no issues with dropping 32bit support, as even cheap budget laptops these days are 64bit architectures.
