### ISSUE TITLE
Crash while opening system overview while in hyperspace

### ISSUE THREAD

**Issue by Damjan94** [pioneerspacesim/pioneer#5424]
### Steps to reproduce
1. Load the savefile
2. Jump to populated system
3. Open System Overview 
4. Crash...
[systemMapCrash.gz](https://github.com/pioneerspacesim/pioneer/files/10050131/systemMapCrash.gz)

__My pioneer version (and OS):__
Compiled from master on linux
commit: 2f301c1510a0e01cb9f0ca547c2c41bcfc71215c

**Comment by impaktor** [comment]
@Damjan94 please test #5425, if possible, and see if that fixes the problem you experienced.
