### ISSUE TITLE
Auto-pilot invisible wall

### ISSUE THREAD

**Issue by DynV** [pioneerspacesim/pioneer#5437]
### Observed behaviour
Right above Zephirin of Ayizan there was an auto-pilot invisible wall, when I switched to manual it wouldn't fall so I used thrusters to "push" through it and then, being so close to the ground, a decent part of the momentum remained and received considerable damage to my ship. Good thing I could cheat myself the amount of money used for that repair.

### Expected behaviour
Can land by auto-pilot, like almost everywhere else.

### Steps to reproduce
I don't know how to find auto-pilot invisible walls.

__My pioneer version (and OS):__
20220203-win

**Update 1**

Another time my ship was aligned and I just activate up & down thrusters and landed without damage. Yet another time it was similarly aligned and hit an invisible wall; I then didn't touch a control and after some seconds (perhaps > 1 min) and it eventually landed without damage.

**Comment by Web-eWorks** [comment]
Unfortunately an issue report like this is unhelpful without a save game to reproduce the issue. If you can, try to save the game at a point just before the autopilot hits the "wall" and attach that here in a zip file.
