### ISSUE TITLE
Local language not found chinese

### ISSUE THREAD

**Issue by Sun-FreePort** [pioneerspacesim/pioneer#5441]
### Observed behaviour

Download `pioneer-20220203-win` and try run it, the install program tell me: select game language.

But I not found "chinese" select.

When access `www.transifex.com/pioneer/pioneer`, can find `Chinese (zh)` item, and only 28 item not translate.

So, can I support any help?

### Expected behaviour

Has chinese language choice.

### Steps to reproduce

not has.

__My pioneer version (and OS):__

Windows 10 64x

**Comment by RacerBG** [comment]
You should scroll down to the bottom of the list. ;)

**Comment by Sun-FreePort** [comment]
> You should scroll down to the bottom of the list. ;)

Hi, really not has Chinese or "中文" select, this snapshot photo:

![20221214102714](https://user-images.githubusercontent.com/19473984/207490435-a67d2b14-d38f-4ba9-8113-405ce8ea1d9f.png)

![20221214102728](https://user-images.githubusercontent.com/19473984/207490375-4f2620e7-ee61-45b8-b84f-4303714633f3.png)

**Comment by impaktor** [comment]
@Sun-FreePort The transifex launguages are for the actual game, the screenshot shows (I assume) an installer for the game.

**Comment by Sun-FreePort** [comment]
> @Sun-FreePort The transifex launguages are for the actual game, the screenshot shows (I assume) an installer for the game, something we do not control.

You are right! thanks bro.
