### ISSUE TITLE
In system at specific time crashes game

### ISSUE THREAD

**Issue by DynV** [pioneerspacesim/pioneer#5443]
### Observed behaviour
If you load the game save, which name includes "hours_before" and go straight for the single mission target, ~14:20 in game-time my system would crash;.I did detours from multiple angles, in case it was limited to the space between the star and that planet and it still crashes. If you load the game save, which name includes "day_before" and make a detour to another system, making the arrival later, there was no crash at all for me.

### Expected behaviour
The game never crash.

### Steps to reproduce

1. load the game save, which name includes "hours_before"
2. go straight for the single mission target
3. pay attention when the time approaches 14:00
4. very close to 14:20 the game may crash on your install (maybe I don't have enough memory, my GPU driver miss something, etc.)

__My pioneer version (and OS):__
20220203-win

The attached file was simply renamed so it would go through the upload extension filter, there was no modification to the file content of my save-file.
[Pioneer-Yoan_Faure-Ioethin_bug-hours_before.zip](https://github.com/pioneerspacesim/pioneer/files/10245412/Pioneer-Yoan_Faure-Ioethin_bug-hours_before.zip)
[Pioneer-Yoan_Faure-Ioethin_bug-day_before.zip](https://github.com/pioneerspacesim/pioneer/files/10245414/Pioneer-Yoan_Faure-Ioethin_bug-day_before.zip)

**Comment by impaktor** [comment]
Did you get some kind of error message / back trace?

This might be difficult to sort out, also since this is on the now, soon to be 1y old release, might be a bug we've already fixed.
Best would be to play latest master. 

In fact, best would be to play-test our latest steaming-hot new-feature-soon-to-be merged: scout-mission branch, you can [download a windows build here](https://github.com/pioneerspacesim/pioneer/suites/10045356746/artifacts/504988902), from [scout build artifacts](https://github.com/pioneerspacesim/pioneer/actions/runs/3773965223) please report bugs over in #5433.

(Currently, each BBS will have 10 scout missions, and price and mass of the new scanner equipment is currently just place holders, will be bumped up to something more reasonable)

**Comment by DynV** [comment]
> Did you get some kind of error message / back trace?

I'm sorry but I can't be sure as it's been some time. Although I assume there wasn't as it's something I'd most likely would mention in a bug report.

**Comment by impaktor** [comment]
@DynV The new version of pioneer, that you can download from link in my previous post, will now generate a full backgrace in the output.txt after a crash, so it's a good thing to hold on to.

**Comment by DynV** [comment]
It seems you've been encouraging me to upgrade version. An issue I'm having with that prospect is that I don't know how to cheat in my potential new gamesave the same # of kills I currently have; I'd appreciate if you could let me know about that.

**Comment by impaktor** [comment]
@DynV https://pioneerwiki.com/wiki/Lua_Console

**Comment by Web-eWorks** [comment]
The CTRL+I debug menu in the RPG tab will also let you set your reputation and number of kills at any time, as well as cheat in money to approximate your old save.

**Comment by DynV** [comment]
There was no attempt at hyperjumping in the OP; why is this linked to Clear autopilot before **hyperjumping** #5564 then?

**Comment by Gliese852** [comment]
@DynV In the provided save, at ~14:24, an NPC ship comes out of hyperspace, which has a dangling pointer in the autopilot object, it immediately tries to refer to it and the game crashes.

Unfortunately this fix will not fix this save, it is aimed at ensuring that this does not happen again.

To get the fixed version, you need to build it from the git master or download it from here (for windows)
https://github.com/pioneerspacesim/pioneer/suites/11314345345/artifacts/580985232
Saves are compatible in 20230203 but not compatible with 20220203
