### ISSUE TITLE
Buried ships

### ISSUE THREAD

**Issue by DynV** [pioneerspacesim/pioneer#5444]
### Observed behaviour
At a partly-buried station there was a fully-buried medium ship and a partly-buried large one.
![Pioneer-Port_Potts-ship_buried-1](https://user-images.githubusercontent.com/2823807/208278493-47034524-2304-4cf8-9a82-942951d053ee.jpg)
![Pioneer-Port_Potts-ship_buried-2](https://user-images.githubusercontent.com/2823807/208278496-b6ee1974-1e41-4816-861d-d95710ff3de3.jpg)

### Expected behaviour
Either block ships from being in the buried docking bays or ensure the station isn't buried (dug out or on stilts).

### Steps to reproduce

1. Load the attach gamesave.
2. Look at the current station.

__My pioneer version (and OS):__
20220203-win

The attached file was simply renamed so it would go through the upload extension filter, there was no modification to the file content of my save-file.
[Pioneer-Port_Potts-ship_buried-231207.zip](https://github.com/pioneerspacesim/pioneer/files/10253091/Pioneer-Port_Potts-ship_buried-231207.zip)

**Update 1**
Another example, from Ubahanyo system James Station.
![screenshot-20221227-213941](https://user-images.githubusercontent.com/2823807/209749159-33f80f20-3487-45f4-bcac-56e67049ac92.png)
![screenshot-20221227-214017](https://user-images.githubusercontent.com/2823807/209749161-b2301e0d-5cf1-48af-8c64-0f6e30331649.png)

**Comment by Web-eWorks** [comment]
Tracking in #5154.
