### ISSUE TITLE
Missing crosshair and target square

### ISSUE THREAD

**Issue by robothauler** [pioneerspacesim/pioneer#5448]
If accepting a local search & rescue mission and clicking on "Set destination as navigation target" the crosshair and the square disappears.

Warning: Caught error in Lua UI code:
        [T] pigui/modules/flight-ui/indicators.lua:121: attempt to index field 'path' (a nil value)

Current master branch

**Comment by WKFO** [comment]
That's my code. Let's see what I broke... again.
