### ISSUE TITLE
Planet rings in shadow dissapear 

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#5461]
### Observed behaviour
Looks weird when ring is completely gone, simply because it's eclipsed by the planet

![2022-12-27-101612_1232x662_scrot](https://user-images.githubusercontent.com/619390/209661951-7af83a99-e41d-4f03-8e7d-2f0121dbe990.png)

### Expected 
Technically, rings are thin, and stars might shine through, if no sun light is hitting the ring, so this might be correct, but from game play perspective, it looks a bit buggy? 

Close or keep this issue open?

**Comment by impaktor** [comment]
This might be screen related, as in @nozmajner's photo, it looks good:
![image](https://user-images.githubusercontent.com/619390/209667465-cb0f2260-06ff-4608-88c6-d1363ba3d8cb.png)

**Comment by Web-eWorks** [comment]
This is an issue with your screen - you can see the absence of stars in the original image where the rings are occluding the background.
