### ISSUE TITLE
Lua UI error on hyperjump

### ISSUE THREAD

**Issue by Bodasey** [pioneerspacesim/pioneer#5463]
### Observed behaviour

Info: 0 clouds brought over
Info: Stars picked from galaxy: 0
Info: Generating 125000 random stars
Info: Final stars number: 125000
Info: Started hyperspacing...
Warning: Caught error in Lua UI code:
        [T] pigui/modules/flight-ui/system-overview.lua:55: attempt to index field 'system' (a nil value)
Info: Stars picked from galaxy: 125000
Info: Generating 0 random stars
Info: Final stars number: 125000
Info: NEWS created: #news = 1
Info: CreateCollisionMesh for : (cargo)
Info: DEBUG: Jumps since warranty: 0

...and the overview window cannot be toggled any more, therefore no destination or command can be selected for the autopilot.

Test hyperjumps was from Jupiter to Ross 248 and Luyten 726-8, both failed.

### Steps to reproduce

Start a hyperjump

__My pioneer version (and OS):__
actual master on SuSE Linux 15.4

Workaround: save the game and restart the program

**Comment by Web-eWorks** [comment]
Another workaround is to press `Ctrl + Delete`. Thanks for reporting, shouldn't be a difficult fix!
