### ISSUE TITLE
Offered the same item multiple times

### ISSUE THREAD

**Issue by DynV** [pioneerspacesim/pioneer#5465]
### Observed behaviour
In Bulletin Board (after clicking Show comms while docked), there was 2 listings of the same item.

### Expected behaviour
There would be a single listing for each offered item.

### Steps to reproduce

1. Load the attached gamesave
2. look at the Bulletin Board (of the current docked station)
3. look at the offers.

__My pioneer version (and OS):__
20220203-win

The attached file was simply renamed so it would go through the upload extension filter, there was no modification to the file content of my save-file.
[Pioneer-Yoan_Faure-250621-2X_same_offer.zip](https://github.com/pioneerspacesim/pioneer/files/10328601/Pioneer-Yoan_Faure-250621-2X_same_offer.zip)
![screenshot-20230101-045732](https://user-images.githubusercontent.com/2823807/210167200-6bf7a333-036b-449e-b29c-b919f61ada71.png)

**Comment by impaktor** [comment]
I don't think this is a bug, it just happened to be two people selling the same item at the same time. It's clearly picked two different flavours of the second hand bbs advert.

**Comment by Web-eWorks** [comment]
Not a bug, this is intended behavior.
