### ISSUE TITLE
[FEAT] Black hole renderer

### ISSUE THREAD

**Issue by Kochise** [pioneerspacesim/pioneer#5485]
Check this : https://github.com/rossning92/Blackhole

Regards.

**Comment by nozmajner** [comment]
Thanks! I've noted it down on our dev forum,

**Comment by impaktor** [comment]
If I'm not mistaken, the Interstellar black hole was for one very specific angle rel. the accretion disc. I wonder if it's possible to see it from other angles.

**Comment by nozmajner** [comment]
I'd guess it would distort the stars, but that wouldn't be that prominent

**Comment by Kochise** [comment]
https://www.youtube.com/@ebruneton/videos
