### ISSUE TITLE
Auto-pilot becomes very slow, need to manually go forward for it to behave normally

### ISSUE THREAD

**Issue by DynV** [pioneerspacesim/pioneer#5497]
### Observed behaviour
The auto-pilot becomes very slow > 135 Km from the target station as well as > 110 Km from the surface (coming at an angle). The doesn't make any sense to me, so I toggle to manual controls and go forward some Kms (probably < 50) then reengage it and it behaves normally. Normally when I want to hover with my ship the thrusters work considerably more, which to me hints of a gravity abnormality. As you can see in a screenshot it took > 19 hrs to travel > 8 Mm on a planet with 0.3g with ~5% fuel.

I know the fuel is low but I've done _plenty_ of missions between 2 stations on, or orbiting, the same planet, and I don't recall ever experiencing anything close to this before.

### Expected behaviour
Coming in--much--faster at the point of the trajectory.

### Steps to reproduce
1. Load gamesave
2. Change time acceleration (auto-pilot docking already set)
3. Keep an eye on the speed for a drastic drops a good distance before the target

__My pioneer version (and OS):__
20220203-win

The attached file was simply renamed so it would go through the upload extension filter, there was no modification to the file content of my save-file.
![screenshot-20230127-033235](https://user-images.githubusercontent.com/2823807/215068325-f98c5730-50df-4999-99c9-415d574fc97f.png)
![screenshot-20230127-033833](https://user-images.githubusercontent.com/2823807/215050080-ee497829-1f04-4a8a-b84c-ecc7883c1da8.png)
![screenshot-20230127-045618](https://user-images.githubusercontent.com/2823807/215066484-c0fcf0cd-54de-4efa-afdd-23dfc3d5e9d7.png)
![screenshot-20230127-053602](https://user-images.githubusercontent.com/2823807/215066490-f24cecfd-b0b4-4192-bb9d-4ebacf92149e.png)
[Pioneer-Yoan_Faure-260726-19hrs_8Mm_0.3g.zip](https://github.com/pioneerspacesim/pioneer/files/10518023/Pioneer-Yoan_Faure-260726-19hrs_8Mm_0.3g.zip)

**Comment by nozmajner** [comment]
Could you please test #5481? Maybe it alleviates the problem?
(Note, your save won't load with that build)

**Comment by DynV** [comment]
> Note, your save won't load with that build
Sorry but I'll stick with my save-files until the next official (non-nightly) release.

**Comment by azieba** [comment]
@DynV, can you use this command in the lua console after loading your savefile?:
`require("Game").player:SetFuelPercent(100)`
It will set the ship fuel to 100%. This way you can verify if it is related to fuel status.

**Comment by DynV** [comment]
At 20, 10 & 6% the autopilot docking works as usual. By both not touching the fuel from the gamesave and setting it at 5% right after loading it, I encounter the bug. Still, at 0.3g to keep that slow descent rate without autopilot, I think the tank would become empty before reaching the target station.
![screenshot-20230128-194236](https://user-images.githubusercontent.com/2823807/215301424-76385ded-9262-4f1e-9a1d-b7ec179cbd36.png)
![screenshot-20230128-213609](https://user-images.githubusercontent.com/2823807/215301416-84827f42-ff40-4358-837f-502b30dd5e92.jpg)

**Comment by azieba** [comment]
I have checked the save from @DynV on 20220203 with my changes from #5481 and indeed it alleviates the problem.

When the autopilot is engaged it sets fuel reserve to half of current fuel but not more then 25%. Reengaging the autopilot resets the reserve. The available fuel for the autopilot is curentFuel - reserve. It tries to limit the ship speed on this basis.
It might be ok, but the autopilot in this case starts to switch erratically between states in the middle of the approach and later overshoots wasting more fuel then expected. When it compensates the overshoot and gets to 0 speed the "fuelspeed" at this point is also 0 because of the wasted fuel and it basically stops.

My changes fix the overshoot as well as the state switching and the ship lands smoothly.

**Comment by DynV** [comment]
My main issue is that the ship seem to hover, as in having anti-gravity apparatus. Of course I prefer the auto-pilot to behave better, as probably with your fix, but if it goes berserk, that physics doesn't veer so much from real ones (in a similar case in real life).

**Comment by azieba** [comment]
> My main issue is that the ship seem to hover, as in having anti-gravity apparatus.

The thrusters are the anti-gravity apparatus. They are on when the ship hovers. It is fine.

**Comment by DynV** [comment]
Look at the screenshots, look at the fuel, look at the time, OMG, why do I need to point everything out?

**Comment by azieba** [comment]
> Look at the screenshots, look at the fuel, look at the time, OMG, why do I need to point everything out?

I have loaded your save and yes after starting the hover the ship has thrusters on. Even on your screenshot if you look carefully you will see a thruster flames, not very bright over the red planet background but they are there.

**Comment by DynV** [comment]
The OP 1st SS shows the fuel is ~5%, the 3rd one is ~3% 13:48:44 later, which is the equivalent of 4:08:37 at 1g. Try hovering for 13:48:44 at .3g or 4:08:37 at 1g and see how much fuel you use.

**Comment by azieba** [comment]
> The OP 1st SS shows the fuel is ~5%, the 3rd one is ~3% 13:48:44 later, which is the equivalent of 4:08:37 at 1g. Try hovering for 13:48:44 at .3g or 4:08:37 at 1g and see how much fuel you use.

I do not get your point. So the trustees are on and the ship uses fuel. Do you think it uses too much or too little?

**Comment by DynV** [comment]
> too little
^

**Comment by azieba** [comment]
> too little

Then it is a rebalancing request not a bug, I suppose.

**Comment by nozmajner** [comment]
> Look at the screenshots, look at the fuel, look at the time, OMG, why do I need to point everything out?
Please maintain civility and proper communication manners.
> too little
Our ships are obscenely strong and efficient. Thermodynamics breaking efficient. There's no way around it, if we want any half-reasonable travel times.
True, maneuvering thrusters could (and in my opinion should) be much less efficient, but even then you'd get quite a lot of hover out of them, especially on low G worlds. That was the case for a long time becuase of an undiscovered bug in the thruster cod, but that got fixed.

**Comment by Web-eWorks** [comment]
2% of fuel in a Skipjack is several tons of hydrogen. That provides a very large amount of thrust, verging on several hundred km/s of deltaV in a low-fuel / low-lading state.

Is there an actual bug here other than the obnoxiously slow descent towards the pad? I'd certainly like to see smarter behavior from the autopilot (being able to perform a forward-moving landing or take over and land without flying back up to 1km), but I'm not seeing any of the ancillary issues qualifying as bugs in their own regard.

**Comment by DynV** [comment]
> Is there an actual bug here other than the obnoxiously slow descent towards the pad?

Since it seems I'm the only one that think that's not enough for a vessel that seemingly weighs 2 houses hovering for the equivalent of 4:08:37 at 1g, no; maybe even a 3rd considering the coolant, lubricants, water, food, etc.

**Comment by Web-eWorks** [comment]
According to your screenshots, you've consumed 200km/s of the 496km/s deltaV available in stored fuel over ~18 hours. The planet has a nominal gravity of 0.3g (closer to 0.25g at 25km altitude), which requires you to passively expend 3m/s of deltaV, every second, to remain hovering. 200km·s at that expenditure rate lasts for ~67,986 seconds, or roughly 18.8 hours.

The relative balance of ships is not salient to the bug report. For the purposes of determining whether or not there is a bug regarding the conservation of fuel, it is *entirely intended* that you can hover at 0.3g for 18+ hours on 5% fuel. In fact, you could most likely hover for 36 hours and land perfectly fine on the remaining 96km/s deltaV. The Apollo missions managed to deorbit and land on the moon on approximately 2km/s of dV 50 years ago, you can definitely land from an already-ballistic trajectory on 96km/s.

For your mental comparison purposes, your three houses are being held up by the endurance equivalent of 21 fully-fueled Falcon 9 launch vehicles (at ~9km/s dV total for both stages with nominal payload).

**Comment by Web-eWorks** [comment]
@azieba if interested in looking into this issue, it seems the relevant behavior is occurring in the "stage 1 approach" AICmdFlyTo generated by AICmdDock (ShipAICmd.cpp line ~1357):

```c++
	// if we're not close to target, do a flyto first
	double targdist = m_target->GetPositionRelTo(ship).LengthSqr();
	if (targdist > 16000.0 * 16000.0) {
		m_child.reset(new AICmdFlyTo(m_dBody, m_target));
		ProcessChild();
		return false;
	}
```

I suspect this may be related to the low-fuel handling in AICmdFlyTo (specifically, the ship's Propulsion fuel reserve is set to half remaining fuel when the dock command is first issued) generating a negligible target velocity, though this is only a hunch.

**Comment by azieba** [comment]
@Web-eWorks I have already stated that my changes from #5481 fix this issue. The autopilot stops acceleration when it reaches fuel reserve. This is fine when it already has some speed as it will just keep cruising, but in the case from this bug the autopilot overshoots and when it gets back to 0 speed does not accelerate any more. With my changes there is simply no overshoot.

**Comment by Web-eWorks** [comment]
> I have already stated that my changes from https://github.com/pioneerspacesim/pioneer/pull/5481 fix this issue.

My apologies, I overlooked that comment when I was re-reading the issue. Thank you for checking that (and fixing the underlying bug!)
