### ISSUE TITLE
Scanner installation issue.

### ISSUE THREAD

**Issue by antonspace** [pioneerspacesim/pioneer#5500]
### Observed behaviour

Skipjack only allows installation of one scanner, either a surface scanner or an orbital scanner.

All other ships tested (pumpkinseed, mola ramsayi, wave) allow multiple scanner installations, including multiple instances of the same scanner type, up to a maximum of 8.

### Expected behaviour

Expected behaviour would be to allow one surface scanner and one orbital scanner to be installed, or perhaps one of each model, 4 in total.

__My pioneer version (and OS):__

20230125
Linux Mint
![Screenshot_2023-01-29_09-29-03](https://user-images.githubusercontent.com/32020353/215318547-449122b9-b637-441c-a587-baeb216eb4d7.png)
![Screenshot_2023-01-29_09-34-22](https://user-images.githubusercontent.com/32020353/215318578-4b72cb22-de97-49b9-8c18-732ed18dc683.png)

**Comment by impaktor** [comment]
I don't think this is a bug, as much as it is other ships defaulting to 4, and this ship has it hardcoded, to demonstrate how to set it. 

@nozmajner How do we want ships to be able to fit sensors? 2 sensor slots allows ships to do both surfase and orbital scans (if they also have leftover cargo space). Not sure if 4 slots is meaningful, but we do have two flavours of both surface and orbital scanner.

**Comment by antonspace** [comment]
While it makes no sense to allow multiple instances of the same scanner model to be installed as is currently the case, after completing multiple orbital scanning missions, my 2 cents would be that having both orbital scanners is preferred if cargo space allows.
 The first orbital scanning mission I ever attempted was of Umbriel, moon of Uranus, in a Skipjack which only allows one orbital scanner to be installed, thinking that more expensive is better, I chose the XKM-1750 for this mission. At medium orbit the ship was below the minimum altitude, and at high orbit the "current frame of reference" switched from Umbriel to Uranus, which stopped the scanner from working, so I was not able to complete the mission with the more expensive scanner, if I had the cheaper scanner also then it is possible that it would have worked at medium orbit. (not had a chance to confirm this).

Strangely, if only one orbital scanner  were permitted, I would go for the cheaper XKM-650 every time, which is counter intuitive, here is why:-

1) Takes up less cargo space
2) Everything else being equal, the cheaper model is faster at collecting the data than the more expensive model, and speed seems to the most important factor in these missions. There were times when the more expensive scanner worked at high orbit and medium orbit (higher is faster), while the cheaper scanner only worked at medium orbit, yet data collection by the cheaper scanner at medium orbit was slightly faster than the expensive model at high orbit.

Not sure this behaviour is intended, maybe some tweaking is needed to make the more expensive scanner  preferable, perhaps offering a bonus for data collected with the more expensive scanner ("the resolution's better than expected captain, here is a bonus), or offering missions with a higher reward that can only be completed with the more expensive scanner (higher resolution missions)?

**Comment by impaktor** [comment]
Moving equipment to cargo space, and not allowing multiple of identical type, I think is what @Web-eWorks is working on for his new equipment implementation, so consider it "work in progress".

The more expensive scanner should be easier/faster to use. At least it allows you to fly at a higher altitude. (Spoiler: the model number is the max(?) altitude, I think, in meters for surface scanner and in km for orbital scanner).

The other problem you describe, of it scanning the wrong body / frame, sounds like a bug / not planned that way, I think, unless it's same as #5504.

**Comment by antonspace** [comment]
The more expensive orbital scanner is slower at collecting data than the cheaper one, every time. Easy to verify. Should I open an issue about this?
Also, I have noticed one instance where the more expensive orbital scanner starts scanning above the "maximum scanning altitude" another issue?
![Screenshot_2023-01-30_10-30-21](https://user-images.githubusercontent.com/32020353/215467543-1591d94f-1339-4556-8f8d-29f41b3992b8.png)

**Comment by impaktor** [comment]
@Web-eWorks See latest post above.

**Comment by impaktor** [comment]
@antonspace I've reduced default number from 8 to 2. I've (hopefully) fixed most of your reported bugs, so please pull from master, so you get the bug fixes, before playing / reporting any more bugs. Thanks for testing!

**Comment by Web-eWorks** [comment]
> Strangely, if only one orbital scanner were permitted, I would go for the cheaper XKM-650 every time, which is counter intuitive, here is why:
>
> - Takes up less cargo space
> - Everything else being equal, the cheaper model is faster at collecting the data than the more expensive model, and speed seems to the most important factor in these missions. There were times when the more expensive scanner worked at high orbit and medium orbit (higher is faster), while the cheaper scanner only worked at medium orbit, yet data collection by the cheaper scanner at medium orbit was slightly faster than the expensive model at high orbit.

This is *partially* intended. Unless you're specifically taking high-value scan missions to scan gas giants or terrestrial planets rather than asteroids and small moons, the "cheaper" scanner module will be more profitable.

However, the more expensive scanner will actually be faster than the cheap scanner if you manually adjust your orbit beyond the high/medium orbit presets. The Scan Manager interface will tell you the maximum scan orbit you can accomplish the mission at - as long as the body's frame of influence extends that far, you'll scan a significantly wider swathe of the body with an expensive scanner at *its* maximum altitude than you will be able to with a cheap scanner.

That being said, the orbital velocity is a good bit different between the two maximum altitudes, so we may tweak the expensive scanner slightly to make up for it.

**Comment by Web-eWorks** [comment]
> Also, I have noticed one instance where the more expensive orbital scanner starts scanning above the "maximum scanning altitude" another issue?

The scan manager shows maximum altitude as relative to the body's sea-level altitude (the average surface height). The flight HUD either displays the "radar altitude" relative to the terrain directly below the ship, or the distance to the body's center once you're a certain distance away from the body. Thus, the two numbers are sometimes not directly comparable.

This is something that's better addressed (and discussed) in a separate issue.

**Comment by antonspace** [comment]
I had no idea you could manually adjust the orbit beyond what the autopilot sets, would like to know how to do this. I tried doing this in a previous instance where the autopilot's orbits were not able to be used with the scanner, by just using the up thruster, and failed. Would assume it involves precise combination of both speed and altitude?

**Comment by Web-eWorks** [comment]
> would like to know how to do this

Point the ship towards the diamond that indicates your velocity vector and thrust forwards to increase the altitude of your orbit, or backwards to decrease the altitude. This is *technically* the basics of orbital maneuvering that we'd like to teach the player if we had the developer resources to commit to making tutorials, but instead we just have to assume you can learn from the vast reams of Kerbal Space Program content out there.

Unfortunately there's not currently any way for the player to specify the orbital height for the autopilot to enter, or any display of apoapsis/periapsis altitudes for your current orbit.

**Comment by impaktor** [comment]
> I had no idea you could manually adjust the orbit beyond what the autopilot sets, would like to know how to do this

One of the key concepts of pioneer is Newtonian mechanics (as a two-body system). We have an orbit planner tool in F6, which shows in blue. Documentation is maybe lacking (check our wiki, to be sure)

> This is partially intended. Unless you're specifically taking high-value scan missions to scan gas giants or terrestrial planets rather than asteroids and small moons, the "cheaper" scanner module will be more profitable.

I'll see if I can think of some in-game lore way to convey this through the Advice module.

**Comment by antonspace** [comment]
This is a very interesting aspect of the game, and can't wait to learn more, will look into the Kerbal Space Program documentation, and play around with the orbit planner until it makes sense, the blue onscreen maneuver burn info is very neat, this promises to be way more fun than just using the autopilot to set the orbit, the orbital missions just took on a whole new depth, as did space flight in general. Thankyou for the help.
