### ISSUE TITLE
Small issue on mission page after completing mapping mission.

### ISSUE THREAD

**Issue by antonspace** [pioneerspacesim/pioneer#5501]
### Observed behaviour

Got the mapping missions working by implementing the relevant pull request by Web-eWorks, and recompiling.

Accepted a mapping mission of Mercury in the Torvalds platform bulletin board.

Flew to Mercury and completed the mission.

On the return journey, the mission page has the following text:-

Hi!
I'm with the geographical society, and we need to update our maps of Torvalds Platform ,,,.. Should of course still be Mercury here.

__My pioneer version (and OS):__

Latest code.
Linux Mint.
![Screenshot_2023-01-29_11-01-35](https://user-images.githubusercontent.com/32020353/215322769-d7fcfd1a-6c07-4689-a8b3-9c8cc6669418.png)

**Comment by impaktor** [comment]
Sounds like return location and mission location gotten mixed up

**Comment by impaktor** [comment]
Indeed, once scan is complete, the `mission.location` updates, to the return station, which (usually*) is the same as you accepted the mission in. The first "torvalds platform" is wrong, the second is correct. We probably need to store this as a separate variable for each mission.

_(*) except for flavour 9: "Will pay for fast delivery of data on {systembody} in {system}"_

**Comment by impaktor** [comment]
Btw, do you have a save of this? I.e. when finished a scan, but not gotten payed yet?

Very much preferred if on a very recent version of pioneer master, that includes the new dynamic in-system economy (it's a save breaking change). If compilation is slow we have build artifacts [here](https://github.com/pioneerspacesim/pioneer/actions/runs/4021731493)

**Comment by antonspace** [comment]
No save for this particular mission, however I can post a save of current or future missions that exhibit this same behaviour?

The code is from 20230125, with additional changes to fix the mapping mission issue #5493, OS, Linux Mint.

**Comment by impaktor** [comment]
No need to post save, I think I've fixed it.

Might be good idea to update to latest master, econ improvement went in 2 days ago. Also, there's memory leaks fixes, and other stuff, for you to break.... I mean test ;) 

Thanks for reporting the bugs. We want to find as many as possible before stable release on Friday.

**Comment by antonspace** [comment]
Will update to latest code and continue testing, thanks.
