### ISSUE TITLE
Orbital scanning mission issue.

### ISSUE THREAD

**Issue by antonspace** [pioneerspacesim/pioneer#5503]
### Observed behaviour

While undertaking an orbital mapping mission, the mission details page describes the type of mission as a "Surface Scan"

### Expected behaviour

Would expect it to say "Orbital Scan"
![Screenshot_2023-01-29_15-00-23](https://user-images.githubusercontent.com/32020353/215335713-be8ea8d5-c6aa-4191-97d5-9c6a81c86345.png)

**Comment by impaktor** [comment]
Are you sure it's an orbital mission? Have you scanned it? Did you use the orbital or surface scanner? Did you fly close to the surface (100 m), or from high altitude (many km)?

A quick glance, I don't see anything wrong in the code.
`{luc.TYPE..":",   mission.orbital and l.ORBITAL_SCAN or l.SURFACE_SCAN}`

**Comment by antonspace** [comment]
It is definitely an orbital mission, the next issue I am about to post should clarify this.

**Comment by impaktor** [comment]
Indeed, I'm seeing it too. This is strange. Will investigate

**Comment by impaktor** [comment]
Hmm, `mission.orbital = nil`, at this point.

**Comment by impaktor** [comment]
Found it!

@antonspace btw, if you want to experiment with finding more bugs: flavor 9, uses some unique code path, in that it will change the return destination upon scan completion, to something nearby, feel free to see if you can find something strange with that too, but you need the code fixes in #5505 (no compilation required). If you want to force that flavor, set `flavourN=9` in `makeAdvert()` (line 442, for me), in data/modules/Scout/Scout.lua
