### ISSUE TITLE
Discrepency between mssion details page and scan manager

### ISSUE THREAD

**Issue by antonspace** [pioneerspacesim/pioneer#5504]
### Observed behaviour

Currently running an orbital scanning mission, the mission details page lists the coverage as "607m", while the scan manager lists the required target coverage as 60.8%

BTW, scanning 60.8% of a planet is a huge undertaking, even running at x100 (>>>) I reckon it will take about an hour real time to complete the mission.

![Screenshot_2023-01-29_15-00-23](https://user-images.githubusercontent.com/32020353/215336657-548f3d0f-08fd-4bc5-9620-2df13c999788.png)
![Screenshot_2023-01-29_15-16-41](https://user-images.githubusercontent.com/32020353/215336662-1c577b22-47ec-43e0-962a-23d85b2a0bdf.png)

**Comment by impaktor** [comment]
Just out of curiosity, what happens if you select a surface scanner? Could the bug be that this is actually a surface scan mission, but the game allows you to select the orbit scanner, when in fact it should only allow surface scanner to progress the scan?

**Comment by antonspace** [comment]
I can't select a surface scanner as the ship doing the scan is a Skipjack, which only allows one scanner to be installed at any one time. #5500   
Here is the mission in question:-
![Screenshot_2023-01-29_15-52-11](https://user-images.githubusercontent.com/32020353/215338412-141ca233-f067-4d47-ba29-701bac428844.png)
