### ISSUE TITLE
Cheating to another ship in external view crash the game

### ISSUE THREAD

**Issue by DynV** [pioneerspacesim/pioneer#5506]
### Observed behaviour
Cheating to another ship in external view crashes the game. I thought about my [passenger transfer issue](https://forum.pioneerspacesim.net/viewtopic.php?f=3&t=713) and wondered if by cheating to another ship if it would fix it so I tried `require "Game".player:SetShipType("ac33")` but my game crashed. After a few seconds it dawned on me that the sudden model change might be the issue so after reloading I changed to internal view before the command and it worked.

### Expected behaviour
The command to go through, even if that mean doing so automatically change to internal view.

### Steps to reproduce
1. Either load a game or start a new one
2. Ensure the view isn't internal
3. Do the command
> `require "Game".player:SetShipType("shipname")`
> "shipname" is the filename of the ship's .json in the data/ships/ directory (without extension). Eg: ...SetShipType("amphiesma")
to another ship.
4. The game should crash either immediately or after a few seconds being unresponsive

__My pioneer version (and OS):__
20220203-win

**Comment by Web-eWorks** [comment]
Fixed in master already.
