### ISSUE TITLE
Mapping mission that Orbital Scanner XKM-1750 is unable to resolve.

### ISSUE THREAD

**Issue by antonspace** [pioneerspacesim/pioneer#5508]
### Observed behaviour

Accepted a mission to perform an orbital scan of Gikegaryu F1, flew to vicinity of Gikegaryu F1, then used autopilot to get into a high orbit around the planet. Engaged Orbital Scanner XKM-1750 when the current frame of reference was Gikegaryu F1, scanning started briefly, but as the autopilot neared high orbit, the scanner no longer worked because the "minimum altitude" had been reached.

### Expected behaviour

One would expect the premium scanner would be up for the job, I worked my ass off shuttling green haired humanoids around the galaxy in order to buy this premium piece of kit, where do I get a refund? ;-)

### Steps to reproduce

Load the savefile, you are already in the vicinity of Gikegaryu F1.
[sinonatrix_15.gz](https://github.com/pioneerspacesim/pioneer/files/10539583/sinonatrix_15.gz)
(the attached file was renamed by adding .gz to allow upload).
Use the autopilot to enter a high orbit of the planet.
When close enough to engage the scanner, engage it, making sure the Orbital Scanner XKM-1750 is selected, it should work briefly.
As the ship approaches close to high orbit altitude, the scanner will reach "minimum altitude" and stop working.
The Orbital Scanner XKM-650 does work in this high orbit.

__My pioneer version (and OS):__

20230129
Linux Mint.
![Screenshot_2023-01-30_19-28-42](https://user-images.githubusercontent.com/32020353/215589649-b44040a0-f069-41d0-ac81-f62b7763c1fc.png)
![Screenshot_2023-01-30_19-11-56](https://user-images.githubusercontent.com/32020353/215589720-f9552a29-348b-4013-87ca-1efead1dbe30.png)

**Comment by Web-eWorks** [comment]
> MINIMUM ALTITUDE

The save as provided has the player's ship outside of the frame of Gikegaryu f 1. That being said, the distance from the planet's sea level altitude to the player's ship is not displayed on the flight HUD, so in reality you're at a ~1.714Mm mean altitude. That's not far enough for the XKM-1750 to start operating, as it requires a 1.750Mm altitude.

**Comment by antonspace** [comment]
The save is just the location where the autopilot's "fly to vicinity of Gikegaryu f 1" stops, when the autopilot's high orbit option is selected, and the ship moves towards Gikegaryu f 1,  Gikegaryu f 1 becomes the current frame of reference when at an altitude approx 2.44Mm, this is when the scanner starts working (scanners only work if the current frame of reference is the planet due to be scanned, irrespective of the altitude above that planet). Between 2.44Mm and 2.33Mm (high orbit altitude of Gikegaryu f 1) is where MINIMUM ALTITUDE for Orbital Scanner XKM-1750 is reached. Hope this makes sense.

**Comment by antonspace** [comment]
![Screenshot_2023-01-30_23-17-40](https://user-images.githubusercontent.com/32020353/215619592-aa95e0db-ed2b-425b-a7a6-5c177b1f3efb.png)
![Screenshot_2023-01-30_23-19-01](https://user-images.githubusercontent.com/32020353/215619599-f593baf1-d335-45f2-8603-62011e1d85ef.png)

**Comment by antonspace** [comment]
I now get there is a difference in altitudes depending where it is measured from, still, if the scanner is not able to use the autopilot's orbits, the average space cadet lacking in the fine art of manual orbit calculations will probably need to carry both orbital scanners before embarking on a mission, because there will be many missions where installing just one of the scanners is not going to get a result as in the case above.

**Comment by Web-eWorks** [comment]
I'll see if I can squeeze in a quick bugfix to display the sea level altitude instead of distance-to-center for this patch, to make it less confusing at the very least.
