### ISSUE TITLE
Time acceleration in Bulletin Board leads to negative mission time and possible error.

### ISSUE THREAD

**Issue by antonspace** [pioneerspacesim/pioneer#5512]
### Observed behaviour

Using the time acceleration feature in the Bulletin board will result in the mission times running down to zero, then into negative territory. Clicking on another tab, or a mission that still has a positive time will clear out the missions with a negative  time, but clicking on a mission with a negative time will cause an error.

### Expected behaviour

The expected behaviour would be that the missions on the bulletin board would be cleared when the time remaining is less than is practically possible to complete the mission. without having to leave the tab, or take some other action to refresh the page.

### Steps to reproduce

Use time acceleration while remaining in the bulletin board.

__My pioneer version (and OS):__

20230131
Linux 
![Screenshot_2023-01-31_19-22-45](https://user-images.githubusercontent.com/32020353/215875314-3be6562f-5c9f-4620-b9bb-f10c394c6bb4.png)
![Screenshot_2023-01-31_19-24-05](https://user-images.githubusercontent.com/32020353/215875390-744d738b-e9b0-4b24-ac12-c205dd6c098e.png)

**Comment by impaktor** [comment]
You have an output.txt as well for that crash? (might not be needed, since it's obvious invalid, but doesn't hurt)

**Comment by antonspace** [comment]
[output.txt](https://github.com/pioneerspacesim/pioneer/files/10551344/output.txt)
