### ISSUE TITLE
Build failed for ALT Linux due to -Werror=return-type

### ISSUE THREAD

**Issue by Gliese852** [pioneerspacesim/pioneer#5532]
### Observed behaviour
Compiler version:
x86_64-alt-linux-g++ (GCC) 12.1.1 20220518 (ALT Sisyphus 12.1.1-alt2)

Because in ALT Linux gcc has the `-Werror=return-type` flag set by default, build error occurs here:
```
.../src/pioneer/src/pigui/PerfInfo.cpp: In member function ‘PiGui::PerfInfo::CounterInfo& PiGui::PerfInfo::GetCounter(CounterType)’:
.../src/pioneer/src/pigui/PerfInfo.cpp:115:1: error: control reaches end of non-void function [-Werror=return-type]
  115 | }
      | ^
cc1plus: some warnings being treated as errors
```

the default is a warning, but the situation borders on UB.
In the distribution, this flag was set due to several cases, for example [this](https://git.altlinux.org/gears/s/synaptic.git?p=synaptic.git;a=blob;f=synaptic/gtk/rguserdialog.cc;h=83349c1e64c61013dac72fe293a8055d84558b36;hb=cfd2d6d12072ecb8bd1c38cdd1cdf39c71e1ba28#l211).  There were troubles due to such non-void functions that did not return a value, when changing the compiler version, new synaptic began to crash due to double-free.

EDIT:
Here is some more information about it:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=87515

__My pioneer version (and OS):__
20230203

**Comment by Web-eWorks** [comment]
> but the situation borders on UB

The function is designed such that exiting the switch case without returning a value is an unreachable path. That being said, I don't believe there's a cross-platform equivalent of the `unreachable` attribute/decorator provided by GCC.

I don't mind cleaning that up a bit, but if the build still fails with a `default: assert(0);` switch case added then there is little that can be done to resolve it other than rewriting the surrounding code.

**Comment by Gliese852** [comment]
@Web-eWorks `std::exit(1)` or `throw` works. (After all, you are sure that you will not reach there).
Caught my eye [std::unreachable](https://en.cppreference.com/w/cpp/utility/unreachable), funny description - "Invokes undefined behavior."

**Comment by Web-eWorks** [comment]
Also only available in C++23, so definitely not usable for us... I'm quite happy with 17 right now.

Will amend that section soonish (probably today) once I've got the rendering closer to a stopping point.

**Comment by Gliese852** [comment]
There is another solution - `CC=/usr/bin/clang CXX=/usr/bin/clang++ ./bootstrap`
(clang they didn't patch)

**Comment by Web-eWorks** [comment]
Closing as `default: assert(0);` case was merged.

**Comment by Gliese852** [comment]
Sorry for doing this, but it doesn't solve the problem, (same error when building).
Probably because assert resolves to 
```
(static_cast < bool >
 (0) ? void (0) : __assert_fail("0", __builtin_FILE(), __builtin_LINE(),
								__extension__ __PRETTY_FUNCTION__));
```
And `__assert_fail` is linked dynamically, so the compiler can hardly be sure as much as we are, that the program will end here. Here is this symbol in the executable:
```
74: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND __assert_fail@GLIBC_2.2.5 (3)
```
