### ISSUE TITLE
Many clouds & station full + weapon on sale not installed

### ISSUE THREAD

**Issue by DynV** [pioneerspacesim/pioneer#5539]
## Bug 1
Many clouds & station full.

### Observed behaviour
A station both had many hyperspace departure clouds around it and refuses docking permissions as there's seemingly no free docking bay even though the interior seem far from full.
![screenshot-20230211-195818](https://user-images.githubusercontent.com/2823807/218288106-f103e376-bd5b-480e-9e5e-28aa99daed18.png)
![screenshot-20230211-195936](https://user-images.githubusercontent.com/2823807/218288121-6948b976-8e92-46c7-88d9-ca819f47f9ac.png)
![screenshot-20230211-200259](https://user-images.githubusercontent.com/2823807/218288165-df5f1a44-a115-47b5-957d-016832e135ea.png)

### Expected behaviour
The station either be
- full and look full, or
- look sparsely filled and not be full

and for both cases not have this many hyperspace departure clouds.

### Steps to reproduce
1. Load gamesave
2. optionally change time acceleration
3. drop to 1X time when receiving the permission refusal in comms
4. observe.

__My pioneer version (and OS):__
20230203-win

The attached file was simply renamed so it would go through the upload extension filter, there was no modification to the file content of my save-file.
[Pioneer-Yoan_Faure-20230203-230212-Jobs_Pad_full_and_many_clouds.zip](https://github.com/pioneerspacesim/pioneer/files/10715069/Pioneer-Yoan_Faure-20230203-230212-Jobs_Pad_full_and_many_clouds.zip)

**Update 1**
Not as bad but striking
![screenshot-20230219-095608](https://user-images.githubusercontent.com/2823807/219957462-333f4efc-9fed-44ce-8967-d6f8bcbeee53.png)
and _right above_ the target there was 4.

## Bug 2
Weapon on sale not installed.

### Observed behaviour
Continuing from the gamesave which a copy have been uploaded in this post, I had a fight and realized the weapon discharge has a color different than what I had with on my previous small plasma accelerator on a Skipjack on the previous release (20220203-win). I then checked on my equipment and the weapon was the same as before I bought the small plasma (4MW pulse), I then checked my flight log tab station and I did have a money drop close the the price of a small plasma on sale (from London to LA).

### Expected behaviour
Either
- the weapon get installed when the money for it is reduced or
- no weapon is installed and the money stay the same.

### Steps to reproduce
1. Load gamesave
2. notice weapon
3. search the flight log tab station for a money drop close the the price of a small plasma accelerator on sale.

**Comment by nozmajner** [comment]
I'd like to add that this hypercloud happens a lot at ground stations as well, especially when you arrive into a system and fly to one. It seems that it does not happen that much when you wait around on a station with time accel though. 
To me it seems that AI ships do not abide the stations hyperspace restrictions. I guess for AI ships that restriction could be a bit larger than for the player both for ground and orbital stations to avoid this kind of clutter. Maybe they could even fly a bit in a random direction before jumping.
![screenshot-20230220-180753](https://user-images.githubusercontent.com/4182678/220166848-56dbaad6-aa84-41bb-96f7-e0588ffeebe3.png)

**Comment by impaktor** [comment]
> do not abide the stations hyperspace restrictions

They don't. Never have. 

I've been thinking, it would be pretty cool, if when you lift off, you see, 10 km above you, a swarm of entry clouds, and you can then see where you need to go (in y-coordinate at least) to jump.

Regarding hyperspace clouds, if I remember correctly, fluffy added a drift factor on them, so they would slowly drift away.

**Comment by DynV** [comment]
This is insane, you can see for yourself with the attached gamesave.
![screenshot-20230228-232921](https://user-images.githubusercontent.com/2823807/222045801-87eaca42-4853-4076-b13e-a53bb7f803fc.png)
![screenshot-20230228-232930](https://user-images.githubusercontent.com/2823807/222045809-cefdfe55-cfbc-4a8c-9e40-8c453e4c4cbc.png)
![screenshot-20230228-232936](https://user-images.githubusercontent.com/2823807/222045816-eb6daff7-3ba1-49e3-95ac-5a4edadc606f.png)
![screenshot-20230228-232943](https://user-images.githubusercontent.com/2823807/222045821-8711b22d-65fb-4f04-a064-353e40b31f74.png)
![screenshot-20230228-232949](https://user-images.githubusercontent.com/2823807/222045830-750a319f-ffee-4175-a877-bc8b84301626.png)
![screenshot-20230228-232955](https://user-images.githubusercontent.com/2823807/222045832-bd8f2151-fc51-4a27-97d7-6b315f1fb319.png)
![screenshot-20230228-233005](https://user-images.githubusercontent.com/2823807/222045836-1e4451dc-071c-4765-ad54-c75f2aea7b42.png)
![screenshot-20230228-233041](https://user-images.githubusercontent.com/2823807/222045840-3243d45d-b514-4b74-8d73-c6cce2847a3a.png)
![screenshot-20230228-233045](https://user-images.githubusercontent.com/2823807/222045850-8e91d6b2-c368-4408-98ce-5b79bbf8f3f4.png)
[Pioneer-Yoan_Faure-20230203-230308-Lalande_21185-Andersen_City_many_clouds.zip](https://github.com/pioneerspacesim/pioneer/files/10857169/Pioneer-Yoan_Faure-20230203-230308-Lalande_21185-Andersen_City_many_clouds.zip)

**Comment by Web-eWorks** [comment]
I generally agree that this is a very unwanted behavior, both for the visual impact as well as the universe consistency factor that all of these ships are performing illegal hyperjumps in a way that misleads the player.

However, this is a very low-priority problem. As of the last time I looked into the issue, fixing this requires adjusting the ship AI abstraction to support queued commands establishing a flight path, or setting up "nanny delegates" for each ship to feed them flight commands after the previous command has finished. The issue will be addressed when the underlying AI framework is next addressed, which will most likely not be for some months yet.

**Comment by DynV** [comment]
As a workaround, perhaps giving each cloud a creation timestamp and setting up a cron to delete those having been up too long would work?

**Comment by impaktor** [comment]
> giving each cloud a creation timestamp

Without looking at the code, I believe we already do that. The entry cloud lives, as long as the exit cloud hasn't been generated, if I remember correctly.

**Comment by nozmajner** [comment]
I could replace the texture to a trasnparent one as a bandaid, so at least it is nat that jarring

**Comment by impaktor** [comment]
Many hyperspace clouds are not necessarily a bug. A while back we added a random drift to them, such that they will drift away from the station.

> This function has additional check against this values which are much less then in the previous check:

Ideally, it should get the distance by calling some function that returns what the legal min altitude is.

> `(is_legal == nil)`

Yes, classic Lua "gotcha".

I don't know what the optimal solution is for making tradeships have legal jumps, but we do have [timers](https://codedoc.pioneerspacesim.net/#CClass:Timer) in the API documentation (that is now always up-to-date), that could try to jump every N seconds when a ship is increasing distance from space station. (Alternative: Do we have event triggers for when entering an orbit / arrive at autopilot destination?).

The real bug warranting keeping this bug report open is not being able to dock. I don't know if @Gliese852 as fixed this issue since then?

(Although we're not against improving trader's jump code).

**Comment by Max5377** [comment]
I will post a video later to show how it looks like with my code. Gates Spaceport as a reference, because it's a pretty populated place.

**Comment by Max5377** [comment]
I recorded two videos before and after my code. Started new game on Mars before flying to Gates Spaceport and then waiting a little bit there:
### Before

https://github.com/pioneerspacesim/pioneer/assets/69468517/2d65f92f-584a-47ac-8fd5-5e19973d71fe



(Notice on 00:30 the distance of ~15km between station and cloud, despite `if (ship:DistanceTo(port) < 20000)`)

### After

https://github.com/pioneerspacesim/pioneer/assets/69468517/9a958b03-16d3-45a2-9782-4a0d87fe94e5



(No clouds at all first time and in the end I showed what I meant by "drifts in space")

P.S.: Hope it's not too compressed.

**Comment by Web-eWorks** [comment]
CC @Gliese852 as this is changing TradeShips behavior.

**Comment by Web-eWorks** [comment]
Closing - ships hyperjumping away while extremely close to the station has been resolved, and the equipment installation issue will become inapplicable with the pending introduction of Equipment v2 in 1-2 months.
