### ISSUE TITLE
Flatpak version crashes on new game

### ISSUE THREAD

**Issue by VortexAcherontic** [pioneerspacesim/pioneer#5541]
### Observed behaviour
Game crashes right after starting a new game when running the flatpak release.
The native  package from my distributions repositories works fine.

### Expected behaviour
- Game to start

### Steps to reproduce
- Install Pioneer via flatpak
- Start the game and select any starting location

__My pioneer version (and OS):__
Game version: 20230203
operating system: openSUSE MicroOS
Version of native package (which runs fine): 20230203

### Crash log
[output.txt](https://github.com/pioneerspacesim/pioneer/files/10717034/output.txt)

**Comment by Web-eWorks** [comment]
CC @pcercuei?

**Comment by pcercuei** [comment]
Sorry, I can't reproduce. The flatpak works perfectly fine here.
If you used a flatpak with the previous release, maybe try to trash the game's config/save files?

**Comment by VortexAcherontic** [comment]
Oh yes it seems there where old config files lying around causeing the issue.
After deleting everything under "/home/<user>/.var/app/net.pioneerspacesim.Pioneer" it worked great.

Thank you :)
