### ISSUE TITLE
Multiple empty face accessory items

### ISSUE THREAD

**Issue by Gliese852** [pioneerspacesim/pioneer#5550]
### Observed behaviour

https://user-images.githubusercontent.com/18342621/219796197-9625fd26-8ca1-4ab4-a80b-9db5f66f46c2.mp4

As shown in the video, you can click multiple times and nothing changes.
Apparently this is happening because in #5537 a lot of accessories have been removed.

__My pioneer version (and OS):__
https://github.com/pioneerspacesim/pioneer/commit/d25533200fe2acea82d24207209e5e504bd42b5b

**Comment by Web-eWorks** [comment]
Yes, this needs to be replaced with random face generation having a higher chance of "no accessory" compared to the other accessory items. Leaving this open so we don't forget it.

**Comment by zonkmachine** [comment]
Yeah, they were meant to be an approximation of a solution for testing purposes.
