### ISSUE TITLE
You can take off without meeting minimum crew requirements.

### ISSUE THREAD

**Issue by Inglonias** [pioneerspacesim/pioneer#5556]
### Observed behaviour
I am able to pilot my Skipjack all by myself, despite the ship's information saying I need a crew of at least two.

### Expected behaviour
I am prevented from launching

### Steps to reproduce
Get yourself a larger ship that requires a crew of at least two
Attempt to launch
You can launch

__My pioneer version (and OS):__
My pioneer version: 20230203
OS: Windows 10 Home 22H2

**Comment by Web-eWorks** [comment]
Tracking in #5688.
