### ISSUE TITLE
CMake build in VS2019 does not display commit version on startup screen

### ISSUE THREAD

**Issue by craigo-** [pioneerspacesim/pioneer#5565]
### Observed behaviour

The CMake build completes successfully using Visual Studio 2019 and produces binaries that execute. However, I've noticed that on the start screen, the commit version that is normally in brackets after the date is missing in my builds.

I have had a look at the start screen of your latest Windows artifact (under github's Actions) - version 20230303, and that displays the commit version in brackets as expected.

c.f. screenshots below.

Any idea why my build does not include this information?

### Expected behaviour

My build displays the commit version.

### Steps to reproduce

Build Process (sections as per COMPILING.TXT):

1.4.1: I have tried two methods.
Method 1: pioneer and pioneer-thirdparty projects forked and local copy created with Github Desktop
Method 2: pioneer and pioneer-thirdparty downloaded directly from project and unpacked locally as per instructions

1.4.4: x64-Release selected

__My pioneer version (and OS):__

Current master at time of writing (604336852b6ac0487cba1f5849224e1f41eb42c0)
Windows 10 Enterprise 22H2
Visual Studio Community 2019 16.11.24

My build:
![image](https://user-images.githubusercontent.com/4467963/222667407-d1a30498-f37d-475d-8457-66e930ab0466.png)

Your CI build:
![image](https://user-images.githubusercontent.com/4467963/222667432-5ca37875-cc3e-4df3-8ea7-2706e80967b9.png)

**Comment by Web-eWorks** [comment]
You most likely need to tell CMake where `git` is on Windows; our CI build passes this as `-DGIT_EXECUTABLE="c:/Program Files/Git/cmd/git.exe"`.

Generally speaking Git is supposed to be on your path if installed properly, but I'm unsure about your specific installation or what CMake does by default.

**Comment by craigo-** [comment]
Thanks, @Web-eWorks. Both CMake and Git are included in Visual Studio 2019, and there is also a git.exe in the GitHub Desktop installation folder. Neither location is included in the OS path however.

In the end, I modified my user profile path to include a reference to the location of git.exe included in Visual Studio. Recompiling resulted in the commit version being displayed 👍
