### ISSUE TITLE
Game crash in Sol

### ISSUE THREAD

**Issue by widowmaiker** [pioneerspacesim/pioneer#5571]
[11:41:13.815211] Fatal:    [T] libs/Economy.lua:403: Standard deviation should not be negative.
stack traceback:
	[C]: in function 'Normal'
	[T] libs/Economy.lua:403: in function 'UpdateStationMarket'
	[T] libs/SpaceStation.lua:947: in function <[T] libs/SpaceStation.lua:943>
[11:41:22.166714] Fatal:    Frame instance deletion outside 'DeleteFrame' [0]

### Steps to reproduce
Load save file, try to autopilot on any destination

__My pioneer version (and OS):__
 ver 20230203 (e77da96), win11 22h2

[Pioneer_save_output_log.zip](https://github.com/pioneerspacesim/pioneer/files/10979495/Pioneer_save_output_log.zip)

**Comment by impaktor** [comment]
I have not seen this bug before. 
I'll see if I can reproduce it. later tonight.

**Comment by impaktor** [comment]
Save doesn't load for me, tried re-compiling the release version, still doesn't load.

**Comment by Web-eWorks** [comment]
Closing as stale.
