### ISSUE TITLE
Unable to open save

### ISSUE THREAD

**Issue by fgfs-fmanu** [pioneerspacesim/pioneer#5573]
Hello. I would like to report a problem of saving on my side.

When i do update, my saved game is not readable by the new version. I tried to update the game from AUR or directly from github (with git clone, and makepkg -si). But everytime, the save file become unreadable.

I send the output file, the latest save file, and a screenshot:
[output.txt](https://github.com/pioneerspacesim/pioneer/files/11019802/output.txt)
[personal.txt](https://github.com/pioneerspacesim/pioneer/files/11019806/personal.txt)
I renamed my save file "personal" to "personal.txt" to pass it to the forum.

Here's the screenshot:
![Capture d’écran_2023-03-20_15-43-58](https://user-images.githubusercontent.com/64139564/226385251-a463a266-e774-424e-9021-d2189cd7641e.png)

I'm on Archlinux.

Thank you for reading my issue.

**Comment by Web-eWorks** [comment]
Closing this issue - the last few updates have included intentional savebumps which make old saves incompatible. I've amended the release notes to clarify that this update is not backwards-compatible.
