### ISSUE TITLE
Military drives are strictly worse than standard hyperdrives

### ISSUE THREAD

**Issue by yump** [pioneerspacesim/pioneer#5576]
When hyperdrive masses were re-balanced in 23447dd6d7305b384777a2cfb43eba2ab77dbe04, the military drives wound up heavier than their civilian equivalents.

### Observed behaviour

Hyperjump to Sol with military drive takes 1w3d and uses 6t of fuel

Same jump with standard drive takes... 1w3d and uses 6t of fuel.

In comparison to the military drive, the standard drive weighs less, costs less, shares fuel with the sublight engine, and benefits from  reverse tyranny of the rocket equation (the ship gets lighter and faster with each jump).

### Expected behaviour

There should be some benefit in exchange for the high prices and troublesome logistics of military drives.

### Steps to reproduce

1. Load attached save file.

2. Use sector map to plot hyperspace route to Sol. Note time and fuel consumption.

3. Go to equipment market and replace Class 3 military drive with Class 3 civilian drive.

4. Check time and fuel consumption again.

__My pioneer version (and OS):__ master @ a1e93056c999998b46e2176f71464117e7ffec09 on Fedora 37

Save file: [cheat.zip](https://github.com/pioneerspacesim/pioneer/files/11084664/cheat.zip)

**Comment by impaktor** [comment]
Military drives should definitely weigh less, but have the same performance (I think).
From the source, we see military drive is too heavy for class 1-5 (and probably 6 as well).
Question is: if class 1 should be just 1t, or remove class 1 military drive? ping @nozmajner 

| CLASS | REGULAR | MIL |
|-------|---------|-----|
|     1 |       2 |   3 |
|     2 |       6 |   7 |
|     3 |      11 |  12 |
|     4 |      25 |  28 |
|     5 |      60 |  63 |
|     6 |     130 | 128 |
|     7 |     245 | 196 |
|     8 |     360 | 285 |
|     9 |     540 | 400 |

**Comment by nozmajner** [comment]
I haven't yet thought much about the hyperdrive masses and stats. Them having similar capabilities is a problem though. The military drives supposed to have lower travel times than the regular ones, but I can't recall any changes to that.

How about these drives would give about the same travel time than a one class larger regular drive? So you could equip a lighter drive for the same capabilites, but with the downside of it being more expensive to buy and service, and the need for military fuel and waste product processing (or the risk of fines for littering). And you forfeit the ability to pump fuel down or up, since your engines can't use it as propellant . Maybe even a bit larger fuel consumption for the same distance.

**Comment by impaktor** [comment]
To remind us how it once was, in Frontier (Lighter (from which greater range follows) & faster)

| CLASS | REGULAR | MIL |
|-------|---------|-----|
|     1 |      10 | 6   |
|     2 |      25 | 12  |
|     3 |      45 | 24  |
|     4 |      80 | ?   |
|     5 |     150 | -   |
|     6 |     250 | -   |
|     7 |     400 | -   |
|     8 |     600 | -   |

_A military drive is faster (useful if you are involved in a lot of police chases and need fast acceleration), lighter and offers a greater jump range. The main advantage here is that a smaller ship can carry a Class 3 Military Drive which offers the same jump range as a Class 4 Standard, with it only taking up half the space. With regards to the Viper, a Class 4 Standard wouldn't even fit in the ship._
[frontierverse](https://www.sharoma.com/frontierverse/basics.htm)

**Comment by yump** [comment]
IMO, it should be possible to balance them with mass alone.  If you can mount a higher-class of military drive than the standard drive that fits in the ship, that gets you reduced travel time, and then you can trade for fuel consumption by taking direct jumps instead of splitting into multiple shorter jumps.
