### ISSUE TITLE
Commodity market in stock reset on save load

### ISSUE THREAD

**Issue by Max5377** [pioneerspacesim/pioneer#5582]
### Observed behaviour
Commodity market in stock resets on save load. In stock and demand for Hydrogen, Radioactive waste and Rubbish gets replaced by some constant value.

1. Cydonia initial market. Easy start

![Pioneer Bug1](https://github.com/pioneerspacesim/pioneer/assets/69468517/aecd9824-7de0-4b6e-9b2f-f69bcccd152e)

2. Bought one Air processor

![Pioneer Bug2](https://github.com/pioneerspacesim/pioneer/assets/69468517/282f7328-5c50-48bc-895b-e1cd3f88e78d)

3. Saved and loaded after purchase

![Pioneer Bug3](https://github.com/pioneerspacesim/pioneer/assets/69468517/1a508359-0a43-4c4f-ac46-2c3171f5ef47)

### Expected behaviour
Commodity market does not reset after loading a save.

### Steps to reproduce
1. Start new game or just load any save;
2. Buy any commodity from any station or city;
3. Save game;
4. Load this save and go to commodity market.

__My pioneer version (and OS):__
https://github.com/pioneerspacesim/pioneer/commit/e77da966923a4ad24c8863bcca7dec7933c33d43 (Windows 10 x64)

**Comment by impaktor** [comment]
Sounds familiar, but perhaps I'm thinking of #5534

**Comment by Web-eWorks** [comment]
This is intentional behavior. "Haulaway" commodities (rubbish, radioactives) and fuel are constantly produced by the station's inhabitants and natural processes and are not saved the same way other commodities are when leaving the system or reloading a save. Potentially in the future we may compute their stocks instead based on a series of rules for station commodity productions, but at this time they're arbitrary as they have little to no impact on commodity trading.

**Comment by Max5377** [comment]
@Web-eWorks What about other commodities that are reset, like Air processors in the example on save loading?

**Comment by Max5377** [comment]
`Economy.lua` was saving data correctly from `stationMarket` property, but `SpaceStation.lua` never restored that data. 
 Adding `createCommodityStock(station)` line to this loop `for station,list in pairs(loaded_data.shipsOnSale) do` in `Event.Register("onGameStart", function ()` in `SpaceStation.lua` apparently fixes this issue. Will do some additional testing and, if everything will be fine, will do PR.

**Comment by Max5377** [comment]
Here's what I gathered so far.
I saw that `transientMarket` in `SpaceStation.lua` is a `cache for commodity markets initialized in unvisited stations` except, it doesn't populate, neither on game start, nor when player ship is entering system.
The only time it gets populated is when calling `createCommodityStock` function and it's tied to `stationMarket` which is `a persistent table of stock information for every station the player has visited in their journey` in `Economy.lua`. This `createCommodityStock` function is called:
1. During event `onShipDocked`, when player has not visited the station before(even if they been at the station, when they leave system it gets reset);
2. In the function `ensureStationData `which is called from:
   2.1. `SpaceStation:AddEquipmentStock`;
   2.2. `SpaceStation:AddCommodityStock`;
   2.3. `SpaceStation:SetCommodityStock`.
This three functions are all called from station UI's.

And I have questions what to do about it:
1. Call `createCommodityStock` for every station in the system when player is entering that system and in the event `onGameStart`?
2. Just do, what I described there https://github.com/pioneerspacesim/pioneer/issues/5582#issuecomment-1721768482 , so `transientMarket` is linked to `stationMarket` only for stations that player visited in the system?
3. Some other solution that I don't know about.

**Comment by Web-eWorks** [comment]
> Call createCommodityStock for every station in the system when player is entering that system and in the event onGameStart

I'd prefer not to. We explicitly moved away from this model, as the created station markets (and the station BBS ads) were contributing heavily to savefile bloat.

> I saw that transientMarket in SpaceStation.lua is a cache for commodity markets initialized in unvisited stations except, it doesn't populate, neither on game start, nor when player ship is entering system.

This is correct. It is *only* populated when the player physically visits a station - or when a badly-behaving mission module tries to modify commodity information of a station that a player has never been to before. It functions as both a source of data for all transient/ephemeral commodities (e.g. Rubbish / Hydrogen) which do not contribute to the economic simulation, and a bug-trap to prevent legacy mission modules from causing game crashes.

Looking at your linked PR, it seems you've found a good solution - I appear to have overlooked the post-load recreation of the `transientMarket` data for the current system. Thanks for catching this bug!
