### ISSUE TITLE
Ship's rotation gets stuck

### ISSUE THREAD

**Issue by Max5377** [pioneerspacesim/pioneer#5583]
### Observed behaviour
I was flying from Daniel's Haven station to Oasis City on Titan on Lunar Shuttle. When I was on the Titan's orbit I started changing speeds between x1, x10 and x100, and correcting my movement. During this, something strange happened: my ship's rotation kinda stuck and I couldn't rotate it. Also, the sound of thrusthers started to repeat infinitely, which was very loud. I could still try to rotate the ship if I changed speed for the brief moment, and if I could land on the surface of the planet, the bug would correct itself. If saved during this bug, it will persist even after load.

!!! **VOLUME WARNING** !!!

https://github.com/pioneerspacesim/pioneer/assets/69468517/ebca7dce-3b5b-4671-9171-a4d2e5cf8045

### Expected behaviour
The ship rotation doesn't break like that.

### Steps to reproduce
Unknown, probably happens randomly. Will update if I can reproduce.

__My pioneer version (and OS):__
https://github.com/pioneerspacesim/pioneer/commit/e77da966923a4ad24c8863bcca7dec7933c33d43 (Windows 10 x64)

__Game Save__
I haven't saved the output.txt when this bug occured, sadly.
[Ship rotation bug.zip](https://github.com/pioneerspacesim/pioneer/files/11504958/Ship.rotation.bug.zip) (Bug already occured)

**Comment by Max5377** [comment]
@impaktor I compiled current master and loaded save which I uncluded. Couldn't still rotate ship but when I changed speed, I could control it again, thanks. This issue is no longer valid.

**Comment by impaktor** [comment]
Not sure I understood the bug, but also, I don't think we've fixed it, so might happen again.

**Comment by Max5377** [comment]
@impaktor I will reopen this issue if it happens again. As for the bug, I think it's with this zero length direction vector, but in action, that you prevented in the last commit.
