### ISSUE TITLE
Countermeasure (Feature Request)

### ISSUE THREAD

**Issue by ArcticGoldfish** [pioneerspacesim/pioneer#5587]
I was reading the heat dissipation feature request and how weapons generate heat, and something I thought would be cool is maybe a new type of defensive counter measure that can come in both civilian and military grade models. I just think it would be cool to hopefully evade the guided missiles. Where civilian can do the simpler ones, and the military grade can do the naval at most. It could also be a way to transfer heat out of a radiator, and forced out or expelled through some means to eject heat. And you could either do it that way if you build up a lot of heat, or perhaps you buy charges for countermeasures, either military or civilian, as well as a method of deploying the countermeasures

**Comment by Zireael07** [comment]
Why open an issue and then immediately close it?

**Comment by ArcticGoldfish** [comment]
Oh because I realize it was already a thing, my bad. I was reading over the equipment list and didn’t see countermeasures at first, then I opened issue, and just to double check I went back and then saw the ecm. I answered my own question pretty much

**Comment by ArcticGoldfish** [comment]
I am looking to get into programming but not sure where to start, and I like pioneer. I think it would be cool to maybe integrate some form news digest for the galaxy, but it’d be cool if chat gpt was able to make stories or some form

**Comment by Web-eWorks** [comment]
For future reference, feature requests like these are best created on [our forum](https://forum.pioneerspacesim.net/) in the dedicated Feature Request category, rather than on the issue tracker. We definitely have some plans to expand signals/missile gameplay over time, but we prefer to keep this issue tracker limited to only current game bugs and actively-developed features.

**Comment by ArcticGoldfish** [comment]
My apologies, I realized that after which is also why I closed it. I was trying to see where to add features, but now I know. Thanks!
