### ISSUE TITLE
Police Issues

### ISSUE THREAD

**Issue by VorTechnix** [pioneerspacesim/pioneer#5603]
### Observed behaviour
- Firing a weapon or torpedo at pirate or into empty space when a police ship is in your vicinity (not sure what the exact range is) makes you get the piracy charge.
- Police almost never come to your aid when you are attacked by pirates
- When police do come to your aid they don't shoot pirates (at least that I saw)

### Expected behaviour
- Hitting a police or civilian ship with a weapon or torpedo while police are in the vicinity should be the only way to trigger a piracy charge. 
- Police should fire on pirates in their vicinity

You should probably be able to appeal a piracy charge if there was a pirate in range when you received the charge.

### Steps to reproduce
Enter a system that has police at the hyperspace arrival area. Fire main weapons or torpedoes at pirate (or even into empty space).

**Comment by VorTechnix** [comment]
Updated post to better reflect the scope of the problems.

**Comment by VorTechnix** [comment]
Ref #5202 also deals with the "Police apathy" problem.

**Comment by Miner34dev** [comment]
> Hitting a police or civilian ship with a weapon or torpedo while police are in the vicinity should be the only way to trigger a piracy charge

I don't think this is the best solution, as it would remove the "unlawful weapon discharge" crime charge, which should still be there, especially near cities/spacestations. Instead it can be removed when there is a pirate nearby.

**Comment by VorTechnix** [comment]
> I don't think this is the best solution, as it would remove the "unlawful weapon discharge" crime charge, which should still be there, especially near cities/spacestations. Instead it can be removed when there is a pirate nearby.

I agree that near cities and space stations "unlawful weapon discharge" should still be a thing but you should be able to do whatever you want in interplanetary space as long as you don't hit the wrong thing while the police are in range.

**Comment by Miner34dev** [comment]
> I agree that near cities and space stations "unlawful weapon discharge" should still be a thing but you should be able to do whatever you want in interplanetary space as long as you don't hit the wrong thing while the police are in range.

Of course.
But what if the pirate is near a city/space station? I think in that case if you're shooting in the direction of the pirate you shouldn't get the piracy charge.

**Comment by VorTechnix** [comment]
> Of course.
> But what if the pirate is near a city/space station? I think in that case if you're shooting in the direction of the pirate you shouldn't get the piracy charge.

I'm not saying it should be either or. All I'm saying is this:
- It's unrealistic to get a piracy charge when the police aren't in range
- It's annoying to get a piracy charge when pirates are around
  - The problem here is that a pirate in range of you might not be in range of a police that's in range of you so to them it would look like you are shooting with no pirate in the area.

Solution: make police more lazy. Basically the only way to get a piracy charge should be to actually destroy a civilian or police vessel while there are no pirates within several megameters of you. Just hitting a police or civilian ship with a stray shot shouldn't count.
