### ISSUE TITLE
Cannot jump to another system

### ISSUE THREAD

**Issue by robothauler** [pioneerspacesim/pioneer#5618]
### Observed behaviour
Pioneer crashes when jumping to another system

Last lines from gdb
...
Info: Started hyperspacing...

Thread 1 "pioneer" received signal SIGSEGV, Segmentation fault.
Camera::CalcLighting (this=this@entry=0x555559b92f80, b=0x55555bcef090, ambient=@0x7fffffffe100: 0.050000000000000003, direct=@0x7fffffffe108: 1) at /home/user/src/pioneer/src/Camera.cpp:366
366             FrameId rotFrame = planet->GetFrame();

### Steps to reproduce
Start at Mars
Jump to Sirius

__My pioneer version (and OS):__
Current master
(Arch Linux)

__My output.txt (required) and game save (optional, but recommended)__

[output.txt](https://github.com/pioneerspacesim/pioneer/files/12504430/output.txt)
[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/12504431/opengl.txt)

**Comment by impaktor** [comment]
I assume "Current master" is: 87a0581

**Comment by WKFO** [comment]
I haven't traced the error to its source or anything but it may be worth noting as with all problems involving the Sirius system: when you jump into Sirius, the player initially has no frame "body". The Sirius system uses the system barycenter as the frame of reference.

**Comment by impaktor** [comment]
ha, true, we've had many bugs triggered by that system.

**Comment by WKFO** [comment]
Hmm... This particular problem appears to be independent from what system you jump to. I playtested the game and whatever system you jump to crashes the game.

**Comment by MirceaKitsune** [comment]
Was resolved in latest Git master for me: Just tested and I can now warp to any system without getting this crash. Thanks for the help!

**Comment by impaktor** [comment]
Yes, looks like @Web-eWorks pushed bugfixes, like d14df431edf5afbb242845fd54dd90accf4ca2ef, 2176631b6b29518f3eb10d95c0dce46058c27b32, 38803763496763474adf3e1107a550104e0d9aaa

**Comment by Web-eWorks** [comment]
I've been so deep in system editor land I didn't realize we had an open issue to close with a PR :smile:

The "bugs" had very simple fixes and were things I probably should have tested and caught when opening the PR they were introduced in, so I just pushed the "fix" commits to master.
