### ISSUE TITLE
Crash Trader.lua

### ISSUE THREAD

**Issue by TheFelin** [pioneerspacesim/pioneer#5653]
### Observed behaviour
sometimes on mission

### Steps to reproduce

__My pioneer version (and OS):__
Linux Kubuntu last Kernel
and last Git Pioneer
![pioneerbug1](https://github.com/pioneerspacesim/pioneer/assets/51317099/8c85fb4d-4316-4363-bc4c-f44493b95cfb)
![pioneerbug2](https://github.com/pioneerspacesim/pioneer/assets/51317099/f1bcc2b4-6697-451f-b901-b411a4474f5d)

__My output.txt (required) and game save (optional, but recommended)__
I can't find output.txt but I have a backup just before the bug

**Comment by Web-eWorks** [comment]
@Max5377 I believe you have or are addressing this issue as part of your bugfix PRs?

**Comment by Max5377** [comment]
@Web-eWorks Yes, but I haven't done PR to fix this yet. I mentioned this issue first [here](https://github.com/pioneerspacesim/pioneer/pull/5647#issuecomment-1763326176) and the cause and possible solution for this [here](https://github.com/pioneerspacesim/pioneer/pull/5643#issuecomment-1772934271).

**Comment by cwyss** [comment]
I also experienced the issue, did some testing, and came up with a route through Barnard's system that will consistently reproduce the issue -- see below for details and game saves.

I then tried the same test route with the suggested PR #5657. Unfortunately, this **PR does not seem to fix the problem**: the crash still happens, although it takes a little longer to appear.

### The test route

I used the following tour through Barnard's star system. **Important** (probably, as this is supposed to be connected to saving): After completing each stage, 
- save game,
- end game, then 
- load the saved game again.

The stages were
1. start new game at Barnard's star; sell radar and atm. shielding
2. autopilot fly&dock OPLI Contemplation
3. autopilot fly&dock High Sec. Prison Tranquility; sell cargo H<sub>2</sub>, refuel full
4. autopilot fly&dock OPLI Pax, refuel
5. autopilot fly&dock System Administration Resting, refuel
6. autopilot fly&dock High Sec. Prison Serenity

#### Results

- for upstream master (at 221548ab4): crash occurs during stage 4, when accelerating to OPLI Pax; savegame after stage 3
[master-stg3.gz](https://github.com/pioneerspacesim/pioneer/files/13326606/master-stg3.gz)

- for PR #5657: crash during stage 6, accelerating to Serenity; savegame after stage 5
[pr5657-stg5.gz](https://github.com/pioneerspacesim/pioneer/files/13326610/pr5657-stg5.gz)


I also checked that this is reproducible, by rerunning the whole test route from stage 1. Interestingly, one such rerun for PR #5657 yielded the crash already at stage 4, just as in master. Another rerun then made it again into stage 6.

**Comment by Max5377** [comment]
@cwyss If you loaded old save with (#5657) then it will not work, because this uses different array to get objects when saving and loading the game. 
And to get this crash you don't even have to do this steps. Just load any save, save the game, load, set max speed and wait for some time.

**Comment by cwyss** [comment]
> @cwyss If you loaded old save with (#5657) then it will not work, because this uses different array to get objects when saving and loading the game. 

When doing the test with #5657, I did not use an old save, but started again from scratch with "New Game" from the main menu. That is, I did the whole test route in #5657, as described.

> And to get this crash you don't even have to do this steps. Just load any save, save the game, load, set max speed and wait for some time.

That's of course much easier :-)

**Comment by Max5377** [comment]
@cwyss Yeah, looks like something happens when the game gets saved second time and more in the same system. Sometimes save gets corrupted so bad that it can't even find json key when loading it for objects (for now, it's mainly `Sfx` and `pos` key, can occur even without PR).
Thanks, for spotting this.
