### ISSUE TITLE
Pioneer does not create fresh local config files?

### ISSUE THREAD

**Issue by Bodasey** [pioneerspacesim/pioneer#5656]
### Observed behaviour
just after compiling on a new computer, means it's the first run of any pioneer on this machine.

romaschw@localhost:pioneer-master> ./pioneer
[  1%] Built target profiler
[  2%] Built target lz4
[  3%] Built target fmt
[  4%] Built target nanosockets
[  7%] Built target pioneer-core
[  9%] Built target savegamedump
[ 69%] Built target pioneer-lib
[ 78%] Built target lua
[ 91%] Built target pioneer-lua
[ 91%] Built target glew
[ 93%] Built target imgui
[ 94%] Built target jenkins
[ 94%] Built target picodds
[ 94%] Built target modelcompiler
[ 96%] Built target unittest
[ 97%] Built target pioneer
[100%] Built target pioneer-editor
[100%] Built target editor
Info: ver 20231031 on: Linux
Info: System Name: Linux
Host Name: localhost.localdomain
Release(Kernel) Version: 5.14.21-150500.55.31-default
Kernel Build Timestamp: #1 SMP PREEMPT_DYNAMIC Wed Oct 4 16:52:05 UTC 2023 (5dc23e0)
Machine Arch: x86_64
Domain Name:
Info: Loaded mods:
Info: --------------------
Info: SDL Version (build) 2.0.8
Info: SDL Version (dynamic) 2.0.8
Info: SDL Versions match
Info: SDL_image Version (build): 2.0.5
Info: SDL_image Version (dynamic): 2.0.5
Info: SDL_image Versions match
Info: Assimp Version: 5.3.0
Info: FreeType Version: 2.10.4
Info: GLEW dynamic version: 2.0.0
Info: --------------------
Info: 
Fatal: Failed to set video mode: Could not create GL context: GLXBadFBConfig
romaschw@localhost:~/pioneer-master>

~/.pioneer is not created by the program, but ~/.local/share/pioneer
~/.pioneer can be created manually, but on both places, only the directory "mods" and the file output.txt are created.

### Expected behaviour

Creation of four files in this directory (as I remember)

__My pioneer version (and OS):__
actual and previous master branch
on openSuSE 15.5 (Linux)

__My output.txt (required) and game save (optional, but recommended)__
see above

**Comment by Web-eWorks** [comment]
Not a bug. Pioneer now prefers storing its user data in `$XDG_DATA_HOME/pioneer`, falling back to `~/.local/share/pioneer` if that variable is not set. `~/.pioneer` is used only for backwards-compatibility reasons.

**Comment by Bodasey** [comment]
It's a bug as long as the program does not start, maybe for another reason, but this is the visible result.

**Comment by nozmajner** [comment]
I've noticed that on windows the installer creates a different directory structure than before, and the game does not run until you rearrange it to the original directory layout.
It now looks like this: 
- Pioneer/ - it puts all the dlls here
    - bin/ - it puts all executables here
    - share/
       - Pioneer/
          - data/
          - licences/
          - authors.txt and such

It happened with the #5617 PR's automatic build

**Comment by Web-eWorks** [comment]
Pioneer fail to start because it cannot initialize a GLX context. That's a completely different issue and unrelated to the lack of config file. Unless you're able to solve the problem and get Pioneer running *only* by creating the `~/.pioneer` directory (e.g. `mkdir ~/.pioneer`) then it's a different issue and should be tracked in a separate issue report.

**Comment by Bodasey** [comment]
Info: ver 20231115 on: Linux
Info: System Name: Linux
Host Name: localhost.localdomain
Release(Kernel) Version: 5.14.21-150500.55.36-default
Kernel Build Timestamp: #1 SMP PREEMPT_DYNAMIC Tue Oct 31 08:37:43 UTC 2023 (e7a2e23)
Machine Arch: x86_64
Domain Name:
Info: Loaded mods:
Info: --------------------
Info: SDL Version (build) 2.0.8
Info: SDL Version (dynamic) 2.0.8
Info: SDL Versions match
Info: SDL_image Version (build): 2.0.5
Info: SDL_image Version (dynamic): 2.0.5
Info: SDL_image Versions match
Info: Assimp Version: 5.3.0
Info: FreeType Version: 2.10.4
Info: GLEW dynamic version: 2.0.0
Info: --------------------
Info: 
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 241 requests (239 known processed) with 8 events remaining.


Seems to be a problem on my machine ... even 2023 February stable who comes with the distribution fails, I know it has run on my old computer. Let's hope for OpenSuSE 15.6.
