### ISSUE TITLE
Ship spinner always starts on same ship

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#5659]
On current master 579d5c6 every time you start the game it's the xylophis that is the first ship in the ship spinner in Main Menu. It used to be random, I believe, and which is what I expected.

**Comment by Max5377** [comment]
Ship is random everytime when starting the game on current master a2170e982f1b830c6dbb57c43a8f483c8839183b

**Comment by impaktor** [comment]
I just compiled a2170e982f1b830c6dbb57c43a8f483c8839183b and I'm still getting Xylophis 5 times out of 5. 

Must be something with my setup then? Mods? (I have bulkship-models (Vgr-battlecruiser & longnose) in my mod folder, together with Evarchart's facegen assets).

**Comment by Max5377** [comment]
Can you give me a link to these? I can't seem to find them anywhere.
**Fun fact**: Pioneer has `moddb` page which has a very old [alpha 7](https://www.moddb.com/games/pioneer/downloads/pioneer-alpha-7) version.

**Comment by impaktor** [comment]
> Fun fact: Pioneer has moddb page 

Yes, Geraldine used to upload every new release to there, but that died off, about the same time that SSC went dormant.

I'm attaching the mods to this post. Background on the mods:

- [Longnose](https://forum.pioneerspacesim.net/viewtopic.php?f=6&t=340) is lacking textures, 
- Vgr-battlecruiser has wrong scale, so I think it's 1 cm big or something (anyone feeling up to play with it in Blender?), thus often there's no bulkship outside the station, because it's too tiny. (Bulkship.lua has some probability for spawning bulkships)
- [Evarchart](https://forum.pioneerspacesim.net/viewtopic.php?f=8&t=382) (aka CaptainNow on [EAB](https://eab.abime.net/)) did the Facegen, but he's been [through a bit](https://eab.abime.net/showpost.php?p=1662161&postcount=801), and now the Amiga game he's done all art & assets for is nearing a physical release.

[facegen.zip](https://github.com/pioneerspacesim/pioneer/files/13987650/facegen.zip)
[longnose0.4.zip](https://github.com/pioneerspacesim/pioneer/files/13987651/longnose0.4.zip)
[Vgr_battlecruiser.zip](https://github.com/pioneerspacesim/pioneer/files/13987653/Vgr_battlecruiser.zip)

**Comment by Max5377** [comment]
Good luck to Evarchart with the launch of his game.
Even with this mods installed, ships are random. Still have to see if moded ships are showing up there.
Also, I can't choose moded ships in the start menu with `Custom Start` option.

**Battlecruiser** in my game is **GIGANTIC**, but it appears to be that it's model is facing backwards:
![Front](https://github.com/pioneerspacesim/pioneer/assets/69468517/fa82f912-363c-4b1f-8c17-c1eb637de489)
![Back](https://github.com/pioneerspacesim/pioneer/assets/69468517/0bd62d43-672a-4141-a95f-a13a0faf826b)

Can confirm with **Longnose** ship:
![No textures](https://github.com/pioneerspacesim/pioneer/assets/69468517/1f08f9e0-7f6d-43e2-ba5f-65d28f4c3585)

**Comment by nozmajner** [comment]
Those two aren't supposed to be choosable, they are only for showing up next to orbitals here and there. By default at least.

**Comment by Max5377** [comment]
Ah, makes sense. Then, it's only the model(Battlecruiser) and textures(Longnose) that are problem here.

**Comment by Max5377** [comment]
@impaktor Just to clarify, it's only the first ship that is not random or other ships are also not random?
If others are also not then might be a problem with `time` function which is used to seed random number generator [here](https://github.com/pioneerspacesim/pioneer/blob/master/src/Pi.cpp#L356).
Randomization of the models in main menu happenes [here](https://github.com/pioneerspacesim/pioneer/blob/master/src/Intro.cpp#L73).
If it's only the first, then I haven't really got a clue what might be causing it. 
Also, found out that spinner is showing second ship on the first iteration, going to do PR later to fix that.

**Comment by impaktor** [comment]
I've run twice now, both times it's looks very alphabetical, starting on the last ship, and wrapping round. Order was (both times):

1. xylophis
2. ac-33
3. bluenose
4. bowfin

**Comment by zonkmachine** [comment]
> I've run twice now, both times it's looks very alphabetical, starting on the last ship, and wrapping round. Order was (both times):
> 
>     1. xylophis
> 
>     2. ac-33
> 
>     3. bluenose
> 
>     4. bowfin

This is what I see too. I think, since shuffle provides a range already and seem to expect an object with a raw random output. If you remove `maxVal` from this line in `PiRngWrapper` the issue is fixed for me.

https://github.com/pioneerspacesim/pioneer/blob/29af573e617275344bac9035c457c0e6ff1ce5fc/src/Intro.cpp#L26

```cpp
 return Pi::rng.Int32(); 
```

If I substitute `return Pi::rng.Int32();` with `return rand()` the issue is also fixed but `return rand() % maxVal` gives the same error. I think the behavior may be not *randomy' enough with the way we do it here. I don't know what's the best way to solve this. I had a go with a PR that goes brute force and removes PiRngWrapper and the shuffle altogether and lets the ship model be just random which means it will show the same model twice in a row on average about once every 23 presentations. I think this is fine as many of them has decoration and color differences so there still will be variation. Just doing the one line fix  (`Pi::rng.Int32()`) looks a bit off as it leaves `PiRngWrapper` with stuff that could/should be cleaned up/removed. I'm curious as to why the issue is only seen by some of us. Maybe it's platform dependent?

Fix? https://github.com/pioneerspacesim/pioneer/compare/master...zonkmachine:pioneer:randship

**Comment by zonkmachine** [comment]
I looked further into this. It looks like gcc std::shuffle has two paths. It tests the random object for it's max()/min() values to decide if the random sequence is good enough to send it to the more fine grained algorithm that uses `__gen_two_uniform_ints(` which [requires the random sequence to be larger than the multiple of it's argument](https://github.com/gcc-mirror/gcc/blob/964c9c247ca691e92f046070dd487f0e0e56958e/libstdc%2B%2B-v3/include/bits/stl_algo.h#L3718). Which is not the case for Pioneer.
Test here: https://github.com/gcc-mirror/gcc/blob/964c9c247ca691e92f046070dd487f0e0e56958e/libstdc%2B%2B-v3/include/bits/stl_algo.h#L3718-L3721

You can poke this by setting the return value for max() in PiRngWrapper to something low enough, like 20. Now, the ship display once more is random on startup. I'm modifying PiRngWrapper to use the full random range of the random object.
