### ISSUE TITLE
Crash on startup, cannot find several data files (probably wrong access path).

### ISSUE THREAD

**Issue by pirogronian** [pioneerspacesim/pioneer#5667]
### Observed behaviour
Crash on startup, with error messagebox about missing shader.

__My pioneer version (and OS):__
Pioneer v. 20230203.r368.g9ee3f29e8-1
OS: ArchLinux up-to-date
Package: [https://aur.archlinux.org/packages/pioneer-git](url)

__My output.txt (required) and game save (optional, but recommended)__
[pioneer-output.txt](https://github.com/pioneerspacesim/pioneer/files/13404484/pioneer-output.txt)
[pioneer-strace.log](https://github.com/pioneerspacesim/pioneer/files/13404486/pioneer-strace.log)

I've investigated it a bit. The game seems to look for its files with wrong path:
`/usr/share/pioneer/<path suffix>`
instead of
`/usr/share/pioneer/data/<path suffix>`

My last working version is from around 15-th September.

**Comment by msuffidy** [comment]
I had this problem, and my theory was the items in the data folder from the compilation folder were somehow not being verbosely copied or moved. So I blew away /usr/local/share/pioneer/data and extracted the original src and just moved the data dir to that location. So like mv data /usr/local/share/pioneer from a new scratch compilation folder after installing. I just happened to be upgrading my Fedora Core the last few days and I guess I hit a bug. I would have liked to go FC39, but it seems to have problems with the nvidia driver and tablets crashing it constantly.

**Comment by impaktor** [comment]
@msuffidy so moving the files manually fixed the shader issue? (and instead you have driver issues?)

**Comment by msuffidy** [comment]
Oh what happened to me was it said it was missing the place holder model dome1 I think. Not about shaders. I have not played the game extensively but it seems to be working at a glance.

**Comment by Web-eWorks** [comment]
This is a problem with the Arch Linux PKGBUILD file, which we do not maintain - it's passing `-DPIONEER_DATA_DIR=/usr/share/pioneer` and not respecting the installation conventions as set in cad5570cca7a7fb893b8b6fab5da0b624fb0c03e. We now generate an install tree that looks like this:

```
/usr/share/pioneer
 | licenses/
 | data/
 | <loose files>
```

The PKGBUILD script should be updated to either pass `-DPIONEER_DATA_DIR:PATH=/usr/share/pioneer/data` or omit the `PIONEER_DATA_DIR` argument entirely (it will be set from the CMake installation prefix anyways).

Please raise this as an issue with the AUR maintainer for the `pioneer-git` package instead.

Copying the `data/` dir from a fresh checkout of Pioneer is technically acceptable as a workaround, but you will have significantly slower startup times as you're not using compiled models.
