### ISSUE TITLE
Loss of cargo free space and content after reloading the game in an uninhabited system when in flight

### ISSUE THREAD

**Issue by CodexMavie** [pioneerspacesim/pioneer#5680]
![Immagine 2023-12-15 072030](https://github.com/pioneerspacesim/pioneer/assets/153892218/1ce41900-7a8e-441f-a08d-71f43ed2bd95)
![Screenshot (1)](https://github.com/pioneerspacesim/pioneer/assets/153892218/f14065b2-9ba5-4523-982d-592af654669e)
![Screenshot (5)](https://github.com/pioneerspacesim/pioneer/assets/153892218/e080e35f-0dad-43cd-934c-086798155309)

After reloading the game

![Screenshot (7)](https://github.com/pioneerspacesim/pioneer/assets/153892218/c2680db9-e00e-4c16-bba3-eda339908221)

Windows 10 operating system
Pioneer version pioneer-20230203

[output.txt](https://github.com/pioneerspacesim/pioneer/files/13681986/output.txt)

Save files:

Before the bug:

[Mavie2.zip](https://github.com/pioneerspacesim/pioneer/files/13682026/Mavie2.zip)

After the bug:

[Mavie.zip](https://github.com/pioneerspacesim/pioneer/files/13682028/Mavie.zip)

**Comment by Web-eWorks** [comment]
This was most likely fixed by #5635. If you're able to download a recent `master` build of Pioneer (e.g. from [this run](https://github.com/pioneerspacesim/pioneer/actions/runs/7305548610)) and test, I'd appreciate it.

**Comment by Web-eWorks** [comment]
Closing as fixed.
