### ISSUE TITLE
Can't do any mission

### ISSUE THREAD

**Issue by Miner34dev** [pioneerspacesim/pioneer#5684]
### Observed behaviour
All missions (but also other thing like the donation for veterans) are grey (like if i couldn't do them), and clicking on them does absolutely nothing.

### Expected behaviour
Allow me to see details of a mission.

### Steps to reproduce
I don't know exactly, but what i did is:

- Start a new game on Mars
- Go to phobos base
- Return to Mars (bradbury landing)
- Return to Cydonia
- Go to Mars high
I think it glitched after loading the mars high save...

__My pioneer version (and OS):__ Latest release, Garuda linux (Arch derivate)

__My game save:__ [save.zip](https://github.com/pioneerspacesim/pioneer/files/13719709/save.zip)

**Comment by nozmajner** [comment]
Make sure the game is not paused. All BBS functionality is disabled on pause, and the game is paused when you load a save.
