### ISSUE TITLE
Should we update fmt?

### ISSUE THREAD

**Issue by hexagonrecursion** [pioneerspacesim/pioneer#5693]
### Observed behaviour

When I compile pioneer, stderr is flooded with warnings like below. This makes it likely that other warnings may be missed.

```
In file included from /home/cdda/git/pioneer/contrib/fmt/include/fmt/format.h:44,
                 from /home/cdda/git/pioneer/src/core/Log.h:7,
                 from /home/cdda/git/pioneer/src/utils.h:7,
                 from /home/cdda/git/pioneer/src/ship/ShipViewController.h:10,
                 from /home/cdda/git/pioneer/src/WorldView.h:10,
                 from /home/cdda/git/pioneer/src/Player.cpp:19:
/home/cdda/git/pioneer/contrib/fmt/include/fmt/core.h:443:7: warning: identifier ‘c
har8_t’ is a keyword in C++20 [-Wc++20-compat]
  443 | using char8_t FMT_DEPRECATED_ALIAS = internal::char8_type;
      |       ^~~~~~~
```

### Expected behaviour

No warnings

### Steps to reproduce

`cmake -S . -B build/ && make -j2 -C build/ `

__My pioneer version (and OS):__ 97d7be673f2124f1b42aee956c4b3a6fc2129558 (and fedora 29)

g++ (GCC) 13.2.1 20231205 (Red Hat 13.2.1-6)

cmake version 3.27.7

GNU Make 4.4.1

### Notes

It appears that fmt>=7.0.0  removed the code that was causing the warning https://github.com/fmtlib/fmt/commit/d6cea50d01d7779ecb5ae4da0d785d9bba47a2f7 (if I am looking at the right git repo)

**Comment by etam** [comment]
Yes, please.

I maintain a patch for openSUSE to build pioneer with latest fmt: https://build.opensuse.org/package/view_file/home:etamPL:branches:games/pioneer/use_system_fmt.patch?expand=1
