### ISSUE TITLE
Ship staus is FLYING even though stopped and landed, cannot complete search and rescue mission

### ISSUE THREAD

**Issue by jonnyleigh** [pioneerspacesim/pioneer#5699]
### Observed behaviour
Ship is stopped on the surface of the planet next to target ship. However ship's status if FLYING and as such cannot finish the search and rescue mission.

![screenshot-20231229-141933](https://github.com/pioneerspacesim/pioneer/assets/29525176/b49afe56-acd1-4b1e-9e51-a9ba3ca8134e)

### Expected behaviour
Ship's status is LANDED

### Steps to reproduce
Land on a planet, probably on a slope.

__My pioneer version (and OS):__
ver 20230203 (e77da96) on: Windows

__My output.txt (required) and game save (optional, but recommended)__

[save.zip](https://github.com/pioneerspacesim/pioneer/files/13794246/save.zip)
[output.txt](https://github.com/pioneerspacesim/pioneer/files/13794248/output.txt)

**Comment by nozmajner** [comment]
You need to rotate a bit, so you are close to horizontal when you touch the ground.
![screenshot-20231229-154258](https://github.com/pioneerspacesim/pioneer/assets/4182678/76d1d494-c96f-41f4-9c61-f2a2daebe4cb)
