### ISSUE TITLE
Passing through landing pad during landing

### ISSUE THREAD

**Issue by claudiusmueller** [pioneerspacesim/pioneer#5705]
### Observed behaviour
Trying to land on Colheita Station on Abundancia (system: 61 Virginis) but the ship keeps sinking through the landing pad as if it wasn't there. I can park on the ground beneath the landing pad, but it (correctly) doesn't count as having landed at the station. The terrain seems flat, no obvious interference from the planet surface.

### Expected behaviour
I should be able to land on the assigned landing pad.

### Steps to reproduce
In the attached savegame the ship is hovering directly above the assigned landing pad. Just descend and you will pass through the pad all the way down to the ground beneath the station.

__My pioneer version (and OS):__
pioneer version: 20231229 (97d7be673)
OS: openSUSE Leap 15.5

__My output.txt (required) and game save (optional, but recommended)__
[output.txt](https://github.com/pioneerspacesim/pioneer/files/13832448/output.txt)
[pioneer_debug_02.zip](https://github.com/pioneerspacesim/pioneer/files/13832449/pioneer_debug_02.zip)

**Comment by claudiusmueller** [comment]
Another example - different system (Hotar, Port Gutierrez), and importantly, different ground station model. This one was annoying because it took me five tries of manual flying and one hour of time to get there. But maybe it will help provide another clue as to what is causing this.

Savegame and output.txt are attached. Ship is hovering above the station, ready to land. Same OS and pioneer version as stated in the first post.

[output.txt](https://github.com/pioneerspacesim/pioneer/files/13851425/output.txt)
[pioneer_debug_03.zip](https://github.com/pioneerspacesim/pioneer/files/13851427/pioneer_debug_03.zip)

**Comment by ARGHouse** [comment]
It happened to me too, but I managed to find a workaround (not a fix) by
running the pioneer.exe in the VSC2022 Profiler. How it did it... I don't
know, but somehow afterwards I was no longer clipping through ground
station landing pads. Now if I start another game, clipping will probs
start bugging out again until I do the same magic trick.
