### ISSUE TITLE
Can't type a name for a save game on a Steam Deck (though quicksave works)

### ISSUE THREAD

**Issue by mikehgentry** [pioneerspacesim/pioneer#5710]
### Observed behaviour

The game actually works reasonably well with a bit of tinkering on a Steam Deck. The major sticking point is that it seems to be impossible to save (possibly you could do it with an external keyboard?).

I can click the 'Save' button in the menu, which opens the save dialogue. I can click into the box for the name, and it'll give me a flashing cursor. I open the onscreen keyboard with Steam key + X. But typing doesn't appear to do anything - the box is obscured by the keyboard *, but once the keyboard is closed it's empty and seems to have lost focus (there's no cursor any more), making it impossible to actually save.

### Expected behaviour

Can type a name for a saved game, or failing that be given an autofilled name.

### Steps to reproduce

Hit a button bound to 'Esc', hit 'Save', hit the bar to type the name in, open the onscreen keyboard, try typing.

__My pioneer version (and OS):__

20231206 (from flatpak), SteamOS 3.5.7

Unfortunately I can't find any logs **, but I'm guessing they wouldn't say anything useful anyway. Let me know if there's anything useful I can tell you - it actually works surprisingly well on the platform, so would be amazing if you can figure out a way to fix it!

Cheers

\* I've just discovered you can hit the menu key to move the keyboard. Neat!

\** For the record, they're in /home/deck/.var/app/net.pioneerspacesim.Pioneer/.pioneer

**Comment by impaktor** [comment]
Technically, we only support Windows & GNU/Linux computers, so this issue could be closed, unless someone wants to spend time tinkering on this. 

Either way, thanks for letting us know. Never heard of pioneer + steam deck before.

**Comment by mikehgentry** [comment]
SteamOS is a custom immutable Arch installation with a wayland compositor called Gamescope (which runs like a console), but with a few button pushes it'll load KDE instead.

So it's got its quirks, but it's probably closer to a normal Linux box than you'd expect.

**Comment by Web-eWorks** [comment]
So - this is a bug that unfortunately is hardware/platform specific with no way to reproduce or dig into without having the hardware in question. As a result, it's going to be *very* low priority unless I or someone else who does engine-level work happens to buy a Steam Deck or other SteamOS-based (e.g. ChimeraOS) handheld in the future.

While we've definitely been inching towards unofficial compatibility with controller-based navigation and handheld game consoles over the past years, Pioneer is still officially targeted only at desktop/laptop Windows and Linux machines with physical keyboard+mouse input devices. It's unlikely this will be fixed in the short term unless someone who has a Deck and knows enough C++ to dig around in the engine guts is willing to learn the codebase.

**Comment by impaktor** [comment]
> would be for the game to automatically propose a name for a saved game based on the date / time

Yeah, I like that idea. It has not been proposed before.

**Comment by Zireael07** [comment]
Thirding automatically proposing a date-time name for savegame

**Comment by mikehgentry** [comment]
You could even put it on a button in the saved game menu if you didn't want it to do it by default.

[my obvious bias is obvious :) but anyway, I've verified that copying the save to different names through the file manager works, and you can load them and overwrite them in game, so that's an acceptable workaround for me whatever the outcome!]

**Comment by mikehgentry** [comment]
I just found this. Looks like the original complaint is probably a SteamOS issue, not a Pioneer issue after all.

https://github.com/ValveSoftware/SteamOS/issues/1053

**Comment by Web-eWorks** [comment]
That certainly matches my expectations - we don't do anything strange when it comes to handling SDL events and as long as keydown/keyup inputs are being sent properly then Pioneer should "just work". I'll keep an eye on that issue.

**Comment by mikehgentry** [comment]
From @Bertogg in the above linked SteamOS thread. I can confirm this works!

> Hi, if it's a Flatpak app, can you try setting the environment variable `SteamDeck=0` ?
> 
> In Steam go to the game -> settings button -> Properties and in LAUNCH OPTIONS there should be something like:
> 
> `"run" "--branch=stable" "--arch=x86_64" ...`
> 
> Add the variable after `"run"` so it looks like this:
> 
> `"run" "--env=SteamDeck=0" "--branch=stable" "--arch=x86_64" ...`
> 
> It works around the problem with GZDoom for me, but if you can verify this with other games I would also appreciate it.
> 
> Thanks!

**Comment by Web-eWorks** [comment]
Excellent! I've done some digging into the transitively-linked issues and while there's technically a workaround from the application side to both have text input and also onscreen keyboard input, there's a possibility this issue will be addressed in SDL 2.30+ so I'd recommend to keep using the environment variable override for now.

**Comment by Web-eWorks** [comment]
Fix appears to be merged in SDL 2.30+, closing as solved by upstream (will be dynamically linked from device runtime libraries).
