### ISSUE TITLE
Mission data persists between games

### ISSUE THREAD

**Issue by mikehgentry** [pioneerspacesim/pioneer#5714]
### Observed behaviour

You can start a game and immediately fail missions from the previous game, losing reputation / money. I believe this only happens if you were carrying something that was supposed to be taken to the starport that the new game starts in.

### Expected behaviour

All mission data is erased upon restart

### Steps to reproduce

From a cold start of the game, load the provided save. Immediately choose 'End game' from the menu. Start a new game, starting in Mars.

You will immediately be chastised by Beyza Baker for discarding his cargo (which was in the hold and destined for Cydonia). I'm not sure it's 100% reproducible yet, but it works reliably with this save on my system.

__My pioneer version (and OS):__

20230203 (labelled 20231206, from flatpak), SteamOS 3.5.7

__My output.txt (required) and game save (optional, but recommended)__

[output.txt](https://github.com/pioneerspacesim/pioneer/files/13929854/output.txt)
[_quicksave.txt](https://github.com/pioneerspacesim/pioneer/files/13929855/_quicksave.txt)

**Comment by impaktor** [comment]
Ah, another bug from Lua state surviving between reloads (those are classic).

Even if the pioneer version is 1 year old, I believe it should still be in current master.

@robothauler Are you interested in looking into this?

**Comment by robothauler** [comment]
> @robothauler Are you interested in looking into this?
> 
> EDIT: I see @Web-eWorks self-assigned this. But he's swamped with reviewing PRs, and re-writing equipment code base, so there's room for taking over this one.

I don't have much time this week. I'm not sure if I can do anything here.

**Comment by mikehgentry** [comment]
> I believe this only happens if you were carrying something that was supposed to be taken to the starport that the new game starts in.

Contra this, and just to be clear but at the risk of stating the bleeding obvious, I suppose it might also trigger if you have a mission to pick something/someone up from the starting spaceport - I haven't checked.
