### ISSUE TITLE
Crash from hyperjump-planner indexing local ship (nil)

### ISSUE THREAD

**Issue by claudiusmueller** [pioneerspacesim/pioneer#5725]
### Observed behaviour
Easily reproducible, happens right after starting a new game, even without taking any action whatsoever. All you have to do is start at Mars and wait for a few (in-game) minutes. Also happens when you fast forward time. In the screenshot below I have the debug window open but it also happens when you start fresh without debug window.

I get the following error message:

![pioneer_debug_01](https://github.com/pioneerspacesim/pioneer/assets/51969417/ba76c3f1-f753-4f44-949b-6a54b6b53c44)

Then:

![pioneer_debug_02](https://github.com/pioneerspacesim/pioneer/assets/51969417/6dfedd31-8330-44fd-b3d3-13139553d80a)

Since I play with full screen this messes up the screen so much that even after killing the pioneer process I have to restart KDE. Maybe something to do with #5671? Certainly a new bug for me after I upgraded to the newest master this morning.

### Expected behaviour
Should not crash.

### Steps to reproduce

1. Start new game on Mars.
2. Wait (or fast forward time) for a few minutes.
3. Crash.

__My pioneer veefcrsion (and OS):__
pioneer version: 48efc4667
OS: openSUSE 15.5

__My output.txt (required) and game save (optional, but recommended)__
[output.txt](https://github.com/pioneerspacesim/pioneer/files/14077808/output.txt)

**Comment by Web-eWorks** [comment]
For future reference, when reporting an error we need the `output.txt` from when you encountered the crash, not from a prior or subsequent launch.

That said, this issue should be fixed by #5721; if not, please re-open the issue after confirming with an up-to-date master build.

**Comment by claudiusmueller** [comment]
Confirmed to be fixed with most recent master.
