### ISSUE TITLE
couldn't run a editor

### ISSUE THREAD

**Issue by raariansyah** [pioneerspacesim/pioneer#5736]
### Observed behaviour
run a editor

### Expected behaviour
the editor closes automatically

### Steps to reproduce
1.open editor app

__My pioneer version (and OS):__
Windows 11
Pioneer version: 2024-02-03

__My output.txt (required) and game save (optional, but recommended)__

**Comment by Web-eWorks** [comment]
As documented on the [wiki page](https://wiki.pioneerspacesim.net/wiki/Custom_Systems), you need to run the editor from the command line and pass the `--system` flag.
