### ISSUE TITLE
Size edtor app is too large 

### ISSUE THREAD

**Issue by raariansyah** [pioneerspacesim/pioneer#5742]
after running in editor app but suddenly size the app screen is too large but i cant resize them

here the actual screenshot size is 1366x768 while running editor app:
![Screenshot (47)](https://github.com/pioneerspacesim/pioneer/assets/129280916/ee19025e-b1ed-41d1-8e5c-be2bdeebe3a1)

**Comment by nozmajner** [comment]
You can set the window resolution in  Documents/Pioneer/editor.ini 
(~/.pioneer on linux I think)

**Comment by Web-eWorks** [comment]
Yes, set the `ScrWidth` and `ScrHeight` keys in editor.ini. The editor defaults to 1600x900 which should fit on most modern systems.
