### ISSUE TITLE
Broken links in net.pioneerspacesim.Pioneer.metainfo.xml

### ISSUE THREAD

**Issue by sagitter** [pioneerspacesim/pioneer#5747]
Hi all.

The links
https://github.com/pioneerspacesim/pioneer/blob/3ebceca6514bed515b276cc54f739252d6cb81e4/metadata/net.pioneerspacesim.Pioneer.metainfo.xml#L42
https://github.com/pioneerspacesim/pioneer/blob/3ebceca6514bed515b276cc54f739252d6cb81e4/metadata/net.pioneerspacesim.Pioneer.metainfo.xml#L45
https://github.com/pioneerspacesim/pioneer/blob/3ebceca6514bed515b276cc54f739252d6cb81e4/metadata/net.pioneerspacesim.Pioneer.metainfo.xml#L48
...

are missing

**Comment by impaktor** [comment]
Ping @VasanthBalguri

**Comment by VasanthBalguri** [comment]
I think the links in the metainfo are broken.
I currently dont know where the url for screeshots are, need to check.

**Comment by impaktor** [comment]
@VasanthBalguri I suggest grabbing them from here: https://github.com/pioneerspacesim/pioneer-hugo/tree/master/static/carousel

**Comment by VasanthBalguri** [comment]
Seems like there is some scope for automation. I will take a look at it.

**Comment by VasanthBalguri** [comment]
For now manually fixing the links, automation seems unnecessary as this will be only changed once every release if there is change in documentation I suppose.
