### ISSUE TITLE
Datadir problems

### ISSUE THREAD

**Issue by etam** [pioneerspacesim/pioneer#5750]
Version: 20240203

### Observed behaviour

Game fails to start, because it can't find it data files.

For example it looks for "/usr/share/pioneer/icons/badge.png", but it's installed in "/usr/share/pioneer/data/icons/badge.png".

The previous version (20230203) was not adding the "/data/" part.

### Expected behaviour

It should work. 

### Steps to reproduce

- Build and install the game under Linux using "cmake -DPIONEER_DATA_DIR=/usr/share/pioneer"
- Run the installed game

Context: I'm packaging pioneer for openSUSE. See https://build.opensuse.org/package/show/home:etamPL:branches:games/pioneer

**Comment by etam** [comment]
Yep, now it finds files correctly.

**Comment by Web-eWorks** [comment]
Added some documentation regarding the build presets we ship to COMPILING.txt if interested. Closing this issue as resolved - as you figured out, the PIONEER_DATA_DIR variable now needs to point to `/usr/share/pioneer/data` if the game is installed to `/usr/share/pioneer`. (This resolved a problematic inconsistency where the data directory sometimes pointed to the data folder and sometimes to the containing folder).
