### ISSUE TITLE
Last date of engine service is nil

### ISSUE THREAD

**Issue by veksever** [pioneerspacesim/pioneer#5752]
### Observed behaviour
Last date of engine service is nil (even if I had done it earlier)
![engine_service_bug](https://github.com/pioneerspacesim/pioneer/assets/99830004/c7a5b826-a185-431f-ba15-e1edc956845a)

### Expected behaviour
The field should display the last date of service

### Steps to reproduce
Select "Engine servicing" in station bulletin board

__My pioneer version (and OS):__
ver 20240203 (e7f3122) on: Windows

__My output.txt (required) and game save (optional, but recommended)__

[output.txt](https://github.com/pioneerspacesim/pioneer/files/14214915/output.txt)

**Comment by impaktor** [comment]
Do you remember if this was from a "new game" from the same session, or a loaded previous game session?

**Comment by veksever** [comment]
I always see "nil" there, in all cases.

Now I checked again:
- Run the program
- Choose a new game on Mars.
- Go to the message board
- Select "Engine Servicing".
- See "nil".

Even if I perform a service, when I select that service again I see "nil".

**Comment by impaktor** [comment]
Yeah, it's in master too, also for English, supposed to say:
`Your drive has not been serviced since it was installed on 21:49:53 9 Feb 3224`
