### ISSUE TITLE
Flight Log crash.

### ISSUE THREAD

**Issue by rochr4** [pioneerspacesim/pioneer#5762]
Crash after deleting default single Flight log entry on New Game.

### Expected behaviour
I shall have log entry deleted / cleaned.

### Steps to reproduce
Start New Game, go to Flight Log, delete entry.

__My pioneer version (and OS):__
2619555d0dcf4f76c646e35e91d67c6d11e4ece5 branch 'master' of https://github.com/pioneerspacesim/pioneer
Linux

[output.txt](https://github.com/pioneerspacesim/pioneer/files/14251272/output.txt)
![2024-02-12_1920x1080](https://github.com/pioneerspacesim/pioneer/assets/60553713/db4db9de-0e2a-425c-8c2a-7de7d9e17fb6)

**Comment by impaktor** [comment]
@JonBooth78 you want this one?

**Comment by JonBooth78** [comment]
@impaktor  - sure I'm happy to take it
