### ISSUE TITLE
Hyperspace text color is unintentional

### ISSUE THREAD

**Issue by impaktor** [pioneerspacesim/pioneer#5765]
Color used to be green (since 2008). Many other green HUD elemets have been shifted to orange/amber (like nav tunnel).

Now the color has changed, to be that from the market, I think, for some reason, which I don't think was intentional. 

We just need to explicitly set some intentional color, I think we agreed on in IRC.

![2024-02-14-180132_1536x960_scrot](https://github.com/pioneerspacesim/pioneer/assets/619390/c2e0930f-c5a0-4340-8048-2d3a6d844bf7)

**Comment by nozmajner** [comment]
I've checked in the theme, and it is defined by 
`hyperspaceInfo			= styleColors.success_300,`
And success_300 sticks out from the others, as the only purple among the greens:
![image](https://github.com/pioneerspacesim/pioneer/assets/4182678/f1569814-6359-40ad-b0a3-b500d8496a66)
I'll change success_300 to an appropriate green. And I think that green could work for in this case too, or I could swithc ito to one of the oranges in the theme

**Comment by Web-eWorks** [comment]
This was broken in #5715 (and partially my fault) - I didn't catch that you changed `success_300` to a *completely* different hue rather than tweaking its position in the progression of the green `success` palette. I'd recommend reverting `success_300` back to its previous value.

**Comment by nozmajner** [comment]
Oh joy, this is why I shouldn't do anything tired. I didn't even realize that it was me. Sorry
