### ISSUE TITLE
Flying down in a hyperjump

### ISSUE THREAD

**Issue by veksever** [pioneerspacesim/pioneer#5770]
### Observed behaviour
Flying down in a hyperjump

https://github.com/pioneerspacesim/pioneer/assets/99830004/12f45437-0884-4e14-ade8-7f2d5fe733d6

### Expected behaviour
Flying forward =)

### Steps to reproduce
Just make a hyperjump to any system

__My pioneer version (and OS):__
ver 20240203-dev on: Windows

__My output.txt (required) and game save (optional, but recommended)__
[output.txt](https://github.com/pioneerspacesim/pioneer/files/14320069/output.txt)

**Comment by Gliese852** [comment]
Looks cool in my opinion!

Are you sure you pointed the bow of the ship at the target system?

**Comment by veksever** [comment]
> Looks cool in my opinion!
> 
> Are you sure you pointed the bow of the ship at the target system?

This does not depend on the direction of the ship's bow. I just tried it in the other direction - same thing.

**Comment by Gliese852** [comment]
@veksever Please tell me, where did you get the -dev version? I'm surprised that there is no commit hash.

**Comment by veksever** [comment]
> @veksever Please tell me, where did you get the -dev version? I'm surprised that there is no commit hash.

today, when I saw that the projectiles were fixed, I downloaded and compiled the latest code =)

**Comment by Gliese852** [comment]
So you don't use git?

**Comment by veksever** [comment]
I just cloned the repository and compiled the code
