### ISSUE TITLE
Game does not start What can i do?

### ISSUE THREAD

**Issue by EckhardBrunkhorst** [pioneerspacesim/pioneer#5786]
### Steps to reproduce

__My pioneer version (and OS):__ 

__My output.txt (required) and game save (optional, but recommended)__
Betriebsystemname	Microsoft Windows 11 Home
Version	10.0.22631 Build 22631
Weitere Betriebsystembeschreibung 	Nicht verfügbar
Betriebsystemhersteller	Microsoft Corporation
Systemname	DESKTOP-GS26109
Systemhersteller	Gigabyte Technology Co., Ltd.
Systemmodell	B460HD3
Systemtyp	x64-basierter PC
System-SKU	Default string
Prozessor	Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz, 4104 MHz, 6 Kern(e), 12 logische(r) Prozessor(en)
BIOS-Version/-Datum	American Megatrends Inc. F3, 01.09.2020
SMBIOS-Version	3.2
Version des eingebetteten Controllers	255.255
BIOS-Modus	UEFI
BaseBoard-Hersteller	Gigabyte Technology Co., Ltd.
BaseBoard-Produkt	B460 HD3
BaseBoard-Version	x.x
Plattformrolle	Desktop
Sicherer Startzustand	Aus
PCR7-Konfiguration	Erweiterung zum Anzeigen erforderlich
Windows-Verzeichnis	C:\WINDOWS
Systemverzeichnis	C:\WINDOWS\system32
Startgerät	\Device\HarddiskVolume17
Gebietsschema	Deutschland
Hardwareabstraktionsebene	Version = "10.0.22621.2506"
Benutzername	DESKTOP-GS26109\Eckhard Brunkhorst
Zeitzone	Mitteleuropäische Zeit
Installierter physischer Speicher (RAM)	32,0 GB
Gesamter physischer Speicher	31,9 GB
Verfügbarer physischer Speicher	24,2 GB
Gesamter virtueller Speicher	33,9 GB
Verfügbarer virtueller Speicher	23,7 GB
Größe der Auslagerungsdatei	2,00 GB
Auslagerungsdatei	C:\pagefile.sys
Kernel-DMA-Schutz	Aus
Virtualisierungsbasierte Sicherheit	Wird ausgeführt...
Virtualisierungsbasierte Sicherheit – erforderliche Sicherheitseigenschaften	
Virtualisierungsbasierte Sicherheit – verfügbare Sicherheitseigenschaften	Allgemeine Virtualisierungsunterstützung, DMA-Schutz, UEFI-Code Readonly, SMM Security Mitigations 1.0, Modusbasierte Ausführungssteuerung, APIC-Virtualisierung
Virtualisierungsbasierte Sicherheit – konfigurierte Dienste	Durch Hypervisor erzwungene Codeintegrität
Virtualisierungsbasierte Sicherheit – ausgeführte Dienste	Durch Hypervisor erzwungene Codeintegrität
Windows Defender-Anwendungssteuerungsrichtlinie	Erzwungen
Windows Defender-Anwendungssteuerungs-Richtlinie für den Benutzermodus	Aus
Unterstützung der Geräteverschlüsselung	Erweiterung zum Anzeigen erforderlich
Es wurde ein Hypervisor erkannt. Features, die für Hyper-V erforderlich sind, werden nicht angezeigt.

**Comment by impaktor** [comment]
1. Is your pioneer version the 2023-02-03 one?
2. has pioneer worked before? If so, what changed? pioneer-version? different machine?

**Comment by EckhardBrunkhorst** [comment]
Hi, yes its the current version, never installed on this machine before.

**Comment by EckhardBrunkhorst** [comment]
I found out its becaouse of Windows Ransomware protection. After i deactivated, id did work.

**Comment by impaktor** [comment]
Good, sounds like you solved it then. 
Thanks for donation :)
