### ISSUE TITLE
Pulse shots being fired from a different location from the ship

### ISSUE THREAD

**Issue by Helioth** [pioneerspacesim/pioneer#5791]
### Observed behaviour
Pulse shots are being fired from a different location from the ship, making impossible to target enemy ships.
This happens for example at a relative high velocity or after a hyperjump.
This doesn't happen e.g. close to a planet with small relative velocity to the planet.
It seems the shots being fired are not in the same reference frame as the ship.

### Expected behaviour
Shots being fired from the location of the ship itself, as it was the case in the previous version.

### Steps to reproduce
Start a new game (e.g. Mars), do a hyperjump, and fire a few shots with a pulse canon.

__My pioneer version (and OS):__
Version : 2024-02-03
Previous version was bug-free : 2023-02-03
OS: W8.1 x64

**Comment by impaktor** [comment]
Fixed master by #5767, thanks for report.
We'll do a bug-fix release in a week, on pi-day (3.14)
