### ISSUE TITLE
Can't move view with mouse

### ISSUE THREAD

**Issue by Miner34dev** [pioneerspacesim/pioneer#5799]
### Observed behaviour
The view seems to try to move but returns back to the old position after a frame

### Expected behaviour
Move the view smoothly

### Steps to reproduce
Press and hold the mouse wheel and try to move the view

__My pioneer version (and OS):__ Pioneer release 2024-03-14, Arch linux derivate, KDE plasma 6

**Note:** I have not played 2024-02-03 on KDE6 so i don't know if the issue is caused by the new Pioneer version or KDE.

**Comment by impaktor** [comment]
This is in WorldView? (I.e. cockpit), or on starmaps?

**Comment by Miner34dev** [comment]
It happens on both.

**Comment by Miner34dev** [comment]
This was probably a problem with the system ui, fixed after a system upgrade.
