### ISSUE TITLE
UI: Buttons overlap the speed-limiter icon

### ISSUE THREAD

**Issue by SomenameIchose** [pioneerspacesim/pioneer#5800]
### Observed behaviour
3 buttons overlap the speed-limiter button
![screenshot-20240315-215804](https://github.com/pioneerspacesim/pioneer/assets/154741968/b2208055-3560-43f7-bf7b-a890770d68cf)

### Expected behaviour
Those 3 buttons must be above the speed-limiter

### Steps to reproduce
1. Just press the speed-limiter button to open a menu of 3 buttons

__My pioneer version (and OS):__

ver 20240314 (8b6ae92) on: Windows

__My output.txt (required) and game save (optional, but recommended)__
[output.txt](https://github.com/pioneerspacesim/pioneer/files/14623395/output.txt)

**Comment by impaktor** [comment]
I think this depends on which resolution you have on your screen and which resolution you've set pioneer to use (in settings-option, or set in config.txt file in your pioneer user folder)

**Comment by SomenameIchose** [comment]
> I think this depends on which resolution you have on your screen and which resolution you've set pioneer to use (in settings-option, or set in config.txt file in your pioneer user folder)

No, screen resolution and in settings are the same

**Comment by SomenameIchose** [comment]
in ver 20230203 (e77da96) speed-limiter's displayed properly

**Comment by zonkmachine** [comment]
I bisected on master and it looks like this was introduced in https://github.com/pioneerspacesim/pioneer/pull/5599
Not all commits would build, leading to skipping.

```
~/builds/pioneer$ git bisect good
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
9568be687e53fe5743868cdbdb2de0bca612183a
77d2201b9d40e298c3e965b7d99284d414c6e452
d8961719cfb79e7a77b23808b1bafb30db1486ef
bcd45c29077d7153b17e832a5c9e8789dc5a8b29
We cannot bisect more!
```

---

Git log of the commits above gives:

```
$ git log bcd45c29077d7153b17e832a5c9e8789dc5a8b29
commit bcd45c29077d7153b17e832a5c9e8789dc5a8b29 (refs/bisect/bad)
Author: Webster Sheets <webster@web-eworks.com>
Date:   Sun Aug 6 01:56:32 2023 -0400

    Update pioneer code for imgui upgrade

commit 77d2201b9d40e298c3e965b7d99284d414c6e452 (refs/bisect/skip-77d2201b9d40e298c3e965b7d99284d414c6e452)
Author: Webster Sheets <webster@web-eworks.com>
Date:   Sun Aug 6 01:17:26 2023 -0400

    Apply pioneer imgui patches

commit 9568be687e53fe5743868cdbdb2de0bca612183a (refs/bisect/skip-9568be687e53fe5743868cdbdb2de0bca612183a)
Author: Webster Sheets <webster@web-eworks.com>
Date:   Sun Aug 6 02:16:59 2023 -0400

    Update pioneer imgui patches

commit d8961719cfb79e7a77b23808b1bafb30db1486ef (refs/bisect/skip-d8961719cfb79e7a77b23808b1bafb30db1486ef)
Author: Webster Sheets <webster@web-eworks.com>
Date:   Sun Aug 6 00:58:07 2023 -0400

    Upgrade imgui to v1.89.8
```

**Comment by SomenameIchose** [comment]
Nice job! Thank you!
