### ISSUE TITLE
Extremely LOUD white noise until game exit after mouse steering

### ISSUE THREAD

**Issue by pcercuei** [pioneerspacesim/pioneer#5804]
### Observed behaviour

And extremely LOUD white noise can be triggered by just playing the game. When it triggers, steering with the keyboard is not possible anymore. The only way to stop the white noise, is to exit back to the main menu.

### Expected behaviour

Calm and quiet game session.

### Steps to reproduce

1. Get my savestate from https://app.box.com/s/6mg4zw13oqec83yg6533t5vf43aeg6oi
2. Load the savestate in the game
3. Press the "Take off" button on the bottom bar
4. When in the air, right-click on an empty space of the screen, then drag the mouse. Repeat a few times if needed, until the bug appears.

__My pioneer version (and OS):__
Pioneer master (7f1cb216e)

__My output.txt (required) and game save (optional, but recommended)__

[output.txt](https://github.com/pioneerspacesim/pioneer/files/14736177/output.txt)

**Comment by nozmajner** [comment]
Addendum: 
I was unable to trigger this with a new game, but it was pretty reliable with the attached save. I was unable to get it with keyboard steering, only with the mouse. It happens with or without the flight assists, and even after you fly for a bit.
It seems like it doesn't happen after a hyperjump.
Also I noticed that that save sometimes won't load, it says it is corruped (damaged?), then it loads after reselecting the save and pressing of the load button. Or crashes the game without an error message. This happens after loading it once, then exiting back to the main menu. Not sure if it is releated, or a general issue with the loading code. 

https://github.com/pioneerspacesim/pioneer/assets/4182678/8d79bb49-2036-40ae-a39e-e8e7652c9d57

**Comment by p164505** [comment]
I can't remember if it ever happened with any other ship than the Xylophis, after playing for maybe a few hours, taking off of an orbital station and often during the flight. I can regain rotation control when setting time acceleration to 10x for a few seconds, but only until the rotation stops. Trying to dock in this state or colliding with the orbital station freezes the game for me.
Playing on an up-to-date installation of Artix (linux with OpenRC, glibc) with the newest release(I have not yet tried to compile myself):
https://github.com/pioneerspacesim/pioneer/releases/tag/20240314
Here's my savefile too where I was close to docking if it is of help:
[b.gz](https://github.com/pioneerspacesim/pioneer/files/14849740/b.gz)

**Comment by neumond** [comment]
Happened to me, made some debugging. Save data contains `m_angVel = -nan,-nan,-nan`, and many other things related to rotation get NaN poisoning. Subjectively, happens mostly after using autopilot on maximum time speed.

**Comment by pcercuei** [comment]
If that matters, I never use the autopilot.

**Comment by p164505** [comment]
> If that matters, I never use the autopilot.

The first thing I do in a new game is sell the autopilot. I didn't use it at all in my above save but I still have the issue. I have not tested if using it has any effect  but it happened a lot when travelling from an orbital station.
By the way, I also didn't set time acceleration above 1000x because it messed with the physics a little (shifted the prograde indicator a tiny bit).

**Comment by neumond** [comment]
Well, looks like when desired mouse direction becomes equal to ship direction, their cross product becomes all zeros, and when it gets normalized, it's all NaNs.

https://github.com/pioneerspacesim/pioneer/blob/c9abf3c3500f7c467083700f261da357e680426e/src/ship/PlayerShipController.cpp#L109

So, to avoid the bug, you must have right mouse button released when blue mouse marker coincides with forward marker.
