### ISSUE TITLE
cmake tries to install libfmt

### ISSUE THREAD

**Issue by Eragonfr** [pioneerspacesim/pioneer#5805]
I'm trying to fix the new archlinux pioneer package. All commands are taken from their build script here.
https://gitlab.archlinux.org/archlinux/packaging/packages/pioneer

### Observed behaviour
After build cmake --install tries to install libfmt in the system

### Expected behaviour
libfmt is not installed by cmake

### Steps to reproduce
Build with 
```bash
cmake -S . -B build -G Ninja \
  -D CMAKE_INSTALL_PREFIX:PATH=/usr/local \ # Changed the prefix path because I don't want to put non-packaged stuff in /usr
  -D PIONEER_DATA_DIR:PATH=/usr/local/share/pioneer/data \
  -D USE_SYSTEM_LIBGLEW:BOOL=ON \
  -D USE_SYSTEM_LIBLUA:BOOL=ON \
  -D CMAKE_EXPORT_COMPILE_COMMANDS=1 \
  -Wno-dev

cmake --build build -j 10 --target all build-data
```
Install with
```bash
cmake --install build --strip
```

__My pioneer version (and OS):__ Sources from release 20240314 on ArtixLinux (Arch based, the only difference is the init)

EDIT: This is the same on Archlinux official build servers.

**Comment by pcercuei** [comment]
Setting `-DFMT_INSTALL=OFF` should work.
(but this probably should be forced in the main CMake script, yes)

**Comment by Eragonfr** [comment]
It works, thank you.

**Comment by impaktor** [comment]
We want to keep this open until someone PRs the suggested change, I assume
