### ISSUE TITLE
Bowfin landing gear animation bug

### ISSUE THREAD

**Issue by Maks2103** [pioneerspacesim/pioneer#5813]
### Observed behaviour
Landing gear freaks out at some point when playing deploy/retract animation, it can be easily seen in model viewer with animation progression set to 0.777-0.788
Screenshot attached
![изображение](https://github.com/pioneerspacesim/pioneer/assets/13766524/3dd1d0b2-49b3-44d5-875e-39de7cac0351)
As for latest bug-free veresion - not sure which one that would be, as I didn't use this ship much in older versions.

### Expected behaviour
Landing gear animation working properly

### Steps to reproduce
Start game with Bowfin, take off, retract landing geat and watch closely
Alternatively: check in the model viewer with animation playback or with specific frames

__My pioneer version (and OS):__
Pioneer version: release from 14.03.2024
OS: Windows 10 x64

__My output.txt (required) and game save (optional, but recommended)__
Not sure that this one actually needs an output txt, but here goes
[output.txt](https://github.com/pioneerspacesim/pioneer/files/14861754/output.txt)

**Comment by nozmajner** [comment]
Hmm, it also happens on last years release. I'll check.

**Comment by nozmajner** [comment]
@Maks2103 PR-ed a fix, but here are the fixed files if you don't want to fiddle with a build/reinstall:
[bowfin_fix.zip](https://github.com/pioneerspacesim/pioneer/files/14863740/bowfin_fix.zip)
Remove bowfin.sgm from data/models/ships/bowfin, and extract the contents of the above zip to that folder. (won't work as a mod, sgms aren't overriden)
