### ISSUE TITLE
Cubed symbol causes crash in Windows build

### ISSUE THREAD

**Issue by Keeper1st** [pioneerspacesim/pioneer#5815]
When starting a new game from a fresh compile for Windows x64, the game crashes when going to the New Game screen. The source of the crash was found in the log: The game cannot load _lang/core/en.json_ because of the ³ character in the abbreviation text for Cubic Meters on line 1756. Changing that superscript 3 to a normal 3 has rectified the problem.

**Comment by Keeper1st** [comment]
I tried re-saving the file with UTF-8 encoding instead of ANSI, as the error had suggested it was a UTF-8 issue, but the same error occurred even with the file saved as UTF-8.

**Comment by Keeper1st** [comment]
OK, now I switched back to UTF-8 and re-typed the character, and it works. So maybe there's no problem after all, for I did make edits to the file previously. I guess the program I use to merge my edits into the default files does not preserve the encoding of the original file...? Or maybe the original file was not UTF-8 to begin with and there really _is_ a problem...

**Comment by impaktor** [comment]
For the record, change was committed by bot 2024-02-24,  4be47541e98c470ce1f7237bf279ad922fbdf120

>  for I did make edits to the file previously.

OK, that makes sense. Your editor butchered the encoding, it seems. Haven't seen this issue reported and should have been included since 3.14 release.
