### ISSUE TITLE
Game window invisible when resolution set to match monitor resolution.

### ISSUE THREAD

**Issue by miloszgost** [pioneerspacesim/pioneer#5819]
### Observed behaviour

When tweaking the window settings for my screen, I wanted to have an accesible (visible) window
instead of fullscren. After making changes however, the end result is the same as in fullscreen.
I took screenshots (they are exactly what the end-user sees).
![Zrzut ekranu 2024-04-12 190941](https://github.com/pioneerspacesim/pioneer/assets/95043396/1aea9119-1ccc-4077-a7d1-5906916c2e9e)
As stated above, no window bar visible.
![Zrzut ekranu 2024-04-12 191050](https://github.com/pioneerspacesim/pioneer/assets/95043396/c0b21f41-a430-416d-887e-39f95be1f919)

### Expected behaviour

The window bar should be visible when setting resolution 1920x1080 of the 1920x1080 screen.

### Steps to reproduce

1. Have a 1920x1080 screen.
2. Turn off fullscreen and set resolution to 1920x1080.
3. Restart the game.

__My pioneer version (and OS):__ ver 20240314 (8b6ae92) on: Windows

__My output.txt__

[output.txt](https://github.com/pioneerspacesim/pioneer/files/14963786/output.txt)

__Since it involves rendering, here's the opengl.txt__

[opengl.txt](https://github.com/pioneerspacesim/pioneer/files/14963819/opengl.txt)

**Comment by Web-eWorks** [comment]
To have a visible window bar, the resolution would need to be smaller than 1920x1080 by an OS-dependent value (the height and width of the window decorations on each axis). This is not a bug - you are setting the resolution of the *game content* not the total window extents including OS theming. This is not an item that will be addressed until such a time as support is added runtime resize of the game window.

**Comment by Zireael07** [comment]
The fact that it is window *content* and not window height isn't made clear enough in the settings window imo
