### ISSUE TITLE
 v.20240314 segmentation fault

### ISSUE THREAD

**Issue by l0ddej0kk0** [pioneerspacesim/pioneer#5824]
Hi,
[pioneer20240311.log](https://github.com/pioneerspacesim/pioneer/files/15048024/pioneer20240311.log)

A Search in the issue tracker didn't reveal any relevant entries.

### Observed behaviour
On my Linux laptop both the Appimage and the .tar.gz of  v.20240314 crash after the intro when clicking "start game" with "segmentation fault", no other errors, no entry in system logs.
I captured the last lines of pioneer's output, started in the game's directory, into pioneer20240311.log (included).

### Expected behaviour
Like v.20240203 (which seems to work just fine), after "start game" the spaceport scenery to come up.

### Steps to reproduce
Put the Appimage or the contents of the tar.gz file somewhere (/opt/4user/pioneer-spacesim for me),
cd there,
./pioneer (or the Appimage)
click "New Game"
click "start game"

__My pioneer version (and OS):__
 v.20240314, 
 Debian stable Bookworm, kernel 6.1.85-1

__My output.txt (required) and game save (optional, but recommended)__
Sorry, i don't have a output.txt from my pioneer config folder, /home/{myuser}/.pioneer never gets created.

For now, i'll use v.20240203.

regards, rec0ok

**Comment by l0ddej0kk0** [comment]
Hi,
just read about gdb usage in this case, so i added:
the last lines of output under gdb
[pioneer20240311gdb.log](https://github.com/pioneerspacesim/pioneer/files/15048455/pioneer20240311gdb.log)

and the gdb backtrace
[pioneer20240311gdb_backtrace.log](https://github.com/pioneerspacesim/pioneer/files/15048456/pioneer20240311gdb_backtrace.log)

Best regards

**Comment by Web-eWorks** [comment]
Crash is inside libfmt, and the stack appears to be at least partially corrupt (the execution flow definitely doesn't go through `luaH_newkey` and `0x0028`). Unsure that I can do anything about this crash dump. I expect it's most likely some formatting weirdness similar to the other libfmt issues we've had.
