### ISSUE TITLE
Mismatch between commodity import/export status as seen on the starmap and their actual market status.

### ISSUE THREAD

**Issue by Mrhnhrm** [pioneerspacesim/pioneer#5836]
### Observed behaviour
According to the economic overview of _Tsubatai_ system as seen on the star map, _Industrial Machinery_ is a major import. When I land there and go to the local commodity market, i suddenly find out that _Industrial Machinery_ is a major export. In fact, barely any commodity at all obeys the import/export status as seen on the star map. Surely, there are random fluctuations of supply and demand that can be observed by reloading a saved game and flying there again or docking at a different starport. But the import/export stati of commodities are reliably far off of what was advertised on the star map.

### Expected behaviour
Actual market import/export status of commodities should be consistent with the expectations set by the economic overview of a system as seen on the star map.

### Steps to reproduce
Load the saved game (unpack from _meh4.zip_).
Open the star map and ascertain that _Tsubatai_ system takes major import of _Industrial Machinery_.
Hyperjump to _Tsubatai A_.
Dock with _Flores Town_.
Go to the commodity market and discover that _Industrial Machinery_ is an export good.
Optionally, travel to any other starport on the planet to see that none of them have any noteworthy demand for _Industrial Machinery_.
Also optionally, observe that local imports/exports thoroughly mismatch the expectations set by the economic overview from the star map.

__My pioneer version (and OS):__
ver 20240314 (e470831 PR#5812), AVX flavour, binary downloaded from GitHub. Linux (64 bit, Gentoo).

__My output.txt (required) and game save__
[output.txt](https://github.com/pioneerspacesim/pioneer/files/15407083/output.txt)
[meh4.zip](https://github.com/pioneerspacesim/pioneer/files/15407210/meh4.zip)

**Comment by Web-eWorks** [comment]
Keep in mind that the import/export information shown on the station market screen is for that station specifically, and is *relative to the system's economy as a whole*. So a major export in a station of a commodity that's already a major export system-wide is going to be a very significant value, but a minor import of a major export commodity isn't as bad as it might seem.

There could most likely be a better display of this information on a dedicated economy screen of some kind, as I agree that the current nomenclature and display creates a misleading perception of what's actually going on.
