### ISSUE TITLE
Hyperdrive when breaking down frees up the slot while taking up space

### ISSUE THREAD

**Issue by Omega596** [pioneerspacesim/pioneer#5837]
### Observed behaviour
The hyperdrive slot frees up visually after it breaks down and still take up space

### Expected behaviour
The hyperdrive slot should show: "Broken hyperdrive {class} class" in my opinion.

### Steps to reproduce
The hyperdrive to break down.

__My pioneer version (and OS):__
Pioneer 20240314-5
Linux 6.9.2-arch1-1 on Endeavour OS

__My output.txt (required) and game save (optional, but recommended)__

**Comment by Omega596** [comment]
[output.txt](https://github.com/user-attachments/files/15521456/output.txt)
[savefiles.zip](https://github.com/user-attachments/files/15521462/savefiles.zip)

**Comment by impaktor** [comment]
> The hyperdrive slot should show: "Broken hyperdrive {class} class" in my opinion.

I think the commodity "rubble" is simpler and what the original game had, and what I'd opt for until @Web-eWorks's big reworked equipment branch is done.

**Comment by Omega596** [comment]
that makes sense

**Comment by impaktor** [comment]
Since you closed it, I assume you found "rubble" in your cargo hold.

**Comment by Omega596** [comment]
I didn't, so...

**Comment by Omega596** [comment]
wait i did
