### ISSUE TITLE
Gj1057d dominates Frame of Reference

### ISSUE THREAD

**Issue by oreganor** [pioneerspacesim/pioneer#5839]
Seems that there is a bug in grav points or frame of refence in system Gj1057

### Observed behaviour
Frame of reference "sticks" to Gj1057d while there are stronger g-fields generated by nearby sources. This complicates operations in the system, the most disruptive, not been able to dock on any Spaceport in Boer's Claim as I understand that collission detection is linked to grav point definitions.

### Expected behaviour
FoR should switch to strongest g-field generator, in this case, Boer's Claim.

### Steps to reproduce
Try to land on any of the spaceports of Boer's Claim, The savegame is prepared to issue maneuvers around Boer's Claim to see the effect in action.

My pioneer version (and OS): 8b6ae92 win

__My output.txt (required) and game save (optional, but recommended)__

[output.txt](https://github.com/user-attachments/files/15858198/output.txt)
[BUG-GV1057d-dominates_reference.zip](https://github.com/user-attachments/files/15858208/BUG-GV1057d-dominates_reference.zip)

**Comment by fluffyfreak** [comment]
I think is related to #5740

**Comment by Bodasey** [comment]
Calculate the Hill sphere / L1/L2 Points and only generate moons inside:

https://en.wikipedia.org/wiki/Hill_sphere

**Comment by Bodasey** [comment]
Which Formula do you use? For Ceres - Sun, I have calculated a Hill-Sphere of 200'000 km, but Pioneer says that even 4000 km around Ceres, the Sun was the dominant source of gravity.

![Screenshot_20240729_085541](https://github.com/user-attachments/assets/ef872209-b1cc-4ece-a38e-c2913ccd16de)

**Comment by impaktor** [comment]
duplicate (now)
