### ISSUE TITLE
Unsorted translated commodity lists

### ISSUE THREAD

**Issue by JeromeChignoli** [pioneerspacesim/pioneer#5844]
Hello.
Trade computer lists unsorted commodities when not in english language.
I use french translation:
"Air processors" translates to "Processeurs d'air".
In trade computer screens, "Processeurs d'air" is the first line of the list.

### Observed behaviour
translated lists are alphabetically sorted by English value.

### Expected behaviour
translated lists should be alphabetically sorted by translated value.

### Steps to reproduce
select other languages in options screen.

__My pioneer version (and OS):__
ver 20240203 on: Linux

### Steps to correct 
in /data/pigui/modules/system-econ-view.lua, table.sort function in lines 101, 102, 128 & 129 needs to be:
lcomm[a[1]] < lcomm[b[1]]    ( in place of  a[1] < b[1] ).

**Comment by impaktor** [comment]
If I remember correctly, this is because we sort not on language, but on the KEY used, which we do because then categories are shows in some what logical order.

**Comment by JeromeChignoli** [comment]
So maybe the commodity market needs to sort the same way.
It actually sorts by translated value.
