### ISSUE TITLE
Task list error

### ISSUE THREAD

**Issue by SomenameIchose** [pioneerspacesim/pioneer#5845]
### Observed behaviour
Got an error trying to open a mission list during jumping
![screenshot-20240622-012156](https://github.com/pioneerspacesim/pioneer/assets/154741968/9229afb6-7d3a-4876-8e20-699e22b5367d)

### Expected behaviour
Open mission with clicking list button.

### Steps to reproduce
1. Pick any mission (interstellar delivery, passanger ets.)
2. Accept the mission.
3. Initiate hyperjump.
4. Open mission list during hyperjump.

__My pioneer version (and OS):__
Pioneer ver. is 20240314(8b6ae92)
OS: Windows 10

__My output.txt (required) and game save (optional, but recommended)__
[output.txt](https://github.com/user-attachments/files/15933932/output.txt)
[save.zip](https://github.com/user-attachments/files/15933938/save.zip)

**Comment by Web-eWorks** [comment]
Fixed by #5843.
