### ISSUE TITLE
All bulletin board items greyed out on game load

### ISSUE THREAD

**Issue by limburgher** [pioneerspacesim/pioneer#5873]
If I dock, save, exit, reopen Pioneer, and load my game, the bulletin board items are all greyed out. If I undock and immediately redock, it's a mix of greyed out and available, as expected.
![Screenshot from 2024-07-22 13-02-53](https://github.com/user-attachments/assets/c4784d5d-c2b2-4d22-903d-ceb41eca8370)
![Screenshot from 2024-07-22 13-04-23](https://github.com/user-attachments/assets/3c404d21-59c7-477a-965a-0d7fe23c4600)

**Comment by impaktor** [comment]
Unpause the game.
