### ISSUE TITLE
Ubuntu 24.04 - Illegal instruction     (core dumped) $SNAP/usr/local/bin/pioneer "$@"

### ISSUE THREAD

**Issue by raj-prince587** [pioneerspacesim/pioneer#5877]
Getting error
```
/snap/pioneer/4/bin/launcher: line 3:  9441 Illegal instruction     (core dumped) $SNAP/usr/local/bin/pioneer "$@"
```

### Observed behaviour
Facing error 
`Illegal instruction     (core dumped) $SNAP/usr/local/bin/pioneer "$@"`

### Expected behaviour
Pioneer SIM should run

### Steps to reproduce
OS: Ubuntu 24.04 LTS

__My pioneer version (and OS):__
```
Info: pioneer 20240710 (dc2706b98)
Info: --------------------
Info: SDL Version (build) 2.0.20
Info: SDL Version (dynamic) 2.0.20
Info: SDL Versions match
Info: SDL_image Version (build): 2.0.5
Info: SDL_image Version (dynamic): 2.0.5
Info: SDL_image Versions match
Info: Assimp Version: 5.2.0
Info: FreeType Version: 2.11.1
Info: GLEW dynamic version: 2.0.0
Info: --------------------

__My output.txt (required) and game save (optional, but recommended)__
Testing for explicit PulseAudio choice...
...and PulseAudio has been explicitly chosen, so using it.
Info: ver 20240710 (dc2706b98) on: Linux
Info: System Name: Linux
Host Name: shivansh-OEM
Release(Kernel) Version: 6.8.0-39-generic
Kernel Build Timestamp: #39-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 21:49:14 UTC 2024
Machine Arch: x86_64
Domain Name: (none)
Info: Loaded mods:

Info: --------------------
Info: SDL Version (build) 2.0.20
Info: SDL Version (dynamic) 2.0.20
Info: SDL Versions match
Info: SDL_image Version (build): 2.0.5
Info: SDL_image Version (dynamic): 2.0.5
Info: SDL_image Versions match
Info: Assimp Version: 5.2.0
Info: FreeType Version: 2.11.1
Info: GLEW dynamic version: 2.0.0
Info: --------------------
Info: 
Info: SDL video driver used: x11
Info: Initialized OpenGL 3.1, with extensions, renderer
Info: Created shader vtxColor (address=0x5d2cefcc9170)
Info: Initializing joystick subsystem.
Info: Loaded PiGui fonts from disk:
Info: font console:s from d0
Info:   - Inpionata.ttf 1
Info:   - DejaVuSansMono.ttf ]1.2
Info:   - wqy-microhei.ttc 1
Info:   - icons/icons.svg ,]5��16x0019
Info: font icons:0
Info:   - PionilliumText22L-Medium.ttf 1
Info:   - icons/icons.svg ,]5��16x0019
Info: font orbiteer:0
Info:   - Orbiteer-Bold.ttf 1
Info:   - DejaVuSans.ttf ]1.2
Info:   - wqy-microhei.ttc 1
Info:   - icons/icons.svg ,]5��16x0019
Info: font pionillium:0
Info:   - PionilliumText22L-Medium.ttf 1
Info:   - DejaVuSans.ttf 7.14e-05
Info:   - wqy-microhei.ttc 1
Info:   - icons/icons.svg ,]5��16x0019
Info: Created shader ui (address=0x5d2cefcf2d40)
/snap/pioneer/4/bin/launcher: line 3:  9441 Illegal instruction     (core dumped) $SNAP/usr/local/bin/pioneer "$@"
```
(imaktor-EDIT:  fixed format)

**Comment by Bodasey** [comment]
This also happens with openSuSE Tumbleweed:

`(gdb) run
Starting program: /home/romaschw/pioneer-master/build/pioneer 

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.opensuse.org/>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Downloading separate debug info for /lib64/ld-linux-x86-64.so.2
Downloading separate debug info for system-supplied DSO at 0x7ffff7fc4000                                     
Missing separate debuginfos, use: zypper install glibc-debuginfo-2.40-1.1.x86_64                              
Downloading separate debug info for /lib64/libfreetype.so.6
Downloading separate debug info for /lib64/libOpenGL.so.0                                                     
Downloading separate debug info for /lib64/libGLX.so.0                                                        
Downloading separate debug info for /lib64/libGLU.so.1                                                        
Downloading separate debug info for /lib64/libsigc-2.0.so.0                                                   
Downloading separate debug info for /lib64/libvorbisfile.so.3                                                 
Downloading separate debug info for /lib64/libstdc++.so.6                                                     
Downloading separate debug info for /lib64/libm.so.6                                                          
Downloading separate debug info for /lib64/libgcc_s.so.1                                                      
Downloading separate debug info for /lib64/libc.so.6                                                          
[Thread debugging using libthread_db enabled]                                                                 
Using host libthread_db library "/lib64/libthread_db.so.1".
Downloading separate debug info for /lib64/libz.so.1
Downloading separate debug info for /lib64/libminizip.so.1                                                    
Downloading separate debug info for /lib64/libbz2.so.1                                                        
Downloading separate debug info for /lib64/libpng16.so.16                                                     
Downloading separate debug info for /lib64/libbrotlidec.so.1                                                  
Downloading separate debug info for /lib64/libGLdispatch.so.0                                                 
Downloading separate debug info for /lib64/libX11.so.6                                                        
Downloading separate debug info for /lib64/libasound.so.2                                                     
Downloading separate debug info for /lib64/libjpeg.so.8                                                       
Downloading separate debug info for /lib64/libtiff.so.6                                                       
Downloading separate debug info for /lib64/libwebpdemux.so.2                                                  
Downloading separate debug info for /lib64/libwebp.so.7                                                       
Downloading separate debug info for /lib64/libvorbis.so.0                                                     
Downloading separate debug info for /lib64/libogg.so.0                                                        
Downloading separate debug info for /lib64/libbrotlicommon.so.1                                               
Downloading separate debug info for /lib64/libxcb.so.1                                                        
Downloading separate debug info for /lib64/libzstd.so.1                                                       
Downloading separate debug info for /lib64/liblzma.so.5                                                       
Downloading separate debug info for /lib64/libjbig.so.2                                                       
Downloading separate debug info for /lib64/libsharpyuv.so.0                                                   
Downloading separate debug info for /lib64/libXau.so.6                                                        
                                                                                                              
Program received signal SIGILL, Illegal instruction.
0x000000000045af5a in Lang::init_string_helper_class::init_string_helper_class (this=<optimized out>)
    at /home/romaschw/pioneer-master/src/LangStrings.inc.h:8
8       DECLARE_STRING(LANG_NAME)
Missing separate debuginfos, use: zypper install libGLU1-debuginfo-9.0.3-2.4.x86_64 libX11-6-debuginfo-1.8.10-1.1.x86_64 libXau6-debuginfo-1.0.11-1.5.x86_64 libasound2-debuginfo-1.2.12-1.1.x86_64 libbrotlicommon1-debuginfo-1.1.0-1.3.x86_64 libbrotlidec1-debuginfo-1.1.0-1.3.x86_64 libbz2-1-debuginfo-1.0.8-5.10.x86_64 libfreetype6-debuginfo-2.13.2-2.2.x86_64 libgcc_s1-debuginfo-14.2.0+git10526-2.1.x86_64 libglvnd-debuginfo-1.7.0-1.3.x86_64 libjbig2-debuginfo-2.1-5.3.x86_64 libjpeg8-debuginfo-8.3.2-79.2.x86_64 liblzma5-debuginfo-5.6.2-1.1.x86_64 libminizip1-debuginfo-1.3.1-1.1.x86_64 libogg0-debuginfo-1.3.5-2.1.x86_64 libsharpyuv0-debuginfo-1.3.2-2.3.x86_64 libsigc-2_0-0-debuginfo-2.12.1-2.3.x86_64 libstdc++6-debuginfo-14.2.0+git10526-2.1.x86_64 libtiff6-debuginfo-4.6.0-5.1.x86_64 libvorbis0-debuginfo-1.3.7-5.1.x86_64 libvorbisfile3-debuginfo-1.3.7-5.1.x86_64 libwebp7-debuginfo-1.3.2-2.3.x86_64 libwebpdemux2-debuginfo-1.3.2-2.3.x86_64 libxcb1-debuginfo-1.17.0-1.1.x86_64 libz1-debuginfo-1.3.1-1.1.x86_64 libzstd1-debuginfo-1.5.6-1.1.x86_64
`

...but these Packages are not available.

Does Ubuntu 24.04 also use gcc/g++ version 14?

**Comment by Bodasey** [comment]
This is july stable, precompiled package by the distributor SuSE, upper one is self-compiled actual master

`(gdb) run
Starting program: /usr/bin/pioneer 

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.opensuse.org/>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Downloading separate debug info for /lib64/ld-linux-x86-64.so.2
Downloading separate debug info for system-supplied DSO at 0x7ffff7fc4000                                     
Missing separate debuginfos, use: zypper install glibc-debuginfo-2.40-1.1.x86_64                              
Downloading separate debug info for /lib64/libOpenGL.so.0
Downloading separate debug info for /lib64/libGLX.so.0                                                        
Downloading separate debug info for /lib64/libsigc-2.0.so.0                                                   
Downloading separate debug info for /lib64/libvorbisfile.so.3                                                 
Downloading separate debug info for /lib64/libfmt.so.11                                                       
Downloading separate debug info for /lib64/libGLEW.so.2.2                                                     
Downloading separate debug info for /lib64/libstdc++.so.6                                                     
Downloading separate debug info for /lib64/libm.so.6                                                          
Downloading separate debug info for /lib64/libgcc_s.so.1                                                      
Downloading separate debug info for /lib64/libc.so.6                                                          
[Thread debugging using libthread_db enabled]                                                                 
Using host libthread_db library "/lib64/libthread_db.so.1".
Downloading separate debug info for /lib64/libz.so.1
Downloading separate debug info for /lib64/libminizip.so.1                                                    
Downloading separate debug info for /lib64/libGLdispatch.so.0                                                 
Downloading separate debug info for /lib64/libX11.so.6                                                        
Downloading separate debug info for /lib64/libasound.so.2                                                     
Downloading separate debug info for /lib64/libpng16.so.16                                                     
Downloading separate debug info for /lib64/libjpeg.so.8                                                       
Downloading separate debug info for /lib64/libtiff.so.6                                                       
Downloading separate debug info for /lib64/libwebpdemux.so.2                                                  
Downloading separate debug info for /lib64/libwebp.so.7                                                       
Downloading separate debug info for /lib64/libvorbis.so.0                                                     
Downloading separate debug info for /lib64/libogg.so.0                                                        
Downloading separate debug info for /lib64/libGL.so.1                                                         
Downloading separate debug info for /lib64/libxcb.so.1                                                        
Downloading separate debug info for /lib64/libzstd.so.1                                                       
Downloading separate debug info for /lib64/liblzma.so.5                                                       
Downloading separate debug info for /lib64/libjbig.so.2                                                       
Downloading separate debug info for /lib64/libsharpyuv.so.0                                                   
Downloading separate debug info for /lib64/libXau.so.6                                                        
                                                                                                              
Program received signal SIGILL, Illegal instruction.
0x000055555570a7f0 in std::__detail::_Compiler<std::__cxx11::regex_traits<char> >::_S_validate (
    __f=<optimized out>) at /usr/include/c++/14/bits/regex_compiler.h:190
warning: Source file is more recent than executable.
190                 return __f;
Missing separate debuginfos, use: zypper install libGLEW2_2-debuginfo-2.2.0-4.3.x86_64 libX11-6-debuginfo-1.8.10-1.1.x86_64 libXau6-debuginfo-1.0.11-1.5.x86_64 libasound2-debuginfo-1.2.12-1.1.x86_64 libfmt11-debuginfo-11.0.2-1.1.x86_64 libgcc_s1-debuginfo-14.2.0+git10526-2.1.x86_64 libglvnd-debuginfo-1.7.0-1.3.x86_64 libjbig2-debuginfo-2.1-5.3.x86_64 liblzma5-debuginfo-5.6.2-1.1.x86_64 libminizip1-debuginfo-1.3.1-1.1.x86_64 libogg0-debuginfo-1.3.5-2.1.x86_64 libpng16-16-debuginfo-1.6.43-3.1.x86_64 libsharpyuv0-debuginfo-1.3.2-2.3.x86_64 libsigc-2_0-0-debuginfo-2.12.1-2.3.x86_64 libstdc++6-debuginfo-14.2.0+git10526-2.1.x86_64 libtiff6-debuginfo-4.6.0-5.1.x86_64 libvorbis0-debuginfo-1.3.7-5.1.x86_64 libvorbisfile3-debuginfo-1.3.7-5.1.x86_64 libwebp7-debuginfo-1.3.2-2.3.x86_64 libwebpdemux2-debuginfo-1.3.2-2.3.x86_64 libxcb1-debuginfo-1.17.0-1.1.x86_64 libz1-debuginfo-1.3.1-1.1.x86_64 libzstd1-debuginfo-1.5.6-1.1.x86_64
`

**Comment by Bodasey** [comment]
> Does Ubuntu 24.04 also use gcc/g++ version 14?

Yes, it does:

https://discourse.ubuntu.com/t/ubuntu-24-04-lts-noble-numbat-release-notes/39890?_gl=1*1vv5905*_gcl_au*MTI0ODk4MTA0MS4xNzI0OTE2MDcz&_ga=2.201437521.1535485630.1725225988-1022566305.1724916070#toolchain-upgrades

@Web-eWorks , what is your opinion?

**Comment by Web-eWorks** [comment]
I suspect the problem you're running into is that your CPU doesn't support SSE4.2 which we enable compilation for on x86/64 unless manually disabled. Pass `-DUSE_SSE42=0` when running `cmake` or `./bootstrap` and see if that resolves the issue.

**Comment by Bodasey** [comment]
Success!

The option has to be given to the ./bootstrap routine, make/cmake seems not to accept it.

**Comment by impaktor** [comment]
> Success!

@Bodasey @raj-prince587 So this issue can be closed?

**Comment by Bodasey** [comment]
For me, I have got the solution - but if SSE4.2 is not in use for a long time yet, maybe we should keep it open with a more general title for a while.

**Comment by raj-prince587** [comment]
Thank you @impaktor @Bodasey for your help

I am able to install this application using flatpak [https://flatpak.org/setup/Ubuntu]
