### ISSUE TITLE
assertion failed in equipment-market.lua:91

### ISSUE THREAD

**Issue by lolo101** [pioneerspacesim/pioneer#5883]
### Observed behaviour

Stack trace when buying a shield
Note that I bought 12 missiles and had to sell one to have enough room to equip a shield.
Since a missile is 0.5 tons, maybe the exception is caused by a fractional number or something?
![Capture d’écran du 2024-08-04 19-34-32](https://github.com/user-attachments/assets/0145e80c-b687-41b0-8535-ebb52a303d13)

### Expected behaviour

No stack

### Steps to reproduce

Reproducible always

1. Go to the Equipment Market
2. Buy a shield

__My pioneer version (and OS):__
20240314 (Linux)

__My output.txt (required) and game save (optional, but recommended)__
[output.txt](https://github.com/user-attachments/files/16488428/output.txt)
[lolo-stack.gz](https://github.com/user-attachments/files/16488432/lolo-stack.gz)

**Comment by lolo101** [comment]
Note that if you sell an additional missile first, the exception does not raises

**Comment by impaktor** [comment]
```lua
assert(player:AddEquip(e, 1, slot) == 1)
```

**Comment by lolo101** [comment]
That's why it's useful to use named constants instead of magic numbers :wink:
