### ISSUE TITLE
Missiles buttons not showing up

### ISSUE THREAD

**Issue by lolo101** [pioneerspacesim/pioneer#5887]
### Observed behaviour

I have 6 smart missiles loaded in my ship
However in the HUD, the missile button is absent, so I cannot fire them

Note that on a previous flight, I had guided missiles and the butotn showed up correctly

button missing:
![image](https://github.com/user-attachments/assets/ee12e864-73e0-4bfa-b459-530a0740e1a6)

But missiles loaded:
![image](https://github.com/user-attachments/assets/6fc4bfb4-7d0d-4499-9be5-484bb3868ed4)

### Expected behaviour

The missile button is present so I can fire them

### Steps to reproduce

Just load the savegame

__My pioneer version (and OS):__

20240710 (e123a3f91) (Linux)

__My output.txt (required) and game save (optional, but recommended)__
[output.txt](https://github.com/user-attachments/files/16564907/output.txt)
[lolo2.gz](https://github.com/user-attachments/files/16564908/lolo2.gz)

**Comment by impaktor** [comment]
I assume this issue will be fixed by the weapon re-write that's in the pipe line (assuming time & motivation to finish it).

**Comment by lolo101** [comment]
Note: I could fire a missile with the shortcut key.
Later I bought another smart missile to replace the one I used, and then the button showed up but displayed only 1 available missile whereas 6 of them were loaded into the ship

**Comment by Web-eWorks** [comment]
This is a bug with the current equipment system. A rewrite is in progress and is targeted for merge before the next major update.

**Comment by Web-eWorks** [comment]
Note that the underlying cause of this issue is already fixed in #5734.
