### ISSUE TITLE
Failed to start 20230203 on macOS 14.6.1

### ISSUE THREAD

**Issue by drwjf** [pioneerspacesim/pioneer#5902]
### Observed behaviour

Failed to start.

### Expected behaviour

Run pioneer

### Steps to reproduce

% brew install pioneer
% pioneer

__My pioneer version (and OS):__

Pioneer version: 20230203
OS version: 
ProductName:		macOS
ProductVersion:		14.6.1
BuildVersion:		23G93

__My output.txt (required) and game save (optional, but recommended)__

Info: ver 20230203 on: Mac OS X
Info: System Name: Darwin
Host Name: mbp.lan
Release(Kernel) Version: 23.6.0
Kernel Build Timestamp: Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64
Machine Arch: x86_64
Info: --------------------
Info: SDL Version (build) 2.28.3
Info: SDL Version (dynamic) 2.30.6
Info: WARNING: SDL Versions differ
Info: SDL_image Version (build): 2.6.3
Info: SDL_image Version (dynamic): 2.8.2
Info: WARNING: SDL_image Versions differ
Info: Assimp Version: 5.4.0
Info: FreeType Version: 2.13.2
Info: GLEW dynamic version: 2.0.0
Info: --------------------
Info: 
Fatal: OpenGL extension GL_ARB_vertex_attrib_binding not supported.
Pioneer can not run on your graphics card as it does not support vertex attribute bindings.
Please check to see if your GPU driver vendor has an updated driver - or that drivers are installed correctly.
2024-08-25 09:07:51.278 pioneer[24802:271715] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
By

**Comment by impaktor** [comment]
Pioneer is not supported om Mac, as of many years. 

How does brew work, it pulls from github? Why is pioneer in brew?

**Comment by Web-eWorks** [comment]
> Fatal: OpenGL extension GL_ARB_vertex_attrib_binding not supported.
> Pioneer can not run on your graphics card as it does not support vertex attribute bindings.

Mac does not provide an OpenGL implementation suitable to run Pioneer. As a result, Pioneer will not run on a Mac.
