### ISSUE TITLE
Selling prices are not displayed until you actually try to sell a commodity

### ISSUE THREAD

**Issue by lolo101** [pioneerspacesim/pioneer#5903]
### Observed behaviour

In the picture below, Hydrogen's price displayed is $3.95
However, when I sell 1 unit, the price is $3.87

Though I understand that the selling price is lower than the buying price, I would like to have it displayed somewhere in order to
- know the selling price of a commodity even when I don't own any
- develop a feeling of how much I can expect to make with a certain quantity of a commodity
- improve immersion

![image](https://github.com/user-attachments/assets/092fe624-60cf-4de1-a454-07de3a5188fb)

### Expected behaviour

I have access to the selling price along with the buying price

### Steps to reproduce

N/A

__My pioneer version (and OS):__

20240710 Linux

__My output.txt (required) and game save (optional, but recommended)__

**Comment by mwerle** [comment]
Displaying the additional data is trivial.

Getting the layout to look nice is beyond me; after playing with the code for several hours I am not much closer to understanding how the UI works.

Might have to leave this to someone else to implement.

![image](https://github.com/user-attachments/assets/5e7b44f0-cd8c-4138-acca-b30def1fefc7)
