### ISSUE TITLE
Asteroids of unusual size

### ISSUE THREAD

**Issue by zonkmachine** [pioneerspacesim/pioneer#5907]
Found this while looking up lots of systems for the sake of testing planet and base names. Rarely an A.O.U.S. (asteroid of unusual size) would pop up. I haven't seen this with any of the other system bodies.  Could be related to density calculations and https://github.com/pioneerspacesim/pioneer/pull/5592 .

master 2c962df832c69c5cd9f4b83e215d7b4916cb2b8f
Iumir (-14, 11, -9)
![asteroid](https://github.com/user-attachments/assets/f7f212a5-8237-4408-90af-fe279b2b85e2)

### Observed behaviour
Asteroid icon can take on a very large size. It seem to also show unrealistic physical values, density for instance.

### Steps to reproduce
Very odd to find a really big one but either manually go through 100's of systems or load the save game below and search for 'iumir).

Ubuntu 22.04
master (2c962df832c69c5cd9f4b83e215d7b4916cb2b8f)

[output.txt](https://github.com/user-attachments/files/16802119/output.txt)
[opengl.txt](https://github.com/user-attachments/files/16802168/opengl.txt)
[asteroidfun.zip](https://github.com/user-attachments/files/16802143/asteroidfun.zip) (not zipped, just renamed)

**Comment by Bodasey** [comment]
Bodies of this mass usually have radii of around 10 km, not twice or more the radius of Jupiter.

Better set the mass, set the type (icy moon, dry moon, dry material asteroid), add an according density and calculate the size?

The real models of this big image, (101955) Bennu and (162173) Ryugu, destination of OSIRIS-REx and Hayabusa 2 who have brought material from there to Earth, are even smaller (250m and 500m radius) and lighter (7*10^10 and 5*10^12 kg) - I don't know which role such bodies shall have in our game.

**Comment by zonkmachine** [comment]
This doesn't seem to be a new problem but maybe the new system body icon set, the one with asteroid **101955 Bennu** that is in current use, made the issue visible. That and the inclusion of density info that makes the issue more visible.

Here's an asteroid approaching the size of Mars from the commit before #5592 was merged
![asteroidsizeold](https://github.com/user-attachments/assets/946fe856-20da-4738-8bf4-4078b64fc395)

**Comment by zonkmachine** [comment]
Duplicate of https://github.com/pioneerspacesim/pioneer/issues/5854
