### ISSUE TITLE
savefiles directory not created on program start

### ISSUE THREAD

**Issue by mwerle** [pioneerspacesim/pioneer#5921]
Follow-up issue to #5917 to track an improvement to the fix. The current implementation delays creating the "savefiles" directory until a game is being saved.

Details in the #5919 PR discussion thread, the TL;DR is below:

----

After the fix, there is still a popup "user://savefiles is not a directory" when attempting to load a game if the "savefiles" directory has not yet been created.

Fix by creating the "savefiles" directory on program startup in `Pi::App::OnStartup()` or as a task inside `StartupScreen:Start()` in "Pi.cpp".

**Comment by mwerle** [comment]
@Web-eWorks 

Current `Pi.cpp` contains some savefiles stuff underneath a big banner-comment :

```C
/*
===============================================================================
	MISCELLANEOUS GARBAGE THAT OUGHT NOT TO BE IN THIS CLASS
===============================================================================
*/
```

Is this an indication that, ideally, these things should be refactored into a separate place, in which case, this bug appears to be the right time to do this in.

FWIW, most/all of the other directories are created in `Application.cpp:Application::Startup()`.

**Comment by Web-eWorks** [comment]
Correct! There are a few things in there that need a *much* deeper level of refactoring (for example, `Pi::FindModel` needs to be replaced with a model lookup procedure that uses actual paths rather than depending on the filename of every model in the entire game being globally unique...) but `Pi::GetSaveDir()` should ideally be elided or moved.

That header is there to denote existing things that need to be improved in one way or another but I don't have any clear idea on what specifically should be done with them - or enough availability to address them at this stage.

**Comment by mwerle** [comment]
Ok, it's just that you recommended to fix this bug by adding the functionality here, but doing so will add to the tech debt.

I'll have a think about how to rework this.  I'd also like to eventually have the savegame system support directories and/or versions for each save.

Thanks for the info.

**Comment by Web-eWorks** [comment]
I was suggesting something like:

```c++
void Pi::App::OnStartup() {
// ...
Game::CreateSavefileDirectory();
// ...
}

// In Game.cpp
void Game::CreateSavefileDirectory() {
    FileSystem::userFiles.MakeDirectory(Game::SAVE_DIR_NAME);
}
```

This moves the responsibility for creating the directory into the class which is actually creating the savefiles, reduces the amount of "static utility functions" in the Pi API, and is something I'd consider to be acceptable.

I'm interested to hear what your thoughts are on supporting multiple directories/versions - my mind isn't immediately connecting the dots.

**Comment by mwerle** [comment]
..Ah, so the `Pi` class merely triggers the action, but the actual logic should be elsewhere. Gotcha.

I was thinking along the lines of abstracting it all into a "Savegame" class which provides APIs to save a game, load a game, delete a game, and list the available savegames (taking a cue from the "Profiler" class which has its own "Makedirectory" method).  This class could then ensure that the "savefiles"  directory exists and would also remove the need for the Lua to implement directory reading functionality as well as a second place where the "magic" `savefiles` string is required (I'm not a fan of duplication, especially "magic" values).

----

> I'm interested to hear what your thoughts are on supporting multiple directories/versions - my mind isn't immediately connecting the dots.

So currently every save file is standalone; it has a name, and it's in the "savefiles" directory. That's it.

When I play, I usually save the game with a new name "MySaveGame_XX" where XX is an increasing number. This is to allow me to backtrack (yes, "cheat"..) or recover from glitches.

This is firstly a rather menial process, and secondly means I end up with a LOT of saves in "savefiles" which are all listed when I go to load a file.

So I was thinking of 2 approaches to implement this:

1. Have each save in its own directory; ie "savefiles/MySaveGame/XX".  In the first iteration, the game might just support sub-directories and a way to move between them. In later iterations, the game might just present a savegame/version view. This should be fairly easy to implement.
2. Have the game internally manage the versioning somehow, for example, by storing the savefiles as a git repo, and having the interface present a savegame/version view.

Neither of these is going to be quick or simple so this is more a future-improvement idea rather than something to do now. It's probably also total overkill..

**Comment by impaktor** [comment]
What would define a save top folder? Pilot name, for different fresh restarts?

**Comment by mwerle** [comment]
> What would define a save top folder? Pilot name, for different fresh restarts?

That was my initial thought, but there will be issues with pilot names and what the filesystem allows. Can always try to sanitise the actual filesystem name and display the pilot name in-game. Will need a bit more thought on how I want it to work.

A first implementation could just re-use the autosave logic and auto-append a number to the current save file name.
