### ISSUE TITLE
wave forward gun fires backwards

### ISSUE THREAD

**Issue by NotEnoughPotions** [pioneerspacesim/pioneer#5928]
For some reason when flying the wave, the forward and rear gun fires backwards.

**Comment by zonkmachine** [comment]
Duplicate of https://github.com/pioneerspacesim/pioneer/issues/5776 ?

**Comment by NotEnoughPotions** [comment]
huh so it is, ill close this, sorry

**Comment by NotEnoughPotions** [comment]
duplicate
