### ISSUE TITLE
Negative delta-v displayed for certain ships in shipyard

### ISSUE THREAD

**Issue by Maks2103** [pioneerspacesim/pioneer#5940]
**Initially discovered by Cat'O'Wisdom on Discord**

### Observed behaviour
Some ships (currently confirmed: Pumpkinseed, Varada, Xylophis and Kanara) have negative delta-v displayed in stats viewed in shipyard

### Expected behaviour
Having correct value displayed

### Steps to reproduce
Load or start a game, find any of the listed ships in the station's shipyard

__My pioneer version (and OS):__
Pioneer version: release from 10.07.2024
OS: Windows 10 x64

__Screenshots__
![screenshot-20241026-110941](https://github.com/user-attachments/assets/bb26f1c1-d78a-4d25-98eb-3e0738e4a0d7)
![screenshot-20241026-111757](https://github.com/user-attachments/assets/52d69986-0487-4ca2-9d0a-64c6b7c04219)
![screenshot-20241026-111823](https://github.com/user-attachments/assets/30d4a9bc-211d-424e-9080-09bf8193d719)
![screenshot-20241026-111849](https://github.com/user-attachments/assets/e7c48eba-29e9-48c1-b4c4-cf29d7e7a293)

__My output.txt (required) and game save (optional, but recommended)__
[output.txt](https://github.com/user-attachments/files/17529599/output.txt)

**Comment by bszlrd** [comment]
At a glance larger ships are affected too, but their deltaVs are inflated.
