### ISSUE TITLE
$HOME/.pioneer is randomly created on Linux

### ISSUE THREAD

**Issue by WickedSmoke** [pioneerspacesim/pioneer#5942]
Occasionally the $HOME/.pioneer directory is created on Linux as the program thinks that directory already exists.  The following patch should fix this.

```
diff --git a/src/posix/FileSystemPosix.cpp b/src/posix/FileSystemPosix.cpp
index b2a2ff8ec..fb36147b6 100644
--- a/src/posix/FileSystemPosix.cpp
+++ b/src/posix/FileSystemPosix.cpp
@@ -61,8 +61,8 @@ namespace FileSystem {
                path += "Library/Application Support/Pioneer";
 #else
                struct stat info;
-               stat((path + ".pioneer").c_str(), &info);
-               if (S_ISDIR(info.st_mode)) {
+               int err = stat((path + ".pioneer").c_str(), &info);
+               if (err == 0 && S_ISDIR(info.st_mode)) {
                        // Check for legacy pioneer directory.
                        path += ".pioneer";
                } else {
```

**Comment by WickedSmoke** [comment]
Also, is there any guarantee that the temporary string object in `(path + ".pioneer").c_str()` exists during the stat() call?

**Comment by Web-eWorks** [comment]
> Also, is there any guarantee that the temporary string object in `(path + ".pioneer").c_str()` exists during the stat() call?

There is a strong guarantee provided by the rules of the C++ language on [lifetime](https://en.cppreference.com/w/cpp/language/lifetime). Temporary objects are guaranteed to last as least as long as their enclosing function call scope. 

Additionally (continuing from IRC) the `stat()` function call has no requirement that the `pathname` parameter exist longer than the duration of the function call.

> The following patch should fix this.

Thanks! Please feel free to submit that as a Pull Request and we can test it and merge it if it solves the problem.

**Comment by WickedSmoke** [comment]
I seem to recall problems in the past (with QString -> const char*) where the object goes away before the call because the object is not what gets passed to the function.

Can a separate pull request be skipped for such a trivial fix?

**Comment by impaktor** [comment]
> Can a separate pull request be skipped for such a trivial fix?

There's three options as I see it:
1. you PR it
2. we copy the patch and apply on the source
3. we PR it. (actually, if I did 2, I would open it as a PR, rather than push directly to master.

If it's the case you need help with github, we can PR it for you, but I assume you know how to do it, based on your code skill.

**Comment by WickedSmoke** [comment]
I'm not going to clone the project on Github at this time, so please use the patch as you will.
