### ISSUE TITLE
default_cockpit_norm.png missing from models/cockpits/default_cockpit/

### ISSUE THREAD

**Issue by fluffyfreak** [pioneerspacesim/pioneer#5960]
### Observed behaviour
> Info: LoadSurfaceFromFile: models/cockpits/default_cockpit/default_cockpit_norm.png: could not read file

It looks like the default_cockpit does not have this normal map committed but it is referenced within the `default_cockpit.model` 

### Expected behaviour
Either the file needs adding or the reference needs removing

### Steps to reproduce
Load the game, enable cockpit in options, start a new game and look at the output

__My pioneer version (and OS):__ Latest [Git version](https://github.com/pioneerspacesim/pioneer/commit/5e06ba6473b66ee5dfc2fcffde1df323bc62867a) on Windows and Raspberry Pi

__My output.txt (required)__
[output.txt](https://github.com/user-attachments/files/17687849/output.txt)

**Comment by bszlrd** [comment]
Oh, I'll check that
