### ISSUE TITLE
Crash/assert when starting new game other than Mars

### ISSUE THREAD

**Issue by fluffyfreak** [pioneerspacesim/pioneer#5969]
### Observed behaviour
Launch Pioneer, choose "New Game" at the menu, select "Start at New Hope" from the profile drop-down and you get the following assert. 
![PioneerLuaNewGameCrash](https://github.com/user-attachments/assets/7f51c42a-d188-4574-a19e-5abc3caf86c0)

If you accept these you'll receive another and then a warning and an error before Pioneer quits out.

It looks like an issue with an EquipSet slot

### Expected behaviour
Not expected to assert and crash 😁

__My pioneer version (and OS):__
Windows 10, 2668aa861
Also seen on Raspberry Pi.

__My output.txt (required) and game save (optional, but recommended)__

[output.txt](https://github.com/user-attachments/files/17787435/output.txt)

**Comment by Web-eWorks** [comment]
Ah, you weren't here for the discussion - this is intentional and waiting on @Gliese852 to finish porting the new-game-window to EquipSet v2. I merged the branch to allow other contributors to work in parallel on it rather than be completely blocked.

**Comment by fluffyfreak** [comment]
Ah my apologies I must have missed that.

**Comment by fluffyfreak** [comment]
I do have a "quick fix" for it locally to treat the assert as an if-then block instead which allows me to start on New Hope

**Comment by fluffyfreak** [comment]
[diff.txt](https://github.com/user-attachments/files/17787539/diff.txt)

**Comment by Web-eWorks** [comment]
> Ah my apologies I must have missed that.

No apologies necessary! It's good to have this tracked in a standalone issue so we don't forget about it :smile:

> I do have a "quick fix" for it locally

I'll leave it to @Gliese852 to decide whether he wants to merge the above and rebase his in-progress work ontop of that, or just hold off until the "full" fix is done.

**Comment by Gliese852** [comment]
My in-progress work rebased here easily and pleasantly. I hope the full fix won’t take too long to arrive.
