### ISSUE TITLE
Error during buying canon in system Anaphi

### ISSUE THREAD

**Issue by LuxusIX** [pioneerspacesim/pioneer#5987]
### Observed behaviour

Wanted to buy a new 2MV(speed fire) canon
but it buged
### Steps to reproduce
Go to system Anaphi,go to Thien facility or Cakir port, try to buy to heavy Canon who's has a weight that will barely complete the maximum weight of the ship
 Example: you have 7t free, so buy a cannon that weighs 7t

__My pioneer version (and OS):__
game version: pioneer 20240710
OS version : Arch Linux x86_64   6.11.7-arch1-1

__My output.txt (required) and game save (optional, but recommended)__

[output.txt](https://github.com/user-attachments/files/17933594/output.txt)

**Comment by impaktor** [comment]
> game version: pioneer 20240710

The entire equipment system has been ripped out and replaced since then, thus whatever bug it be, it be dead now (likely)

**Comment by LuxusIX** [comment]
> > game version: pioneer 20240710
> 
> The entire equipment system has been ripped out and replaced since then, thus whatever bug it be, it be dead now (likely)

I use the last release which dates from July 2024
How can it be possible to steal it there?

**Comment by impaktor** [comment]
We're not going to maintain code that no longer exists in the master branch. Since the July version that you're playing, that code has been re-written.  

You can compile from our master branch, and see that equipment now works differently (has volume, mass, mass in kg, slot system is different, buy/sell confirmation is different)

**Comment by impaktor** [comment]
> In which deposit code has been changed?
> And why did you abandon this code?

Code changes because the game is under constant development to improve the game. This fall the equipment code was re-written. You can see the development history [here](https://raw.githubusercontent.com/pioneerspacesim/pioneer/refs/heads/master/Changelog.txt)

**Comment by LuxusIX** [comment]
> > In which deposit code has been changed?
> > And why did you abandon this code?
> 
> Code changes because the game is under constant development to improve the game. This fall the equipment code was re-written. You can see the development history [here](https://raw.githubusercontent.com/pioneerspacesim/pioneer/refs/heads/master/Changelog.txt)

Ohh
I understand now!
You've changed the main code!
 But there's no official release yet!


> EDIT: removed duplicate post
Thanks! 

_PS: you're Impaktor, the main and lead maintainer of Pioneer, nice to meet you sir! _

**Comment by impaktor** [comment]
> But there's no official release yet!

You can download a build from the "Actions" tab from different branches (2nd column labels them). I'd recommend the build artifacts from 'master' branch. You can also build it from source yourself. If you build it using AUR, you should have all the dependencies already installed (unless removed after AUR build done).

I'm closing this for now, under the assumption this particular bug is in code we no longer maintain.

Please feel free to open new bug report on equipment from a more recent pioneer build (November), or bugs not related to equipment in your current July release.
