### ISSUE TITLE
Vatakara missing it's shield model

### ISSUE THREAD

**Issue by fluffyfreak** [pioneerspacesim/pioneer#5989]
### Observed behaviour
As seen in the Visual Studio debug output
>Exception thrown at 0x00007FFB04D0B699 in pioneer.exe: Microsoft C++ exception: SceneGraph::LoadingError at memory location 0x00000046D10FEAE8.
Exception thrown at 0x00007FFB04D0B699 in pioneer.exe: Microsoft C++ exception: ModelCache::ModelNotFoundException at memory location 0x00000046D10FEE78.

This is caused the missing model file `vatakara_shield`, and  `\data\models\ships\malabar\vatakara_shield.dae` is missing.
The file needs to have the name `vatakara_shield.dae` because the lookup is done based on this line in `ShipType.cpp`:
> shieldName = data.value("shield_model", modelName + "_shield");

### Expected behaviour
No exception thrown and the file `vatakara_shield.dae` is loaded

### Steps to reproduce
Just load the game, perhaps use the modelviewer to test that the shield works

__My pioneer version (and OS):__
Off on a branch from the latest Git but very recent, Windows 10

__My output.txt (required) and game save (optional, but recommended)__
No `output.txt` supplied because it doesn't log to it so there's nothing to show. I had to debug it via MSVC to gather the above info.

**Comment by bszlrd** [comment]
Hmm, that should use the malabar shield model. On it.

**Comment by fluffyfreak** [comment]
Yeah but it can't because it loads by name, and it builds the name from the modelname, so it's "vatakara" + "_shield"
