### ISSUE TITLE
Nethack style #conduct (also has implications for reputation)

### ISSUE THREAD

**Issue by johnbartholomew** [pioneerspacesim/pioneer#663]
This is a long term design/feature request. Mentioned on IRC a couple of times (logs below).

NetHack's [#conduct](http://nethack.wikia.com/wiki/Conduct) is a set of challenges that you can attempt while playing. These are things like "You have been a pacifist." They're not active (you don't go into a menu anywhere and pick a challenge to try), and they're not binding (just because you've been a pacifist in the game so far doesn't in any way prevent you from attacking a monster now). The game just keeps track of various events and statistics about the player's actions.

I'd like to see this idea in Pioneer. The game should keep track of lots of statistics about what the player does (stats are usually pretty cheap to keep, so we should just track whatever stats we can think of), and then we can have achievements and conduct. Some examples of possible Pioneer conduct and achievements:
- Never used autopilot
- Never used set-speed
- Won all battles
- Never landed on a planet
- Never docked in a space station
- Only used main thruster
- Never used external view
- Made a profit on every journey
- Lived for a million (virtual) years
- Never cheated (never used the Lua console)
- Never fired a weapon

Keeping stats on player actions has other possible uses as well, in particular it can be used in a reputation system. If you never (or only rarely) run away from a fight you might get a reputation as being tough or violent. If you reliably make profits on trading runs you might get a reputation as being a good trader. If you always make deliveries quickly you might get a reputation that allows you to get more lucrative delivery contracts.

```
Oct 13
<jpabx> re: nethack. I want Pioneer to keep a lot of stats on player actions to get a nethack style #conduct list
<jpabx> (never used autopilot; never used set-speed; won all battles; never landed on a planet; never docked in a space station; only used main thruster; never used external view; made a profit on every journey; etc)
<s20dan> "distance traveled" :)
<kko_> "never used time acceleration"
<Ae_1> lol
<matthewfarmery> would take forever to get anyway without time acceleration, 
<Ae_1> that was the joke:)
<matthewfarmery> I know
<matthewfarmery> leave your computer on for a year, and it might just get somewhere
<Ae_1> 'million virtual years'

Oct 14
<jpab> I want Pioneer #conduct though, as I've said before
<Brianetta> jpab: That's worth an issue
<Brianetta> Might be able to code that in Lua already
<jpab> well it's almost entirely stat tracking -- most of those stats will have to be exposed through the core I imagine
<Brianetta> although conduct() will by necessity never show "never used console"
<jpab> actually stat tracking of the sort I'm thinking of might be a good way of doing reputation too
<Brianetta> jpab: If we merge that with my musings on a GURPS-style character sheet, we're set up for everything like that
<Brianetta> self-quote from earlier: "Roll under your charisma to get that deal"
<_robn> This matches well with modifier-based equipment
<Brianetta> with a character sheet for each crew member (or applicant)
<Brianetta> Player can't see the actual sheet
<Brianetta> but it will influence the answers inteh BBS ad
<_robn> Yay, engine mod / crew with +10% hyperspace range
```

**Comment by Web-eWorks** [comment]
Closing as unimplemented and inactive; feature requests and discussion should go on the [forum](https://pioneerspacesim.net/forum), as we use Github for tracking actively-developed features and issues with currently-implemented functionality.

Thank you @johnbartholomew for all the lovely feature requests; we're cleaning house right now, but we'd love it if you could re-open some of these on the forum for further discussion!
