### ISSUE TITLE
lights

### ISSUE THREAD

**Issue by dewasha** [pioneerspacesim/pioneer#746]
I like the lights of the ship could disable and enable

thanks

**Comment by Web-eWorks** [comment]
While I too would love a better implementation of ship navlights and general lighting, the realization of that dream lies well in the future.

Closing as unimplemented; feature requests and discussion should go on the [forum](https://pioneerspacesim.net/forum), as we use Github for tracking actively-developed features and issues with currently-implemented functionality.

If you'd like to re-open this, please instead open a new PR with an implementation of the proposed functionality, thank you!
