### ISSUE TITLE
Lua API request: Space.SpawnShipInOrbit

### ISSUE THREAD

**Issue by Brianetta** [pioneerspacesim/pioneer#759]
This would be handy:
## SpawnShipInOrbit

Create a ship and place it directly into orbit

```
 ship = Space.SpawnShipInOrbit(type, body, min, max,)
```
### Parameters

`type`      the name of the ship
`body`  the Body about which the ship should be spawned
`min`       periapsis, in km
`max`       optional apoapsis, in km, defaulting to periapsis
### Return

`ship`      a Ship object for the new ship

**Comment by nozmajner** [comment]
Isn't this got implemented for the SAR missions?

**Comment by impaktor** [comment]
There's a `SpawnShipNear` a body.

**Comment by nozmajner** [comment]
SAR missions do spawn ships in orbit, so I assume, it's a yes.
