### ISSUE TITLE
Untarget bodies when they go out of range

### ISSUE THREAD

**Issue by robn** [pioneerspacesim/pioneer#774]
Right now if you have something targeted and it gets so far away that its label wouldn't be shown (currently 1000km away for anything that isn't  a planet, star or space station), it remains targeted but can not be deselected because it no longer has a label.

I propose that targets be automatically deselected when they go out of range. For navigation targets I propose they become deselected and unselectable at the same time their label disappears (1000km). Obviously that's never for large bodies. For combat targets I propose the same functionality but when they go out of scanner range (currently 100km but possibly modifiable in the future).

Target loss should be accompanied with an appropriate message. Probably "Navigation target lost." or "Combat target lost." would be sufficient.

**Comment by Web-eWorks** [comment]
Closing as inactive and outdated; if this is still an issue in latest master after two UI refactors, please open a new issue with updated specifics!
