### ISSUE TITLE
Remove old hyperspace clouds

### ISSUE THREAD

**Issue by robn** [pioneerspacesim/pioneer#805]
Hyperspace clouds need to be removed when they're no longer needed. There are two cases:
- Arrival (blue) cloud remnants that the ship has left. These probably need a fairly short life time - perhaps a day at most?
- Departure (red) clouds need to removed once the due date has passed. This can occur if the player sticks around in the system for days after the NPC has left - long enough for the NPC to complete its jump.

**Comment by richardpl** [comment]
Looks like they disappear now.

**Comment by fluffyfreak** [comment]
True, I did some changes where they disappear after a time... cannot remember how long they last but they should disappear.
