### ISSUE TITLE
Racing Ideas

### ISSUE THREAD

**Issue by CreepyStepdad** [pioneerspacesim/pioneer#837]
I know Brianetta has been working on racing. I had an idea. To leverage Pioneer's ability to travel between stars and enter atmospheres of certain parameters, races could emulate today's long distance cross-country races like they have in Baja, Mexico. Racers could start at either a special facility that must be landed on to initiate, or start from the existing station and be tasked with reaching a certain geographic position by a certain time to qualify or for the race itself. Some races could allow hostility toward the other racers, others wouldn't. 

Checkpoints located literally anywhere would require the racer to dock, check in, and leave for the next leg. Dockside congestion could cause traffic jams at the bays.  Fuel, repairs, new parts, or all of the above could be available at the checkpoints, or it could not. The first racer to successfully dock at all checkpoints would be the winner. 

For all I know, all of this has already been thought out. But if not...

**Comment by Web-eWorks** [comment]
Thank you for the suggestion! Closing as unimplemented; feature requests and discussion should go on the [forum](https://pioneerspacesim.net/forum), as we use Github for tracking actively-developed features and issues with currently-implemented functionality.

If you'd like to re-open this, please instead open a new PR with an implementation of the proposed functionality, thank you!

**Comment by impaktor** [comment]
Well, we have an open pull request on a racing mission, all we need is some people play-testing it, I think, as I've hadn't had time to either review the code or try it out, but I suspect racing would be quite sensitive to initial conditions, making it uninteresting. Link: #4358
