### ISSUE TITLE
Terrestrial missions

### ISSUE THREAD

**Issue by draxel** [pioneerspacesim/pioneer#851]
I get a lot of enjoyment out of flying close to the surface of planets - even the ones that are supposed to be an endless sea of rusty dunes or craters.  But there isn't a lot to do besides duck and weave between mountain peaks.

Missions, at present, are almost entirely space-based, leaving planet surfaces largely unused.  A few new types of missions could provide more of a reason to explore planet surfaces: something to the effect of "A starship crashed somewhere near latitude x, longitude y on planet z.  We need you to land near the crash site, rescue the pilot, and bring him back here."  Add in the occasional danger factor ("the ship who shot him down might still be patrolling the area...") and some variations (deliver package to latitude x, longitude y on planet z discreetly, or search for unobtanium deposit around latitude x, longitude y on planet z) and planets become much more rewarding to explore.

Some rocks and villages and vegetation would not be unwelcome either... but that has already been mentioned elsewhere. :)

**Comment by richardpl** [comment]
There are already such missions available on BB.
