### ISSUE TITLE
Facilities for autopilotless flying; 180 degree turn, timed burn

### ISSUE THREAD

**Issue by damerell** [pioneerspacesim/pioneer#853]
I have been doing some autopilotless flying, and there are two things I would appreciate. One is a facility to turn the ship through exactly 180 degrees, "stem to stern". The second is a facility for using a specified thruster for a specified amount of time (and optionally ending time acceleration when the "timed burn" is complete).

**Comment by Web-eWorks** [comment]
Closing as unimplemented; feature requests and discussion should go on the [forum](https://pioneerspacesim.net/forum), as we use Github for tracking actively-developed features and issues with currently-implemented functionality.
