### ISSUE TITLE
Abort hyperspace

### ISSUE THREAD

**Issue by robn** [pioneerspacesim/pioneer#883]
@Brianetta in #879:

> Suggestion for the future: Allow the player to press a key (such as F7 again) to abort a jump whilst it's happening. Use the displayed percentage chance as the chance that your ship will end up at the destination. Otherwise, it doesn't go anywhere (whilst still having used up all the fuel). This would allow a desperate player to attempt to get somewhere more quickly. The more desperate, the earlier, and the greater the probability of failure.
> 
> Contrast with a mis-jump - here, the hyperdrive is basically putting the ship in two places and altering the probability of it being at the other place. The drive powers down naturally when that probability hits 1 (or 100%).

**Comment by Web-eWorks** [comment]
Thank you for the suggestion! Closing as unimplemented; feature requests and discussion should go on the [forum](https://pioneerspacesim.net/forum), as we use Github for tracking actively-developed features and issues with currently-implemented functionality.

**Comment by Brianetta** [comment]
How things have changed since I was the triage nurse here (-:

**Comment by impaktor** [comment]
@Brianetta you're welcome back at any time :)

**Comment by fluffyfreak** [comment]
@Brianetta 👋

**Comment by impaktor** [comment]
![](https://user-images.githubusercontent.com/619390/75339958-c5c8e100-5891-11ea-928f-2314aa0e1b59.jpg)
