### ISSUE TITLE
Button to fix camera angle on chosen object in first and/or third person

### ISSUE THREAD

**Issue by Azimech** [pioneerspacesim/pioneer#889]
Purely for enjoying visuals, I'd love a button so I won't have to use the keys or mouse when for example i want to orbit a planet with high time compression. Could be advantageous during battle when in third person, like in Bridgecommander.

**Comment by Web-eWorks** [comment]
Thank you for the suggestion! Similarly to #192, work on the camera controller is planned, but we'd rather track the details of that in very specific issues that aren't eight years old!

Closing as unimplemented; feature requests and discussion should go on the [forum](https://pioneerspacesim.net/forum), as we use Github for tracking actively-developed features and issues with currently-implemented functionality.
