### ISSUE TITLE
Lafa (-24,-1,0) has some impossible bodies

### ISSUE THREAD

**Issue by Ziusudra** [pioneerspacesim/pioneer#929]
The i 3 moon is so big that the planet it orbits and moons 1 & 2 are inside it. The orbit of moon 4 takes it inside 3 periodically. 3 also has a surface gravity of 0.000. Meanwhile moon 2 has a surface gravity of 22646.967.

**Comment by richardpl** [comment]
Does this still happens?

**Comment by Web-eWorks** [comment]
Closing this as inactive; if this is still an issue in latest master, please open a new issue with pertinent details in that case!
