### ISSUE TITLE
Tranquility Base is in the wrong location

### ISSUE THREAD

**Issue by robn** [pioneerspacesim/pioneer#938]
![](http://i.imgur.com/vG06V.png)

(Starport is on the front side in this shot)

It has the correct lat/lon in `00_sol.lua` (00°41′15″N, 23°26′00″E ie 0.6875/23.4334) but doesn't appear in the right place. The reason is that our Moon's rotation does not line up with the heightmap. Put another way, 0° doesn't match).

We could fudge around it with a rotational offset paramater, but since its only required for terrains with an explicit heightmap, we might as well just fix it in the raw data.

**Comment by Bodasey** [comment]
old one - no such problems considered in actual master branch versions.

**Comment by Web-eWorks** [comment]
The moon is using heightmapV2 for it's texturing, which I believe fixes the issue. Closing this, will reopen if someone *really* cares about it.
