### ISSUE TITLE
Monsters under the bed!

### ISSUE THREAD

**Issue by Brianetta** [pioneerspacesim/pioneer#987]
So I was following traders around, seeing how they did. The one I was following landed, so I followed it down and docked at Dante's Base. On the way down I realised that I couldn't see the Caribou that I was following on the pad. They're hard to miss. Next, I noticed its registration, on the pad where I was cleared.

So, I took a look underneath the pad, and look what I found!
![Imgur](http://i.imgur.com/gEMHz.png)

**Comment by fluffyfreak** [comment]
Docking has been rewritten since this bug was reported and we have different stations now. Closing.
